# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Debezium
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  Debezium is an open source distributed platform for change data capture.
  Start it up, point it at your databases, and your apps can start responding
  to all of the inserts, updates, and deletes that other apps commit to your
  databases. Debezium is durable and fast, so your apps can respond quickly
  and never miss an event, even when things go wrong.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://debezium.io" # the base hostname & protocol for your site, e.g. http://example.com
# Google Analytics
google_analytics: UA-76464546-1
twitter_username: debezium ‏
github_username:  debezium
github_fork_url: "https://github.com/debezium/debezium.github.io"

# Build settings
markdown: kramdown
theme: minima

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives
  - jekyll-minifier 

# Pages permalink
defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: /blog/:year/:month/:day/:title/

# Excerpt separator
excerpt_separator: "+++<!-- more -->+++"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ANTORA.md
  - CONTRIBUTING.md
  - LICENSE.txt
  - playbook.yml
  - playbook_author.yml
  - README.md
  - Rakefile
  
keep_files: [documentation] 

# Collection configurations
collections:
  pages:
    output: true
    permalink: /:name  
  posts: 
    output: true
    permalink: /blog/:year/:month:/:day/:title/

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)

  
  sort_reverse: true
  sort_field: 'date'

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title'
  trail:
      before: 2
      after: 2
      
# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: Debezium

feed:
  posts_limit: 20
  
# Integrations
integrations:
  - id: java
    name: Java
  - id: connect
    name: Kafka Connect
  - id: mysql
    name: MySQL
  - id: mongodb
    name: MongoDB
  - id: postgresql
    name: PostgreSQL
  - id: oracle
    name: Oracle
  - id: sqlserver
    name: SQL Server
  - id: cassandra
    name: Cassandra
  - id: db2
    name: Db2
  - id: vitess
    name: Vitess
