---
layout: page-menu
title: Debezium Roadmap
permalink: /roadmap/
---
:linkattrs:
:icons: font
:source-highlighter: highlight.js

This page describes the roadmap for upcoming work on Debezium.

Debezium is community-driven and as such the roadmap constantly evolves to reflect the users needs and contributions.
You can find a fine-grained list of planned issues and feature requests in our https://issues.redhat.com/browse/DBZ[issue tracker],
but this page is a good starting point to see where we are going.

This roadmap is subject to changes.
Please get https://groups.google.com/forum/#!forum/debezium[in touch] if you think anything important is missing on the roadmap.

[NOTE]
====
The Debezium community pursues a time-boxed release scheme: minor releases (1.2, 1.3, etc.) are done at the end of every quarter,
with preview releases (1.3.0.Alpha1, 1.3.0.Beta1, etc.) every three weeks.
As our engineering capacity is limited, we're focusing our efforts on a single release line at a time (e.g. 1.3),
i.e. patch releases for the current stable minor release (e.g. 1.2.1.Final) are done in case of critical bug fixes only.
====

== 3.5: January - March 2026

* [Core] Cross-connector SPI for message / transaction buffers
* [Core] Snapshotting single tables using multiple threads for higher throughput
* [Oracle] Move LogMiner reader to a dedicated thread apart from event processing loop thread
* [Debezium Server] Cloud storage sinks
* [Debezium Server] PoC to support clustering
* [Debezium Server] Source connector for Milvus
* [Debezium Server] Source connector for Qdrant
* [Quarkus Extension] Advanced filtering support
* [Quarkus Extension] Support for Oracle 19c+
* [Platform] Integrate documentation for better user experience
* [Platform] Component descriptors/registry

== 3.6: April - June 2026

* [Core] Micrometer monitoring using OpenTelemetry
* [Core] Remove dependency on Kafka Connect APIs
* [Debezium Server] CLI support
* [Quarkus Extension] CLI support
* [Platform] Monitor and alerting
* [Platform] Guided workflow for modify table include lists
* [Testing] Framework to fully test Platform (functional and visual components)

== 3.7: July - September 2026

* [Core] Alternative persistent stores for `ReselectPostProcessor`
* [Connectors] A new source connector for a graph database (TBD)
* [Connectors] Maven archetype for Debezium connector development
* [Oracle] Capture changes from multiple Pluggable Databases using a single deployment
* [Debezium Server] First-class support for Iceberg sink
* [Platform] Incremental snapshot progress notifications
* [Platform] Dispatch K8 events from Debezium operator
* [AI] New PyDebeziumAI

== 3.8: October - December 2026

* [Connectors] New ElasticSearch sink (Kafka and Debezium Server)
* [Connectors] New SQLite source connector
* [Platform] Provide Auth and AuthZ via Identity Access Management

== Future Releases

* Source connector for InfluxDB time series database
* Debezium Server Fluss sink
* Debezium Server WASM sink
* Introduce an SPI to reduce memory footprint for multi-tenant databases with identical schemas
* Design/Implement user-friendly offset manipulation (i.e, start at a specific position in the transaction logs)
* Provide a Debezium-specific SPI for describing change event schemas
* API/SPI allowing to implement custom connectors on the foundations of Debezium
* Exploration of creating aggregated events, based on the streams/data from multiple tables, so to enable use cases which need to incorporate data from multiple tables into a single output structure (e.g. an Elasticsearch document containing order and orderline info)
* Support for Infinispan as a source
* Allow to propagate custom contextual data in change messages (e.g. the business user doing a certain change)
* Provide more detailed monitoring information about Debezium's internal state and health via JMX (e.g. to spot loss of DB connection while the connector still is running)
* Explore publication of change events via reactive data streams (on top of embedded connector)
* New implementation of the Debezium embedded engine independent of Kafka Connect APIs
* Read-only incremental snapshot for SQL Server and Oracle
* Create PoC for implementing sagas (long-running business transactions spanning multiple (micro-)services) using CDC and the outbox pattern
* Add schema history compaction tool
** Incremental Snapshot interface
** Quick-start connector deployment
** Support varied Kafka Connect and Debezium versions
** Make storage configurable at runtime
* Debezium Operator
** Improved Observability and Metrics
** R&D to consider multitasking support with Debezium Server
** Integration with Distribution Builder

== Past Releases

Please see the link:/releases[releases overview] page to learn more about the contents of past Debezium releases.
