---
layout: page-menu
title: Debezium Roadmap
permalink: /roadmap/
---
:linkattrs:
:icons: font
:source-highlighter: highlight.js

This page describes the roadmap for upcoming work on Debezium.

Debezium is community-driven and as such the roadmap constantly evolves to reflect the users needs and contributions.
You can find a fine-grained list of planned issues and feature requests in our https://issues.redhat.com/browse/DBZ[issue tracker],
but this page is a good starting point to see where we are going.

This roadmap is subject to changes.
Please get https://groups.google.com/forum/#!forum/debezium[in touch] if you think anything important is missing on the roadmap.

[NOTE]
====
The Debezium community pursues a time-boxed release scheme: minor releases (1.2, 1.3, etc.) are done at the end of every quarter,
with preview releases (1.3.0.Alpha1, 1.3.0.Beta1, etc.) every three weeks.
As our engineering capacity is limited, we're focusing our efforts on a single release line at a time (e.g. 1.3),
i.e. patch releases for the current stable minor release (e.g. 1.2.1.Final) are done in case of critical bug fixes only.
====

== 2.7 - June 2024

* Official MariaDB connector
* Db2 z/OS source connector
* Introduce an SPI to reduce memory footprint for multi-tenant databases with identical schemas
* R&D for read-only incremental snapshots for other relational connectors
* R&D to determine feasibility of using SQL Server transaction logs rather than capture instances
* Design/Implement user-friendly offset manipulation (i.e, start at a specific position in the transaction logs)
* Streaming from MongoDB collections
* Sink connector for MongoDB
* Additional monitoring - Quantimeter
* Expand Oracle 23c support (pending Oracle's EE release of 23c)
* New Debezium UI R&D for integration with Debezium Server and Operator
* Debezium Operator promoted to stable

== 3.0 - September 2024

* Java 17 baseline
* Kafka 3.1 minimum baseline support
* Source connector for InfluxDB time series database
* New off-heap Oracle transaction buffer implementations, more details soon.
* Exactly-Once support for other connectors
* Remove deprecated code
* Implement read-only incremental snapshots for relational connectors
* And much more...

== 3.1 - December 2024

* Oracle 12c support sunset (best-effort moving forward).
* Create PoC for implementing sagas (long-running business transactions spanning multiple (micro-)services) using CDC and the outbox pattern
* Explore and provide building blocks for implementing CQRS architectures based on change data streams

== Future Releases

* Add schema history compaction tool
* Provide a Debezium-specific SPI for describing change event schemas
* API/SPI allowing to implement custom connectors on the foundations of Debezium
* Exploration of creating aggregated events, based on the streams/data from multiple tables, so to enable use cases which need to incorporate data from multiple tables into a single output structure (e.g. an Elasticsearch document containing order and orderline info)
* Support for Infinispan as a source
* Allow to propagate custom contextual data in change messages (e.g. the business user doing a certain change)
* Provide more detailed monitoring information about Debezium's internal state and health via JMX (e.g. to spot loss of DB connection while the connector still is running)
* Explore publication of change events via reactive data streams (on top of embedded connector)
* New implementation of the Debezium embedded engine independent of Kafka Connect APIs
* Debezium UI (Legacy) - New CLI tooling
** Incremental Snapshot interface
** Quick-start connector deployment
** Support varied Kafka Connect and Debezium versions
** Offset manipulation
* Debezium Operator
** Improved Observability and Metrics
** R&D to consider multitasking support with Debezium Server
** Integration with Distribution Builder

== Past Releases

Please see the link:/releases[releases overview] page to learn more about the contents of past Debezium releases.
