= Release Notes for Debezium 0.10
:awestruct-layout: doc
:awestruct-documentation_version: "0.10"
:toc:
:toc-placement: macro
:toclevels: 1
:sectanchors:
:linkattrs:
:icons: font

All notable changes for Debezium releases are documented in this file.
Release numbers follow http://semver.org[Semantic Versioning].

toc::[]

[[release-0-10-0-cr1]]
== *Release 0.10.0.CR1* _(September 10th, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12342542[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.3.0 and has been tested with version 2.3.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.10.0.CR1 from any of the earlier 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.10.0.CR1 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.10.0.CR1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

The ProtoBuf library use by PostgreSQL plugin has been https://issues.jboss.org/browse/DBZ-1390[upgraded].

SQL Server connector now supports Kafka Connect's https://issues.jboss.org/browse/DBZ-1419[temporal datatypes].
At the same time the default temporal mode is no longer `adaptive_time_microseconds` but `adaptive`.
Mode `adaptive_time_microseconds` is no longer supported.

=== New Features

* Replace YAML Dependency with Property File in Cassandra Connector https://issues.jboss.org/browse/DBZ-1406[DBZ-1406]
* Support Connect date/time precision https://issues.jboss.org/browse/DBZ-1419[DBZ-1419]
* Exported snapshots are supported by PostgreSQL 9.4+ https://issues.jboss.org/browse/DBZ-1440[DBZ-1440]
* Enhance Postgresql & Mysql Docker example images with some Spatial geometry  https://issues.jboss.org/browse/DBZ-1459[DBZ-1459]


=== Fixes

This release includes the following fixes:

* Date conversion broken if date more than 3000 year https://issues.jboss.org/browse/DBZ-949[DBZ-949]
* Overflowed Timestamp in Postgres Connection https://issues.jboss.org/browse/DBZ-1205[DBZ-1205]
* Debezium does not expect a year larger than 9999 https://issues.jboss.org/browse/DBZ-1255[DBZ-1255]
* ExportedSnapshotter and InitialOnlySnapshotter should not always execute a snapshot. https://issues.jboss.org/browse/DBZ-1437[DBZ-1437]
* Source Fields Not Present on Delete Rewrite https://issues.jboss.org/browse/DBZ-1448[DBZ-1448]
* NPE raises when a new connector has nothing to commit https://issues.jboss.org/browse/DBZ-1457[DBZ-1457]
* MongoDB connector throws NPE on "op=n" https://issues.jboss.org/browse/DBZ-1464[DBZ-1464]


=== Other changes

This release includes also other changes:

* Upgrade ProtoBuf dependency https://issues.jboss.org/browse/DBZ-1390[DBZ-1390]
* Engine does not stop on Exception https://issues.jboss.org/browse/DBZ-1431[DBZ-1431]
* Create "architecture" and "feature" pages https://issues.jboss.org/browse/DBZ-1458[DBZ-1458]



[[release-0-10-0-beta4]]
== *Release 0.10.0.Beta4* _(August 16th, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12342545[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.3.0 and has been tested with version 2.3.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.10.0.Beta4 from any of the earlier 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.10.0.Beta4 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.10.0.Beta4 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

The default format of the message values produced by the link:/docs/configuration/outbox-event-router/[outbox event router] has been https://issues.jboss.org/browse/DBZ-1385[changed].
It will solely contain the value of the `payload` column by default.
In order to add the `eventType` value that previously was part of the message value, use the "additional field" configuration option with a placement option of `envelope`.
In this case, the message value will be a complex structure containing the `payload` key and one additional key for each further field.

=== New Features

* Implement a CDC connector for Apache Cassandra https://issues.jboss.org/browse/DBZ-607[DBZ-607]
* Support "Exported Snapshots" feature for taking lockless snapshots with Postgres https://issues.jboss.org/browse/DBZ-1035[DBZ-1035]
* Snapshot Order of tables https://issues.jboss.org/browse/DBZ-1254[DBZ-1254]
* Add ability to insert fields from source struct in ExtractNewRecordState SMT https://issues.jboss.org/browse/DBZ-1395[DBZ-1395]


=== Fixes

This release includes the following fixes:

* Debezium for MySQL fails on GRANT DELETE ON <table> https://issues.jboss.org/browse/DBZ-1411[DBZ-1411]
* Debezium for MySQL tries to flush a table for a database not in the database whitelist https://issues.jboss.org/browse/DBZ-1414[DBZ-1414]
* Table scan is performed anyway even if snapshot.mode is set to initial_schema_only https://issues.jboss.org/browse/DBZ-1417[DBZ-1417]
* SMT ExtractNewDocumentState does not support Heartbeat events https://issues.jboss.org/browse/DBZ-1430[DBZ-1430]
* Postgres connector does not honor `publication.name` configuration https://issues.jboss.org/browse/DBZ-1436[DBZ-1436]


=== Other changes

This release includes also other changes:

* Issue with debezium embedded documentation https://issues.jboss.org/browse/DBZ-393[DBZ-393]
* Refactor Postgres connector to be based on new framework classes https://issues.jboss.org/browse/DBZ-777[DBZ-777]
* Don't obtain new connection each time when getting xmin position https://issues.jboss.org/browse/DBZ-1381[DBZ-1381]
* Unify handling of attributes in EventRouter SMT https://issues.jboss.org/browse/DBZ-1385[DBZ-1385]
* DockerHub: show container specific README files https://issues.jboss.org/browse/DBZ-1387[DBZ-1387]
* Remove unused dependencies from Cassandra connector https://issues.jboss.org/browse/DBZ-1424[DBZ-1424]
* Simplify custom engine name parsing grammar https://issues.jboss.org/browse/DBZ-1432[DBZ-1432]

[[release-0-10-0-beta3]]
== *Release 0.10.0.Beta3* _(July 23rd, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12342463[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.3.0 and has been tested with version 2.3.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.10.0.Beta3 from any of the earlier 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.10.0.Beta3 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.10.0.Beta3 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

The value of heartbeat messages has been https://issues.jboss.org/browse/DBZ-1363[changed], it now contains a field with the timestamp of the heartbeat.
Note that the message format of heartbeat messages is considered an implementation detail of Debezium, i.e. its format may be altered incompatibly and consumers should not rely on any specific format.

=== New Features

* Handle tables without primary keys https://issues.jboss.org/browse/DBZ-916[DBZ-916]
* Define exposed connector metrics in MySQL https://issues.jboss.org/browse/DBZ-1120[DBZ-1120]
* Set heartbeat interval for the binlog reader https://issues.jboss.org/browse/DBZ-1338[DBZ-1338]
* Outbox router should skip heartbeat messages by default https://issues.jboss.org/browse/DBZ-1388[DBZ-1388]
* Introduce number ofEventsInError metric https://issues.jboss.org/browse/DBZ-1222[DBZ-1222]
* Add option to skip table locks when snapshotting https://issues.jboss.org/browse/DBZ-1238[DBZ-1238]
* Explore built-in logical decoding added in Postgres 10 https://issues.jboss.org/browse/DBZ-766[DBZ-766]
* Support deletion events in the outbox routing SMT https://issues.jboss.org/browse/DBZ-1320[DBZ-1320]
* Expose metric for progress of DB history recovery https://issues.jboss.org/browse/DBZ-1356[DBZ-1356]


=== Fixes

This release includes the following fixes:

* Incorrect offset may be committed despite unparseable DDL statements https://issues.jboss.org/browse/DBZ-599[DBZ-599]
* SavePoints are getting stored in history topic https://issues.jboss.org/browse/DBZ-794[DBZ-794]
* delete message "op:d" on tables with unique combination of 2 primary keys  = (composite keys) ,  the d records are not sent  https://issues.jboss.org/browse/DBZ-1180[DBZ-1180]
* When a MongoDB collection haven't had activity for a period of time an initial sync is triggered https://issues.jboss.org/browse/DBZ-1198[DBZ-1198]
* Restore compatibility with Kafka 1.x https://issues.jboss.org/browse/DBZ-1361[DBZ-1361]
* no viable alternative at input 'LOCK DEFAULT' https://issues.jboss.org/browse/DBZ-1376[DBZ-1376]
* NullPointer Exception on getReplicationSlotInfo for Postgres https://issues.jboss.org/browse/DBZ-1380[DBZ-1380]
* CHARSET is not supported for CAST function https://issues.jboss.org/browse/DBZ-1397[DBZ-1397]
* Aria engine is not known by Debezium parser https://issues.jboss.org/browse/DBZ-1398[DBZ-1398]
* Debezium does not get the first change after creating the replication slot in PostgreSQL https://issues.jboss.org/browse/DBZ-1400[DBZ-1400]
* Built-in database filter throws NPE https://issues.jboss.org/browse/DBZ-1409[DBZ-1409]
* Error processing RDS heartbeats https://issues.jboss.org/browse/DBZ-1410[DBZ-1410]
* PostgreSQL Connector generates false alarm for empty password https://issues.jboss.org/browse/DBZ-1379[DBZ-1379]


=== Other changes

This release includes also other changes:

* Developer Preview Documentation https://issues.jboss.org/browse/DBZ-1284[DBZ-1284]
* Upgrade to Apache Kafka 2.3 https://issues.jboss.org/browse/DBZ-1358[DBZ-1358]
* Stabilize test executions on CI https://issues.jboss.org/browse/DBZ-1362[DBZ-1362]
* Handling tombstone emission option consistently https://issues.jboss.org/browse/DBZ-1365[DBZ-1365]
* Avoid creating unnecessary type metadata instances; only init once per column. https://issues.jboss.org/browse/DBZ-1366[DBZ-1366]
* Fix tests to run more reliably on Amazon RDS https://issues.jboss.org/browse/DBZ-1371[DBZ-1371]



[[release-0-10-0-beta2]]
== *Release 0.10.0.Beta2* _(June 27th, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12342231[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.3.0 and has been tested with version 2.3.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.10.0.Beta2 from any of the earlier 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.10.0.Beta2 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.10.0.Beta2 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.


=== New Features

* Protect against invalid configuration https://issues.jboss.org/browse/DBZ-1340[DBZ-1340]
* Make emission of tombstone events configurable https://issues.jboss.org/browse/DBZ-835[DBZ-835]
* Support HSTORE array types https://issues.jboss.org/browse/DBZ-1337[DBZ-1337]


=== Fixes

This release includes the following fixes:

* Events for TRUNCATE TABLE not being emitted https://issues.jboss.org/browse/DBZ-708[DBZ-708]
* Connector consumes huge amount of memory https://issues.jboss.org/browse/DBZ-1065[DBZ-1065]
* Exception when starting the connector on Kafka Broker 0.10.1.0 https://issues.jboss.org/browse/DBZ-1270[DBZ-1270]
* Raise warning when renaming table causes  it to be captured or not captured any longer https://issues.jboss.org/browse/DBZ-1278[DBZ-1278]
* no viable alternative at input 'ALTER TABLE `documents` RENAME INDEX' https://issues.jboss.org/browse/DBZ-1329[DBZ-1329]
* MySQL DDL parser - issue with triggers and NEW https://issues.jboss.org/browse/DBZ-1331[DBZ-1331]
* MySQL DDL parser - issue with COLLATE in functions https://issues.jboss.org/browse/DBZ-1332[DBZ-1332]
* Setting "include.unknown.datatypes" to true works for streaming but not during snapshot https://issues.jboss.org/browse/DBZ-1335[DBZ-1335]
* PostgreSQL db with materialized view failing during snapshot https://issues.jboss.org/browse/DBZ-1345[DBZ-1345]
* Switch RecordsStreamProducer to use non-blocking stream call https://issues.jboss.org/browse/DBZ-1347[DBZ-1347]
* Can't parse create definition on the mysql connector https://issues.jboss.org/browse/DBZ-1348[DBZ-1348]
* String literal should support utf8mb3 charset https://issues.jboss.org/browse/DBZ-1349[DBZ-1349]
* NO_AUTO_CREATE_USER sql mode is not supported in MySQL 8 https://issues.jboss.org/browse/DBZ-1350[DBZ-1350]
* Incorrect assert for invalid timestamp check in MySQL 8 https://issues.jboss.org/browse/DBZ-1353[DBZ-1353]


=== Other changes

This release includes also other changes:

* Add to FAQ what to do on offset flush timeout https://issues.jboss.org/browse/DBZ-799[DBZ-799]
* Update MongoDB driver to 3.10.1 https://issues.jboss.org/browse/DBZ-1333[DBZ-1333]
* Fix test for partitioned table snapshot https://issues.jboss.org/browse/DBZ-1342[DBZ-1342]
* Enable PostGIS for Alpine 9.6 https://issues.jboss.org/browse/DBZ-1351[DBZ-1351]
* Fix description for state of Snapshot https://issues.jboss.org/browse/DBZ-1346[DBZ-1346]
* Remove unused code for alternative topic selection strategy https://issues.jboss.org/browse/DBZ-1352[DBZ-1352]


[[release-0-10-0-beta1]]
== *Release 0.10.0.Beta1* _(June 11th, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12342194[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.2.1 and has been tested with version 2.2.1 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.10.0.Beta1 from any of the earlier 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.10.0.Beta1 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.10.0.Beta1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.


=== New Features

* Issue a warning for filters not matching any table/database https://issues.jboss.org/browse/DBZ-1242[DBZ-1242]


=== Fixes

This release includes the following fixes:

* Multiple cdc entries with exactly the same commitLsn and changeLsn https://issues.jboss.org/browse/DBZ-1152[DBZ-1152]
* PostGIS does not work in Alpine images https://issues.jboss.org/browse/DBZ-1307[DBZ-1307]
* Processing MongoDB document contains UNDEFINED type causes exception with MongoDB Unwrap SMT https://issues.jboss.org/browse/DBZ-1315[DBZ-1315]
* Partial zero date datetime/timestamp will fail snapshot https://issues.jboss.org/browse/DBZ-1318[DBZ-1318]
* Default value set null when modify a column from nullable to not null https://issues.jboss.org/browse/DBZ-1321[DBZ-1321]
* Out-of-order chunks don't initiate commitTime https://issues.jboss.org/browse/DBZ-1323[DBZ-1323]
* NullPointerException when receiving noop event https://issues.jboss.org/browse/DBZ-1317[DBZ-1317]


=== Other changes

This release includes also other changes:

* Describe structure of SQL Server CDC events https://issues.jboss.org/browse/DBZ-1296[DBZ-1296]
* Upgrade to Apache Kafka 2.2.1 https://issues.jboss.org/browse/DBZ-1316[DBZ-1316]


[[release-0-10-0-alpha2]]
== *Release 0.10.0.Alpha2* _(June 3rd, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12342158[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.2.0 and has been tested with version 2.2.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.10.0.Alpha2 from any of the earlier 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.10.0.Alpha2 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.10.0.Alpha2 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

The snapshot marking has been overhauled https://issues.jboss.org/browse/DBZ-1295[DBZ-1295].
Originally the snapshot marker has been field with boolean value indicating whther the record was obtained via snapshot or not.
Now it has been turned into three state string enumeration indicating the record came from snapshot (true), is last in the snapshot (last) or is from streaming (false).

=== New Features

* "source" block for MySQL schema change events should contain db and table names https://issues.jboss.org/browse/DBZ-871[DBZ-871]
* Adhere to Dockerfile good practices https://issues.jboss.org/browse/DBZ-1279[DBZ-1279]


=== Fixes

This release includes the following fixes:

* DDL that contains `user` are unparsable by antlr https://issues.jboss.org/browse/DBZ-1300[DBZ-1300]
* Only validate history topic name for affected connectors https://issues.jboss.org/browse/DBZ-1283[DBZ-1283]


=== Other changes

This release includes also other changes:

* Replace Predicate<Column> with ColumnNameFilter https://issues.jboss.org/browse/DBZ-1092[DBZ-1092]
* Upgrade ZooKeeper to 3.4.14 https://issues.jboss.org/browse/DBZ-1298[DBZ-1298]
* Upgrade Docker tooling image https://issues.jboss.org/browse/DBZ-1301[DBZ-1301]
* Upgrade Debezium Postgres Example image to 11 https://issues.jboss.org/browse/DBZ-1302[DBZ-1302]
* Create profile to build assemblies without drivers https://issues.jboss.org/browse/DBZ-1303[DBZ-1303]
* Modify release pipeline to use new Dockerfiles https://issues.jboss.org/browse/DBZ-1304[DBZ-1304]
* Add 3rd party licences https://issues.jboss.org/browse/DBZ-1306[DBZ-1306]
* Remove unused methods from ReplicationStream https://issues.jboss.org/browse/DBZ-1310[DBZ-1310]


[[release-0-10-0-alpha1]]
== *Release 0.10.0.Alpha1* _(May 28th, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12340285[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.2.0 and has been tested with version 2.2.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.10.0.Alpha1 from any of the earlier 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.10.0.Alpha1 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.10.0.Alpha1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

All connectors now share the common source info block fields https://issues.jboss.org/browse/DBZ-596[DBZ-596].
This led to the renaming and/or change of content of some of the source fields.
We are providing an option `source.struct.version=v1` to use legacy source info block.

Unwrap SMTs have been renamed https://issues.jboss.org/browse/DBZ-677[DBZ-677] to better express their use.

MySQL connector now consistently handle `database.history.store.only.monitored.tables.ddl` for both snapshot and streaming mode https://issues.jboss.org/browse/DBZ-683[DBZ-683].
This leads to changes in the contents of database history topic.

MySQL legacy DDL parser has been removed https://issues.jboss.org/browse/DBZ-736[DBZ-736] and was fully replaced with ANTLR-based parser.

Oracle and SQL Server connectors now contain database, schema, and table names in the source info block https://issues.jboss.org/browse/DBZ-875[DBZ-875].

MongoDB now contains both database and collection name in source info block https://issues.jboss.org/browse/DBZ-1175[DBZ-1175].
The original `ns` field has been dropped.

Metric `NumberOfEventsSkipped` is now available only for MySQL connector https://issues.jboss.org/browse/DBZ-1209[DBZ-1209].

All deprecated features and configuration options https://issues.jboss.org/browse/DBZ-1234[DBZ-1234] have been removed from the codebase and are no longer available.

Outbox routing SMT option names have been renamed to follow a consistent naming schema https://issues.jboss.org/browse/DBZ-1289[DBZ-1289].


=== New Features

* Excessive warnings in log about column missing charset https://issues.jboss.org/browse/DBZ-844[DBZ-844]
* Update JDBC (and Mongo) drivers to latest versions https://issues.jboss.org/browse/DBZ-1273[DBZ-1273]
* Support snapshot SELECT overrides for SQL Server connector https://issues.jboss.org/browse/DBZ-1224[DBZ-1224]
* Generate warning in logs if change table list is empty https://issues.jboss.org/browse/DBZ-1281[DBZ-1281]


=== Fixes

This release includes the following fixes:

* MySQL connection with client authentication does not work https://issues.jboss.org/browse/DBZ-1228[DBZ-1228]
* Unhandled exception prevents snapshot.mode : when_needed functioning https://issues.jboss.org/browse/DBZ-1244[DBZ-1244]
* MySQL connector stops working with a NullPointerException error https://issues.jboss.org/browse/DBZ-1246[DBZ-1246]
* CREATE INDEX can fail for non-monitored tables after connector restart https://issues.jboss.org/browse/DBZ-1264[DBZ-1264]
* Create a spec file for RPM for postgres protobuf plugin https://issues.jboss.org/browse/DBZ-1272[DBZ-1272]
* Last transaction events get duplicated on EmbeddedEngine MySQL connector restart https://issues.jboss.org/browse/DBZ-1276[DBZ-1276]


=== Other changes

This release includes also other changes:

* Misleading description for column.mask.with.length.chars parameter https://issues.jboss.org/browse/DBZ-1290[DBZ-1290]
* Clean up integration tests under integration-tests https://issues.jboss.org/browse/DBZ-263[DBZ-263]
* Consolidate DDL parser tests https://issues.jboss.org/browse/DBZ-733[DBZ-733]
* Document "database.ssl.mode" option https://issues.jboss.org/browse/DBZ-985[DBZ-985]
* Synchronize MySQL grammar with upstream grammar https://issues.jboss.org/browse/DBZ-1127[DBZ-1127]
* Add FAQ entry about -XX:+UseStringDeduplication JVM flag https://issues.jboss.org/browse/DBZ-1139[DBZ-1139]
* Test and handle time 24:00:00 supported by PostgreSQL https://issues.jboss.org/browse/DBZ-1164[DBZ-1164]
* Define final record format for MySQL, Postgres, SQL Server and MongoDB https://issues.jboss.org/browse/DBZ-1235[DBZ-1235]
* Improve error reporting in case of misaligned schema and data https://issues.jboss.org/browse/DBZ-1257[DBZ-1257]
* Adding missing contributors to COPYRIGHT.txt https://issues.jboss.org/browse/DBZ-1259[DBZ-1259]
* Automate contributor check during release pipeline. https://issues.jboss.org/browse/DBZ-1282[DBZ-1282]
