= Release Notes for Debezium 1.1
:awestruct-layout: doc
:awestruct-documentation_version: "1.1"
:toc:
:toc-placement: macro
:toclevels: 1
:sectanchors:
:linkattrs:
:icons: font

All notable changes for Debezium releases are documented in this file.
Release numbers follow http://semver.org[Semantic Versioning].

toc::[]

[[release-1.1.0-alpha1]]
== *Release 1.1.0.Alpha1* _(January 16th, 2020)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12344080[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.4.0 and has been tested with version 2.4.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 1.1.0.Alpha1 from any of the earlier 1.1.x, 1.0.x, 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 1.1.0.Alpha1 plugin files, and restart the connector using the same configuration.
Upon restart, the 1.1.0.Alpha1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

When using the outbox event routing SMT and configuring a column from which to obtain the Kafka record timestamp from (table.field.event.timestamp option), then that value could have been exported as milliseconds, microseconds or nanoseconds, based on the source column's definition.
As of this release, the timestamp always be exported as milliseconds (https://issues.jboss.org/browse/DBZ-1707[DBZ-1707]).

The deprecated Postgres connector option `slot.drop_on_stop` has been removed; use `slot.drop.on.stop` instead (https://issues.jboss.org/browse/DBZ-1600[DBZ-1600]).


=== New Features

* MongoDB authentication against non-admin authsource https://issues.jboss.org/browse/DBZ-1168[DBZ-1168]
* Oracle: Add support for different representations of "NUMBER" Data Type https://issues.jboss.org/browse/DBZ-1552[DBZ-1552]
* Update Mongo Java driver to version 3.12.0 https://issues.jboss.org/browse/DBZ-1690[DBZ-1690]
* Support exporting change events in "CloudEvents" format https://issues.jboss.org/browse/DBZ-1292[DBZ-1292]
* Build Quarkus extension facilitating implementations of the outbox pattern https://issues.jboss.org/browse/DBZ-1478[DBZ-1478]
* Support column masking option for Postgres https://issues.jboss.org/browse/DBZ-1685[DBZ-1685]


=== Fixes

This release includes the following fixes:

* Make slot creation in PostgreSQL more resilient https://issues.jboss.org/browse/DBZ-1684[DBZ-1684]
* SQLserver type time(4)...time(7) lost nanoseconds https://issues.jboss.org/browse/DBZ-1688[DBZ-1688]
* Support boolean as default for INT(1) column in MySQL https://issues.jboss.org/browse/DBZ-1689[DBZ-1689]
* SIGNAL statement is not recognized by DDL parser https://issues.jboss.org/browse/DBZ-1691[DBZ-1691]
* When using in embedded mode MYSQL connector fails https://issues.jboss.org/browse/DBZ-1693[DBZ-1693]
* MySQL connector fails to parse trigger DDL https://issues.jboss.org/browse/DBZ-1699[DBZ-1699]


=== Other changes

This release includes also other changes:

* Update outbox routing example https://issues.jboss.org/browse/DBZ-1673[DBZ-1673]
* Add option to JSON change event SerDe for ignoring unknown properties https://issues.jboss.org/browse/DBZ-1703[DBZ-1703]
* Update debezium/awestruct image to use Antora 2.3 alpha 2 https://issues.jboss.org/browse/DBZ-1713[DBZ-1713]

