---
layout: release-notes
title: Release Notes for Debezium 1.1
debezium-version: "1.1"
---
:toc:
:toc-placement: macro
:toclevels: 1
:sectanchors:
:linkattrs:
:icons: font

All notable changes for Debezium releases are documented in this file.
Release numbers follow http://semver.org[Semantic Versioning].

toc::[]

[[release-1.1.2-final]]
== *Release 1.1.2.Final* _(June 2nd, 2020)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12345564[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.5.0 and has been tested with version 2.5.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL, SQL Server, Cassandra or DB2 connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 1.1.2.Final from any of the earlier 1.1.x, 1.0.x, 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 1.1.2.Final plugin files, and restart the connector using the same configuration.
Upon restart, the 1.1.2.Final connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

Db2 and Oracle connectors were using database name which is fixed to configure table filters.
This is now simplified so only `<schema_name>.<table_name>` naming is used.
Db2, Oracle and SQL Server connectors were using database name which is fixed to configure column/key filters and mappers.
This is now simplified so only `<schema_name>.<table_name>.<column_name>` naming is used (https://issues.jboss.org/browse/DBZ-1312[DBZ-1312]).

Db2 connector was providing `initial_schema_only` snapshot mode.
This name was not consistent with other connectors so the mode was renamed to `schema_only` (https://issues.jboss.org/browse/DBZ-2051[DBZ-2051]).


=== New Features

There are no new features in this release.


=== Fixes

This release includes the following fixes:

* Outbox Quarkus Extension throws NPE in quarkus:dev mode https://issues.jboss.org/browse/DBZ-1966[DBZ-1966]
* [Doc] Debezium User Guide should provide example of DB connector yaml and deployment instructions https://issues.jboss.org/browse/DBZ-2011[DBZ-2011]
* MySQL alias `FLUSH TABLE` not handled https://issues.jboss.org/browse/DBZ-2047[DBZ-2047]
* DDL statement throws error if compression keyword contains backticks (``) https://issues.jboss.org/browse/DBZ-2062[DBZ-2062]
* Error and connector stops when DDL contains algorithm=instant https://issues.jboss.org/browse/DBZ-2067[DBZ-2067]
* Unable to parse MySQL ALTER statement with named primary key https://issues.jboss.org/browse/DBZ-2080[DBZ-2080]


=== Other changes

This release includes also other changes:

* Adding tests and doc updates around column masking and truncating https://issues.jboss.org/browse/DBZ-775[DBZ-775]
* Align snapshot/streaming semantics in MongoDB documentation https://issues.jboss.org/browse/DBZ-1901[DBZ-1901]
* Only top-level menu items shown for MySQL connector 1.1 docs https://issues.jboss.org/browse/DBZ-1980[DBZ-1980]
* Upgrade to Apache Kafka 2.5.0 and Confluent Platform 5.5.0 https://issues.jboss.org/browse/DBZ-1981[DBZ-1981]
* Fix broken link https://issues.jboss.org/browse/DBZ-1983[DBZ-1983]
* Avoid broken cross-book references in downstream docs https://issues.jboss.org/browse/DBZ-1999[DBZ-1999]
* Fix wrong attribute name in MongoDB connector https://issues.jboss.org/browse/DBZ-2006[DBZ-2006]
* Remove additional Jackson dependencies as of AK 2.5 https://issues.jboss.org/browse/DBZ-2076[DBZ-2076]
* Tar packages must use posix format https://issues.jboss.org/browse/DBZ-2088[DBZ-2088]
* Upgrade to Quarkus 1.5.0.Final https://issues.jboss.org/browse/DBZ-2119[DBZ-2119]



[[release-1.1.1-final]]
== *Release 1.1.1.Final* _(April 17th, 2020)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12345315[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.4.1 and has been tested with version 2.4.1 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL, SQL Server, Cassandra or DB2 connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 1.1.1.Final from any of the earlier 1.1.x, 1.0.x, 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 1.1.1.Final plugin files, and restart the connector using the same configuration.
Upon restart, the 1.1.1.Final connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.

=== New Features

* Improve documentation on WAL disk space usage for Postgres connector https://issues.jboss.org/browse/DBZ-1732[DBZ-1732]
* Add docs for mask column and truncate column features https://issues.jboss.org/browse/DBZ-1954[DBZ-1954]
* Snapshot metrics shows TotalNumberOfEventsSeen as zero https://issues.jboss.org/browse/DBZ-1932[DBZ-1932]


=== Fixes

This release includes the following fixes:

* Snapshot lock timeout setting is not documented https://issues.jboss.org/browse/DBZ-1914[DBZ-1914]
* AvroRuntimeException when publishing transaction metadata https://issues.jboss.org/browse/DBZ-1915[DBZ-1915]
* Connector restart logic throttles for the first 2 seconds https://issues.jboss.org/browse/DBZ-1918[DBZ-1918]
* Wal2json empty change event could cause NPE above version 1.0.3.final https://issues.jboss.org/browse/DBZ-1922[DBZ-1922]
* Broken internal links and anchors in documentation https://issues.jboss.org/browse/DBZ-1935[DBZ-1935]
* Dokumentation files in modules create separate pages, should be partials instead https://issues.jboss.org/browse/DBZ-1944[DBZ-1944]
* Validation of binlog_row_image is not compatible with MySQL 5.5 https://issues.jboss.org/browse/DBZ-1950[DBZ-1950]
* High CPU usage when idle https://issues.jboss.org/browse/DBZ-1960[DBZ-1960]


=== Other changes

This release includes also other changes:

* Fix typo in Quarkus Outbox extension documentation https://issues.jboss.org/browse/DBZ-1902[DBZ-1902]
* Documentation should link to Apache Kafka upstream docs https://issues.jboss.org/browse/DBZ-1906[DBZ-1906]
* Restore documentation of MySQL event structures https://issues.jboss.org/browse/DBZ-1919[DBZ-1919]
* Update snapshot.mode options in SQL Server documentation https://issues.jboss.org/browse/DBZ-1924[DBZ-1924]
* Remove obsolete metrics from downstream docs https://issues.jboss.org/browse/DBZ-1947[DBZ-1947]



[[release-1.1.0-final]]
== *Release 1.1.0.Final* _(March 23rd, 2020)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12344981[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.4.0 and has been tested with version 2.4.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL, SQL Server, Cassandra or DB2 connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 1.1.0.Final from any of the earlier 1.1.x, 1.0.x, 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 1.1.0.Final plugin files, and restart the connector using the same configuration.
Upon restart, the 1.1.0.Final connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.

=== New Features

* The Postgres connector heartbeat should optionally write back a heartbeat change to the DB https://issues.redhat.com/browse/DBZ-1815[DBZ-1815]

=== Fixes

This release includes the following fixes:

* Postgres Connector ignoring confirmed_flush_lsn and skipping ahead to latest txn https://issues.redhat.com/browse/DBZ-1730[DBZ-1730]
* Postgresql money error handling https://issues.redhat.com/browse/DBZ-1755[DBZ-1755]
* MongoDB tests not working correctly https://issues.redhat.com/browse/DBZ-1867[DBZ-1867]
* MongoDB transaction metadata topic generates extra events https://issues.redhat.com/browse/DBZ-1874[DBZ-1874]
* NullPointerException on delete in ExtractNewRecordState class https://issues.redhat.com/browse/DBZ-1876[DBZ-1876]
* MongoDB connector unrecoverable exception https://issues.redhat.com/browse/DBZ-1880[DBZ-1880]
* High log volume from: "Awaiting end of restart backoff period" logs https://issues.redhat.com/browse/DBZ-1889[DBZ-1889]
* Kafka records from one Cassandra table get published to the kafka queue of another Cassandra table https://issues.redhat.com/browse/DBZ-1892[DBZ-1892]


=== Other changes

This release includes also other changes:

* Use snapshot versions in master branch documentation https://issues.redhat.com/browse/DBZ-1793[DBZ-1793]
* Misc docs issues https://issues.redhat.com/browse/DBZ-1798[DBZ-1798]
* Outbox Quarkus Extension: Clarify default column types when using defaults. https://issues.redhat.com/browse/DBZ-1804[DBZ-1804]
* Create CI job to run OpenShift test https://issues.redhat.com/browse/DBZ-1817[DBZ-1817]
* Failing test jobs for Mongo and SQL Server due to insecure maven registry https://issues.redhat.com/browse/DBZ-1837[DBZ-1837]
* Support retriable exceptions with embedded engine https://issues.redhat.com/browse/DBZ-1857[DBZ-1857]
* Modularize Debezium logging doc https://issues.redhat.com/browse/DBZ-1861[DBZ-1861]
* Centralize closing of coordinator https://issues.redhat.com/browse/DBZ-1863[DBZ-1863]
* Assert format of commit messages https://issues.redhat.com/browse/DBZ-1868[DBZ-1868]
* Bump MongoDB java driver to the latest version 3.12.2 https://issues.redhat.com/browse/DBZ-1869[DBZ-1869]
* Add Travis CI task for MongoDB 3.2 https://issues.redhat.com/browse/DBZ-1871[DBZ-1871]
* Unstable tests for PostgreSQL https://issues.redhat.com/browse/DBZ-1875[DBZ-1875]
* Add MongoDB JMX integration tests https://issues.redhat.com/browse/DBZ-1879[DBZ-1879]



[[release-1.1.0-cr1]]
== *Release 1.1.0.CR1* _(March 11th, 2020)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12344727[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.4.0 and has been tested with version 2.4.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL, SQL Server, Cassandra or DB2 connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 1.1.0.CR1 from any of the earlier 1.1.x, 1.0.x, 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 1.1.0.CR1 plugin files, and restart the connector using the same configuration.
Upon restart, the 1.1.0.CR1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

The default value of MySQL config option `gtid.new.channel.position` was originally set to `latest` that should never be used in a production. The default value was thus set to `earliest` and the config option is scheduled for removal (https://issues.jboss.org/browse/DBZ-1705[DBZ-1705]).
The MySQL config option `event.deserialization.failure.handling.mode` was renamed to `event.processing.failure.handling.mode` to make the naming consistent with other connectors (https://issues.jboss.org/browse/DBZ-1826[DBZ-1826]).
MongoDB config option `field.renames` adds renamed field (wtih `null value`) even when the source field is missing.
This was identified as a defect and the non-present fields are no longer added (https://issues.jboss.org/browse/DBZ-1848[DBZ-1848]).

=== New Features

* Distinguish between public (API) and internal parts of Debezium https://issues.jboss.org/browse/DBZ-234[DBZ-234]
* Default `gtid.new.channel.position` to earliest https://issues.jboss.org/browse/DBZ-1705[DBZ-1705]
* Add option to skip unprocesseable event https://issues.jboss.org/browse/DBZ-1760[DBZ-1760]
* ExtractNewRecordState - add.source.fields should strip spaces from comma-separated list of fields https://issues.jboss.org/browse/DBZ-1772[DBZ-1772]
* Add support for update events for sharded MongoDB collections https://issues.jboss.org/browse/DBZ-1781[DBZ-1781]
* Useless/meaningless parameter in function https://issues.jboss.org/browse/DBZ-1805[DBZ-1805]
* Replace BlockEventQueue with Debezium ChangeEventQueue  https://issues.jboss.org/browse/DBZ-1820[DBZ-1820]
* Option to configure column.propagate.source.type on a per-type basis, not per column-name basis https://issues.jboss.org/browse/DBZ-1830[DBZ-1830]
* Support MongoDB Oplog operations as config https://issues.jboss.org/browse/DBZ-1831[DBZ-1831]
* Add app metrics for mongodb connector to jmx https://issues.jboss.org/browse/DBZ-845[DBZ-845]
* Provide SPI to override schema and value conversion for specific columns https://issues.jboss.org/browse/DBZ-1134[DBZ-1134]
* Retry polling on configured exceptions https://issues.jboss.org/browse/DBZ-1723[DBZ-1723]


=== Fixes

This release includes the following fixes:

* CDC Event Schema Doesn't Change After 2 Fields Switch Names and Places https://issues.jboss.org/browse/DBZ-1694[DBZ-1694]
* TINYINT(1) value range restricted on snapshot. https://issues.jboss.org/browse/DBZ-1773[DBZ-1773]
* MySQL source connector fails while parsing new AWS RDS internal event https://issues.jboss.org/browse/DBZ-1775[DBZ-1775]
* Connector fails when performing a Hot Schema Update in SQLServer (Data row is smaller than a column index). https://issues.jboss.org/browse/DBZ-1778[DBZ-1778]
* Incosistency in MySQL TINYINT mapping definition https://issues.jboss.org/browse/DBZ-1800[DBZ-1800]
* Debezium skips messages after restart https://issues.jboss.org/browse/DBZ-1824[DBZ-1824]
* Supply of message.key.columns disables primary keys. https://issues.jboss.org/browse/DBZ-1825[DBZ-1825]
* MySql connector fails after CREATE TABLE IF NOT EXISTS table_A, given table_A does exist already https://issues.jboss.org/browse/DBZ-1833[DBZ-1833]
* Unable to listen to binlogs for tables with a period in the table names https://issues.jboss.org/browse/DBZ-1834[DBZ-1834]
* Mongodb field.renames will add renamed field even when source field is missing https://issues.jboss.org/browse/DBZ-1848[DBZ-1848]
* Redundant calls to refresh schema when using user defined types in PostgreSQL https://issues.jboss.org/browse/DBZ-1849[DBZ-1849]
* postgres oid is too large to cast to integer https://issues.jboss.org/browse/DBZ-1850[DBZ-1850]


=== Other changes

This release includes also other changes:

* Verify correctness of JMX metrics https://issues.jboss.org/browse/DBZ-1664[DBZ-1664]
* Document that server name option must not use hyphen in name https://issues.jboss.org/browse/DBZ-1704[DBZ-1704]
* Move MongoDB connector to base framework https://issues.jboss.org/browse/DBZ-1726[DBZ-1726]
* hstore.handling.mode docs seem inaccurate (and map shows null values) https://issues.jboss.org/browse/DBZ-1758[DBZ-1758]
* Document transaction metadata topic name https://issues.jboss.org/browse/DBZ-1779[DBZ-1779]
* Remove Microsoft references in Db2 connector comments https://issues.jboss.org/browse/DBZ-1794[DBZ-1794]
* Fix link to CONTRIBUTE.md in debezium-incubator repository README.md https://issues.jboss.org/browse/DBZ-1795[DBZ-1795]
* Invalid dependency definition in Quarkus ITs https://issues.jboss.org/browse/DBZ-1799[DBZ-1799]
* Document MySQL boolean handling https://issues.jboss.org/browse/DBZ-1801[DBZ-1801]
* Jackson dependency shouldn't be optional in Testcontainers module https://issues.jboss.org/browse/DBZ-1803[DBZ-1803]
* Change Db2 configuration for faster test execution https://issues.jboss.org/browse/DBZ-1809[DBZ-1809]
* MySQL: Rename event.deserialization.failure.handling.mode to event.processing.failure.handling.mode https://issues.jboss.org/browse/DBZ-1826[DBZ-1826]
* Misleading warning message about uncommitted offsets https://issues.jboss.org/browse/DBZ-1840[DBZ-1840]
* Missing info on DB2 connector in incubator README file https://issues.jboss.org/browse/DBZ-1842[DBZ-1842]
* Only replace log levels if LOG_LEVEL var is set https://issues.jboss.org/browse/DBZ-1843[DBZ-1843]
* Modularize tutorial https://issues.jboss.org/browse/DBZ-1845[DBZ-1845]
* Modularize the monitoring doc https://issues.jboss.org/browse/DBZ-1851[DBZ-1851]
* Remove deprecated methods from SnapshotProgressListener https://issues.jboss.org/browse/DBZ-1856[DBZ-1856]
* Document PostgreSQL connector metrics https://issues.jboss.org/browse/DBZ-1858[DBZ-1858]



[[release-1.1.0-beta2]]
== *Release 1.1.0.Beta2* _(February 13th, 2020)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12344682[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.4.0 and has been tested with version 2.4.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 1.1.0.Beta2 from any of the earlier 1.1.x, 1.0.x, 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 1.1.0.Beta2 plugin files, and restart the connector using the same configuration.
Upon restart, the 1.1.0.Beta2 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.

=== New Features

* Add ability to insert fields from op field in ExtractNewRecordState SMT https://issues.jboss.org/browse/DBZ-1452[DBZ-1452]
* Integrates with TestContainers project https://issues.jboss.org/browse/DBZ-1722[DBZ-1722]


=== Fixes

This release includes the following fixes:

* Postgres Connector losing data on restart due to commit() being called before events produced to Kafka https://issues.jboss.org/browse/DBZ-1766[DBZ-1766]
* DBREF fields causes SchemaParseException using New Record State Extraction SMT and Avro converter https://issues.jboss.org/browse/DBZ-1767[DBZ-1767]


=== Other changes

This release includes also other changes:

* Superfluous whitespace in intra-level ToC sidebar https://issues.jboss.org/browse/DBZ-1668[DBZ-1668]
* Outbox Quarkus Extension follow-up tasks https://issues.jboss.org/browse/DBZ-1711[DBZ-1711]
* DB2 connector follow-up tasks https://issues.jboss.org/browse/DBZ-1752[DBZ-1752]
* Unwrap SMT demo not compatible with ES 6.1+ https://issues.jboss.org/browse/DBZ-1756[DBZ-1756]
* Instable SQL Server test https://issues.jboss.org/browse/DBZ-1764[DBZ-1764]
* Remove Db2 JDBC driver from assembly package https://issues.jboss.org/browse/DBZ-1776[DBZ-1776]
* Fix PostgresConnectorIT.shouldOutputRecordsInCloudEventsFormat test https://issues.jboss.org/browse/DBZ-1783[DBZ-1783]
* Use "application/avro" as data content type in CloudEvents https://issues.jboss.org/browse/DBZ-1784[DBZ-1784]
* Update Standard Tutorials/Examples with DB2 https://issues.jboss.org/browse/DBZ-1558[DBZ-1558]



[[release-1.1.0-beta1]]
== *Release 1.1.0.Beta1* _(February 5th, 2020)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12344479[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.4.0 and has been tested with version 2.4.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 1.1.0.Beta1 from any of the earlier 1.1.x, 1.0.x, 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 1.1.0.Beta1 plugin files, and restart the connector using the same configuration.
Upon restart, the 1.1.0.Beta1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

Before updating the DecoderBufs logical decoding plug-in in your Postgres database to this new version (or when pulling the debezium/postgres container image for that new version), it is neccessary to upgrade the Debezium Postgres connector to 1.0.1.Final or 1.1.0.Alpha2 or later (https://issues.jboss.org/browse/DBZ-1052[DBZ-1052]).

The `ExtractNewDocumentState` SMT to be used with the Debezium MongoDB connector will convert `Date` and `Timestamp` fields now into the `org.apache.kafka.connect.data.Timestam`p logical type, clarifying its semantics.
The schema type itself remains unchanged as `int64`.
Please note that the resolution of `Timestamp` is seconds as per the semantics of that type in MongoDB. (https://issues.jboss.org/browse/DBZ-1717[DBZ-1717]).


=== New Features

* Create a plug-in for DB2 streaming https://issues.jboss.org/browse/DBZ-695[DBZ-695]
* Add topic routing by field option for New Record State Extraction https://issues.jboss.org/browse/DBZ-1715[DBZ-1715]
* Generate date(time) field types in the Kafka Connect data structure https://issues.jboss.org/browse/DBZ-1717[DBZ-1717]
* Publish TX boundary markers on a TX metadata topic https://issues.jboss.org/browse/DBZ-1052[DBZ-1052]
* Replace connectorName with kafkaTopicPrefix in kafka key/value schema https://issues.jboss.org/browse/DBZ-1763[DBZ-1763]


=== Fixes

This release includes the following fixes:

* Connector error after adding a new not null column to table in Postgres https://issues.jboss.org/browse/DBZ-1698[DBZ-1698]
* MySQL connector doesn't use default value of connector.port https://issues.jboss.org/browse/DBZ-1712[DBZ-1712]
* Fix broken images in Antora and brush up AsciiDoc  https://issues.jboss.org/browse/DBZ-1725[DBZ-1725]
* ANTLR parser cannot parse MariaDB Table DDL with TRANSACTIONAL attribute https://issues.jboss.org/browse/DBZ-1733[DBZ-1733]
* Postgres connector does not support proxied connections https://issues.jboss.org/browse/DBZ-1738[DBZ-1738]
* GET DIAGNOSTICS statement not parseable https://issues.jboss.org/browse/DBZ-1740[DBZ-1740]
* Examples use http access to Maven repos which is no longer available https://issues.jboss.org/browse/DBZ-1741[DBZ-1741]
* MySql password logged out in debug log level https://issues.jboss.org/browse/DBZ-1748[DBZ-1748]
* Cannot shutdown PostgreSQL if there is an active Debezium connector https://issues.jboss.org/browse/DBZ-1727[DBZ-1727]


=== Other changes

This release includes also other changes:

* Add tests for using fallback values with default REPLICA IDENTITY https://issues.jboss.org/browse/DBZ-1158[DBZ-1158]
* Migrate all attribute name/value pairs to Antora component descriptors https://issues.jboss.org/browse/DBZ-1687[DBZ-1687]
* Upgrade to Awestruct 0.6.0 https://issues.jboss.org/browse/DBZ-1719[DBZ-1719]
* Run CI tests for delivered non-connector modules (like Quarkus) https://issues.jboss.org/browse/DBZ-1724[DBZ-1724]
* Remove overlap of different documentation config files https://issues.jboss.org/browse/DBZ-1729[DBZ-1729]
* Don't fail upon receiving unkown operation events https://issues.jboss.org/browse/DBZ-1747[DBZ-1747]
* Provide a method to identify an envelope schema https://issues.jboss.org/browse/DBZ-1751[DBZ-1751]
* Upgrade to Mongo Java Driver version 3.12.1 https://issues.jboss.org/browse/DBZ-1761[DBZ-1761]
* Create initial Proposal for DB2 Source Connector https://issues.jboss.org/browse/DBZ-1509[DBZ-1509]
* Review Pull Request for DB2 Connector https://issues.jboss.org/browse/DBZ-1527[DBZ-1527]
* Test Set up of the DB2 Test Instance https://issues.jboss.org/browse/DBZ-1556[DBZ-1556]
* Create Documentation for the DB2 Connector https://issues.jboss.org/browse/DBZ-1557[DBZ-1557]
* Verify support of all DB2 types https://issues.jboss.org/browse/DBZ-1708[DBZ-1708]



[[release-1.1.0-alpha1]]
== *Release 1.1.0.Alpha1* _(January 16th, 2020)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12344080[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.4.0 and has been tested with version 2.4.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 1.1.0.Alpha1 from any of the earlier 1.1.x, 1.0.x, 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 1.1.0.Alpha1 plugin files, and restart the connector using the same configuration.
Upon restart, the 1.1.0.Alpha1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

When using the outbox event routing SMT and configuring a column from which to obtain the Kafka record timestamp from (table.field.event.timestamp option), then that value could have been exported as milliseconds, microseconds or nanoseconds, based on the source column's definition.
As of this release, the timestamp always be exported as milliseconds (https://issues.jboss.org/browse/DBZ-1707[DBZ-1707]).

The deprecated Postgres connector option `slot.drop_on_stop` has been removed; use `slot.drop.on.stop` instead (https://issues.jboss.org/browse/DBZ-1600[DBZ-1600]).


=== New Features

* MongoDB authentication against non-admin authsource https://issues.jboss.org/browse/DBZ-1168[DBZ-1168]
* Oracle: Add support for different representations of "NUMBER" Data Type https://issues.jboss.org/browse/DBZ-1552[DBZ-1552]
* Update Mongo Java driver to version 3.12.0 https://issues.jboss.org/browse/DBZ-1690[DBZ-1690]
* Support exporting change events in "CloudEvents" format https://issues.jboss.org/browse/DBZ-1292[DBZ-1292]
* Build Quarkus extension facilitating implementations of the outbox pattern https://issues.jboss.org/browse/DBZ-1478[DBZ-1478]
* Support column masking option for Postgres https://issues.jboss.org/browse/DBZ-1685[DBZ-1685]


=== Fixes

This release includes the following fixes:

* Make slot creation in PostgreSQL more resilient https://issues.jboss.org/browse/DBZ-1684[DBZ-1684]
* SQLserver type time(4)...time(7) lost nanoseconds https://issues.jboss.org/browse/DBZ-1688[DBZ-1688]
* Support boolean as default for INT(1) column in MySQL https://issues.jboss.org/browse/DBZ-1689[DBZ-1689]
* SIGNAL statement is not recognized by DDL parser https://issues.jboss.org/browse/DBZ-1691[DBZ-1691]
* When using in embedded mode MYSQL connector fails https://issues.jboss.org/browse/DBZ-1693[DBZ-1693]
* MySQL connector fails to parse trigger DDL https://issues.jboss.org/browse/DBZ-1699[DBZ-1699]


=== Other changes

This release includes also other changes:

* Update outbox routing example https://issues.jboss.org/browse/DBZ-1673[DBZ-1673]
* Add option to JSON change event SerDe for ignoring unknown properties https://issues.jboss.org/browse/DBZ-1703[DBZ-1703]
* Update debezium/awestruct image to use Antora 2.3 alpha 2 https://issues.jboss.org/browse/DBZ-1713[DBZ-1713]

