= Release Notes for Debezium 0.3
:toc:
:toc-placement: macro
:toclevels: 1
:sectanchors:
:linkattrs:
:icons: font

All notable changes for Debezium releases are documented in this file.
Release numbers follow http://semver.org[Semantic Versioning].

toc::[]

[[release-0-4-1]]
== *Release 0.4.1* _(March 17, 2017)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12333486[complete list of issues].

=== Kafka compatibility

This release has been tested with Kafka Connect 0.10.1.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.redhat.com/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.4.1 from any of the earlier 0.4.0, 0.3.x, 0.2.x, or 0.1.x versions, first check the upgrading notes for the version you're using. Gracefully stop the running connector, remove the old plugin files, install the 0.4.1 plugin files, and restart the connector using the same configuration. Upon restart, the 0.4.1 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release has no breaking changes since the link:release-0-4-0[previous] release.

=== New Features

This release adds/improves to the MySQL connector preliminary support for https://aws.amazon.com/rds/mysql/[Amazon RDS] and https://aws.amazon.com/rds/aurora/[Amazon Aurora (MySQL compatibility)] (see https://issues.redhat.com/projects/DBZ/issues/DBZ-140[DBZ-140]).

=== Fixes

This release includes the following fixes relative to the link:release-0-4-0[0.4.0] release:

* MySQL connector now allows filtering production of DML events by GTIDs. https://issues.redhat.com/projects/DBZ/issues/DBZ-188[DBZ-188]
* Support InnoDB savepoints. https://issues.redhat.com/projects/DBZ/issues/DBZ-196[DBZ-196]
* Corrected MySQL DDL parser. https://issues.redhat.com/projects/DBZ/issues/DBZ-193[DBZ-193] https://issues.redhat.com/projects/DBZ/issues/DBZ-198[DBZ-198]
* Improved handling of MySQL connector's built-in tables. https://issues.redhat.com/projects/DBZ/issues/DBZ-194[DBZ-194]
* MySQL connector properly handles invalid/blank enum literal values. https://issues.redhat.com/projects/DBZ/issues/DBZ-197[DBZ-197]
* MySQL connector properly handles reserved names as column names. https://issues.redhat.com/projects/DBZ/issues/DBZ-200[DBZ-200]
* MongoDB connector properly generates event keys based upon ObjectID for updates. https://issues.redhat.com/projects/DBZ/issues/DBZ-201[DBZ-201]



[[release-0-4-0]]
== *Release 0.4.0* _(February 7, 2017)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12330743[complete list of issues].

=== Kafka compatibility

This release has been tested with Kafka Connect 0.10.1.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.redhat.com/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.4.0 from any of the earlier 0.3.x, 0.2.x, or 0.1.x versions, first check the upgrading notes for the version you're using. Gracefully stop the running connector, remove the old plugin files, install the 0.4.0 plugin files, and restart the connector using the same configuration. Upon restart, the 0.4.0 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release has no breaking changes since the link:release-0-3-5[previous] release.

=== New Features

This release includes a new link:/docs/connectors/postgresql/[PostgreSQL connector] (see https://issues.redhat.com/projects/DBZ/issues/DBZ-3[DBZ-3]) and adds to the MySQL connector preliminary support for https://aws.amazon.com/rds/mysql/[Amazon RDS] and https://aws.amazon.com/rds/aurora/[Amazon Aurora (MySQL compatibility)] (see https://issues.redhat.com/projects/DBZ/issues/DBZ-140[DBZ-140]).

=== Fixes

This release includes the following fixes relative to the link:release-0-3-6[0.3.6] release:

* Update Kafka dependencies to 0.10.1.1. https://issues.redhat.com/projects/DBZ/issues/DBZ-173[DBZ-173]
* Update MySQL binary log client library to 0.9.0. https://issues.redhat.com/projects/DBZ/issues/DBZ-186[DBZ-186]
* MySQL should apply GTID filters to database history. https://issues.redhat.com/projects/DBZ/issues/DBZ-185[DBZ-185]
* Add names of database and table to the MySQL event metadata. https://issues.redhat.com/projects/DBZ/issues/DBZ-184[DBZ-184]
* Add the MySQL thread ID to the MySQL event metadata. https://issues.redhat.com/projects/DBZ/issues/DBZ-113[DBZ-113]
* Corrects MySQL connector to properly handle timezone information for `TIMESTAMP`. https://issues.redhat.com/projects/DBZ/issues/DBZ-183[DBZ-183]
* Correct MySQL DDL parser to handle `CREATE TRIGGER` command with `DEFINER` clauses. https://issues.redhat.com/projects/DBZ/issues/DBZ-176[DBZ-176]
* Update MongoDB Java driver and MongoDB server versions. https://issues.redhat.com/projects/DBZ/issues/DBZ-187[DBZ-187]
* MongoDB connector should restart incomplete initial sync. https://issues.redhat.com/projects/DBZ/issues/DBZ-182[DBZ-182]
* MySQL and PostgreSQL connectors should load JDBC driver independently of DriverManager. https://issues.redhat.com/projects/DBZ/issues/DBZ-177[DBZ-177]
* Upgrade MySQL binlog client library to support new binlog events added with MySQL 5.7. https://issues.redhat.com/projects/DBZ/issues/DBZ-174[DBZ-174]
* EmbeddedEngine should log all errors. https://issues.redhat.com/projects/DBZ/issues/DBZ-178[DBZ-178]
* PostgreSQL containers' generated Protobuf source moved to separate directory. https://issues.redhat.com/projects/DBZ/issues/DBZ-179[DBZ-179]
