= Release Notes for Debezium 0.3
:toc:
:toc-placement: macro
:toclevels: 1
:sectanchors:
:linkattrs:
:icons: font

All notable changes for Debezium releases are documented in this file.
Release numbers follow http://semver.org[Semantic Versioning].

toc::[]

[[release-0-3-6]]
== *Release 0.3.6* _(December 21, 2016)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12332775[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.redhat.com/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.6 from any of the earlier 0.3.x, 0.2.x, or 0.1.x versions, first check the upgrading notes for the version you're using. Gracefully stop the running connector, remove the old plugin files, install the 0.3.6 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.6 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release has no breaking changes since the link:release-0-3-5[previous] release.

=== New Features

There are no new features in this release.

=== Fixes

This release includes the following fixes to the link:release-0-3-5[0.3.5] release:

* Deleting a Debezium connector in Kafka Connect no longer causes NPEs. https://issues.redhat.com/projects/DBZ/issues/DBZ-138[DBZ-138]
* MongoDB connector properly connects to a sharded cluster and the primaries for each replica set. https://issues.redhat.com/projects/DBZ/issues/DBZ-170[DBZ-170], https://issues.redhat.com/projects/DBZ/issues/DBZ-167[DBZ-167]
* Stopping the MySQL connector while in the middle of a snapshot now cloasses all MySQL resources. https://issues.redhat.com/projects/DBZ/issues/DBZ-166[DBZ-166]
* MySQL connector properly parses with `ON UPDATE` timestamp values. https://issues.redhat.com/projects/DBZ/issues/DBZ-169[DBZ-169]
* MySQL connector ignores `CREATE FUNCTION` DDL statements. https://issues.redhat.com/projects/DBZ/issues/DBZ-162[DBZ-162]
* MySQL connector properly parses `CREATE TABLE` script with ENUM type and default value 'b'. https://issues.redhat.com/projects/DBZ/issues/DBZ-160[DBZ-160]
* MySQL connector now properly supports `NVARCHAR` columns. https://issues.redhat.com/projects/DBZ/issues/DBZ-142[DBZ-142]
* MySQL connector's snapshot process now uses `SHOW TABLE STATUS ...` rather than `SELECT COUNT(\*)` to obtain an estimate of the number of rows for each table, and can even forgo this step if all tables are to be streamed. https://issues.redhat.com/projects/DBZ/issues/DBZ-152[DBZ-152]
* MySQL connector's snaphot process ignores "artificial" database names exposed by MySQL. https://issues.redhat.com/projects/DBZ/issues/DBZ-164[DBZ-164]
* MySQL connector ignores XA statements appearing in the binlog. https://issues.redhat.com/projects/DBZ/issues/DBZ-168[DBZ-168]
* MySQL connector no longer expects GTID set information on older MySQL versions. https://issues.redhat.com/projects/DBZ/issues/DBZ-161[DBZ-161]
* Improved the EmbeddedEngine and fixed several issues. https://issues.redhat.com/projects/DBZ/issues/DBZ-156[DBZ-156]
* Upgrade to the latest Docker Maven plugin https://issues.redhat.com/projects/DBZ/issues/DBZ-157[DBZ-157]




[[release-0-3-5]]
== *Release 0.3.5* _(November 9, 2016)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12332052[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.redhat.com/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

*We strongly urge all users to upgrade to this release from earlier versions.* In prior versions, the MySQL connector may stop without completing all updates in a transaction, and when the connector restarts it starts with the _next_ transaction and therefore might fail to capture some of the change events in the earlier transaction. This release fixes this issue so that when restarting it will always pick up where it left off, even if that point is in the middle of a transaction. Note that this fix only takes affect once a connector is upgraded and restarted. Also, this fix does not affect or alter the content of change events produced by the connector. See https://issues.redhat.com/projects/DBZ/issues/DBZ-144[the issue] for more details.

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.5 from 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.5 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.5 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release has no backward-incompatible changes since the link:release-0-3-4[0.3.4] release.

=== New Features

* MySQL connector now supports failover to MySQL masters that are slaves of _multiple_ other MySQL servers/clusters, as long as the new MySQL master has all of the transactions (as specified by GTID sets) the connector had previously seen. The connector can be configured to include or exclude particular GTID sources. https://issues.redhat.com/projects/DBZ/issues/DBZ-143[DBZ-143]

=== Fixes

This release includes the following fixes to the link:release-0-3-4[0.3.4] release:

* Restarting MySQL connector will no longer lose or miss events from the previous transaction that was incompletely processed prior to the easlier shutdown. The content of change events are unaffected. https://issues.redhat.com/projects/DBZ/issues/DBZ-144[DBZ-144]
* Shutting down MySQL connector task database and quickly terminating the Kafka Connect process may cause connector to be restarted in a strange state when Kafka Connect is restarted, but this no longer results in a null pointer exception in the Kafka database history. https://issues.redhat.com/projects/DBZ/issues/DBZ-146[DBZ-146]
* MySQL connector now has option to treat `DECIMAL` and `NUMERIC` columns as double values rather than `java.math.BigDecimal` values that are encoded in the messages by Kafka Connect in binary form. This option may result in lost precision, but makes the values far easier for consumers to work with them. https://issues.redhat.com/projects/DBZ/issues/DBZ-147[DBZ-147]
* MySQL connector tests now take into account daylight savings time in the expected results. https://issues.redhat.com/projects/DBZ/issues/DBZ-148[DBZ-148]
* MySQL connector now properly treats `BINARY` columns as binary values rather than string values. https://issues.redhat.com/projects/DBZ/issues/DBZ-149[DBZ-149]
* MySQL connector now handles updates to a row's primary/unique key by issuing `DELETE` and tombstone events for the row with the old key, and then an `INSERT` event for the row with the new key. Previously, the `INSERT` was emitted before the `DELETE`. https://issues.redhat.com/projects/DBZ/issues/DBZ-150[DBZ-150]
* MySQL connector now handles `ENUM` and `SET` literals with parentheses. https://issues.redhat.com/projects/DBZ/issues/DBZ-153[DBZ-153]



[[release-0-3-4]]
== *Release 0.3.4* _(October 25, 2016)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12331604[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.redhat.com/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.4 from 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.4 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.4 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release has one breaking changes since the link:release-0-3-3[0.3.3] release:

* MySQL connector produced change events with a `ts_sec` field that now shows correct timestamp in seconds past epoch as found from the MySQL server events. In previous releases the last 3 digits in this field were truncated. https://issues.redhat.com/projects/DBZ/issues/DBZ-139[DBZ-139]

=== New Features

* MySQL connector has a new `SCHEMA_ONLY` snapshot mode. When the connector starts up for the first time and uses this snapshot mode, the connector captures the current table schemas without reading any data, and then proceeds to read the binlog. The resulting change event streams do not have all the data in the databases, but do include those change events that occurred after the snapshot started. This may be useful for consumers that only need to know the changes since the connector was started. https://issues.redhat.com/projects/DBZ/issues/DBZ-133[DBZ-133]
* MySQL connector supports the MySQL `JSON` datatype. These JSON values are represented as STRING values in the change events, although the name of the field's Kafka Connect schema is `io.debezium.data.Json` to signal to consumers that the string value is actually a JSON document, array, or scalar. https://issues.redhat.com/projects/DBZ/issues/DBZ-126[DBZ-126]
* MySQL connector metrics are exposed via JMX. All of the Debezium Docker images can expose the JMX data via a custom port. See the link:/docs/monitoring/[Monitoring Debezium] document for more details. https://issues.redhat.com/projects/DBZ/issues/DBZ-134[DBZ-134]

=== Fixes

This release includes no other fixes.



[[release-0-3-3]]
== *Release 0.3.3* _(October 18, 2016)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12331604[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.redhat.com/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.3 from 0.3.2, 0.3.1, 0.3.0, 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.3 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.3 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release includes no breaking changes since the link:release-0-3-2[0.3.2] release.

=== New Features

This release includes no new features since the link:release-0-3-2[0.3.2] release.

=== Fixes

This release includes the following fixes to the link:release-0-3-2[0.3.2] release:

* MySQL connector now works with MySQL 5.5. https://issues.redhat.com/projects/DBZ/issues/DBZ-115[DBZ-115]
* MySQL connector now handles `BIT(n)` column values. https://issues.redhat.com/projects/DBZ/issues/DBZ-123[DBZ-123]
* MySQL connector supports failing over based on subset of GTIDs. https://issues.redhat.com/projects/DBZ/issues/DBZ-129[DBZ-129]
* MySQL connector processes GTIDs with line feeds and carriage returns. https://issues.redhat.com/projects/DBZ/issues/DBZ-135[DBZ-135]
* MySQL connector has improved output of GTIDs and status when reading the binary log. https://issues.redhat.com/projects/DBZ/issues/DBZ-130[DBZ-130], https://issues.redhat.com/projects/DBZ/issues/DBZ-131[DBZ-131]
* MySQL connector properly handles multi-character `ENUM` and `SET` values. https://issues.redhat.com/projects/DBZ/issues/DBZ-132[DBZ-132]



[[release-0-3-2]]
== *Release 0.3.2* _(September 26, 2016)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12331401[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.redhat.com/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.2 from 0.3.1, 0.3.0, 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.2 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.2 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release includes no breaking changes since the link:release-0-3-1[0.3.1] release.

=== New Features

This release includes no new features since the link:release-0-3-1[0.3.1] release.

=== Fixes

This release includes the following fixes to the link:release-0-3-1[0.3.1] release:

* MySQL connector now handles zero-value dates. https://issues.redhat.com/projects/DBZ/issues/DBZ-114[DBZ-114]
* MySQL connector no longer prints out password-related configuration properties, though https://issues.apache.org/jira/browse/KAFKA-4171[KAFKA-4171] for a similar issue with Kafka Connect. https://issues.redhat.com/projects/DBZ/issues/DBZ-122[DBZ-122]
* MySQL connector no longer causes "Error registering AppInfo mbean" warning in Kafka Connect. https://issues.redhat.com/projects/DBZ/issues/DBZ-124[DBZ-124]
* MySQL connector periodically outputs status when reading binlog. https://issues.redhat.com/projects/DBZ/issues/DBZ-116[DBZ-116]
* MongoDB connector periodically outputs status when reading binlog. https://issues.redhat.com/projects/DBZ/issues/DBZ-117[DBZ-117]
* MySQL connector correctly uses long for the `server.id` configuration property. https://issues.redhat.com/projects/DBZ/issues/DBZ-118[DBZ-118]
* MySQL connector fails or warns when MySQL is not using row-level logging. https://issues.redhat.com/projects/DBZ/issues/DBZ-128[DBZ-128]


[[release-0-3-1]]
== *Release 0.3.1* _(August 30, 2016)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12331359[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.redhat.com/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.1 from 0.3.0, 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.1 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.1 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release includes no breaking changes compared to the link:release-0-3-0[0.3.0] release.

=== New Features

* Added support for secure (encrypted) connections to MySQL. https://issues.redhat.com/projects/DBZ/issues/DBZ-99[DBZ-99]

=== Fixes

This release includes the following fixes to the link:release-0-3-0[0.3.0] release:

* MySQL connector now properly decodes string values from the binlog based upon the column's character set encoding as read by the DDL statement. Upon upgrade and restart, the connector will re-read the recorded database history and now associate the columns with their the character sets, and any newly processed events will use properly encoded strings values. As expected, previously generated events are never altered. Force a snapshot to regenerate events for the servers. https://issues.redhat.com/projects/DBZ/issues/DBZ-102[DBZ-102]
* Corrected how the MySQL connector parses some DDL statements. https://issues.redhat.com/projects/DBZ/issues/DBZ-106[DBZ-106]
* Corrected the MySQL connector to handle MySQL server GTID sets with newline characters. https://issues.redhat.com/projects/DBZ/issues/DBZ-107[DBZ-107], https://issues.redhat.com/projects/DBZ/issues/DBZ-111[DBZ-111]
* Corrected the MySQL connector's startup logic properly compare the MySQL SSL-related system properties to prevent overwriting them. The connector no longer fails when the system properties are the same, which can happen upon restart or starting a second MySQL connector with the same keystore. https://issues.redhat.com/projects/DBZ/issues/DBZ-112[DBZ-112]
* Removed unused code and test case. https://issues.redhat.com/projects/DBZ/issues/DBZ-108[DBZ-108]
* Ensure that the MySQL error code and SQLSTATE are included in exceptions reported by the connector. https://issues.redhat.com/projects/DBZ/issues/DBZ-109[DBZ-109]


[[release-0-3-0]]
== *Release 0.3.0* _(August 16, 2016)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12329661[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.redhat.com/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.0 from 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.0 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.0 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release includes one potentially breaking changes from the link:release-0-2-4[0.2.4] release:

* By default the MySQL connector now represents temporal values with millisecond, microsecond, or nanosecond precision based upon the precision of the source database columns. This changes the schema name of these fields to Debezium-specific constants, and the meaning/interpretation of the literal values now depends on this schema name. To enable previous behavior that always used millisecond precision using only Kafka Connect logical types, set `time.precision.mode` connector property to `connect`. https://issues.redhat.com/projects/DBZ/issues/DBZ-91[DBZ-91]

=== New Features

* Added the link:/docs/connectors/mongodb/[MongoDB connector], which can capture and record the changes within a MongoDB replica set or MongoDB sharded cluster. In the latter case, the connector even automatically handles the addition or removal of shards. https://issues.redhat.com/projects/DBZ/issues/DBZ-2[DBZ-2]

=== Fixes

This release includes all of the fixes from the link:release-0-2-4[0.2.4] release, and also includes the following fixes:

* Corrected how the MySQL connector handles `TINYINT` columns. https://issues.redhat.com/projects/DBZ/issues/DBZ-84[DBZ-84]
* MySQL snapshots records DDL statements as separate events on the schema change topic. https://issues.redhat.com/browse/DBZ-97[DBZ-97]
* MySQL connector tolerates binlog filename missing from ROTATE events in certain situations. https://issues.redhat.com/browse/DBZ-95[DBZ-95]
* The Kafka Connect schema names used in the MySQL connector's change events are now always Avro-compatible schema names. Now, using the Avro converter with a `database.server.name` value, database names, or table names that contain Avro-incompatible characters produce log warnings but no longer result in errors during serialization and Avro schema generation. Whenever possible, use a `database.server.name` value that contains alphanumeric and underscore characters. https://issues.redhat.com/projects/DBZ/issues/DBZ-86[DBZ-86]
