---
layout: post
title:  Debezium 0.3.6 Released
date:   2016-12-21 10:19:59 -0600
tags: [ releases, mysql, docker ]
author: rhauch
---

We're happy to announce that **Debezium 0.3.6** is now available for use with Kafka Connect 0.10.0.1. This release contains over a dozen fixes combined for the MySQL connector and MongoDB connectors. See the link:/docs/releases/[release notes] for specifics on these changes. 

We've also updated the https://hub.docker.com/r/debezium/[Debezium Docker images] labelled `0.3` and `latest`, which we use in our link:/docs/tutorial/[tutorial].

Thanks to Farid, RenZhu, Dongjun, Anton, Chris, Dennis, Sharaf, Rodrigo, Tim, and others for their help with this release, issues, discussions, contributions, and questions!

+++<!-- more -->+++

== What's next

We'll continue to improve the MongoDB and MySQL connectors, and we also have a great PostgreSQL connector that is nearly ready to be released. With the new connector we'll switch release numbers to 0.4.x and plan to stop issuing 0.3.x releases. Stay tuned for this next 0.4.0 release!
