---
tags: [ releases, mysql, mongodb, docker ]
---
= Debezium 0.3.2 Released
rhauch
:awestruct-tags: [ releases, mysql, mongodb, docker ]
:awestruct-layout: blog-post

We're happy to announce that **Debezium 0.3.2** is now available for use with Kafka Connect 0.10.0.1. This release contains a handful of bug fixes and minor improvements for the link:/docs/connectors/mysql/[MySQL connector] and link:/docs/connectors/mongodb/[MongoDB connector]. The MySQL connector better handles `BIT(n)` values and http://dev.mysql.com/doc/refman/5.7/en/date-and-time-types.html[zero-value] date and timestamp values. This release also improves the log messages output by the MySQL and MongoDB connectors to better represent the ongoing activity when consuming the changes from the source database. See the link:/docs/releases/[release notes] for specifics.

We've also updated the https://hub.docker.com/r/debezium/[Debezium Docker images] labelled `0.3` and `latest`, which we use in our link:/docs/tutorial/[tutorial]. We've also updated the tutorial to use the https://docs.docker.com/engine/installation/[latest Docker installations] on Linux, Windows, and OS X.

Thanks to Akshath, Colum, Emmanuel, Konstantin, Randy, RenZhu, Umang, and others for their help with the release, issues, discussions, contributions, and questions!

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams, so applications can see and respond almost instantly to each committed row-level change in the databases. Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems. Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running, ensuring that all events are processed correctly and completely. Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try. Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter], or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community. All of the code is open source https://github.com/debezium/[on GitHub], so build the code locally and help us improve the MySQL connector and add more connectors. If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
