---
tags: [ releases, mysql, mongodb, postgres, docker ]
---
= Debezium 0.5.0 Released
rhauch
:awestruct-tags: [ releases, mysql, mongodb, postgres, docker ]
:awestruct-layout: blog-post

We're happy to announce that **Debezium 0.5.0** is now available for use with *Kafka Connect 0.10.2.0*. This release also includes a few fixes for the link:/docs/connectors/mysql/[MySQL connector]. See the link:/docs/releases/[release notes] for specifics on these changes, and be sure to check out the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with the version of the Kafka broker that you are using.

Kafka Connect 0.10.2.0 comes with a significant new feature called https://cwiki.apache.org/confluence/display/KAFKA/KIP-66%3A+Single+Message+Transforms+for+Kafka+Connect[Single Message Transforms], and you can now use them with Debezium connectors. SMTs allow you to modify the messages produced by Debezium connectors and any oher Kafka Connect source connectors, before those messages are written to Kafka. SMTs can also be used with Kafka Connect sink connectors to modify the messages _before_ the sink connectors processes them. You can use SMTs to filter out or mask specific fields, add new fields, modify existing fields, change the topic and/or topic partition to which the messages are written, and even more. And you can even chain multiple SMTs together.

Kafka Connect comes with a number of built-in SMTs that you can simply configure and use, but you can also create your own SMT implementations to do more complex and interesting things. For example, although Debezium connectors normally map all of the changes in each table (or collection) to separate topics, you can write a custom SMT that uses a completely different mapping between tables and topics and even add fields to message keys and/or values. Using your new SMT is also very easy - simply put it on the Kafka Connect classpath and update the connector configuration to use it.

We've also added https://hub.docker.com/r/debezium/[Debezium Docker images] labelled `0.5` and `latest`, which we use in our link:/docs/tutorial/[tutorial].

Thanks to Sanjay and everyone in the community for their help with this release, issues, discussions, contributions, and questions!

== What's next

We'll continue to improve the MongoDB, MySQL, and PostgreSQL connectors and pushing out 0.5.x releases with fixes. And we're still working on connectors for https://issues.redhat.com/browse/DBZ-40[SQL Server] and https://issues.redhat.com/browse/DBZ-137[Oracle]. Stay tuned and get involved!

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams, so applications can see and respond almost instantly to each committed row-level change in the databases. Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems. Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running, ensuring that all events are processed correctly and completely. Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try. Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter], or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community. All of the code is open source https://github.com/debezium/[on GitHub], so build the code locally and help us improve ours existing connectors and add even more connectors. If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
