---
tags: [ introduction, presentation ]
---
= Debezium at Devoxx Belgium
jpechane
:awestruct-tags: [ introduction, presentation ]
:awestruct-layout: blog-post

Debezium's project lead https://twitter.com/gunnarmorling[Gunnar Morling] gave a few talks during recent https://cfp.devoxx.be/2017/index.html[Devoxx Belgium 2017].
One of his talks was dedicated to Debezium and change data capture in general.

If you are interested in those topics and you want to obtain a fast and simple introduction to it, do not hesitate and watch the talk.
Batteries and demo included!

++++
<div class="responsive-video">
<iframe width="1600" height="900" src="https://www.youtube.com/embed/IOZ2Um6e430?rel=0" frameborder="0" allowfullscreen></iframe>
</div>
++++

The slide deck is https://speakerdeck.com/gunnarmorling/streaming-database-changes-with-debezium[available], too: +

++++
<div style="text-align-center">
<script async class="speakerdeck-embed" data-id="4fb7aa5af1c54d7ea807c9d46fb5b1fa" data-ratio="1.77777777777778" src="//speakerdeck.com/assets/embed.js"></script>
</div>
++++

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
