---
layout: post
title:  Debezium 0.6 Is Out
date:   2017-09-21 10:19:59 -0600
tags: [ releases, mysql, mongodb, postgres, docker ]
author: gmorling
---

What's better than getting http://openjdk.java.net/projects/jdk9/[Java 9]?
Getting Java 9 and a new version of Debezium at the same time!
So it's with great happiness that I'm announcing the release of **Debezium 0.6** today.

+++<!-- more -->+++

== What's in it?

Debezium is now built against and tested with Apache Kafka 0.11.0.
Also the Debezium Docker images have been updated do that version (https://issues.redhat.com/browse/DBZ-305[DBZ-305]).
You should make sure to read the Kafka https://kafka.apache.org/documentation/#upgrade[update guide] when upgrading from an earlier version.

To improve integration with existing Kafka sink connectors such as the https://docs.confluent.io/current/connect/connect-jdbc/docs/sink_connector.html[JDBC sink connector] or the https://docs.confluent.io/current/connect/connect-elasticsearch/docs/elasticsearch_connector.html[Elasticsearch] connector,
Debezium provides a new https://github.com/debezium/debezium/blob/master/debezium-core/src/main/java/io/debezium/transforms/UnwrapFromEnvelope.java[single message transformation] (https://issues.redhat.com/projects/DBZ/issues/DBZ-226[DBZ-226]).
This SMT converts Debezium's CDC event structure into a more conventional structure commonly used in other sink and non-CDC source connectors where the message represents the state of the inserted or updated row, or null in the case of a deleted row.
This lets your for instance capture the changes from a table in MySQL and update a corresponding table in a Postgres database accordingly.
We'll provide a complete example showing the usage of that new SMT in the next few days.

If you are doing the Debezium link:/docs/tutorial/[tutorial], you will like the new https://github.com/debezium/debezium-examples/tree/master/tutorial[Docker Compose set-up] provided in the examples repo (https://issues.redhat.com/browse/DBZ-127[DBZ-127]).
This lets you start all the required Docker containers with a single command.

== New connector features

Now let's take a look at some of the changes around the specific Debezium connectors.
The **MySQL connector** has seen multiple improvements, e.g.:

* Snapshot consistency wasn't guaranteed before in some corner cases (https://issues.redhat.com/browse/DBZ-210[DBZ-210]); that's fixed now
* DEC and FIXED types supported in the DDL parser (https://issues.redhat.com/browse/DBZ-359[DBZ-359]; thanks to https://github.com/ooooorz[Liu Hanlin]!)
* UNION clause supported for ALTER TABLE (https://issues.redhat.com/browse/DBZ-346[DBZ-346])

For the **MongoDB connector**, the way of serializing ids into the key payload of CDC events has changed (https://issues.redhat.com/browse/DBZ-306[DBZ-306]).
The new format allows to read back ids into the correct type.
We also took the opportunity and made the id field name consistent with the other connectors, i.e. it's "id" now.
**Note:** that change may break existing consumers, so some work on your end may be required, depending on the implementation of your consumer.
The details are discussed in the link:/docs/releases/#_breaking_changes[release notes] and the format of message keys is described in depth in the link:/docs/connectors/mongodb/#change-events-key[connector documentation].
Kudos to https://github.com/hpgrahsl[Hans-Peter Grahsl] who contributed on this feature!

Another nice improvement for this connector is support for SSL connections (https://issues.redhat.com/projects/DBZ/issues/DBZ-343[DBZ-343]).

Finally, the **Postgres connector** learned some new tricks, too:

* Support for variable-width numeric columns (https://issues.redhat.com/browse/DBZ-318[DBZ-318])
* Views won't stop the connector any more (https://issues.redhat.com/browse/DBZ-319[DBZ-319])
* Warnings and notifications emitted by the server are correctly forwarded to the log (https://issues.redhat.com/browse/DBZ-279[DBZ-279])

Please refer to the https://debezium.io/docs/releases/#release-0-6-0[changelog] for an overview of all the 20 issues fixed in Debezium 0.6.0.

== What's next?

High on our agenda is exploring support for Oracle (https://issues.redhat.com/browse/DBZ-20[DBZ-20]).
We are also looking into using another logical decoding plug-in (wal2json) for the Postgres connector, which would enable to use Debezium with Postgres instances running on Amazon RDS.
Another feature being worked on by community member https://github.com/mtagle[Moira Tagle] is support for updates to the `table.whitelist` for existing connector instances.
Finally, we've planned to test and adapt the existing MySQL connector for providing CDC functionality to MariaDB.

Debezium 0.7 with one or more out of those features as well as hopefully some others will be released later this year.
We'll likely also do further 0.6.x releases with bug fixes as required.

You'd like to contribute?
That's great - let us know and we'll get you started.
Check out the details below on how to get in touch.
