---
layout: post
title:  PostgreSQL support added to Debezium
date:   2017-02-08 10:19:59 -0600
tags: [ postgres, docker ]
author: hchiorean
---

With the https://debezium.io/blog/2017/02/07/Debezium-0-4-0-Released[recent Debezium release], we're happy to announce that a new **PostgreSQL connector** has been added alongside the already existing MySQL and MongoDB connectors.

+++<!-- more -->+++

[TIP]
====
Make sure you https://debezium.io/docs/connectors/postgresql[read the connector documentation] for an in-depth look at the different configuration options.
====

== Getting started

The fastest way to check out the new connector is using https://hub.docker.com/r/debezium/postgres[Debezium's Postgres docker image] which is based on a vanilla Postgres docker image on top of which it compiles and installs a PostgreSQL https://github.com/debezium/postgres-decoderbufs[logical decoding plugin] 
and sets up the necessary permissions for streaming changes locally (on `localhost`)

Once you fire up the Docker machine with the database server, starting up and configuring the connector to stream changes from that machine is exactly the same as described in detail by the https://debezium.io/docs/tutorial[Debezium tutorial]. The only obvious difference is that instead of the MySQL machine and MySQL connector configuration you need to use the PostgreSQL machine and the PostgreSQL connector configuration parameters. 

== Using the connector in your own environment

Unlike the Mongo and MySQL connectors, getting the PostgreSQL connector up and running is a bit more complicated due to the fact that it requires a server-side logical decoding plugin running in the PostgreSQL server. 

In general, there are three major steps involved in getting the connector running in your environment:

1. Compiling and installing the https://github.com/debezium/postgres-decoderbufs[logical decoding plugin] into your own server
2. Setting up the PostgreSQL server with appropriate replication permissions
3. Starting the Kafka Connect, Broker and Zookeeper machines

For steps 1 and 2 you can check out our https://github.com/debezium/docker-images/tree/master/postgres/9.6[PostgreSQL Docker image] together with the sources for the https://github.com/debezium/postgres-decoderbufs[logical decoding plugin]

For step 3 you can either use Debezium's https://github.com/debezium/docker-images[Kafka Docker images] or perform a similar setup locally. The https://debezium.io/docs/tutorial[Debezium tutorial] and the https://debezium.io/docs/connectors/postgresql[the connector documentation] are great resources for helping out with this task.
