---
tags: [ releases, mysql, mongodb, postgres, docker ]
---
= Debezium 0.6.1 Is Released
gmorling
:awestruct-tags: [ releases, mysql, mongodb, postgres, docker ]
:awestruct-layout: blog-post

Just shy of a month after the 0.6.0 release, I'm happy to announce the release of **Debezium 0.6.1**!

This release contains several bugfixes, dependency upgrades and a new option for controlling how `BIGINT UNSIGNED` columns are conveyed.
We also expanded the set of Docker images and Docker Compose files accompanying link:/docs/tutorial/[our tutorial], so you can run it now with all the databases we support.

Let's take a closer look at some of the changes.

== New connector option for controlling BIGINT UNSIGNED representation

`BIGINT UNSIGNED` columns from MySQL databases have been represented using Kafka Connect's `Decimal` type until now.
This type allows to represent all possible values of such columns, but its based on a byte array, so it can be a bit cumbersome to handle for consumers.
Therefore we added a new option named `bigint.unsigned.handling.mode` to the MySQL connector that allows to represent such columns using `long`.

For the very most cases that's the preferable option, only if your column contains values larger than 2^63
(which https://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html[MySQL doesn't recommend] due to potential value losses when performing calculations),
you should stick to the `Decimal` representation.

Using `long` will be the default as of Debezium 0.7, for the 0.6.x timeline we decided to go with the previous behavior (i.e. using `Decimal`) for the sake of backwards compatibility.

Thanks a lot to https://github.com/vultron81[Ben Williams] who contributed this feature!

== New example Docker images and Docker Compose files

In the https://github.com/debezium/debezium-examples/[Debezium examples repository] we now provide https://github.com/debezium/debezium-examples/tree/master/tutorial[Docker Compose files] which let you run the tutorial with all the three databases we currently support, MySQL, Postgres and MongoDB.

Just choose the Compose file for your preferred database and get a all the required components (ZooKeeper, Apache Kafka, Kafka Connect and the database) running within a few seconds.

We've also deployed Docker images for Postgres and MongoDB to the https://hub.docker.com/u/debezium/[Debezium organization] on Docker Hub, so you got some data to play with.

== Version upgrades

We've upgraded our images from Kafka 0.11.0.0 to https://issues.apache.org/jira/projects/KAFKA/versions/12340632[0.11.0.1].
Also the https://github.com/shyiko/mysql-binlog-connector-java[binlog client library] used by the MySQL connector was upgraded from 0.9.0 to 0.13.0.

== Bugfixes

Finally, several bugs were fixed in 0.6.1.
E.g. you can now name a column ``column`` in MySQL (https://issues.redhat.com/browse/DBZ-408[DBZ-408]),
generated `DROP TEMP TABLE` statements won't flood the DB history topic (https://issues.redhat.com/browse/DBZ-395[DBZ-295])
and we've fixed a case where the Postgres connector would stop working due to an internal error but fail to report though via the task/connector status (https://issues.redhat.com/browse/DBZ-380[DBZ-380]).

Please see the link:/docs/releases/#release-0-6-1[full change log] for more details and the complete list of fixed issues.

== What's next?

The work on Debezium 0.7 has already begun and we've merged the first set of changes.
You can expect to see support for using the https://github.com/eulerto/wal2json[wal2json] logical decoding plug-in with the Postgres connector, which will finally allow it to use Debezium with Postgres on Amazon RDS!
We've also started our explorations of providing a connector for Oracle (https://issues.redhat.com/browse/DBZ-20[DBZ-20]) and hope to report some progress here soon.

While the work on Debezium 0.7 continues, you will likely continue to see one or more 0.6.x bugfix releases.
We've automated the release process as much as possible, making it a breeze to ship a new release and getting fixes into your hands quickly.

If you'd like to contribute, please let us know.
We're happy about any help and will work with you to get you started quickly.
Check out the details below on how to get in touch.

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
