---
layout: post
title:  Debezium 0.5.1 Released
date:   2017-06-12 10:19:59 -0600
tags: [ releases, mysql, mongodb, postgres, docker ]
author: gmorling
---

It's my pleasure to announce the release of **Debezium 0.5.1**!

This release fixes several bugs in the link:/docs/connectors/mysql/[MySQL], link:/docs/connectors/postgresql/[Postgres] and link:/docs/connectors/mongodb/[MongoDB] connectors.
There's also support for some new datatypes: `POINT` on MySQL (https://issues.redhat.com/browse/DBZ-222[DBZ-222]) and `TSTZRANGE` on Postgres (https://issues.redhat.com/browse/DBZ-280[DBZ-280]).
This release is a drop-in replacement for 0.5.0, upgrading is recommended to all users.

Note that in the -- rather unlikely -- case that you happened to enable Debezium for all the system tables of MySQL,
any configured table filters will be applied to these system tables now, too (https://issues.redhat.com/browse/DBZ-242[DBZ-242]).
This may require an adjustment of your filters if you indeed wanted to capture all system tables but only selected non-system tables.

+++<!-- more -->+++

Please refer to the https://github.com/debezium/debezium/blob/master/CHANGELOG.md#051[changelog] for an overview of all the 29 issues fixed in Debezium 0.5.1.

The Docker image containing https://hub.docker.com/r/debezium/connect/[Kafka Connect and all the Debezium 0.5.x connectors]
as well as the image containing https://hub.docker.com/r/debezium/postgres/[Postgres and the Debezium logical decoding plug-in] have been updated to 0.5.1, too.

As Debezium continues to evolve and grow, the number of people contributing to the project is also going up.
The following people have sent in pull requests for this release:
https://github.com/arosenber[Aaron Rosenberg], https://github.com/CyberDem0n[Alexander Kukushkin], https://github.com/brendanmaguire[Brendan Maguire], https://github.com/DuncanSands[Duncan Sands], https://github.com/dasl-[David Leibovic], https://github.com/jpechane[Jiri Pechanec], https://github.com/nacivida[nacivida], https://github.com/omarsmak[Omar Al-Safi], https://github.com/rhauch[Randall Hauch] and https://github.com/tombentley[Tom Bentley].

Thanks a lot to you and everyone else in the community contributing via feature requests, bug reports, discussions and questions!

== What's next

We've planned to do further bug fix releases for the 0.5.x line.
Specifically, we'll release a fix for https://issues.redhat.com/browse/DBZ-217[DBZ-217] shortly,
which is about the MySQL connector stumbling when getting across a corrupt event in the binlog.

In parallel we're looking into Debezium connectors for https://issues.redhat.com/browse/DBZ-40[SQL Server] and https://issues.redhat.com/browse/DBZ-137[Oracle].
While we cannot promise anything yet in terms of when these will be ready to be published, we hope to have at least one of them ready some time soon.
Stay tuned and get involved!

