---
tags: [ releases, mysql, docker ]
---
= Debezium 0.4.0 Released
rhauch
:awestruct-tags: [ releases, mysql, docker ]
:awestruct-layout: blog-post

We're happy to announce that **Debezium 0.4.0** is now available for use with Kafka Connect 0.10.1.1. This release introduces a new link:/docs/connectors/postgresql/[PostgreSQL connector], and contains over a dozen fixes combined for the link:/docs/connectors/mongodb/[MongoDB connector] and link:/docs/connectors/mysql/[MySQL connector], including preliminar support for https://aws.amazon.com/rds/mysql/[Amazon RDS] and https://aws.amazon.com/rds/aurora/[Amazon Aurora (MySQL compatibility)]. See the link:/docs/releases/[release notes] for specifics on these changes. 

We've also created https://hub.docker.com/r/debezium/[Debezium Docker images] labelled `0.4` and `latest`, which we use in our link:/docs/tutorial/[tutorial].

Thanks to Horia, Chris, Akshath, Ramesh, Matthias, Anton, Sagi, barton, and others for their help with this release, issues, discussions, contributions, and questions!

== What's next

We'll continue to improve the MongoDB, MySQL, and PostgreSQL connectors and pushing out 0.4.x releases. We're also going to work on a few new connectors, though we'll likely increase the minor version with each new connector. Stay tuned and get involved!

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams, so applications can see and respond almost instantly to each committed row-level change in the databases. Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems. Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running, ensuring that all events are processed correctly and completely. Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try. Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter], or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community. All of the code is open source https://github.com/debezium/[on GitHub], so build the code locally and help us improve ours existing connectors and add even more connectors. If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
