---
layout: post
title:  Debezium 0.5.0 Released
date:   2017-03-27 10:19:59 -0600
tags: [ releases, mysql, mongodb, postgres, docker ]
author: rhauch
---

We're happy to announce that **Debezium 0.5.0** is now available for use with *Kafka Connect 0.10.2.0*. This release also includes a few fixes for the link:/docs/connectors/mysql/[MySQL connector]. See the link:/docs/releases/[release notes] for specifics on these changes, and be sure to check out the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with the version of the Kafka broker that you are using.

Kafka Connect 0.10.2.0 comes with a significant new feature called https://cwiki.apache.org/confluence/display/KAFKA/KIP-66%3A+Single+Message+Transforms+for+Kafka+Connect[Single Message Transforms], and you can now use them with Debezium connectors. SMTs allow you to modify the messages produced by Debezium connectors and any oher Kafka Connect source connectors, before those messages are written to Kafka. SMTs can also be used with Kafka Connect sink connectors to modify the messages _before_ the sink connectors processes them. You can use SMTs to filter out or mask specific fields, add new fields, modify existing fields, change the topic and/or topic partition to which the messages are written, and even more. And you can even chain multiple SMTs together.

Kafka Connect comes with a number of built-in SMTs that you can simply configure and use, but you can also create your own SMT implementations to do more complex and interesting things. For example, although Debezium connectors normally map all of the changes in each table (or collection) to separate topics, you can write a custom SMT that uses a completely different mapping between tables and topics and even add fields to message keys and/or values. Using your new SMT is also very easy - simply put it on the Kafka Connect classpath and update the connector configuration to use it.

We've also added https://hub.docker.com/r/debezium/[Debezium Docker images] labelled `0.5` and `latest`, which we use in our link:/docs/tutorial/[tutorial].

Thanks to Sanjay and everyone in the community for their help with this release, issues, discussions, contributions, and questions!

+++<!-- more -->+++

== What's next

We'll continue to improve the MongoDB, MySQL, and PostgreSQL connectors and pushing out 0.5.x releases with fixes. And we're still working on connectors for https://issues.redhat.com/browse/DBZ-40[SQL Server] and https://issues.redhat.com/browse/DBZ-137[Oracle]. Stay tuned and get involved!
