---
layout: post
title:  Debezium 0.5.2 Is Out
date:   2017-08-17 10:19:59 -0600
tags: [ releases, mysql, mongodb, postgres, docker ]
author: gmorling
---

I'm very happy to announce the release of **Debezium 0.5.2**!

As the previous release, the 0.5.2 release fixes several bugs in the link:/docs/connectors/mysql/[MySQL], link:/docs/connectors/postgresql/[Postgres] and link:/docs/connectors/mongodb/[MongoDB] connectors.
But there are also several new features and options:

* The `decimal.handling.mode` option already known from the MySQL connector is now also supported for PostgreSQL (https://issues.redhat.com/browse/DBZ-337[DBZ-337]).
It lets you control how `NUMERIC` and `DECIMAL` columns are represented in change events (either using Kafka's `Decimal` type or as `double`).
* The MongoDB connector supports the options `database.whitelist` and `database.blacklist` now (https://issues.redhat.com/browse/DBZ-302[DBZ-302])
* The PostgreSQL connector can deal with array-typed columns as well as with quoted identifiers for tables, schemas etc. (https://issues.redhat.com/browse/DBZ-297[DBZ-297], https://issues.redhat.com/browse/DBZ-298[DBZ-298])
* The Debezium Docker images run on Red Hat's https://www.openshift.com/[OpenShift] cloud environment (https://issues.redhat.com/browse/DBZ-267[DBZ-267])

+++<!-- more -->+++

Speaking about the Docker images, we've set up _nightly_ tags for the https://hub.docker.com/u/debezium/[Debezium images on Docker Hub],
allowing you to grab the latest improvements even before an official release has been cut.
The connector archives are also deployed to the https://oss.sonatype.org/content/repositories/snapshots/io/debezium/[Sonatype OSS Maven repository].

Finally, we've spent some time to extend the documentation on some things not covered before:

* https://debezium.io/docs/configuration/avro/[Avro Serialization] describes how to use the use the Avro converter and the Confluent Schema Registry instead of the JSON converter instead of the default JSON converter for serializing change events, resulting in much smaller message sizes;
The Avro converter itself has also been added to the Debezium Docker image for Kafka Connect, so you can use it right away
* https://debezium.io/docs/configuration/topic-routing/[Topic Routing] describes how to use Debezium's `ByLogicalTableRouter` single message transformation (SMT) for routing the change events from multiple tables into a single topic, which for instance is very useful when working with sharded tables

Please refer to the https://github.com/debezium/debezium/blob/master/CHANGELOG.md#052[changelog] for an overview of all the 19 issues fixed in Debezium 0.5.2.

The following people from the community have sent in pull requests for this release:
https://github.com/emrul[Emrul Islam], https://github.com/ekreiser[Eric S. Kreiser], https://github.com/xenji[Mario Mueller], https://github.com/mcapitanio[Matteo Capitanio], https://github.com/omarsmak[Omar Al-Safi] and https://github.com/Satyajitv[Satyajit Vegesna].

Thanks a lot to you and everyone else in the community for contributing to Debezium via feature requests, bug reports, discussions and questions!

== What's next

The next version of Debezium will be 0.6 (planned for September).
This release is planned to bring the upgrade to Kafka 0.11.
We'll also look into an SMT for transforming the change events emitted by Debezium into a flat representation, which for instance will be very useful in conjunction with the JDBC sink connector.

While 0.6 is planned to be more of a "stabilization release", 0.7 should bring a long-awaited major feature:
we've planned to explore support for Oracle and hopefully will do an initial release of a Debezium connector for that database.

In other words, exciting times are ahead!
If you'd like to get involved, let us know.
Check out the details below on how to get in touch.
