---
layout: post
title:  Debezium 0.4.0 Released
date:   2017-02-07 10:19:59 -0600
tags: [ releases, mysql, docker ]
author: rhauch
---

We're happy to announce that **Debezium 0.4.0** is now available for use with Kafka Connect 0.10.1.1. This release introduces a new link:/docs/connectors/postgresql/[PostgreSQL connector], and contains over a dozen fixes combined for the link:/docs/connectors/mongodb/[MongoDB connector] and link:/docs/connectors/mysql/[MySQL connector], including preliminar support for https://aws.amazon.com/rds/mysql/[Amazon RDS] and https://aws.amazon.com/rds/aurora/[Amazon Aurora (MySQL compatibility)]. See the link:/docs/releases/[release notes] for specifics on these changes. 

We've also created https://hub.docker.com/r/debezium/[Debezium Docker images] labelled `0.4` and `latest`, which we use in our link:/docs/tutorial/[tutorial].

Thanks to Horia, Chris, Akshath, Ramesh, Matthias, Anton, Sagi, barton, and others for their help with this release, issues, discussions, contributions, and questions!

+++<!-- more -->+++

== What's next

We'll continue to improve the MongoDB, MySQL, and PostgreSQL connectors and pushing out 0.4.x releases. We're also going to work on a few new connectors, though we'll likely increase the minor version with each new connector. Stay tuned and get involved!
