---
layout: post
title:  Debezium 0.4.1 Released
date:   2017-03-17 10:19:59 -0600
tags: [ releases, mysql, mongodb, rds, docker ]
author: rhauch
---

We're happy to announce that **Debezium 0.4.1** is now available for use with Kafka Connect 0.10.1.1. This release includes several fixes for the link:/docs/connectors/mongodb/[MongoDB connector] and link:/docs/connectors/mysql/[MySQL connector], including improved support for https://aws.amazon.com/rds/mysql/[Amazon RDS] and https://aws.amazon.com/rds/aurora/[Amazon Aurora (MySQL compatibility)]. See the link:/docs/releases/[release notes] for specifics on these changes. 

We've also updated the https://hub.docker.com/r/debezium/[Debezium Docker images] labelled `0.4` and `latest`, which we use in our link:/docs/tutorial/[tutorial].

Thanks to Jan, Horia, David, Josh, Johan, Sanjay, Saulius, and everyone in the community for their help with this release, issues, discussions, contributions, and questions!

+++<!-- more -->+++

== What's next

Kafka 0.10.2.0 is out, so we plan to release 0.5.0 next week with all of the changes/fixes in 0.4.1 but with support for Kafka 0.10.2.0. We'll then continue to improve the MongoDB, MySQL, and PostgreSQL connectors and pushing out 0.5.x releases. Stay tuned and get involved!
