---
tags: [ releases, mysql, mongodb, postgres, docker ]
---
= Debezium 0.7.1 Is Released
jpechane
:awestruct-tags: [ releases, mysql, mongodb, postgres, docker ]
:awestruct-layout: blog-post

Just last few days before Christmas we are releasing Debezium  *0.7.1*!
This is a bugfix release that fixes few annoying issues that were found during first rounds of use of Debezium 0.7 by our community.
All issues relate to either newly provided wal2json support or reduced risk of internal race condition improvement.

https://github.com/rcoup[Robert Coup] has found a https://issues.redhat.com/browse/DBZ-512[performance regression] in situations when 0.7.0 was used with old version of Protobuf decoder.

Suraj Savita (and others) has found an issue when our code failed to https://issues.redhat.com/browse/DBZ-513[correctly detect] it runs with Amazon RDS wal2json plug-in.
We are outsmarted by the JDBC driver internals and included a distinct plugin decoder name https://issues.redhat.com/browse/DBZ-517[wal2json_rds] that bypasses detection routine and by default expects it runs against Amazon RDS instance. This mode should be used only with RDS instances.

We have also gathered feedback from first tries to run with Amazon RDS and included link:/docs/connectors/postgresql/#amazon-rds[a short section] in our documentation on this topic.

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
