---
tags: [ releases, mysql, mongodb, postgres, docker ]
---
= Debezium 0.8.3.Final Released
gmorling
:awestruct-tags: [ releases, mysql, mongodb, postgres, docker ]
:awestruct-layout: blog-post

As temperatures are cooling off, the Debezium team is getting into full swing again and we're happy to announce the release of Debezium *0.8.3.Final*!

This is a bugfix release to the current stable release line of Debezium, 0.8.x, while the work on Debezium 0.9 goes on in parallel.
There are link:/docs/releases/#release-0-8-3-final[14 fixes] in this release.
As in earlier 0.8.x releases, we've further improved the new Antlr-based DDL parser used by the link:/docs/connectors/mysql/[MySQL connector] (see https://issues.redhat.com/browse/DBZ-901[DBZ-901], https://issues.redhat.com/browse/DBZ-903[DBZ-903] and https://issues.redhat.com/browse/DBZ-910[DBZ-910]).

The link:/docs/connectors/postgres/[Postgres connector] saw a huge improvement to its start-up time for databases with lots of custom types (https://issues.redhat.com/browse/DBZ-899[DBZ-899]).
The user reporting this issue had nearly 200K entries in pg_catalog.pg_type, and due to an N + 1 SELECT issue within the Postgres driver itself, this caused the connector to take 24 minutes to start.
By using a custom query for obtaining the type metadata, we were able to cut down this time to 5 seconds!
Right now we're working with the maintainers of the Postgres driver to get this issue fixed upstream, too.

== More Flexible Propagation of DELETEs

Besides those bug fixes we decided to also merge one new feature from the 0.9.x branch into the 0.8.3.Final release,
which those of you may find useful who are using the link:/docs/configuration/event-flattening/[SMT for extracting the "after" state] from change events (https://issues.redhat.com/browse/DBZ-857[DBZ-857]).

This SMT can be employed to stream changes to sink connectors which expect just a "flat" row representation of data instead of Debezium's complex event structure.
Not all sink connectors support the handling of deletions, though.
E.g. some connectors will fail when encountering tombstone events.
Therefore the SMT can now optionally rewrite delete events into updates of a special "deleted" marker field.

For that, set the `delete.handling.mode` option of the SMT to "rewrite":

[source,json]
----
...
"transforms" : "unwrap",
"transforms.unwrap.type": "io.debezium.transforms.UnwrapFromEnvelope",
"transforms.unwrap.delete.handling.mode" : "rewrite",
...
----

When a DELETE event is propagated, the "__deleted" field of outgoing records will be set to true.
So when for instance consuming the events with the JDBC sink connector, you'd see this being reflected in a corresponding column in the sink tables:

[source]
----
__deleted | last_name |  id  | first_name |         email
-----------+-----------+------+------------+-----------------------
false     | Thomas    | 1001 | Sally      | sally.thomas@acme.com
false     | Bailey    | 1002 | George     | gbailey@foobar.com
false     | Kretchmar | 1004 | Anne       | annek@noanswer.org
true      | Walker    | 1003 | Edward     | ed@walker.com
----

You then for instance can use a batch job running on your sink to remove all records flagged as deleted.

== What's next?

We're continuing the work on Debezium 0.9, which will mostly be about improvements to the SQL Server and Oracle connectors.
The current plan is to do the next 0.9 release (either Alpha2 or Beta1) in two weeks from now.

Also it's the beginning of the conference season, so we'll spend some time with preparing demos and presenting Debezium at multiple locations.
There will be sessions on change data capture with Debezium a these conferences:

* https://jug-saxony-day.org/programm/#!/P31[JUG Saxony Day]; Dresden, Germany; Sept. 28
* https://kafka-summit.org/sessions/change-data-streaming-patterns-microservices-debezium/[Kafka Summit]; San Francisco, Cal.; Oct. 17
* https://vxdms2018.confinabox.com/talk/INI-9172/Data_Streaming_for_Microservices_using_Debezium[VoxxedDays Microservices]; Paris, France; Oct. 29 - 31
* https://cfp.devoxx.ma/2018/talk/AEY-4477/Change_Data_Streaming_Patterns_for_Microservices_With_Debezium[Devoxx Morocco]; Marrakesh, Morocco; Nov. 27 - 29

If you are at any of these conferences, come and say Hi;
we'd love to exchange with you about your use cases, feature requests, feedback on our link:/docs/roadmap/[roadmap] and any other ideas around Debezium.

Finally, a big "Thank You" goes to our fantastic community members https://github.com/jchipmunk[Andrey Pustovetov], https://github.com/maver1ck[Maciej Bryński] and https://github.com/PengLyu[Peng Lyu] for their contributions to this release!

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
