---
layout: post
title:  Debezium 0.9 Alpha1 and 0.8.1 Released
date:   2018-07-26 10:19:59 -0600
tags: [ releases, postgres, oracle, docker, sqlserver ]
author: gmorling
---

Just two weeks after the Debezium 0.8 release, I'm very happy to announce the release of Debezium *0.9.0.Alpha1*!

The main feature of the new version is a first work-in-progress version of the long-awaited Debezium connector for https://www.microsoft.com/en-us/sql-server[MS SQL Server].
Based on the https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/about-change-data-capture-sql-server?view=sql-server-2017[CDC functionality] available in the Enterprise and Standard editions,
the new connector lets you stream data changes out of Microsoft's popular RDBMS.

Besides that we've continued the work on the Debezium link:/docs/connectors/oracle/[Oracle connector].
Most notably, it supports initial snapshots of captured tables now.
We've also upgraded Apache Kafka in our Docker images to 1.1.1 (https://issues.redhat.com/browse/DBZ-829[DBZ-829]).

Please take a look at the link:/docs/releases/#release-0-9-0-alpha1[change log] for the complete list of changes in 0.9.0.Alpha1 and general upgrade notes.

_Note:_ [.line-through]#At the time of writing (2018-07-26), the release artifacts (connector archives) are available on http://central.maven.org/maven2/io/debezium/[Maven Central].
We'll upload the Docker images for 0.9.0.Alpha1 to https://hub.docker.com/u/debezium/[Docker Hub] as soon as possible.#
The Docker images are already uplodaded and ready for use under tags `0.9.0.Alpha1` and rolling `0.9`.

+++<!-- more -->+++

== SQL Server Connector

Support for SQL Server had been on the wish list of Debezium users for a long time (the original issue was https://issues.redhat.com/browse/DBZ-40[DBZ-40]).
Thanks to lots of basic infrastructure created while working on the Oracle connector,
we were finally able to come up with a first preview of this new connector in comparatively short time of development.

Just as the Oracle connector, the one for SQL Server is under active development and should be considered an incubating feature at this point.
So for instance the structure of emitted change messages may change in upcoming releases.
In terms of features, it supports initial snapshotting and capturing changes via SQL Server's CDC functionality.
There's support for the most common column types, table whitelisting/blacklisting and more.
The most significant feature missing is support for structural changes of tables while the connector is running.
This is the next feature we'll work on and it's planned to be delivered as part of the next 0.9 release (see https://issues.redhat.com/browse/DBZ-812[DBZ-812]).

We'd be very happy to learn about any feedback you may have on this newest connector of the Debezium family.
If you spot any bugs or have feature requests for it, please create a report in our https://issues.redhat.com/browse/DBZ[JIRA tracker].

== Oracle Connector

The Debezium connector for Oracle is able to take initial snapshots now.
By means of the new connector option `snapshot.mode` you can control whether _read_ events for all the records of all the captured tables should be emitted.

In addition the support for numeric data types has been honed (https://issues.redhat.com/browse/DBZ-804[DBZ-804]);
any integer columns (i.e. `NUMBER` with a scale <\= 0) will be emitted using the corresponding `int8`/`int16`/`int32`/`int64` field type,
if the columns precision allows for that.

We've also spent some time on expanding the Oracle link:/docs/connectors/oracle/[connector documentation],
which covers the structure of emitted change events and all the data type mappings in detail now.

== Debezium 0.8.1.Final

Together with Debezium 0.9.0.Alpha1 we also did another release of the current stable Debezium version 0.8.

While 0.9 at this point is more interesting to those eager to try out the latest developments in the Oracle and SQL Server connectors,
0.8.1.Final is a recommended upgrade especially to the users of the Postgres connector.
This release fixes an issue where it could happen that WAL segments on the server were retained longer than necessary,
in case only records of non-whitelisted tables changed for a while.
This has been addressed by means of supporting heartbeat messages (as already known from the MySQL connector) also for Postgres (https://issues.redhat.com/browse/DBZ-800[DBZ-800]).
This lets the connector regularly commit offsets to Kafka Connect which also serves as the hook to acknowledge processed LSNs with the Postgres server.

You can find the list of all changes done in Debezium 0.8.1.Final in the link:/docs/releases/#release-0-8-1-final[change log].

== What's next?

As discussed above, we'll work on supporting structural changes to captured tables while the SQL Server connector is running.
The same applies to the Oracle connector.
This will require some work on our DDL parsers, but thanks to the foundations provided by our recent migration of the MySQL DDL parser to Antlr, this should be manageable.

The other big focus of work with be to provide an alternative implementation for getting changes from Oracle which isn't based on the XStream API.
We've done some experiments with LogMiner and are also actively exploring further alternatives.
While some details are still unclear, we are optimistic to have something to release in this area soon.

If you'd like to learn more about some middle and long term ideas, please check out our link:/docs/roadmap/[roadmap].
Also please get in touch with us if you got any ideas or suggestions for future development.
