---
layout: post
title:  Debezium 0.8.0.CR1 Is Released
date:   2018-07-04 10:19:59 -0600
tags: [ releases, mysql, postgres, mongodb, oracle, docker ]
author: gmorling
---

A fantastic Independence Day to all the Debezium users in the U.S.!
But that's not the only reason to celebrate: it's also with great happiness that I'm announcing the release of Debezium *0.8.0.CR1*!

Following our new link:/blog/2018/06/21/debezium-0-8-0-beta1-released/[release scheme],
the focus for this candidate release of Debezium 0.8 has been to fix bug reported for last week's Beta release,
accompanied by a small number of newly implemented features.

Thanks a lot to everyone testing the new Antlr-based DDL parser for the MySQL connector;
based on the issues you reported, we were able to fix a few bugs in it.
As announced recently, for 0.8 the legacy parser will remain the default implementation,
but you are strongly encouraged to test out the new one
(by setting the connector option `ddl.parser.mode` to `antlr`) and report any findings you may have.
We've planned to switch to the new implementation by default in Debezium 0.9.

+++<!-- more -->+++

In terms of new features, the CR1 release brings support for `CITEXT` columns in the Postgres connector (https://issues.redhat.com/browse/DBZ-762[DBZ-762]).
All the relational connectors support it now to convey the original name and length of captured columns using schema parameters in the emitted change messages (https://issues.redhat.com/browse/DBZ-644[DBZ-644]).
This can come in handy to properly size columns in a sink database for types such as `VARCHAR`.

Thanks a lot to the following community members who contributed to this release:
https://github.com/abergmeier[Andreas Bergmeier],
https://github.com/olavim[Olavi Mustanoja] and
https://github.com/orrganani[Orr Ganani].

Please take a look at the link:/docs/releases/#release-0-8-0-cr-1[change log] for the complete list of changes in 0.8.0.CR1 and general upgrade notes.

== What's next?

Barring any unforeseen issues and critical bug reports, we'll release Debezium 0.8.0.Final next week.

Once that's out, we'll continue work on the Oracle connector (e.g. exploring alternatives to using XStream for ingesting changes from the database as well as initial snapshotting),
which remains a "tech preview" component as of 0.8.

We'll also work towards a connector for SQL Server (see https://issues.redhat.com/browse/DBZ-40[DBZ-40]),
for which the first steps just have been made today by preparing a Docker-based setup with a CDC-enabled SQL Server instance,
allowing to implement and test the connector in the following.

To find out about some more long term ideas, please check out our link:/docs/roadmap/[roadmap] and get in touch with us, if you got any ideas or suggestions for future development.
