---
layout: post
title:  Debezium 0.7.4 Is Released
date:   2018-03-07 10:19:59 -0600
tags: [ releases, mysql, postgres, docker ]
author: gmorling
---

It's my pleasure to announce the release of Debezium *0.7.4*!

Continuing the 0.7 release line, this new version brings several bug fixes and a handful of new features.
We recommend this upgrade to all users.
When upgrading from earlier versions,
please check out the link:/docs/releases/[release notes] of all versions between the one you're currently on and 0.7.4 in order to learn about any steps potentially required for upgrading.

+++<!-- more -->+++

== New features

In terms of new features, there's a new mode for handling decimal columns in Postgres and MySQL (https://issues.redhat.com/browse/DBZ-611[DBZ-611]).
By setting the `decimal.handling.mode` connector option to `string`, Debezium will emit decimal and numeric columns as Strings.
That oftentimes is easier to handle for consumers than the byte-array based representation used by default, while keeping the full precision.
As a bonus, `string` also allows to convey the special numeric values `NaN` and `Infinity` as supported by Postgres.
Note that this functionality required an update to Debezium's logical decoding plug-in which runs within the Postgres database server.
This plug-in must be upgraded to the new version _before_ upgrading the Debezium Postgres connector.

Speaking of byte arrays, the `BYTEA` column type in Postgres is now also supported (https://issues.redhat.com/browse/DBZ-605[DBZ-605]).

For the MySQL connector, there's a new option to the snapshotting routine: `snapshot.locking.mode` (https://issues.redhat.com/browse/DBZ-602[DBZ-602]).
By setting this to `NONE`, this option allows to skip any table locks during snapshotting.
This should be used if and only if you're absolutely sure that the tables don't undergo structural changes (columns added, removed etc.)
while the snapshot is taken.
But if that's guaranteed, the new mode can be a useful tool for increasing overall system performance, as writes by concurrent processes won't be blocked.
That's especially useful on environments such as Amazon RDS, where the connector otherwise would be required to keep a lock for the entirety of the snapshot.
The new option supersedes the existing `snapshot.minimal.locks` option.
Please see the connector documentation for link:/docs/connectors/mysql/#connector-properties[the details].
This feature was contributed by our community member https://github.com/Crim[Stephen Powis]; many thanks to you!

== Bug Fixes

0.7.4 brings multiple fixes related to how numeric columns are handled.
E.g. columns without scale couldn't correctly be processed by the MySQL connector during binlog reading (https://issues.redhat.com/browse/DBZ-615[DBZ-615]).
That's fixed now.
And when using the Postgres connector, arbitrary precision column values are correctly converted into change data message fields now (https://issues.redhat.com/browse/DBZ-351[DBZ-351]).

We also noticed a regression introduced in Debezium 0.6:
the field schema for `NUMERIC` columns was always marked as optional, also if that column was actually declared as `NOT NULL`.
The same affected geo-spatial array types on Postgres as supported as of Debezium 0.7.
This has been fixed with https://issues.redhat.com/browse/DBZ-635[DBZ-635].
We don't expect any impact on consumers by this change
(just as before, they'll always get a value for such field, only its schema won't be incorrectly marked as optional any more).

Please see the link:/docs/releases/#release-0-7-4[full change log] for more details and the complete list of issues fixed in Debezium 0.7.4.

== What's next?

Following our three weeks release cadence, the next Debezium release is planned for March 28th.
We got some exciting changes in the works for that:
if things go as planned, we'll release the first version of our Oracle connector (https://issues.redhat.com/browse/DBZ-20[DBZ-20]).
This will be based on the Oracle XStream API in the first iteration and not support snapshots yet.
But we felt it'd make sense to roll out this connector incrementally, so to get out the new feature early on and collect feedback on it.
We've also planned to explore alternatives to using the XStream API in future releases.

Another great new feature will be http://www.reactive-streams.org/[Reactive Streams] support (https://issues.redhat.com/browse/DBZ-566[DBZ-566]).
Based on top of the existing link:/docs/embedded/[embedded mode],
this will make it very easy to consume change data events using Reactive Streams implementations such as RxJava 2, the Java 9 Flow API and many more.
It'll also be very useful to consume change events in reactive frameworks such as Vert.x.
We're really looking forward to shipping this feature and already have a pending https://github.com/debezium/debezium/pull/458[pull request] for it.
If you like, take a look and let us know about your feedback!

Please also check out our link:/docs/roadmap/[roadmap] for the coming months of Debezium's development.
This is our current plan for the things we'll work on,
but it's not cast in stone, so please tell us about your feature requests by sending a message to our Google group.
We're looking forward to your feedback!
