---
tags: [ releases, mysql, mongodb, postgres, sqlserver, oracle, docker ]
---
= Debezium 0.9.0.Beta1 Released
gmorling
:awestruct-tags: [ releases, mysql, mongodb, postgres, sqlserver, oracle, docker ]
:awestruct-layout: blog-post

It's my pleasure to announce the release of Debezium *0.9.0.Beta1*!
Oh, and to those of you who are celebrating it -- Happy Thanksgiving!

This new Debezium release comes with several great improvements to our work-in-progress SQL Server connector:

* Initial snapshots can be done using the `snapshot` isolation level if enabled in the DB (https://issues.redhat.com/browse/DBZ-941[DBZ-941])
* Changes to the structures of captured tables after the connector has been set up are supported now (https://issues.redhat.com/browse/DBZ-812[DBZ-812])
* New connector option `decimal.handling.mode` (https://issues.redhat.com/browse/DBZ-953[DBZ-953]) and pass-through of any `database.*` option to the JDBC driver (https://issues.redhat.com/browse/DBZ-964[DBZ-964])

Besides that, we spent some time on supporting the latest versions of the different databases.
The Debezium connectors now support Postgres 11 (https://issues.redhat.com/browse/DBZ-955[DBZ-955]) and MongoDB 4.0 (https://issues.redhat.com/browse/DBZ-974[DBZ-974]).
We are also working on supporting MySQL 8.0, which should be completed in the next 0.9.x release.
The Debezium container images have been updated to Kafka 2.0.1 (https://issues.redhat.com/browse/DBZ-979[DBZ-979])
and the Kafka Connect image now supports the `STATUS_STORAGE_TOPIC` environment variable,
bringing consistency with `CONFIG_STORAGE_TOPIC` and `OFFSET_STORAGE_TOPIC` that already were supported before (https://issues.redhat.com/browse/DBZ-893[DBZ-893]).

As usual, several bugs were fixed, too.
Several of them dealt with the new Antlr-based DDL parser for the MySQL connector.
By now we feel confident about its implementation, so it's the default DDL parser as of this release (https://issues.redhat.com/browse/DBZ-757[DBZ-757]).
If you would like to continue to use the legacy parser for some reason, you can do so by setting the `ddl.parser.mode` connector option to "legacy".
This implementation will remain available in the lifetime of Debezium 0.9.x and is scheduled for removal after that.
So please make sure to log issues in JIRA should you run into any problems with the Antlr parser.

Overall, this release contains link:/docs/releases/#release-0-9-0-beta1[21 fixes].
Thanks a lot to all the community members who helped with making this happen:
https://github.com/anton-martynov[Anton Martynov],
https://github.com/deepakbarr[Deepak Barr],
https://github.com/grzegorz8[Grzegorz Kołakowski],
https://github.com/olavim[Olavi Mustanoja],
https://github.com/renatomefi[Renato Mefi],
https://github.com/vamossagar12[Sagar Rao] and
https://github.com/shivamsharma[Shivam Sharma]!

== What else?

While the work towards Debezium 0.9 continues, we've lately been quite busy with presenting Debezium at multiple conferences.
You can find the slides and recordings from https://kafka-summit.org/sessions/change-data-streaming-patterns-microservices-debezium/[Kafka Summit] San Francisco and https://vxdms2018.confinabox.com/talk/INI-9172/Data_Streaming_for_Microservices_using_Debezium[Voxxed Days Microservices] on our list of link:/docs/online-resources/[online resources] around Debezium.

There you also can find the links to the slides of the great talk "The Why’s and How’s of Database Streaming" by Joy Gao of WePay, a Debezium user of the first hour,
as well as the link to a blog post by Hans-Peter Grahsl about setting up a CDC pipeline from MySQL into Cosmos DB running on Azure.
If you know about other great articles, session recordings or similar on Debezium and change data capture which should be added there, please let us know.

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
