---
layout: post
title:  Debezium 0.9.0.Alpha2 Released
date:   2018-10-04 10:19:59 -0600
tags: [ releases, mysql, mongodb, postgres, sqlserver, oracle, docker ]
author: gmorling
---

It's my pleasure to announce the release of Debezium *0.9.0.Alpha2*!

While the work on the connectors for SQL Server and Oracle continues, we decided to do another Alpha release,
as lots of fixes and new features - many of them contributed by community members - have piled up,
which we wanted to get into your hands as quickly as possible.

This release supports Apache Kafka 2.0, comes with support for Postgres' HSTORE column type, allows to rename and filter fields from change data messages for MongoDB
and contains multiple bug fixes and performance improvements.
Overall, this release contains link:/docs/releases/#release-0-9-0-alpha2[55 fixes]
(note that a few of these have been merged back to 0.8.x and are contained in earlier 0.8 releases, too).

A big "Thank You" is in order to community members
https://github.com/jchipmunk[Andrey Pustovetov],
https://github.com/artiship[Artiship Artiship],
https://github.com/CliffWheadon[Cliff Wheadon],
https://github.com/deepakbarr[Deepak Barr],
https://github.com/ian-axelrod[Ian Axelrod],
https://github.com/ooooorz[Liu Hanlin],
https://github.com/maver1ck[Maciej Bryński],
https://github.com/oripwk[Ori Popowski],
https://github.com/PengLyu[Peng Lyu],
https://github.com/PSanetra[Philip Sanetra],
https://github.com/sagarrao[Sagar Rao] and
https://github.com/SyedMuhammadSufyian[Syed Muhammad Sufyian]
for their contributions to this release.
We salute you!

+++<!-- more -->+++

== Kafka Upgrade

Debezium runs with and has been tested on top of the recently released Apache Kafka 2.0 (https://issues.redhat.com/browse/DBZ-858[DBZ-858]).
The widely used version Kafka 1.x continues to be supported as well.

Note that 0.10.x is not supported due to Debezium's usage of the admin client API which is only available in later versions.
It shouldn't be too hard to work around this, so if someone is interested in helping out with this,
this would be a great contribution (see https://issues.redhat.com/browse/DBZ-883[DBZ-883]).

== Support for HSTORE columns in Postgres

Postgres is an amazingly powerful and flexible RDBMS, not the least due to its wide range of column types which go far beyond what's defined by the SQL standard.
One of these types being https://www.postgresql.org/docs/current/static/hstore.html[HSTORE], which is a string-to-string map essentially.

Debezium can capture changes to columns of this type now (https://issues.redhat.com/browse/DBZ-898[DBZ-898]).
By default, the field values will be represented using Kafka Connect's map data type.
As this may not be supported by all sink connectors,
you might alternatively represent them as a string-ified JSON by setting the new `hstore.handling.mode` connector option to `json`.
In this case, you'd see HSTORE columns represented as values in change messages like so: `{ "key1" : "val1", "key2" : "val2" }`.

== Field filtering and renaming for MongoDB

Unlike the connectors for MySQL and Postgres, the Debezium MongoDB connector so far didn't allow to exclude single fields of captured collections from CDC messages.
Also renaming them wasn't supported e.g. by means of Kafka's `ReplaceField` SMT.
The reason being that MongoDB doesn't mandate a fixed schema for the documents of a given collection,
and documents therefore are represented in change messages using a single string-ified JSON field.

Thanks to the fantastic work of community member Andrey Pustovetov,
this finally has changed, i.e. you can remove given fields (https://issues.redhat.com/browse/DBZ-633[DBZ-633]) now from the CDC messages of given collections or have them renamed (https://issues.redhat.com/browse/DBZ-881[DBZ-881]).
Please refer to the description of the new connector options `field.blacklist` and `field.renames` in the link:/docs/connectors/mongodb/[MongoDB connector documentation] to learn more.

== Extended source info

Another contribution by Andrey is the new optional `connector` field within the source info block of CDC messages
(https://issues.redhat.com/browse/DBZ-918[DBZ-918]).
This tells the type of source connector that produced the messages ("mysql", "postgres" etc.),
which can come in handy in cases where specific semantics need to be applied on the consumer side depending on the type of source database.

== Bug fixes and version upgrades

The new release contains a good number of bug fixes and other smaller improvements.
Amongst them are

* correct handling of invalid temporal default values with MySQL (https://issues.redhat.com/browse/DBZ-927[DBZ-927]),
* support for table/collection names with special characters for MySQL (https://issues.redhat.com/browse/DBZ-878[DBZ-878]) and MongoDB (https://issues.redhat.com/browse/DBZ-865[DBZ-865]) and
* fixed handling of blacklisted tables with the new Antlr-based DDL parser (https://issues.redhat.com/browse/DBZ-872[DBZ-872]).

Community member Ian Axelrod provided a fix for a potential performance issue,
where changes to tables with TOAST columns in Postgres would cause repeated updates to the connector's internal schema metadata,
which can be a costly operation (https://issues.redhat.com/browse/DBZ-911[DBZ-911]).
Please refer to the link:/docs/connectors/postgresql/[Postgres connector documentation] for details on the new `schema.refresh.mode` option,
which deals with this issue.

In terms of version upgrades we migrated to the latest releases of the MySQL (https://issues.redhat.com/browse/DBZ-763[DBZ-763], https://issues.redhat.com/browse/DBZ-764[DBZ-764]) and Postgres drivers (https://issues.redhat.com/browse/DBZ-912[DBZ-912]).
The former is part of a longer stream of work leading towards support of MySQL 8 which should be finished in one of the next Debezium releases.
For Postgres we provide a Docker image with Debezium's supported logical decoding plug-ins based on Alpine now,
which might be interesting to those concerned about container size (https://issues.redhat.com/browse/DBZ-705[DBZ-705]).

Please see the change log for the complete list of fixed issues.

== What's next?

The work towards Debezium 0.9 continues, and we'll focus mostly on improvements to the SQL Server and Oracle connectors.
Other potential topics include support for MySQL 8 and native logical decoding as introduced with Postgres 10,
which should greatly help with using the Debezium Postgres connectors in cloud environments such as Amazon RDS.

We'll also be talking about Debezium at the following conferences:

* https://kafka-summit.org/sessions/change-data-streaming-patterns-microservices-debezium/[Kafka Summit]; San Francisco, Cal.; Oct. 17
* https://vxdms2018.confinabox.com/talk/INI-9172/Data_Streaming_for_Microservices_using_Debezium[VoxxedDays Microservices]; Paris, France; Oct. 29 - 31
* https://cfp.devoxx.ma/2018/talk/AEY-4477/Change_Data_Streaming_Patterns_for_Microservices_With_Debezium[Devoxx Morocco]; Marrakesh, Morocco; Nov. 27 - 29

Already last week I had the opportunity to present Debezium at https://jug-saxony-day.org/programm/#!/P31[JUG Saxony Day].
If you are interested, you can find the (German) https://speakerdeck.com/gunnarmorling/streaming-von-datenbankanderungen-mit-debezium-jug-saxony-day[slideset of that talk] on Speaker Deck.
