---
layout: post
title:  Debezium 0.8 Final Is Released
date:   2018-07-12 10:19:59 -0600
tags: [ releases, mysql, postgres, mongodb, oracle, docker ]
author: gmorling
---

I'm very happy to announce the release of Debezium *0.8.0.Final*!

The key features of Debezium 0.8 are the first work-in-progress version of our link:/docs/connectors/oracle/[Oracle connector]
(based on the XStream API) and a brand-new parser for MySQL DDL statements.
Besides that, there are plenty of smaller new features (e.g. propagation of default values to corresponding Connect schemas,
optional propagation of source queries in CDC messages and a largely improved SMT for sinking changes from MongoDB into RDBMS)
as well as lots of bug fixes (e.g. around temporal and numeric column types, large transactions with Postgres).

Please see the previous announcements (link:/blog/2018/06/21/debezium-0-8-0-beta1-released/[Beta 1], link:/blog/2018/07/04/debezium-0-8-0-cr1-released/[CR 1])
to learn about all the changes in more depth.
The Final release largely resembles CR1;
apart from further improvements to the Oracle connector (https://issues.redhat.com/browse/DBZ-762[DBZ-792]) there's one nice addition to the MySQL connector contributed by https://github.com/pgoranss[Peter Goransson]:
when doing a snapshot, it will now expose information about the processed rows via JMX (https://issues.redhat.com/browse/DBZ-789[DBZ-789]), which is very handy when snapshotting larger tables.

Please take a look at the link:/docs/releases/#release-0-8-0-final[change log] for the complete list of changes in 0.8.0.Final and general upgrade notes.

+++<!-- more -->+++

== What's next?

We're continuing our work on the Oracle connector.
The work on initial snapshotting is well progressing and it should be part of the next release.
Other improvements will be support for structural changes to captured tables after the initial snapshot has been made,
more extensive source info metadata and more.
Please track https://issues.redhat.com/browse/DBZ-716[DBZ-716] for this work; the improvements are planned to be released incrementally in the upcoming versions of Debezium.

We've also started to explore ingesting changes via LogMiner.
This is more involved in terms of engineering efforts than using XStream, but it comes with the huge advantage of not requiring a separate license
(LogMiner comes with the Oracle database itself).
It's not quite clear yet when we can release something on this front, and we're also actively exploring further alternatives.
But we are quite optimistic and hope to have something some time soon.

The other focus of work is a connector for SQL Server (see https://issues.redhat.com/browse/DBZ-40[DBZ-40]).
Work on this has started as well, and there should be an Alpha1 release of Debezium 0.9 with a first drop of that connector within the next few weeks.

To find out about some more long term ideas, please check out our link:/docs/roadmap/[roadmap] and get in touch with us, if you got any ideas or suggestions for future development.
