---
tags: [ releases, mysql, postgres, mongodb, docker ]
---
= Debezium 0.7.5 Is Released
gmorling
:awestruct-tags: [ releases, mysql, postgres, mongodb, docker ]
:awestruct-layout: blog-post

It's my pleasure to announce the release of Debezium *0.7.5*!

This is a bugfix release to the 0.7 release line, which we decided to do while working towards Debezium 0.8.
Most notably it fixes an unfortunate bug introduced in 0.7.3 (https://issues.redhat.com/browse/DBZ-663[DBZ-663]),
where the internal database history topic of the Debezium MySQL connector could be partly deleted under some specific conditions.
Please see the link:/2018/03/16/note-on-database-history-topic-configuration/[dedicated blog post] on this issue to find out whether this affects you and what you should do to prevent this issue.

Together with this, we released a couple of other fixes and improvements.
Thanks to https://github.com/maver1ck[Maciej Brynski], the performance of the link:/docs/configuration/topic-routing/[logical table routing SMT] has been improved significantly (https://issues.redhat.com/browse/DBZ-655[DBZ-655]).
Another fix contributed by Maciej is for https://issues.redhat.com/browse/DBZ-646[DBZ-646] which lets the MySQL connector handle `CREATE TABLE` statements for the TokuDB storage engine now.

And we got some more bugfixes by our fantastic community:
Long-term community member https://github.com/pgoranss[Peter Goransson] fixed an issue about the snapshot JMX metrics of the MySQL connector,
which are now also accessible after the snapshot has been completed (https://issues.redhat.com/browse/DBZ-640[DBZ-640]).
https://github.com/atongen[Andrew Tongen] spotted and fixed an issue for the Debezium embedded engine (https://issues.redhat.com/browse/DBZ-665[DBZ-665]) which caused offsets to be committed more often than needed.
And https://github.com/matzew[Matthias Wessendorf] upgraded the Debezium dependencies and Docker images to Apache Kafka 1.0.1 (https://issues.redhat.com/browse/DBZ-647[DBZ-647]).

Thank you all for your help!

Please refer to the link:/docs/releases/#release-0-7-4[change log] for the complete list of changes in Debezium 0.7.5.

== What's next?

Please see the link:/blog/2018/03/07/debezium-0-7-4-released/[previous release announcement] for the next planned features.
Due to the unplanned 0.7.5 release, though, the schedule of the next one will likely be extended a little bit.

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
