---
tags: [ releases, mysql, postgres, mongodb, oracle, docker ]
---
= Debezium 0.8 Final Is Released
gmorling
:awestruct-tags: [ releases, mysql, postgres, mongodb, oracle, docker ]
:awestruct-layout: blog-post

I'm very happy to announce the release of Debezium *0.8.0.Final*!

The key features of Debezium 0.8 are the first work-in-progress version of our link:/docs/connectors/oracle/[Oracle connector]
(based on the XStream API) and a brand-new parser for MySQL DDL statements.
Besides that, there are plenty of smaller new features (e.g. propagation of default values to corresponding Connect schemas,
optional propagation of source queries in CDC messages and a largely improved SMT for sinking changes from MongoDB into RDBMS)
as well as lots of bug fixes (e.g. around temporal and numeric column types, large transactions with Postgres).

Please see the previous announcements (link:/blog/2018/06/21/debezium-0-8-0-beta1-released/[Beta 1], link:/blog/2018/07/04/debezium-0-8-0-cr1-released/[CR 1])
to learn about all the changes in more depth.
The Final release largely resembles CR1;
apart from further improvements to the Oracle connector (https://issues.redhat.com/browse/DBZ-762[DBZ-792]) there's one nice addition to the MySQL connector contributed by https://github.com/pgoranss[Peter Goransson]:
when doing a snapshot, it will now expose information about the processed rows via JMX (https://issues.redhat.com/browse/DBZ-789[DBZ-789]), which is very handy when snapshotting larger tables.

Please take a look at the link:/docs/releases/#release-0-8-0-final[change log] for the complete list of changes in 0.8.0.Final and general upgrade notes.

== What's next?

We're continuing our work on the Oracle connector.
The work on initial snapshotting is well progressing and it should be part of the next release.
Other improvements will be support for structural changes to captured tables after the initial snapshot has been made,
more extensive source info metadata and more.
Please track https://issues.redhat.com/browse/DBZ-716[DBZ-716] for this work; the improvements are planned to be released incrementally in the upcoming versions of Debezium.

We've also started to explore ingesting changes via LogMiner.
This is more involved in terms of engineering efforts than using XStream, but it comes with the huge advantage of not requiring a separate license
(LogMiner comes with the Oracle database itself).
It's not quite clear yet when we can release something on this front, and we're also actively exploring further alternatives.
But we are quite optimistic and hope to have something some time soon.

The other focus of work is a connector for SQL Server (see https://issues.redhat.com/browse/DBZ-40[DBZ-40]).
Work on this has started as well, and there should be an Alpha1 release of Debezium 0.9 with a first drop of that connector within the next few weeks.

To find out about some more long term ideas, please check out our link:/docs/roadmap/[roadmap] and get in touch with us, if you got any ideas or suggestions for future development.

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
