---
tags: [ releases, mysql, mongodb, postgres, docker ]
---
= Debezium 0.8.2 Released
gmorling
:awestruct-tags: [ releases, mysql, mongodb, postgres, docker ]
:awestruct-layout: blog-post

The Debezium team is back from summer holidays and we're happy to announce the release of Debezium *0.8.2*!

This is a bugfix release to the current stable release line of Debezium, 0.8.x, while the work on Debezium 0.9 is continuing.

_Note:_ By accident the version of the release artifacts is _0.8.2_ instead of _0.8.2.Final_.
This is not in line with our recently established convention of always letting release versions end with qualifiers such as _Alpha1_, _Beta1_, _CR1_ or _Final_.
The next version in the 0.8 line will be _0.8.3.Final_ and we'll improve our release pipeline to make sure that this situation doesn't occur again.

The 0.8.2 release contains link:/docs/releases/#release-0-8-2[10 fixes] overall, most of them dealing with issues related to DDL parsing as done by the Debezium link:/docs/connectors/mysql/[MySQL connector].
For instance, implicit non-nullable primary key columns will be handled correctly now using the new Antlr-based DDL parser (https://issues.redhat.com/browse/DBZ-860[DBZ-860]).
Also the link:/docs/connectors/mongodb/[MongoDB connector] saw a bug fix (https://issues.redhat.com/browse/DBZ-838[DBZ-838]): initial snapshots will be interrupted now if the connector is requested to stop
(e.g. when shutting down Kafka Connect).
More a useful improvement rather than a bug fix is the link:/docs/connectors/postgres/[Postgres connector's] capability to add the table, schema and database names to the `source` block of emitted CDC events (https://issues.redhat.com/browse/DBZ-866[DBZ-866]).

Thanks a lot to community members https://github.com/jchipmunk[Andrey Pustovetov], https://github.com/CliffWheadon[Cliff Wheadon] and https://github.com/oripwk[Ori Popowski] for their contributions to this release!

== What's next?

We're continuing the work on Debezium 0.9, which will mostly be about improvements to the SQL Server and Oracle connectors.
Both will get support for handling structural changes to captured tables while the connectors are running.
Also the exploration of alternatives to using the XStream API for the Oracle connector continues.

Finally, a recurring theme of our work is to further consolidate the code bases of the different connectors,
which will allow us to roll out new and improved features more quickly across all the Debezium connectors.
The recently added Oracle and SQL Server connectors already share a lot of code,
and in the next step we've planned to move the existing Postgres connector to the new basis established for these two connectors.

If you'd like to learn more about some middle and long term ideas, please check out our link:/docs/roadmap/[roadmap].
Also please get in touch with us if you got any ideas or suggestions for future development.

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
