---
tags: [ releases, mysql, postgres, docker ]
---
= Debezium 0.7.3 Is Released
gmorling
:awestruct-tags: [ releases, mysql, postgres, docker ]
:awestruct-layout: blog-post

I'm very happy to announce the release of Debezium *0.7.3*!

This is primarily a bugfix release, but we've also added a handful of smaller new features.
It's a recommended upgrade for all users.
When upgrading from earlier versions,
please check out the link:/docs/releases/[release notes] of all versions between the one your're currently on and 0.7.3 in order to learn about any steps potentially required for upgrading.

Let's take a closer look at some of the new features.

== All Connectors

Using the new connector option `tombstones.on.delete` you can now control whether upon record deletions a tombstone event should be emitted or not
(https://issues.redhat.com/browse/DBZ-582[DBZ-582]).
Doing so is usually the right thing and thus remains the default behaviour.
But disabling tombstones may be desirable in certain situations,
and this gets a bit easier now using that option
(before you'd have to use an SMT - single message transform -, which for instance isn't supported when using Debezium's embedded mode).
This feature was contributed by our community member https://github.com/rliwoch[Raf Liwoch]. Thanks!

We've also spent some time on a few operational aspects:
The `sourceInfo` element of Debezium's change data messages contains a new field representing the version of the connector that created the message
(https://issues.redhat.com/browse/DBZ-593[DBZ-593]).
This lets message consumers take specific action based on the version.
For instance this can be helpful where a new Debezium release fixes a bug, which consumers could work around so far.
Now, after the update to that new Debezium version, that workaround should not be applied anymore.
The version field will allow consumers to decide whether to apply the workaround or not.

The names of all the threads managed by Debezium are now structured in the form of "debezium-<connector>-..."
(https://issues.redhat.com/browse/DBZ-587[DBZ-587]).
This helps with identifying Debezium's threads when analyzing thread dumps for instance.

== Postgres Connector

Here we've focused on improving the support for array types:
besides fixing a bug related to numeric arrays (https://issues.redhat.com/browse/DBZ-577[DBZ-577])
we've also completed the support for the PostGIS types (which was introduced in 0.7.2),
allowing you to capture array columns of types `GEOMETRY` and `GEOGRAPHY`.

Snapshots are now correctly interruptable (https://issues.redhat.com/browse/DBZ-586[DBZ-586])
and the connector will correctly handle the case where after a restart it should continue from a WAL position which isn't available any more:
it'll stop, requiring you to do a new snapshot (https://issues.redhat.com/browse/DBZ-590[DBZ-590]).

== MySQL Connector

The MySQL connector can create the DB history topic automatically, if needed
(https://issues.redhat.com/browse/DBZ-278[DBZ-278]).
This means you don't have to create that topic yourself and you also don't need to rely on Kafka's automatic topic creation any longer
(any change data topics will automatically be created by Kafka Connect).

Also the connector can optionally emit messages to a dedicated heartbeat topic in a configurable interval
(https://issues.redhat.com/browse/DBZ-220[DBZ-220]).
This comes in handy in situations where you only want to capture tables with low traffic,
while other tables in the database are changed more frequently.
In that case, no messages would have been emitted to Kafka Connect for a long time,
and thus no offset would have been committed either.
This could have caused trouble when restarting the connector: it wanted to resume from the last comitted offset,
which may not be available in the binlogs any longer.
But as the captured tables didn't change, it actually wouldn't be necessary to resume from such old binlog position.
This all is avoided by emitting messages to the heartbeat topic regularly, which causes the last offset the connector has seen to be committed.

We'll roll out this change to the other connectors, too, in future releases.

== What's next?

Please see the link:/docs/releases/#release-0-7-3[full change log] for more details and the complete list of issues fixed in Debezium 0.7.3.

The next release is scheduled for March 7th.
We'll still have to decide whether that will be 0.7.4 or 0.8.0, depending on how far we are by then with our work on the Oracle connector
(https://issues.redhat.com/browse/DBZ-137[DBZ-137]).

Please also our link:/docs/roadmap/[roadmap] describing our ideas for future development of Debezium.
This is our current thinking of the things we'd like to tackle in the coming months,
but it's not cast in stone, so please let us know about your feature requests by sending a message to our Google group.
We're looking forward to your feedback!

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
