---
layout: post
title:  Debezium 0.8.0.Beta1 Is Released
date:   2018-06-21 10:19:59 -0600
tags: [ releases, mysql, postgres, mongodb, oracle, docker ]
author: gmorling
---

It's with great excitement that I'm announcing the release of Debezium *0.8.0.Beta1*!

This release brings many exciting new features as well as bug fixes,
e.g. the first drop of our new Oracle connector,
a brand new DDL parser for the MySQL connector,
support for MySQL default values and the update to Apache Kafka 1.1.

Due to the big number of changes (the release contains exactly https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%200.8.0.Beta1[42 issues] overall),
we decided to alter our versioning schema a little bit:
going forward we may do one or more Beta and CR ("candidate release") releases before doing a final one.
This will allow us to get feedback from the community early on,
while still completing and polishing specific features.
Final (stable) releases will be named like 0.8.0.Final etc.

+++<!-- more -->+++

This release would not have been possible without our outstanding community;
a huge "thank you" goes out to the following open source enthusiasts who all contributed to the new version:
https://github.com/echo-xu[Echo Xu],
https://github.com/vuckooo[Ivan Vucina],
https://github.com/glistman[Listman Gamboa],
https://github.com/omarsmak[Omar Al-Safi],
https://github.com/pgoranss[Peter Goransson],
https://github.com/kucharo2[Roman Kuchar] (who did a tremendous job with the new DDL parser implementation!),
https://github.com/sagarrao[Sagar Rao],
https://github.com/sauliusvl[Saulius Valatka],
https://github.com/sairam881990[Sairam Polavarapu],
https://github.com/Crim[Stephen Powis] and
https://github.com/sweat123[WenZe Hu].

Thank you all very much for your help!

Now let's take a closer look at some of the features new in Debezium 0.8.0.Beta1;
as always, you can find the complete list of changes of this release in the link:/docs/releases/#release-0-8-0-beta-1[change log].
Plese take a special look at the breaking changes and the upgrade notes.

== XStream-based Oracle Connector (Tech Preview)

Support for a Debezium Oracle connector has been one of the most asked for features for a long time
(its original issue number is https://issues.redhat.com/browse/DBZ-20[DBZ-20]!).
So we are very happy that we eventually can release a first work-in-progress version of that connector.
At this point this code is still very much evolving, so it should be considered as a first tech preview.
This means it's not feature complete (most notably, there's no support for initial snapshots yet),
the emitted message format may still change etc.
So while we don't recommend using it in production quite yet,
you should definitely give it a try and report back about your experiences.

One challenge for the Oracle connector is how to get the actual change events out of the database.
Unlike with MySQL and Postgres, there's unfortunately no free-to-use and easy-to-work-with API which would allow to do the same for Oracle.
After some exploration we decided to base this first version of the connector on the https://docs.oracle.com/database/121/XSTRM/xstrm_intro.htm#XSTRM72647[Oracle XStream] API.
While this (kinda) checks the box for "easy-to-work-with", it doesn't do so for "free-to-use":
using this API requires you to have a license for Oracle's separate GoldenGate product.
We're fully aware of this being not ideal, but we decided to still go this route as a first step,
allowing us to get some experiences with Oracle and also get a connector into the hands of those with the required license handy.
Going forward, we are going to explore alternative approaches.
We already have some ideas and discussions around this, so please stay tuned (the issue to track is https://issues.redhat.com/browse/DBZ-137[DBZ-137]).

The Oracle connector is going to evolve within the next 0.8.x releases.
To learn more about it, please check its link:/docs/connectors/oracle/[connector documentation page].

== Antlr-based MySQL DDL Parser

In order to build up an internal meta-model of the captured database's structure,
the Debezium MySQL connector needs to parse all issued DDL statements (`CREATE TABLE` etc.).
This used to be done with a hand-written DDL parser which worked reasonably well,
but over time it also revealed some shortcomings; as the DDL language is quite extensive,
we saw repeatedly bug reports caused by some specific DDL constructs not being parseable.

So we decided to go back to the drawing board and came up with a brand new parser design.
Thanks to the great work of Roman Kuchar, we now have a completely new DDL parser
which is based on the proven and very mature http://antlr.org/[Antlr] parser generator
(luckily, the Antlr project provides a complete MySQL grammar).
So we should see much less issue reports related to DDL parsing going forward.

For the time being, the old parser still is in place and remains to be the default parser for Debezium 0.8.x.
You are very encouraged though to test the new implementation by setting the connector option `ddl.parser.mode` to `antlr`
and report back if you run into any issues doing so.
We plan to improve and polish the Antlr parser during the 0.8.x release line
(specifically we're going to measure its performance and optimize as needed)
and switch to it by default as of Debezium 0.9.
Eventually, the old parser will be removed in a future release after that.

== Further MySQL Connector Changes

The MySQL Connector propagates column default values to corresponding Kafka Connect schemas now (https://issues.redhat.com/browse/DBZ-191[DBZ-191]).
That's beneficial when using Avro as serialization format and the schema registry with compatibility checking enabled.

By setting the `include.query` connector option to true, you can add the original query that caused a data change to the corresponding CDC events (https://issues.redhat.com/browse/DBZ-706[DBZ-706]).
While disabled by default, this feature can be a useful tool for analyzing and interpreting data changes captured with Debezium.

Some other changes in the MySQL connector include configurability of the heartbeat topic name (https://issues.redhat.com/browse/DBZ-668[DBZ-668]),
fixes around timezone handling for `TIMESTAMP` (https://issues.redhat.com/browse/DBZ-578[DBZ-578]) and `DATETIME` columns (https://issues.redhat.com/browse/DBZ-741[DBZ-741])
and correct handling of `NUMERIC` column without an explicit scale value (https://issues.redhat.com/browse/DBZ-727[DBZ-727]).

== Postgres Connector

The Debezium Connector for Postgres has seen quite a number of bugfixes, including the following ones:

* wal2json can handle transactions now that are bigger than 1Gb (https://issues.redhat.com/browse/DBZ-638[DBZ-638])
* the transaction ID is consistently handled as long now (https://issues.redhat.com/browse/DBZ-673[DBZ-673])
* multiple fixes related to temporal column types (https://issues.redhat.com/browse/DBZ-681[DBZ-681], https://issues.redhat.com/browse/DBZ-696[DBZ-696])
* OIDs are handled correctly as unsigned int now (https://issues.redhat.com/browse/DBZ-697[DBZ-697], https://issues.redhat.com/browse/DBZ-701[DBZ-701])

== MongoDB Connector

Also for the MongoDB Connector a number of small feature implementations and bugfixes has been done:

* Tested against MongoDB 3.6 (https://issues.redhat.com/browse/DBZ-529[DBZ-529])
* Nested documents can be flattened using a provided SMT now (https://issues.redhat.com/browse/DBZ-561[DBZ-561]), which is useful when sinking changes from MongoDB into a relational database
* The link:/docs/configuration/mongodb-event-flattening/[unwrapping SMT] can be used together with Avro now (https://issues.redhat.com/browse/DBZ-650[DBZ-650])
* The unwrapping SMT can handle arrays with mixed element types (https://issues.redhat.com/browse/DBZ-649[DBZ-649])
* When interrupted during snapshotting before completion, the connector will redo the snapshot after restarting (https://issues.redhat.com/browse/DBZ-712[DBZ-712])

== What's next?

As per the new Beta/CR/Final release scheme, we hope to get some feedback by the community (i.e. you :) on this Beta release.
Depending on the number of issues reported, we'll either release another Beta or go to CR1 with the next version.
The 0.8.0.Final version will be released within a few weeks.
Note that the Oracle connector will remain a "tech preview" component also in the final version.

After that, we've planned to do a few 0.8.x releases with bug fixes mostly,
while work on Debezium 0.9 will commence in parallel.
For that we've planned to work on a connector for SQL Server (see https://issues.redhat.com/browse/DBZ-40[DBZ-40]).
We'd also like to explore means of creating consistent materializations of joins from multiple tables' CDC streams,
based on the ids of originating transactions.
Also there's the idea and a first prototype of exposing Debezium change events as a reactive event stream (https://issues.redhat.com/browse/DBZ-566[DBZ-566]),
which might be shipped eventually.

Please take a look at the link:/docs/roadmap/[roadmap] for some more long term ideas and get in touch with us,
if you got thoughts around that.
