---
layout: post
title:  A Note On Database History Topic Configuration
date:   2018-03-16 10:19:59 -0600
tags: [ mysql ]
author: gmorling
---

A user of the Debezium connector for MySQL informed us about a potential issue with the configuration of the connector's internal database history topic,
which may cause the deletion of parts of that topic (https://issues.redhat.com/browse/DBZ-663[DBZ-663]).
Please continue reading if you're using the Debezium MySQL connector in versions 0.7.3 or 0.7.4.

+++<!-- more -->+++

== What is the issue about?

In Debezium 0.7.3 we rolled out a feature for creating the database history automatically if it doesn't exist yet (https://issues.redhat.com/browse/DBZ-278[DBZ-278]).
While this feature sets the retention time for the topic to an "infinite" period, it doesn't specify the "retention.bytes" option for the history topic.
This may cause parts of the history topic to be deleted in case all of the following conditions are met:

* You are using versions 0.7.3 or 0.7.4 of the Debezium connector for MySQL
* The database history topic has been created by the connector (i.e. you haven't created it yourself)
* The broker level option "log.retention.bytes" is set to another value than -1
(note that the default *is* -1, in which case things work as intended)
* The database history topic grows beyond the threshold configured via "log.retention.bytes"

If the history topic is incomplete, the connector will fail to recover the database history after a restart of the connector and will not continue with reading the MySQL binlog.

== How to prevent the issue?

You should either create the database history topic yourself with an infinite retention
or alternatively override the "retention.bytes" configuration for the history topic created by the connector:

[source,shell]
----
<KAFKA_DIR>/bin/kafka-configs.sh \
  --zookeeper zookeeper:2181 \
  --entity-type topics \
  --entity-name <DB_HISTORY_TOPIC> \
  --alter \
  --add-config retention.bytes=-1
----

In case parts of the history topic were removed already,
you can use the snapshot mode `schema_only_recovery` for re-creating the history topic in case no schema changes have happened since the last committed offset of the connector.
Alternatively, a complete new snapshot should be taken, e.g. by setting up a new connector instance.

== Next steps

We'll release Debezium 0.7.5 with a fix for this issue early next week.
Note that previously created database history topics should be re-configured as described above.
Please don't hesitate to get in touch in the comments below, the chat room or the mailing list in case you have any further questions on this issue.
