---
layout: post
title:  Debezium 0.9.2.Final Released
date:   2019-02-25 10:19:59 -0600
tags: [ releases, mysql, mongodb, postgres, sqlserver, docker ]
author: gmorling
---

The Debezium team is happy to announce the release of Debezium *0.9.2.Final*!

This is mostly a bug-fix release and a drop-in replacement for earlier Debezium 0.9.x versions.
Overall, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%200.9.2.Final[18 issues] were resolved.

A couple of fixes relate to the link:/docs/connectors/postgresql/[Debezium Postgres connector]:

+++<!-- more -->+++

* When not using `REPLICA IDENTITY FULL`, certain data types could trigger exceptions for update or delete events; those are fixed now
(https://issues.redhat.com/browse/DBZ-1141[DBZ-1141], https://issues.redhat.com/browse/DBZ-1149[DBZ-1149])
* The connector won't fail any longer when encountering a change to a row with an unaltered TOAST column value
(https://issues.redhat.com/browse/DBZ-1146[DBZ-1146])

Also the link:/docs/connectors/mysql/[Debezium MySQL connector] saw a number of fixes:

* The connector works correctly now when using GTIDs and `ANSI_QUOTES` SQL mode (https://issues.redhat.com/browse/DBZ-1147[DBZ-1147])
* The new Antlr-based DDL parsers can handle column names that are key words such as `MEDIUM` (https://issues.redhat.com/browse/DBZ-1150[DBZ-1150])
* `TIME` columns with a default value larger than 23:59:59 can be exported now (https://issues.redhat.com/browse/DBZ-1137[DBZ-1137])


Another important fix was done in the link:/docs/connectors/sqlserver/[Debezium connector for SQL Server],
where the connector archive deployed to Maven Central accidentally contained all test-scoped and provided-scoped dependencies.
This has been resolved now, so the connector archive only contains the actually needed JARs and thus is much smaller (https://issues.redhat.com/browse/DBZ-1138[DBZ-1138]).

== New Features

The 0.9.2 release also comes with two small new features:

* You can pass arbitrary parameters to the logical decoding plug-in used by the Postgres connector;
this can for instance be used with wal2json to limit the number of tables to capture on the server side
(https://issues.redhat.com/browse/DBZ-1130[DBZ-1130])
* The MongoDB connector now has the long-awaited snapshotting mode `NEVER` (https://issues.redhat.com/browse/DBZ-867[DBZ-867]),
i.e. you can set up a new connector without taking an initial snapshot and instantly beginning streaming changes from the oplog

== Version Updates

As of this release, Debezium has been upgraded to Apache Kafka 2.1.1.
Amongst others, this release fixes an issue where the Kafka Connect REST API would expose connector credentials also when those were configured via secrets (https://issues.apache.org/jira/browse/KAFKA-5117[KAFKA-5117]).
We've also upgraded the binlog client used by the MySQL connector to version 0.19.0 (https://issues.redhat.com/browse/DBZ-1140[DBZ-1140]),
which fixes a bug that had caused exceptions during rebalancing the connector before (https://issues.redhat.com/browse/DBZ-1132[DBZ-1132]).

Check out the link:/docs/releases/#release-0-9-2-final[release notes] for the complete list of issues fixed in Debezium 0.9.2.

Many thanks to Debezium community members https://github.com/jchipmunk[Andrey Pustovetov], https://github.com/kbarber2[Keith Barber], https://github.com/krizhan[Krizhan Mariampillai] and https://github.com/taylor-rolison[Taylor Rolison] for their contributions to this release!
