---
tags: [ releases, mysql, postgres, mongodb, sqlserver, oracle, docker ]
---
= Debezium 0.10.0.Beta1 Released
gmorling
:awestruct-tags: [ releases, mysql, postgres, mongodb, sqlserver, oracle, docker ]
:awestruct-layout: blog-post

Another week, another Debezium release -- I'm happy to announce the release of Debezium *0.10.0.Beta1*!

Besides the upgrade to Apache Kafka 2.2.1 (https://issues.redhat.com/browse/DBZ-1316[DBZ-1316]),
this mostly fixes some bugs, including a regression to the MongoDB connector introduced in the Alpha2 release
(https://issues.redhat.com/browse/DBZ-1317[DBZ-1317]).

A very welcomed usability improvement is that the connectors will log a warning now
if not at least one table is actually captured as per the whitelist/blacklist configuration
(https://issues.redhat.com/browse/DBZ-1242[DBZ-1242]).
This helps to prevent the accidental exclusion all tables by means of an incorrect filter expression,
in which case the connectors "work as intended", but no events are propagated to the message broker.

Please see the link:/docs/releases/#release-0-10-0-beta1[release notes] for the complete list of issues fixed in this release.
Also make sure to examine the upgrade guidelines for 0.10.0.Alpha1 and Alpha2 when upgrading from earlier versions.

Many thanks to community members https://github.com/pan3793[Cheng Pan] and https://github.com/ChingTsai[Ching Tsai] for their contributions to this release!

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
