---
layout: post
title:  Debezium 0.10.0.Alpha2 Released
date:   2019-06-03 10:19:59 -0600
tags: [ releases, mysql, postgres, mongodb, sqlserver, oracle, docker ]
author: jpechane
---

Release early, release often -- Less than a week since the Alpha1 we are announcing the release of Debezium *0.10.0.Alpha2*!

This is an incremental release that completes some of the tasks started in the Alpha1 release and provides a few bugfixes and also quality improvements in our Docker images.

The change in the logic of the `snapshot` field has been delivered (https://issues.redhat.com/browse/DBZ-1295[DBZ-1295]) as outlined in link:2019/05/29/debezium-0-10-0-alpha1-released/#outlook[the last announcement].
All connectors now provide information which of the records is the last one in the snapshot phase so that downstream consumers can react to this.

+++<!-- more -->+++

Apache ZooKeeper was upgraded to version 3.4.14 to fix a security vulnerability (https://nvd.nist.gov/vuln/detail/CVE-2019-0201[CVE-2019-0201]).

Our regular contributor https://github.com/renatomefi[Renato] dived deeply into our image build scripts and enriched (https://issues.redhat.com/browse/DBZ-1279[DBZ-1279]) them with a Dockerfile linter.

Schema change events include the table name(s) in the metadata describing which tables are affected by the change (https://issues.redhat.com/browse/DBZ-871[DBZ-871]).

https://github.com/barrti[Bartosz Miedlar] has fixed a bug in MySQL ANTLR grammar causing issues with identifiers in backquotes (https://issues.redhat.com/browse/DBZ-1300[DBZ-1300]).

== What's next?

We hope we will be able to keep the recent release cadence and get lout the first beta version of 0.10 in two weeks.

Stay tuned for more!
