---
layout: post
title:  Debezium's Newsletter 01/2019
date:   2019-06-05 10:19:59 -0600
tags: [ community, news, newsletter ]
author: ccranfor
---

Welcome to the first edition of the Debezium community newsletter in which we share blog posts, group discussions, as well as StackOverflow
questions that are relevant to our user community.

+++<!-- more -->+++

== Upcoming Events

* https://www.meetup.com/fr-FR/Paris-Data-Engineers/events/260694777/[Paris Data Engineers Meet-up]
* https://2019.javazone.no[Oslo JavaZone 2019 - Change Data Streaming For Microservices With Apache Kafka and Debezium]

== Articles

Gunnar Morling recently attended Kafka Summit in London where he gave a talk on Change Data Streaming Patterns
for Microservices With Debezium.  You can watch the full presentation https://www.confluent.io/kafka-summit-lon19/change-data-streaming-patterns-microservices-debezium[here].

Strimzi provides an easy way to run Apache Kafka on Kubernetes or Openshift.  https://medium.com/@sincysebastian/setup-kafka-with-debezium-using-strimzi-in-kubernetes-efd494642585[This article]
by Sincy Sebastian shows just how simple it is to replicate change events from MySQL to Elastic Search using Debezium.

Debezium allows replicating data between heterogeneous data stores with ease.  https://blog.couchbase.com/kafka-connect-mysql-couchbase-debezium/[This article] by Matthew Groves
explains how you can replicate data from MySQL to CouchBase.

As the size of data that systems maintain continues to grow, this begins to impact how we capture, compute, and report
real-time analytics. https://medium.com/high-alpha/data-stream-processing-for-newbies-with-kafka-ksql-and-postgres-c30309cfaaf8[This article] by Maria Patterson
explains how you can use Debezium to stream data from Postgres, perform analytical calculations using KSQL, and then
stream those results back to Postgres for consumption.

In a https://medium.com/@singaretti/streaming-de-dados-do-postgresql-utilizando-kafka-debezium-v2-d49f46d70b37[recent article] published in Portuguese,
Paulo Singaretti illustrates how they use Debezium and Kafka to stream changes from their relational database and then store
the change stream results in Google Cloud Services.

This https://debezium.io/blog/2019/05/23/tutorial-using-debezium-connectors-with-apache-pulsar/[recent blog] by Jia Zhai provides
a complete tutorial showing how to use Debezium connectors with Apache Pulsar.

== Time to upgrade

Debezium version https://debezium.io/blog/2019/05/06/debezium-0-9-5-final-released/[0.9.5] was just released.
If you are using the 0.9 branch you should definitely check out 0.9.5.  For details on the bug fixes as well as
the enhancements this version includes, check out the
https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12341657[release notes].

The Debezium team has also begun active development on the next major version, 0.10.  We recently published
a https://debezium.io/blog/2019/05/29/debezium-0-10-0-alpha1-released/[blog] that provides an overview
behind what 0.10 is meant to deliver.  If you want details on the bug fixes and enhancements we've packed
into this release, you can view the https://issues.redhat.com/issues/?jql=fixVersion%20IN%20(0.10.0.Alpha1%2C%200.10.0.Alpha2)%20ORDER%20BY%20KEY[issue list].

== Questions and answers

* https://stackoverflow.com/questions/55569090/how-to-let-debezium-start-reading-binlog-from-the-last-row[How to have Debezium start reading binlog from last row]
* https://stackoverflow.com/questions/55633590/is-it-possible-to-apply-smt-single-message-transforms-to-messages-from-specifi[Is it possible to apply Single Message Transforms to messages from specified topics]
* https://stackoverflow.com/questions/55648457/kafkaconnect-produces-cdc-event-with-null-value-when-reading-from-mongodb-with-d[Kafka Connect produces CDC events with null values when reading from MongoDB with Debezium]
* https://groups.google.com/d/msgid/debezium/1bae4e45-c6c4-4190-9955-44f901b8ca04%40googlegroups.com?utm_medium=email&utm_source=footer[Renaming Topics]
* https://groups.google.com/d/msgid/debezium/cfc333f1-b5f6-462b-a1c8-0f65bc91b725%40googlegroups.com?utm_medium=email&utm_source=footer[Stream changes with differing column names between source and destination]
* https://groups.google.com/d/msgid/debezium/18c1239f-af69-4161-8adc-329a91aa4c7e%40googlegroups.com?utm_medium=email&utm_source=footer[Can't connect to debezium kafka from Docker host]

== Feedback

We intend to publish new additions of this newsletter periodically.  Should anyone have any suggestions on changes or what could be highlighted here, we welcome that feedback.  You can reach out to us via any of our community channels found link:/community[here].
