---
layout: post
title:  Debezium 0.9.0.CR1 Released
date:   2019-01-28 10:19:59 -0600
tags: [ releases, mysql, mongodb, postgres, sqlserver, oracle, docker ]
author: gmorling
---

Reaching the home stretch towards Debezium 0.9, it's with great pleasure that I'm announcing the first release of Debezium in 2019, *0.9.0.CR1*!

For this release we've mainly focused on sorting out remaining issues in the Debezium link:/docs/connectors/sqlserver/[connector for SQL Server];
the connector comes with greatly improved performance and has received a fair number of bug fixes.

Other changes include a new interface for event handlers of Debezium's link:/docs/embedded/[embedded engine],
which allows for bulk handling of change events, an option to export the scale of numeric columns as schema parameter,
as well as a wide range of bug fixes for the Debezium connectors for MySQL, Postgres and Oracle.

+++<!-- more -->+++

== SQL Server Connector Improvements

The SQL Server connector supports blacklisting of specific columns now (https://issues.redhat.com/browse/DBZ-1067[DBZ-1067]).
That's useful in cases where you'd like to exclude specific columns from emitted change data messages, e.g. to data protection considerations.

The "snapshot locking mode" option has been reworked (https://issues.redhat.com/browse/DBZ-947[DBZ-947]) and is named "snapshot isolation mode" now,
better reflecting its semantics.
A new mode "repeatable_read" has been added, and "none" has been renamed to "read_uncommitted".
Please see the connector documentation and the link:/docs/releases/#breaking_changes[migration notes] for more details.

The connector allows for a much higher through-put now, thanks to caching of timestamps for the same LSN (https://issues.redhat.com/browse/DBZ-1078[DBZ-1078]).
Please refer to the link:/docs/releases/#release-0-9-0-cr1[change log] for details on bugs fixed in this connector.
A massive "Thank You" is in order to Grzegorz Kołakowski, for his tireless work on and testing of this connector!

== New Embedded Engine Handler Interface

Debezium's embedded engine now comes with a new interface `ChangeConsumer`,
which event handlers can implement if they'd like to process change events in bulks (https://issues.redhat.com/browse/DBZ-1080[DBZ-1080]).
That can result in substantial performance improvements when pushing change events to APIs that apply batch semantics themselves,
such as the Kinesis Producer Library.
You can learn more in the link:/docs/embedded/[embedded engine] docs.

== Misc. Changes and Bug Fixes

All the relational connectors allow now to propagate the scale of numeric columns as a schema parameter
(https://issues.redhat.com/browse/DBZ-1073[DBZ-1073]).
This is controlled via the `column.propagate.source.type` option and builds on the exposure of type name and width added in Debezium 0.8.
All these schema parameters can be used when creating the schema of corresponding tables in sink databases.

Debezium's container image for Apache Kafka allows to create and watch topics now
(https://issues.redhat.com/browse/DBZ-1057[DBZ-1057]).
You also can specify a clean-up policy when creating a topic
(https://issues.redhat.com/browse/DBZ-1038[DBZ-1038]).

The Debezium MySQL connector handles unsigned `SMALLINT` columns as expected now.
(https://issues.redhat.com/browse/DBZ-1063[DBZ-1063]).
For nullable columns with a default value, `NULL` values are correctly exported
(https://issues.redhat.com/browse/DBZ-1064[DBZ-1064]; previously, the default value would have been exported in that case).

The Postgres connector handles tables without a primary key correctly now
(https://issues.redhat.com/browse/DBZ-1029[DBZ-1029]).
We've also applied a fix to make sure that the connector works with Postgres on Amazon RDS,
which recently was broken due to an update of wal2json in RDS
(https://issues.redhat.com/browse/DBZ-1083[DBZ-1083]).
Going forward, we're planning to set-up CI jobs to test against Postgres on RDS in all the versions supported by the Debezium connector.
This will help us to spot similar issues early on and react quickly.

Please see the link:/docs/releases/#release-0-9-0-cr1[change log] for the complete list of all addressed issues.

This release wouldn't have been possible without all the contributions by the following members of the Debezium community:
https://github.com/addisonj[Addison Higham],
https://github.com/amitsela[Amit Sela],
https://github.com/gaganpaytm[Gagan Agrawal],
https://github.com/grzegorz8[Grzegorz Kołakowski],
https://github.com/Ipshin[Ilia Bogdanov],
https://github.com/ivankovbas[Ivan Kovbas],
https://github.com/mtagle[Moira Tagle],
https://github.com/renatomefi[Renato Mefi] and
https://github.com/trizko[Tony Rizko].

Thanks a lot!

== Next Steps

The CR1 release took us a bit longer than anticipated.
The release of Debezium 0.9.0.Final will therefore be moved to early February.
Rather quickly thereafter we're planning to release Debezium 0.9.1,
which will provide improvements and potential bugfixes to the features added in 0.9.

For further plans beyond that, check out our link:/docs/roadmap/[road map].
If you got any feedback or suggestions for future additions, please get in touch via the https://groups.google.com/forum/#!forum/debezium[mailing list] or in the comments below.
