---
layout: post
title:  Debezium 0.10 Final Released
date:   2019-10-02 10:19:59 -0600
tags: [ releases, mysql, postgres, sqlserver, cassandra ]
author: gmorling
---

On behalf of the Debezium community it's my great pleasure to announce the release of Debezium *0.10.0.Final*!

As you'd expect it, there were not many changes since last week's CR2,
one exception being a performance fix for the `pgoutput` plug-in of the Postgres connector,
which may have suffered from slow processing when dealing with many small transactions in a short period of time
(https://issues.redhat.com/browse/DBZ-1515[DBZ-1515]).

This release finalizes the work of overall link:/releases/0.10/[eight preview releases].
We have discussed the new features and changes in depth in earlier announcements,
but here are some highlights of Debezium 0.10:

+++<!-- more -->+++

* Incubating link:/documentation/reference/0.10/connectors/cassandra.html[CDC support for Apache Cassandra] via our first community-led connector
* Support for the `pgoutput` logical decoding plug-in of Postgres 10 and later; support for "exported" snapshots with link:/documentation/reference/0.10/connectors/postgresql.html[Postgres]
* Extended and more unified metrics across the different connectors
* More consistent and improved `source` structure in change events
* Significantly less memory usage in the link:/documentation/reference/0.10/connectors/sqlserver.html[SQL Server connector]
* Many improvements and bugfixes to the DDL parser of the link:/documentation/reference/0.10/connectors/mysql.html[MySQL connector]
* Lots of improvements to the SMTs for link:/documentation/reference/0.10/configuration/outbox-event-router.html[routing outbox events] and link:/documentation/reference/0.10/configuration/event-flattening.html[extracting the "after" state] from change events
* Customizable message keys
* Reworked link:/blog/2019/09/05/website-documentation-overhaul/[website and restructured documentation], organized by releases

In addition, we also removed some previously deprecated options and did some clean-up of the message structures produced by the Debezium connectors, e.g. in regards to certain type mappings.
When upgrading from earlier releases,
please make sure to carefully study the link:/releases/0.10/release-notes/[release notes], which discuss in detail any changed or removed functionality, as well as options which for instance allow to keep the original `source` structure for some time.

Pleas refer to the orignal announcements for more details (https://debezium.io/blog/2019/05/29/debezium-0-10-0-alpha1-released/[Alpha1], https://debezium.io/blog/2019/06/03/debezium-0-10-0-alpha2-released/[Alpha2], https://debezium.io/blog/2019/06/12/debezium-0-10-0-beta1-released/[Beta1], https://debezium.io/blog/2019/06/28/debezium-0-10-0-beta2-released/[Beta2], https://debezium.io/blog/2019/07/25/debezium-0-10-0-beta3-released/[Beta3], https://debezium.io/blog/2019/08/20/debezium-0-10-0-beta4-released/[Beta4], https://debezium.io/blog/2019/09/10/debezium-0-10-0-cr1-released/[CR1], https://debezium.io/blog/2019/09/26/debezium-0-10-0-cr2-released/[CR2]).
Altogether, a whopping https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20in%20(0.10.0.Alpha1%2C%200.10.0.Alpha2%2C%200.10.0.Beta1%2C%200.10.0.Beta2%2C%200.10.0.Beta3%2C%200.10.0.Beta4%2C%200.10.0.CR1%2C%200.10.0.CR2%2C%200.10.0.Final)[171 issues] were resolved in Debezium 0.10.

Such effort would not nearly be possible without all the fantastic people in the Debezium community.
Until today, almost https://github.com/debezium/debezium/blob/master/COPYRIGHT.txt[130 people] have contributed to the main Debezium code repository,
plus some more to the incubator and container image repositories.
But submitting pull requests with code changes is not the only way to help,
we're equally thankful for each bug report, feature request, suggestions in the chat rooms etc.

Another great thing to observe is the growing number of blog posts, conference presentations and other material covering Debezium in one way or another.
We maintain a list of link:/documentation/online-resources/[Debezium-related resources] on the website;
if you know of other contents which should be linked there, please file a PR for adding it.

I can't begin to express how lucky we feel about all these amazing contributions,
no matter whether small or large!

== Coming Next: Debezium 1.0!

With Debezium 0.10.0.Final being done, the question is: what's next?
If you thought 0.11, then we got to disappoint you -- we're finally setting course towards Debezium 1.0!

With all the community feedback we got (in parts from huge deployments with hundreds of Debezium connectors), and with the clean-up changes done for 0.10, we feel that it's finally about time for the 1.0 release and the even increased expectations towards it in regards to compatibility and stability.

We don't expect many new functionality for 1.0 in comparison over 0.10
(with exception of the incubating connectors),
the focus will primarily be on further bug fixing, stability and usability improvements.
In the good old tradition of open source, we don't specify any timeline other than "it's done, when it's done".
But it should be safe to say that it will be done quicker than 0.10:
going forward, we'd like to increase the release cadence and publish new minor releases more often, for sure doing less than eight preview releases as in 0.10.
Any contributions, input on the roadmap and other feedback will be very welcomed of course.

Upwards and onwards!
