---
layout: post
title:  Debezium 0.9.3.Final Released
date:   2019-03-26 10:19:59 -0600
tags: [ releases, mysql, mongodb, postgres, sqlserver, docker ]
author: jpechane
---

The Debezium team is happy to announce the release of Debezium *0.9.3.Final*!

This is mostly a bug-fix release and a drop-in replacement for earlier Debezium 0.9.x versions, but there are few significant new features too.
Overall, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%200.9.3.Final[17 issues] were resolved.

[NOTE]
Container images will be released with a small delay due to some Docker Hub configuration issues.

+++<!-- more -->+++

== New Features

The 0.9.3 release comes with two larger new features:

* A feature request was made to execute a partial recovery of the replication process after losing the replication slot with the PostgreSQL database, e.g. after failing over to a secondary database host (https://issues.redhat.com/browse/DBZ-1082[DBZ-1082]).
Instead of adding yet another snapshotting mode, we took a step back and decided to make the Postgres snapshotting process more customizable by introducing a service provider interface (SPI). This lets you implement and register your own Java class for controlling the snaphotting process.
See the issue description of DBZ-1082 for one possible custom implementation of this SPI, which is based on Postgres' `catalog_xmin` property and selects all records altered after the last known xmin position.
To learn more about the SPI, see the the https://github.com/debezium/debezium/blob/master/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/spi/Snapshotter.java[Snapshotter] contract.
Note that the feature is still in incubating phase and the SPI should be considered unstable for the time being.
* Not long ago we published blogpost about implementing the link:/blog/2019/02/19/reliable-microservices-data-exchange-with-the-outbox-pattern/[outbox] pattern with Debezium for propagating data changes between microservices.
Community member https://github.com/renatomefi[Renato Mefi] expanded the idea and created a ready-made implementation of the single message transform (SMT) described in the post for routing events from the outbox table to specific topics.
This SMT is part of the Debezium core library now (https://issues.redhat.com/browse/DBZ-1169[DBZ-1169]).
Its usage will be described in the documentation soon; for the time being please refer to the https://github.com/debezium/debezium/tree/master/debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouter.java[EventRouter] type and the accompanying configuration class.

== Bug fixes

We did a couple of fixes related to the link:/docs/connectors/postgresql/[Debezium Postgres connector]:

* A regression that introduced a deadlock in snapshotting process has been fixed (https://issues.redhat.com/browse/DBZ-1161[DBZ-1161])
* The `hstore` datatype works correctly in snapshot phase (https://issues.redhat.com/browse/DBZ-1162[DBZ-1162])
* The `wal2json` plug-in processes also empty events (https://issues.redhat.com/browse/DBZ-1181[DBZ-1181]) as e.g. originating from materialize view updates; this should help to resolve some of the issues where log files in Postgres couldn't be discarded due to Debezium's replication slot not advancing.
* The commit time is propely converted to microseconds (https://issues.redhat.com/browse/DBZ-1174[DBZ-1174])

Also the link:/docs/connectors/mysql/[Debezium MySQL connector] saw a number of fixes especially in SQL parser:

* The `SERIAL` datatype and default value is now supported (https://issues.redhat.com/browse/DBZ-1185[DBZ-1185])
* A specific detail in the MySQL grammar that allows to enumerate table options in `ALTER TABLE` without comma works (https://issues.redhat.com/browse/DBZ-1186[DBZ-1186])
* A false alarm for empty MySQL password is no longer reported (https://issues.redhat.com/browse/DBZ-1188[DBZ-1188])
* It is no longer necessary to create history topic manually for broker without default topic replication value (https://issues.redhat.com/browse/DBZ-1179[DBZ-1179])

It is now possible to process multiple schemas with a single Oracle connector (https://issues.redhat.com/browse/DBZ-1166[DBZ-1166]).

Check out the link:/docs/releases/#release-0-9-3-final[release notes] for the complete list of issues fixed in Debezium 0.9.3.

Many thanks to Debezium community members https://github.com/renatomefi[Renato Mefi], https://github.com/ShubhamRwt[Shubham Rawat], https://github.com/addisonj[Addison Higham], https://github.com/jcasstevens[Jon Casstevens], https://github.com/hashhar[Ashar Hassan] and https://github.com/p5k6[Josh Stanfield] for their contributions to this release!
