---
layout: post
title:  Debezium 0.10.0.Alpha1 "Spring Clean-Up" Edition Released
date:   2019-05-29 10:19:59 -0600
tags: [ releases, mysql, postgres, mongodb, sqlserver, oracle, docker ]
author: gmorling
---

I'm very happy to announce the release of Debezium *0.10.0.Alpha1*!

The major theme for Debezium 0.10 will be to do some clean-up
(that's what you do at this time of the year, right?);
we've planned to remove a few deprecated features and to streamline some details in the structure the CDC events produced by the different Debezium connectors.

This means that upgrading to Debezium 0.10 from earlier versions might take a bit more planning and consideration compared to earlier upgrades,
depending on your usage of features and options already marked as deprecated in 0.9 and before.
But no worries, we're describing all changes in great detail in this blog post and the https://debezium.io/docs/releases/#release-0-10-0-alpha1[release notes].

+++<!-- more -->+++

== Why?

First of all, let's discuss a bit why we're doing these changes.

Over the last three years, Debezium has grown from supporting just a single database into an entire family of link:/docs/connectors/[CDC connectors] for a range of different relational databases and MongoDB,
as well as accompanying components such as message transformations for link:/docs/configuration/topic-routing/[topic routing] or link:/docs/configuration/outbox-event-router/[implementing the outbox pattern].

As in any mature project, over time we figured that a few things should be done differently in the code base than we had thought at first.
For instance we moved from a hand-written parser for processing MySQL DDL statements to a much more robust implementation based on Antlr.
Also we realized the way certain temporal column types were exported was at risk of value overflow in certain conditions,
so we added a new mode not prone to these issues.
As a last example, we made options like the batch size used during snapshotting consistent across the different connectors.

Luckily, Debezium quickly gained traction and despite the 0.x version number, it is used heavily in production at a large number of organizations, and users rely on its stability.
So whenever we did such changes, we aimed at making the upgrade experience as smooth as possible;
usually that means that the previous behavior is still available but is marked as deprecated in the documentation,
while a new improved option, implementation etc. is added and made the default behavior.

At the same time we realized that there are a couple of differences between the connectors which shouldn't really be there.
Specifically, the `source` block of change events has some differences which make a uniform handling by consumers more complex than it should be;
for instance the timestamp field is named "ts_sec" in MySQL events but "ts_usec" for Postgres.

With all this in mind, we decided that it is about time to clean up these issues.
This done for a couple of purposes:

* Keeping the code base maintainable and open for future development by removing legacy code such as deprecated options and their handling as well as the legacy MySQL DDL parser
* Making CDC events from different connectors easier to consume by unifying the `source` block created by the different connectors as far as possible
* Preparing the project to go to version 1.0 with an even stronger promise of retaining backwards compatibility than already practiced today

=== What?

Now as we have discussed why we feel it's time for some "clean-up", let's take a closer look at the most relevant changes.
Please also refer to the https://debezium.io/docs/releases/#breaking_changes["breaking changes"] section of the migration notes for more details.

* The legacy DDL parser for MySQL has been removed (https://issues.redhat.com/browse/DBZ-736[DBZ-736]);
if you are not using the Antlr-based one yet (it was introduced in 0.8 and became the default in 0.9),
it's highly recommended that you test it with your databases.
Should you run into any parsing errors, please report them so we can fix them for the 0.10 Final release.
* The SMTs for retrieving the new record/document state from change events have been renamed from
`io.debezium.transforms.UnwrapFromEnvelope` and `io.debezium.connector.mongodb.transforms.UnwrapFromMongoDbEnvelope`
into `ExtractNewRecordState` and `ExtractNewDocumentState`, respectively
(https://issues.redhat.com/browse/DBZ-677[DBZ-677]).
The old names can still be used as of 0.10, but doing so will raise a warning.
They are planned for removal in Debezium 0.11.
* Several connector options that were deprecated in earlier Debezium versions have been removed
(https://issues.redhat.com/browse/DBZ-1234[DBZ-1234]):
the `drop.deletes` option of new record/document state extraction SMTs (superseded by `delete.handling.mode` option),
the `rows.fetch.size` option (superseded by `snapshot.fetch.size`),
the `adaptive` value of `time.precision.mode` option for MySQL (prone to value loss, use `adaptive_microseconds` instead) and
the `snapshot.minimal.locks` for the MySQL connector (superseded by `snapshot.locking.mode`)
* Several option names of the (incubating) SMT for the outbox pattern
have been renamed for the sake of consistency (https://issues.redhat.com/browse/DBZ-1289[DBZ-1289])
* Several fields within the `source` block of CDC events have been renamed for the sake of consistency
(https://issues.redhat.com/browse/DBZ-596[DBZ-596]);
as this is technically a backwards-incompatible change when using Avro and the schema registry,
we've added a connector option `source.struct.version` which, when set to the value `v1`, will have connectors produce the previous `source` structure.
`v2` is the default and any consumers should be adjusted to work with the new `source` structure as soon as possible.

=== New Features and Bugfixes

Besides these changes, the 0.10.0.Alpha1 release also contains some feature additions and bug fixes:

* The SQL Server connector supports custom SELECT statements for snapshotting (https://issues.redhat.com/browse/DBZ-1224[DBZ-1224])
* database, schema and table/collection names have been added consistently to the `source` block for CDC events from all connectors
(https://issues.redhat.com/browse/DBZ-875[DBZ-875])
* Client authentication works for the MySQL connector(https://issues.redhat.com/browse/DBZ-1228[DBZ-1228])
* The embedded engine doesn't duplicate events after restarts any longer (https://issues.redhat.com/browse/DBZ-1276[DBZ-1276])
* A parser bug related to `CREATE INDEX` statements was fixed (https://issues.redhat.com/browse/DBZ-1264[DBZ-1264])

Overall, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%200.10.0.Alpha1[30 issues] were addressed in this release.
Many thanks to https://github.com/Arkoprabho[Arkoprabho Chakraborti], https://github.com/rsatishm[Ram Satish] and https://github.com/Wang-Yu-Chao[Yuchao Wang] for their contributions to this release!

Speaking of contributors, we did some housekeeping to https://github.com/debezium/debezium/blob/master/COPYRIGHT.txt[the list] of everyone ever contributing to Debezium, too.
Not less than exactly *111 individuals have contributed* code up to this point,
which is just phenomenal! Thank you so much everyone, you folks rock!

=== Outlook

Going forward, there are some more details we'd like to unify across the different connectors before going to Debezium 0.10 Final.
For instance the `source` attribute `snapshot` will be changed so it can take one of three states: `true`, `false` or `last`
(indicating that this event is the last one created during initial snapshotting).

We'll also continue our efforts to to migrate the existing Postgres connector to the framework classes established for the SQL Server and Oracle connectors.
Another thing we're actively exploring is how the Postgres could take advantage of the "logical replication" feature added in Postgres 10.
This may provide us with a way to ingest change events without requiring a custom server-side logical decoding plug-in,
which proves challenging in cloud environments where there's typically just a limited set of logical decoding options available.
