---
tags: [ releases, mysql, postgres, sqlserver, cassandra ]
---
= Debezium 1.0.0.Beta1 Released
ccranfor
:awestruct-tags: [ releases, mysql, postgres, sqlserver, cassandra ]
:awestruct-layout: blog-post

History is in the making as Debezium begins to sprint to its 1.0 milestone.
It's my pleasure to announce the release of Debezium *1.0.0.Beta1*!

This new Debezium release includes several notable new features, enhancements, and fixes:

* ExtractNewDocumentState and EventRouter SMTs propagate heartbeat &amp; schema change messages (https://issues.redhat.com/browse/DBZ-1513[DBZ-1513])
* Provides alternative mapping for `INTERVAL` columns via `interval.handling.mode` (https://issues.redhat.com/browse/DBZ-1498[DBZ-1498])
* Ensure message keys have the right column order (https://issues.redhat.com/browse/DBZ-1507[DBZ-1507])
* Warn of table locking problems in connector logs (https://issues.redhat.com/browse/DBZ-1280[DBZ-1280])

Additionally, several PostgreSQL issues were fixed to improve snapshotting large databases environments (https://issues.redhat.com/browse/DBZ-685[DBZ-685]) and specific circumstances where write ahead logs (WAL) would continue to consume diskspace (https://issues.redhat.com/browse/DBZ-892[DBZ-892]).

In total, this release contains link:/releases/1.0/release-notes/#release-1.0.0-beta1[18 fixes].


Thanks to all the community members who helped make this happen:
https://github.com/pushpavanthar[Purushotham Pushpavanthar],
https://github.com/jfinsel[Jeremy Finzel],
https://github.com/grantcooksey[Grant Cooksey]

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
