---
layout: post
title:  Debezium 0.10.0.Beta4 Released
date:   2019-08-20 10:19:59 -0600
tags: [ releases, mysql, postgres, mongodb, sqlserver, oracle, docker ]
author: gmorling
---

The temperatures are slowly cooling off after the biggest summer heat,
an the Debezium community is happy to announce the release of Debezium *0.10.0.Beta4*.
In this release we're happy to share some news we don't get to share too often:
with http://cassandra.apache.org/[Apache Cassandra],
another database gets added to the list of databases supported by Debezium!

In addition, we finished our efforts for rebasing the existing Postgres connector to Debezium framework structure established for the SQL Server and Oracle connectors.
This means more shared coded between these connectors, and in turn reduced maintenance efforts for the development team going forward;
but there's one immediately tangible advantage for you coming with this, too:
the Postgres connector now exposes the same metrics you already know from the other connectors.

Finally, the new release contains a range of bugfixes and other useful improvements.
Let's explore some details below.

+++<!-- more -->+++

== Incubating Cassandra Connector

If you have been following this blog lately, you'll have read about the latest addition to the Debezium family
in Joy Gao's excellent posts about the new connector
(link:/blog/2019/07/12/streaming-cassandra-at-wepay-part-1/[part 1], link:/blog/2019/07/15/streaming-cassandra-at-wepay-part-2/[part 2]).

In case you haven't read those yet, we'd highly recommend to do so in order to learn more about the challenges encountered when implementing a CDC connector for a distributed datastore such as Cassandra as well as the design decisions made in order to come up with a first "minimal viable product".
Joy also did a https://www.infoq.com/presentations/wepay-database-streaming/[great talk at QCon] last year, which touches on the topic of CDC for Cassandra.

Having been originally developed internally at link:/blog/2017/02/22/Debezium-at-WePay/[long-term Debezium user] WePay,
the https://wecode.wepay.com/[WePay team] decided to open-source their work, put it under the Debezium umbrella and continue to evolve it there.
That's really great news for the Debezium community!
We couldn't be happier about this contribution and look forward to evolving this new connector together in the open.

At this point the Cassandra connector is in "incubating" state,
i.e. its design and implementation are still pretty much in flux, the event structure which it creates may change in future releases etc.
Note that, unlike the other Debezium connectors, this one currently is not based on Kafka Connect.
Instead, it is implemented as a standalone process running on Cassandra node(s) themselves.
Refer to the blog posts linked above for the reasoning behind this design and possible future developments around this.
Needless to say, any ideas and contributions in this area will be highly welcomed.

Together with the connector we've also provided an initial draft of the link:/docs/connectors/cassandra[connector documentation];
this is still work-in-progress and will be amended in the next few days.

== Further New Features

The Postgres connector supports the metrics known from SQL Server and Oracle now (https://issues.redhat.com/browse/DBZ-777[DBZ-777]).
When using the SQL Server connector, it is now ensured that tables are snapshotted in a deterministic order,
as defined by the given table whitelist configuration (https://issues.redhat.com/browse/DBZ-1254[DBZ-1254]).

There have also been two improvements to our SMTs (single message transformations):

* The SMT for link:/docs/configuration/event-flattening/[new record state extraction] allows to add additional columns for propagating metadata fields from the `source` block
(https://issues.redhat.com/browse/DBZ-1395[DBZ-1395], e.g. useful to propagate the transaction into sink tables).
* The default structure produced by the link:/docs/configuration/outbox-event-router/[outbox routing SMT] has been further streamlined (https://issues.redhat.com/browse/DBZ-1385[DBZ-1385]);
the message value will now only contain the contents of the configured outbox table payload column.
In case you want to re-add the `eventType` value, you can configure it as an "additional field",
which either goes into the message as a header (recommended) or into the message value,
which as before will be a nested structure then.

== Bugfixes and Other Improvements

Finally, here's an overview of asorted bugfixes in the 0.10 Beta4 release:

* The MySQL connector handles `GRANT DELETE ON <table>` statements correctly (https://issues.redhat.com/browse/DBZ-1411[DBZ-1411])
* Superfluous tables scans are avoided when using the `initial_schema_only` snapshot strategy with SQL Server (https://issues.redhat.com/browse/DBZ-1417[DBZ-1417])
* The superfluous creation of connections is avoided when obtaining the xmin position of Postgres (https://issues.redhat.com/browse/DBZ-1381[DBZ-1381])
* The new record state extraction SMT handles heartbeat events correctly (https://issues.redhat.com/browse/DBZ-1430[DBZ-1430])

Please refer to the 0.10.0.Beta4 link:/docs/releases/#release-0-10-0-beta4[release notes] for the complete list of addressed issues and the upgrading procedure.

A big thank you goes out to all the contributors from the Debezium community who worked on this release:
https://github.com/jgao54[Joy Gao],
https://github.com/renatomefi[Renato Mefi] and
https://github.com/willome[Guillaume Rosauro]!
