---
tags: [ releases, mysql, postgres, mongodb, sqlserver, oracle, docker ]
---
= Debezium 0.10.0.Beta3 Released
jpechane
:awestruct-tags: [ releases, mysql, postgres, mongodb, sqlserver, oracle, docker ]
:awestruct-layout: blog-post

The summer is at its peak but Debezium community is not relenting in its effort so the Debezium *0.10.0.Beta3* is released.

This version not only continues in incremental improvements of Debezium but also brings new shiny features.

All of you who are using PostgreSQL 10 and higher as a service offered by different cloud providers definitely felt the complications when you needed to deploy logical decoding plugin necessary to enable streaming.
This is no longer necessary. Debezium now supports (https://issues.redhat.com/browse/DBZ-766[DBZ-766]) https://www.postgresql.org/docs/10/protocol-logical-replication.html[pgoutput] replication protocol that is available out-of-the-box since PostgreSQL 10. 

There is a set of further minor improvements.
The tombstones for deletes are configurable for all connectors now (https://issues.redhat.com/browse/DBZ-1365[DBZ-1365]).
Also tables without primary keys are now supported for all connectors (https://issues.redhat.com/browse/DBZ-916[DBZ-916]).
This further reduces the gap between old and new connectors capabilities.

There are improvements for heartbeat system.
Heartbeat messages now contain the timestamp (https://issues.redhat.com/browse/DBZ-1363[DBZ-1363]) of when they were created in their body.
The new messages are properly skipped by the Outbox router (https://issues.redhat.com/browse/DBZ-1388[DBZ-1388]).
MySQL connector additionally uses heartbeats for `BinlogReader` (https://issues.redhat.com/browse/DBZ-1338[DBZ-1338]).
MongoDB connector now utilizes heartbeats too (https://issues.redhat.com/browse/DBZ-1198[DBZ-1198]).

As we now that metrics are very important for keeping Debezium happy in production we have extended the set of supported metrics.
A new metric count of events in error (https://issues.redhat.com/browse/DBZ-1222[DBZ-1222]) is added so it is easy to monitor any non-standards in processing.
Database history recovery can take a long time during startup so it is now possible to monitor the progress of it (https://issues.redhat.com/browse/DBZ-1356[DBZ-1356]).

The other changes include updating of Docker images to use Kafka 2.3.0 (https://issues.redhat.com/browse/DBZ-1358[DBZ-1358]).
PostgreSQL supports lockless snapshotting (https://issues.redhat.com/browse/DBZ-1238[DBZ-1238]) and Outbox router now  process delete messages (https://issues.redhat.com/browse/DBZ-1320[DBZ-1320]).

We continue with stabilization of the 0.10 release line, with lots of bug fixes to the different connectors.

Multiple defects in MySQL parser have been fixed (https://issues.redhat.com/browse/DBZ-1398[DBZ-1398], (https://issues.redhat.com/browse/DBZ-1397[DBZ-1397], https://issues.redhat.com/browse/DBZ-1376[DBZ-1376]) and `SAVEPOINT` statements are no longer recorded in database history (https://issues.redhat.com/browse/DBZ-794[DBZ-794]).  

Under certain circumstances, it was possible that PostgreSQL connector lost the first event while switching to streaming from the snapshot (https://issues.redhat.com/browse/DBZ-1400[DBZ-1400]).

Please refer to the 0.10.0.Beta3 link:/docs/releases/#release-0-10-0-beta3[release notes] to learn more about all resolved issues and the upgrading procedure.

Many thanks to everybody from the Debezium community who contributed to this release:
https://github.com/addisonj[Addison Higham],
https://github.com/BinLi1988[Bin Li],
https://github.com/brbrown25[Brandon Brown] and
https://github.com/renatomefi[Renato Mefi].

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
