---
tags: [ releases, mysql, postgres, sqlserver, cassandra ]
---
= Debezium 1.0.0.Beta2 Released
ccranfor
:awestruct-tags: [ releases, mysql, postgres, sqlserver, cassandra ]
:awestruct-layout: blog-post

It is my pleasure to announce the release of Debezium *1.0.0.Beta2*!

This new Debezium release includes several notable new features, enhancements, and fixes:

* Support PostgreSQL `LTREE` columns with a logical data type (https://issues.redhat.com/browse/DBZ-1336[DBZ-1336])
* Support for PostgreSQL 12 (https://issues.redhat.com/browse/DBZ-1542[DBZ-1542])
* Validate configured PostgreSQL replication slot not contains no invalid characters (https://issues.redhat.com/browse/DBZ-1525[DBZ-1525])
* Add MySQL DDL parser support for index creation `VISIBLE` and `INVISIBLE` keywords (https://issues.redhat.com/browse/DBZ-1534[DBZ-1534])
* Add MySQL DDL parser support for granting `SESSION_VARIABLES_ADMIN` (https://issues.redhat.com/browse/DBZ-1535[DBZ-1535])
* Fix MongoDB `collection` source struct field when collection name contains a dot (https://issues.redhat.com/browse/DBZ-1563[DBZ-1563])
* Close idle transactions after performing a PostgreSQL snapshot (https://issues.redhat.com/browse/DBZ-1564[DBZ-1564])

Additionally the PostgreSQL connector was improved to warn users of a common situation where their configuration does not enable heartbeats and the monitored table(s) change less frequent than tables that are not monitored.
This often lead to the write ahead logs (WAL) consuming additional disk space creating a WAL backlog as the connector only flushes LSN information to PostgreSQL if the log contains events for tables that are monitored.
Our hope is this will help automated tools identify this problem earlier while also giving hints on how to avoid it.

In total, this release contains link:/releases/1.0/release-notes/#release-1.0.0-beta2[13 fixes].

Thanks to all the community members who helped make this happen:
https://github.com/grantcooksey[Grant Cooksey],
https://github.com/mincong-h[Mingcong Huang],
https://github.com/navdeep710[navdeep710]

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
