---
tags: [ introduction, presentation ]
---
= Debezium at DevNation Live
gmorling
:awestruct-tags: [ introduction, presentation ]
:awestruct-layout: blog-post

Last week I had the pleasure to do a https://developers.redhat.com/videos/youtube/QYbXDp4Vu-8/[webinar on change data streaming patterns for microservices] with the fabulous Burr Sutter at DevNation Live.

The recording of that 30 min session is available on YouTube now.
It also contains a demo that shows how to set-up a data streaming pipeline with Debezium and Apache Kafka,
running on OpenShift.
The demo begins at 12 min 40 into the recording.

Enjoy!

++++
<div class="responsive-video">
<iframe width="560" height="315" src="https://www.youtube.com/embed/QYbXDp4Vu-8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<!--<iframe width="1600" height="900" src="https://www.youtube.com/embed/IOZ2Um6e430?rel=0" frameborder="0" allowfullscreen></iframe>-->
</div>
++++

{nbsp} +
You can also find the https://speakerdeck.com/gunnarmorling/change-data-streaming-patterns-for-microservices-with-debezium-apache-kafka-meetup-hamburg[slide deck] (in a slightly extended version) on Speaker Deck:
{nbsp} +
{nbsp} +

++++
<div style="text-align-center">
<script async class="speakerdeck-embed" data-id="c390d77e50464c99916ede7368a279c2" data-ratio="1.77777777777778" src="//speakerdeck.com/assets/embed.js"></script>
</div>
++++

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
