---
tags: [ releases, mysql, postgres, mongodb, sqlserver, oracle, docker ]
---
= Debezium 0.10.0.Beta2 Released
gmorling
:awestruct-tags: [ releases, mysql, postgres, mongodb, sqlserver, oracle, docker ]
:awestruct-layout: blog-post

It's my pleasure to announce the release of Debezium *0.10.0.Beta2*!

This further stabilizes the 0.10 release line, with lots of bug fixes to the different connectors.
https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%200.10.0.Beta2[23 issues] were fixed for this release;
a couple of those relate to the DDL parser of the MySQL connector,
e.g. around `RENAME INDEX` (https://issues.redhat.com/browse/DBZ-1329[DBZ-1329]),
`SET NEW` in triggers (https://issues.redhat.com/browse/DBZ-1331[DBZ-1331])
and function definitions with the `COLLATE` keyword (https://issues.redhat.com/browse/DBZ-1332[DBZ-1332]).

For the Postgres connector we fixed a potential inconsistency when flushing processed LSNs to the database
(https://issues.redhat.com/browse/DBZ-1347[DBZ-1347]).
Also the "include.unknown.datatypes" option works as expected now during snapshotting
(https://issues.redhat.com/browse/DBZ-1335[DBZ-1335])
and the connector won't stumple upon materialized views during snapshotting any longer
(https://issues.redhat.com/browse/DBZ-1345[DBZ-1345]).

The SQL Server connector will use much less memory in many situations
(https://issues.redhat.com/browse/DBZ-1065[DBZ-1065])
and it's configurable now whether it should emit tombstone events for deletions or not
(https://issues.redhat.com/browse/DBZ-835[DBZ-835]).
This also was added for the Oracle connector, bringing consistency for this option across all the connectors.

Note that this release can be used with Apache Kafka 2.x, but not with 1.x.
This was an unintentional change and compatibility with 1.x will be restored for the Beta3 release
(the issue to track is https://issues.redhat.com/browse/DBZ-1361[DBZ-1361]).

Please refer to the 0.10.0.Beta2 link:/docs/releases/#release-0-10-0-beta2[release notes] to learn more about all resolved issues and the upgrading procedure.

Many thanks to everybody from the Debezium community who contributed to this release:
https://github.com/pan3793[Cheng Pan],
https://github.com/willome[Guillaume Rosauro],
https://github.com/szczeles[Mariusz Strzelecki] and
https://github.com/ssouris[Stathis Souris].

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
