---
layout: post
title:  Debezium's Newsletter 02/2019
date:   2019-10-17 10:19:59 -0600
tags: [ community, news, newsletter ]
author: ccranfor
---

Welcome to the Debezium community newsletter in which we share all things CDC related including blog posts, group discussions, as well as StackOverflow
questions that are relevant to our user community.

+++<!-- more -->+++

== Upcoming Events

* https://jokerconf.com/en/2019/talks/6nkqqv8zj4gmujxmo64ov3/[JokerConf - Practical change data streaming uses cases with Apache Kafka and Debezium]
* https://qconsf.com/sf2019/presentation/practical-change-data-streaming-use-cases-apache-kafka-debezium[QCon San Fransisco - Practical change data streaming use cases with Apache Kafka and Debezium]

== Articles

There have been quite a number of blog posts about Debezium lately; here are some of the latest ones that you should not miss:

This https://debezium.io/blog/2019/10/01/audit-logs-with-change-data-capture-and-stream-processing/[recent blog] by Gunnar Morling discusses how Debezium combined with Kafka stream post processing can deliver an enriched stream of events suitable for even the most complicated of tasks like audit tracking.

Rod Shokrian from Varo https://medium.com/engineering-varo/event-driven-architecture-and-the-outbox-pattern-569e6fba7216[recently blogged] about their CDC solution and experiences using Debezium in conjunction with the Outbox Pattern.

Community involvement is critical to each Open Source project and Debezium is no different.  Joy Gao https://wecode.wepay.com/posts/streaming-cassandra-at-wepay-part-1[blogs] about her experience at WePay where CDC innovation brought Cassandra and Debezium together.

This https://speakerdeck.com/jbfletch/using-kafka-to-discover-events-hidden-in-your-database[slide deck] by Anna McDonald showcases Debezium capturing database change events in complex architectures to emit enriched, derivative-based events across your enterprise.

There are quite a number of applicable use cases for Debezium.
Dave Cramer from Crunchy Data recently https://info.crunchydata.com/blog/postgresql-change-data-capture-with-debezium[blogged] about his experiences using Debezium to replicate data between both a source and sink PostgreSQL environment using CDC and Apache Kafka.

Data analytics are vital across lots of industries.
This https://medium.com/convoy-tech/logs-offsets-near-real-time-elt-with-apache-kafka-snowflake-473da1e4d776[post] by Adrian Kreuziger discusses how Convoy used Debezium and Apache Kafka to design a low-latency data warehouse solution for the trucking industry.

You can also checkout our https://debezium.io/documentation/online-resources[online resources] for more...

== Examples

An example is often much like a picture, its worth a thousand words.
Debezium's https://github.com/debezium/debezium-examples[examples repository] has recently undergone changes introducing new examples and update existing ones:

* [NEW] https://github.com/debezium/debezium-examples/tree/master/auditlog[Build Audit Logs using Debezium and Kafka Streams]
* [NEW] https://github.com/debezium/debezium-examples/tree/master/postgres-toast[Dealing with PostgreSQL TOAST columns]
* [UPDATE] https://github.com/debezium/debezium-examples/tree/master/end-to-end-demo[End to End demo now supports propagating delete events]
* [UPDATE] https://github.com/debezium/debezium-examples/tree/master/unwrap-smt[Unwrap SMT example now propagates delete events]
* [UPDATE] https://github.com/debezium/debezium-examples/tree/master/unwrap-mongodb-smt[MongoDB Unwrap SMT example now propagates delete events]

== Time to upgrade

Debezium version https://debezium.io/blog/2019/10/02/debezium-0-10-0-final-released/[0.10.0.Final] was released at the beginning of October.
If you are using the 0.9 branch, we urge you to check out the latest major release.
For details on the bug fixes, enhancements, and improvements that spanned 8 preview releases, check out the https://debezium.io/releases/0.10/release-notes/[release-notes].

The Debezium team has also begun active development on the next major version, 1.0.
If you want details on the bug fixes, enhancements, and improvements, you can view https://debezium.io/releases/1.0/release-notes[release-notes] for more details.

== Questions and answers

* https://stackoverflow.com/questions/58337376/debezium-postgres-error-parameter-include-unchanged-toast-was-deprecated[Debezium postgres ERROR: Parameter "include-unchanged-toast" was deprecated]
* https://stackoverflow.com/questions/57095096/unable-to-register-debezium-kafka-connect-connector-in-ssl-enabled-kafka-clust[Unable to register Debezium (Kafka-Connect) connector in SSL enabled Kafka cluster]
* https://groups.google.com/d/msg/debezium/1vKTWwcf71I/L98pV5nnBgAJ[Debezium or database triggers]

== Using Debezium?

We recently added a https://www.debezium.io/community/users[community users] page to https://www.debezium.io.
If you are a user of Debezium and would like to be included, please send us a GitHub pull request or reach out to us directly.

== Getting involved

It can often be overwhelming when starting work on an existing code base.
We welcome community contributions and we want to make the process of getting started extremely easy.
Below is a list of open issues that are currently labeled with `easy-starter` if you want to dive in quick.

* Configure Avro serialization automatically when detecting link to schema registry (https://issues.redhat.com/browse/DBZ-59[DBZ-59])
* Add tests for using fallback values with default REPLICA IDENTITY (https://issues.redhat.com/browse/DBZ-1158[DBZ-1158])
* Add ability to insert fields from op field in ExtractNewRecordState SMT (https://issues.redhat.com/browse/DBZ-1452[DBZ-1452])
* Support CREATE TABLE ... LIKE syntax for blacklisted source table (https://issues.redhat.com/browse/DBZ-1496[DBZ-1496])
* Provide change event JSON Serde for Kafka Streams (https://issues.redhat.com/browse/DBZ-1533[DBZ-1533])
* Explore SMT for Externalizing large column values (https://issues.redhat.com/browse/DBZ-1541[DBZ-1541])
* Whitespaces not stripped from table.whitelist (https://issues.redhat.com/browse/DBZ-1546[DBZ-1546])

== Opportunities

We recently https://twitter.com/debezium/status/1184514850627739649[tweeted] about an Internship opening on the Debezium project.

* Are you in the Czech Republic area?
* Are you passionate about Open Source?
* Do you think change data capture is interesting?

If you answered yes to any or all of these, then you should definitely check out https://global-redhat.icims.com/jobs/73814/software-developer-internship---debezium-project/job?hub=7&mobile=false&width=1470&height=500&bga=true&needsRedirect=false&jan1offset=60&jun1offset=120[the details] and apply!

== Feedback

We intend to publish new additions of this newsletter periodically.
Should anyone have any suggestions on changes or what could be highlighted here, we welcome that feedback.
You can reach out to us via any of our community channels found link:/community[here].
