---
layout: post
title:  Site and Documentation Overhaul
date:   2019-09-05 10:19:59 -0600
tags: [ community, news, website ]
author: ccranfor
---

This past summer has been a super exciting time for the team.
Not only have we been working hard on Debezium 0.10 but we have unveiled some recent changes to link:/[debezium.io].

+++<!-- more -->+++

== New Releases Page

It is important that the Debezium community be able to find information easily about a given release series.
We have introduced a new link:/releases[Releases] area on the site that describes details about each release series (e.g. link:/releases/0.9[0.9], the current _stable release_ and link:/releases/0.10[0.10], the current _development_ release) such as:

* What database or Apache Kafka (Connect) platforms were tested
* What Java version is supported
* How to migrate to a specific release series
* Where to download the connectors or other series artifacts
* What changes were introduced in that series
* And much more...

The goal is to make it simple and easy to find all information about a specific release series in a single place.

== New Documentation

Probably one of the most limiting factors with how our documentation was published previously is that it focused solely on the idea of the latest stable version.
Also the documentation sources were separated from the actual code sources in the main code repository.
This presented several drawbacks:

* Confusing to users of older releases
* Prevented publishing documentation for development versions
* Caused friction for contributors when implementing new features that need documentation updates

What we felt we needed to provide the community was documentation published by version.
This would allow documentation to be tailored specific to that version, allowing fluid changes for future versions without impact to prior versions.

Such a solution also has the benefit that it enables the Debezium team to publish development version documentation easily, which is a critical step in helping users who test unstable releases.

With https://antora.org/[Antora] we found a toolchain which addresses these needs.
It allows us to maintain different versions of the documentation right next to the actual code and aggregate them on the website.
Going forward, Debezium documentation can be found at link:/documentation[Reference documentation].
This page allows visitors to quickly navigate to documentation for a specific version.
Once in the documentation, you can quickly navigate between various Debezium versions easily.
Built by the friendly folks behind AsciiDoctor, Antora comes with lots of well thought out details;
e.g. there's an "Edit this Page" link on each page, which makes it very easy to create GitHub pull requests with documentation fixes.

Finally, we also took the time to fill the long-standing place holder pages describing the Debezium link:/documentation/reference/0.10/architecture.html[Architecture] and link:/documentation/reference/0.10/features.html[Features] with some actual contents.
Woohoo!

== Feedback

We certainly hope these recent changes make it much easier for the community.

If something is unclear, could be improved, or worse a link that isn't working, we welcome feedback.
You can report such concerns to us by link:https://issues.redhat.com/browse/DBZ[opening an issue] for our website.
