---
layout: post
title:  Debezium 0.9.4.Final Released
date:   2019-04-11 10:19:59 -0600
tags: [ releases, mysql, postgres, docker ]
author: gmorling
---

It's my pleasure to announce the release of Debezium *0.9.4.Final*!

This is a drop-in replacement for earlier Debezium 0.9.x versions, containing mostly bug fixes and some improvements related to metrics.
Overall, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%200.9.4.Final[17 issues] were resolved.

+++<!-- more -->+++

== MySQL Connector Improvements

The Debezium connector for MySQL comes with two new metrics:

* Whether GTID is enabled for offset tracking or not (https://issues.redhat.com/browse/DBZ-1221[DBZ-1221])
* Number of filtered events (https://issues.redhat.com/browse/DBZ-1206[DBZ-1206])

It also supports database connections using TLS 1.2 (https://issues.redhat.com/browse/DBZ-1208[DBZ-1208]) now.

== New Postgres Datatypes

The Postgres connector now allows to capture changes to columns of the `CIDR` and `INET` types (https://issues.redhat.com/browse/DBZ-1189[DBZ-1189]).

== Bug Fixes

The fixed bugs include the following:

* Closing connection after snapshotting (https://issues.redhat.com/browse/DBZ-1218[DBZ-1218])
* Can parse ALTER statement affecting enum column with character set options (https://issues.redhat.com/browse/DBZ-1203[DBZ-1203])
* Avoiding timeout after bootstrapping a new table (https://issues.redhat.com/browse/DBZ-1207[DBZ-1207])

Check out the link:/docs/releases/#release-0-9-4-final[release notes] for the complete list of issues fixed in Debezium 0.9.4.

Many thanks to Debezium community members
https://github.com/jchipmunk[Andrey Pustovetov],
https://github.com/jordanbragg[Jordan Bragg],
https://github.com/jgao54[Joy Gao],
https://github.com/preethi29[Preethi Sadagopan],
https://github.com/renatomefi[Renato Mefi],
https://github.com/sashakovryga[Sasha Kovryga],
https://github.com/ShubhamRwt[Shubham Rawat] and
https://github.com/Crim[Stephen Powis]
for their contributions to this release!
