---
layout: post
title:  Debezium 1.2.0.Beta2 Released
date:   2020-05-19 10:19:59 -0600
tags: [ releases, mysql, postgres, mongodb, sqlserver, cassandra, db2, testcontainers, debezium-server ]
author: gmorling
---

I'm very happy to share the news that Debezium *1.2.0.Beta2* has been released!

Core feature of this release is _Debezium Server_,
a dedicated stand-alone runtime for Debezium, opening up its open-source change data capture capabilities towards messaging infrastructure like Amazon Kinesis.

Overall, the community has fixed https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.2.0.Beta2%20ORDER%20BY%20issuetype%20DESC[25 issues] since the Beta1 release,
some of which we're going to explore in more depth in the remainder of this post.

+++<!-- more -->+++

== Debezium Server

Adding the link:/documentation/reference/operations/debezium-server.html[Debezium Server] runtime is a major milestone for the project.
It is a ready-to-use standalone application for executing Debezium connectors.
With Debezium Server, users can now choose from three different ways of operating Debezium,
matching their individual needs:

* As plug-ins for https://kafka.apache.org/documentation/#connect[Kafka Connect], ingesting data change events into an Apache Kafka cluster
* Through the link:/documentation/reference/development/engine.html[Debezium Engine], embedded as a library into bespoke JVM-based applications
* Via Debezium Server, sending data change events to a growing number of messaging platforms like Kinesis

Which one of these modes of execution you should use depends on your specific prerequisites, requirements and CDC use cases.
Organizations running Apache Kafka and interested in setting up no-code data integration pipelines leveraging a rich connector eco-system, should go for the Kafka Connect approach.
In-application cache invalidation is an application benefitting from the Debezium embedded engine.
Debezium Server finally is meant for users who would like to take advantage of Debezium's CDC functionality,
using messaging platforms other than Apache Kafka.
While you could have done so before by means of the embedded engine and a bit of bespoke Java programming,
Debezium Server will greatly simplify this scenario.

Powered by the popular https://quarkus.io/[Quarkus] stack,
Debezium Server is a ready-made configurable Java application which runs a Debezium connector and propagates the produced change events to consumers via a chosen sink adapter.
Initially supporting Amazon Kinesis, the Debezium Server architecture is extensible,
and other adapters -- e.g. for Google Cloud Pub/Sub or Microsoft Azure Event Hubs --
will follow soon.
Through the Debezium Server extension API, you can also implement custom sink adapters for your preferred infrastructure of propagating change events to consumers.

Ultimately, Debezium Server also is means of realizing our vision of CDC-as-a-Service,
smoothly integrated with cloud-native infrastructure like Kubernetes and Knative.
This release marks the first step of this endavour, and we couldn't be more excited about the prospect of working together with the Debezium community towards this goal.

Stay tuned for more sink adapters, a container image, support for https://knative.dev/docs/eventing/[Knative Eventing], an operator for running Debezium Server on Kubernetes, and more!

== Other Features and Fixes

Besides Debezium Server, a few other improvements and fixes found their way into this release.
A number of improvements was done to the different single message transforms (SMTs) coming with Debezium:
 
* The recently added SMTs for content-based change link:/documentation/reference/configuration/filtering.html[event filtering] and link:/documentation/reference/configuration/content-based-routing.html[routing] can be applied to a sub-set of topics now (https://issues.redhat.com/browse/DBZ-2024[DBZ-2024])
* Record headers and topic name are exposed to script expressions configured for these SMTs, so they can be evaluated by the filtering and routing logic (https://issues.redhat.com/browse/DBZ-2074[DBZ-2074])
* The link:/documentation/reference/configuration/topic-routing.html[logical topic routing] SMT can optionally pass through message keys as-is, instead of enriching them with a source topic identifier (https://issues.redhat.com/browse/DBZ-2034[DBZ-2034]); this is very helpful when uniqueness of keys already is ensured across the different re-routed topics, e.g. when routing change events from the partition tables of a partitioned Postgres table into a single topic

Debezium's link:/documentation/reference/integrations/testcontainers.html[Testcontainers integration] allows for the usage of custom container images for Kafka Connect now (https://issues.redhat.com/browse/DBZ-2070[DBZ-2070]), which comes in handy if you want to leverage custom connectors, converters or SMTs in your integration tests.
For the SQL Server connector it's optionally possible now to skip the queries for obtaining LSN timestamps
(https://issues.redhat.com/browse/DBZ-1988[DBZ-1988]).
This can help to signficantly increase through-put of the connector.

Several fixes relate to the MySQL DDL parser,
e.g. due to additional DDL capabilities in MySQL 8.0.x (https://issues.redhat.com/browse/DBZ-2080[DBZ-2080], "Unable to parse MySQL ALTER statement with named primary key", https://issues.redhat.com/browse/DBZ-2067[DBZ-2067]; "Error and connector stops when DDL contains algorithm=instant") and when being used with MariaDB (https://issues.redhat.com/browse/DBZ-2062[DBZ-2062], "DDL statement throws error if compression keyword contains backticks (``)").

As always, you can find the complete list of all addressed issues and upgrading procedures in the link:/releases/1.2/release-notes/#release-1.2.0-beta2[release notes].

Many thanks to all the community members contributing to this release:
https://github.com/insom[Aaron Brady],
https://github.com/bingqinzhou[Bingqin Zhou],
https://github.com/bradengroom[Braden Groom],
https://github.com/gergof[Fándly Gergő],
https://github.com/grantcooksey[Grant Cooksey],
https://github.com/jgao54[Joy Gao],
https://github.com/jantpedraza[Juan Antonio Pedraza],
https://github.com/kaplanmaxe[Max Kaplan], and
https://github.com/crazy-2020[Xuan Shen]!
