---
layout: post
title:  Debezium 1.4.0.Beta1 Released
date:   2020-12-09
tags: [ releases, mysql, postgres, mongodb, sqlserver, cassandra, db2, oracle, vitess ]
author: ccranfor
---

I'm pleased to announce the release of Debezium *1.4.0.Beta1*!

This release includes support for distributed tracing,
lowercase table and schema naming for Db2,
specifying MySQL snapshot records as create or read operations,
and enhancements to Vitess for nullable and primary key columns.

+++<!-- more -->+++

Overall, the community fixed https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.4.0.Beta1%20ORDER%20BY%20issuetype%20DESC[39 issues] for this release.
Let's take a closer look at some of the highlights.

== Distributed Tracing

In a nutshell, distributed tracing is a pattern used to profile and monitor applications to allow quick identification of failures or performance concerns.
Tracing works by having each component in a distributed process contribute a block of metadata called a "span".
Each span contains unique details about that component's unit of work.
Typically a full distributed trace consists of a sequence of multiple spans.

Distributed tracing in Debezium is enabled by using the *ActivateTracingSpan* SMT:

[source]
----
"transforms": "tracing"
"transforms.tracing.type": "io.debezium.transforms.tracing.ActivateTracingSpan"
----

The above configuration will lead to the emitted message header containing the tracing key/value pairs.

A blog post discussing the distributed tracing support in depth, including end-to-end tracing for microservices data exchange via the outbox pattern, will follow up shortly.

== Bugfixes

Also a number of bugs were fixed, e.g.:

* DDL parser: Allow stored procedure variables in LIMIT clause https://issues.jboss.org/browse/DBZ-2692[DBZ-2692]
* Wrong mysql command in openshift dpeloyment docs https://issues.jboss.org/browse/DBZ-2746[DBZ-2746]
* long running transaction will be abandoned and ignored https://issues.jboss.org/browse/DBZ-2759[DBZ-2759]
* MS SQL Decimal with default value not matching the scale of the column definition cause exception https://issues.jboss.org/browse/DBZ-2767[DBZ-2767]
* Cassandra Connector doesn't shut down completely https://issues.jboss.org/browse/DBZ-2768[DBZ-2768]
* MySQL Parser fails for BINARY collation shortcut https://issues.jboss.org/browse/DBZ-2771[DBZ-2771]
* PostgresConnectorIT.shouldResumeStreamingFromSlotPositionForCustomSnapshot is failing for wal2json on CI https://issues.jboss.org/browse/DBZ-2772[DBZ-2772]
* Connector configuration property "database.out.server.name" is not relevant for Logminer implementation but cannot be omitted https://issues.jboss.org/browse/DBZ-2801[DBZ-2801]
* CHARACTER VARYING mysql identifier for varchar is not supported in debezium https://issues.jboss.org/browse/DBZ-2821[DBZ-2821]
* try-with-resources should not be used when OkHttp Response object is returned https://issues.jboss.org/browse/DBZ-2827[DBZ-2827]
* EmbeddedEngine does not shutdown when commitOffsets is interrupted https://issues.jboss.org/browse/DBZ-2830[DBZ-2830]
* Rename user command parsing fails https://issues.jboss.org/browse/DBZ-2743[DBZ-2743]

A big thank you to all the contributors from the community who worked on this release:
https://github.com/jeremy-l-ford[Jeremy Ford],
https://github.com/hauntingEcho[Matt Beary],
https://github.com/ramanenka[Vadzim Ramanenka],
https://github.com/johnjmartin[John Martin],
https://github.com/keweishang[Kewei Shang],
https://github.com/vanhoale[Hoa Le],
https://github.com/rareddy[Ramesh Reddy], and
https://github.com/seeekr[Denis Andrejew].
