---
layout: post
title:  Debezium 1.2.1.Final Released
date:   2020-07-16 10:19:59 -0600
tags: [ releases, mysql, postgres, mongodb, sqlserver, testcontainers, debezium-server ]
author: gmorling
---
= Debezium 1.2.1.Final Released
gmorling
:awestruct-tags: [ releases, mysql, postgres, mongodb, sqlserver, testcontainers, debezium-server ]
:awestruct-layout: blog-post

I am happy to announce the release of Debezium *1.2.1.Final*!

This release includes several bug fixes to different Debezium connectors, and we highly recommend the upgrade from 1.2.0.Final and earlier versions:

* The Debezium Postgres connector may have missed events from concurrent transactions when transitioning from snapshotting to streaming events from the WAL (https://issues.redhat.com/browse/DBZ-2288[DBZ-2288]);
this is fixed now when using the link:/documentation/reference/connectors/postgresql.html#postgresql-property-snapshot-mode[exported snapshotting mode];
this mode should preferably be used, and for Debezium 1.3 we're planning for this to be the basis for all the existing snapshotting modes
* The Postgres JDBC driver got upgraded to 42.2.14 (https://issues.redhat.com/browse/DBZ-2317[DBZ-2317]),
which fixes a CVE in the driver related to processing XML column values sourced from untrusted XML input
* The Debezium MySQL connector MariaDB's supports `ALTER TABLE` statements with `IF EXISTS` (https://issues.redhat.com/browse/DBZ-2219[DBZ-2219]);
it also handles single dimension `DECIMAL` columns in `CAST` expressions (https://issues.redhat.com/browse/DBZ-2305[DBZ-2305])
* The MySQL connector automatically filters out specific DML binlog entries from internal tables when using it with Amazon RDS (https://issues.redhat.com/browse/DBZ-2275[DBZ-2275])
* The Debezium MongoDB connector got more resilient against connection losses (https://issues.redhat.com/browse/DBZ-2141[DBZ-2141])

If you're using the https://www.apicur.io/registry/[Apicurio] open-source API and schema registry for link:/documentation/reference/configuration/avro.html[managing the JSON and Avro schemas] of your Debezium connectors,
then things got a bit simpler for you:
the Debezium container image for Kafka Connect comes with the required converters out of the box now
(https://issues.redhat.com/browse/DBZ-2083[DBZ-2083]).

Overall, 34 issues were fixed for this release; please refer to the link:/releases/1.2/release-notes/#release-1.2.1-final[release notes] for the full list of addressed issues, upgrade procedures, and notes on any backward compatibility changes.

Many thanks to all the members from the Debezium community contributing to this release:

https://github.com/frankkoornstra[Frank Koornstra],
https://github.com/jgraf50[John Graf],
https://github.com/jhuiting[Jos Huiting],
https://github.com/jhiza[Justin Hiza],
https://github.com/keweishang[Kewei Shang],
https://github.com/michaelwang[Michael Wang],
https://github.com/omarsmak[Omar Al-Safi], and
https://github.com/rhauch[Randall Hauch]!

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
