---
layout: post
title:  Debezium 1.1.0.Final Released
date:   2020-03-24 10:19:59 -0600
tags: [ releases, mysql, postgres, mongodb, oracle, sqlserver, db2, cassandra ]
author: gmorling
---
= Debezium 1.1.0.Final Released
gmorling
:awestruct-tags: [ releases, mysql, postgres, mongodb, oracle, sqlserver, db2, cassandra ]
:awestruct-layout: blog-post

It's with great excitement that I'm announcing the release of Debezium *1.1.0.Final*!

About three months after the 1.0 release, this new version comes with many exciting new features such as:

* a link:/documentation/reference/1.1/integrations/outbox.html[Quarkus] extension facilitating the outbox pattern
* support for the link:/documentation/reference/1.1/integrations/cloudevents.html[CloudEvents] specification
* an incubating link:/documentation/reference/1.1/connectors/db2.html[connector for the IBM Db2 database]
* transaction marker events
* support for link:/documentation/reference/1.1/integrations/testcontainers.html[CDC integration testing] via Testcontainers
* a brand-new API Debezium module containing a reworked link:/documentation/reference/1.1/development/engine.html[embedded engine API] as well as an SPI for link:/documentation/reference/1.1/development/converters.html[customizing schema and values of change events]

Besides these key features, there's many other smaller improvements such as reconnects for the Postgres connector, more flexibility when extracting the `after` state from change events,
and more powerful options for propagating metadata on the source types of captured columns.

Since the CR1 release, https://issues.redhat.com/projects/DBZ/versions/12344981[22 more issues] were resolved: mostly bug fixes, documentation improvements and related to the stabilization of some flaky tests that'd fail intermittently on our CI server.

Besides these, there's one very useful improvement for the Postgres connector:
as part of its heartbeat functionality, it can now regularly execute DML operations in the source database (https://issues.redhat.com/browse/DBZ-1815[DBZ-1815]).
This helps to prevent situations with a combination of multiple databases on the same database host,
receiving writes with different frequencies,
where Debezium couldn't acknowledge processed WAL offsets with the source database otherwise.

Overall, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20in%20(1.1.0.Alpha1%2C%201.1.0.Beta1%2C%201.1.0.Beta2%2C%201.1.0.CR1%2C%201.1.0.Final)[123 issues] have been resolved for Debezium 1.1 and its preview releases.
Please refer to the original announcements
(link:/blog/2020/01/16/debezium-1-1-alpha1-released/[Alpha1],
link:/blog/2020/02/11/debezium-1-1-beta1-released/[Beta1],
link:/blog/2020/02/13/debezium-1-1-beta2-released/[Beta2],
link:/blog/2020/03/13/debezium-1-1-c1-released/[CR1])
to learn more about the details.

The most important part of any open-source project is its community.
The following people have contributed to Debezium 1.1,
bumping the total number of community members contributing to Debezium to more than 175:

_https://github.com/Alan-zhangzf[Alan Zhangzf],
https://github.com/oscerd[Andrea Cosentino],
https://github.com/lordofthejars[Alex Soto],
https://github.com/ahus1[Alexander Schwartz],
https://github.com/bingqinzhou[Bingqin Zhou],
https://github.com/daanroosen-DS[Daan Roosen],
https://github.com/mozinator[Fabian Aussems],
https://github.com/FabioCantarini[Fabio Cantarini],
https://github.com/FrankMormino[Frank Mormino],
https://github.com/blcksrx[Hossein Torabi],
https://github.com/igabaydulin[Igor Gabaydulin],
https://github.com/juyttenh[Jan Uyttenhove],
https://github.com/JanHendrikDolling[Jan-Hendrik Dolling],
https://github.com/jgraf50[John Graf],
https://github.com/jpsoroulas[John Psoroulas],
https://github.com/jhuiting[Jos Huiting],
https://github.com/lga-zurich[Luis Garcés-Erice],
https://github.com/mzbyszynski[Marc Zbyszynski],
https://github.com/matzew[Matthias Wessendorf],
https://github.com/mwinstanley[Melissa Winstanley],
https://github.com/zrlurb[Peter Urbanetz],
https://github.com/raultov[Raúl Tovar],
https://github.com/rgibaiev[Ruslan Gibaiev],
https://github.com/sahandilshan[Sahan Dilshan],
https://github.com/SeanRooooney[Sean Rooney],
https://github.com/taylor-rolison[Taylor Rolison],
https://github.com/vasilyulianko-visma[Vasily Ulianko],
https://github.com/vedit[Vedit Firat Arig],
https://github.com/liulangwa[Yongjun Du] and
https://github.com/Wang-Yu-Chao[Yuchao Wang]_

A big, big "thank you" to each and every one of you!

Having shipped Debezium 1.1, the team is focusing on 1.2 now.
Adhering to a quarterly release cadence,
Debezium 1.2 is scheduled for end of June.
You can expect preview releases roughly every three weeks.

What's coming up in 1.2?
Check out the link:/roadmap/[roadmap] to learn more;
one key feature will be a "standalone mode" for running Debezium independently of Kafka Connect,
allowing to feed change events to other messaging infrastructure such as Amazon Kinesis.
Also make sure to let us know about your suggestions, requirements and feature requests!

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
