---
layout: post
title:  Debezium 1.3.0.Final Released
date:   2020-10-01 10:19:59 -0600
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: gmorling
---

It's with great please that I'm announcing the release of Debezium *1.3.0.Final*!

As per Debezium's quarterly release cadence, this wraps up the work of the last three months.
Overall, the community has fixed https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20in%20(1.3.0.Final%2C%201.3.0.Alpha1%2C%201.3.0.Beta1%2C%201.3.0.Beta2%2C%201.3.0.CR1)%20ORDER%20BY%20issuetype%20DESC%2C%20updated%20DESC%2C%20priority%20DESC[138 issues] during that time, including the following key features and changes:

* A new incubating link:/documentation/reference/connectors/oracle.html#_logminer[LogMiner-based implementation] for ingesting change events from Oracle
* Support for Azure Event Hubs in link:/documentation/reference/operations/debezium-server.html[Debezium Server]
* Upgrade to Apache Kafka 2.6
* Revised https://debezium.io/blog/2020/09/03/debezium-1-3-beta1-released/[filter option names]
* A new SQL Server connector snapshot mode, `initial_only`
* Support for database-filtered columns for SQL Server
* Additional connection options for the MongoDB connector
* Improvements to `ByteBufferConverter` for implementing the link:/documentation/reference/configuration/outbox-event-router.html[outbox pattern] with Avro as the payload format

+++<!-- more -->+++

Please refer to the announcements of the preview releases (https://debezium.io/blog/2020/08/06/debezium-1-3-alpha1-released/[Alpha1], https://debezium.io/blog/2020/09/03/debezium-1-3-beta1-released/[Beta1], https://debezium.io/blog/2020/09/16/debezium-1-3-beta2-released/[Beta2], https://debezium.io/blog/2020/09/24/debezium-1-3-cr1-released/[CR1]) for more details.
Since last week's CR1 release, we've https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.3.0.Final%20ORDER%20BY%20issuetype%20DESC%2C%20updated%20DESC%2C%20priority%20DESC[been focusing] on ironing out some remaining bugs and improvements to the documentation.
To learn more about procedures for upgrading from earlier Debezium versions, please take a look the link:/releases/1.3/release-notes/#release-1.3.0-final1[release notes].

Thank you to everyone testing the preview releases, this is of invaluable help for spotting and fixing short-comings in new features as well as regressions.
And of course I'd also like to thank all the community members contributing to this release:
https://github.com/insom[Aaron Brady],
https://github.com/abhirockzz[Abhishek Gupta],
https://github.com/AndreyIg[Andrey Ignatenko],
https://github.com/creactiviti[Arik Cohen],
https://github.com/bingqinzhou[Bingqin Zhou],
https://github.com/bjoernhaeuser[Björn Häuser],
https://github.com/coryharperbind[Cory Harper],
https://github.com/denisprog[Denis Liseichykau],
https://github.com/eric-weaver[Eric Weaver],
https://github.com/grantcooksey[Grant Cooksey],
https://github.com/grzegorz8[Grzegorz Kołakowski],
https://github.com/gsmet[Guillaume Smet],
https://github.com/GuyIEX[Guy Pascarella],
https://github.com/jgormley6[James Gormley],
https://github.com/jfinzel[Jeremy Finzel],
https://github.com/jonaslins[Jonas Lins],
https://github.com/jhuiting[Jos Huiting],
https://github.com/jhiza[Justin Hiza],
https://github.com/korzenek[Lukasz Korzeniowski],
https://github.com/lga-zurich[Luis Garcés-Erice],
https://github.com/hauntingEcho[Matt Beary],
https://github.com/misaert[Mickaël Isaert],
https://github.com/mtagle[Moira Tagle],
https://github.com/rivernate[Nathan Mills],
https://github.com/petoju[Peter Junos],
https://github.com/rgibaiev[Ruslan Gibaiev],
https://github.com/tprelle[Thomas Prelle], and
https://github.com/victorxiang30[Victor Xiang]!

Overall, more than 220 individuals have contributed to the Debezium project at this point.

But not only that, also the number of Debezium users is constantly growing,
as e.g. documented on our link:/community/users/[reference list of Debezium users]
(let us know if you want to be added).
There's also several new entries in our compilation of link:/documentation/online-resources/[public talks and blog posts] touching on Debezium,
e.g. a highly recommendable talk by Marta Paes about link:https://noti.st/morsapaes/liQzgs/change-data-capture-with-flink-sql-and-debezium[change data capture with Flink SQL and Debezium],
a blog post by Cemal Turkoglu about https://turkogluc.com/postgresql-capture-data-change-with-debezium/[[making sense of change data capture pipelines for Postgres with the Debezium Kafka Connector],
and a nice piece on https://medium.com/@changeant/implementing-the-transactional-outbox-pattern-with-debezium-in-quarkus-f2680306951[implementing the outbox pattern with Debezium in Quarkus] by Iain Porter.
Abdellatif Bouchama did an amazing job by creating a https://developers.redhat.com/cheat-sheets/debezium-openshift-cheat-sheet[cheat sheet] for running Debezium on OpenShift.

== Outlook

With the 1.3 Final release out, planning for the 1.4 version (due by the end of the year) is happening right now.
The link:/roadmap/[roadmap] still is in flux, so make sure to chime in and let us know about your requirements and feature requests.
Some of the things we're likely going to work on include:

* The https://github.com/debezium/debezium-connector-vitess/[community-led connector] for https://vitess.io/[Vitess]; the initial contribution has already been merged and we plan to ship the first release of this as part of Debezium 1.4 Alpha1 later this month
* Moving the MySQL connector to the CDC connector framework shared by most other Debezium connectors; this will drastically reduce maintenance burden of this connector in the future
* Exploring more powerful snapshotting options (e.g. for parallelization and re-doing snapshots of selected tables)
* Improving the new LogMiner-based implementation for Oracle

And lastly, there's one other area of activity which I'm particularly excited to share here today for the first time:
a proof-of-concept of how a potential future Debezium user interface might look like.
In that PoC we're exploring how a graphical UI could help with the set-up and operation of Debezium connectors.
We've got quite a few ideas in that field and will share more details in a blog post very soon.
If you feel adventureous in the meantime, you could grab the https://github.com/debezium/debezium-ui-poc/[current PoC code] and take it for spin!

Until then, happy change data streaming, onwards and upwards!
