---
layout: post
title:  Debezium 1.3.0.CR1 Released
date:   2020-09-24 10:19:59 -0600
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, outbox ]
author: ccranfor
---

I'm very happy to announce the release of Debezium *1.3.0.CR1*!

As we approach the final stretch of Debezium 1.3 Final,
we took this opportunity to add delegate converter support for the `ByteBufferConverter` and introduce a `debezium-scripting` module.
In addition, there's also a range of bug fixes and quite a bit of documentation polish;
overall, not less than https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.3.0.CR1%20ORDER%20BY%20issuetype%20DESC&startIndex=20[15 issues] have been resolved for this release.

+++<!-- more -->+++

== ByteBufferConverter improvements

The `ByteBufferConverter` is a converter that is used with the Outbox event router SMT to serialize an existing Avro payload column.
In a recent report (https://issues.jboss.org/browse/DBZ-2396[DBZ-2396]),
the `ByteBufferConverter` was unable to serialize events emitted from a connector that was configured to emit heartbeat, transaction metadata, or schema change events.
In order to improve the converter's compatibility when these events are emitted,
the `ByteBufferConverter` can now be configured to delegate event serialization to an additional converter.
This delegation is necessary so that heartbeat, transaction metadata, and schema change events (if applicable) can be serialized.

In order to use the Outbox event router SMT and the `ByteBufferConverter` with these event types,
the connector configuration must be changed to reflect the delegate converter and its configurable options.

As an example to use the Apache Kafka `JsonConverter` as a delegate with schemas disabled,
the following configuration would need to be included in the connector:

[source]
----
value.converter=io.debezium.converters.ByteBufferConverter
value.converter.delegate.converter.type=org.apache.kafka.connect.json.JsonConverter
value.converter.delegate.converter.type.schemas.enable=false
----

For more information about using the `ByteBufferConverter`,
please see the https://debezium.io/documentation/reference/configuration/outbox-event-router.html#avro-as-payload-format[Using Avro as the payload format] section in the Outbox event router documentation.

== Scripting module

In this release, the SMTs for content-based routing and filtering that both use JSR 223 scripting engines have been moved out of `debezium-core` and into a separate artifact `debezium-scripting` (https://issues.jboss.org/browse/DBZ-2549[DBZ-2549]).
Any connector that previous used these SMTs requires that the new artifact be added to the plug-in directories for those connector(s).

When using the Debezium container image for Kafka Connect, set the environment variable `ENABLE_DEBEZIUM_SCRIPTING` to `true` to enable this feature.
This change is done to allow the scripting functionality to be available only in environments with an apppropriately secured Kafka Connect configuration interface.

== Misc. Features and Bug Fixes

In addition, the community has completed the work on some other features and fixes, too:

* Catch up streaming before snapshot may duplicate messages upon resuming streaming https://issues.jboss.org/browse/DBZ-2550[DBZ-2550]
* Fix Quarkus datasource configuration for Quarkus 1.9 https://issues.jboss.org/browse/DBZ-2558[DBZ-2558]
* Implement connection retry support for Oracle https://issues.jboss.org/browse/DBZ-2531[DBZ-2531]

As always, please refer to the link:/releases/1.3/release-notes/#release-1.3.0-cr1[release notes] for the complete list of resolved issues as well as procedures for upgrading from earlier Debezium versions.

Thank you so much to https://github.com/gsmet[Guillaume Smet] and https://github.com/grantcooksey[Grant Cooksey] for their contributions to this release.

== Outlook

Barring any unforeseen regressions and bug reports, Debezium 1.3 Final should be out next week.
Until then, we'll focus on some more polishing.
The https://github.com/debezium/debezium-connector-vitess/pull/1[community-lead work] towards a Debezium connector for https://vitess.io/[Vitess] is also making good progress,
with an initial release of this new connector planned with Debezium 1.4 Alpha1 in late October.
