---
layout: post
title:  Debezium 1.4.0.Alpha1 Released
date:   2020-10-23 10:19:59 -0600
tags: [ releases, mysql, postgres, mongodb, sqlserver, cassandra, db2, oracle, vitess ]
author: ccranfor
---
= Debezium 1.4.0.Alpha1 Released
ccranfor
:awestruct-tags: [ releases, mysql, postgres, mongodb, sqlserver, cassandra, db2, oracle, vitess ]
:awestruct-layout: blog-post

I am excited to announce the release of Debezium *1.4.0.Alpha1*!

This first pass of the 1.4 release line provides a few useful new features:

* New Vitess connector
* Allow fine-grained selection of snapshotted tables

Overall, the community fixed https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.4.0.Alpha1%20ORDER%20BY%20issuetype%20DESC[41 issues] for this release.
Let's take a closer look at some of the highlights.

== Vitess Connector

https://www.vitess.io[Vitess] is a database solution for deploying, scaling, and managing large clusters of MySQL.
We are very happy that the development team around Ruslan Gibaiev and Kewei Shang of https://bolt.eu/en/[Bolt Technology OÜ] decided to build a CDC solution based on Debezium and to https://www.github.com/debezium/debezium-connector-vitess[open-source it] under the Debezium umbrella.
This connector is released in *incubating* state in Debezium 1.4.

Ruslan and Kewei will follow up with a blog post with more details around this connector very soon;
in the mean time please refer to the connector https://debezium.io/documentation/reference/1.4/connectors/vitess.html[reference documentation] to learn more.

== Fine-grained Selection of Snapshotted Tables

One of the major focus points for Debezium 1.4 is to explore more flexible snapshot options,
e.g. to re-snapshot chosen tables or parallelizing long-running snapshot operations.

A first improvement related to snapshotting is the new connector configuration `snapshot.include.collection.list`,
which allows to snapshot only a subset of all the tables which the connector will capture later on during log reading.
This comes in handy if for instance you're interested in capturing changes to all your tables, but only need an initial snasphot of the data for some of them.

For the Postgres connector, by creating a custom implementation of the `Snapshotter` SPI contract, this also allows for a selective re-snapshot of specific tables.
After restarting the connector, such `Snapshotter` would continue to read the log from the point where it left off previously until "now",
then it would take a snapshot of the given tables, and finally continue to read the log for _all_ captured tables.

For more information on this option, please see the connector-specific https://debezium.io/documentation/reference/connectors/index.html[documentation] for more details.

== Other Features

Besides these key features, there's a few other features coming with the 1.4.0.Alpha1 release:

* Implement snapshot select override behavior for MongoDB https://issues.jboss.org/browse/DBZ-2496[DBZ-2496]
* SqlServer - Skip processing of LSNs not associated with change table entries https://issues.jboss.org/browse/DBZ-2582[DBZ-2582]

== Bugfixes

Also a number of bugs were fixed, e.g.:

* Cant override environment variables https://issues.jboss.org/browse/DBZ-2559[DBZ-2559]
* ConcurrentModificationException during exporting data for a mongodb collection in a sharded cluster https://issues.jboss.org/browse/DBZ-2597[DBZ-2597]
* Mysql connector didn't pass the default db charset to the column definition https://issues.jboss.org/browse/DBZ-2604[DBZ-2604]
* [Doc] "registry.redhat.io/amq7/amq-streams-kafka-25: unknown: Not Found" error occurs https://issues.jboss.org/browse/DBZ-2609[DBZ-2609]
* [Doc] "Error: no context directory and no Containerfile specified" error occurs https://issues.jboss.org/browse/DBZ-2610[DBZ-2610]
* SqlExceptions using dbz with Oracle on RDS online logs and LogMiner https://issues.jboss.org/browse/DBZ-2624[DBZ-2624]
* Mining session stopped - task killed/SQL operation cancelled - Oracle LogMiner https://issues.jboss.org/browse/DBZ-2629[DBZ-2629]
* Unparseable DDL: Using 'trigger' as table alias in view creation https://issues.jboss.org/browse/DBZ-2639[DBZ-2639]
* Antlr DDL parser fails to interpret BLOB([size]) https://issues.jboss.org/browse/DBZ-2641[DBZ-2641]
* MySQL Connector keeps stale offset metadata after snapshot.new.tables is changed https://issues.jboss.org/browse/DBZ-2643[DBZ-2643]
* WAL logs are not flushed in Postgres Connector https://issues.jboss.org/browse/DBZ-2653[DBZ-2653]
* Debezium Server Event Hubs plugin support in v1.3 https://issues.jboss.org/browse/DBZ-2660[DBZ-2660]
* Cassandra Connector doesn't use log4j for logging correctly https://issues.jboss.org/browse/DBZ-2661[DBZ-2661]
* Should Allow NonAsciiCharacter in SQL https://issues.jboss.org/browse/DBZ-2670[DBZ-2670]
* MariaDB nextval function is not supported in grammar https://issues.jboss.org/browse/DBZ-2671[DBZ-2671]
* Sanitize field name do not sanitize sub struct field https://issues.jboss.org/browse/DBZ-2680[DBZ-2680]
* Debezium fails if a non-existing view with the same name as existing table is dropped https://issues.jboss.org/browse/DBZ-2688[DBZ-2688]

A big thank you to all the contributors from the community who worked on this release:
https://github.com/Faizan[Faizan],
https://github.com/morozov[Sergei Morozov],
https://github.com/keweishang[Kewei Shang],
https://github.com/michaelwang[Michael Wang],
https://github.com/creactiviti[Arik Cohen],
https://github.com/jgormley6[James Gormley],
https://github.com/jinguangyang[jinguangyang],
https://github.com/KaushikIyer16[Kaushik Iyer],
https://github.com/johnjmartin[John Martin],
https://github.com/telnicky[Travis Elnicky],
https://github.com/yimingl17[Yiming Liu], and
https://github.com/bingqinzhou[Bingqin Zhou]!

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].
