---
layout: post
title:  Debezium 1.1.0.Beta2 Released
date:   2020-02-13 10:19:59 -0600
tags: [ releases, postgres, mongodb, oracle, sqlserver, db2, outbox, quarkus ]
author: gmorling
---

Release early, release often!
After the 1.1 Beta1 and 1.0.1 Final releases earlier this week, I'm today happy to share the news about the release of Debezium *1.1.0.Beta2*!

The main addition in Beta2 is support for integration tests of your change data capture (CDC) set-up using Testcontainers.
In addition, the Quarkus extension for implementing the outbox pattern as well as
the SMT for extracting the `after` state of change events have been re-worked and offer more configuration flexibility now.

+++<!-- more -->+++

== Testcontainers Support

When setting up CDC pipelines, you should test your configuration thoroughly:
the source database must be correctly configured (e.g. think binlog mode of MySQL),
connectors must use the right credentials, filters and more.

Automation is king, and thus we're very excited about the new support for writing CDC integration tests using https://www.testcontainers.org/[Testcontainers] (https://issues.redhat.com/browse/DBZ-1722[DBZ-1722]).
With just a few lines of code, you can set up all the required services using Linux containers,
deploy a Debezium connector and run assertions against the emitted change data events.

We're planning to publish a blog post dedicated to this topic very soon,
in the mean time refer to to the link:/documentation/reference/1.1/integrations/testcontainers.html[documentation] to learn more.

== More Configuration Options for the Quarkus Outbox Pattern Extension

The https://debezium.io/documentation/reference/1.1/integrations/outbox.html[Quarkus extension] for implementing the link://blog/2019/02/19/reliable-microservices-data-exchange-with-the-outbox-pattern/[outbox pattern] comes in handy if a service needs to update its own database as well as send events to external consumers:
by writing events into an "outbox" table and capturing them from there using Debezium,
unsafe "dual writes" to a database and Apache Kafka are avoided.

To offer more flexibility, the Quarkus extension allows now for fully flexible customization of the outbox table's column types ((https://issues.redhat.com/browse/DBZ-1711[DBZ-1711])).
E.g. you can set the option `quarkus.debezium-outbox.payload.column-definition` to `JSONB NOT NULL`,
in order to use a Postgres `JSONB` column for the outbox table's payload column.

== More Flexible `After` State Extraction

The SMT for https://debezium.io/documentation/reference/1.1/configuration/event-flattening.html[extracting the `after` state of change events] allows for a more flexible propagation of specific event attributes now: using the new `add.fields` and `add.headers` options, any top-level attribute (`op`, `ts_ms`) as well as `source` and `transaction` attributes can be propagated into the outgoing record and/or as header of the Kafka record:

[source]
----
transforms=unwrap,...
transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
transforms.unwrap.add.fields=table,lsn
transforms.unwrap.add.headers=op,source.ts_ms
----

The existing `operation.header` and `add.source.fields` options have been deprecated and will be removed in a future Debezium version.

== Further Changes and Bugfixes

Overall https://debezium.io/releases/1.1/release-notes/#release-1.1.0-beta2[13 issues] have been addressed for the Debezium 1.1 Beta2 release.

Most notably, a known Kafka Connect issue has been mitigated which may cause missed change events when the Postgres or Oracle connectors are stopped (https://issues.redhat.com/browse/DBZ-1766[DBZ-1766]), and the MongoDB SMT for https://debezium.io/documentation/reference/1.1/configuration/mongodb-event-flattening.html[extracting the new document state] handles identifiers with characters un-supported by Apache Avro, e.g. `$ref`, gracefully (https://issues.redhat.com/browse/DBZ-1767[DBZ-1767]).

A big shout-out to all the contributors of this release:
https://github.com/lordofthejars[Alex Soto],
https://github.com/daanroosen-DS[Daan Roosen],
https://github.com/jpsoroulas[John Psoroulas],
https://github.com/matzew[Matthias Wessendorf],
https://github.com/mwinstanley[Melissa Winstanley],
as well as https://github.com/bsideup/[Sergei Egorov] for his advice on the Testcontainers work.
