---
layout: post
title:  Debezium 1.3.0.Beta2 Released
date:   2020-09-16 10:19:59 -0600
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, outbox ]
author: gmorling
---

I'm very happy to announce the release of Debezium *1.3.0.Beta2*!

In this release we've improved support for column filtering for the MySQL and SQL Server connectors,
and there's a brand-new implementation for ingesting change events from Oracle, using the LogMiner package.
As we're on the home stretch towards Debezium 1.3 Final,
there's also a wide range of smaller improvements, bug fixes and documentation clarifications;
overall, not less than https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.3.0.Beta2%20ORDER%20BY%20issuetype%20DESC&startIndex=20[44 issues] have been resolved for this release.

+++<!-- more -->+++

== Column Filtering Improvements

Addressing a long standing feature request (https://issues.redhat.com/browse/DBZ-1068[DBZ-1068]),
the Debezium connector for SQL Server supports now server-side column filtering:
capture instances in the database itself can be configured so to only contain a sub-set of the captured table's columns.
That way, specific columns can be excluded by the CDC process right away,
instead of only removing them in the Debezium connector,
which is much more efficient for large BLOB for instance.

The MySQL connector adds support for the `column.include.list` option already known from the Debezium Postgres connector
(https://issues.redhat.com/browse/DBZ-2508[DBZ-2508]).

Related to the matter of filtering,
following up on the work begun in the https://debezium.io/blog/2020/09/03/debezium-1-3-beta1-released/[1.3 Beta1 release] around replacing the terms "master/slave", "blacklist" and "whitelist" with more inclusive alternatives,
also all the incubating connectors (Oracle, Db2, Cassandra) use the new terms like "database.include.list", "primary/replica", etc. now (https://issues.redhat.com/browse/DBZ-2462[DBZ-2462]).

== LogMiner-based Ingestion Engine for Oracle

The Debezium Oracle connector can now use the LogMiner package to ingest change events.
As this package comes with the Oracle database itself,
it's a very attractive alternative to the existing XStream-based implementation.
Discussions and work towards LogMiner support have been happening in the Debezium community for a long time
(as you already might have guessed from the very low issue number https://issues.redhat.com/browse/DBZ-137[DBZ-137]),
so we're particularly excited about this work being merged eventually and being part of this release.

Note that there's several follow-up tasks to be resolved related to the LogMiner-based ingestion implementation;
while it is not recommended for production usage at this point,
we'd love to get your feedback from testing and evaluating!

A massive thank you to everyone involved with this:
Andrey Ignatenko and his team for the main work,
Andrey Pustovetov for his ideas around transaction buffering,
Chris Cranford for picking up the PR and preparing it to get merged,
Milo vd Zee for his extensive review,
as well as everyone else commenting and providing feedback on the PR and Jira issue.

== Misc. Features and Bug Fixes

In addition to these key features, the community has completed the work on some other features and fixes, too:

* The MySQL connector supports the `LOCK TABLES FOR BACKUP` lock mode when being used with Percona Server for MySQL (https://issues.redhat.com/browse/DBZ-2466[DBZ-2466]),
which reduces contention during snapshots
* The Postgres connector snapshot SPI got more flexible, allowing for custom implementations now that e.g. can re-snapshot selected tables (https://issues.redhat.com/browse/DBZ-2094[DBZ-2094])
* The prefix of additional headers and fields produced by the event flattening SMTs is customizeable now (https://issues.redhat.com/browse/DBZ-2504[DBZ-2504])
* Support for JSON functions in MySQL DDL statements (https://issues.redhat.com/browse/DBZ-2453[DBZ-2453])
* Improved exception logging for the Cassandra connector (https://issues.redhat.com/browse/DBZ-2498[DBZ-2498])

As always, please refer to the link:/releases/1.3/release-notes/#release-1.3.0-beta2[release notes] for the complete list of resolved issues as well as procedures for upgrading from earlier Debezium versions.

Thank you so much to all the community members contributing to this release:
https://github.com/insom[Aaron Brady],
https://github.com/AndreyIg[Andrey Ignatenko],
https://github.com/bingqinzhou[Bingqin Zhou],
https://github.com/eric-weaver[Eric Weaver],
https://github.com/grantcooksey[Grant Cooksey],
https://github.com/grzegorz8[Grzegorz Kołakowski],
https://github.com/GuyIEX[Guy Pascarella],
https://github.com/jgormley6[James Gormley],
https://github.com/jhuiting[Jos Huiting],
https://github.com/misaert[Mickaël Isaert],
and https://github.com/rivernate[Nathan Mills].

== Outlook

With the first cut of LogMiner support being merged and released,
we're now planning to focus on stabilization and bug fixing,
with the Debezium 1.3 Final release to be expected around the end of the month.

In parallel, work is happening on a https://github.com/debezium/debezium-connector-vitess/pull/1[new connector] contributed by the community for the Vitess (which will - depending on progress of review - be released as an incubating connector either in Debezium 1.3 or 1.4),
and we're going to share some exciting efforts around a proof-of-concept for a potential future Debezium UI with you very soon!
