---
layout: post
title:  Debezium 1.4.0.Alpha2 Released
date:   2020-11-17
tags: [ releases, mysql, postgres, mongodb, sqlserver, cassandra, db2, oracle, vitess ]
author: ccranfor
---

I'm excited to announce the release of Debezium *1.4.0.Alpha2*!

This second pass of the 1.4 release line provides a few useful new features:

* New API hook for the PostgreSQL `Snapshotter` interface
* Field renaming using `ExtractNewRecordState` SMT's `add.fields` and `add.headers` configurations

+++<!-- more -->+++

Overall, the community fixed https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.4.0.Alpha2%20ORDER%20BY%20issuetype%20DESC[37 issues] for this release.
Let's take a closer look at some of the highlights.

== PostgreSQL Snapshotter completion hook

The PostgreSQL `Snapshotter` API is a contract that allows for the customization of the snapshot process.
This API was introduced in 0.9.3.Final and has continued to evolve in the releases since.

A new backward compatible completion hook has been added:
```
void snapshotCompleted()
```
This new hook is called by the snapshot process when the snapshot has concluded,
allowing implementations to clean-up any resources it may have allocated prior streaming changes.

== ExtractNewRecordState SMT field renaming support

One of the features of the `ExtractNewRecordState` SMT is that the transformation can retain parts of the original message in the transformed message's header or payload.
This release extends this feature to allow specifying a new name to be used for the field when added to the message header or payload.

For example, to add the source database's event timestamp to the message header using the new renaming feature, the SMT configuration would be:

```
transforms=unwrap
transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
transforms.unwrap.add.headers=source.ts_ms:timestamp
```

The format of the `add.headers` and `add.fields` configuration options have been improved to support a comma-separated list of fields with the syntax `<OLD_FIELD>[:NEW_FIELD]`.
The above emitted message's headers would now contain `pass:[__timestamp]` rather than the default `pass:[__source.ts_ms]` field.

This syntax improvement remains backward compatible.

== Bugfixes

Also a number of bugs were fixed, e.g.:

* Oracle throw "no snapshot found based on specified time" when running flashback query https://issues.jboss.org/browse/DBZ-1446[DBZ-1446]
* Exception when PK definition precedes column definition https://issues.jboss.org/browse/DBZ-2580[DBZ-2580]
* Patroni can't stop PostgreSQL when Debezium is streaming https://issues.jboss.org/browse/DBZ-2617[DBZ-2617]
* ChangeRecord informations don't connect with the TableSchema https://issues.jboss.org/browse/DBZ-2679[DBZ-2679]
* MySQL connector fails on a zero date https://issues.jboss.org/browse/DBZ-2682[DBZ-2682]
* Oracle LogMiner doesn't support partition tables https://issues.jboss.org/browse/DBZ-2683[DBZ-2683]
* DB2 doesn't start reliably in OCP  https://issues.jboss.org/browse/DBZ-2693[DBZ-2693]
* Dropped columns cause NPE in SqlServerConnector https://issues.jboss.org/browse/DBZ-2716[DBZ-2716]
* Timestamp default value in 'yyyy-mm-dd' format fails MySQL connector https://issues.jboss.org/browse/DBZ-2726[DBZ-2726]
* Connection timeout on write should retry https://issues.jboss.org/browse/DBZ-2727[DBZ-2727]
* No viable alternative at input error on "min" column https://issues.jboss.org/browse/DBZ-2738[DBZ-2738]
* SQLServer CI error in SqlServerConnectorIT.whenCaptureInstanceExcludesColumnsAndColumnsRenamedExpectNoErrors:1473 https://issues.jboss.org/browse/DBZ-2747[DBZ-2747]
* debezium-connector-db2: DB2 SQL Error: SQLCODE=-206 on DB2 for z/OS https://issues.jboss.org/browse/DBZ-2755[DBZ-2755]
* no viable alternative at input 'alter table `order` drop CONSTRAINT' https://issues.jboss.org/browse/DBZ-2760[DBZ-2760]
* Tests are failing on macos https://issues.jboss.org/browse/DBZ-2762[DBZ-2762]

A big thank you to all the contributors from the community who worked on this release:
https://github.com/Iskuskov[Alexander Iskuskov],
https://github.com/alisator[Alisa Houskova],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/AndreyIg[Andrey Ignatenko],
https://github.com/creactiviti[Arik Cohen],
https://github.com/bduisenov[Babur Duisenov],
https://github.com/grantcooksey[Grant Cooksey],
https://github.com/rgannu[Ganesh Ramasubramanian],
https://github.com/vanhoale[Hoa Le],
https://github.com/keweishang[Kewei Shang],
https://github.com/mans2singh[Mans Singh],
https://github.com/hussain-k1[Mohamed Pudukulathan],
https://github.com/zrlurb[Peter Urbanetz],
https://github.com/rareddy[Ramesh Reddy],
https://github.com/morozov[Sergei Morozov], and
https://github.com/ramanenka[Vadzim Ramanenka].
