---
layout: post
title:  Debezium 1.3.1.Final Released
date:   2020-11-12
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: ccranfor
---

I'm excited to announce the release of Debezium *1.3.1.Final*!

This release primarily focuses on bugs that were reported after the 1.3 release.
Most importantly, the following bugs were fixed related to the link:/docs/connectors/oracle[Debezium connector for Oracle] LogMiner adapter thanks to the continued feedback by the Debezium community.

* SQLExceptions thrown when using Oracle LogMiner (https://issues.redhat.com/browse/DBZ-2624[DBZ-2624])
* LogMiner mining session stopped due to WorkerTask killed (https://issues.redhat.com/browse/DBZ-2629[DBZ-2629])
+++<!-- more -->+++

In addition, there were other bugs identified and fixed in this release, including:

* [MongoDB] Sanitization of field names not applied to nested struct fields (https://issues.redhat.com/browse/DBZ-2680[DBZ-2680])
* [MySQL] MariaDB nextval function is not supported by grammar (https://issues.redhat.com/browse/DBZ-2671[DBZ-2671])
* [MSSQL] Hide stack-trace when default value cannot be parsed (https://issues.redhat.com/browse/DBZ-2642[DBZ-2642])
* [MySQL] Upgrade JDBC driver to 8.0.19 (https://issues.redhat.com/browse/DBZ-2626[DBZ-2626])
* [MySQL] ANTLR parser fails to interpret `BLOB(size)` types (https://issues.redhat.com/browse/DBZ-2641[DBZ-2641])
* [MySQL] Should allow non-ascii character in SQL (https://issues.redhat.com/browse/DBZ-2670[DBZ-2670])
* [MySQL] Connector fails if non-existing view with same name as table is dropped (https://issues.redhat.com/browse/DBZ-2688[DBZ-2688])
* [MySQL] No viable alternative at input error when column uses aggregate function names (https://issues.redhat.com/browse/DBZ-2738[DBZ-2738])
* [Oracle] No snapshot found based on specified time (https://issues.redhat.com/browse/DBZ-1446[DBZ-1446])
* [PostgreSQL] WAL logs are not properly flushed (https://issues.redhat.com/browse/DBZ-2653[DBZ-2653])
* [Server] Event Hubs plugin support (https://issues.redhat.com/browse/DBZ-2660[DBZ-2660])

Altogether, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.3.1.Final[14 issues] were resolved in this release.
Please refer to the link:/releases/1.3/release-notes/#release-1.3.1-final[release notes] to learn more about all fixed bugs, update procedures etc.

A big thank you to everyone who helped test and identify these bugs.
The team appreciates the invaluable feedback the community continually provides!


== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.redhat.com/projects/DBZ/issues/[log an issue].