---
layout: post
title:  Debezium 1.3.0.Alpha1 Released
date:   2020-08-06 10:19:59 -0600
tags: [ releases, mysql, postgres, mongodb, sqlserver, cassandra, db2 ]
author: ccranfor
---

I'm excited to announce the release of Debezium *1.3.0.Alpha1*!

This initial pass in the 1.3 release line provides a number of useful new features:

* A new Debezium Server sink adapter for Azure Event Hubs
* A new SQL Server connector snapshot mode, `initial_only`
* Additional connection timeout options for the MongoDB Connector

Overall, the community fixed not less than https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.3.0.Alpha1%20ORDER%20BY%20issuetype%20DESC[31 issues] for this release.
Let's take a closer look at some of them in the remainder of this post.

+++<!-- more -->+++

== Azure Event Hubs sink adapter

Debezium's link:/documentation/reference/1.3/operations/debezium-server.html[standalone server] is one of the newest features in the Debezium ecosystem.
The standalone server provides a ready-to-use application that can stream change events from a source database to a variety of messaging infrastructures.

Driven by the community, the Debezium Server now supports Azure Event Hubs (https://issues.redhat.com/browse/DBZ-2282[DBZ-2282]).
This now enables the Debezium Server to stream change events to Amazon Kinesis, Apache Pulsar, Google Cloud Pub/Sub, and Azure Event Hubs.

== Additional MongoDB connection options

The Debezium MongoDB connector has traditionally used the driver default connection options and timeouts.
There are use cases where customization of these defaults are necessary to support latency or performance concerns in your deployment.

There additional configuration options are now available for MongoDB:

`mongodb.connect.timeout.ms` +
_The number of milliseconds the driver waits for a new conneciton before the attempt is aborted. +
Defaults to `10000`._

`mongodb.server.selection.timeout.ms` +
_The number of milliseconds the driver will wait to select a server before it times out, throwing an error. +
Defaults to `30000`._

`mongodb.socket.timeout.ms` +
_The number of milliseconds the driver waits before a send/receive on the socket may timeout. +
A value of `0` disables this behavior.
Defaults to `0`._

== Other Features

Besides these key features, there's a number of other new features coming with the 1.3.0.Alpha1 release:

* New SQL Server snapshot mode `initial_only` (https://issues.redhat.com/browse/DBZ-2379[DBZ-2379])
* Postgres and possibly other DB connections are not properly shutdown when the task encounters thread interrupt (https://issues.redhat.com/browse/DBZ-2133[DBZ-2133])

== Bugfixes

Also a number of bugs were fixed, e.g.:

* Ignore non-existing table reported on Aurora via SHOW TABLES (https://issues.redhat.com/browse/DBZ-1939[DBZ-1939])
* Cassandra connector not getting events (https://issues.redhat.com/browse/DBZ-2086[DBZ-2086])
* PubSub Sink sends empty records (https://issues.redhat.com/browse/DBZ-2277[DBZ-2277])
* Skipping LSN is inefficient and does not forward slot position (https://issues.redhat.com/browse/DBZ-2310[DBZ-2310])
* message size is at least 68x larger for changes with bit varying columns (https://issues.redhat.com/browse/DBZ-2315[DBZ-2315])
* Change events lost when connnector is restarted while processing transaction with PK update (https://issues.redhat.com/browse/DBZ-2329[DBZ-2329])
* Error when processing commitLogs related to list-type columns (https://issues.redhat.com/browse/DBZ-2345[DBZ-2345])
* Fix dependency groupId on Outbox Quarkus Extension documentation (https://issues.redhat.com/browse/DBZ-2367[DBZ-2367])
* Cannot detect Azure Sql Version (https://issues.redhat.com/browse/DBZ-2373[DBZ-2373])
* ParallelSnapshotReader sometimes throws NPE  (https://issues.redhat.com/browse/DBZ-2387[DBZ-2387])

Please refer to the link:/releases/1.3/release-notes/#release-1.3.0-alpha1[release notes] for the complete list of resolved issues as well as procedures for upgrading from earlier Debezium versions.

A big thank you to all the contributors from the community who worked on this release:
https://github.com/abhirockzz[Abhishek Gupta],
https://github.com/coryharperbind[Cory Harper],
https://github.com/creactiviti[Arik Cohen],
https://github.com/mtagle[Moira Tagle],
https://github.com/victorxiang30[Victor Xiang],
https://github.com/grzegorz8[Grzegorz Kołakowski],
https://github.com/bjoernhaeuser[Björn Häuser],
https://github.com/korzenek[Lukasz Korzeniowski], and
https://github.com/jonaslins[Jonas Lins]!
