---
layout: post
title:  Debezium 1.2.0.Final Released
date:   2020-06-24 10:19:59 -0600
tags: [ releases, mysql, postgres, mongodb, sqlserver, cassandra, db2, oracle, debezium-server ]
author: gmorling
---

I'm very happy to announce the release of Debezium *1.2.0.Final*!

Over the last three months, the community has resolved nearly https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20in%20(1.2.0.Alpha1%2C%201.2.0.Beta1%2C%201.2.0.Beta2%2C%201.2.0.CR1%2C%201.2.0.CR2%2C%201.2.0.Final)[200 issues]. Key features of this release include:

* New Kafka Connect single message transforms (SMTs) for content-based event link:/documentation/reference/1.2/configuration/content-based-routing.html[routing] and link:/documentation/reference/1.2/configuration/filtering.html[filtering];
Upgrade to Apache Kafka 2.5
* Schema change topics for the Debezium connectors for link:/documentation/reference/1.2/connectors/sqlserver.html[SQL Server], link:/documentation/reference/1.2/connectors/db2.html[Db2] and link:/documentation/reference/1.2/connectors/oracle.html[Oracle]
* Support for SMTs and message converters in the Debezium link:/documentation/reference/1.2/development/engine.html[embedded engine]
* link:/documentation/reference/1.2/operations/debezium-server.html[Debezium Server], a brand-new runtime which allows to propagate data change events to a range of messaging infrastructures like Amazon Kinesis, Google Cloud Pub/Sub, and Apache Pulsar
* A new column masking mode "consistent hashing", allowing to anonymize column values while still keeping them correlatable
* New metrics for the MongoDB connector
* Improved re-connect capability for the SQL Server connector

+++<!-- more -->+++

== Debezium Server

Should I pick one feature I'm the most excited about, it would be Debezium Server.
It allows even more users to benefit from open-source change data capture with Debezium,
no matter which messaging infrastructure they are on.
Being able to propagate Debezium data change events via managed services such as Kinesis and Pub/Sub was a feature request we've received again and again from the community,
and it's amazing to see that this feature eventually becomes a reality.

Debezium Server will also be a great foundation for exposing Debezium as a native https://knative.dev/docs/eventing/[Knative Eventing] event source, and you can expect to see more exciting developments in this area very soon.
With Debezium Server, there's now link:/documentation/reference/1.2/architecture.html[three ways] for running Debezium:

* Via _Kafka Connect_, using its fantastic eco-system of connectors to set up low-latency data streaming pipelines with Apache Kafka
* With _Debezium Server_, sending data change events to a growing number of messaging platforms like Kinesis 
* Through the _Debezium Engine_, embedded as a library into custom JVM-based applications, e.g. addressing use cases like updating embedded caches

I'm really excited about all the opportunties which this brings to the Debezium community.
Debezium Server is powered by the innovative https://quarkus.io/[Quarkus] framework, which also opens up many interesting technical possibilities.
E.g. we could explore running Debezium connectors as native binaries via https://www.graalvm.org/[GraalVM],
resulting in a largely reduced memory consumption, which could make this a very interesting deployment option for cloud environments.

== A Big Thank You to the Community!

Please refer to the original announcements (link:/blog/2020/04/16/debezium-1-2-alpha1-released/[Alpha1], link:/blog/2020/05/07/debezium-1-2-beta1-released/[Beta1], link:/blog/2020/05/19/debezium-1-2-beta2-released/[Beta2], link:/blog/2020/06/11/debezium-1-2-cr1-released/[CR1]) to learn more about all the new features of Debezium 1.2.
You can find the complete list of addressed issues, upgrade procedures, and notes on any backward compatibility changes in the link:/releases/1.2/release-notes/#release-1.2.0-final[release notes].

An open-source project would be nothing without its community of users in contributors;
thanks a lot to the following people from the community who worked on the Debezium 1.2 release:

_https://github.com/insom[Aaron Brady],
https://github.com/Iskuskov[Alexander Iskuskov],
https://github.com/ahus1[Alexander Schwartz],
https://github.com/andersenleo[Anders Engström],
https://github.com/ant0nk[Anton Kondratev],
https://github.com/ateijelo[Andy Teijelo Pérez],
https://github.com/nbali[Balázs Németh],
https://github.com/bingqinzhou[Bingqin Zhou],
https://github.com/bradengroom[Braden Groom],
https://github.com/brbrown25[Brandon Brown],
https://github.com/cobolbaby[cobolbaby],
https://github.com/dajerome[David Jerome],
https://github.com/dcumberland[Dave Cumberland],
https://github.com/ebrard[Emmanuel Brard],
https://github.com/edbighead[Ed Laur],
https://github.com/mozinator[Fabian Aussems],
https://github.com/fgakk[Fatih Güçlü Akkaya],
https://github.com/gergof[Fándly Gergő],
https://github.com/grantcooksey[Grant Cooksey],
https://github.com/blcksrx[Hossein Torabi],
https://github.com/ivan-klass[Ivan Klass],
https://github.com/renardeinside[Ivan Trusov],
https://github.com/JanHendrikDolling[Jan-Hendrik Dolling],
https://github.com/jfinzel[Jeremy Finzel],
https://github.com/jgao54[Joy Gao],
https://github.com/jantpedraza[Juan Antonio Pedraza],
https://github.com/jhiza[Justin Hiza],
https://github.com/jhuiting[Jos Huiting],
https://github.com/jpsoroulas[John Psoroulas],
https://github.com/keweishang[Kewei Shang],
https://github.com/hoanglinh0710[Linh Nguyen Hoang],
https://github.com/lga-zurich[Luis Garcés-Erice],
https://github.com/metlos[Lukas Krejci],
https://github.com/lyidataminr[lyidataminr],
https://github.com/kaplanmaxe[Max Kaplan],
https://github.com/devzer01[Nayana Hettiarachchi],
https://github.com/zrlurb[Peter Urbanetz],
https://github.com/rk3rn3r[René Kerner],
https://github.com/RobertHana[Robert B. Hanviriyapunt],
https://github.com/TechnocratSid[Siddhant Agnihotry], and
https://github.com/crazy-2020[Xuan Shen]_

This brings the total number of contributors to the main Debezium code repositories to over 200!

== Outlook

Let's close this post with an outlook to the next things to come.
We'll stick to our quarterly release cadence, i.e. you can expect Debezium 1.3 to be out by the end of September,
with preview releases in between every three weeks.

We're currently updating the link:/roadmap[roadmap] for the next release,
and your input and feedback on this will be very welcomed!
The things we've planned so far include more flexible options for snapshotting (re-snapshotting specific tables, filter changes, parallelized snapshotting, etc.),
moving Db2 connector out of incubating state, and an exploration of what it'd take to officially support MariaDB.

Onwards and upwards!
