---
layout: post
title:  Debezium 1.1.0.Alpha1 Released
date:   2020-01-16 10:19:59 -0600
tags: [ releases, mysql, postgres, sqlserver ]
author: gmorling
---

Did you know January 16th is https://en.wikipedia.org/wiki/National_Nothing_Day[National Nothing Day]?
It's the one day in the year without celebrating, observing or honoring anything.

Well, normally, that is.
Because we couldn't stop ourselves from sharing the news of the Debezium *1.1.0.Alpha1* release with you!
It's the first release after Debezium 1.0,
and there are some really useful features coming with it.
Let's take a closer look.

+++<!-- more -->+++

== Quarkus Outbox Pattern Extension

The link:/blog/2019/02/19/reliable-microservices-data-exchange-with-the-outbox-pattern/[outbox pattern] is a great way for letting services update their own database
(e.g. to persist a new purchase order) as well as emitting corresponding events to other services in a reliable and consistent way.
The pattern avoids unsafe dual writes, but also doesn't require distributed transactions.

Debezium already supports this pattern via its link:/documentation/reference/1.1/configuration/outbox-event-router.html[outbox event router],
which can be used to stream events from one outbox table into different topics in Apache Kafka.
As we saw a growing adoption of the pattern and usage of this router,
we wanted to take things to the next level and also provide a component to simplify the creation of outbox events within your application itself.

For that purpose there's now a link:/documentation/reference/1.1/integrations/outbox.html[brand-new extension] for https://quarkus.io/[Quarkus], a "Kubernetes Native Java stack tailored for OpenJDK HotSpot and GraalVM, crafted from the best of breed Java libraries and standards".
Using this extension it becomes as simple as firing plain CDI events to produce outbox events:

[source,java]
----
@ApplicationScoped
public class OrderService {

    @Inject
    Event<ExportedEvent<?, ?>> event;

    @Transactional
    public PurchaseOrder addOrder(PurchaseOrder order) {
        // process and persist the order...

        // create a corresponding outbox event to notify other services
        event.fire(OrderCreatedEvent.of(order));

        return order;
    }
}
----

Once the event has been persisted in the outbox table and the transaction has been committed,
Debezium will capture it and propagate it to downstream consumers via Kafka.

We're planning to publish a detailed post with a complete end-to-end example for implementing the outbox pattern with this Debezium and this Quarkus extension next week, so stay tuned.
To read up on the outbox pattern in the meantime, please refer to the blog post linked above or to any of https://dzone.com/articles/implementing-the-outbox-pattern[these] https://medium.com/engineering-varo/event-driven-architecture-and-the-outbox-pattern-569e6fba7216[great] https://thoughts-on-java.org/outbox-pattern-with-cdc-and-debezium/[posts] from the community.

== CloudEvents Support

https://cloudevents.io/[CloudEvents] is a "specification for describing event data in a common way", aiming at providing "interoperability across services, platforms and systems". 
By means of a new Kafka Connect message converter (`io.debezium.converters.CloudEventsConverter`), Debezium now can link:/documentation/reference/1.1/integrations/cloudevents.html[emit change events] that adhere to the CloudEvents specification:

[source,java]
----
{
  "id" : "name:test_server;lsn:29274832;txId:565",
  "source" : "/debezium/postgresql/test_server",
  "specversion" : "1.0",
  "type" : "io.debezium.postgresql.datachangeevent",
  "time" : "2020-01-13T13:55:39.738Z",
  "datacontenttype" : "application/json",
  "iodebeziumop" : "r",
  "iodebeziumversion" : "1.1.0.Alpha1",
  "iodebeziumconnector" : "postgresql",
  "iodebeziumname" : "test_server",
  "iodebeziumtsms" : "1578923739738",
  "iodebeziumsnapshot" : "true",
  "iodebeziumdb" : "postgres",
  "iodebeziumschema" : "s1",
  "iodebeziumtable" : "a",
  "iodebeziumtxId" : "565",
  "iodebeziumlsn" : "29274832",
  "iodebeziumxmin" : null,
  "data" : {
    "before" : null,
    "after" : {
      "pk" : 1,
      "name" : "Bob"
    }
  }
}
----

With CloudEvents, each event contains a few defined attributes such as `id`, `source` and `type`.
The actual event payload can be found in the `data` attribute, which in the case of Debezium is the structure of old and new state of the affected database record.
Most of the other Debezium change events attributes (`op`, timestamp, source metadata) are mapped to custom attributes using the `iodebezium` prefix.

The `data` attribute as well as the entire event can be encoded using JSON or Avro.
Initially, only the "structured mode" of CloudEvents is supported, i.e. all the attributes are part of the event structure, which is the Kafka record value in this case.
In a future release we'll also add support for the CloudEvents "binary mode",
where only the `data` attribute is part of the event structure, while all other attributes will be mapped the (Kafka) header attributes.

CloudEvents support is under active development, so details around the format likely will change in future versions as this feature matures.
We'd love to get your feedback on this and learn from your insights and experiences with CloudEvents.

== Further Changes

Besides these two larger features, a number of smaller improvements and fixes has been done for Debezium 1.1 Alpha1:

* Column value masking for Postgres, allowing to replace sensitive column values with asterisks (https://issues.redhat.com/browse/DBZ-1685[DBZ-1685])
* Several fixes to the MySQL DDL parser related to trigger definitions (https://issues.redhat.com/browse/DBZ-1699[DBZ-1699]) and the `SIGNAL` keyword (https://issues.redhat.com/browse/DBZ-1691[DBZ-1691])
* Two bugfixes around time and precision thereof (https://issues.redhat.com/browse/DBZ-1688[DBZ-1688], https://issues.redhat.com/browse/DBZ-1707[DBZ-1707])

Altogether, https://debezium.io/releases/1.1/release-notes/#release-1.1.0-alpha1[17 issues] were fixed for this release.

Many thanks to https://github.com/oscerd[Andrea Cosentino], https://github.com/vasilyulianko-visma[Vasily Ulianko], https://github.com/vedit[Vedit Firat Arig], https://github.com/liulangwa[Yongjun Du] and https://github.com/Wang-Yu-Chao[Yuchao Wang] for their contributions to this release!

Going forward, we'll continue with further Debezium 1.1 preview releases every two to three weeks.
Take a look at the link:/roadmap/[roadmap] to see what's coming up, or get in touch to tell us about your specific feature requirements!
