---
layout: post
title:  Debezium UI support for Single Message Transformations
date:   2021-11-23
tags: [ releases, mysql, postgres, mongo, debezium-ui ]
author: mdrilling
---

The Debezium UI team is pleased to announce support for Single Message Transformations (SMTs) in the Debezium UI!

Our goal with the Debezium graphical user interface is to allow users to set up and operate connectors more easily.  To that end, we have added support for Kafka Connect https://kafka.apache.org/documentation/#connect_transforms[single message transformations] to the UI.  Read futher for more information, and for a video demo of the new feature!

+++<!-- more -->+++

== Single Message Transformations (SMTs)

Connectors can be configured with transformations to make lightweight per message modifications.
https://www.morling.dev/blog/single-message-transforms-swiss-army-knife-of-kafka-connect/[Common SMT use cases] include format conversions (e.g. different date formats and number types), message filtering and routing, handling of "tombstone" events, encryption/decryption, etc.

Debezium provides several single message transformations (SMTs) that you can use to either modify records before they are sent to Apache Kafka (by applying them to the Debezium connectors), or when they are read from Kafka by a sink connector.
For instance we provide SMTs for extracting only the "after" part from change events and propagate that one in a flat row format and SMTs for routing the events from an outbox table.

To learn more about the SMTs coming with Debezium, please refer to the link:/documentation/reference/transformations/index.html[reference documentation].
And thanks to the support for SMTs in the Debezium UI, setting them up is easier than ever;
For a short demo of this feature in action, see the following video:

++++
<div class="responsive-video">
<iframe width="1600" height="900" src="https://www.youtube.com/embed/F5o0Zyjlpeg" frameborder="0" allowfullscreen></iframe>
</div>
++++

Fun fact: this video is the very first entry to our brand-new https://www.youtube.com/channel/UCk8VviAaxNZkakaL1hPykIg[Debezium YouTube channel]!
We recommend you subscribe to the channel to never miss any new videos.

== Trying It Out Yourself

We have created a self-contained example https://github.com/debezium/debezium-examples/tree/main/ui-demo[UI demo], which is included under https://github.com/debezium/debezium-examples[debezium-examples] on Github.  The UI demo includes a Docker Compose file which brings up several sources with data as well as the UI. Please refer to the https://github.com/debezium/debezium-examples/tree/main/ui-demo[README file] for more details on running the Debezium UI demo.

To learn more about the Debezium UI, please refer to the link:/documentation/reference/stable/operations/debezium-ui.html[reference documentation].

== Next Steps

We plan to continue with improvements and new features for the UI in the coming releases.  Some items under consideration:

* Incorporation of more Debezium connector types, such as the ones for SQL Server and Oracle
* Addition and improvement of connector metrics and monitoring
* Add capability for viewing and editing connector properties after creation
* ...And more!

We'd also be very happy to learn about your requirements and feedback on the Debezium UI.
Please let us know in the comments below, or send a message to our https://groups.google.com/g/debezium[mailing list].

_A big thank you to the team who have contributed in many ways: Ashique Ansari, Indra Shukla, René Kerner and Gunnar Morling!_
