---
layout: post
title:  Debezium 1.7.0.CR2 Released
date:   2021-09-23
tags: [ releases, mysql, postgres, sqlserver, oracle, outbox ]
author: jpechane
---

We are very happy to announce the release of Debezium *1.7.0.CR2*!

As we are moving ahead towards the final release we include mostly bugfixes.
Yet this release contains important performance improvements and a new feature for read-only MySQL incremental snapshots.

+++<!-- more -->+++

== Kafka based signalling

Recent releases provided a new feature for MySQL - incremental snapshotting from a read-only database.
The snapshot process is based on GTIDs and does not need writing to signalling table.
The problem is that triggering the process still required the existence and write access to the signalling table.

Now it is possible to send the signal via Kafka topic.
This feature is available when the MySQL connector is configured with `read-only = true`.
Please refer to the documentation for more details.

== Performance improvements

https://github.com/krnaveen14[Naveen Kumar] identified multiple performance issues in the Debezium's core critical path.
He benchmarked them and provided pull requests solving them.
If you are interested in details, please check https://issues.redhat.com/browse/DBZ-4015[DBZ-4015] and https://issues.redhat.com/browse/DBZ-3887[DBZ-3887].


== Further Fixes

As we're approaching the 1.7 Final release,
most changes have been centered around bug fixing and maturing the codebase.
Some of the resolved issues include:

* Connection failure after snapshot wasn't executed for a while (https://issues.jboss.org/browse/DBZ-3951[DBZ-3951])
* Incorrect incremental snapshot DDL triggers snapshot that generates unending inserts against signalling table
(https://issues.jboss.org/browse/DBZ-4013[DBZ-4013])
* Several fixes to DML and DDL parsing for Oracle
(https://issues.redhat.com/browse/DBZ-3917[DBZ-3917], https://issues.redhat.com/browse/DBZ-4017[DBZ-4017])

Altogether, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.7.0.CR2[14 issues] have been fixed for this release.
A big thank you to all contributors:
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/roldanbob[Bob Roldan],
https://github.com/Naros[Chris Cranford],
https://github.com/gunnarmorling[Gunnar Morling],
https://github.com/novotnyJiri[Jiri Novotny],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/kgalieva[Katerina Galieva],
https://github.com/krnaveen14[Naveen Kumar KR],
https://github.com/roldanbob[Robert Roldan],
https://github.com/vivekwassan[Vivek Wassan],
and https://github.com/fuxiao224[Xiao Fu].

We are on a good path towards `1.7.0.Final` by the end of the next week.

