---
layout: post
title:  Debezium 1.8.0.Final Released
date:   2021-12-16
tags: [ releases, mongodb, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: gmorling
---

It's my great pleasure to announce the release of Debezium *1.8.0.Final*!

Besides a strong focus on the Debezium connector for MongoDB (more on that below),
the 1.8 release brings support for Postgres' logical decoding messages,
support for configuring SMTs and topic creation settings in the Debezium UI,
and much more.

Overall, the community has fixed https://issues.redhat.com/browse/DBZ-4460?jql=project%20%3D%20DBZ%20AND%20fixVersion%20in%20(1.8.0.Alpha1%2C%201.8.0.Alpha2%2C%201.8.0.Beta1%2C%201.8.0.CR1%2C%201.8.0.Final)[242 issues] for this release.
A big thank you to everyone who helped to make this release happen on time, sticking to our quarterly release cadence!

+++<!-- more -->+++

== Improvements to the Debezium Connector for MongoDB

The team has made a strong push to bring multiple new features and improvements to the https://debezium.io/documentation/reference/stable/connectors/mongodb.html[connector for MongoDB].
It has now a brand-new capturing implementation based on MongoDB https://docs.mongodb.com/manual/changeStreams/[Change Streams], which allows for some very exciting new functionalities.
More specifically, the connector now

* Supports and has been tested with all the latest versions up to 5.0
* Can optionally https://debezium.io/documentation/reference/stable/connectors/mongodb.html#mongodb-property-capture-mode[emit the complete document state] for update events (by means of the Change Streams capability of reading back the entire document affected by change)
* Provides support for https://debezium.io/documentation/reference/stable/connectors/mongodb.html#_incremental_snapshot[incremental snapshots], as already known from the other Debezium connectors (more details on that in a separate blog post)
* Helps you to implement the outbox pattern for microservices data exchange by means of an https://debezium.io/documentation/reference/stable/transformations/mongodb-outbox-event-router.html[event routing SMT], specifically tailored to the event format emitted by this connector

== Further Improvements

Besides the work on the MongoDB connector, many improvements and feature additions have been made to the other connectors.
Amongst other things,

* The names of transaction metadata topics are configurable
* The Debezium UI has been further built out (see link:/blog/2021/11/23/debezium-ui-transforms/[here] and link:/blog/2021/12/02/debezium-ui-topic-groups/[here] for demos of this)
* The Debezium connector for Postgres now https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-message-events[supports logical decoding messages], as emitted using the `pg_logical_emit_message()` function
* There's a new snapshot mode `SCHEMA_ONLY_RECOVERY` for the Debezium connector for Oracle
* The Debezium connector for Oracle supports https://debezium.io/documentation/reference/stable/connectors/oracle.html#oracle-truncate-events[`TRUNCATE` events] and the `binary.handling.mode` option for controlling how BLOB data is exported 
* There's support for https://debezium.io/documentation/reference/stable/connectors/oracle.html#oracle-event-buffering-infinispan[remote Infinispan caches] for buffering large Oracle transactions
* The Debezium connector for MySQL now can export table comments; it also supports heartbeat action queries and schema changes while an incremental snapshot is running; in addition, it received many improvements to its DDL parser and character set handling
* The Debezium connector for Vitess supports transaction metadata events, has an improved `source` struct, and supports re-sharding operations in a more flexible way

Please take a look at the original release announcements
(link:/blog/2021/10/27/debezium-1-8-alpha1-released/[Alpha1],
link:/blog/2021/11/11/debezium-1.8-alpha2-released/[Alpha2],
link:/blog/2021/11/30/debezium-1.8-beta1-released/[Beta1],
and link:/blog/2021/12/09/debezium-1.8-cr1-released/[CR1])
as well as the link:/releases/1.8/release-notes[1.8 release notes] in order to learn more about these and other new features of this release.

Many thanks to all the folks from the Debezium community which contributed code changes to this release:

https://github.com/abhishekkh[Abhishek Hodavdekar],
https://github.com/ahus1[Alexander Schwartz],
https://github.com/dlg99[Andrey Yegorov],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/uidoyen[Ashique Ansari],
https://github.com/bgaraue[Biel Garau Estarellas],
https://github.com/roldanbob[Bob Roldan],
https://github.com/camilesing[Camile Sing],
https://github.com/Naros[Chris Cranford],
https://github.com/cburch824[Christopher Burch],
https://github.com/kometen[Claus Guttesen],
https://github.com/danielpetisme[Daniel PETISME],
https://github.com/famartinrh[Fabian Martinez],
https://github.com/gunnarmorling[Gunnar Morling],
https://github.com/gkorland[Guy Korland],
https://github.com/harveyyue[Harvey Yue],
https://github.com/blcksrx[Hossein Torabi],
https://github.com/uidoyen[Hussain Ansari],
https://github.com/sugarcrm-jgminder[Jacob Gminder],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/Jiabao-Sun[Jiabao Sun],
https://github.com/novotnyJiri[Jiri Novotny],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/josetesan[Jose Luis],
https://github.com/juanfiallo[Juan Fiallo],
https://github.com/judahrand[Judah Rand],
https://github.com/kgalieva[Katerina Galieva],
https://github.com/lairen[Lairen Hightower],
https://github.com/lbroudoux[Laurent Broudoux],
https://github.com/lujiefsi[陆杰],
https://github.com/xenji[Mario Mueller],
https://github.com/mdrillin[Mark Drilling],
https://github.com/mikekamornikov[Mike Kamornikov],
https://github.com/PlugaruT[Plugaru Tudor],
https://github.com/rk3rn3r[René Kerner],
https://github.com/roldanbob[Robert Roldan],
https://github.com/morozov[Sergei Morozov],
https://github.com/shichao-an[Shichao An],
https://github.com/sgc109[Sungho Hwang],
https://github.com/Thiago-Dantas[Thiago Dantas],
https://github.com/TomBillietKlarrio[Tom Billiet],
https://github.com/unalsurmeli[Ünal Sürmeli],
https://github.com/ramanenka[Vadzim Ramanenka],
https://github.com/vivekwassan[Vivek Wassan],
https://github.com/vjuranek[Vojtech Juranek],
https://github.com/zxpzlp[Willie Zhu],
https://github.com/sonne5[Yang Wu], and
https://github.com/ashulin[Zongwen Li]!

== What's Next?

With another release shipped on schedule,
it's time for a break and take a rest over the upcoming holidays.
We'll be back to business in early January,
with the planning for the 1.9 release being the first activity.

Please let us know about any requirements and feature requests you may have.
One area we'd like to focus on for the next release is performance benchmarking and subsequentially applying performance improvements based on that.
It also looks like there will be new community-led Debezium connector for a distributed NoSQL store; stay tuned for the details around this super-exciting development!

Later in the year, you also can expect the release of Debezium 2.0,
where we'll focus on cleaning up some inconsistencies and removing some deprecated features such as wal2json support in the Debezium connector for Postgres.

For now, we wish everybody a happy holiday season,
and, if you're into it, Merry Christmas!
Please note the core team will be on PTO mostly for the coming weeks,
so replies to emails, chat messages, issue reports, and pull requests will be slower than usual.
Upwards and onwards!
