---
layout: post
title:  Debezium 1.8.0.CR1 Released
date:   2021-12-09
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: gmorling
---

I'm very excited to announce the release of Debezium *1.8.0.CR1*!

As were near the final release due out next week, this release focused heavily on bugfixes.
Yet this release includes incremental snapshot support for MongoDB!
Overall, not less than https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.8.0.CR%20ORDER%20BY%20component%20ASC[34 issues] have been fixed for this release.

Let's take a closer look at some of them.

+++<!-- more -->+++

== MongoDB incremental snapshots

Incremental snapshotting is a feature that we first introduced as a part of Debezium 1.6 nearly six ago.
The goals of incremental snapshots is to primarily address to very common user pain-points:

* the necessity to execute consistent snapshots before streaming can begin upon connector restart
* inability to trigger full or partial snapshots after connector has begun streaming

The implementation of this feature is based on a novel approach to snapshotting originally invented by https://arxiv.org/pdf/2010.12597v1.pdf[DBLog Framework].
Debezium implementation is described in more detail in the https://github.com/debezium/debezium-design-documents/blob/main/DDD-3.md[design document].

With this release, we're excited to finally debut this feature for MongoDB.
All Debezium core connectors now support this feature; an amazing milestone!

I'd like to thank our very own https://github.com/jpechane[Jiri Pechanec] and https://github.com/kgalieva[Kate Galieva] from Shopify for their amazing efforts these last few months at refining and delivering on this feature as well as the entire community for testing and offering solid feedback.

== Further fixes

With 1.8 Final release scheduled for next week,
a vast majority of the changes in this release focus on stability and bugfixes.
Some resolved issues include:

* [PostgreSQL] Parallel write can be lost during catch-up phase (https://issues.redhat.com/browse/DBZ-2792[DBZ-2792]).
* [Oracle] None of log files contains offset SCN (SCN offset is no longer available in the online redo logs) (https://issues.redhat.com/browse/DBZ-3635[DBZ-3635])
* [Oracle] Add support for truncate in oracle connector (https://issues.redhat.com/browse/DBZ-4385[DBZ-4385])
* [Oracle] Support binary_handling_mode for Oracle connector (https://issues.redhat.com/browse/DBZ-4400[DBZ-4400])
* [Debezium Server] Event Hubs exporter slow/Event data was too large (https://issues.redhat.com/browse/DBZ-4277[DBZ-4277])
* [Vitess] Enforce consistent vgtid representation in vitess connector (https://issues.redhat.com/browse/DBZ-4409[DBZ-4409])
* [Vitess] VStream gRPC connection closed after being idle for a few minutes (https://issues.redhat.com/browse/DBZ-4389[DBZ-4389])
* Several fixes to DML and DDL parsing for MySQL (https://issues.redhat.com/browse/DBZ-4397[DBZ-4397], https://issues.redhat.com/browse/DBZ-4402[DBZ-4402]) and Oracle (https://issues.redhat.com/browse/DBZ-4388[DBZ-4388], https://issues.redhat.com/browse/DBZ-4396[DBZ-4396])

Please refer to the link:/releases/1.8/release-notes#release-1.8.0-cr1[release notes] to learn more about these and further fixes in this release.

As always, a big thank you to everyone contributing to this release:

<add users>

== Outlook

As the year is coming to close, we're actively preparing some holiday treats!

You can expect 1.7.2.Final to be released early next week including many bugfixes and improvements.
Additionally, we intend to release 1.8.0.Final in the middle of next week barring no unforeseen bug reports with CR1.

After the holiday break, we plan to be back in full swing on Debezium 1.9.
Keep at eye on our https://debezium.io/roadmap[road map] as we'll be updating this to include our focus for next quarter's release cycle.

We're also actively working on the planning and scope of Debezium 2.0 which we intend to release sometime in 2022.
We would love your feedback on any features or changes you'd like to see so join the discussion on this topic on the https://groups.google.com/u/1/g/debezium/c/X17AUmQ88-E[mailing list].
