---
layout: post
title:  Debezium 1.5.0.Beta1 Released
date:   2021-02-24
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: gmorling
---

I'm very happy to announce the release of Debezium *1.5.0.Beta1*!

This release adds a brand-new component -- the web-based Debezium UI --, transaction metadata support for the MySQL connector,
a large number of improvements to the LogMiner-based capture implementation for the Debezium Oracle connector,
support for Vitess 9.0, and much more.
Let's explore some of the new features in the following.

+++<!-- more -->+++

== Debezium UI

The different Debezium connectors provide great power and flexibility for setting up and running change data capture sources for a range of databases.
But this flexibility also comes at a cost: getting started with the connectors can take some time for understanding all the different options and their semantics.
Another critical aspect is operating the connectors, i.e. gaining insight into their current status and metrics,
being able to react to connector failures, and more etc.

Based on this feedback from the community, we link:/blog/2020/10/22/towards-debezium-ui/[have explored] over the last few months how a graphical user interface could help with these matters.
The initial proof-of-concept looked very promising, so we decided to move forward and make the https://github.com/debezium/debezium-ui/[UI] an official component of the Debezium project.
Still under active development, you already can try out the UI today
(available as a https://hub.docker.com/r/debezium/debezium-ui[container image on Docker Hub]) and use it to set up Debezium connectors in your Kafka Connect clusters.

We'll follow up with more details on the Debezium UI in a separate blog post within the next few days,
discussing its current status, the roadmap for this component, and more.

== Improved LogMiner-based CDC Implementation

Continuing our current focus on the LogMiner-based CDC implementation for Oracle,
we've fixed a substantial number of issues for this connector.
Amongst them are:

* Drastically improved DML parsing performance (https://issues.redhat.com/browse/DBZ-3078[DBZ-3078]); a new hand-written parser for the LogMiner DML statements allows for better throughput of this connector, the existing external parser implementation will be removed very soon
* Support for capturing changes from multiple schemas (https://issues.redhat.com/browse/DBZ-3009[DBZ-3009])
* Support for column filtering (https://issues.redhat.com/browse/DBZ-3167[DBZ-3167])
* Correct transaction metadata (https://issues.redhat.com/browse/DBZ-3090[DBZ-3090])
* Several bug fixes related to log file switching and similar (https://issues.redhat.com/browse/DBZ-2754[DBZ-2754], https://issues.redhat.com/browse/DBZ-3001[DBZ-3001], https://issues.redhat.com/browse/DBZ-3153[DBZ-3153], etc.)

== Vitess Connector

Led by community member Kewei Shang, the Debezium connector for Vitess now supports Vitess 9.0
(https://issues.redhat.com/browse/DBZ-3100[DBZ-3100]).
The connector also can capture changes from JSON and ENUM columns
(https://issues.redhat.com/browse/DBZ-3115[DBZ-3115], https://issues.redhat.com/browse/DBZ-3124[DBZ-3124]),
and it implements the configuration validation API of Kafka Connect
(https://issues.redhat.com/browse/DBZ-3117[DBZ-3117]).

== Other Features

Further fixes and improvements in this release including the following:

* The Debezium MySQL connector can expose metadata about transaction boundaries (https://issues.redhat.com/browse/DBZ-3114[DBZ-3114]);
this is one of the first benefits we obtain by rebasing this connector onto the common Debezium connector framework,
as discussed in the link:/blog/2021/02/08/debezium-1-5-alpha1-released/[1.5.0.Alpha1] release announcement 
* The Debezium connector for Postgres is tested and validated against PG 13 (https://issues.redhat.com/browse/DBZ-3022[DBZ-3022^])
* Ability to customize offsets when using the Debezium embedded API (https://issues.redhat.com/browse/DBZ-2897[DBZ-2897])
* Support for `CREATE OR REPLACE INDEX` DDL when using the MySQL connector with MariaDB (https://issues.redhat.com/browse/DBZ-3067[DBZ-3067])
* Infinite timestamp values supported with Postgres (https://issues.redhat.com/browse/DBZ-2614[DBZ-2614])

Altogether, a grand total of https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.5.0.Beta1%20ORDER%20BY%20component%20ASC[78 issues] have been addressed for this release.

As always, a big thanks you to all the community members who contributed:
https://github.com/adhaamehab[Adhaam Ehab],
https://github.com/ahmedjami[Ahmed Eljami],
https://github.com/bingqinzhou[Bingqin Zhou],
https://github.com/fahimfarookme[Fahim Farook],
https://github.com/rgannu[Ganesh Ramasubramanian],
https://github.com/harveyyue[Harvey Yue],
https://github.com/kppullin[Kevin Pullin],
https://github.com/keweishang[Kewei Shang],
https://github.com/michaelcizmar[Michael Cizmar],
https://github.com/nitin456[Nitin Agarwal],
https://github.com/r-ballard[Russell Ballard],
https://github.com/mrshanepaul[Shane Paul],
https://github.com/tprelle[Thomas Prelle],
https://github.com/twthorn[Thomas Thornton], and
https://github.com/Cyril-Engels[Yilong Chang].
