---
layout: post
title:  Debezium 1.5.0.Beta2 Released
date:   2021-03-15
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: ccranfor
---

We are very happy to announce the release of Debezium *1.5.0.Beta2*!

The main feature of this release is the new Debezium Signaling Table support,
while also focusing on continued Oracle LogMiner improvements and overall polish as we sprint to the finish line for the 1.5. release.

Overall, the community fixed https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.5.0.Beta2%20ORDER%20BY%20issuetype%20DESC[54 issues] since the Beta1 release,
some of which we'll explore more in-depth below.

+++<!-- more -->+++

== Signaling Table

The signal table feature is a huge milestone for Debezium.
It provides a command pattern based on a source database table to send commands (aka signals) to Debezium so that specific actions may be taken.
The signal table framework is extendable, meaning that a connector can implement its own custom commands as needed.

In order to use the signal table feature, the connector option `signal.data.collection` must be specified in the connector's configuration.
This option specifies the fully qualified name of the table from which signal requests will be sourced.
If this option is not specified or empty, the signal table feature will be disabled.

The signal table itself must be created ahead of time and it must adhere to the following convention:

|===
|Column Name|Data Type

|ID
|`STRING` +
The unique identifier of the signal such as a UUID.
|TYPE
|`STRING` +
The unique command to be performed.
|DATA
|`STRING` +
The payload for the command.
|===

Lastly, the signal table must be explicitly found as part of your connector's include/exclude-list specifications.
In other words, if you're specifying a list of tables to monitor, this list will need to be adjusted to include the name of the signal table as well.

This new feature has quite a number of use cases that we intend to explore in future releases.
Lets discuss what signals are currently supported in this release.

==== Log Signal

The log signal is detected when the `TYPE` column in the signal table is `log`.
This signal requests that Debezium write the contents of the `DATA` column (payload) to the connector logs as-is.
This can be useful for a variety of purposes from debugging to tracking progress of database script operations and much more.

As an example:

```sql
INSERT INTO DEBEZIUM_SIGNALS (ID, TYPE, DATA) VALUES ('1', 'log', 'Hello World');
```

Once that insert is committed and written to the database's transaction logs,
Debezium will recognize the signal and will then write `Hello World` to the connector logs using the `INFO` log level.

==== Schema Changes Signal

The schema changes signal is detected when the `TYPE` column in the signal table is `schema-changes`.
This signal tells Debezium to emit a `SchemaChangeEvent` to the schema changes topic that is based on the changes supplied in the row's `DATA` column (payload).
The format of the `DATA` column must be given in JSON and an example of the format is below.
Additionally, this signal will also have Debezium update it's in-memory representation of the table's schema structure.

As an example, we have a PostgreSQL table `s1.a` where we want to add a new column `aa`:

```json
{
  "database": "postgres",
  "changes": [{
    "type": "ALTER",
    "id": "s1.a",
    "table": {
      "defaultCharsetName": null,
      "primaryKeyColumnNames": [ "pk" ],
      "columns": [{
        "name": "pk",
        "jdbcType": 4,
        "nativeType": 23,
        "typeName": "serial",
        "typeExpression": "serial",
        "charsetName": null,
        "length": 10,
        "scale", 0,
        "position": 1,
        "optional": false,
        "autoIncremented": true,
        "generated": false
      }, {
        "name": "aa",
        "jdbcType": 4,
        "nativeType": 23,
        "typeName": "int4",
        "typeExpression": "int4",
        "charsetName": null,
        "length": 10,
        "scale", 0,
        "position": 2,
        "optional": true,
        "autoIncremented": false,
        "generated": false
      }]
    }
  }]
}
```

With this JSON payload, the signal would be inserted as:

```sql
INSERT INTO DEBEZIUM_SIGNALS (ID, TYPE, DATA) VALUES ('1', 'schema-changes', <json-payload-string>);
```

== Other Features and Fixes

Besides the Signal Table support, a few other improvements and fixes found their way into this release.
A number of these improvements were with the Oracle LogMiner connector:

* The Debezium connector for Oracle now uses the LogMiner-based capturing implementation by default.
In order to use the XStream-based implementation, the `database.connection.adapter` option must be explicitly set to `xstream` (https://issues.redhat.com/browse/DBZ-3241[DBZ-3241]).

* In an earlier release of Debezium 1.5, the Oracle connector began to emit `NUMBER(1)` data types as `BOOLEAN`.
Rather than this conversion be implicitly done by the connector, this behavior has been moved to an OOTB converter, `NumberOneToBooleanConverter`,
that can be used as needed (https://issues.redhat.com/browse/DBZ-3208[DBZ-3208]).

As always, you can find the complete list of all the addressed issues and upgrade procedures in the link:/release/1.5/release-notes/#release-1.5.0-beta2[release notes].

Many thanks to all the community members contributing to this release:
https://github.com/AndreyIg[Andrey Ignatenko],
https://github.com/ant0nk[Anton Kondratev],
https://github.com/bingqinzhou[Bingqin Zhou],
https://github.com/ddseapy[David Seapy],
https://github.com/denisprog[Victar Malinouski],
https://github.com/fuxiao224[Xiao Fu],
https://github.com/keweishang[Kewei Shang],
https://github.com/lga-zurich[Luis Garcés-Erice],
https://github.com/mpermar[Martín Pérez],
https://github.com/vanhoale[Hoa Le],
https://github.com/vaosinbi[Vladimir Osin],
https://github.com/zrlurb[Peter Urbanetz],
https://github.com/martper2[Martín Pérez], and
https://github.com/mengqiu[Meng Qiu]!
