---
layout: post
title:  Debezium Community Newsletter 01/2021
date:   2021-07-07
tags: [ community, news, newsletter ]
author: anmohant
---

Welcome to the newest edition of the Debezium community newsletter, in which we share all things CDC related including blog posts, group discussions, as well as StackOverflow
questions that are relevant to our user community.

It's been a long time since our last edition. But we are back again!
In case you missed our last edition, you can check it out link:/blog/2020/03/31/debezium-newsletter-01-2020/[here].

+++<!-- more -->+++

== Upcoming Events

Due to the ongoing global pandemic, all the conferences, and meet-ups have gone virtual.
On the bright side, this means you get to attend some nice events from the comfort of your couch:

* https://www.meetup.com/apache-pinot/events/279202435/[Apache Pinot meet-up -- "Analyzing Real-time Order Deliveries using CDC with Debezium and Pinot"] by Kenny Bastani and Gunnar Morling
* https://www.mongodb.com/live/agenda[MongoDB.Live -- "Dissecting our Legacy: The Strangler Fig Pattern with Apache Kafka, Debezium and MongoDB"] by Hans-Peter Grahsl and Gunnar Morling

If you'd like to have a session on Debezium at your virtual meetup or conference, please get in touch!


== Articles

There have been several blog posts about Debezium lately; here are some of the latest ones that you should not miss:

* link:https://shopify.engineering/capturing-every-change-shopify-sharded-monolith[Capturing Every Change From Shopify’s Sharded Monolith] by John Martin and Adam Bellemare

* link:/blog/2020/11/04/streaming-vitess-at-bolt/[Streaming Vitess at Bolt] by Kewei Shang, and Ruslan Gibaiev

* link:https://www.infoq.com/articles/saga-orchestration-outbox/[Saga Orchestration for Microservices Using the Outbox Pattern] by Gunnar Morling

* link:https://developers.redhat.com/articles/2021/06/14/application-modernization-patterns-apache-kafka-debezium-and-kubernetes/[Application modernization patterns with Apache Kafka, Debezium, and Kubernetes] by Bilgin Ibryam

* link:https://inside.getyourguide.com/blog/2021/5/4/enhancing-the-outbox-pattern-with-kafka-streams/[Enhancing the outbox pattern with Kafka Streams] by Hinrik Örn Sigurðsson

* link:https://thenewstack.io/kubernetes-run-analytics-at-the-edge-postgres-kafka-debezium/[Kubernetes-Run Analytics at the Edge: Postgres, Kafka, Debezium] by Jonathan Katz

* link:/blog/2021/03/18/understanding-non-key-joins-with-quarkus-extension-for-kafka-streams/[Understanding Non-Key Joins With the Quarkus Extension for Kafka Streams] by Anisha Mohanty

* link:https://medium.com/vimeo-engineering-blog/debezium-event-flattening-with-sql-in-snowflake-b0e8397cfac2/[Debezium event flattening with SQL in Snowflake] by Obed

* A series of really insightful blog posts about Debezium and change data capture in general by Dunith Dhanushka:
** link:https://medium.com/event-driven-utopia/a-gentle-introduction-to-event-driven-change-data-capture-683297625f9b/[A Gentle Introduction to Event-driven Change Data Capture]
** link:https://medium.com/event-driven-utopia/a-visual-introduction-to-debezium-32563e23c6b8/[A Visual Introduction to Debezium]
** link:https://medium.com/event-driven-utopia/8-practical-use-cases-of-change-data-capture-8f059da4c3b7/[8 Practical Use Cases of Change Data Capture]

* link:https://medium.com/apache-pinot-developer-blog/change-data-analysis-with-debezium-and-apache-pinot-b4093dc178a7/[Change Data Analysis with Debezium and Apache Pinot] by Kenny Bastani

* link:https://noti.st/morsapaes/liQzgs/change-data-capture-with-flink-sql-and-debezium[Change Data Capture with Flink SQL and Debezium] by Marta Paes

* link:https://www.wix.engineering/post/change-data-capture-at-deviantart/[Change Data Capture at DeviantArt] by Ruslan Danilin

And if watching a talk is more your kind of thing, here's the recording of the session link:https://2021.berlinbuzzwords.de/session/change-data-streaming-patterns-distributed-systems/[Change Data Streaming Patterns in Distributed Systems] from this year's Berlin Buzzwords, by Gunnar Morling and Hans-Peter Grahsl:

++++
<div class="responsive-video">
<iframe width="1600" height="900" src="https://www.youtube.com/embed/CLv2EcYnr2g" frameborder="0" allowfullscreen></iframe>
</div>
++++

Please also check out our compiled list of link:/documentation/online-resources/[resources around Debezium] for even more related posts, articles, podcasts and presentations.

== Integrations

A few cool integrations and usages of Debezium appeared over the last few weeks and months.
Here are several ones which we found especially fascinating:

* A Debezium Server https://github.com/memiiso/debezium-server-iceberg[outbound adaptor for Apache Iceberg]
* The https://docs.scylladb.com/using-scylla/integrations/scylla-cdc-source-connector/[ScyllaDB CDC Source Connector], based on Debezium's CDC connector framework
* https://ci.apache.org/projects/flink/flink-docs-release-1.13/docs/connectors/table/formats/debezium/[Bespoke support] for the Debezium change event format in Apache Flink
* https://materialize.com/docs/sql/create-source/avro-kafka/#kafka-topic-requirements[Support] for Debezium change events in Materialize

== Examples

If you are getting started with Debezium, you can get hands-on learning and better understanding of how things work from the examples and demos
in our https://github.com/debezium/debezium-examples[examples repository].
We have introduced several new examples and updated the existing ones.
Out of which we'd like to highlight some new additions:

* https://github.com/debezium/debezium-examples/tree/master/debezium-server-mongo-pubsub/[Integration of Debezium Server with MongoDB and Pub/Sub (GCP)]
* https://github.com/debezium/debezium-examples/tree/master/distributed-caching/[Integration of Debezium with Infinispan]
* https://github.com/debezium/debezium-examples/tree/master/kstreams-fk-join/[Demonstrates non-key joins with the Quarkus Kafka Streams extension]
* https://github.com/debezium/debezium-examples/tree/master/monitoring/[Demonstrates how to monitor a Debezium instance]
* https://github.com/debezium/debezium-examples/tree/master/saga[Demonstrates the implementation of Saga pattern for realizing distributed transactions across multiple microservices]

If you are interested in showcasing a new demo or an example, please send us a GitHub pull request or reach out to us directly through our community channels found link:/community[here].

== Time to Upgrade

Debezium version link:/blog/2021/06/30/debezium-1-6-final-released/[1.6.0.Final] was released last week.
Apart from Debezium Server sinks for Apache Kafka and Pravega,
the 1.6 release brought a brand-new feature for incremental and ad-hoc snapshots,
providing long-awaited capabilities like resuming long-running snapshots after a connector restart,
Re-snapshotting selected tables during streaming,
and snapshotting tables newly added to the list of captured tables after changing the filter configuration.
A big shout-out to Netflix engineers Andreas Andreakis and Ioannis Papapanagiotou for their paper https://arxiv.org/pdf/2010.12597v1.pdf[DBLog: A Watermark Based Change-Data-Capture Framework], upon which incremental snapshotting is based.

Given the long time since the last community newsletter,
it's also worth mentioning some of the new features added in Debezium 1.5,
link:/blog/2021/04/08/debezium-1-5-final-released/[released in April] this year:
the MySQL connector saw a substantial rewrite,
now also supporting transaction marker events,
Debezium's LogMiner-based CDC implementation for Oracle was declared stable,
and we've added support for Redis Streams to Debezium Server.

If you are using an older version, we urge you to check out the latest major release.
For details on all the bug fixes, enhancements, and improvements, check out the link:/releases/1.6/release-notes/[release-notes].

The Debezium team has also begun active development on the next version, 1.7.
The major focus in 1.7 is implementing incremental snapshotting for more connectors (MongoDB, Oracle), reworking the transaction buffer for the Oracle connector,
and expanding the Debezium UI. For details on the further upcoming release check out the link:/docs/roadmap/[Debezium roadmap].

You can keep track of bug fixes, enhancements, and changes that will be coming up in the 1.7 release by visiting our link:/releases/[releases page].

== Questions and Answers

* https://stackoverflow.com/questions/68073799/mongodb-as-sink-connector-not-capturing-data-as-expected-kafka[MongoDB as sink connector not capturing data as expected - kafka?]
* https://stackoverflow.com/questions/67823515/additional-unique-index-referencing-columns-not-exposed-by-cdc-causes-exception[Additional unique index referencing columns not exposed by CDC causes exception]
* https://stackoverflow.com/questions/66384583/unable-to-deserialise-dynamic-json-with-jackson-using-generics[Unable to deserialise dynamic json with Jackson using generics]
* https://stackoverflow.com/questions/66150335/the-connector-does-not-work-after-stopping-the-debezium-connector-with-ctrlc-an[The connector does not work after stopping the Debezium Connector with Ctrl+C and restart the connector again]
* https://stackoverflow.com/questions/66123544/debezium-heartbeat-action-not-firing[Debezium Heartbeat Action not firing]
* https://stackoverflow.com/questions/66816670/flink-interrupted-while-waiting-for-data-to-be-acknowledged-by-pipeline[Flink: Interrupted while waiting for data to be acknowledged by pipeline]
* https://stackoverflow.com/questions/67330280/cdc-with-debezium-in-docker[CDC with debezium in docker]
* https://stackoverflow.com/questions/67368304/is-debezium-sqlserver-connector-task-multi-threading[Is debezium sqlServer connector task multi-threading?]
* https://stackoverflow.com/questions/68148783/how-to-create-subject-for-ksqldb-from-kafka-tapic[How to create subject for ksqldb from kafka topic]
* https://stackoverflow.com/questions/65682694/debezium-kafka-connect-is-there-a-way-to-send-only-payload-and-not-schema[Debezium, Kafka connect: is there a way to send only payload and not schema?]

== Getting Involved

Getting started with a huge, and an existing code base can be intimidating, but we want to make sure that the process of getting started is extremely easy and smooth for you here.
We are now a vibrant community with https://github.com/debezium/debezium/graphs/contributors[270+ contributors] overall, and we welcome all kinds of community contributions, discussions, and enhancements.
As a beginner you can grab some of the issues labeled with `easy-starter` if you want to dive in quickly.
Below is a list of issues that are open to grab:

* Document "schema.include.list"/"schema.exclude.list" for SQL Server connector (https://issues.redhat.com/browse/DBZ-2793[DBZ-2793])
* Limit log output for "Streaming requested from LSN" warnings (https://issues.redhat.com/browse/DBZ-3007[DBZ-3007])
* Create smoke test to make sure Debezium Server container image works (https://issues.redhat.com/browse/DBZ-3226[DBZ-3226])
* Add signal table automatically to include list (https://issues.redhat.com/browse/DBZ-3293[DBZ-3293])
* Implement support for JSON_TABLE in MySQL parser (https://issues.redhat.com/browse/DBZ-3575[DBZ-3575])
* Implement window function in MySQL parser (https://issues.redhat.com/browse/DBZ-3576[DBZ-3576])
* Standardize "snapshot.fetch.size default" values across connectors (https://issues.redhat.com/browse/DBZ-3694[DBZ-3694])

If you are new to open source, please check out our https://github.com/debezium/debezium.github.io/blob/develop/CONTRIBUTING.md[contributing guidelines] to get started!

== Call to Action

Our https://www.debezium.io/community/users[community users] page includes a variety of organizations that are currently using Debezium.
If you are a user of Debezium, and would like to be included, please send us a GitHub pull request or reach out to us directly through our community channels found link:/community[here].

And if you haven't yet done so, please consider https://github.com/debezium/debezium/stargazers[adding a ⭐] for the GitHub repo;
keep them coming, we're almost at 5,000 stars!

Also, we'd like to learn about your requirements for future Debezium versions.
In particular, we'd be very curious about your feedback on the https://github.com/debezium/debezium-examples/tree/master/saga[CDC-based Sagas approach] mentioned above.
Is it something you'd like to see supported in our link:/documentation/reference/integrations/outbox.html[Quarkus extension] for instance?
Please let us know about this, as well as any other feedback you may have, via the Debezium https://groups.google.com/g/debezium[mailing list].

Lastly, we're planning to continue our interview series link:/blog/2020/10/08/debezium-community-stories-with-renato-mefi/[Debezium Community Stories With...];
so if you got exciting stories to tell about your usage of Debezium,
please reach out!

And as always, stay safe, and healthy. Wish you and your loved ones good health and strength.
