---
layout: post
title:  Debezium 1.6.0.Beta1 Released
date:   2021-05-20
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: ccranfor
---

I'm pleased to announce the release of Debezium *1.6.0.Beta1*!

This release introduces incremental snapshot support for SQL Server and Db2, performance improvements for SQL Server,
support for BLOB/CLOB for Oracle, and much more.  Lets take a few moments and explore some of these new features in the following.

+++<!-- more -->+++

== Incremental Snapshotting - SQL Server / Db2

Debezium first introduced incremental snapshotting in 1.6.0.Alpha1.
As discussed in this https://debezium.io/blog/2021/05/06/debezium-1-6-alpha1-released/[blog post], there are several pain points that exist when running Debezium:

* the necessity to execute consistent snapshots before streaming has begun upon connector restarts
* inability to trigger full or even partial snapshots after having the connector running for extended periods of time

With this release, this feature has been extended to both the SQL Server and Db2 connectors.
We intend to continue to roll this feature out to additional connectors in future releases.

If you would like to try the feature yourself then you need to

* provide a https://debezium.io/documentation/reference/1.6/configuration/signalling.html#_overview[signalling table]
* trigger an ad-hoc incremental snapshot by using a SQL command like

```
INSERT INTO myschema.debezium_signal VALUES('ad-hoc-1', 'execute-snapshot', '{"data-collections": ["schema1.table1", "schema1.table2"]}')
```

== SQL Server Performance Improvement

The SQL Server connector option, `source.timestamp.mode`, controls how the timestamp for an emitted event is resolved.
The default `commit` setting is designed to resolve the timestamp based on when the change record was committed in the database.
It was identified that this method used separate JDBC calls to resolve the timestamp for an event, which caused a loss in both performance and throughput.

This release fixes the `commit` mode performance problem by moving where the timestamp is resolved.
This substantially increases the connector's performance and throughput while maintaining existing functionality.

We would like to thank https://github.com/morozov[Sergei Morozov] for identifying and contributing a solution to this problem.

== Oracle Large Object Data Types

In the era of "Big Data", its not all that uncommon to use data types such as `BLOB` and `CLOB` to store large object data.
The Debezium Oracle connector has supported a wide range of data types and we're happy to report that we've now extended that support to cover large both BLOB and CLOB for both the XStream and LogMiner based implementations.

When emitting events that contain `BLOB` or `CLOB` data, the memory footprint of the connector as well as the emitted event's message size will be directly impacted by the size of the large object data.
As a result, the connector's JVM process may require additional memory as well as adjusting some Kafka configurations, such as `message.max.bytes`.

We encourage the community to test drive the support for these new data types and report any and all feedback.

== Other Features

Further fixes and improvements in this release include the following:

* The Debezium connector for Oracle now supports `ALTER TABLE` and `DROP TABLE` automatically (https://issues.redhat.com/browse/DBZ-2916[DBZ-2916])
* The Debezium connector for Oracle is tested and validated using ojdbc.jar version 21.1.0.0 (https://issues.redhat.com/browse/DBZ-3460[DBZ-3460])
* The Debezium connector for MonogDB could lead to lost change events where a long running snapshot was greater than the configured oplog window (https://issues.redhat.com/browse/DBZ-3331[DBZ-3331]);
the connector now validates the oplog position's existance when streaming starts
* The Debezium connector for Cassandra was not responding to schema changes correctly (https://issues.redhat.com/browse/DBZ-3417[DBZ-3417])

Altogether, a total of https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.6.0.Beta1%20ORDER%20BY%20component%20ASC[52 issues] have been addressed for this release.

As always, a big thank you to all the community members who contributed:
https://github.com/Alfusainey[Alfusainey Jallow],
https://github.com/bingqinzhou[Bingqin Zhou],
https://github.com/CaoManhDat[Cao Manh Dat],
https://github.com/johnjmartin[John Martin],
https://github.com/shiawu[John Wu],
https://github.com/truman303[Mike],
https://github.com/ojacquemart[Olivier Jacquemart],
https://github.com/morozov[Sergei Morozov],
https://github.com/siufay325[SiuFay],
https://github.com/smiklosovic[Stefan Miklosovic],
https://github.com/TAregger[Thomas Aregger], and
https://github.com/ramanenka[Vadzim Ramanenka].