---
layout: post
title:  Debezium 1.7.0.CR1 Released
date:   2021-09-16
tags: [ releases, mysql, postgres, sqlserver, oracle, outbox ]
author: gmorling
---

I am very happy to announce the release of Debezium *1.7.0.CR1*!

For this release, we've reworked how column filters are handled during snapshotting,
the Debezium container images have been updated to use Fedora 34 as their base,
there's support for MySQL `INVISIBLE` columns, and much more.

+++<!-- more -->+++

== Column Filtering During Snapshotting

While the different Debezium connectors already had the capability to exclude specific columns of the captured tables from change events,
these filters were only applied when processing the data within the connectors.
For initial snapshots, a more efficient approach has been implemented now:
tailored SQL SELECT statements will be executed for fetching only the actually included columns
(https://issues.redhat.com/browse/DBZ-2525[DBZ-2525]).
This allows for significant performance gains when for instance excluding large `BLOB` columns from change events.

== Updated Container Image Base

The https://hub.docker.com/u/debezium[Debezium container images] for Apache Kafka, Kafka Connect, and Apache ZooKeeper are based on the Fedora 34 minimal container base image
(https://issues.redhat.com/browse/DBZ-3939[DBZ-3939]).
This change became necessary as the previously used base image (derived from CentOS 7)
was not maintained any longer.
While this change will be transparent for most users of Debezium,
some adjustments may be required for those users who derive their own custom images from the Debezium ones,
e.g. when installing further packages using the operating system's package manager.
Please refer to the https://debezium.io/releases/1.7/release-notes#breaking_changes[release notes] for more details.

== Further Fixes

As we're approaching the 1.7 Final release,
most changes have been centered around bug fixing and maturing the code base.
Some of the resolved issues include:

* Support for `INVISIBLE` columns as available since MySQL 8.0.23 (https://issues.jboss.org/browse/DBZ-3623[DBZ-3623]);
we've used that occassion to also update the Debezium example image for MySQL to version 8.0
(https://issues.jboss.org/browse/DBZ-3936[DBZ-3936])
* The SQL Server allows for the usage of custom connection factories
(https://issues.jboss.org/browse/DBZ-4001[DBZ-4001])
* Several fixes to DML and DDL parsing for MySQL
(https://issues.redhat.com/browse/DBZ-3969[DBZ-3969], https://issues.redhat.com/browse/DBZ-3984[DBZ-3984])
and Oracle
(https://issues.redhat.com/browse/DBZ-3892[DBZ-3892], https://issues.redhat.com/browse/DBZ-3962[DBZ-3962])

Altogether, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.7.0.CR1[47 issues] have been fixed for this release.
A big thank you to all contributors:
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/ashmeet13[Ashmeet Lamba],
https://github.com/roldanbob[Bob Roldan],
https://github.com/camilesing[Camile Sing],
https://github.com/Naros[Chris Cranford],
https://github.com/d3vel0per[Dhrubajyoti G],
https://github.com/gunnarmorling[Gunnar Morling],
https://github.com/harveyyue[Harvey Yue],
https://github.com/uidoyen[Hussain Ansari],
https://github.com/indraraj[Indra Shukla],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/Jiabao-Sun[Jiabao Sun],
https://github.com/novotnyJiri[Jiri Novotny],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/kgalieva[Katerina Galieva],
https://github.com/rk3rn3r[René Kerner], and
https://github.com/zhangyuan[Yuan Zhang].

Going forward, we're planning to do another CR (candidate release) in a few days,
followed by Debezium 1.7.0.Final at the end of the month.
We'll primarily focus on bug fixing and some asorted performance optimizations.
There'll also be some exciting improvements to the link:/documentation/reference/1.7/operations/debezium-ui.html[Debezium UI],
which should be wrapped up for the 1.7 Final release:
support for the configuration of single message transforms (SMTs),
as well as the ability to configure topic creation settings.

In parallel, we're working on the roadmap for Debezium 1.8, planned to be released by the end of the year.
Please reach out in the comments below or on the https://groups.google.com/g/debezium[mailing list] if you'd like to raise specific feature requests for this release.
