---
layout: post
title:  Debezium 1.8.0.Alpha2 Released
date:   2021-11-11
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: ccranfor
---

It's my pleasure to announce the second release of the Debezium 1.8 series, *1.8.0.Alpha2*!

With the holiday season just around the corner, the team's release schedule remains steadfast.
While Debezium 1.8.0.Alpha2 delivers quite a lot of bugfixes and minor changes, there are a few notable changes:

* MySQL support for heartbeat action queries
* Configurable transaction topic name

In addition, the latest `1.2` tag of the https://hub.docker.com/repository/docker/debezium/tooling[debezium/tooling] image is available.
The newest version includes all the latest tools, including https://github.com/kcctl/kcctl[kcctl], a super simple, cuddly CLI for Apache Kafka Connect.

+++<!-- more -->+++

[NOTE]
====
This release does include several breaking changes.
Please see the https://debezium.io/releases/1.8/release-notes#release-1.8.0-alpha2[release notes] for details on what changed and how to upgrade.
====

== MySQL heartbeat action query support

A heartbeat action query can be enabled by supplying a `heartbeat.action.query` configuration option in the connector's configuration.
This property is meant to supply a SQL statement that the connector will execute periodically.

The initial implementation of the heartbeat action query was specifically for PostgreSQL to handle dealing with WAL growth under specific conditions.
But a heartbeat action query has many uses and is entirely connector or even user driven.

For example, you may want to notify downstream consumers that your MySQL topology has changed by supplying consumers with an event with the GTID.
The following configuration shows how to capture changes from the heartbeat action query table that can then be consumed easily by your CDC pipeline.

[source,yaml]
----
"table.include.list": "gtid_history",
"heartbeat.action.query": "INSERT INTO gtid_history( select * from mysql.gtid_executed )"
----

== Configurable transaction topic names

The Debezium transaction metadata topic had previously used a relatively non-configurable naming convention of `<database.server.name>.transaction`.
While it was possible to manipulate the topic name using a single message transform (SMT) as a workaround, we felt that allowing this to be a bit more flexible in Debezium proper made sense.

A new configuration option, `transaction.topic.prefix`, has been introduced that allows the connector configuration to adjust the naming of the transaction metadata topic.
The configuration option value specifies what will be used as a direct replacement for the `<database.server.name>~ portion of the topic name.
If this configuration option is not supplied, the prior topic naming behavior will continue to be used; requiring no changes for existing connector deployments.

== Other Fixes

There were quite a number of bugfixes and stability changes in this release, some noteworthy are:

* Invalid default value error on captured table DDL with default value https://issues.redhat.com/browse/DBZ-3710[DBZ-3710]
* Incremental snapshot doesn't work without primary key https://issues.redhat.com/browse/DBZ-4107[DBZ-4107]
* Signal based incremental snapshot is failing if database name contains dash https://issues.redhat.com/browse/DBZ-4244[DBZ-4244]

Altogether, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.8.0.Alpha2%20ORDER%20BY%20component%20ASC[45 issues] were fixed for this release.
A big thank you to all the contributors from the community who worked on this release:
https://github.com/abhishekkh[Abhishek Hodavdekar],
https://github.com/ahus1[Alexander Schwartz],
https://github.com/dlg99[Andrey Yegorov],
https://github.com/harveyyue[Harvey Yue],
https://github.com/uidoyen[Hussain Ansari],
https://github.com/Jiabao-Sun[Jiabao Sun],
https://github.com/novotnyJiri[Jiri Novotny],
https://github.com/josetesan[Jose Luis],
https://github.com/juanfiallo[Juan Fiallo],
https://github.com/kgalieva[Katerina Galieva],
https://github.com/mikekamornikov[Mike Kamornikov], and
https://github.com/morozov[Sergei Morozov]!


== Debezium 1.7

In addition to this release, we also released Debezium 1.7.1.Final, a bugfix update for the 1.7 series.
The 1.7.1.Final release includes many of the bugfixes in the 1.8 series that have been done since 1.7.0.Final.
For more information on what changed in 1.7.1.Final, please see the https://debezium.io/releases/1.7/release-notes#release-1.7.1-final[release notes].

== Outlook

The holiday season is upon us, but we intend to stick to our release cadence as closely as possible.
If you haven't already taken an opportunity, we'd love your feedback on the https://groups.google.com/u/1/g/debezium/c/X17AUmQ88-E[open discussion] regarding Debezium 2.0 on the mailing list.
In the meantime, you can expect the first beta release of 1.8 in a couple of weeks.
