---
layout: post
title:  Configuring topic automatic creation with the Debezium UI
date:   2021-12-01
tags: [ releases, mysql, postgres, mongo, debezium-ui ]
author: mdrilling
---
The Debezium UI team continues to add support for more features, allowing users to more easily configure connectors.  In this article, we'll describe and demonstrate the UI support for topic automatic creation.  Read further for more information, including a video demo!

+++<!-- more -->+++

== Topic auto-creation

When you start a Debezium connector, the topics for the captured events are created by the Kafka broker based on a default, possibly customized, broker configuration (if `auto.create.topics.enable = true`). But often when you use Debezium and Kafka in a production environment, you might choose to disable Kafka’s topic auto creation capability (`auto.create.topics.enable = false`), or you want the connector topics to be configured differently from the default. In this case you'll need to create topics for Debezium’s captured data sources upfront.

Beginning with Kafka 2.6.0, Kafka Connect comes with topic creation enabled (`topic.creation.enable = true`). If topic creation is enabled, the Debezium UI now allows you to configure connector topics using the UI.

== Kafka Connect topic creation

Kafka Connect topic creation works with groups.  There is a `default` group, which is used when there is no other group defined that matches the topic.  

You can also define multiple custom topic groups, each with it's own configuration.  Each group can specify its configuration parameters to customize how the matched topics of the group will be created. The custom groups will fall back to the default group settings for the required `replication.factor` and `partitions` properties.  If the configuration for a custom topic group leaves other properties undefined, the values specified in the default group are not applied. 

To find more detail about topic auto-creation with Debezium, please refer to this link:/documentation/reference/configuration/topic-auto-create-config.html[reference documentation].  You can also refer to this https://debezium.io/blog/2020/09/15/debezium-auto-create-topics/[Blog post] for a full example.

Watch the following video for a quick demo of topic creation in the Debezium UI:

++++
<div class="responsive-video">
<iframe width="1600" height="900" src="https://youtu.be/C7K1V833eDk" frameborder="0" allowfullscreen></iframe>
</div>
++++

== Self-contained example

You can try out topic auto-creation (and more) with our self-contained example https://github.com/debezium/debezium-examples/tree/main/ui-demo[UI demo] - which is included under https://github.com/debezium/debezium-examples[debezium-examples] on Github.  The UI demo includes a Docker Compose file which brings up several sources with data as well as the UI. Please refer to the https://github.com/debezium/debezium-examples/tree/main/ui-demo[README file] for more details on running the Debezium UI demo.

To learn more about the Debezium UI, please refer to the link:/documentation/reference/operations/debezium-ui.html[reference documentation].

== More coming soon!

Stay tuned for further improvements and new features in the UI in the coming releases.  Support for SQL Server and Oracle connectors are coming soon!

_A big thank you to the team who have contributed in many ways: Ashique Ansari, Indra Shukla, René Kerner and Gunnar Morling!_
