---
layout: post
title:  Debezium 1.7.0.Alpha1 Released
date:   2021-08-02
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: jpechane
---

It's my pleasure to announce the first release of the Debezium 1.7 series, *1.7.0.Alpha1*!

With the summer in a full-swing, this release brings additional improvements to the Debezium Oracle connector but also to the others as well.

+++<!-- more -->+++

== Alternative Oracle Connector LogMiner processors

The Oracle connector can be memory-heavy in case of really large traffic with parallel large transactions in progress.
All these changes in progress need to be kept in memory which might be impossible so in previous versions it was necessary to remove the really old transaction out of the picture.

The current release brings significant refactoring of the connector code that enables the processor to be pluggable.
There is the old memory-based available out-of-the-box but for the first time, we release a new processor based on https://infinispan.org/[Infinispan distributed data store].
With this processor in place, it is possible to track an almost unlimited number of in-progress transactions for unlimited time.

The first release has few limitations

* the Inifinspan configuration is not exposed outside to the user for tuning
* there is only one cache store provided - file-based which means that the connector needs either to run on a single machine or in case of a cluster the cache store must be located on a networked filesystem

This should not stop you from giving it a test drive and send as much feedback as possible to us for further improvements.
We expect to remove the above restrictions in the next release.

== Incremental Snapshotting

The major feature of the 1.6 release has got also new improvements.
Oracle connector now supports incremental snapshots in the same way as the other connectors so Oracle users now can easily add new tables to the capture list and get them snapshotted on the fly.

For MySQL connector, there is a new incremental snapshot mode that could be used for databases that do not allow writing to the signal table.
https://github.com/kgalieva[Kate Galieva] invented a method based on GTID lists that could be used to provide watermarking without writing to the database. Thank you for the nice contribution!


Altogether, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.7.0.Alpha1%20ORDER%20BY%20component%20ASC[49 issues] were fixed for this release.
A big thank you goes out to all the community members who contributed:
Blake Peno,
https://github.com/Alfusainey[Alfusainey Jallow],
https://github.com/bingqinzhou[Bingqin Zhou],
https://github.com/blcksrx[Hossein Torabi],
https://github.com/kgalieva[Katerina Galieva],
https://github.com/kyleyj[Kyley Jex],
https://github.com/mpermar[Martín Pérez],
https://github.com/krnaveen14[Naveen Kumar KR],
https://github.com/patrichu-cisco[Patrick Chu],
https://github.com/xaka[Pavel Strashkin],
https://github.com/raphaelauv[Raphael Auv],
https://github.com/morozov[Sergei Morozov],
https://github.com/Thiago-Dantas[Thiago Dantas],
https://github.com/tinntsea[Tin Nguyen],
https://github.com/tommyk-gears[Tommy Karlsson],
https://github.com/elgca[WenChao Ke],
and https://github.com/jjiey[yangsanity].

For the upcoming 1.7 preview releases, we're planning to focus on completing the follow-up task for the Oracle LogMiner processor and provide the support for JDBC based process too.
We will explore incremental snapshotting support for MongoDB and do research on MariaDB support.
