---
layout: post
title:  Debezium 1.6.0.Final Released
date:   2021-06-30
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: ccranfor
---

I'm pleased to announce the release of Debezium *1.6.0.Final*!

This release is packed full with tons of new features, including support for incremental snapshotting that can be toggled using the new the link:/documentation/reference/1.6/configuration/signalling.html[Signal API].
Based on the excellent paper https://arxiv.org/pdf/2010.12597v1.pdf[DBLog: A Watermark Based Change-Data-Capture Framework] by Netflix engineers Andreas Andreakis and Ioannis Papapanagiotou,
the notion of incremental snapshotting addresses several requirements around snapshotting that came up repeatedly in the Debezium community:

+++<!-- more -->+++

* Ability to resume an on-going snapshot after a connector restart
* Re-snapshot selected tables during streaming, e.g. to re-bootstrap Kafka topics with change events for specific tables
* Snapshot tables newly added to the list of captured tables after changing the filter configuration
* Begin to stream changes while an initial snapshot is running

Incremental snapshotting is an incubating feature as of Debezium 1.6,
and we're looking forward to your feedback on this feature.
To learn more about this functionality, please refer to the individual connector docs, e.g. for the Debezium link:/documentation/reference/1./connectors/mysql#_incremental_snapshot[MySQL connector].
There are already some follow-up improvements in this area in the workings,
for instance the https://github.com/debezium/debezium/pull/2430[usage of MySQL GTIDs] for setting the high/low watermarks required for this snapshotting approach,
which will avoid the need for write access to the database by the connector.
You can expect these improvements to be rolled out in one of the upcoming 1.7 preview releases.

Besides incremental snapshotting, other new features in Debezium 1.6 include two brand new link:/documentation/reference/1.6/operations/debezium-server.html[Debezium Server] sinks,
one for Apache Kafka and another for https://pravega.io/[Pravega],
as well as several notable enhancements to the link:/documentation/reference/1.6/connectors/oracle.html[Debezium connector for Oracle] which include reacting to DDL schema changes and an opt-in, incubating feature to emit `BLOB` and `CLOB` column data types.
There's also improvements to the community-led connectors for link:/documentation/reference/1.6/connectors/vitess.html[Vitess] and link:/documentation/reference/1.6/connectors/cassandra.html[Apache Cassandra],
as well as wide range of bug fixes and other smaller improvements.
We've also upgraded the link:/documentation/reference/1.6/integrations/outbox.html[Debezium Quarkus extension] for implementing the outbox pattern to Quarkus 2.0.

Across all the 1.6 preview and the final releases, a grand total of https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20in%20(1.6.0.Alpha1%2C%201.6.0.Beta1%2C%201.6.0.Beta2%2C%201.6.0.CR1%2C%201.6.0.Final)[188 issues] has been addressed.

For more details, please see the earlier announcements for the link:/blog/2021/05/06/debezium-1-6-alpha1-released/[1.6.0 Alpha1],
link:/blog/2021/05/20/debezium-1-6-beta1-released/[Beta1],
link:/blog/2021/06/10/debezium-1-6-beta2-released/[Beta2],
and link:/blog/2021/06/24/debezium-1-6-cr1-released/[CR1] releases.

Since the CR1 release, we've primarily focused on documentation improvements and some bug fixes.
But there was one last-minute feature addition, too, which allows you to specify archive log locations (https://issues.redhat.com/browse/DBZ-3661[DBZ-3661]) for the Oracle connector.

Please refer to the link:/releases/1.6/release-notes#release-1.6.0-final[release notes] of Debezium 1.6.0.Final for the complete list of resolved issues as well as procedures for upgrading from earlier versions.

As always, a big thank you to all the members from the community who helped with this release,
be it via code contributions, bug report, testing, providing insight and expertise, etc.
Kudos to the following individuals from the community which contributed to Debezium 1.6, bringing the https://github.com/debezium/debezium/graphs/contributors[overall number] of contributors to the Debezium core repository to 277:

https://github.com/ani-sha[Anisha Mohanty],
https://github.com/bingqinzhou[Bingqin Zhou],
https://github.com/roldanbob[Bob Roldan],
https://github.com/camilesing[Camile Sing],
https://github.com/CaoManhDat[Cao Manh Dat],
https://github.com/ccollingwood[Chris Collingwood],
https://github.com/derekm[Derek Moore],
https://github.com/eslep[Eric Slep],
https://github.com/gvaquez-ubi[Gilles Vaquez],
https://github.com/blcksrx[Hossein Torabi],
https://github.com/piee9818[Hyunjin Oh],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/JapuDCret[JapuDCret],
https://github.com/novotnyJiri[Jiri Novotny],
https://github.com/kppullin[Kevin Pullin],
https://github.com/truman303[Mike],
https://github.com/ojacquemart[Olivier Jacquemart],
https://github.com/patrichu-cisco[Patrick Chu],
https://github.com/roldanbob[Robert Roldan],
https://github.com/sarafonseca-123[Sara Fonseca],
https://github.com/morozov[Sergei Morozov],
https://github.com/siufay325[SiuFay],
https://github.com/smiklosovic[Stefan Miklosovic],
https://github.com/zifeo[Teo Stocco],
https://github.com/TAregger[Thomas Aregger], and
https://github.com/ramanenka[Vadzim Ramanenka]!

== Outlook

As always, Debezium will be following its normal quarterly release cadence with Debezium 1.7 planned by the end of September.
There are a couple of key issues we intend to work on over the course of this version including support for incremental snapshots with the MongoDB and Oracle connectors.
Additionally, we plan to explore some new buffering options for the Oracle connector's LogMiner-based implementation,
work on a tool for compacting large schema history topics,
expand the feature set of https://github.com/debezium/debezium-ui/[Debezium UI], and much more.

In the coming week(s), keep an eye out on our https://debezium.io/roadmap/[roadmap] as we'll be refining this in preparations for Debezium 1.7.
If you have any specific feature requests or other input for the roadmap and future releases, please let us know via the https://groups.google.com/g/debezium[mailing list]!
