---
layout: post
title:  Debezium 1.5.0.Final Released
date:   2021-04-08
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: gmorling
---

I'm thrilled to announce the release of Debezium *1.5.0.Final*!

With Debezium 1.5, the LogMiner-based link:/documentation/reference/1.5/connectors/oracle.html[CDC implementation for Oracle] moves from Incubating to Stable state,
and there's a brand-new implementation of the MySQL connector,
which brings features like link:/documentation/reference/1.5/connectors/mysql.html#mysql-transaction-metadata[transaction metadata support].
Other key features include support for a new "signalling table", which for instance can be used to implement link:/documentation/reference/1.5/connectors/oracle.html#surrogate-schema-evolution[schema changes] with the Oracle connector,
and support for `TRUNCATE` events with Postgres.
There's also many improvements to the community-led connectors for link:/documentation/reference/1.5/connectors/vitess.html[Vitess] and link:/documentation/reference/1.5/connectors/cassandra.html[Apache Cassandra],
as well as wide range of bug fixes and other smaller improvements.

+++<!-- more -->+++

Across all the 1.5 preview and the final releases, a grand total of https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20in%20(1.5.0.Alpha1%2C%201.5.0.Beta1%2C%201.5.0.Beta2%2C%201.5.0.CR1%2C%201.5.0.Final)[236 issues] has been addressed.

For more details, please see the earlier announcements for the link:/blog/2021/02/08/debezium-1-5-alpha1-released/[1.5.0 Alpha1],
link:/blog/2021/02/24/debezium-1-5-beta1-released/[Beta1],
link:/blog/2021/03/15/debezium-1-5-beta2-released/[Beta2],
and link:/blog/2021/03/24/debezium-1-5-cr1-released/[CR1] releases.

Since the CR1 release, we've primarily focused on documentation improvements and some bug fixes.
But there are two last-minute feature additions, too:

* link:/documentation/reference/1.5/operations/debezium-server.html#_redis_stream[Support for Redis Streams] in Debezium Server (https://issues.redhat.com/browse/DBZ-2879[DBZ-2879]),
allowing to propagate Debezium data change events into https://redis.io/topics/streams-intro[Redis-based logs]
* Provide LSN coordinates as standardized sequence field in Postgres change events (https://issues.redhat.com/browse/DBZ-2911[DBZ-2911]),
allowing consumers to identify duplicated events and exclude them from processing, for instance after an un-clean connector shut-down; this field will be added to the `source` block of other connectors going forward, too

Please refer to the link:/releases/1.5/release-notes#release-1.5.0-final[release notes] of Debezium 1.5.0.Final for the complete list of resolved issues as well as procedures for upgrading to earlier versions.

As always, a big thank you to all the members from the community who helped with this release,
be it via code contributions, bug report, testing, providing insight and expertise, etc.
In particular for the LogMiner-based CDC implementation for Oracle, we've received a huge number of contributions of all kinds.
We're deeply grateful for that and look forward a lot to further grow and improve this connector implementation!
Kudos to the following individuals from the community which contributed to Debezium 1.5, bringing the https://github.com/debezium/debezium/graphs/contributors[overall number] of contributors to the Debezium core repository to 253:

https://github.com/adhaamehab[Adhaam Ehab],
https://github.com/ahmedjami[Ahmed Eljami],
https://github.com/bingqinzhou[Bingqin Zhou],
https://github.com/davecramer[Dave Cramer],
https://github.com/ddseapy[David Seapy],
https://github.com/fahimfarookme[Fahim Farook],
https://github.com/frankkoornstra[Frank Koornstra],
https://github.com/rgannu[Ganesh Ramasubramanian],
https://github.com/harveyyue[Harvey Yue],
https://github.com/vanhoale[Hoa Le],
https://github.com/JeremyVigny[Jeremy Vigny].
https://github.com/keweishang[Kewei Shang],
https://github.com/kppullin[Kevin Pullin],
https://github.com/mpermar[Martín Pérez],
https://github.com/msillence[Martin Sillence],
https://github.com/mengqiu[Meng Qiu],
https://github.com/michaelcizmar[Michael Cizmar],
https://github.com/krnaveen14[Naveen Kumar],
https://github.com/pkpfr[Nick Murray],
https://github.com/nitin456[Nitin Agarwal],
https://github.com/r-ballard[Russell Ballard],
https://github.com/mrshanepaul[Shane Paul],
https://github.com/tprelle[Thomas Prelle],
https://github.com/twthorn[Thomas Thornton],
https://github.com/denisprog[Victar Malinouski],
https://github.com/vaosinbi[Vladimir Osin],
https://github.com/Cyril-Engels[Yilong Chang], and
https://github.com/fuxiao224[Xiao Fu]!

== Outlook

Following our quarterly release cadence, Debezium 1.6 is planned for the end of June.
A key issue we're planning to work on for this version is explorations of how to improve the notion of initial snapshots,
where we plan to touch on topics like resumeability, parallelization, changes of filter configuration, and more.
This is going to be an open-ended investigation, but we hope to have at least a proof-of-concept implementation for some of these features,
which constantly show up high on the wish list of Debezium users.

Another focus area will again be the Debezium connector for Oracle, where we have planned several functional and performance improvements.
We are also discussing to move to Java 11 as a minimum baseline for running Debezium.
This is primarily caused by external dependencies which are moving on from Java 8.
In case you have specific questions or potential concerns around this change, please chime into https://groups.google.com/g/debezium/c/ZVOYm_S3Jk4[the discussion].
Also, if you got specific feature requests or other input for the roadmap and future releases, please let us know via the https://groups.google.com/g/debezium[mailing list]!
