---
layout: post
title:  Debezium 1.6.0.Beta2 Released
date:   2021-06-10
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, outbox ]
author: gmorling
---

It's my pleasure to announce the release of Debezium *1.6.0.Beta2*!

This release adds support for Pravega to Debezium Server, expands the snapshotting options of the Debezium Oracle connector,
and provides a range of bug fixes and other improvements across different Debezium connectors.

+++<!-- more -->+++

== Pravega Support for Debezium Server

With link:/documentation/reference/operations/debezium-server.html[Debezium Server],
we're on a mission to bring open-source change data capture to all the users,
no matter which data streaming platform or commit log they are using.
So we are very happy to receive a contribution which adds support for https://pravega.io/[Pravega] to Debezium Server.
A Cloud Native Computing Foundation (CNCF) sandbox and Apache 2.0 licensed open-source project,
Pravega describes itself as a "storage abstraction for continuously generated and unbounded data".

The Debezium Server Pravega sink adapter offers two modes: non-transactional and transactional. 
The non-transactional mode individually writes each event in a Debezium batch to Pravega.
The transactional mode writes the Debezium batch to a Pravega transaction that commits when the batch is completed. 

To learn more about using Debezium with Pravega, please refer to the link:/documentation/reference/operations/debezium-server.html#_pravega[documentation].
Many thanks to https://twitter.com/derekm00r3[Derek Moore] for this fantastic contribution!

== Oracle Snapshotting Improvements

The Debezium connector for Oracle received two improvements related to snapshotting:

* Support for the `snapshot.include.collection.list` option (https://issues.redhat.com/browse/DBZ-3062[DBZ-3062]); this allows to create an initial snapshot only for a subset of all those tables captured by the connector
* New option `snapshot.locking.mode` which provides control over the locking behavior when the connector captures the schema of the tables (https://issues.redhat.com/browse/DBZ-3557[DBZ-3557]); in particular, this allows to disable locking completely, which is very useful if you can guarantee that no DDL changes are happening while the connector is taking the (schema) snapshot

In addition, there's several bug fixes for this connector, including a few ones related to DDL and DML parsing
(https://issues.redhat.com/browse/DBZ-3545[DBZ-3545], https://issues.redhat.com/browse/DBZ-3549[DBZ-3549], https://issues.redhat.com/browse/DBZ-3554[DBZ-3554], https://issues.redhat.com/browse/DBZ-3606[DBZ-3606]), handling of RAC installations (https://issues.redhat.com/browse/DBZ-3563[DBZ-3563], https://issues.redhat.com/browse/DBZ-3599[DBZ-3599]),
and more efficient handling of LOB columns (https://issues.redhat.com/browse/DBZ-3556[DBZ-3556]).

== Further Improvements and Bugfixes

The Debezium connector for SQL Server saw two performance-related improvments
(https://issues.redhat.com/browse/DBZ-3486[3486], https://issues.redhat.com/browse/DBZ-3515[DBZ-3515]).
The schemas of change events from the Postgres connector contain default values now, based on the source column definition
(https://issues.redhat.com/browse/DBZ-2790[DBZ-2790]).
This comes in handy for instance when deriving downstream table schemas from a change event stream.

Other fixes include correct identification of primary members in MongoDB replica sets (https://issues.redhat.com/browse/DBZ-3522[DBZ-3522]),
support for the `JSON` function in the MySQL connector's DDL parser (https://issues.redhat.com/browse/DBZ-3559[DBZ-3559]),
and the upgrade of the link:/documentation/reference/integrations/outbox.html[Debezium Quarkus extension] for implementing the outbox pattern to Quarkus 2.0 (https://issues.redhat.com/browse/DBZ-3550[DBZ-3550]).

Overall, https://issues.redhat.com/browse/DBZ-400?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.6.0.Beta2%20ORDER%20BY%20key%20ASC%2C%20component%20ASC[48 issues] have been addressed in Debezium 1.6.0.Beta2.
We're deeply grateful to all the community members contributing to this release:

https://github.com/ani-sha[Anisha Mohanty],
https://github.com/bingqinzhou[Bingqin Zhou],
https://github.com/roldanbob[Bob Roldan],
https://github.com/ccollingwood[Chris Collingwood],
https://github.com/Naros[Chris Cranford],
https://github.com/derekm[Derek Moore],
https://github.com/eslep[Eric Slep],
https://github.com/gvaquez-ubi[Gilles Vaquez],
https://github.com/gunnarmorling[Gunnar Morling],
Jackey Zhang,
https://github.com/jcechace[Jakub Cechacek],
https://github.com/novotnyJiri[Jiri Novotny],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/kppullin[Kevin Pullin],
https://github.com/patrichu-cisco[Patrick Chu],
https://github.com/roldanbob[Robert Roldan],
https://github.com/sarafonseca-123[Sara Fonseca],
https://github.com/morozov[Sergei Morozov],
https://github.com/smiklosovic[Stefan Miklosovic], and
https://github.com/ramanenka[Vadzim Ramanenka]!

With Beta2 through the door, we're entering the stabilization phase for the 1.6 release cycle.
You can expect one or two CRs (candidate releases),
before the final release, which is planned for the end of the month,
barring any unforeseen complications of cause.
Besides some more bug fixes and documentation improvements we're also intending to upgrade to Apache Kafka 2.8,
which will allow you to take a sneak peak at using Debezium with https://www.morling.dev/blog/exploring-zookeeper-less-kafka/[ZooKeeper-less Kafka]!

In parallel, we're going to work on the roadmap for Debezium 1.7 (due by the end of September).
Please get in touch via the https://groups.google.com/g/debezium/[mailing list] if you have specific feature requests for this release!
