---
layout: post
title:  Debezium 1.5.0.CR1 Released
date:   2021-03-24
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: ccranfor
---

It's my pleasure to announce the release of Debezium *1.5.0.CR1*!

As we begin moving toward finalizing the Debezium 1.5 release stream,
the Oracle connector has been promoted to stable and there were some TLS improvements for the Cassandra connector, as well as numerous bugfixes.
Overall, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.5.0.CR1%20ORDER%20BY%20issuetype%20DESC&startIndex=20[50 issues] have been addressed for this release.

+++<!-- more -->+++

== Oracle connector now stable

The Oracle connector has been in incubating status for a while but recent efforts have helped to bring new features and stability to the connector.
We felt at this point, the connector is ready so with this release we're officially promoting the Oracle connector from _incubating_ to *stable*.

A tremendous effort by the community has made all this possible.
The numerous contributions, bug reports, and testing has helped so much!
The team and I cannot thank the community enough for all its insight, help, and dedication in making this milestone a reality so quickly!

== Cassandra connector TLS improvements

The Cassandra connector uses the defaut available ciphers to establish SSL connections.
For most use cases, this is more than satisfactory; however it does prevent the use of non-standard ciphers.
In this release, the Cassandra connector property file can be configured to specify a list of ciphers in precedence order for use.

To use this new feature, add a line to the connector's property file like below:

[source,properties]
----
cipherSuites=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
----

== Bugfixes

A number of bugs were fixed in this release, e.g.:

* Debezium logs "is not a valid Avro schema name" can be too verbose https://issues.jboss.org/browse/DBZ-2511[DBZ-2511]
* message.key.columns Regex Validation Time Complexity https://issues.jboss.org/browse/DBZ-2957[DBZ-2957]
* OID values don't fit to INT32 schema https://issues.jboss.org/browse/DBZ-3033[DBZ-3033]
* Connector automatically restart on ORA-26653 https://issues.jboss.org/browse/DBZ-3236[DBZ-3236]
* UI container has no assets (JS artifacts, fonts, etc) and randomly fails building https://issues.jboss.org/browse/DBZ-3247[DBZ-3247]
* Revert Clob behavior for Oracle LogMiner to avoid null values https://issues.jboss.org/browse/DBZ-3257[DBZ-3257]
* SQL Server misses description for decimal.handling.mode https://issues.jboss.org/browse/DBZ-3267[DBZ-3267]
* Oracle connector ignores time.precision.mode and just uses adaptive mode https://issues.jboss.org/browse/DBZ-3268[DBZ-3268]
* commons-logging JAR is missing from Debezium Server distro https://issues.jboss.org/browse/DBZ-3277[DBZ-3277]
* MongoDB timeouts crash the whole connector https://issues.jboss.org/browse/DBZ-3278[DBZ-3278]
* Prefer archive logs over redo logs of the same SCN range https://issues.jboss.org/browse/DBZ-3292[DBZ-3292]
* LogMiner mining query may unintentionally skip records https://issues.jboss.org/browse/DBZ-3295[DBZ-3295]
* IndexOutOfBoundsException when LogMiner DML update statement contains a function as last column's value https://issues.jboss.org/browse/DBZ-3305[DBZ-3305]
* Out of memory with mysql snapshots (regression of DBZ-94 https://issues.jboss.org/browse/DBZ-3309[DBZ-3309]
* Keyword ORDER is a valid identifier in MySQL grammar https://issues.jboss.org/browse/DBZ-3310[DBZ-3310]
* DDL statement couldn't be parsed for ROW_FORMAT=TOKUDB_QUICKLZ https://issues.jboss.org/browse/DBZ-3311[DBZ-3311]
* LogMiner can miss a log switch event if too many switches occur. https://issues.jboss.org/browse/DBZ-3319[DBZ-3319]
* Function MOD is missing from MySQL grammar https://issues.jboss.org/browse/DBZ-3333[DBZ-3333]
* Incorrect SR label names in OCP testusite https://issues.jboss.org/browse/DBZ-3336[DBZ-3336]
* DB2 upstream tests are still using master as the default branch https://issues.jboss.org/browse/DBZ-3337[DBZ-3337]

As always, please refer to the link:/releases/1.5/release-notes/#release-1.5.0-cr1[release notes] for the complete list of resolved issues as well as procedures for upgrading to earlier Debezium versions.

A big thank you to all the contributors from the community who worked on this release:
https://github.com/frankkoornstra[Frank Koornstra] and
https://github.com/JeremyVigny[Jeremy Vigny].

== Outlook

As we begin to wrap up Debezium 1.5 and barring any unforeseen regressions or bug reports, we expect Debezium 1.5  Final to be released by the end of March.
Once 1.5 Final is out, we'll begin our focus toward 1.6.
We have quite a bit in store for Debezium 1.6 so stay tuned to learn what is lurking just around the corner!