---
layout: post
title:  Debezium 1.6.0.Alpha1 Released
date:   2021-05-06
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: jpechane
---

It's my pleasure to announce the first release of the Debezium 1.6 series, *1.6.0.Alpha1*!

This release brings the brand new feature called incremental snapshots for MySQL and PostgreSQL connectors,
a Kafka sink for Debezium Server,
as well as a wide range of bug fixes and other small feature additions.

+++<!-- more -->+++

== Incremental Snapshotting

Running Debezium exhibits few pain-points

* the necessity to execute consistent snapshot before streaming is started upon new connector restart
* inability to trigger full or partial snapshot after having connector to be running for some time

Starting this release we are deploying the solution to both these potential pitfalls.

The simpler one - an ability to trigger the snapshot during the runtime is solved by *ad-hoc snapshots*.
The user can trigger a snapshot anytime during the streaming phase by sending an `execute-snapshot` https://debezium.io/documentation/reference/1.6/configuration/signalling.html[signal] to Debezium with the list of tables to be snapshotted and the type of the snapshot to be used (only `incremental` is supported right now, see below).
When Debezium receives the signal it will execute the snapshot of the requested tables.

The more complex part that goes hand-in-hand with ad-hoc snapshotting is *incremental snapshots*.
This feature allows the user to execute a snapshot of a set of tables during the streaming phase without interrupting the streaming.
Moreover, contrary to the initial snapshot, the snapshot will resume upon connector restart and does not need to start from scratch again.

The implementation of this feature is based on a novel approach to snapshotting originally invented by https://arxiv.org/pdf/2010.12597v1.pdf[DBLog Framework].
Debezium implementation is described in more detail in the https://github.com/debezium/debezium-design-documents/blob/main/DDD-3.md[design document].

If you want to try the feature yourself then you need to

* provide a https://debezium.io/documentation/reference/1.6/configuration/signalling.html#_overview[signalling table]
* trigger an ad-hoc incremental snapshot by using SQL command like

```
INSERT INTO myschema.debezium_signal VALUES('ad-hoc-1', 'execute-snapshot', '{"data-collections": ["schema1.table1", "schema1.table2"]}')
```

== Kafka Sink for Debezium Server

Debezium connectors can either run in Kafka Connect or can be deployed using https://debezium.io/documentation/reference/1.6/operations/debezium-server.html[Debezium Server] that provides different destination sinks.
Starting with this release if a sink is Apache Kafka it is no longer necessary to use Kafka Connect but Debezium Server with https://debezium.io/documentation/reference/1.6/operations/debezium-server.html#_apache_kafka[Apache Kafka Sink] could be used instead which may simplify operational requirements for some deployments.
In this case, the regular Apache Kafka client API is used.

Altogether,  https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.5.0.Alpha1%20ORDER%20BY%20component%20ASC[47 issues] were fixed for this release.
A big thank you goes out to all the community members who contributed:
https://github.com/Alfusainey[Alfusainey Jallow],
https://github.com/bingqinzhou[Bingqin Zhou],
https://github.com/blcksrx[Hossein Torabi],
https://github.com/kyleyj[Kyley Jex],
https://github.com/mpermar[Martín Pérez],
https://github.com/patrichu-cisco[Patrick Chu],
https://github.com/raphaelauv[Raphael Auv],
https://github.com/tommyk-gears[Tommy Karlsson],
https://github.com/elgca[WenChao Ke],
and https://github.com/jjiey[yangsanity].

For the upcoming 1.6 preview releases, we're planning to focus on completing the follow-up task for incremental snapshotting and provide the support for SQL Server and Db2 connectors too, further improving the LogMiner-based connector implementation for Oracle mainly related to schema evolutions and LOB support.
