---
layout: post
title:  Debezium 1.9.0.Alpha2 Released
date:   2022-02-09
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: anmohant
---

It's my pleasure to announce the second release of the Debezium 1.9 series, *1.9.0.Alpha2*!

This release includes support for Oracle 21c,
improvements around Redis for Debezium Server, configuring the `kafka.query.timeout.ms` option,
and a number of bug fixes around DDL parsers, build infrastructure, etc.

Overall, the community fixed https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.9.0.Alpha2%20ORDER%20BY%20issuetype%20DESC[51 issues] for this release. Let’s take a closer look at some of the highlights.

+++<!-- more -->+++

== Support for Oracle 21c

The Debezium Oracle connector has been tested with the latest release of Oracle 21c, 21.3.0.0, and is compatible.
If you use either the LogMiner or the Xstreams adapter, you should now be able to use Oracle's latest flagship version and stream change events without any changes.
If you are on Oracle 12 or Oracle 19 and perform a database upgrade, your connector configuration should require no changes and remain compatible.

== Configuring `kafka.query.timeout.ms`

When using the Kafka Admin Client and issuing API calls, the default timeout is 3 seconds.
The new `kafka.query.timeout.ms` field can be used to provide a custom timeout to the Kafka Admin Client to avoid possible timeout problems in environments that may use TLS or SSL encryption or where network latency causes an unexpected timeout.

Thanks to the great work done by community member, https://github.com/snigdhasjg[Snigdhajyoti Ghosh].

== Improvements in Redis for Debezium Server

We have three new fields in the Redis support for Debezium Server

* `redis.retry.initial.delay.ms`
* `redis.retry.max.delay.ms`
* `batch.size`

Redis allows specifying a maximum memory limit using the `maxmemory` configuration; however, if this field is not configured then Redis will continue to allocate memory.
If all memory is consumed, an OutOfMemory exception occurs.
The Redis sink now uses `redis.retry.initial.delay.ms` and `redis.retry.max.delay.ms` to set an initial and max-retry delay to be more resilient to this and connection-related issues.
If you have or are experiencing such exceptions, we urge you to try these new settings to improve the sink's resilience and experience.

Pipeline-based transactions can substantially increase Redis queries.
In order to leverage pipeline-based transactions, the `batch.size` configuration option can be specified which will allow Redis to write batches of change records rather than each record one by one.

Thanks to https://github.com/spicy-sauc[Yossi Shirizli], for these amazing improvements.

== Other fixes

Some notable bug fixes and upgrades are:

* Suspected inconsistent documentation for 'Ad-hoc read-only Incremental snapshot' https://issues.redhat.com/browse/DBZ-4171[DBZ-4171]
* Oracle Logminer: snapshot->stream switch misses DB changes in ongoing transactions https://issues.redhat.com/browse/DBZ-4367[DBZ-4367]
* DDL parsing issue: ALTER TABLE ... MODIFY PARTITION ... https://issues.redhat.com/browse/DBZ-4649[DBZ-4649]
* OracleSchemaMigrationIT fails with Xstream adapter https://issues.redhat.com/browse/DBZ-4703[DBZ-4703]
* Migrating UI from webpack-dev-server v3 to v4 https://issues.redhat.com/browse/DBZ-4642[DBZ-4642]
* Upgrade postgres driver to version 42.3.2 https://issues.redhat.com/browse/DBZ-4658[DBZ-4658]
* Upgrade to Quarkus 2.7.0.Final https://issues.redhat.com/browse/DBZ-4677[DBZ-4677]
* Update shared UG deployment file for use with downstream OCP Install Guide https://issues.redhat.com/browse/DBZ-4700[DBZ-4700]
* Indicate ROWID is not supported by XStream https://issues.redhat.com/browse/DBZ-4702[DBZ-4702]
* Incremental snapshots does not honor column case sensitivity https://issues.redhat.com/browse/DBZ-4584[DBZ-4584]
* Build trigger issues https://issues.redhat.com/browse/DBZ-4672[DBZ-4672]
* Cannot expand JSON payload with nested arrays of objects https://issues.redhat.com/browse/DBZ-4704[DBZ-4704]

We will also be backporting the critical bugfixes to the 1.8 branch and will release Debezium 1.8.1.Final later this week.

A big thank you to all the contributors from the community who worked on this release:
https://github.com/isacandrei[Andrei Isac],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/roldanbob[Bob Roldan],
https://github.com/Naros[Chris Cranford],
https://github.com/daha[David Haglund],
https://github.com/chanetd[Dominique Chanet],
https://github.com/fuyar[Farid Uyar],
https://github.com/gunnarmorling[Gunnar Morling],
https://github.com/harveyyue[Harvey Yue],
https://github.com/ismailsimsek[Ismail Simsek],
https://github.com/jmks[Jason Schweier],
https://github.com/novotnyJiri[Jiri Novotny],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/mdrillin[Mark Drilling],
https://github.com/nathan-smit-1[Nathan Smit],
https://github.com/pmalon[Paweł Malon],
https://github.com/rk3rn3r[René Kerner],
https://github.com/shichao-an[Shichao An],
https://github.com/snigdhasjg[Snigdhajyoti Ghosh],
https://github.com/vjuranek[Vojtech Juranek], and
https://github.com/spicy-sauce[Yossi Shirizli]!
