---
layout: post
title:  Debezium 1.9.1.Final Released
date:   2022-04-21
tags: [ releases, mongodb, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: ccranfor
---

I'm excited to announce the release of Debezium *1.9.1.Final*!

This release primarily focuses on bugfixes and stability concerns after the 1.9.0.Final release.

+++<!-- more -->+++

== Overview

One of the more critical changes addresses a problem with the Oracle connector when stopping and restarting the connector.
More specifically, the last committed transaction's events would be re-emitted upon restart and should not have been (https://issues.redhat.com/browse/DBZ-4936[DBZ-4936]).

A second critical problem was that incremental snapshots were not working correctly for MongoDB.
When an incremental snapshot signal was sent, a JSON parsing error was raised and should not have been (https://issues.redhat.com/browse/DBZ-5015[DBZ-5015]).

And finally, there were numerous SQL parsing errors for both MySQL and Oracle that were also addressed (https://issues.redhat.com/browse/DBZ-4976[DBZ-4976], https://issues.redhat.com/browse/DBZ-4979[DBZ-4979], https://issues.redhat.com/browse/DBZ-4980[DBZ-4980], https://issues.redhat.com/browse/DBZ-4994[DBZ-4994], https://issues.redhat.com/browse/DBZ-4996[DBZ-4996]).

We strongly recommend upgrading to 1.9.1.Final to avoid these issues as well as the other bugfixes that were included as a part of this release.

Overall, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20and%20fixVersion%20%3D%201.9.1.Final[29 issues] were fixed in this release.
Please refer to the link:/releases/1.9/release-notes#release-1.9.1-final[release notes] to learn more about all fixed bugs, update procedures, etc.

Many thanks to the following individuals from the community which contributed to Debezium 1.9.1.Final:
https://github.com/LarsWerkman[ Lars Werkman],
https://github.com/jchipmunk[Andrey Pustovetov],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/bmorganpa[Brad Morgan],
https://github.com/Naros[Chris Cranford],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/yzia2000[Mohammad Yousuf Minhaj Zia],
https://github.com/ypt[Paul Tzen],
https://github.com/spicy-sauce[Yossi Shirizli], and
https://github.com/chadthman[chadthamn]!

== Outlook

The Debezium 1.9 release stream will remain the current long-running version for the next five months.
During this time, we will continue to evaluate user reports and do micro-releases to address bugs and regressions.

Also in the coming week, expect to hear updates about Debezium's link:/roadmap[roadmap] as well as a clear plan on Debezium 2.0, it's preview releases and what lies ahead for the future.
We have a lot in store to share, so be sure to stay tuned!