---
layout: post
title:  Debezium 1.9.6.Final Released
date:   2022-09-26
tags: [ releases, mongodb, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: ccranfor
---

I'm excited to announce the release of Debezium *1.9.6.Final*!

This release focuses on bug fixes and stability; and is the recommended update for all users from earlier versions.
This release contains https://issues.redhat.com/issues/?jql=project+%3D+DBZ+AND+fixVersion+%3D+1.9.6.Final[78 resolved issues] overall.

+++<!-- more -->+++

== Changes

A few noteworthy bug fixes and stability improvements include:

* Oracle SCAN VIP support https://issues.redhat.com/browse/DBZ-3987[DBZ-3987]
* Memory leak in EventDeserializer caused by tableMapEventByTableId https://issues.redhat.com/browse/DBZ-5126[DBZ-5126]
* Postgres Incremental Snapshot on parent partitioned table not working https://issues.redhat.com/browse/DBZ-5240[DBZ-5240]
* Lob type data is inconsistent between source and sink, after modifying the primary key https://issues.redhat.com/browse/DBZ-5295[DBZ-5295]
* Unsigned tinyint conversion fails for MySQL 8.x https://issues.redhat.com/browse/DBZ-5343[DBZ-5343]
* NullPointerException thrown when unique index based on both system and non-system generated columns https://issues.redhat.com/browse/DBZ-5356[DBZ-5356]
* AWS DocumentDB (with MongoDB Compatibility) Connect Fail https://issues.redhat.com/browse/DBZ-5371[DBZ-5371]
* org.postgresql.util.PSQLException: Bad value for type timestamp/date/time: CURRENT_TIMESTAMP https://issues.redhat.com/browse/DBZ-5384[DBZ-5384]
* Timestamp with time zone column's default values not in GMT https://issues.redhat.com/browse/DBZ-5403[DBZ-5403]
* OffsetStore not stopped if it fails to fully start https://issues.redhat.com/browse/DBZ-5433[DBZ-5433]
* Duplicate SCNs on same thread Oracle RAC mode incorrectly processed https://issues.redhat.com/browse/DBZ-5439[DBZ-5439]
* Outbox doesn't check array consistecy properly when it detemines its schema https://issues.redhat.com/browse/DBZ-5475[DBZ-5475]
* Debezium connector task didn't retry when failover in mongodb 5 https://issues.redhat.com/browse/DBZ-5479[DBZ-5479]
* Use TCCL as the default classloader to load interface implementations https://issues.redhat.com/browse/DBZ-5561[DBZ-5561]
* Vitess: Handle VStream close unepectedly https://issues.redhat.com/browse/DBZ-5579[DBZ-5579]
* Oracle connector parsing SELECT_LOB_LOCATOR event missing constant `unavailable.value.placeholder` https://issues.redhat.com/browse/DBZ-5581[DBZ-5581]
* Message with LSN foo larger than expected LSN bar https://issues.redhat.com/browse/DBZ-5597[DBZ-5597]
* Continuously WARNs about undo transactions when LOB is enabled https://issues.redhat.com/browse/DBZ-5635[DBZ-5635]
* Large numbers of ROLLBACK transactions can lead to memory leak when LOB is not enabled. https://issues.redhat.com/browse/DBZ-5645[DBZ-5645]

In addition, there were quite a number of SQL parser fixes for both MySQL and Oracle, https://issues.redhat.com/browse/DBZ-5472[DBZ-5472], https://issues.redhat.com/browse/DBZ-5488[DBZ-5488], https://issues.redhat.com/browse/DBZ-5499[DBZ-5499], https://issues.redhat.com/browse/DBZ-5508[DBZ-5508], https://issues.redhat.com/browse/DBZ-5521[DBZ-5521], https://issues.redhat.com/browse/DBZ-5522[DBZ-5522], https://issues.redhat.com/browse/DBZ-5526[DBZ-5526], https://issues.redhat.com/browse/DBZ-5550[DBZ-5550], https://issues.redhat.com/browse/DBZ-5592[DBZ-5592], https://issues.redhat.com/browse/DBZ-5595[DBZ-5595], https://issues.redhat.com/browse/DBZ-5605[DBZ-5605], https://issues.redhat.com/browse/DBZ-5630[DBZ-5630], and https://issues.redhat.com/browse/DBZ-5643[DBZ-5643].

Please refer to the link:/releases/1.9/release-notes#release-1.9.6-final[release notes] to learn more about all fixed bugs, update procedures, etc.

Many thanks to the following individuals from the community who contributed to Debezium 1.9.6.Final:
https://github.com/ahus1[Alexander Schwartz],
https://github.com/aloubyansky[Alexey Loubyansky],
Gabor Andras,
https://github.com/ajunwalker[Andrew Walker],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/roldanbob[Bob Roldan],
https://github.com/Naros[Chris Cranford],
https://github.com/ggaborg[Gabor Andras],
https://github.com/gunnarmorling[Gunnar Morling],
https://github.com/harveyyue[Harvey Yue],
https://github.com/HenryCaiHaiying[Henry Cai],
https://github.com/nicholas-fwang[Inki Hwang],
https://github.com/ismailsimsek[Ismail Simsek],
https://github.com/domsj[Jan Doms],
https://github.com/Jiabao-Sun[Jiabao Sun],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/nirolevy[Nir Levy],
https://github.com/thangdc94[Phạm Ngọc Thắng],
https://github.com/roldanbob[Robert Roldan],
https://github.com/morozov[Sergei Morozov],
https://github.com/smiklosovic[Stefan Miklosovic],
https://github.com/vjuranek[Vojtech Juranek], and
https://github.com/GOODBOY008[Zhongqiang Gong]!

== Outlook, What's next?

Debezium 1.9 will continue to receive bug fix and maintenance changes throughout the early part of the next quarter.
I expect there to be at least a 1.9.7.Final in the middle to late October timeframe, potentially wrapping up the 1.9 release stream.

Debezium 2.0 is wrapping up with the latest 2.0.0.Beta2 build released just last week.
We are currently focusing on bug fixes, stability, and polishing the Debezium 2.0 release stream.
We expect to have 2.0.0.CR1 released in about another week or so with 2.0.0.Final scheduled for mid-October.

Until next time, keep an eye out as we'll soon be discussing what's to come in Debezium 2.1 later this year!
