---
layout: post
title:  Debezium 1.9.0.Alpha1 Released
date:   2022-01-26
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: ccranfor
---

It's my pleasure to announce the first release of the Debezium 1.9 series, *1.9.0.Alpha1*!

With the new year comes a new release!
The Debezium 1.9.0.Alpha1 release comes with quite a number of fixes and improvements,
most notably improved metrics and Oracle ROWID data type support.

+++<!-- more -->+++

== Improved Metrics

Debezium's connectors provide a wide range of metrics.
We have expanded upon the `TotalNumberOfEventsSeen` metric to provide a breakdown of those events by type.
To support this endeavor, the following new metrics have been added:

* `TotalNumberOfCreateEventsSeen`
* `TotalNumberOfUpdateEventsSeen`
* `TotalNumberOfDeleteEventsSeen`

These metrics represent the number of _insert_, _update_, and _delete_ events respectively that have occurred since the start of the connector's streaming phase.
So not only can you continue to get the total number of events aggregate, but you can now get a breakdown of that total by event type.

== Oracle ROWID data type support

Oracle users may elect to use a `ROWID` data type column as an optimization to represent a relationship between the current row and the row identified by the `ROWID` column value.
Starting with this release, columns using the `ROWID` data type can be captured by Debezium and emitted in change events.

[NOTE]
====
Oracle has two flavors of row identifier column data types, `ROWID` and `UROWID`.
While these may be used interchangeably in some contexts, they're very different in the context of change data capture events.
Although we've added support for `ROWID`, support for `UROWID` remains unsupported at this time.
====

== Other Fixes

There were quite a number of bugfixes and stability changes in this release, some noteworthy are:

* JSON Payload not expanding when enabling it (https://issues.redhat.com/browse/DBZ-4457[DBZ-4457])
* R/O incremental snapshot can blocks the binlog stream on restart (https://issues.redhat.com/browse/DBZ-4502[DBZ-4502])
* Infinispan doesn't work with underscores inside cache names (https://issues.redhat.com/browse/DBZ-4526[DBZ-4526])
* Can't process column definition with length exceeding Integer.MAX_VALUE (https://issues.redhat.com/browse/DBZ-4583[DBZ-4583])
* Oracle connector can't find the SCN (https://issues.redhat.com/browse/DBZ-4597[DBZ-4597])
* Update Postgres JDBC driver to 42.3.1 (https://issues.redhat.com/browse/DBZ-4374[DBZ-4374])
* Upgrade SQL Server driver to 9.4 (https://issues.redhat.com/browse/DBZ-4463[DBZ-4463])


Altogether, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.9.0.Alpha1%20ORDER%20BY%20component%20ASC[100 issues] were fixed for this release.
A big thank you to all the contributors from the community who worked on this release:

https://github.com/ani-sha[Anisha Mohanty],
https://github.com/roldanbob[Bob Roldan],
https://github.com/Naros[Chris Cranford],
https://github.com/chanetd[Dominique Chanet],
https://github.com/gunnarmorling[Gunnar Morling],
https://github.com/hjwalt[Hady Willi],
https://github.com/harveyyue[Harvey Yue],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/JapuDCret[JapuDCret],
https://github.com/novotnyJiri[Jiri Novotny],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/kgalieva[Katerina Galieva],
https://github.com/wndemon[Nansen],
https://github.com/nathan-smit-1[Nathan Smit],
https://github.com/0sc[Oscar Romero],
https://github.com/poonam-meghnani[Poonam Meghnani],
https://github.com/zhongqishang[Qishang Zhong],
https://github.com/sarumont[Richard Kolkovich],
https://github.com/Sebruck[Sebastian Bruckner],
https://github.com/morozov[Sergei Morozov],
https://github.com/shichao-an[Shichao An], and
https://github.com/AChangFeng[胡琴].

== What's Next?

We have started an https://groups.google.com/u/1/g/debezium/c/X17AUmQ88-E[open discussion] regarding Debezium 2.0 on the mailing list.
Your feedback is invaluable so let us know what you'd like to see added, changed, or improved!

In the meantime, we're just getting started!
There will be another 1.9 pre-release in the coming weeks, sticking with our 3-week cadence.
You can also expect a bugfix release sometime this quarter for 1.8 as we continue to get community feedback.

