---
layout: post
title:  Debezium 2.1.0.Final Released
date:   2022-12-22
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, mongodb, spanner ]
author: jpechane
---

Today it's my great pleasure to announce the availability of Debezium *2.1.0.Final*!

You might recently noticed that Debezium went a bit silent for the last few weeks.
No, we are not going away. In fact the elves in Google worked furiously to bring you a present under a Christmas tree - Debezium Spanner connector.

+++<!-- more -->+++

After a plenty of intensive effort we woud like to present https://github.com/nancyxu123[Nancy Xu] as the leading engineer behind the implementation of the https://github.com/debezium/debezium-connector-spanner[Debezium Spanner connector] for Google's https://cloud.google.com/spanner[Cloud Spanner] distributed database.
The connector itself is now in incubating state and still not fully feature complete (for example initial snapshots are not supported yet). Yet it is ready for a general use in scenarios where a robust Spanner-to-Kafka streaming implementation is required.

The initial release provides

* https://repo1.maven.org/maven2/io/debezium/debezium-connector-spanner/2.1.0.Final/[Installation packages]
* https://hub.docker.com/layers/debezium/connect/2.1.0.Final/images/sha256-43975658ce8055cd0733f99e574393c387649b7ad63c1a65c0b7901e445904ee?context=repo[Container image]
* link:/documentation/reference/2.1/connectors/spanner.html[Documentation]

As exciting these news are, this is not the only new feature available for Debezium. The release brings a nice pack of additional improvements.

* Vitess connector supports initial snapshotting.
This is a completely new feature and means that now the default behaviour for a new Vitess connector instance is to snapshot the current table content and then switch to streaming.
* Starting Debezium 2.0 we extracted a set of interfaces to provide additional pluggable persistent stores.
Redis offset and internal schema history store was converted into module and is now available for generic use.
* MySQL connector processes `TRUNCATE TABLE` commands.
When detected a `t` message is emitted into the table topic.
This feature is optional and is diabled by default.
* Kafka Connect provides so-called `predicates` that enable user to apply transfromations conditionally.
Debezium Engine and Debezium Server supports the same functionality too and is configured in the same way as kafka Connect.
* PostgreSQL connector is compatible with PostgreSQL 15.
* Cassandra connector is from the very start a bit odd duckgling in the way how the codebase is written and connector deployed.
This meant that only Kafka was suported as a destination.
The connector was rewritten so it now can run inside Debezium Server and so any suported sink can be used as the destination.
* Nats JetStream is the new sink provided by Debezium Server.
* Kafka Connect by default calculates the topic partition number based on the message primary key.
With the new `ComputePartition` it is possible to define a list of per-table columns to explicitly calculate and set the partition number.
* PostgreSQL flushes LSN (and thus truncates the WAL) when the message is recorded in Kafka.
For scenarios that prefer manual WAL management it is possible to disable this behaviour.
* MongoDB connector always connected and streamed from primary node in the cluster.
This is no longer necessary and non-primary nodes are preferred.

== Other fixes & improvements

There were many bugfixes, stability changes, and improvements throughout the development of Debezium 2.1.
Altogether, a total of https://issues.redhat.com/browse/DBZ-5824?jql=project%20%3D%20DBZ%20AND%20fixVersion%20in%20(2.1.0.Alpha1%2C%202.1.0.Alpha2%2C%202.1.0.Beta1%2C%202.1.0.Final)%20ORDER%20BY%20component%20ASC[149 issues] were fixed for this release.

A big thank you to all the contributors from the community who worked on this major release:
Masazumi Kobayashi,
https://github.com/jchipmunk[Andrey Pustovetov],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/Skezzowski[Balázs Sipos],
https://github.com/roldanbob[Bob Roldan],
https://github.com/btiernay[Bobby Tiernay],
https://github.com/Naros[Chris Cranford],
https://github.com/egyedt[Egyed Tamas],
https://github.com/enzo-cappa[Enzo Cappa],
https://github.com/erdinctaskin[Erdinç Taşkın],
https://github.com/ggaborg[Gabor Andras],
https://github.com/gunnarmorling[Gunnar Morling],
https://github.com/harveyyue[Harvey Yue],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/jeremy-l-ford[Jeremy Ford],
https://github.com/novotnyJiri[Jiri Novotny],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/keriharris[Keri Harris],
https://github.com/marceloavan[Marcelo Avancini],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/dude0001[Mark Lambert],
https://github.com/MartinMedek[Martin Medek],
https://github.com/mikekamornikov[Mike Kamornikov],
https://github.com/nancyxu123[Nancy Xu],
https://github.com/nirolevy[Nir Levy],
https://github.com/obabec[Ondrej Babec],
https://github.com/poonam-meghnani[Poonam Meghnani],
https://github.com/prburgu[Praveen Burgu],
https://github.com/uurl[Raúl Estrada],
https://github.com/roldanbob[Robert Roldan],
https://github.com/sahapasci[Sahap Asci],
https://github.com/smiklosovic[Stefan Miklosovic],
https://github.com/subodh1810[Subodh Kant Chaturvedi],
https://github.com/vjuranek[Vojtech Juranek],
https://github.com/wuzhenhua01[Wu Zhenhua],
Xuan Shen,
https://github.com/yoheimuta[Yohei Yoshimuta],
https://github.com/tooptoop4[tooptoop4]!

== What's next?

So what are our current plans for the first quarter of the next year?
Some potential features you can expect include:

* Initial work on JDBC sink connector
* Configurable signalling channels
* JDBC and S3 history and offset storage support

As always, this roadmap is heavily influenced by the community, i.e. you.
So if you would like to see any particular items here, please let us know.

Merry Christmas and Happy New Year 2023!

Onwards and Upwards!

