---
layout: post
title:  Debezium 1.9.7.Final Released
date:   2022-10-26
tags: [ releases, mongodb, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: ccranfor
---

I'm excited to announce the release of Debezium *1.9.7.Final*!

This release focuses on bug fixes and stability; and is the recommended update for all users from earlier versions.
This release contains https://issues.redhat.com/issues/?jql=project+%3D+DBZ+AND+fixVersion+%3D+1.9.7.Final[22 resolved issues] overall.

+++<!-- more -->+++

== Changes

A few noteworthy bug fixes and stability improvements include:

* Debezium connectors ship with an old version of google-protobuf vulnerable to CVE-2022-3171 https://issues.redhat.com/browse/DBZ-5747[DBZ-5747]
* ORA-01289: cannot add duplicate logfile https://issues.redhat.com/browse/DBZ-5276[DBZ-5276]
* Using snapshot boundary mode "all" causes DebeziumException on Oracle RAC https://issues.redhat.com/browse/DBZ-5302[DBZ-5302]
* Missing snapshot pending transactions https://issues.redhat.com/browse/DBZ-5482[DBZ-5482]
* Outbox pattern nested payload leads to connector crash https://issues.redhat.com/browse/DBZ-5654[DBZ-5654]
* Keyword virtual can be used as an identifier https://issues.redhat.com/browse/DBZ-5674[DBZ-5674]
* MongoDB Connector with DocumentDB errors with "{$natural: -1} is not supported" https://issues.redhat.com/browse/DBZ-5677[DBZ-5677]
* Function DATE_ADD can be used as an identifier https://issues.redhat.com/browse/DBZ-5679[DBZ-5679]
* UNIQUE INDEX with NULL value throws exception when lob.enabled is true https://issues.redhat.com/browse/DBZ-5682[DBZ-5682]
* MySqlConnector parse create view statement failed https://issues.redhat.com/browse/DBZ-5708[DBZ-5708]
* Debezium Server 1.9.6 is using MSSQL JDBC 7.2.2 instead of 9.4.1 https://issues.redhat.com/browse/DBZ-5711[DBZ-5711]
* Vitess: Handle Vstream error: unexpected server EOF https://issues.redhat.com/browse/DBZ-5722[DBZ-5722]
* ParsingException: DDL statement couldn't be parsed (index hints) https://issues.redhat.com/browse/DBZ-5724[DBZ-5724]
* Oracle SQL parsing error when collation used https://issues.redhat.com/browse/DBZ-5726[DBZ-5726]
* Unparseable DDL statement https://issues.redhat.com/browse/DBZ-5734[DBZ-5734]

Please refer to the link:/releases/1.9/release-notes#release-1.9.7-final[release notes] to learn more about all fixed bugs, update procedures, etc.

Many thanks to the following individuals from the community who contributed to Debezium 1.9.7.Final:
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/xinbinhuang[Bin Huang],
https://github.com/roldanbob[Bob Roldan],
https://github.com/Naros[Chris Cranford],
https://github.com/harveyyue[Harvey Yue],
https://github.com/HenryCaiHaiying[Henry Cai],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/janjwerner-confluent[Jan Werner],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/joschi[Jochen Schalanda],
https://github.com/nilshartmann[Nils Hartmann],
https://github.com/thangdc94[Phạm Ngọc Thắng],
https://github.com/Sage-Pierce[Sage Pierce],
https://github.com/smiklosovic[Stefan Miklosovic], and
https://github.com/vjuranek[Vojtech Juranek]!

== Outlook, What's next?

This past year has been packed full of tons of changes.
This makes the eighth and likely final stable release for Debezium 1.9 as we begin to turn our attention fully to Debezium 2.0 moving forward.

With Debezium 2.0 released on October 17th, just last week, the team is now hard at work addressing your feedback, so keep that coming.
We're also actively working on the next installment of Debezium, 2.1, which will be released later this year.
Be sure to keep an eye on our link:/roadmap[road map] in the coming week as we intend to debut what is planned for Debezium 2.1 and what's to come in 2023!

Until then, stay safe!