---
layout: post
title:  Debezium 1.9.5.Final Released
date:   2022-07-11
tags: [ releases, mongodb, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: ccranfor
---

With the summer in full swing, the team is pleased to announce the release of Debezium *1.9.5.Final*!

This release primarily focuses on bugfixes and stability; and is the recommended update for all users from earlier versions.
This release contains https://issues.redhat.com/issues/?jql=project+%3D+DBZ+AND+fixVersion+%3D+1.9.5.Final[24 resolved issues] overall.

+++<!-- more -->+++

== Changes

This release focused entirely on stability and bugfixes.
A few noteworthy changes include:

* Data duplication problem using postgresql source on debezium server https://issues.redhat.com/browse/DBZ-5070[DBZ-5070]
* Duplicate SCNs on Oracle RAC installations incorrectly processed https://issues.redhat.com/browse/DBZ-5245[DBZ-5245]
* NPE when using Debezium Embedded in Quarkus https://issues.redhat.com/browse/DBZ-5251[DBZ-5251]
* No changes to commit_scn when oracle-connector got new lob data https://issues.redhat.com/browse/DBZ-5266[DBZ-5266]
* database.history.store.only.captured.tables.ddl not suppressing logs https://issues.redhat.com/browse/DBZ-5270[DBZ-5270]
* Debezium server fail when connect to Azure Event Hubs https://issues.redhat.com/browse/DBZ-5279[DBZ-5279]
* Enabling database.history.store.only.captured.tables.ddl does not restrict history topic records https://issues.redhat.com/browse/DBZ-5285[DBZ-5285]
* Snapshot fails when table's relational model is created using an abstract data type as unique index https://issues.redhat.com/browse/DBZ-5300[DBZ-5300]
* Incremental Snapshot: Oracle table name parsing does not support periods in DB name https://issues.redhat.com/browse/DBZ-5336[DBZ-5336]
* Support PostgreSQL default value function calls with schema prefixes https://issues.redhat.com/browse/DBZ-5340[DBZ-5340]
* Log a warning when an unsupported LogMiner operation is detected for a captured table https://issues.redhat.com/browse/DBZ-5351[DBZ-5351]
* MySQL Connector column hash v2 does not work https://issues.redhat.com/browse/DBZ-5366[DBZ-5366]
* Outbox JSON expansion fails when nested arrays contain no elements https://issues.redhat.com/browse/DBZ-5367[DBZ-5367]
* docker-maven-plugin needs to be upgraded for Mac Apple M1 https://issues.redhat.com/browse/DBZ-5369[DBZ-5369]

Please refer to the link:/releases/1.9/release-notes#release-1.9.5-final[release notes] to learn more about all fixed bugs, update procedures, etc.

Many thanks to the following individuals from the community which contributed to Debezium 1.9.5.Final:
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/roldanbob[Bob Roldan],
https://github.com/ProofOfPizza[Chai Stofkoper],
https://github.com/Naros[Chris Cranford],
Mikhail Dubrovin,
https://github.com/harveyyue[Harvey Yue],
https://github.com/HenryCaiHaiying[Henry Cai],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/pmalon[Paweł Malon],
https://github.com/roldanbob[Robert Roldan],
https://github.com/vjuranek[Vojtech Juranek], and
https://github.com/yangrong688[yangrong688]!

== Outlook

The Debezium 1.9 release stream will remain the current long-running version for the next three months.
During this time, we will continue to evaluate user reports and do micro-releases to address bugs and regressions depending on severity.

The development on Debezium 2.0 is moving along quite nicely.
We have entered the second half of the development cycle, and we'll begin beta releases with the next release toward the end of July.

Stay tuned for more in the coming weeks, stay cool out there, and happy capturing!
