---
layout: post
title:  Debezium 2.0.0.Alpha3 Released
date:   2022-07-05
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: ccranfor
---

I am thrilled to share that Debezium *2.0.0.Alpha3* has been released!

While this release contains a plethora of bugfixes,
there are a few noteworthy improvements,
which include providing a timestamp in transaction metadata events,
the addition of several new fields in Oracle's change event source block,
and a non-backward compatible change to the Oracle connector's offsets.

Lets take a look at these in closer detail.

+++<!-- more -->+++

== Transaction metadata changes

A transaction metadata event describes the _beginning_ and the _end_ (commit) of a database transaction.
These events are useful for a variety of reasons, including auditing.
By default, transaction metadata events are not generated by a connector and to enable this feature, the `provide.transaction.metadata` option must be enabled.

In this release, both `BEGIN` and `END` events include a new field, `ts_ms`, which is the database timestamp of when the transaction either began or committed depending on the event type.
An example of such an event now looks like:

[source,json]
----
{
  "status": "END",
  "id": "12345",
  "event_count": 2,
  "ts_ms": "1657033173441",
  "data_collections": [
    {
      "data_collection": "s1.a",
      "event_count": 1
    },
    {
      "data_collection": "s2.a",
      "event_count": 1
    }
  ]
}
----

If you are already using the transaction metadata feature, new events will contain this field after upgrading.

If you are not using the transaction metadata feature but find this useful, simply add the `provide.transaction.metadata` option set to _true_ to your connector configuration.
By default, metadata events are emitted to a topic named after your `database.server.name` option.
This can be overridden by specifying the `transaction.topic` option, as shown below:

[source,properties]
----
database.server.name=server1
provide.transaction.metadata=true
transaction.topic=my-transaction-events
----

In this example, all transaction metadata events will be emitted to `my-transaction-events`.
Please see your connector specific configuration for more details.

== Oracle source info changes

The `source` information block is a section in the change event's payload that describes the database attributes of what generated the change event.
For example, this section includes the system change number, the database timestamp of the change, and the transaction the change was part of.

In this release, we identified a regression where the `scn` field did not correctly reflect the right `source` of where the change event occurred.
While it isn't abnormal for Oracle to generate multiple changes with the same system change number, we did find a regression that caused the wrong system change number to get assigned to each individual event within a scoped transaction, which made it difficult for some to use this information for auditing purposes.
The `source.scn` field should now correctly reflect the system change number from Oracle LogMiner or Oracle Xstream.

Additionally, several new fields were added to the `source` information block to improve integration with the LogMiner implementation and Oracle RAC.
An example of the new source information block:

[source,json]
----
{
    "source": {
        "version": "2.0.0.Alpha3",
        "name": "server1",
        "ts_ms": 1520085154000,
        "txId": "6.28.807",
        "scn": "2122184",
        "commit_scn": "2122185",
        "rs_id": "001234.00012345.0124",
        "ssn": 0,
        "redo_thread": 1
    }
}
----

The newly added fields are:

`rs_id`::
Specifies the rollback segment identifier associated with the change.

`ssn`::
Specifies the SQL sequence number, this combined with the `rs_id` represent a unique tuple for a change.

`redo_thread`::
Specifies the actual database redo thread that managed the change's lifecycle.

Whether using Oracle Standalone or RAC, these values will always be provided when using Oracle LogMiner.
These values have more importance on an Oracle RAC installation because you have multiple database servers manipulating the shared database concurrently.
These fields specifically annotate which node and at what position on that node that the change originated.

== Oracle connector offset changes

In an Oracle Real Application Clusters (RAC) environment, multiple nodes access and manipulate the Oracle database concurrently.
Each node maintains its own redo log buffers and executes its own redo writer thread.
This means that at any given moment, each node has its own unique "position" and these will differ entirely on the activity that takes place on each respective node.

In this release, a small change was necessary in https://issues.redhat.com/browse/DBZ-5245[DBZ-5245] to support Oracle RAC.
Previously, the connector offsets maintained a field called `scn` which represented this "position" of where the connector should stream changes from.
But since each node could be at different positions in the redo, a single `scn` value was inadequate for Oracle RAC.

The old Oracle connector offsets looked like this:

[source,json]
----
{
  "scn": "1234567890",
  "commit_scn": "2345678901",
  "lcr_position": null,
  "txId": null
}
----

Starting in 2.0.0.Alpha3, the new offset structure now has this form:

[source,json]
----
{
  "scn": "1234567890:00124.234567890.1234:0:1,1234567891:42100.0987656432.4321:0:2",
  "commit_scn": "2345678901",
  "lcr_position": null,
  "txId": null
}
----

You will notice that the `scn` field now consists of a comma-separated list of values, where each entry represents a tuple of values.
This new tuple has the format of `scn:rollback-segment-id:ssn:redo-thread`.

While this change is forward compatible, meaning you can safely upgrade to 2.0.0.Alpha3 and the old format can be read, once the new format is written to the offsets, the older versions of the connector will be unable to read the offsets.
If you upgrade and decide you need to roll back, be aware you'll need to manually adjust the connector offset's `scn` field to simply contain a string of the most recent `scn` value across all redo threads.

== Other fixes & improvements

There are several bugfixes and stability changes in this release, some noteworthy are:

* Incorrect loading of LSN from offsets https://issues.redhat.com/browse/DBZ-3942[DBZ-3942]
* Database history recovery will retain old tables after they've been renamed https://issues.redhat.com/browse/DBZ-4451[DBZ-4451]
* Adding new table with incremental snapshots not working https://issues.redhat.com/browse/DBZ-4834[DBZ-4834]
* BigDecimal has mismatching scale value for given Decimal schema https://issues.redhat.com/browse/DBZ-4890[DBZ-4890]
* Debezium has never found starting LSN https://issues.redhat.com/browse/DBZ-5031[DBZ-5031]
* Data duplication problem using postgresql source on debezium server https://issues.redhat.com/browse/DBZ-5070[DBZ-5070]
* Cursor fetch is used for all results during connection https://issues.redhat.com/browse/DBZ-5084[DBZ-5084]
* Debezuim connector fails at parsing select statement overrides when table name has space https://issues.redhat.com/browse/DBZ-5198[DBZ-5198]
* DDL statement couldn't be parsed 2 - Oracle connector 1.9.3.Final https://issues.redhat.com/browse/DBZ-5230[DBZ-5230]
* Debezium server duplicates scripting jar files https://issues.redhat.com/browse/DBZ-5232[DBZ-5232]
* Cannot convert field type tinyint(1) unsigned to boolean https://issues.redhat.com/browse/DBZ-5236[DBZ-5236]
* Oracle unparsable ddl create table https://issues.redhat.com/browse/DBZ-5237[DBZ-5237]
* Postgres Incremental Snapshot on parent partitioned table not working https://issues.redhat.com/browse/DBZ-5240[DBZ-5240]
* Character set influencers are not properly parsed on default values https://issues.redhat.com/browse/DBZ-5241[DBZ-5241]
* NPE when using Debezium Embedded in Quarkus https://issues.redhat.com/browse/DBZ-5251[DBZ-5251]
* Oracle LogMiner may fail with an in-progress transaction in an archive log that has been deleted https://issues.redhat.com/browse/DBZ-5256[DBZ-5256]
* Order of source block table names in a rename schema change event is not deterministic https://issues.redhat.com/browse/DBZ-5257[DBZ-5257]
* Debezium fails to connect to replicaset if a node is down https://issues.redhat.com/browse/DBZ-5260[DBZ-5260]
* No changes to commit_scn when oracle-connector got new lob data https://issues.redhat.com/browse/DBZ-5266[DBZ-5266]
* Invalid date 'SEPTEMBER 31' https://issues.redhat.com/browse/DBZ-5267[DBZ-5267]
* database.history.store.only.captured.tables.ddl not suppressing logs https://issues.redhat.com/browse/DBZ-5270[DBZ-5270]
* io.debezium.text.ParsingException: DDL statement couldn't be parsed https://issues.redhat.com/browse/DBZ-5271[DBZ-5271]
* Deadlock during snapshot with Mongo connector https://issues.redhat.com/browse/DBZ-5272[DBZ-5272]
* Mysql parser is not able to handle variables in KILL command https://issues.redhat.com/browse/DBZ-5273[DBZ-5273]
* Debezium server fail when connect to Azure Event Hubs https://issues.redhat.com/browse/DBZ-5279[DBZ-5279]
* ORA-01086 savepoint never established raised when database history topic cannot be created or does not exist https://issues.redhat.com/browse/DBZ-5281[DBZ-5281]
* Enabling database.history.store.only.captured.tables.ddl does not restrict history topic records https://issues.redhat.com/browse/DBZ-5285[DBZ-5285]

Altogether, a total of https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%202.0.0.Alpha3%20ORDER%20BY%20component%20ASC[66 issues] were fixed for this release.

A big thank you to all the contributors from the community who worked on this release:
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/roldanbob[Bob Roldan],
https://github.com/ProofOfPizza[Chai Stofkoper],
https://github.com/Naros[Chris Cranford],
Mikhail Dubrovin,
https://github.com/gunnarmorling[Gunnar Morling],
https://github.com/harveyyue[Harvey Yue],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/novotnyJiri[Jiri Novotny],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/yannickzj[Jun Zhao],
https://github.com/kanha-gupta[Kanha Gupta],
https://github.com/alwaysbemark[Mark Bereznitsky],
https://github.com/mimaison[Mickael Maison],
https://github.com/mikekamornikov[Mike Kamornikov],
https://github.com/krnaveen14[Naveen Kumar KR],
Oskar Polak,
https://github.com/rahulkhanna2[Rahul Khanna],
https://github.com/roldanbob[Robert Roldan],
https://github.com/tim-patterson[Tim Patterson],
https://github.com/vjuranek[Vojtech Juranek], and
https://github.com/yangrong688[yangrong688]!

== What's Next?

You can expect a 1.9.5.Final release in the next week.
This release will include many of the bugfixes that are part of this release, as we continue to improve the stability of 1.9 in micro-releases.

You can also expect 2.0.0.Beta1 in the next 3 weeks, keeping with our usual release cadence.
The next major milestones includes unifying snapshot modes across connectors, a new `Snapshotter` API for all connectors, compactable JSON database history, offset unification, offset storage API and much more.


