---
layout: post
title:  Debezium Community Newsletter 01/2022
date:   2022-10-05
tags: [ community, news, newsletter ]
author: ccranfor
---

Welcome to the latest edition of the Debezium community newsletter, in which we share all things change data capture (CDC) related including blog posts,
group discussions, as well as StackOverflow questions that are relevant to our user community.

It has been a while since our last newsletter, but we're back!
In case you missed our last publication, you can check it out at link:/blog/2021-07-07/debezium-newsletter-01-2021/[here].

+++<!-- more -->+++

== Upcoming Events

While the pandemic is still ongoing, conferences, and meet-ups have begun to move slightly away from virtual to in-person.
We're excited to see this happening, but this is still something that is ongoing, and it varies on the event.
Regardless of whether the event is in-person or virtual, here's a list of remaining events for this year:

* https://devoxx.be/talk/?id=20401[DEVOXX Belgium 2022 -- "Keep Your Cache Always Fresh with Debezium!"] by Gunnar Morling

If you would like to have a session on Debezium at any meet-up or conference, please get in touch!

== Articles

There have been several blog posts about Debezium lately; here are some of the latest ones that you should check out:

* A series of insightful blog posts about Debezium and change data capture in general by Dunith Dhanushka:
** link:https://medium.com/event-driven-utopia/cdc-based-upserts-with-debezium-apache-kafka-and-apache-pinot-427cced24eb1[CDC-based Upserts with Debezium, Apache Kafka, and Apache Pinot]
** link:https://medium.com/event-driven-utopia/building-cqrs-views-with-debezium-kafka-materialize-and-apache-pinot-part-1-4f697735b2e4[Building CQRS Views with Debezium, Kafka, Materialize, and Apache Pinot - Part 1]
** link:https://medium.com/event-driven-utopia/building-cqrs-views-with-debezium-kafka-materialize-and-apache-pinot-part-2-6899e9efc74e[Building CQRS Views with Debezium, Kafka, Materialize, and Apache Pinot - Part 2]

* link:https://medium.com/yotpoengineering/scheduling-millions-of-messages-with-kafka-debezium-6d1a105160c[Scheduling Millions of Messages With Kafka & Debezium] by Ella Rohana.

Please also check out our compiled list of link:/documentation/online-resources/[resources around Debezium] for even more related posts, articles, podcasts and presentations.

== Integrations

A few cool integrations and usages of Debezium appeared over the last few weeks and months.
Here are several ones which we found especially fascinating:

* A Debezium Server https://github.com/memiiso/debezium-server-bigquery[outbound adapter for BigQuery]

== Examples

If you are getting started with Debezium, you can get hands-on learning and better understanding of how things work from the examples and demos in our https://github.com/debezium/debezim-examples[examples repository].
We have introduced several new examples and updated the existing ones.
Out of which we'd like to highlight some new additions:

* https://github.com/debezium/debezium-examples/tree/main/mongodb-outbox[Demonstrates the Outbox pattern with MongoDB]

If you are interested in showcasing a new demo or an example, please send us a GitHub pull request or reach out to us directly through our community channels found link:/community[here].

== Time to Upgrade

Debezium version link:/blog/2022/09/26/debezium-1-9-6-final-released/[1.9.6.Final] was released recently.
The Debezium 1.9 release stream has been the ongoing stable release for the last 6 months, and has brought about a number of new features as well as hundreds of bugfixes.
Some noteworthy enhancements include:

* Support for Cassandra 4
* SQL Server Multi-database Support
* Debezium Server sink for Knative Serving (HTTP)
* Debezium Server storage with Redis Streams
* Binary-based SerDes Supprot for MongoDB
* Initial-only Snapshots for Db2

But given the length since our last newsletter, we've also published two addition release streams, versions 1.7 and 1.8 in September 2021 and December 2021 respectively.
The following list are some new features worth mentioning in those releases as well:

* [1.8] MongoDB Change Streams support
* [1.8] Improved Infinispan Integration with Oracle
* [1.8] Default values stored in JSON-based schema history
* [1.8] Heartbeat Action Query support
* [1.8] Configurable transaction topic name
* [1.8] Support for `pg_logical_emit_message` in PostgreSQL
* [1.8] Incremental snapshots for MongoDB
* [1.8] New Debezium Kafka Connect REST extension
* [1.7] Infinispan Integration with Oracle
* [1.7] MySQL Read-Only Incremental Snapshots
* [1.7] Oracle Incremental Snapshots
* [1.7] Debezium Server NATs sink
* [1.7] Kafka-based signal support for MySQL

If you are using an older version, we urge you to check out the latest major release.
For details on all the bug fixes, enhancements, and improvements, please check out the link:/releases/1.9/release-notes[release-notes].

The Debezium team has also been diligently working on the next version, 2.0.
The major focus in 2.0 is Java 11, improvements to incremental snapshots, improved pass-through namespace support, and much more.
For details on the further upcoming release check out the link:/releases/2.0/release-notes[release-notes] for 2.0.

YOu can keep track of bug fixes, enhancements, and changes that will be coming up in the 2.0 release by visiting our link:/releases/[releases page].

== Questions and Answers

* https://stackoverflow.com/questions/73856736/debezium-mysql-kafkaconnect-capture-only-new-changelog-data[Debezium MySQL KafkaConnect - capture only new changelog data]
* https://stackoverflow.com/questions/73829017/aws-msk-s3-sink-json-messages-getting-stored-as-structs-instead-of-json[AWS MSK + S3 Sink - JSON Messages getting stored as Structs instead of JSON]
* https://stackoverflow.com/questions/73350827/kafka-is-not-accessbile-from-outside-of-the-docker-container[Kafka is not accessible from outside the docker container]
* https://stackoverflow.com/questions/73215023/kafka-connect-single-connector-or-connector-per-table-approach[Kafka Connect: Single connector or connector per table approach]
* https://stackoverflow.com/questions/73025949/how-to-manipulate-offsets-of-the-source-database-for-debezium[How to manipulate offsets of the source database for Debezium]
* https://stackoverflow.com/questions/72958490/debezium-sql-server-connector-couldnt-obtain-database-name[Debezium SQL Server Connector - "Couldn't obtain database name"]
* https://stackoverflow.com/questions/72639881/debezium-sql-server-source-connectors-streams-events-only-once-per-day[Debezium SQL Server Source Connectors streams events only once per day]
* https://stackoverflow.com/questions/72554856/debezium-connector-starts-but-returns-no-tables-from-cdc[Debezium connector starts but returns no tables from CDC]
* https://stackoverflow.com/questions/72213136/how-to-rename-the-id-header-of-a-debezium-mongodb-connector-outbox-message[How to rename the id header of a debezium mongodb connector outbox message]

== Getting Involved

Getting started with a huge, and an existing code base can be intimidating, but we want to make sure that the process of getting started is extremely easy and smooth for you here.
We are now a vibrant community with https://github.com/debezium/debezium/graphs/contributors[385+ contributors] overall, and we welcome all kinds of community contributions, discussions, and enhancements.
As a beginner, you can grab issues labeled with `easy-starter` if you want to dive in quickly.
Below is a list of issues that are open to grab:

* Add example for capturing changes from multiple SQL Server databases (https://issues.redhat.com/browse/DBZ-4803[DBZ-4803])
* Use `snapshot.isolation.mode` for incremental snapshots (https://issues.redhat.com/browse/DBZ-3653[DBZ-3653])
* Standardize "snapshot.fetch.size default" values across connectors (https://issues.redhat.com/browse/DBZ-3694[DBZ-3694])
* Establish some separate constant class (https://issues.redhat.com/browse/DBZ-3640[DBZ-3640])
* Implement window function in MySQL parser (https://issues.redhat.com/browse/DBZ-3576[DBZ-3576])
* Implement support for JSON_TABLE in MySQL parser (https://issues.redhat.com/browse/DBZ-3575[DBZ-3575])
* Create smoke test to make sure Debezium Server container image works (https://issues.redhat.com/browse/DBZ-3226[DBZ-3226])

If you are new to open source, please check out our https://github.com/debezium/debezium.github.io/blob/develop/CONTRIBUTING.md[contributing guidelines] to get started!

== Call to Action

Our link:/community/users[community users] page includes a variety of organizations that are currently using Debezium.
If you are a user of Debezium, and would like to be included, please send us a GitHub pull request or reach out to us directly through our community channels found link:/community[here].

And if you haven't yet done so, please consider https://github.com/debezium/debezium/stargazers[adding a ⭐] for the GitHub repo;
keep them coming, we're almost at 5,000 stars!

Also, we'd like to learn about your requirements for future Debezium versions.
In particular, we'd be very curious about your feedback on the https://github.com/debezium/debezium-examples/tree/main/saga[CDC-based Sagas approach] mentioned above.
Is it something you'd like to see supported in our link:/documentation/reference/integrations/outbox.html[Quarkus extension] for instance?
Please let us know about this, as well as any other feedback you may have, via the Debezium https://groups.google.com/g/debezium[mailing list].

Lastly, we're planning to continue our interview series link:/blog/2020/10/08/debezium-community-stories-with-renato-mefi/[Debezium Community Stories With...];
so if you got exciting stories to tell about your usage of Debezium,
please reach out!

And as always, stay safe, and healthy. Wish you and your loved ones good health and strength.
