---
layout: post
title:  Debezium 1.9.4.Final Released
date:   2022-06-21
tags: [ releases, mongodb, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: ccranfor
---

I'm pleased to announce the release of Debezium *1.9.4.Final*!

This release primarily focuses on bugfixes and stability; and is the recommended update for all users from earlier versions.
This release contains https://issues.redhat.com/issues/?jql=project+%3D+DBZ+AND+fixVersion+%3D+1.9.4.Final[32 resolved issues] overall.

+++<!-- more -->+++

== Fixes

This release focused entirely on stability and bugfixes.
A few noteworthy changes include:

* Include event scn in Oracle records https://issues.redhat.com/browse/DBZ-5225[DBZ-5225]
* Redis Store does not work with GCP Managed Redis https://issues.redhat.com/browse/DBZ-5268[DBZ-5268]
* Database history recovery will retain old tables after they've been renamed https://issues.redhat.com/browse/DBZ-4451[DBZ-4451]
* Adding new table with incremental snapshots not working https://issues.redhat.com/browse/DBZ-4834[DBZ-4834]
* Debezium has never found starting LSN https://issues.redhat.com/browse/DBZ-5031[DBZ-5031]
* Cursor fetch is used for all results during connection https://issues.redhat.com/browse/DBZ-5084[DBZ-5084]
* Debezium Postgres v1.9.3 fails in Materialize CI https://issues.redhat.com/browse/DBZ-5204[DBZ-5204]
* Cannot convert field type tinyint(1) unsigned to boolean https://issues.redhat.com/browse/DBZ-5236[DBZ-5236]
* Oracle LogMiner may fail with an in-progress transaction in an archive log that has been deleted https://issues.redhat.com/browse/DBZ-5256[DBZ-5256]
* Order of source block table names in a rename schema change event is not deterministic https://issues.redhat.com/browse/DBZ-5257[DBZ-5257]
* Debezium fails to connect to replicaset if a node is down https://issues.redhat.com/browse/DBZ-5260[DBZ-5260]
* Deadlock during snapshot with Mongo connector https://issues.redhat.com/browse/DBZ-5272[DBZ-5272]

In addition, there were several SQL parser fixes for both Oracle and MySQL.

Please refer to the link:/releases/1.9/release-notes/#release-1.9.4.Final[release notes] to learn more about all fixed bugs, update procedures, etc.

Many thanks to the following individuals from the community which contributed to Debezium 1.9.3.Final:
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/roldanbob[Bob Roldan],
https://github.com/Naros[Chris Cranford],
https://github.com/harveyyue[Harvey Yue],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/yannickzj[Jun Zhao],
Oskar Polak,
https://github.com/rahulkhanna2[Rahul Khanna],
https://github.com/rk3rn3r[René Kerner],
https://github.com/tim-patterson[Tim Patterson],
https://github.com/vjuranek[Vojtech Juranek]!

== Outlook

The Debezium 1.9 release stream will remain the current long-running version for the next three months.
During this time, we will continue to evaluate user reports and do micro-releases to address bugs and regressions depending on severity.

Also, quite a lot of work has gone into Debezium 2.0.
We are currently actively working on Debezium 2.0.0.Alpha3 and should have an update on this in the next week.

Stay tuned for more in the coming weeks and stay cool out there!