---
layout: post
title:  Debezium 1.9.0.Beta1 Released
date:   2022-03-03
tags: [ releases, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: ccranfor
---

I am happy to announce the release of Debezium *1.9.0.Beta1*!

This release includes many new features for Debezium Sink including Knative event support,
offset storage management with the Redis sink,
multi-partitioned SQL Server scaling,
and various of bugfixes and improvements.
Overall, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%201.9.0.Beta1%20ORDER%20BY%20component%20ASC[56 issues] have been fixed for this release.

Let's take a closer look at a couple of them.

+++<!-- more -->+++

== Debezium Server Knative events

Debezium Server has grown quite a lot since its introduction to the Debezium portfolio in version 1.2.
In this release, we have added a new sink implementation to support Knative eventing.

Knative eventing provides tools and infrastructure to route events from a producer to consumers, in a very similar way in which Apache Kafka allows the exchange of events via message topics.
With Debezium Server, you can now leverage the new https://github.com/debezium/debezium/tree/main/debezium-server/debezium-server-http[debezium-server-http] sink to deliver Debezium change events to a Knative Broker, a Kubernetes resource that defines a mesh for collecting and distributing https://cloudevents.io/[CloudEvents] to consumers.

In order to get started with Debezium and Knative eventing, you simply need to configure the Debezium Server with your desired source connector and then configure the sink side with the following:

```properties
debezium.sink.type=http
debezium.format.value=cloudevents
```

The sink will attempt to automatically detect the endpoint based on the `K_SINK` environment variable.
If no value is defined by this variable, you can explicitly provide the end-point URL directly using:

```properties
debezium.sink.http.url=https://<hostname>/<end-point>
```

We're super excited about this new sink connector and we look forward to all your feedback!

== Multi-partitioned SQL Server scaling

Some database platforms, such as SQL Server and Oracle, support the creation and management of multiple logical databases within a single database instance.
Traditionally, streaming changes from the multiple logical databases required a separate connector deployment.
Now there isn't anything innately wrong with such a deployment strategy, but it can quickly start to show its shortcomings if you have many logical databases and then there is also the concern of one task per connector.

Over the last several 1.x releases, a tremendous amount of work has gone into key fundamental changes to Debezium's common connector framework, setting the stage for a new horizontal scaling strategy.

One of the initial goals of this new strategy is to eliminate the need for multiple connector deployments when streaming changes from multiple logical databases within a single SQL Server instance.
Additionally, it was critical to expose metrics in a way that enables monitoring tools to report on the state and health of the connector both from a connector-centric perspective but also  from each logical database being processed.
In this release, we've achieved those goals.

But this is just the beginning folks!

This foundation prepares the groundwork where we can move toward new horizontal scaling strategies.
Debezium uses a single-task based architecture and this opens the possibilities to really harness the power of a multi-node Kafka Connect cluster and distribute chunks of work across multiple tasks.
Furthermore, this can be extended to other connectors such as Oracle.

This has been a wonderful journey with the folks at SugarCRM, and we're all still just getting started with what's to come.
We very much appreciate all their work they put into making this possible for the Debezium community!


== Other Fixes and Changes

Further fixes and improvements in the 1.9.0.Beta1 release include:

* Support for reading and storing connector offsets inside Redis when using the https://github.com/debezium/debezium/tree/main/debezium-server/debezium-server-redis[Redis sink] with Debezium Server (https://issues.redhat.com/browse/DBZ-4509[DBZ-4509])
* Various DDL parser fixes for both MySQL (https://issues.redhat.com/browse/DBZ-4707[DBZ-4707]) and Oracle (https://issues.redhat.com/browse/DBZ-4641[DBZ-4641] https://issues.redhat.com/browse/DBZ-4662[DBZ-4662] https://issues.redhat.com/browse/DBZ-4706[DBZ-4706] https://issues.redhat.com/browse/DBZ-4746[DBZ-4746] https://issues.redhat.com/browse/DBZ-4746[DBZ-4752] https://issues.redhat.com/browse/DBZ-4763[DBZ-4763])
* Corrected a long-running transaction with the PostgreSQL connector (https://issues.redhat.com/browse/DBZ-2306[DBZ-2306])
* Oracle connector stability improvements (https://issues.redhat.com/browse/DBZ-4635[DBZ-4635] https://issues.redhat.com/browse/DBZ-4715[DBZ-4715] https://issues.redhat.com/browse/DBZ-4723[DBZ-4723] https://issues.redhat.com/browse/DBZ-4737[DBZ-4737] https://issues.redhat.com/browse/DBZ-4744[DBZ-4744])

Please refer to the link:/releases/1.9/release-notes#release-1.9.0-beta1[release notes] to learn more about these and further fixes in this release.

As always, a big thank you to everyone contributing to this release:

https://github.com/samagonas[Aidas],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/roldanbob[Bob Roldan],
https://github.com/cab105[Chris Baumbauer],
https://github.com/Naros[Chris Cranford],
https://github.com/chanetd[Dominique Chanet],
https://github.com/gunnarmorling[Gunnar Morling],
https://github.com/harveyyue[Harvey Yue],
https://github.com/sugarcrm-jgminder[Jacob Gminder],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/novotnyJiri[Jiri Novotny],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/jribera-sugarcrm[Josh Ribera],
https://github.com/limer2[Li Mo],
https://github.com/MartinMedek[Martin Medek],
https://github.com/mikekamornikov[Mike Kamornikov],
https://github.com/sazzad16[M Sazzadul Hoque],
https://github.com/zalmane[Oren Elias],
https://github.com/rk3rn3r[René Kerner],
https://github.com/roldanbob[Robert Roldan],
https://github.com/morozov[Sergei Morozov],
https://github.com/snigdhasjg[Snigdhajyoti Ghosh],
https://github.com/vjuranek[Vojtech Juranek],
https://github.com/zxpzlp[Willie Zhu],
https://github.com/y5w[Yang],
https://github.com/yingyingtang-brex[Yingying Tang], and
https://github.com/spicy-sauce[Yossi Shirizli]

== Outlook

With the Beta1 release done,
we are approaching the final phase of the 1.9 release cycle.
Depending on the incoming issue reports,
you can expect a new release in the next few weeks to likely be CR1.

As we turn and look ahead beyond 1.9, you can expect work on Debezium 2.0 to begin in early April 2022.
The current roadmap is to devote 2 full release cycles,
which means you can expect Debezium 2.0 sometime near the end of September 2022.
In the meantime,
you can expect regular updates to Debezium 1.9 throughout this process.

If you are interested in Debezium 2.0, we have collected a number of items in https://issues.redhat.com/browse/DBZ-3899[DBZ-3899] thus far.
This is not an exhaustive list nor has this list been prioritized and scoped to what you can expect in totality of 2.0;
however,
it is what we've identified to be things that either the community or the team feel are actionable tasks for this new major release.
If there is something you would like to see, please take a moment and either raise a discussion on the above Jira ticket or join the discussion on https://groups.google.com/u/1/g/debezium/c/X17AUmQ88-E[this topic] on our mailing list.