---
layout: post
title:  Debezium 2.3.3.Final Released
date:   2023-09-05
tags: [ releases, mongodb, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner ]
author: ccranfor
---

It is my pleasure to announce the immediate release of Debezium *2.3.3.Final*.

This release includes several bug fixes to address regressions, stability, documentation updates.
If you are currently looking to upgrade to the Debezium 2.3.x release stream, we highly recommend you consider using this release.
Let's take a quick look into the regressions and bug fixes.

+++<!-- more -->+++

== Breaking changes

There is currently one breaking change in this release, where the behavior of Debezium 2.3.3.Final changes from the previous release of Debezium 2.3.2.Final.
If you are upgrading from Debezium 2.3.2.Final or any prior version, please review the following breaking changes for details.

=== Oracle connector SCN-based metrics

Oracle tracks a variety of system change number, often called SCN, values in its JMX metrics including `OffsetScn`, `CurrentScn`, `OldestScn`, and `CommittedScn`.
These SCN values are numeric and can often exceed the upper bounds of a `Long` data type, and so Debezium has traditionally exposed these values as `String` s.

Unfortunately, tooling such as Grafana and Prometheus do not work with `String` -based values, and it has been raised on several occasions that the community would like to be able to view these values from metrics gathering frameworks.
With Debezium 2.3.3.Final or later, there is a small behavior change with the these JMX metrics as they are no longer exposed as `String` values but instead are now exposed as `BigInteger` values.

This change in behavior allows tooling such as Grafana and Prometheus to now scrape these values from the JMX beans automatically for reporting and observability stacks.

[NOTE]
====
If you were previously gathering these values for other purposes, be aware they're no longer string-based and should be interpreted as `BigInteger` numerical values moving forward.
====

== Other fixes & improvements

There are several bugfixes and stability changes in this release, some noteworthy are:

* Support PostgreSQL coercion for UUID, JSON, and JSONB data types https://issues.redhat.com/browse/DBZ-6589[DBZ-6589]
* Debezium 2.3.0.Final Missing Kafka Channel Documentation https://issues.redhat.com/browse/DBZ-6688[DBZ-6688]
* Debezium crashes on parsing MySQL DDL statement (specific JOIN) https://issues.redhat.com/browse/DBZ-6724[DBZ-6724]
* ExtractNewDocumentState for MongoDB ignore previous document state when handling delete event's with REWRITE https://issues.redhat.com/browse/DBZ-6725[DBZ-6725]
* Missing or misspelled IDs result in downstream build errors https://issues.redhat.com/browse/DBZ-6754[DBZ-6754]
* When using pgoutput in postgres connector, (+/-)Infinity is not supported in decimal values https://issues.redhat.com/browse/DBZ-6758[DBZ-6758]
* Outbox transformation can cause connector to crash https://issues.redhat.com/browse/DBZ-6760[DBZ-6760]
* Postgres tests for toasted byte array and toasted date array fail with decoderbufs plugin https://issues.redhat.com/browse/DBZ-6767[DBZ-6767]
* MongoDB New Document State Extraction: nonexistent field for add.headers https://issues.redhat.com/browse/DBZ-6774[DBZ-6774]
* Notifications and signals leaks between MBean instances when using JMX channels https://issues.redhat.com/browse/DBZ-6777[DBZ-6777]
* Dbz crashes on parsing MySQL DDL statement (SELECT 1.;) https://issues.redhat.com/browse/DBZ-6780[DBZ-6780]
* Dbz crashed on parsing MySQL DDL statement (SELECT 1 + @sum:=1 AS ss;) https://issues.redhat.com/browse/DBZ-6794[DBZ-6794]
* MySQL DDL parser - REPEAT function not accepted https://issues.redhat.com/browse/DBZ-6803[DBZ-6803]
* Dbz crashes on DDL statement (non Latin chars in variables) https://issues.redhat.com/browse/DBZ-6821[DBZ-6821]
* Not trim the default value for the BIGINT and SMALLINT types when parsing MySQL DDL https://issues.redhat.com/browse/DBZ-6824[DBZ-6824]
* Make partial and multi-response transactions debug level logs https://issues.redhat.com/browse/DBZ-6830[DBZ-6830]
* Oracle test shouldContinueToUpdateOffsetsEvenWhenTableIsNotChanged fails with NPE https://issues.redhat.com/browse/DBZ-6860[DBZ-6860]
* Streaming aggregation pipeline broken for combination of database filter and signal collection https://issues.redhat.com/browse/DBZ-6867[DBZ-6867]

Altogether, a total of https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%202.3.3.Final%20ORDER%20BY%20component%20ASC[19 issues] were fixed for this release.
https://github.com/andreas-ibm[Andreas Martens],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/roldanbob[Bob Roldan],
https://github.com/chrisbeard[Chris Beard],
https://github.com/Naros[Chris Cranford],
https://github.com/vidourem[David Remy],
https://github.com/Fraznist[Emre Akgün],
https://github.com/ericpangiawan[Eric Pangiawan],
https://github.com/ruanhang1993[Hang Ruan],
https://github.com/harveyyue[Harvey Yue],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/twthorn[Thomas Thornton],
https://github.com/vjuranek[Vojtech Juranek], and
https://github.com/vidourem[david remy]!

== Outlook &amp; What's Next?

As the team continues active development of Debezium 2.4, I would expect another maintenance release of Debezium 2.3 later this mont, barring any reported regressions or bugs.

In addition, the Debezium Community Event's agenda and date will be published this week, so keep an eye out for that news.
And finally, we'll be presenting at Kafka Summit 2023 (aka Current 2023) later this upcoming month.
If you're planning to attend and would like to ask the experts, be sure to get in touch with me or anyone on the team and we can plan to meet up and discuss anything related to Debezium and CDC.

As always, if you have any ideas or suggestions, you can also get in touch with us on the https://groups.google.com/g/debezium[mailing list] or our https://debezium.zulipchat.com/login/#narrow/stream/302529-users[chat].
