---
layout: post
title:  Debezium 2.4.0.Alpha1 Released
date:   2023-07-17
tags: [ releases, mongodb, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner ]
author: ccranfor
---

It's been a busy month in Debezium-land, and it's my pleasure to announce the first release of Debezium 2.4 series, *2.4.0.Alpha1*.

This release includes a plethora of changes, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%202.4.0.Alpha1[59 changes] to be exact, that cover a wide range of resolved issues, improvement to stability, new features, and several breaking changes.
Let's dive into each of these and discuss them in more depth.

+++<!- more -->+++

* xref:breaking-changes[Breaking changes]
* xref:new-features[New features]
* xref:other-changes[Other changes]

[id="breaking-changes"]
== Breaking changes

==== MongoDB

The MongoDB connector explicitly preferred to use the secondary under specific scenarios previously.
This explicit usage created problems for users who wanted to connect to the primary node.
Thanks to recent changes (https://issues.redhat.com/browse/DBZ-6521[DBZ-6521]), this is no longer the case and the connection string setting is used instead.

==== Vitess

The Vitess connector's change event structure has been slightly adjusted thanks to changes (https://issues.redhat.com/browse/DBZ-6617[DBZ-6617]).
The change event's `source` information block now includes a new field that identifies the shard the event originated from.

[id="new-features"]
== New Features

==== Offset editor example

Users often express the need to manipulate connector offsets for various reasons.
This can often be very difficult for those who may not be familiar with Kafka's CLI tools or Java if you use Debezium Server.
Thanks to a contribution (https://issues.redhat.com/browse/DBZ-6338[DBZ-6338]) by Nathan Smit, you can now use an editor to manipulate the offsets from the command line or a web-based interface.

Head to our https://github.com/debezium/debezium-examples/tree/main/offset-editor[examples repository] and follow the `README.md` to get started.

==== Error handling

Some Debezium connectors previously used a connector property, `errors.max.retries`.
This property controlled how often a Debezium connector failure exception would be explicitly wrapped in a `RetriableException` but the connector threw the raw exception up to the runtime.
While this may sound similar to Kafka Connect's `errors.retry.timeout`, this effectively gave users a common way to deal with retries across multiple Debezium runtimes, including Kafka Connect, Debezium Server, and Debezium Embedded.

With this release, https://issues.redhat.com/browse/DBZ-6573[DBZ-6573] unifies this behavior making it available to all connectors.

==== Notify initial snapshot progress

Debezium's new notification subsystem provides an easy way to integrate third-party tools and applications with Debezium to gain insight into the ongoing change data capture process, above and beyond the traditional JMX approach.
In 2.4, the notification subsystem now includes the ability to notify you about the status of the ongoing initial snapshot (https://issues.redhat.com/browse?DBZ-6416[DBZ-6416]).

Initial snapshot notifications are emitted with an `aggregatetType` of `Initial Snapshot` and contain a `type` field that exposes the current status of the snapshot.
The possible values include: `STARTED`, `ABORTED`, `PAUSED`, `RESUMED`, `IN_PROGRESS`, `TABLE_SCAN_COMPLETED`, and `COMPLETED`.

==== MySQL improvements

Thanks to a contribution provided by Harvey Yue (https://issues.redhat.com/browse/DBZ-6472[DBZ-6472]), the MySQL connector will use parallelization to generate schema events during its snapshot phase.
This should improve the overall performance when capturing the schema for many tables in your database.
We plan to investigate how this can be extended to other relational connectors.

==== MongoDB improvements

The MongoDB connector continues to see lots of active development.
This release introduces several new features specifically for MongoDB, which include:

* Cluster-wide privileges are no longer necessary when watching a single database or collection (https://issues.redhat.com/browse/DBZ-6182[DBZ-6182]).
* Read preference taken from connection string (https://issues.redhat.com/browse/DBZ-6468[DBZ-6468], https://issues.redhat.com/browse/DBZ-6578[DBZ-6578]).
* Support authentication with TC MongoDB deployments (https://issues.redhat.com/browse/DBZ-6596[DBZ-6596]).

As we continue to make further improvements to the MongoDB connector, please let us  know if there are still rough edges or enhancements that will help streamline its usage.

==== Oracle improvements

Debezium 2.4 supports several new Oracle data types, which include `XML_TYPE` and `RAW` (https://issues.redhat.com/browse/DBZ-3605[DBZ-3605]).
Two new Oracle dependencies were necessary to support XML: `xdb` and `xmlparserv2`.
These dependencies are not redistributable, so they're not included in the connector plugin archive by default, much like the connector's driver.
You must obtain these directly from Maven Central or oracle, just like the driver dependency.

In addition, XML works similarly to `CLOB` and `BLOB` data types; therefore, the connector must be configured with `lob.enabled` set to `true` to ingest XML changes.
We'd love to hear your feedback on this new feature as it's been requested for quite some time.

==== JDBC sink improvements

Thanks to a contribution from Nicholas Fwang (https://issues.redhat.com/browse/DBZ-6595[DBZ-6595]), the JDBC sink connector can now reference values from the change event's `source` information block as a part of the connector's configuration property `table.name.format`.
If you want to reference such fields, simply use `${source.<field-name>}` in the configuration, and the field's value will be used.

In addition, Roman Kudryashov also contributed the ability to resolve a row's primary key from a header defined on the change event (https://issues.redhat.com/browse/DBZ-6602[DBZ-6602]).
To use this new feature, specify the connector configuration property `primary.key.mode` as `record_header`.
If the header value is a primitive type, you will need to define a `primary.key.fields` configuration similar to how you would if the event's record key was a primitive.
If the header value is a `struct` type, all fields of the structure will be used by default, but specifying the `primary.key.fields` property allows you to choose a subset of fields from the header as the key.

==== Spanner improvements

It was possible due to certain conditions that a Spanner connector may not advance from the `START_INITIAL_SYNC` state during initialization.
After investigation by Nancy Xu, a new configuration option was introduced to supply a configurable timeout.
This can be done by adding the following to the connector's configuration:

[source,properties]
----
connector.spanner.task.await.initialization.timeout=<timeout in milliseconds>
----

==== Debezium UI metrics

The Debezium UI project allows you to easily deploy any Debezium connector onto Kafka Connect using a web-based interface.
This release has improved the interface by including several connector metrics (https://issues.redhat.com/browse/DBZ-5321[DBZ-5321]) on the main connector listing view.
We'd love your feedback on this change and welcome any suggestions on other metrics you may find useful.

[id="other-changes"]
== Other fixes

In addition, there were quite a number of stability and bug fixes that made it into this release.
These include the following:

* Mysql connector fails to parse statement FLUSH FIREWALL_RULES https://issues.redhat.com/browse/DBZ-3925[DBZ-3925]
* Add the API endpoint to expose running connector metrics https://issues.redhat.com/browse/DBZ-5359[DBZ-5359]
* Display critical connector metrics https://issues.redhat.com/browse/DBZ-5360[DBZ-5360]
* Snapshot result not saved if LAST record is filtered out https://issues.redhat.com/browse/DBZ-5464[DBZ-5464]
* Define and document schema history topic messages schema https://issues.redhat.com/browse/DBZ-5518[DBZ-5518]
* Align query.fetch.size across connectors https://issues.redhat.com/browse/DBZ-5676[DBZ-5676]
* Upgrade to Apache Kafka 3.5.0 https://issues.redhat.com/browse/DBZ-6047[DBZ-6047]
* Remove downstream related code from UI Frontend code https://issues.redhat.com/browse/DBZ-6394[DBZ-6394]
* Make Signal actions extensible https://issues.redhat.com/browse/DBZ-6417[DBZ-6417]
* CloudEventsConverter throws static error on Kafka Connect 3.5+ https://issues.redhat.com/browse/DBZ-6517[DBZ-6517]
* Dependency io.debezium:debezium-testing-testcontainers affects logback in tests https://issues.redhat.com/browse/DBZ-6525[DBZ-6525]
* Cleanup duplicate jobs from jenkins https://issues.redhat.com/browse/DBZ-6535[DBZ-6535]
* Implement sharded MongoDB ocp deployment and integration tests  https://issues.redhat.com/browse/DBZ-6538[DBZ-6538]
* Batches with DELETE statement first will skip everything else https://issues.redhat.com/browse/DBZ-6576[DBZ-6576]
* Oracle unsupported DDL statement - drop multiple partitions https://issues.redhat.com/browse/DBZ-6585[DBZ-6585]
* Only Struct objects supported for [Header field insertion], found: null https://issues.redhat.com/browse/DBZ-6588[DBZ-6588]
* Support PostgreSQL coercion for UUID, JSON, and JSONB data types https://issues.redhat.com/browse/DBZ-6589[DBZ-6589]
* MySQL parser cannot parse CAST AS dec https://issues.redhat.com/browse/DBZ-6590[DBZ-6590]
* Refactor retry handling in Redis schema history https://issues.redhat.com/browse/DBZ-6594[DBZ-6594]
* Excessive Log Message 'Marking Processed Record for Topic' https://issues.redhat.com/browse/DBZ-6597[DBZ-6597]
* Support for custom tags in the connector metrics https://issues.redhat.com/browse/DBZ-6603[DBZ-6603]
* Fixed DataCollections for table scan completion notification https://issues.redhat.com/browse/DBZ-6605[DBZ-6605]
* Oracle connector is not recoverable if ORA-01327 is wrapped by another JDBC or Oracle exception https://issues.redhat.com/browse/DBZ-6610[DBZ-6610]
* Fatal error when parsing Mysql (Percona 5.7.39-42) procedure https://issues.redhat.com/browse/DBZ-6613[DBZ-6613]
* Build of Potgres connector fails when building against Kafka 2.X https://issues.redhat.com/browse/DBZ-6614[DBZ-6614]
* Upgrade postgresql driver to v42.6.0 https://issues.redhat.com/browse/DBZ-6619[DBZ-6619]
* MySQL ALTER USER with RETAIN CURRENT PASSWORD fails with parsing exception https://issues.redhat.com/browse/DBZ-6622[DBZ-6622]
* Upgrade Quarkus to 3.2.0.Final https://issues.redhat.com/browse/DBZ-6626[DBZ-6626]
* Inaccurate documentation regarding additional-condition https://issues.redhat.com/browse/DBZ-6628[DBZ-6628]
* Oracle connection SQLRecoverableExceptions are not retried by default https://issues.redhat.com/browse/DBZ-6633[DBZ-6633]
* Upgrade kcctl to 1.0.0.Beta3 https://issues.redhat.com/browse/DBZ-6642[DBZ-6642]
* Cannot delete non-null interval value https://issues.redhat.com/browse/DBZ-6648[DBZ-6648]
* Upgrade gRPC to 1.56.1 https://issues.redhat.com/browse/DBZ-6649[DBZ-6649]
* ConcurrentModificationException thrown in Debezium 2.3 https://issues.redhat.com/browse/DBZ-6650[DBZ-6650]
* Dbz crashes on parsing Mysql Procedure Code (Statement Labels) https://issues.redhat.com/browse/DBZ-6651[DBZ-6651]
* CloudEvents converter is broken for JSON message deserialization https://issues.redhat.com/browse/DBZ-6654[DBZ-6654]
* Vitess: Connector fails if table name is a mysql reserved word https://issues.redhat.com/browse/DBZ-6656[DBZ-6656]
* Junit conflicts cause by test-containers module using transitive Junit5 from quarkus https://issues.redhat.com/browse/DBZ-6659[DBZ-6659]
* Disable Kafka 2.x CRON trigger https://issues.redhat.com/browse/DBZ-6667[DBZ-6667]

Altogether, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%202.4.0.Alpha1%20ORDER%20BY%20component%20ASC[59 issues] were fixed for this release.
A big thank you to all the contributors from the community who worked on this release:
https://github.com/adamstrickland[Adam Strickland],
https://github.com/aozmen121[Alisa Houskova],
https://github.com/AnatolyPopov[Anatolii Popov],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/maxant[Ant Kutschera],
https://github.com/Artgyk[Artur Gukasian],
https://github.com/bdbene[Balint Bene],
https://github.com/roldanbob[Bob Roldan],
https://github.com/Naros[Chris Cranford],
https://github.com/harveyyue[Harvey Yue],
https://github.com/blcksrx[Hossein Torabi],
https://github.com/indraraj[Indra Shukla],
https://github.com/nicholas-fwang[Inki Hwang],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/MartinMedek[Martin Medek],
https://github.com/nancyxu123[Nancy Xu],
https://github.com/obabec[Ondrej Babec],
https://github.com/rk3rn3r[René Kerner],
https://github.com/jaegwonseo[Seo Jae-kwon],
https://github.com/smiklosovic[Stefan Miklosovic],
https://github.com/twthorn[Thomas Thornton], and
https://github.com/vjuranek[Vojtech Juranek]!

== What's next?

This initial release of Debezium 2.4 is already packed with lots of new features and the team is only getting started.
Looking at our https://debezium.io/roadmap[road map], we've already tackled nearly half of our plans for 2.4, but much still remains including:

* Single message transforms for TimescaleDB and Timestamps
* OpenLogReplicator ingestion for Oracle
* Ad-hoc blocking snapshots
* Parallelization of Debezium Embedded
* Parallel incremental snapshots for MongoDB
* Further improvements to Debezium UI

We intend to stick to our approximate two week cadence, so expect Alpha2 at the start of August.
Until then, please be sure to get in touch with us on the https://groups.google.com/g/debezium[mailing list] or our https://debezium.zulipchat.com/login/#narrow/stream/302529-users[chat] if you have any ideas or suggestions.
