---
layout: post
title:  Debezium 2.3.0.Beta1 Released
date:   2023-05-29
tags: [ releases, mongodb, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner ]
author: ccranfor
---

It's my pleasure to announce the next release of the Debezium 2.3 series, *2.3.0.Beta1*!

While this release focuses primarily on bug fixes and stability improvements, there are some new improvements with the PostgreSQL connector and the new notification and channels subsystem.
In addition, there are also some compatibility breaking changes.

This release contains changes for https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%202.3.0.Beta1%20ORDER%20BY%20issuetype%20DESC[22 issues],
so lets take a moment and dive into the new features and any potential bug fixes or breaking changes that are noteworthy!

+++<!-- more -->+++

== Breaking Changes

Debezium recently introduced the JDBC storage module that allows you to store offsets and schema history data inside a relational database.
The JDBC storage module used UTF-16 as its default encoding; however, most databases use UTF-8.
This release of Debezium aligns the JDBC storage module's encoding to use UTF-8 moving forward.

== PostgreSQL Replica Identity Changes

Debezium 2.3 introduces a new PostgreSQL connector feature called "Autoset Replica Identity".

Replica identity is PostgreSQL's way to identify what columns are captured in the database transaction logs for inserts, updates, and deletes.
This new feature allows configuring a table's replica identity via connector configuration and delegating the responsibility of setting this configuration to the connector at start-up.

The new configuration option, `replica.identity.autoset.values`, specifies a comma-separated list of table and replica identity tuples.
If the table already has a given replica identity, the identity will be overwritten to match what is specified in this configuration if the table is included.
PostgreSQL supports several replica identity types, more information on these can be found in the https://debezium.io/documentation/reference/2.3/connectors/postgresql.html#postgresql-replica-identity[documentation].

When specifying the `replica.identity.autoset.values`, the value is a comma-separated list of values where each element uses the format of `<fully-qualified-table-name>:<replica-identity>`.
An example is shown below where two tables are configured to have full replica identity:

[source,json]
----
{
  "replica.identity.autoset.values": "public.table1:FULL,public.table2:FULL"
}
----

Be mindful that if the user account used by the connector does not have the appropriate database permissions to set a table's replica identity, the use of this feature will result in a failure.
In the event of a failure due to permissions, you must make sure the proper replica identity is set manually using a database account with the right permissions.

== Correlate Incremental Snapshot notification ids

Debezium 2.3 introduces a new notification and channels subsystem.
This subsystem allows you to send a signal via a variety of channels that include the filesystem, Kafka topic, and database table out of the box; however, the feature is extendable.
In addition, this subsystem also includes the ability to send notifications about the status of the initial snapshots and incremental snapshots if they're used.
These notifications can help facilitate an easier line of communication between Debezium and other third-party systems that may need to know when an incremental or traditional snapshot has finished and whether it finished successfully or not.

In this release, the notification and channels subsystem has been improved to correlate the signal to the notification.
So when you send a signal and it is consumed by Debezium, any notification that is raised will contain a reference to the signal, allowing any third-party or external process to know precisely which signal the notification references.

This should help close the gap in distribution communications across applications or processes relying on the new notification and channel subsystem.

== Other fixes

There were quite a number of bugfixes and stability changes in this release, some noteworthy are:

* Debezium Server stops sending events to Google Cloud Pub/Sub https://issues.redhat.com/browse/DBZ-5175[DBZ-5175]
* Snapshot step 5 - Reading structure of captured tables time too long  https://issues.redhat.com/browse/DBZ-6439[DBZ-6439]
* Oracle parallel snapshots do not properly set PDB context when using multitenancy https://issues.redhat.com/browse/DBZ-6457[DBZ-6457]
* [MariaDB] Add support for userstat plugin keywords https://issues.redhat.com/browse/DBZ-6459[DBZ-6459]
* Debezium Server cannot recover from Google Pub/Sub errors https://issues.redhat.com/browse/DBZ-6461[DBZ-6461]
* Db2 connector can fail with NPE on notification sending https://issues.redhat.com/browse/DBZ-6485[DBZ-6485]
* BigDecimal fails when queue memory size limit is in place https://issues.redhat.com/browse/DBZ-6490[DBZ-6490]
* ORACLE table can not be captrued, got runtime.NoViableAltException https://issues.redhat.com/browse/DBZ-6492[DBZ-6492]
* Signal poll interval has incorrect default value https://issues.redhat.com/browse/DBZ-6496[DBZ-6496]
* Oracle JDBC driver 23.x throws ORA-18716 - not in any time zone https://issues.redhat.com/browse/DBZ-6502[DBZ-6502]
* Alpine postgres images should use llvm/clang 15 explicitly https://issues.redhat.com/browse/DBZ-6506[DBZ-6506]
* ExtractNewRecordState SMT in combination with HeaderToValue SMT results in Unexpected field name exception https://issues.redhat.com/browse/DBZ-6486[DBZ-6486]

Altogether, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%202.3.0.Beta1%20ORDER%20BY%20component%20ASC[22 issues] were fixed for this release.
A big thank you to all the contributors from the community who worked on this release:
https://github.com/angsdey2[Angshuman Dey],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/Naros[Chris Cranford],
https://github.com/harveyyue[Harvey Yue],
https://github.com/ismailsimsek[Ismail Simsek],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/joschi[Jochen Schalanda],
https://github.com/subkanthi[Kanthi Subramanian],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/MartinMedek[Martin Medek], and
https://github.com/vjuranek[Vojtech Juranek]!

== What's next?

With Debezium 2.3 being released under a condensed schedule, you can expect the next CR1 release within the next 1-2 weeks.
The plan is to release Debezium 2.3.0.Final in the middle of June and for the team to begin preparation on Debezium 2.4.

As we begin to prepare to move toward Debezium 2.4, we would love to hear your feedback or suggestions.
The roadmap will be updated in the coming week, so please be sure to get in touch with us on the https://groups.google.com/g/debezium[mailing list] or our https://debezium.zulipchat.com/login/#narrow/stream/302529-users[chat] if you have any ideas or suggestions.

Until next time...