---
layout: post
title:  Debezium 2.1.2.Final Released
date:   2023-01-26
tags: [ releases, mongodb, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox ]
author: ccranfor
---

The Debezium release cadence is in full swing as I'm excited to announce Debezium *2.1.2.Final*!

This release focuses primarily on bug fixes and stability; and it is the recommended update for all users from earlier versions.
This release contains https://issues.redhat.com/issues/?jql=project+%3D+DBZ+AND+fixVersion+%3D+2.1.2.Final[28 resolved issues],
so let's take a moment and discuss a critical breaking change.

+++<!-- more -->+++

== Breaking Change

An edge case was reported in https://issues.redhat.com/browse/issues/DBZ-5996[DBZ-5996] where if a temporal column used `ZonedTimestamp` and if the column's value had `0` micro or nanoseconds, rather than emitting the value as `2023-01-19T12:30:00.123000Z`, the value would be emitted in a truncated way as `2023-01-19T12:30:00.123Z`.
This could lead to other issues with converters used in the event pipeline when the output from that column could be formatted inconsistently.

In order to remedy the edge case, the `ZonedTimestamp` implementation will now pad the fraction-based seconds value of the column's value to the length/scale of the source database column.
Using the example above of a `TIMESTAMP(6)` MySQL column type, the emitted value will now properly reflect a value of `2023-01-19T12:30:00.123000Z`.

While this change in behavior is likely to have minimal impact to most users, we wanted to bring attention to it in the event that you've perhaps used other means to handle this edge case in your pipelines.
If you have, you should be able to rely on Debezium to emit the value consistently, even when the fraction-based seconds is `0`.

== Other changes

A few noteworthy bug fixes and stability improvements include:

* Data type conversion failed for mysql bigint https://issues.redhat.com/browse/DBZ-5798[DBZ-5798]
* Oracle cannot undo change https://issues.redhat.com/browse/DBZ-5907[DBZ-5907]
* Truncate records incompatible with ExtractNewRecordState https://issues.redhat.com/browse/DBZ-5966[DBZ-5966]
* Computed partition must not be negative https://issues.redhat.com/browse/DBZ-5967[DBZ-5967]
* NPE in execute snapshot signal with exclude.tables config on giving wrong table name https://issues.redhat.com/browse/DBZ-5988[DBZ-5988]
* There is a problem with postgresql connector parsing the boundary value of money type https://issues.redhat.com/browse/DBZ-5991[DBZ-5991]
* Nullable columns marked with "optional: false" in DDL events https://issues.redhat.com/browse/DBZ-6003[DBZ-6003]
* Vitess: Handle the shard list difference between current db shards and persisted shards https://issues.redhat.com/browse/DBZ-6011[DBZ-6011]
* Postgres LSN check should honor event.processing.failure.handling.mode https://issues.redhat.com/browse/DBZ-6012[DBZ-6012]
* Enhance the Spanner connector by adding features and/or solving bugs https://issues.redhat.com/browse/DBZ-6014[DBZ-6014]
* DDL statement with TokuDB engine specific "CLUSTERING KEY" couldn't be parsed https://issues.redhat.com/browse/DBZ-6016[DBZ-6016]
* DDL parse fail for role revoke with "user-like" role name https://issues.redhat.com/browse/DBZ-6019[DBZ-6019]
* DDL parse fail for ALTER USER x DEFAULT ROLE y; https://issues.redhat.com/browse/DBZ-6020[DBZ-6020]
* Offsets are not flushed on connect offsets topic when encountering an error on Postgres connector https://issues.redhat.com/browse/DBZ-6026[DBZ-6026]
* Unexpected format for TIME column: 8:00 https://issues.redhat.com/browse/DBZ-6029[DBZ-6029]
* Oracle does not support compression/logging clauses after an LOB storage clause https://issues.redhat.com/browse/DBZ-6031[DBZ-6031]
* Debezium is logging the full message along with the error https://issues.redhat.com/browse/DBZ-6037[DBZ-6037]
* Improve resilience during internal schema history recovery from Kafka https://issues.redhat.com/browse/DBZ-6039[DBZ-6039]

Please refer to the link:/releases/2.1/release-notes#release-2.1.2-final[release notes] to learn more about all fixed bugs, update procedures, etc.

Many thanks to the following individuals from the community who contributed to Debezium 2.1.2.Final:
Akshansh Jain,
https://github.com/akanimesh7[Animesh Kumar],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/roldanbob[Bob Roldan],
https://github.com/Naros[Chris Cranford],
https://github.com/harveyyue[Harvey Yue],
https://github.com/HenryCaiHaiying[Henry Cai],
https://github.com/indraraj[Indra Shukla],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/Lucascanna[Luca Scannapieco],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/dude0001[Mark Lambert],
https://github.com/morozov[Sergei Morozov],
https://github.com/vjuranek[Vojtech Juranek],
https://github.com/yoheimuta[Yohei Yoshimuta], and
https://github.com/yoheimuta[yohei yoshimuta]!

== Outlook, What's next?

Debezium 2.1 will continue to receive bug fix and maintenance changes throughout this quarter.
I expect there will be at least one additional release likely toward the middle or late February or March timeframe as we begin to wrap up up the work on Debezium 2.2.

Regarding Debezium 2.2, we intend to deliver another Alpha build in the coming weeks.
We have lots of features still in the works, including the JDBC Sink Connector, configurable signal channels, new message transformations, and much more.

Stay tuned, and until then ...
