---
layout: post
title:  Debezium 2.4.0.CR1 Released
date:   2023-09-22
tags:   [ releases, mongodb, mysql, postgres, sqlserver, caassandra, oracle, db2, vitess, outbox, spanner ]
author: ccranfor
---

As the summer concludes for us in the north and we await the autumn colors, the team has been busy preparing for the next major release of Debezium 2.4.
It's my pleasure to announce today that we are nearly there with the release of Debezium **2.4.0.CR1**.

The focus for this release is primarily on stability; however, we do have a few new last minute addititons that we should highlight, so let's dive right in, shall we?!

+++<!- more ->+++

== Breaking changes

The community led Vitess connector was retrying only a subset of errors by default.
This behavior has been changed and now only explicitly defined errors are not retried.  For more details, please see https://issues.redhat.com[DBZ-6944].

== New Features

=== MongoDB parallel incremental snapshots

Since the introduction of incremental snapshots back in Debezium 1.x, the process to incremental snapshot existing data while concurrently capturing changes from a database transaction has been a single-threaded activity.
It's not uncommon when adding new features to focus on the basics and build upon that foundation, which is precisely what has happened with MongoDB.

In Debezium 2.4, we are taking the first steps to add parallel support to incremental snapshots with the MongoDB connector by reading multiple chunks in parallel.
This should allow faster throughput at the cost of memory while the chunks are being collected, sorted, and deduplication occurs against the transaction log capture data set.
Thanks to https://github.com/xidui[Yue Wang] for starting this effort in https://issues.redhat.com/browse/DBZ-6518[DBZ-6518], it's most definitely something we are looking to explore for the relational connectors in an upcoming Debezium release.

=== PostgreSQL 16 support

PostgreSQL announced the immediate release for PostgreSQL 16 just over a week ago, and we're pleased to announce that Debezium 2.4 will support that release.

[NOTE]
====
PostgreSQL 16 introduces logical replication from standby servers; however, this feature has not yet been tested by Debezium and will be a feature introduced in a later build of Debezium.
For now, logical replication remains only supported via the primary.
====


=== Google Spanner GKE workload identity support

Google Kubernetes Engine (GKE) supports identity workloads, allowing you to use a more secure authentication mechanism than the traditional JSON-based keys.
In Debezium 2.4, when no JSON key is explicitly set, the Spanner connector will now automatically default to GKE workload identity authentication.
Thanks to https://github.com/laughingman7743[laughingman7743] for this effort as a part of https://issues.redhat.com/browse/DBZ-6885[DBZ-6885].

== Other Fixes

* Ad-hoc blocking snaps trigger emits schema changes of all tables https://issues.redhat.com/browse/DBZ-6828[DBZ-6828]
* When the start_scn corresponding to the existence of a transaction in V$TRANSACTION is 0, log mining starts from the oldest scn when the oracle connector is started for the first time https://issues.redhat.com/browse/DBZ-6869[DBZ-6869]
* Ensure that the connector can handle rebalance events robustly https://issues.redhat.com/browse/DBZ-6870[DBZ-6870]
* OpenLogReplicator confirmation can resend or omit events on restarts https://issues.redhat.com/browse/DBZ-6895[DBZ-6895]
* ExtractNewRecordState's schema cache is not updated with arrival of the ddl change event https://issues.redhat.com/browse/DBZ-6901[DBZ-6901]
* Misleading Debezium error message when RDI port is not specified in application.properties https://issues.redhat.com/browse/DBZ-6902[DBZ-6902]
* Generting protobuf files to target/generated-sources breaks build https://issues.redhat.com/browse/DBZ-6903[DBZ-6903]
* Clean log printout in Redis Debezium Sink https://issues.redhat.com/browse/DBZ-6908[DBZ-6908]
* Values being omitted from list of JSON object https://issues.redhat.com/browse/DBZ-6910[DBZ-6910]
* fix logger named https://issues.redhat.com/browse/DBZ-6935[DBZ-6935]
* MySql connector get NPE when snapshot.mode is set to never and signal data collection configured https://issues.redhat.com/browse/DBZ-6937[DBZ-6937]
* Sanity check / retry for redo logs does not work per Oracle RAC thread https://issues.redhat.com/browse/DBZ-6938[DBZ-6938]
* Drop events has wrong table changes information https://issues.redhat.com/browse/DBZ-6945[DBZ-6945]
* Remove spaces from Signal and Notification MBean's ObjectName https://issues.redhat.com/browse/DBZ-6957[DBZ-6957]

Altogether, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%202.4.0.CR1%20ORDER%20BY%20component%20ASC[20 issues] were fixed for this release.
A big thank you to all the contributors from the community who worked on this release:
https://github.com/BigGillyStyle[Andy Pickler],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/brenoavm[Breno Moreira],
https://github.com/Naros[Chris Cranford],
https://github.com/harveyyue[Harvey Yue],
https://github.com/indraraj[Indra Shukla],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/nancyxu123[Nancy Xu],
https://github.com/nirolevy[Nir Levy],
https://github.com/obabec[Ondrej Babec],
https://github.com/rk3rn3r[René Kerner],
https://github.com/eizners[Sergey Eizner],
https://github.com/twthorn[Thomas Thornton],
https://github.com/wuzhenhua01[Wu Zhenhua],
Zheng Wang,
https://github.com/laughingman7743[laughingman7743], and
https://github.com/tisonkun[tison]!

== Outlook and What's next?

We're now at the junction where we begin to set our vision on Debezium 2.5 and what lies ahead.
We recently held our first Community Meeting and discussed a number of our 2.5 roadmap ideas, some of which include:

* Parallel incremental snapshots for relational connectors.
* Improved MongoDB support for BSONDocument exceeding 16MB.
* Db2 support on z/OS and iSeries platforms.
* Batch support in the JDBC sink connector.
* Parallelization of tasks and other Debezium Engine internals.
* Preview of MariaDB and Oracle 23 support

For more details, please check out our https://debezium.io/roadmap[road map] for all upcoming details around Debezium 2.5 and beyond.

Additionally, Debezium will be at https://www.confluent.io/events/current/[Current 2023] next week.
If you are attending, be sure to stop by the Ask-The-Experts session on Wednesday at 2:30PM to catch a sesssion on Debezium and Kafka.
Additionally, be sure to check out the sponsored session on Wednesday at 4:30PM to find out just how easy it is to deploy data pipelines from the edge to the cloud using open-source projects such as Debezium, Strimzi, Apicurio, and Kubernetes.

As always, if you have any questions, suggestions, or feedback, please reach out to us on our https://groups.google.com/g/debezium[mailing list] or https://debezium.zulipchat.com/login/#narrow/stream/302529-users[chat].
We always enjoy hearing what you have to share.
Until next time, be safe.



