---
layout: post
title:  Debezium 2.4.1.Final Released
date:   2023-11-16
tags: [ releases, mongodb, mysql, mariadb, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner ]
author: ccranfor
---

As the year starts to come to a close, I am happy to announce the first maintenance release for the Debezium 2.4 release series, Debezium *2.4.1.Final*.

While our maintenance releases focus primarily on bug fixes and stability improvements, there are a few new features we back ported from our most recent Debezium 2.5 development series.
All these new features focus on the Debezium Operator for Kubernetes, so lets take a quick deep dive into those details.
As always, you can find the complete list of changes for this release in the link:/releases/2.4/release-notes[release notes].

+++<!-- more -->+++

== Debezium Operator - Specify image pull secrets

There may be situations where the Debezium Server image may not contain all the necessary components for your chosen deployment, such as proprietary drivers that aren't included the image.
In such cases, it's common practice for users to construct their own image from the base image to include such files.
It's then common to place that newly created image onto an image container registry where you may require credentials to fetch that image for your deployment.
Debezium 2.4.1.Final introduces the ability to specify those credentials directly as a part of your CRD. (https://issues.redhat.com/browse/DBZ-6962[DBZ-6962])

.An example CRD that now includes the new `imagePullSecrets` configuration:
[source,yaml]
----
runtime:
  templates:
    pod:
      imagePullSecrets:
      - name: debezium-server-secret
----

== Debezium Operator - Specify container resources

With Debezium Server on Kubernetes, you may want to limit the resources that your pod consumes, particularly if you are streaming large volumes of data regularly.
Debezium 2.4.1.Final introduces the ability to specify these constraints as part  of the Pod template as well. (https://issues.redhat.com/browse/DBZ-7052[DBZ-7052])

.An example CRD specifying Pod resource constraints
[source,yaml]
----
runtime:
  templates:
    container:
      resources:
        limits:
          memory: "64Mi"
          cpu: "250m"
        requests:
          memory: "128Mi"
          cpu: "500m"
----

Please see the https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/[Kubernetes documentation] for more details on the supported properties.

== Debezium Operator metrics endpoint improvements

Debezium 2.4.1.Final introduces a new JMX metrics endpoint for better metrics gathering and exposure with the Debezium Operator and Debezium Server. (https://issues.redhat.com/browse/DBZ-7053[DBZ-7053])
This feature can be enabled in the custom resource definition by simply adding the following lines:

[source,yaml]
----
spec:
  runtime:
    jmx:
      enabled: true
      port: 1099
----

The endpoint currently does not support authentication nor SSL but those are on the road-map and will be added as a supplemental change to this feature in a future release.


[id="other-changes"]
== Other fixes

In addition, there were quite a number of stability and bug fixes that made it into this release.
These include the following:

* Oracle RAC throws ORA-00310: archive log sequence required https://issues.redhat.com/browse/DBZ-5350[DBZ-5350]
* oracle missing CDC data https://issues.redhat.com/browse/DBZ-5656[DBZ-5656]
* Missing oracle cdc records https://issues.redhat.com/browse/DBZ-5750[DBZ-5750]
* Multiple debezium:offsets Redis clients https://issues.redhat.com/browse/DBZ-6952[DBZ-6952]
* Wrong case-behavior for non-avro column name in sink connector https://issues.redhat.com/browse/DBZ-6958[DBZ-6958]
* Missing events from Oracle 19c https://issues.redhat.com/browse/DBZ-6963[DBZ-6963]
* Handle properly bytea field for jdbc sink to postgresql https://issues.redhat.com/browse/DBZ-6967[DBZ-6967]
* Debezium jdbc sink process truncate event failure https://issues.redhat.com/browse/DBZ-6970[DBZ-6970]
* Debezium jdbc sink should throw not supporting schema change topic exception https://issues.redhat.com/browse/DBZ-6990[DBZ-6990]
* OLM bundle version for GA releases is invalid https://issues.redhat.com/browse/DBZ-6994[DBZ-6994]
* Further refactoring to correct downstream rendering of incremental snapshots topics https://issues.redhat.com/browse/DBZ-6997[DBZ-6997]
* ALTER TABLE fails when adding multiple columns to JDBC sink target https://issues.redhat.com/browse/DBZ-6999[DBZ-6999]
* Invalid Link to zulip chat in CSV metadata https://issues.redhat.com/browse/DBZ-7000[DBZ-7000]
* Make sure to terminate the task once connectivity is lost to either the rebalance or sync topic https://issues.redhat.com/browse/DBZ-7001[DBZ-7001]
* Missing .metadata.annotations.repository field in CSV metadata https://issues.redhat.com/browse/DBZ-7003[DBZ-7003]
* Single quote replication and loss of data https://issues.redhat.com/browse/DBZ-7006[DBZ-7006]
* Oracle connector: Payload size over 76020 bytes are getting truncated https://issues.redhat.com/browse/DBZ-7018[DBZ-7018]
* Use optional schema for Timezone Converter tests https://issues.redhat.com/browse/DBZ-7020[DBZ-7020]
* DDL statement couldn't be parsed https://issues.redhat.com/browse/DBZ-7030[DBZ-7030]
* Debezium Embedded Infinispan Performs Slowly https://issues.redhat.com/browse/DBZ-7047[DBZ-7047]
* Update operator dependencies and add qosdk platform bom https://issues.redhat.com/browse/DBZ-7048[DBZ-7048]
* Field exclusion does not work with events of removed fields https://issues.redhat.com/browse/DBZ-7058[DBZ-7058]
* Consolidate resource labels and annotations https://issues.redhat.com/browse/DBZ-7064[DBZ-7064]
* Allow DS JMX to use username-password authentication on k8 https://issues.redhat.com/browse/DBZ-7087[DBZ-7087]
* Debezium crashes on parsing MySQL DDL statement (specific INSERT) https://issues.redhat.com/browse/DBZ-7119[DBZ-7119]
* Debezium-ddl-parser crashes on parsing MySQL DDL statement (specific UNION) https://issues.redhat.com/browse/DBZ-7140[DBZ-7140]

Altogether, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%202.4.1.Final%20ORDER%20BY%20component%20ASC[30 issues] were fixed for this release.
A big thank you to all the contributors from the community who worked on this release:
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/bpaquet[Bertrand Paquet],
https://github.com/roldanbob[Bob Roldan],
https://github.com/Naros[Chris Cranford],
https://github.com/vidourem[David Remy],
https://github.com/dtseiler[Don Seiler],
https://github.com/harveyyue[Harvey Yue],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/nancyxu123[Nancy Xu],
https://github.com/roldanbob[Robert Roldan],
https://github.com/eizners[Sergey Eizner],
https://github.com/twthorn[Thomas Thornton],
https://github.com/vjuranek[Vojtech Juranek], and
https://github.com/adityajain311995[adityajain311995]!

[id="whats-next"]
== What's next?

As mentioned in our last release announcement, the cadence for Debezium 2.5 is condensed due to the upcoming holiday season.
The next preview release for Debezium 2.5 will be our first and most likely only Beta release, later this month.
We plan to conclude the Debezium 2.5 release series with a release candidate most likely the first week of December and a final release mid-way through December, just before the holiday break.

We are also moving forward on our review and process for MariaDB support.
There will likely be some news on this in the coming weeks as we begin to find a path forward around this particular advancement.
The team is also continuing the work on the Debezium Engine improvements, and much more.
You can find all the details for our continued plans for Debezium 2.5 on our link:/roadmap[roadmap].

As always, please be sure to get in touch with us on the https://groups.google.com/g/debezium[mailing list] or https://debezium.zulipchat.com/login/#narrow/stream/302529-users[Zulip chat] if you have questions or feedback.
Until next time, stay warm out there!
