---
layout: post
title:  Debezium signaling and notifications - [part 1]
date:   2023-06-07 11:11:11 +0100
tags: [ debezium, features, notifications, signaling, integration ]
author: mfvitale
---

In today's interconnected world of software applications and systems, the ability to seamlessly integrate with other products is crucial for building robust and efficient solutions.

One of the key challenges in building integrated software ecosystems is establishing effective communication channels between different components and services.

In this context, Debezium now offers comprehensive support for signaling and notification, enabling seamless integration with other product. By leveraging Debezium's signaling and notification mechanisms, users can easily orchestrate actions and stay informed about the status and progress of Debezium.

Debezium signal has been re-designed to be extensible to provide an easy way to add more signaling channels. Furthermore, new out-of-the-box channels has been developed.

We have also added a way to be notified about what is going on inside Debezium through the notification mechanism. Even in this case we provide out-of-the-box channels and an easy way to add more.

Let's explore the different types of signaling and notification channels available in Debezium, along with their functionalities and benefits.

+++<!-- more -->+++

== Signaling in Debezium
Signaling in Debezium refers to the mechanism through which users can trigger specific actions within the product. It allows users to interact with Debezium and control some behaviors. One notable use case of signaling is the execution of incremental snapshots, which permits to start an ad-hoc snapshot of database.

Debezium provides different signaling channels through which users can send signals to the platform. Let's explore the available signaling channels:

Signaling through Database Tables::
In earlier versions of Debezium, signaling was only achieved by using a dedicated database table. Users can insert specific records into this table to trigger actions in Debezium connectors. For example, to initiate an incremental snapshot, a record would be inserted into a designated signaling table, prompting the connector to perform the snapshot operation.

Signaling through Kafka Topics::
In earlier versions of Debezium, there was available signaling thorough a configurable Kafka topic. The limitation was that it was only available for MySQL with read-only access and GTIDs enabled.
Starting from Debezium version 2.3, Kafka signaling can be used as a signaling mechanism across all connectors. This enhancement provides a more unified approach to signaling, simplifying the integration and allowing for consistent signaling across different databases. Now, users can send signaling messages to a specific Kafka topic, and Debezium will process the signals accordingly.
Using Kafka for signaling offers several advantages. Firstly, it aligns with the event-driven nature of Debezium, making it a natural fit for managing signals. Additionally, it enables sending signal more easily for user that doesn't have direct access to database.

[NOTE]
===============================
An important note is that even using Kafka for trigger signal, the incremental snapshot feature still requires the presence of the signaling table, expect for MySQL with GTIDs enabled.
===============================

Signaling through File::
Thanks to our exiting community you can also trigger signals through a simple file. This can be suitable for example when you are not relying on Kafka connect using Debezium server, and you cannot use database signaling.

Signaling through Java Management Extensions (JMX)::
With this channel you can send signal calling the signal operation exposed through a dedicated MBean. You can do it by connecting to the MBeanServer with your preferred client. A dedicated post about this feature will follow.

Signaling through custom channel::
As said before, in this release we revisited the signaling mechanism to be extensible. You can provide your own implementation and use it with minimal configuration. A dedicated post about this feature will follow.

== Notification in Debezium:
Notification, on the other hand, focuses on obtaining status information and progress updates about Debezium. It provides insights into the execution and completion of tasks such as initial snapshots or incremental snapshots. Debezium generates notifications to keep users informed about the progress of these tasks, facilitating monitoring and decision-making based on real-time information. By leveraging the notification functionality, users can track the state of Debezium and take appropriate actions based on the received notifications.

Debezium offers different channels through which notifications can be delivered. Let's explore the out-of-the-box channels:

Notification through Sink channel::
This implementation sends notifications through the Connect API to a configured topic. Users can enable this channel and specify the topic name. By publishing notifications to the specified topic, Debezium allows users to consume and process the notifications in a way that suits their needs. Since `Sink` is not technology dependent (i.e. Kafka) it can be also used with Debezium server and its available sinks.

Notification through logs::
This simple implementations permits to append notifications to the log. Enabling this channel ensures that notifications become part of the application's log stream. This facilitates easy access to notifications for monitoring, debugging, and analysis purposes. Notifications are readily available within the log files, providing a convenient way to track Debezium's progress.

Notifications through Java Management Extensions (JMX)::
Enabling this notification channel, Debezium exposes a dedicated MBean with a specific attributes that contains the list of generated notifications. In addition, JMX notifications are exposed as well. Also for this topic, a dedicated post will follow.

Notification through custom channel::
Debezium's notification mechanism is designed to be extensible, enabling users to implement custom channels for delivering notifications in a manner that aligns with their environment. We will cover how to provide a custom notification channel in a dedicated post.

== Conclusion
Signaling and notification are now an important feature of Debezium. Signaling empowers users to interact with Debezium and trigger actions, while notification provides valuable information about Debezium's state and progress.

In previous versions of Debezium initiating an incremental snapshot was only possible through the use of a signaling table. Users had to configure a specific table as a signaling mechanism to trigger the incremental snapshot. However, for MySQL with GTIDs enabled, it was possible to utilize Kafka for signaling purposes.

With the release of Debezium version 2.3, significant improvements have been introduced. Now, users can utilize Kafka for signaling purposes across all connectors, eliminating the need for a dedicated signaling table. However, it's important to note that for incremental snapshot functionality, the signaling table is still required, unless MySQL with GTIDs enabled is being used.

These improvements in Debezium's functionality provide users with more streamlined and standardized approaches to signaling and initiating incremental snapshots, enhancing the overall experience of working with Debezium.

By leveraging the power of signaling and notifications, staying updated with the latest Debezium releases, users can maximize the capabilities of the platform and efficiently capture and process real-time database events.