---
layout: post
title:  Debezium 2.6.1.Final Released
date:   2024-04-12
tags: [ releases, mongodb, mysql, mariadb, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner, jdbc, informix, ibmi ]
author: ccranfor
---

I'm pleased to announce the immediate availability of Debezium **2.6.1.Final**.
This release is the first maintenance release that focuses on addressing several critical stability issues with the 2.6.0.Final release, including classpath loading problems with Debezium Server, MongoDB silently stops gathering changes, and a race condition with the Oracle Infinispan buffer implementation.

Let's take a few moments and dive into these and more...

+++<!-- more -->+++

[id="new-features-and-improvements"]
== New features and improvements

Debezium 2.6.1.Final also introduces many improvements and features, lets take a look at each individually.

=== Oracle RAW data type to STRING converter

Debezium treats a `RAW` column type as a series of bytes, and therefore, change events that contain `RAW` columns use a schema type of `BYTES`.
This is a reasonable default because Debezium does not know the application's purpose for using a `RAW` column, and it is packaging the data from the column as-is.
However, this may not be ideal for consumer applications that would prefer the data emitted as a `STRING` type rather than as `BYTES`.

To help users, we've introduced a new `RawToStringConverter`, which automatically emits `RAW` columns as `STRING` based types rather than the default of `BYTES` (https://issues.redhat.com/browse/DBZ-7753[DBZ-7753]).

To configure the converter, simply add the following configuration:

[source,properties]
----
converters=raw-to-string
converters.raw-to-string.type=io.debezium.connector.oracle.converters.RawToStringConverter
converters.raw-to-string.selector=.*.MY_TABLE.MY_RAW_COLUMN
----

The `selector` property allows the converter to specifically target one or multiply `RAW` columns across one or more tables by providing a comma-separated list of regular expressions.

[IMPORTANT]
====
The `selector` property is optional, and if omitted, the converter applies to _ALL_ `RAW` columns.
====

[id="important-fixes"]
== Fixes and stability improvements

=== Debezium Server snapshotting fixed

If you attempted to perform or re-execute the snapshot phase with Debezium Server in 2.6.0.Final, the process would fail with an error about acquiring a lock.
This was quickly identified as it severely affected the ability to use any Debezium Connector under Debezium Server based on 2.6.0.Final.

We have adjusted how we resolve the components needed for the new Snapshotter API so that when multiple connectors exist on the same class path, the resolution appropriate picks the right component.
In addition, we've also improved the Debezium Server test suite to look specifically for these types of issues moving forward to avoid the potential release of such a build that has similar problems.

[TIP]
====
Debezium Server users should move to 2.6.1.Final and not use 2.6.0.Final.
====

== Other fixes

* Incremental Snapshot: read duplicate data when database has 1000 tables https://issues.redhat.com/browse/DBZ-7716[DBZ-7716]
* SQLServerConnectorIT.shouldNotStreamWhenUsingSnapshotModeInitialOnly check an old log message https://issues.redhat.com/browse/DBZ-7729[DBZ-7729]
* Snapshot fails with an error of invalid lock https://issues.redhat.com/browse/DBZ-7732[DBZ-7732]
* Column CON_ID queried on V$THREAD is not available in Oracle 11 https://issues.redhat.com/browse/DBZ-7737[DBZ-7737]
* Redis NOAUTH Authentication Error when DB index is specified https://issues.redhat.com/browse/DBZ-7740[DBZ-7740]
* Getting oldest transaction in Oracle buffer can cause NoSuchElementException with Infinispan https://issues.redhat.com/browse/DBZ-7741[DBZ-7741]
* The MySQL Debezium connector is not doing the snapshot after the reset. https://issues.redhat.com/browse/DBZ-7743[DBZ-7743]
* MongoDb connector doesn't work with Load Balanced cluster https://issues.redhat.com/browse/DBZ-7744[DBZ-7744]
* Pod Security Context not set from template https://issues.redhat.com/browse/DBZ-7749[DBZ-7749]
* Apply MySQL binlog client version 0.29.1 - bugfix: read long value when deserializing gtid transaction's length https://issues.redhat.com/browse/DBZ-7757[DBZ-7757]
* Change streaming exceptions are swallowed by BufferedChangeStreamCursor https://issues.redhat.com/browse/DBZ-7759[DBZ-7759]
* Sql-Server connector fails after initial start / processed record on subsequent starts https://issues.redhat.com/browse/DBZ-7765[DBZ-7765]
* Valid resume token is considered invalid which leads to new snapshot with some snapshot modes https://issues.redhat.com/browse/DBZ-7770[DBZ-7770]

In total there were https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20and%20fixVersion%20%20in%20(2.6.1.Final[14 issues] resolved in Debezium 2.6.1.Final.
The list of changes can also be found in our https://debezium.io/releases/2.6[release notes].

A big thank you to all the contributors from the community who worked diligently on this release:
https://github.com/jchipmunk[Andrey Pustovetov],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/Naros[Chris Cranford],
https://github.com/chrisrecalis[Chris Recalis],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/methodmissing[Lourens Naudé],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/roldanbob[Robert Roldan], and
https://github.com/selman-genc-alg[Selman Genç]!