---
layout: post
title:  Debezium 2.6.2.Final Released
date:   2024-05-30
tags: [ releases, mongodb, mysql, mariadb, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner, jdbc, informix, ibmi ]
author: ccranfor
---

I'm pleased to announce the immediate availability of Debezium **2.6.2.Final**.
This release is the second maintenance release that focuses on addressing several critical stability issues with the 2.6.1.Final release, support for Oracle database query filtering with more than one thousand tables, fixed race condition with PostgreSQL offset flushing, fixed Avro compatibility, and more.

Let's take a few moments and dive into these and more...

+++<!-- more -->+++

[id="new-features-and-improvements"]
== New features and improvements

Debezium 2.6.2.Final introduces one new feature, lets take a look at it.

=== Oracle database query filtering with 1000+ tables

The Debezium Oracle connector allows configuring the table include and exclude lists to be applied as part of the database query for efficiency reasons using the `log.mining.query.filter.mode`.
When setting this configuration property to a value of `in`, the query is constructed using a SQL in-clause.
In Oracle, an in-clause is restricted to one thousand elements, and if your connector configuration exceeded this limit, the query would fail to execute.

Debezium 2.6 addresses this by creating sub-buckets of exactly one thousand elements and constructs the query using multiple in-clauses separated by a disjunction if the table include and exclude lists are too large.
This improves the user experience, allowing a single connector to capture more than one thousand tables with a single deployment, using the query filter mode, and without resorting to regular expressions. (https://issues.redhat.com/browse/DBZ-7847[DBZ-7847]).

[id="important-fixes"]
== Fixes and stability improvements

Debezium 2.6.2.Final introduces several new bug fixes and stability improvements, lets take a look at a few of them.

=== PostgreSQL offset flush race condition

The Debezium PostgreSQL connector requires that not only do we publish offset metadata to Kafka to handle connector restarts, but the connector must also flush these details to the database's underlying replication slot to prevent unbounded WAL growth.

Using an example, let's propose we have two changes for LSN `1` and `2`.
Both of these changes are written to two different partitions, `A` and `B`, respectively.
As this happens asynchronously, it's possible that the write to partition `B` succeeds while the write to partition `A` fails.

If Debezium receives acknowledgement for partition `B` before `A`, the connector will synchronize the WAL confirmed LSN as `2`.
Should the connector fail before acknowledging partition `A` or get restarted due to a rebalance, upon connector restart the change for LSN `1` is lost.

This problem has been fixed in Debezium 2.6 onward, and the replication slot's confirmed LSN will correctly match the state in the topics (https://issues.redhat.com/browse/DBZ-7816[DBZ-7816]).

=== Avro compatibility

In Debezium 2.5, we introduced several new timestamp fields, `ts_us`, and `ts_ns`, which represent the millisecond-based time values in microseconds and nanoseconds.
Unfortunately, these fields were not introduced in a compatible way for users who use Avro (https://issues.redhat.com/browse/DBZ-7880[DBZ-7880]).

We have adjusted the change event schema so that the new fields introduced are optional, making the change event schema compatible with old versions so that users can upgrade to Debezium 2.6 or later without issues using Avro.

== Other fixes

* After the initial deployment of Debezium, if a new table is added to MSSQL, its schema is was captured https://issues.redhat.com/browse/DBZ-7697[DBZ-7697]
* NO_DATA snapshot mode validation throw DebeziumException on restarts if snapshot is not completed https://issues.redhat.com/browse/DBZ-7780[DBZ-7780]
* DDL statement couldn't be parsed https://issues.redhat.com/browse/DBZ-7788[DBZ-7788]
* old class reference in ibmi-connector services https://issues.redhat.com/browse/DBZ-7795[DBZ-7795]
* Ad-hoc blocking snapshot not working through file channeling without inserting a row in the database. https://issues.redhat.com/browse/DBZ-7806[DBZ-7806]
* Postgres: Potential data loss on connector restart https://issues.redhat.com/browse/DBZ-7816[DBZ-7816]
* Add c3p0 timeout configuration example to JDBC sink https://issues.redhat.com/browse/DBZ-7822[DBZ-7822]
* Sql Server incorrectly applying quoted snapshot statement overrides https://issues.redhat.com/browse/DBZ-7828[DBZ-7828]
* Debezium JDBC Sink not handle order correctly https://issues.redhat.com/browse/DBZ-7830[DBZ-7830]
* in the Cassandra documentation, there is a typo which should have been disable not Dusable. https://issues.redhat.com/browse/DBZ-7851[DBZ-7851]
* Debezium MySQL Snapshot Connector Fails https://issues.redhat.com/browse/DBZ-7858[DBZ-7858]
* Support Oracle DDL Alter Audit Policy https://issues.redhat.com/browse/DBZ-7864[DBZ-7864]
* Support Oracle DDL Create Audit Policy https://issues.redhat.com/browse/DBZ-7865[DBZ-7865]
* Default value of error retries not interpreted correctly https://issues.redhat.com/browse/DBZ-7870[DBZ-7870]
* Too much logs after Debezium update https://issues.redhat.com/browse/DBZ-7871[DBZ-7871]
* Avro schema compatibility issues when upgrading from Oracle Debezium 2.5.3.Final to 2.6.1.Final https://issues.redhat.com/browse/DBZ-7880[DBZ-7880]
* ParsingException (MySQL 8): create trigger if exists https://issues.redhat.com/browse/DBZ-7881[DBZ-7881]
* Debezium can't handle columns with # in its name https://issues.redhat.com/browse/DBZ-7893[DBZ-7893]
* Oracle interval default values are not properly parsed https://issues.redhat.com/browse/DBZ-7898[DBZ-7898]

In total there were https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20and%20fixVersion%20%20in%20(2.6.2.Final)[20 issues] resolved in Debezium 2.6.2.Final.
The list of changes can also be found in our https://debezium.io/releases/2.6[release notes].

A big thank you to all the contributors from the community who worked diligently on this release:
https://github.com/adasari[Anil Dasari],
https://github.com/Naros[Chris Cranford],
https://github.com/DLT1412[Duc Le Tu],
https://github.com/ilyasahsan123[Ilyas Ahsan],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/joschi[Jochen Schalanda],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/augi[Michal Augustýn],
https://github.com/PradeepNain[Pradeep Nain],
https://github.com/roldanbob[Robert Roldan],
https://github.com/rmoff[Robin Moffatt],
https://github.com/rkudryashov[Roman Kudryashov], and
https://github.com/ramanenka[Vadzim Ramanenka]!