---
layout: post
title:  Moving Debezium to a Foundation
date:   2024-10-03
tags: [ announcement ]
author: ccranfor
---

== tl;dr

We are considering moving Debezium to a Software Foundation to expand our community, become more open and transparent in our roadmap and decisions, and encourage multi-vendor participation and execution.

+++<!-- more -->+++

== Introduction

Since its inception in late 2015, Debezium has strived to be the leading open-source platform for Change Data Capture.
A project that started focusing on two connectors has now grown into a portfolio of connectors for nearly a dozen different database vendors.

Over the past several years, there has been rapid growth in multiple areas.
We’ve introduced sink connectors to our portfolio to improve the user experience and offer solutions for full end-to-end Change Data Capture pipelines.
We have introduced supplementary components such as the Debezium Operator and Debezium Server, providing alternative deployment options rather than just Kafka Connect as the only runtime.

But beyond that, the team has grown in other ways, too.
Not only have we had the pleasure of expanding our committer team, but we’ve also enlisted nearly a half-dozen volunteers from the community who help contribute, maintain, and lead our community-led connector portfolio for Google Spanner, Vitess, Informix, and Cassandra.

The project’s overall success would not have been possible without the passion, dedication, and collaboration of our volunteers, contributors, committers, and the extraordinary and vibrant user community.

== Why move to a Foundation?

For Debezium to remain the leading open-source platform for Change Data Capture, we must consider long-term goals to enable the project to adapt to a fast-paced, highly innovative landscape.

Our goals are simple:

* Continue to grow our community
* Increase the adoption and awareness of Debezium
* Embrace transparency in our roadmap and decision-making
* Encourage multi-vendor participation and execution

We believe that moving Debezium to a Foundation will help drive these goals more organically, benefiting everyone involved.

== Support and Alignment with Red Hat Values

Red Hat is dedicated to fostering a vendor-neutral culture for collaboration on Debezium, like other projects such as the Linux kernel, Kubernetes, OpenJDK, and Quarkus.

== Community Feedback

So far, all preliminary discussions about this change have been positive.
But we want to make sure that we make a decision that provides a net benefit, so we’ve created a set of criteria to evaluate foundations, which includes:

* Remain visible, relevant, and recognizable in a foundation’s portfolio.
* Maintain our current release processes without extra processes or steps.
* Make independent, self-informed decisions rather than those imposed.
* License flexibility to continue using a wide array of third-party libraries.
* Flexibility to create sub-projects or use the Debezium brand, focusing on new areas of interest or proofs of concepts that could expand the project’s portfolio.

We invite you, the broader Debezium community, to get involved in the conversation.
You can share your concerns and constructive feedback on our https://groups.google.com/forum/#!forum/debezium[mailing list] or https://debezium.zulipchat.com/login/#narrow/stream/302529-community-general/topic/Move20Debezium20to20a20Foundation[zulip chat].
This is crucial for us to decide the best home for Debezium.

Let’s guarantee that Debezium continues to grow, thrive, and remain the leader in Change Data Capture together!