---
layout: post
title:  Debezium 2.7.1.Final Released
date:   2024-08-08
tags: [ releases, mongodb, mysql, mariadb, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner, jdbc, informix, ibmi ]
author: ccranfor
---

I am pleased to announce the first maintenance release of Debezium 2.7, **2.7.1.Final**.
This maintenance release focuses on addressing a number of stability issues, including improvements to ad-hoc snapshots, closing of transformations in the embedded engine, improvements to the Oracle LogMiner implementation, Vitess epoch calculations, and more...

Let's dive into these changes...

+++<!-- more -->+++

[id="important-fixes"]
== Fixes and stability improvements

Debezium 2.7.1.Final introduces several new bug fixes and stability improvements, lets take a look at a few of them.

=== MariaDB is now included in Debezium container images

In Debezium 2.7.0.Final, we mistakenly missed including the new Debezium for MariaDB connector in the container images, which necessitated users to manually install the MariaDB connector.
This has been fixed and Debezium 2.7.1.Final's container images now include all connectors like they did previously (https://issues.redhat.com/browse/DBZ-8008[DBZ-8008]).

=== Support for MariaDB `RENAME TABLE`

In Debezium 2.7 with the separation of MariaDB and MySQL into their unique connectors, each also use a unique grammar to parse SQL statements.
A regression was identified that the new MariaDB grammar did not support the SQL syntax for `RENAME TABLE` (https://issues.redhat.com/browse/DBZ-8066[DBZ-8066]).
This has been fixed and is fully supported in both MySQL and MariaDB.

=== JDBC sink partition rebalance fixed

In prior versions of the Debezium JDBC sink, users may have noticed several strange messages in their connector logs that may resemble the following output:

[source,bash]
====
Ignoring invalid task provided offset topicXYZ-1 OffsetAndMetadata{offset=4966, leaderEpoch=null, metadata=''} -- partition not assigned, assignment=[topicXYZ-1] (org.apache.kafka.connect.runtime.WorkerSinkTask:434)
====

Thanks to a user report (https://issues.redhat.com/browse/DBZ-7946[DBZ-7946]), it was identified that the JDBC sink connector was not properly handling the rebalance of partitions across multiple tasks.
This regression has been fixed in **2.7.1.Final**, and when a partition rebalance occurs, the partition will be closed by the task that no longer will manage the partition; ergo, the above messages will no longer be written to the connector logs.

=== Ad-hoc snapshot improvements

In Debezium 2.7, users may have noticed that if you picked the `insert_delete` watermark strategy for handling signal table entries, that the connector would eventually fail with a `StackOverflowError` (https://issues.redhat.com/browse/DBZ-8011[DBZ-8011]).
With Debezium 2.7.1.Final or later, this regression has been fixed and users can once again use the `insert_delete` watermark strategy.

In addition, there was also a report where sending an ad-hoc snapshot signal that contained a regular expression that matches no database tables would cause the ad-hoc snapshot process to fail with an `"Unexpected result ."` error (https://issues.redhat.com/browse/DBZ-8050[DBZ-8050]).
This has also been fixed so the ad-hoc snapshot will gracefully skip the signal as no matching tables were found.

Finally, it was also identified that ad-hoc blocking snapshots could lead to a `CommunicationsException` due to how the connection was being managed by the initial and blocking snapshot code paths (https://issues.redhat.com/browse/DBZ-8058[DBZ-8058]).
This has been fixed in Debezium 2.7.1.Final by having the blocking snapshot validate and re-open the connection if required.

=== Embedded engine now closes transformations

The new asynchronous embedded engine was recently released by the Debezium team and continues to improve across releases.
As a part of our continuous improvements,  it was identified that single message transforms did not have their `close()` method being called.
This could easily lead to resource leaks depending on what the transformation does.

This release introduces a fix to automatically close transformations to avoid this problem (https://issues.redhat.com/browse/DBZ-8106[DBZ-8106]).

=== Oracle connector could produce a NullPointerException

A change was added to the Debezium Oracle connector (https://issues.redhat.com/browse/DBZ-8055[DBZ-8055]) that to address several race concerns with Oracle LogMiner and capturing changes.
Unfortunately, that change introduced a corner case where the connector would recalculate the upper mining range, and in such cases would lead to a `NullPointerException`.

A new fix (https://issues.redhat.com/browse/DBZ-8119[DBZ-8119]) was included in Debezium 2.7.1.Final to correct the problem.
Oracle connector users are recommended to upgrade to 2.7.1.Final and to skip 2.7.0.Final to avoid this regression.

=== Vitess epoch calculations fixed

It was identified that there were some corner cases where the transaction epoch value was being reset when a transaction ID was unavailable (https://issues.redhat.com/browse/DBZ-8087[DBZ-8087]).
This is unexpected behavior as the transaction epoch should monotonically increase, and the resetting to zero broke that expectation.
A fix has been added to avoid the reset and to restore the expected transaction epoch behavior.

[id="other-fixes"]
== Other fixes

* Document new MariaDB connector https://issues.redhat.com/browse/DBZ-7786[DBZ-7786]
* Clarify that Oracle connector does not read from physical standby https://issues.redhat.com/browse/DBZ-7895[DBZ-7895]
* Issue with Hybrid mode and DDL change https://issues.redhat.com/browse/DBZ-7991[DBZ-7991]
* Incorrect offset/history property mapping generated https://issues.redhat.com/browse/DBZ-8007[DBZ-8007]
* Bump Infinispan to 14.0.29.Final https://issues.redhat.com/browse/DBZ-8010[DBZ-8010]
* JDBC primary.key.fields cannot be empty when i set insert.mode to upsert and primary.key.mode record_value https://issues.redhat.com/browse/DBZ-8018[DBZ-8018]
* Unable to acquire buffer lock, buffer queue is likely full https://issues.redhat.com/browse/DBZ-8022[DBZ-8022]
* ORA-65090: operation only allowed in a container database when connecting to a non-CDB database https://issues.redhat.com/browse/DBZ-8023[DBZ-8023]
* Add disclaimer that PostProcessors and CustomConverters are Debezium source connectors only https://issues.redhat.com/browse/DBZ-8031[DBZ-8031]
* Added type to Prometheus JMX exporter https://issues.redhat.com/browse/DBZ-8036[DBZ-8036]
* Add `kafka.producer` metrics to debezium-server jmx exporter config https://issues.redhat.com/browse/DBZ-8037[DBZ-8037]
* Oracle connector inconsistency in redo log switches https://issues.redhat.com/browse/DBZ-8055[DBZ-8055]
* Oracle histogram metrics are no longer printed in logs correctly https://issues.redhat.com/browse/DBZ-8068[DBZ-8068]
* In hybrid log.mining.strategy reconstruction logs should be set to DEBUG https://issues.redhat.com/browse/DBZ-8070[DBZ-8070]
* Support capturing BLOB column types during snapshot for MySQL/MariaDB https://issues.redhat.com/browse/DBZ-8076[DBZ-8076]
* Conditionalize reference to the MySQL default value in description of `schema.history.internal.store.only.captured.databases.ddl` https://issues.redhat.com/browse/DBZ-8081[DBZ-8081]
* After changing the column datatype from int to float the Debezium fails to round it and i get a null value for this field in the stream https://issues.redhat.com/browse/DBZ-8089[DBZ-8089]
* MySQL and MariaDB keyword YES cannot be parsed as a column name https://issues.redhat.com/browse/DBZ-8092[DBZ-8092]
* Update third-party LICENSE with LGPL forMariaDB Connector/J https://issues.redhat.com/browse/DBZ-8099[DBZ-8099]
* NotificationIT tests seemingly seem to fail due to stepping on one another https://issues.redhat.com/browse/DBZ-8100[DBZ-8100]
* ORA-26928 - Unable to communicate with XStream apply coordinator process should be retriable https://issues.redhat.com/browse/DBZ-8102[DBZ-8102]
* Converters documentation uses incorrect examples https://issues.redhat.com/browse/DBZ-8104[DBZ-8104]
* Remove reference to`additional condition` signal parameter from ad hoc snapshots doc https://issues.redhat.com/browse/DBZ-8107[DBZ-8107]
* Don't close connection after loading timescale metadata in TimescaleDb SMT https://issues.redhat.com/browse/DBZ-8109[DBZ-8109]
* Primary Key Update/ Snapshot Race Condition https://issues.redhat.com/browse/DBZ-8113[DBZ-8113]
* Docs: connect-log4j.properties instead log4j.properties https://issues.redhat.com/browse/DBZ-8117[DBZ-8117]
* TimescaleDbDatabaseTest.shouldTransformCompressedChunks is failing https://issues.redhat.com/browse/DBZ-8123[DBZ-8123]
* Update Oracle connector doc to describe options for restricting access permissions for the Debezium LogMiner user https://issues.redhat.com/browse/DBZ-8124[DBZ-8124]

In total there were https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20and%20fixVersion%20%20in%20(2.7.1.Final)[37 issues] resolved in Debezium 2.7.1.Final.
The list of changes can also be found in our https://debezium.io/releases/2.7[release notes].

A big thank you to all the contributors from the community who worked diligently on this release:
https://github.com/andreas-ibm[Andreas Martens],
https://github.com/jchipmunk[Andrey Pustovetov],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/bpaquet[Bertrand Paquet],
https://github.com/Naros[Chris Cranford],
https://github.com/cjmencias[Christian Jacob Mencias],
https://github.com/DLT1412[Duc Le Tu],
https://github.com/gaurav7261[Gaurav Miglani],
https://github.com/gunnarmorling[Gunnar Morling],
https://github.com/harveyyue[Harvey Yue],
https://github.com/HenkvanDyk[Henk van Dyk],
https://github.com/blcksrx[Hossein Torabi],
https://github.com/nicholas-fwang[Inki Hwang],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/Naros[M. Gökhan Akgül],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/michal-k-gl[Michal Pioun],
https://github.com/mimaison[Mickael Maison],
https://github.com/nguymin4[Minh Son Nguyen],
https://github.com/obabec[Ondrej Babec],
https://github.com/missingcharacter[Ricardo Rosales],
https://github.com/roldanbob[Robert Roldan],
https://github.com/rkudryashov[Roman Kudryashov],
https://github.com/ryanvanhuuksloot[Ryan van Huuksloot],
https://github.com/joontube[Seongjoon Jeong],
https://github.com/twthorn[Thomas Thornton],
https://github.com/blcksrx[Hossein Torabi],
https://github.com/ramanenka[Vadzim Ramanenka],
https://github.com/vjuranek[Vojtech Juranek], and
https://github.com/j2gg0s[Yanjie Wang]!