---
layout: post
title:  Debezium 2.5.2.Final Released
date:   2024-02-27
tags: [ releases, mongodb, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner, jdbc ]
author: ccranfor
---

We are happy to announce the second maintenance release of the Debezium 2.5 release stream, **Debezium 2.5.2.Final**.
This release includes some improvements and numerous bug fixes, so let's dive right in...

+++<!-- more -->+++

== Improvements and changes

=== Scoped Key/Trust - store support with MongoDB

Debezium supports secure connections; however, MongoDB requires that the key/trust -store configurations be supplied as JVM process arguments, which is less than ideal for environments in the cloud.
This feature was first introduced as part of Debezium 2.6, and we've opted to back-port this to Debezium 2.5.
This new change allows per connector scoped key/trust -store configurations as part of the connector configuration (https://issues.redhat.com/browse/DBZ-7379[DBZ-7379]).

The MongoDB connector now includes the following new configuration properties:

`mongodb.ssl.keystore`::
Specifies the path to the SSL keystore file.

`mongodb.ssl.keystore.password`::
Specifies the credentials to open and access the SSL keystore provided by _mongodb.ssl.keystore_.

`mongodb.ssl.keystore.type`::
Specifies the SSL keystore file type, defaults to `PKC512`.

`mongodb.ssl.truststore`::
Specifies the path to the SSL truststore file.

`mongodb.ssl.truststore.password`::
Specifies the credentials to open and access the SSL truststore provided by _mongodb.ssl.truststore_.

`mongodb.ssl.truststore.type`::
Specifies the SSL truststore file type, defaults to `PKC512`.

== Other changes

Altogether, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%202.5.2.Final%20ORDER%20BY%20component%20ASC[30 issues] were fixed in this release:

* PostgreSQL connector doesn't restart properly if database if not reachable https://issues.redhat.com/browse/DBZ-6236[DBZ-6236]
* Correctly handle METADATA records https://issues.redhat.com/browse/DBZ-7176[DBZ-7176]
* Cassandra-4: Debezium connector stops producing events after a schema change https://issues.redhat.com/browse/DBZ-7363[DBZ-7363]
* Informix-Connector breaks on table with numerical default value https://issues.redhat.com/browse/DBZ-7372[DBZ-7372]
* Poor performance with incremental snapshot with long list of tables https://issues.redhat.com/browse/DBZ-7421[DBZ-7421]
* Oracle Snapshot mistakenly uses LogMiner Offset Loader by default https://issues.redhat.com/browse/DBZ-7425[DBZ-7425]
* Reselect columns should source key values from after Struct when not using event-key sources https://issues.redhat.com/browse/DBZ-7429[DBZ-7429]
* Allow the C3P0ConnectionProvider to be customized via configuration https://issues.redhat.com/browse/DBZ-7431[DBZ-7431]
* Stopwatch throw NPE when toString is called without having statistics https://issues.redhat.com/browse/DBZ-7436[DBZ-7436]
* Adhoc snapshots are not triggered via File channel signal when submitted before the start of the application https://issues.redhat.com/browse/DBZ-7441[DBZ-7441]
* Upgrade protobuf to 3.25.2 https://issues.redhat.com/browse/DBZ-7442[DBZ-7442]
* Correct debezium.sink.pubsub.flowcontrol.* variable names in Debezium Server docs site https://issues.redhat.com/browse/DBZ-7443[DBZ-7443]
* LogMiner batch size does not increase automatically https://issues.redhat.com/browse/DBZ-7445[DBZ-7445]
* Consolidate version management  https://issues.redhat.com/browse/DBZ-7455[DBZ-7455]
* Oracle connector does not ignore reselection for excluded clob/blob columns https://issues.redhat.com/browse/DBZ-7456[DBZ-7456]
* The expected value pattern for table.include.list does not align with the documentation https://issues.redhat.com/browse/DBZ-7460[DBZ-7460]
* Signals actions are not loaded for SQLServer https://issues.redhat.com/browse/DBZ-7467[DBZ-7467]
* MySQL connector cannot parse table with WITH SYSTEM VERSIONING PARTITION BY SYSTEM_TIME https://issues.redhat.com/browse/DBZ-7468[DBZ-7468]
* Test Db2ReselectColumnsProcessorIT randomly fails https://issues.redhat.com/browse/DBZ-7471[DBZ-7471]
* Make readiness and liveness proble timouts configurable https://issues.redhat.com/browse/DBZ-7476[DBZ-7476]
* PreparedStatement leak in Oracle ReselectColumnsProcessor https://issues.redhat.com/browse/DBZ-7479[DBZ-7479]
* Document toggling MariaDB mode  https://issues.redhat.com/browse/DBZ-7487[DBZ-7487]
* Poor snapshot performance with new reselect SMT https://issues.redhat.com/browse/DBZ-7488[DBZ-7488]
* Debezium Oracle Connector ParsingException on XMLTYPE with lob.enabled=true https://issues.redhat.com/browse/DBZ-7489[DBZ-7489]
* Fix MySQL 8 event timestamp resolution logic error where fallback to seconds occurs erroneously for non-GTID events https://issues.redhat.com/browse/DBZ-7500[DBZ-7500]
* Add Start CDC hook in Reselect Columns PostProcessor Tests https://issues.redhat.com/browse/DBZ-7516[DBZ-7516]
* Update commons-compress to 1.26.0 https://issues.redhat.com/browse/DBZ-7520[DBZ-7520]
* Promote JDBC sink from Incubating https://issues.redhat.com/browse/DBZ-7521[DBZ-7521]
* Fix null event timestamp possible from FORMAT_DESCRIPTION and PREVIOUS_GTIDS events in MySqlStreamingChangeEventSource::setEventTimestamp https://issues.redhat.com/browse/DBZ-7567[DBZ-7567]

A big thank you to all the contributors from the community who worked on this release:
https://github.com/jchipmunk[Andrey Pustovetov],
https://github.com/Naros[Chris Cranford],
https://github.com/CliffordCheefoon[Clifford Cheefoon],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/nrkljo[Lars M. Johansson],
https://github.com/methodmissing[Lourens Naudé],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/obabec[Ondrej Babec],
https://github.com/roldanbob[Robert Roldan], and
https://github.com/schampilomatis[Stavros Champilomatis]!

== Outlook &amp; What's next?

We are just over a month away from the next minor installment, Debezium 2.6.
This next release is packed with tons of new features and changes that we are excited to share. We encourage you to take a moment, grab the pre-releases available https://debezium.io/documentation/reference/nightly/install.html#_installing_a_debezium_connector[here], and share your feedback.

In a few short weeks, the team will begin to shift focus to what lies ahead with Debezium 2.7.
This will be the last minor release of the Debezium 2.x release stream, which will include read-only incremental snapshots for other connectors, a new dedicated MariaDB source connector, and a MongoDB sink connector, just to name a few highlights.
We will also be carrying over any work from 2.6 that we're still working on but didn't make it into that release.

And in closing, the last half of the year will be focusing on Debezium 3, where we'll be moving to Java 17, work on new time-series source connectors, and more.
Please take a moment and review our link:/docs/roadmap[road map].
If you have any suggestions or ideas, please feel free to get in touch with us on our https://groups.google.com/forum/#!forum/debezium[mailing list] or in our https://debezium.zulipchat.com/login/#narrow/stream/302529-users[Zulip chat].

Until next time...
