---
layout: post
title:  Debezium 2.6.0.Beta1 Released
date:   2024-03-06
tags: [ releases, mongodb, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner, jdbc, informix, ibmi ]
author: ccranfor
---

We are pleased to announce the release of **Debezium 2.6.0.Beta1**.
We enter the home stretch with this release, packed with many improvements, enhancements, bug fixes, and yes _a brand new Db2 connector for iSeries_.
There is a lot to cover in this release, so lets dive right in!

+++<!- more --->+++

== Breaking changes

The team aims to avoid any potential breaking changes between minor releases; however, such changes are sometimes inevitable.

Oracle::
In older versions of Debezium, users were required to manually install the `ojdbc8.jar` JDBC driver.
With 2.6, the connector now bundles the Oracle JDBC driver with the connector, so manual installation is no longer necessary (https://issues.redhat.com/browse/DBZ-7364[DBZ-7364]).

[NOTE]
====
We've also updated the driver to version `21.11.0.0`, please verify that you do not have multiple versions after upgrading to Debezium 2.6 (https://issues.redhat.com/browse/DBZ-7365[DBZ-7365]).
====

Container Images::
The handling of the `MAVEN_DEP_DESTINATION` environment variable has changed in the `connect-base` container image, which is the basis for `debezium/connect`.
It is no longer used for downloading all dependencies, including connectors, but only for general purpose Maven Central located dependencies (https://issues.redhat.com/browse/DBZ-7551[DBZ-7551]).
If you were using custom images that relied on this environment variable, your image build steps may require modifications.

== Improvements and changes

=== Db2 for iSeries connector

Debezium 2.6 introduces a brand-new connector for IBM fans to stream changes from Db2 iSeries/AS400 using the IBM iJournal system.
This collaboration is a multi-year development effort from the community, and we're pleased that the community has allowed this to be distributed under the Debezium umbrella.

The new connector can be obtained from Maven Central using the following coordinates or a https://repo1.maven.org/maven2/io/debezium/debezium-connector-ibmi/2.6.0.Beta1/debezium-connector-ibmi-2.6.0.Beta1-plugin.zip[direct download].
```xml
<dependency>
    <groupId>io.debezium</groupId>
    <artifactId>debezium-connector-ibmi</artifactId>
    <version>2.6.0.Beta1</version>
</dependency>
```

[NOTE]
====
The documentation for this new connector is still a work-in-progress.
If you have any questions, please be sure to reach out to the team on Zulip or the mailing list.
====

=== Incremental snapshot row-value constructors for PostgreSQL

The PostgreSQL driver supports a SQL syntax called a row-value constructor using the `ROW()` function.
This allows a query to express predicate conditions in a more efficient way when working with multi-columned primary keys that have a suitable index.
The incremental snapshot process is an ideal candidate for the use of the `ROW()` function, the process involves issuing a series of select SQL statements to fetch data in chunks.
Each statement, aka chunk query, should ideally be as efficient as possible to minimize the cost overhead of these queries to maximize throughput of your WAL changes to your topics.

There are no specific changes needed, but the query issued for PostgreSQL incremental snapshots has been adjusted to take advantage of this new syntax, and therefore users who utilize incremental snapshots should see performance improvements.

An example of the old query used might look like this for a simple table:
```sql
SELECT *
  FROM users
 WHERE (a = 10 AND (b > 2 OR b IS NULL)) OR (a > 10) OR (a IS NULL)
 ORDER BY a, b LIMIT 1024
```

The new implementation constructs this query using the `ROW()` function as follows:
```sql
SELECT *
  FROM users
 WHERE row(a,b) > row(10,2)
ORDER BY a, b LIMIT 1024
```

We'd be interested in any feedback on this change, and what performance improvements are observed.

=== Signal table watermark metadata

An incremental snapshot process requires a signal table to write open/close markers to coordinate the change boundaries with the data recorded in the transaction logs, unless you're using MySQL's read-only flavor.
In some cases, users would like to be able to track the window time slot, knowing when the window was opened and closed.

Starting with Debezium 2.6, the `data` column in the signal table will be populated with the time window details, allowing users to obtain when the window was opened and closed.
The following shows the details of the `data` column for each of the two signal markers:

.Window Open Marker
```json
{"openWindowTimestamp": "<window-open-time>"}
```

.Window Close Marker
```json
{"openWindowTimestamp": "<window-open-time>", "closeWindowTimestamp": "<window-close-time>"}
```

=== Oracle Redo SQL per event with LogMiner

We have improved the Oracle connector's event structure for inserts, updates, and deletes to optionally contain the SQL that was reconstructed by LogMiner in the `source` information block.
This feature is an opt-in only feature that you must enable as this can easily more than double the size of your existing event payload.

To enable the inclusion of the REDO SQL as part of the change event, add the following connector configuration:
```json
"log.mining.include.redo.sql": "true"
```

With this option enabled, the `source` information block contains a new field `redo_sql`, as shown below:

```json
"source": {
  ...
  "redo_sql": "INSERT INTO \"DEBEZIUM\".\"TEST\" (\"ID\",\"DATA\") values ('1', 'Test');"
}
```

[WARNING]
====
This feature cannot be used with `lob.enabled` set to `true` due to how LogMiner reconstructs the SQL related to CLOB, BLOB, and XML data types.
If the above configuration is added with `lob.enabled` set to `true`, the connector will start with an error about this misconfiguration.
====

=== Oracle LogMiner transaction buffer improvements

A new delay-strategy for transaction registration has been added when using LogMiner.
This strategy effectively delays the creation of the transaction record in the buffer until we observe the first captured change for that transaction.

[NOTE]
====
For users who use the Infinispan cache or who have enabled `lob.enabled`, this delayed strategy cannot be used due to how specific operations are handled in these two modes of the connector.
====

Delaying transaction registration has a number of benefits, which include:

* Reducing the overhead on the transaction cache, especially in a highly concurrent transaction scenario.
* Avoids long-running transactions that have no changes that are being captured by the connector.
* Should aid in advancing the low-watermark SCN in the offsets more efficiently in specific scenarios.

We are looking into how we can explore this change for Infinispan-based users in a future build; however, due to the nature of how `lob.enabled` works with LogMiner, this feature won't be possible for that use case.

=== Improved event timestamp precision

Debezium 2.6 introduces a new community requested feature to improve the precision of timestamps in change events.
Users will now notice the addition of 4 new fields, two at the envelope level and two in the `source` information block as shown below:

```json
{
  "source": {
    ...,
    "ts_us": "1559033904863123",
    "ts_ns": "1559033904863123000"
  },
  "ts_us": "1580390884335451",
  "ts_ns": "1580390884335451325",
}
```

The envelope values will always provide both microsecond (`ts_us`) and nanosecond (`ts_ns`) values while the `source` information block may have both micro and nano -second precision values truncated to a lower precision if the source database does not provide that level of precision.

=== Informix appends LSN to Transaction Identifier

Informix databases only increases the transaction identifier when there are concurrent transactions, otherwise the value remains identical for sequential transactions.
This can prove difficult for users who may want to utilize the transaction metadata to order change events in a post processing step.

Debezium 2.6 for Informix will now append the log sequence number (LSN) to the transaction identifier so that users can easily sort change events based on the transaction metadata.
The transaction identifier field will now use the format `<id>:<lsn>`.
This change affects transaction metadata events and the `source` information block for change events, as shown below:

.Transaction Begin Event
```json
{
  "status": "BEGIN",
  "id": "571:53195829",
  ...
}
```
.Transaction End Event
```json
{
  "status": "END",
  "id": "571:53195832",
  ...
}
```
.Change Events
```json
{
  ...
  "source": {
    "id": "571:53195832"
    ...
  }
}
```

=== New Arbitrary-based payload formats

While it's common for users to utilize serialization based on Json, Avro, Protobufs, or CloudEvents, there may be reasons to use a more simplistic format.
Thanks to a community contribution as part of https://issues.redhat.com/browse/DBZ-7512[DBZ-7512], Debezium can be configured to use two new formats called `simplestring` and `binary`.

The `simplestring` and `binary` formats are configured in Debezium server using the `debezium.format` configurations.
For `simplestring`, the payload will be serialized as a single `STRING` data type into the topic.
For `binary`, the payload will be serialized as a `BYTES` using a `byte[]` (byte array).

=== Oracle LogMiner Hybrid Mining Strategy

Debezium 2.6 also introduces a new Oracle LogMiner mining strategy called _hyrid_, which can be enabled by setting the configuration property `log.mining.strategy` with the value of `hybrid`.
This new strategy is designed to support all schema evolution features of the default mining strategy while taking advantage of all the performance optimizations from the online catalog strategy.

The main problem with the `online_catalog` strategy is that if a mining step observes a schema change and a data change in the same mining step, LogMiner is incapable of reconstructing the SQL correctly, which will result in the table name being `OBJ# xxxxxx` or the columns represented as `COL1`, `COL2`, and so on.
To avoid this while using the online catalog strategy, users are recommended to perform schema changes in a lock-step pattern to avoid a mining step that observes both a schema change and a data change together; however, this is not always feasible.

The new hybrid strategy works by tracking a table's object id at the database level and then using this identifier to look up the schema associated with the table from Debezium's relational table model.
In short, this allows Debezium to do what Oracle LogMiner is unable to do in these specific corner cases.
The table name will be taken from the relational model's table name and columns will be mapped by column position.

Unfortunately, Oracle does not provide a way to reconstruct failed SQL operations for CLOB, BLOB, and XML data types.
This means that the new hybrid strategy cannot be configured with configurations that use `lob.enabled` set to `true`.
If a connector is started using the hybrid strategy and has `lob.enabled` set to `true`, the connector will fail to start and report a configuration failure.

== Other changes

Altogether, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%202.6.0.Beta1%20ORDER%20BY%20component%20ASC[86 issues] were fixed in this release:

* MySQL config values validated twice https://issues.redhat.com/browse/DBZ-2015[DBZ-2015]
* PostgreSQL connector doesn't restart properly if database if not reachable https://issues.redhat.com/browse/DBZ-6236[DBZ-6236]
* NullPointerException in MongoDB connector https://issues.redhat.com/browse/DBZ-6434[DBZ-6434]
* Tests in RHEL system testsuite throw errors without ocp cluster https://issues.redhat.com/browse/DBZ-7002[DBZ-7002]
* Move timeout configuration of MongoDbReplicaSet into Builder class https://issues.redhat.com/browse/DBZ-7054[DBZ-7054]
* Several Oracle tests fail regularly on Testing Farm infrastructure https://issues.redhat.com/browse/DBZ-7072[DBZ-7072]
* Remove obsolete MySQL version from TF https://issues.redhat.com/browse/DBZ-7173[DBZ-7173]
* Add Oracle 23 to CI test matrix https://issues.redhat.com/browse/DBZ-7195[DBZ-7195]
* Refactor sharded mongo ocp test https://issues.redhat.com/browse/DBZ-7221[DBZ-7221]
* Implement Snapshotter SPI Oracle https://issues.redhat.com/browse/DBZ-7302[DBZ-7302]
* Align snapshot modes for SQLServer https://issues.redhat.com/browse/DBZ-7303[DBZ-7303]
* Update snapshot mode documentation https://issues.redhat.com/browse/DBZ-7309[DBZ-7309]
* Cassandra-4: Debezium connector stops producing events after a schema change https://issues.redhat.com/browse/DBZ-7363[DBZ-7363]
* Upgrade ojdbc8 to 21.11.0.0 https://issues.redhat.com/browse/DBZ-7365[DBZ-7365]
* Document relation between column type and serializers for outbox https://issues.redhat.com/browse/DBZ-7368[DBZ-7368]
* Callout annotations rendered multiple times in downstream User Guide https://issues.redhat.com/browse/DBZ-7418[DBZ-7418]
* Test testEmptyChangesProducesHeartbeat tends to fail randomly https://issues.redhat.com/browse/DBZ-7453[DBZ-7453]
* Align snapshot modes for PostgreSQL, MySQL, Oracle https://issues.redhat.com/browse/DBZ-7461[DBZ-7461]
* PreparedStatement leak in Oracle ReselectColumnsProcessor https://issues.redhat.com/browse/DBZ-7479[DBZ-7479]
* Allow special characters in signal table name https://issues.redhat.com/browse/DBZ-7480[DBZ-7480]
* Document toggling MariaDB mode  https://issues.redhat.com/browse/DBZ-7487[DBZ-7487]
* Poor snapshot performance with new reselect SMT https://issues.redhat.com/browse/DBZ-7488[DBZ-7488]
* Debezium Oracle Connector ParsingException on XMLTYPE with lob.enabled=true https://issues.redhat.com/browse/DBZ-7489[DBZ-7489]
* Add informix to main repository CI workflow https://issues.redhat.com/browse/DBZ-7490[DBZ-7490]
* Db2ReselectColumnsProcessorIT does not clean-up after test failures https://issues.redhat.com/browse/DBZ-7491[DBZ-7491]
* Disable Oracle Integration Tests on GitHub https://issues.redhat.com/browse/DBZ-7494[DBZ-7494]
* Unify and adjust thread time outs https://issues.redhat.com/browse/DBZ-7495[DBZ-7495]
* Completion callback called before connector stop https://issues.redhat.com/browse/DBZ-7496[DBZ-7496]
* Add "IF [NOT] EXISTS" DDL support for Oracle 23 https://issues.redhat.com/browse/DBZ-7498[DBZ-7498]
* Deployment examples show attribute name instead of its value https://issues.redhat.com/browse/DBZ-7499[DBZ-7499]
* Fix MySQL 8 event timestamp resolution logic error where fallback to seconds occurs erroneously for non-GTID events https://issues.redhat.com/browse/DBZ-7500[DBZ-7500]
* Remove incubating from Debezium documentation https://issues.redhat.com/browse/DBZ-7501[DBZ-7501]
* Add ability to parse Map<String, Object> into ConfigProperties https://issues.redhat.com/browse/DBZ-7503[DBZ-7503]
* LogMinerHelperIT test shouldAddCorrectLogFiles randomly fails https://issues.redhat.com/browse/DBZ-7504[DBZ-7504]
* Support Oracle 23 SELECT without FROM https://issues.redhat.com/browse/DBZ-7505[DBZ-7505]
* Add Oracle 23 Annotation support for CREATE/ALTER TABLE statements https://issues.redhat.com/browse/DBZ-7506[DBZ-7506]
* TestContainers MongoDbReplicaSetAuthTest randomly fails https://issues.redhat.com/browse/DBZ-7507[DBZ-7507]
* MySQl ReadOnlyIncrementalSnapshotIT testStopSnapshotKafkaSignal fails randomly https://issues.redhat.com/browse/DBZ-7508[DBZ-7508]
* Add Informix to Java Outreach https://issues.redhat.com/browse/DBZ-7510[DBZ-7510]
* Disable parallel record processing in DBZ server tests against Apicurio https://issues.redhat.com/browse/DBZ-7515[DBZ-7515]
* Add Start CDC hook in Reselect Columns PostProcessor Tests https://issues.redhat.com/browse/DBZ-7516[DBZ-7516]
* Remove the unused 'connector' parameter in the createSourceTask method in EmbeddedEngine.java https://issues.redhat.com/browse/DBZ-7517[DBZ-7517]
* Update commons-compress to 1.26.0 https://issues.redhat.com/browse/DBZ-7520[DBZ-7520]
* Promote JDBC sink from Incubating https://issues.redhat.com/browse/DBZ-7521[DBZ-7521]
* Allow to download containers also from Docker Hub https://issues.redhat.com/browse/DBZ-7524[DBZ-7524]
* Update rocketmq version https://issues.redhat.com/browse/DBZ-7525[DBZ-7525]
* signalLogWithEscapedCharacter fails with pgoutput-decoder https://issues.redhat.com/browse/DBZ-7526[DBZ-7526]
* Move RocketMQ dependency to debezium server https://issues.redhat.com/browse/DBZ-7527[DBZ-7527]
* Rework shouldGenerateSnapshotAndContinueStreaming assertions to deal with parallelization https://issues.redhat.com/browse/DBZ-7530[DBZ-7530]
* Multi-threaded snapshot can enqueue changes out of order https://issues.redhat.com/browse/DBZ-7534[DBZ-7534]
* AsyncEmbeddedEngineTest#testTasksAreStoppedIfSomeFailsToStart fails randomly https://issues.redhat.com/browse/DBZ-7535[DBZ-7535]
* MongoDbReplicaSetAuthTest fails randomly https://issues.redhat.com/browse/DBZ-7537[DBZ-7537]
* SQLServer tests taking long time due to database bad state https://issues.redhat.com/browse/DBZ-7541[DBZ-7541]
* Explicitly import jakarta dependencies that are excluded via glassfish filter https://issues.redhat.com/browse/DBZ-7545[DBZ-7545]
* ReadOnlyIncrementalSnapshotIT#testStopSnapshotKafkaSignal fails randomly https://issues.redhat.com/browse/DBZ-7553[DBZ-7553]
* Include RocketMQ and Redis container output into test log https://issues.redhat.com/browse/DBZ-7557[DBZ-7557]
* Allow XStream error ORA-23656 to be retried https://issues.redhat.com/browse/DBZ-7559[DBZ-7559]
* Numeric default value decimal scale mismatch https://issues.redhat.com/browse/DBZ-7562[DBZ-7562]
* Wait for Redis server to start https://issues.redhat.com/browse/DBZ-7564[DBZ-7564]
* Documentation conflict https://issues.redhat.com/browse/DBZ-7565[DBZ-7565]
* Fix null event timestamp possible from FORMAT_DESCRIPTION and PREVIOUS_GTIDS events in MySqlStreamingChangeEventSource::setEventTimestamp https://issues.redhat.com/browse/DBZ-7567[DBZ-7567]
* AsyncEmbeddedEngineTest.testExecuteSmt fails randomly https://issues.redhat.com/browse/DBZ-7568[DBZ-7568]
* Debezium fails to compile with JDK 21 https://issues.redhat.com/browse/DBZ-7569[DBZ-7569]
* Upgrade PostgreSQL driver to 42.6.1 https://issues.redhat.com/browse/DBZ-7571[DBZ-7571]
* Upgrade Kafka to 3.7.0 https://issues.redhat.com/browse/DBZ-7574[DBZ-7574]
* Redis tests fail randomly with JedisConnectionException: Unexpected end of stream https://issues.redhat.com/browse/DBZ-7576[DBZ-7576]
* RedisOffsetIT.testRedisConnectionRetry fails randomly https://issues.redhat.com/browse/DBZ-7578[DBZ-7578]
* Oracle connector always brings OLR dependencies https://issues.redhat.com/browse/DBZ-7579[DBZ-7579]
* Correct JDBC connector dependencies https://issues.redhat.com/browse/DBZ-7580[DBZ-7580]
* Improved logging in case of PostgreSQL failure https://issues.redhat.com/browse/DBZ-7581[DBZ-7581]
* Unavailable Toasted HSTORE Json Storage Mode column causes serialization failure https://issues.redhat.com/browse/DBZ-7582[DBZ-7582]
* Reduce debug logs on tests  https://issues.redhat.com/browse/DBZ-7588[DBZ-7588]
* Server SQS sink doesn't support quick profile https://issues.redhat.com/browse/DBZ-7590[DBZ-7590]
* Oracle Connector REST Extension Tests Fail https://issues.redhat.com/browse/DBZ-7597[DBZ-7597]
* Serialization of XML columns with NULL values fails using Infinispan Buffer https://issues.redhat.com/browse/DBZ-7598[DBZ-7598]

A huge thank you to all the contributors from the community who worked on this release:
https://github.com/akulapidAkula[Akula],
https://github.com/akulapid[Akula],
https://github.com/jchipmunk[Andrey Pustovetov],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/Bue-von-hon[Bue Von Hun],
https://github.com/Naros[Chris Cranford],
https://github.com/enzo-cappa[Enzo Cappa],
https://github.com/harveyyue[Harvey Yue],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/james-johnston-thumbtack[James Johnston],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/nrkljo[Lars M. Johansson],
https://github.com/methodmissing[Lourens Naudé],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/MartinMedek[Martin Medek],
https://github.com/mostafaghadimi[Mostafa Ghadimi],
https://github.com/nancyxu123[Nancy Xu],
https://github.com/obabec[Ondrej Babec],
https://github.com/razvanz[Razvan Laurus],
https://github.com/rk3rn3r[René Kerner],
https://github.com/roldanbob[Robert Roldan],
https://github.com/schampilomatis[Stavros Champilomatis],
https://github.com/vjuranek[Vojtech Juranek], and
https://github.com/xmzhou00[Xianming Zhou]!

== Outlook &amp; What's next?

The next few weeks will be focused primarily on stability and bug fixes.
We expect to release Debezium 2.6.0.Final in just under three weeks, so we courage you to download and test the latest Beta and provide your feedback.

If you have any questions or interested in what the roadmap holds for not only 2.6 but also the road to the new Debezium 3.0 later this fall, we encourage you to take a look at our link:/docs/roadmap[road map].
If you have any suggestions or ideas, please feel free to get in touch with us on our https://groups.google.com/forum/#!forum/debezium[mailing list] or in our https://debezium.zulipchat.com/login/#narrow/stream/302529-users[Zulip chat].

And in closing, our very own Mario Vitale will be speaking at https://osday.dev[Open Source Day 2024], where he will talk about https://osday.dev/speakers#mario[Dealing with data consistency - a CDC approach to dual writes].
Please be sure to check out his session on Day 1 as a part of the Beta track at 10:45am!

Until next time...
