---
layout: post
title:  Debezium 2.5.3.Final Released
date:   2024-03-19
tags: [ releases, mongodb, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner, jdbc, informix ]
author: ccranfor
---

We are happy to announce the third maintenance release of the Debezium 2.5 release stream, **Debezium 2.5.3.Final**.
This release includes some improvements and numerous bug fixes, so let's dive right in...

+++<!-- more -->+++

== Breaking changes

The team aims to avoid any potential breaking changes between minor releases; however, such changes are sometimes inevitable.

SQL Server::
The SQL Server connector was not capturing all schemas when the connector was first deployed, and instead, was only capturing the schemas based on the tables defined in the configuration's include list.
This was a bug that could prevent users from easily adding new tables to the connector when expecting that the new table's schema would already exist in the schema history topic.
The connector now correctly honors the `store.only.captured.tables.ddl` configuration option (https://issues.redhat.com/browse/DBZ-7593[DBZ-7593]). +
 +
For existing connector deployments, if you do not specifically set the `store.only.captured.tables.ddl` property for the schema history topic, the connector will begin capturing schema changes for all relevant tables in your database.
If you want to prevent this and retain the prior behavior, you will need to adjust your connector configuration by adding `schema.history.internal.store.only.captured.tables.ddl` with a value of `true`.

== Improvements and changes

=== TRACE level logging for Debezium Server

Debezium Server is a ready-made runtime for Debezium source connectors that uses the Quarkus framework to manage the source and sink deployments.
As most Debezium Server users are aware who have reached out with questions or bugs, we often ask for TRACE-level logs and this has often proven difficult as it requires a full rebuild of Debezium Server due to how minimum logging level is a build-time configuration in Quarkus.

With Debezium 2.5.3.Final and the upcoming Debezium 2.6.0.Final releases, this will no longer be required.
The build time configuration has been adjusted by default to include TRACE logging levels, so moving forward users can simply set the log level to TRACE and restart Debezium Server to obtain the logs (https://issues.redhat.com/brwose/DBZ-7369[DBZ-7369]).

=== Informix appends LSN to Transaction Identifier

Informix databases only increases the transaction identifier when there are concurrent transactions, otherwise the value remains identical for sequential transactions.
This can prove difficult for users who may want to utilize the transaction metadata to order change events in a post processing step.

In Debezium 2.5.3.Final and the upcoming 2.6, Informix will now append the log sequence number (LSN) to the transaction identifier so that users can easily sort change events based on the transaction metadata.
The transaction identifier field will now use the format `<id>:<lsn>` (https://issues.redhat.com/browse/DBZ-7454[DBZ-7454]).
This change affects transaction metadata events and the `source` information block for change events, as shown below:

.Transaction Begin Event
```json
{
  "status": "BEGIN",
  "id": "571:53195829",
  ...
}
```
.Transaction End Event
```json
{
  "status": "END",
  "id": "571:53195832",
  ...
}
```
.Change Events
```json
{
  ...
  "source": {
    "id": "571:53195832"
    ...
  }
}
```

=== PostgreSQL improvements

Updated JDBC driver::
The PostgreSQL driver was upgraded to version 42.6.1.

Improved logging::
During the start-up of the PostgreSQL connector, some users reported the connector stuck or acting as though it could be caught in an infinite loop. (https://issues.redhat.com/browse/DBZ-7581[DBZ-7581]).
The issue appeared that the `pg_replication_slot_advance` was taking longer than the read database timeout, and the exception thrown wasn't satisfactory to identify the problem.
In this case, the logging has been significantly improved to identify this root-cause so that users can make necessary adjustments if they encounter this problem.

== Other changes

Altogether, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%202.5.3.Final%20ORDER%20BY%20component%20ASC[25 issues] were fixed in this release:

* NullPointerException in MongoDB connector https://issues.redhat.com/browse/DBZ-6434[DBZ-6434]
* Numeric default value decimal scale mismatch https://issues.redhat.com/browse/DBZ-7562[DBZ-7562]
* Documentation conflict https://issues.redhat.com/browse/DBZ-7565[DBZ-7565]
* Oracle connector always brings OLR dependencies https://issues.redhat.com/browse/DBZ-7579[DBZ-7579]
* Correct JDBC connector dependencies https://issues.redhat.com/browse/DBZ-7580[DBZ-7580]
* Unavailable Toasted HSTORE Json Storage Mode column causes serialization failure https://issues.redhat.com/browse/DBZ-7582[DBZ-7582]
* Incorrect value of TIME(n) replicate from MySQL if the original value is negative https://issues.redhat.com/browse/DBZ-7594[DBZ-7594]
* Re-select Post Processor not working for complex types https://issues.redhat.com/browse/DBZ-7596[DBZ-7596]
* Serialization of XML columns with NULL values fails using Infinispan Buffer https://issues.redhat.com/browse/DBZ-7598[DBZ-7598]
* Null instead of toast placeholder written for binary types when "hex" mode configured https://issues.redhat.com/browse/DBZ-7599[DBZ-7599]
* Poor snapshot performance during schema snapshot DDL processing https://issues.redhat.com/browse/DBZ-7608[DBZ-7608]
* Re-select post processor performance https://issues.redhat.com/browse/DBZ-7611[DBZ-7611]
* Uncaught exception during config validation in Engine https://issues.redhat.com/browse/DBZ-7614[DBZ-7614]
* Incremental snapshot query doesn't honor message.key.columns order https://issues.redhat.com/browse/DBZ-7617[DBZ-7617]
* Metric ScnFreezeCount never increases https://issues.redhat.com/browse/DBZ-7619[DBZ-7619]
* Upgrade Debezium Server to Quarkus 3.2.10 https://issues.redhat.com/browse/DBZ-7624[DBZ-7624]
* Cassandra can have misaligned Jackson dependencies https://issues.redhat.com/browse/DBZ-7629[DBZ-7629]
* Numeric value without mantissa cannot be parsed https://issues.redhat.com/browse/DBZ-7643[DBZ-7643]
* Fix MySQL image fetch for tests https://issues.redhat.com/browse/DBZ-7651[DBZ-7651]

A big thank you to all the contributors from the community who worked on this release:
https://github.com/samssh[Amirmohammad Sadat Shokouhi],
https://github.com/andreas-ibm[Andreas Martens],
https://github.com/jchipmunk[Andrey Pustovetov],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/Naros[Chris Cranford],
https://github.com/enzo-cappa[Enzo Cappa],
https://github.com/indraraj[Indra Shukla],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/nivolg[Nick Golubev],
https://github.com/razvanz[Razvan Laurus],
https://github.com/roldanbob[Robert Roldan], and
https://github.com/VWagen1989[Sean Wu]!

== Outlook &amp; What's next?

We are only just a few weeks away from the final build of Debezium 2.6.
I would anticipate 2.6.0.CR1 build later in the week, with 2.6.0.Final sometime next week, barring no unforeseen issues.

In a few short weeks, the team will begin to shift focus to what lies ahead with Debezium 2.7.
This will be the last minor release of the Debezium 2.x release stream, which will include read-only incremental snapshots for other connectors, a new dedicated MariaDB source connector, and a MongoDB sink connector, just to name a few highlights.
We will also be carrying over any work from 2.6 that we're still working on but didn't make it into that release.

And in closing, the last half of the year will be focusing on Debezium 3, where we'll be moving to Java 17, work on new time-series source connectors, and more.
Please take a moment and review our link:/docs/roadmap[road map].
If you have any suggestions or ideas, please feel free to get in touch with us on our https://groups.google.com/forum/#!forum/debezium[mailing list] or in our https://debezium.zulipchat.com/login/#narrow/stream/302529-users[Zulip chat].

Until next time...
