---
layout: post
title:  Debezium 2.5.1.Final Released
date:   2024-01-30
tags: [ releases, mongodb, mysql, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner, jdbc ]
author: ccranfor
---

While we remain on track with the upcoming Debezium 2.6 release, we are continuously looking at improvements and fixes that are being made that ensures that older releases continue to provide the best possible experience.
With that, the team is pleased to announce the first maintenance release of Debezium 2.5, **Debezium 2.5.1.Final**.
Let's dive into what this release includes and what you should be aware of while upgrading...

+++<!-- more -->+++

== Breaking changes

The team aims to avoid any potential breaking changes between minor releases; however, such changes are sometimes inevitable.

Re-select Columns Post Processor::

* The re-select columns post processor used the key based on the `message.key.columns` when building the query. This is not correct for most tables with primary keys.
The default behavior has changed and the table primary key is used by default.
A new configuration option was introduced to allow the user to choose between whether to use the primary key or the generated key, `reselect.use.event.key` (https://issues.redhat.com/browse/DBZ-7358[DBZ-7358]).

== Improvements and changes

=== MongoDB post-image changes

The MongoDB connector's event payload can be configured to include the full document that was changed in an update.
The connector previously made an opinionated choice about how the full document would be fetched as part of the change stream; however, this behavior was not consistent with our expectations in all use cases.

Debezium 2.5+ introduces a new configuration option, `capture.mode.full.update.type`, allowing the connector to explicitly control how the change stream's full document lookup should be handled (https://issues.redhat.com/browse/DBZ-7299[DBZ-7299]).
The default value for this option is `lookup`, meaning that the database will make a separate look-up to fetch the full document.
If you are working with MongoDB 6+, you can also elect to use `post_image` to rely on MongoDB change stream's post-image support.

== Other changes

Altogether, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%202.5.1.Final%20ORDER%20BY%20component%20ASC[21 issues] were fixed in this release:

* Connector is getting stopped while processing bulk update(50k) records in debezium server 2.0.1.Final https://issues.redhat.com/browse/DBZ-6955[DBZ-6955]
* Empty object sent to GCP Pub/Sub after DELETE event https://issues.redhat.com/browse/DBZ-7098[DBZ-7098]
* Debezium-ddl-parser crashes on parsing MySQL DDL statement (sub-query with UNION) https://issues.redhat.com/browse/DBZ-7259[DBZ-7259]
* Oracle DDL parsing error in PARTITION REFERENCE https://issues.redhat.com/browse/DBZ-7266[DBZ-7266]
* PostgreSQL ad-hoc blocking snapshots fail when snapshot mode is "never" https://issues.redhat.com/browse/DBZ-7311[DBZ-7311]
* Ad-hoc blocking snapshot dies with "invalid snapshot identifier" immediately after connector creation https://issues.redhat.com/browse/DBZ-7312[DBZ-7312]
* Specifying a table include list with spaces between elements cause LogMiner queries to miss matches https://issues.redhat.com/browse/DBZ-7315[DBZ-7315]
* Debezium heartbeat.action.query does not start before writing to WAL: part 2 https://issues.redhat.com/browse/DBZ-7316[DBZ-7316]
* Oracle connector is occasionally unable to find SCN https://issues.redhat.com/browse/DBZ-7345[DBZ-7345]
* Initial snapshot notifications should use full identifier. https://issues.redhat.com/browse/DBZ-7347[DBZ-7347]
* Debezium fails after table split operation https://issues.redhat.com/browse/DBZ-7360[DBZ-7360]
* MSSQL wrong default values in db schema for varchar, nvarchar, char columns https://issues.redhat.com/browse/DBZ-7374[DBZ-7374]
* Replace additional role binding definition in kubernetes.yml with @RBACRule https://issues.redhat.com/browse/DBZ-7381[DBZ-7381]
* Kinesis Sink Exception on PutRecord https://issues.redhat.com/browse/DBZ-7417[DBZ-7417]
* ParsingException (MariaDB Only): alterSpec drop foreign key with 'tablename.' prefix https://issues.redhat.com/browse/DBZ-7420[DBZ-7420]

A big thank you to all the contributors from the community who worked on this release:
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/brenoavm[Breno Moreira],
https://github.com/Naros[Chris Cranford],
https://github.com/ilyasahsan123[Ilyas Ahsan],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/james-johnston-thumbtack[James Johnston],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/mimaison[Mickael Maison],
https://github.com/wukachn[Peter Hamer],
https://github.com/roldanbob[Robert Roldan],
https://github.com/koneru9999[V K], and
https://github.com/leoloel[leoloel]!

== Outlook &amp; What's next?

The team remains dedicated toward Debezium 2.6 over the next few months.
However, in that time, you can expect that we'll continue to review regressions and bugfixes, and provide maintenance releases for Debezium 2.5.

In the meantime, if you're interested in what the team has in store for Debezium 2.6 and beyond throughout 2024, we encourage you to review our link:/docs/roadmap[road map], which includes details about our path to Debezium 3.0 later this year.
If you have any suggestions or ideas, please feel free to get in touch with us on our https://groups.google.com/forum/#!forum/debezium[mailing list] or in our https://debezium.zulipchat.com/login/#narrow/stream/302529-users[Zulip chat].

We have two upcoming talks later this week at Fosdem 2024 in Brussels.
Ondrej Babec will be speaking about https://fosdem.org/2024/schedule/event/fosdem-2024-2968-performance-testing-and-why-even-the-imperfect-one-is-important/[performance testing and why it's important] and Vojtech Juranek will https://fosdem.org/2024/schedule/event/fosdem-2024-2272-feeding-ml-models-with-the-data-from-the-databases-in-real-time/[use Debezium to feed AI models in real-time].
If you plan to attend, be sure to check out these talks and meet and greet with our Debezium engineers.

Until next time...
