---
layout: post
title:  Debezium 3.0.0.Alpha1 Released
date:   2024-07-11
tags: [ releases, mongodb, mysql, mariadb, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner, jdbc, informix, ibmi ]
author: ccranfor
---

We are happy to announce the first pre-release of Debezium 3, **3.0.0.Alpha1**.
This release, albeit smaller than our normal pre-releases, is highly focused on a few key points, such as testing the release process with Java 17/21; however, it also includes several new features.
Let's take a moment and talk about the upcoming breaking changes in-depth and the new features you will find.

+++<!-- more -->+++

[id="breaking-changes"]
== Breaking changes

With any new major release of software, there is often several breaking changes.
The Debezium **3.0.0.Alpha1** release is no exception, so lets discuss the major changes you should be aware about.

=== Java and Maven requirements changed

This release also shifts the Java requirements needed to both build and run Debezium.
In addition, this release also requires a later version of Maven for building Debezium from source.

If you intend to build Debezium from source for any reason, all Debezium projects require using Java 21 to build and Maven 3.9.8.
This includes the main repository, community-led repositories, Debezium Server, Operator, etc.
If you attempt to build Debezium from source using a version of Java that is less-than Java 21, the build will report a Java version error, instructing you to use Java 21 or higher.

All Debezium connectors require a baseline of **Java 17** for runtime.
This means if you are not building from source but simply deploying the connectors on runtimes such as Kafka Connect, then **Java 17** is sufficient.

If you are using Debezium Server, Debezium Operator, or the Debezium Quarkus Outbox Extension, these components all require **Java 21** for both runtime and build-time.

Please see the following chart from an at-a-glance view of the Java and Maven requirements

.Requirements by component
|===
|Component |Java (Runtime) |Java (Building) |Maven (Building)

|Debezium Server
|Java 21+
|Java 21+
|3.9.8+

|Debezium Operator
|Java 21+
|Java 21+
|3.9.8+

|Debezium Quarkus Outbox Extension
|Java 21+
|Java 21+
|3.9.8+

|Debezium Connectors +
_Embedded Engine or Kafka Connect_
|Java 17+
|Java 21+
|3.9.8+

|===

[id="new-features-and-improvements"]
== New features and improvements

The upgrade to Debezium **3.0.0.Alpha1** introduces several new features and improvements in several components:

[id="new-features-mongodb"]
=== MongoDB

==== MongoDB Sink Connector

Debezium introduced its first sink-based connector in Debezium 2.2, just over a year ago and we're pleased to announce the inclusion of another sink-based connector for MongoDB as a part of Debezium 3.

Unlike the JDBC sink relational connector that requires an additional plug-in to be installed to use it, the MongoDB sink connector is bundled alongside the MongoDB source connector in the same artifact.
So if you have already installed or use the MongoDB source connector and are using Debezium 3 or later, you also have the MongoDB sink connector.

The configuration to get started with the MongoDB is quite straightforward, here's an example:
[source,json]
----
{
  "connector.class": "io.debezium.connector.mongodb.MongoDbSinkConnector",
  "connection.string": "...",
  "topics": "topic1,topic2",
  "sink.database": "targetdb",
}
----

The `connection.string` and `sink.database` configuration properties are mandatory.
These define the details for connecting to the target MongoDB database and the name of the target database where the changes will be written.

Additionally, the `topics` configuration property is mandatory by Kafka Connect, and it describes a comma-separated list of regular expressions for the topics that the sink connector will observe.

[NOTE]
====
Documentation for this connector is still a work-in-progress, so if you have any questions or problems, don't hesitate to reach out to the team on our Zulip chat or Mailing List.
====

[id="other-changes"]
== Other changes

* Debezium postgres jdbc sink not handling infinity values https://issues.redhat.com/browse/DBZ-7920[DBZ-7920]
* JdbcSinkTask doesn't clear offsets on stop https://issues.redhat.com/browse/DBZ-7946[DBZ-7946]
* ibmi as400 connector config isn't prefixed with "database." https://issues.redhat.com/browse/DBZ-7955[DBZ-7955]
* Duplicate downstream annotation comments incorrectly refer to Db2 connector https://issues.redhat.com/browse/DBZ-7968[DBZ-7968]
* Issue with Hybrid mode and DDL change https://issues.redhat.com/browse/DBZ-7991[DBZ-7991]
* Extends process of finding Bundle path https://issues.redhat.com/browse/DBZ-7992[DBZ-7992]
* Incorrect offset/history property mapping generatated  https://issues.redhat.com/browse/DBZ-8007[DBZ-8007]
* Debezium Server Operator on minikube with java.lang.NullPointerException': java.lang.NullPointerException https://issues.redhat.com/browse/DBZ-8019[DBZ-8019]
* ORA-65090: operation only allowed in a container database when connecting to a non-CDB database https://issues.redhat.com/browse/DBZ-8023[DBZ-8023]
* Added type to Prometheus JMX exporter https://issues.redhat.com/browse/DBZ-8036[DBZ-8036]
* Add `kafka.producer` metrics to debezium-server jmx exporter config https://issues.redhat.com/browse/DBZ-8037[DBZ-8037]
* Support FLOAT32 type in debezium-connector-spanner https://issues.redhat.com/browse/DBZ-8043[DBZ-8043]

In total, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20and%20fixVersion%20%20in%20(3.0.0.Alpha1)[20 issues] were resolved in Debezium 3.0.0.Alpha1.
The list of changes can also be found in our https://debezium.io/releases/3.0[release notes].

A big thank you to all the contributors from the community who worked diligently on this release:
https://github.com/andreas-ibm[Andreas Martens],
https://github.com/arawind[Aravind],
https://github.com/Naros[Chris Cranford],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/obabec[Ondrej Babec],
https://github.com/rk3rn3r[René Kerner],
https://github.com/missingcharacter[Ricardo Rosales],
https://github.com/roldanbob[Robert Roldan],
https://github.com/ryanvanhuuksloot[Ryan van Huuksloot], and
https://github.com/ShuranZhang[Shuran Zhang]!

[id="whats-next"]
== What's next &amp; Outlook

With Debezium 2.7.0.Final released, we're actively looking at the reports from the community and addressing any critical bugs or regressions that were not identified throughout development.
If you believe you've spotted a bug or regression, please log a https://issues.redhat.com/projects/DBZ[Jira issue] so that these can be tracked and addressed.
Of course, contributions for these are much appreciated, if you have the bandwidth.

While this pre-release is smaller than we generally prefer, it's focus was primarily on the inclusion of the MongoDB sink connector and the move to Java 17/21.
There are still many features in the pipeline that will be coming in a future build of Debezium, including but not limited to:

* Kafka 3.1+ as baseline
* New off-heap Oracle cache implementations based on EhCache & Hazelcast
* Exactly-once semantics support for other relational connectors
* and more

This list represents a quick glance view at just what's at the top of our queue, and is subject to change.
If you'd like to get involved in the conversation about Debezium 3.0 and the next evolution of the project, contact us on the https://groups.google.com/g/debezium[mailing list] or https://debezium.zulipchat.com/login/#narrow/stream/302529-users[Zulip chat].
As always, please review our https://debezium.io/roadmap[road map] for more details.

For now, that's it from our side, enjoy the summer and be safe!
Until next time...