---
layout: post
title:  Debezium 2.7.3.Final Released
date:   2024-09-23
tags: [ releases, mongodb, mysql, mariadb, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner, jdbc, informix, ibmi ]
author: ccranfor
---

I am happy to announce the third maintenance release of the Debezium 2.7 release stream, **2.7.3.Final**.
This maintenance release focuses on addressing stability and regressions, with several improvements.
Let's dive into these changes...

+++<!-- more -->+++

[id="new-features-and-improvements"]
== New features and improvements

Debezium 2.7.3.Final introduces a couple improvements and features, lets take a look at each individually.

=== MariaDB 11.4.3

Debezium 3 also introduces support for the most recent non-rolling release of MariaDB, 11.4.3 (https://issues.redhat.com/browse/DBZ-8226[DBZ-8226]).
We are also closing monitoring the MariaDB 11.6 release cycle and plan to introduce vector data type support when MariaDB 11.6 becomes stable.

=== Oracle offline RAC node flush improvements

In recent improvements to the Oracle RAC node flush strategy, it was determined that a three-second delay was being forced when an Oracle RAC node was taken offline by the database administrator.
Since an Oracle RAC node cannot perform any writes to the redo logs while offline, this three-second delay introduced an unnecessary amount of latency while the node remained offline.

In Debezium 3, the three-second delay is only imposed if a connection is active to an Oracle RAC node; however, the flush SQL operation was unsuccessful.
This means that when database administrators take RAC nodes offline for maintenance, no latency overhead will be imposed by the connector (https://issues.redhat.com/browse/DBZ-8177[DBZ-8177]).

[id="other-fixes"]
== Other fixes

* Make ORA-00600 - krvrdccs10 automatically retriable https://issues.redhat.com/browse/DBZ-5009[DBZ-5009]
* DDL statement couldn't be parsed: REVOKE IF EXISTS https://issues.redhat.com/browse/DBZ-8209[DBZ-8209]
* Oracle TableSchemaBuilder provides wrong column name in error message https://issues.redhat.com/browse/DBZ-8217[DBZ-8217]
* Implement separate source and sink connector sections in documentation navigation https://issues.redhat.com/browse/DBZ-8220[DBZ-8220]
* Debezium does not restart automatically after throwing an ORA-00600 krvrdccs30 error https://issues.redhat.com/browse/DBZ-8223[DBZ-8223]
* JDBC sink doesn't include fields as per documentation https://issues.redhat.com/browse/DBZ-8224[DBZ-8224]
* Broken link to Streams doc about configuring logging  https://issues.redhat.com/browse/DBZ-8231[DBZ-8231]
* Document passthrough hibernate.* properties for the JDBC connector https://issues.redhat.com/browse/DBZ-8232[DBZ-8232]
* Unbounded number of processing threads in async engine https://issues.redhat.com/browse/DBZ-8237[DBZ-8237]
* Streaming metrics are stuck after an ad-hoc blocking snapshot https://issues.redhat.com/browse/DBZ-8238[DBZ-8238]
* DDL statement couldn't be parsed with IF EXISTS https://issues.redhat.com/browse/DBZ-8240[DBZ-8240]
* Random engine factory used by default https://issues.redhat.com/browse/DBZ-8241[DBZ-8241]
* Support BLOB with EMPTY_BLOB() as default https://issues.redhat.com/browse/DBZ-8248[DBZ-8248]
* AbstractConnectorTest consumeRecordsUntil may prematurely exit loop https://issues.redhat.com/browse/DBZ-8250[DBZ-8250]

In total there were https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20and%20fixVersion%20%20in%20(2.7.3.Final)[17 issues] resolved in Debezium 2.7.3.Final.
The list of changes can also be found in our https://debezium.io/releases/2.7[release notes].

A big thank you to all the contributors from the community who worked diligently on this release:
https://github.com/m8719-github[Andrei Leibovski],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/Naros[Chris Cranford],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/zalmane[Oren Elias],
https://github.com/roldanbob[Robert Roldan],
https://github.com/vjuranek[Vojtech Juranek], and
https://github.com/msillence[martin]!
