---
layout: post
title:  Debezium 3.2.5.Final Released
date:   2025-12-01 00:00:00 -0600
tags: [ releases, mongodb, mysql, mariadb, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner, jdbc, informix, ibmi ]
author: ccranfor
extraClasses: release-v2
---

Debezium 3.2.5.Final is now available with important fixes and stability improvements across multiple database connectors.

+++<!-- more -->+++

In this post, we're going to take a deep dive into the improvements made across several key modules of Debezium, discussing any new features, and explaining any changes that could impact your upgrade process.
As always, we recommend you read the link:/releases/3.2/release-notes#release-3.2.5-final[release notes] to learn about all the bugs that were fixed, update procedures, and more.

[id=new-features-and-improvements]
== New features and improvements

Let's cover some noteworthy improvements and changes in 3.2.5.Final.

=== Oracle low watermark calculation no longer causes performance loss

When an Oracle LogMiner mining step completes, the Debezium Oracle connector needs to calculate the next starting position for mining.
When `lob.enabled` is set to `false` (the default), it was observed that this calculation was too conservative, and could lead to a regression in performance.

This regression has been fixed, and the connector should once again resume reading changes without the low watermark calculation causing performance loss (https://issues.redhat.com/browse/DBZ-9664[DBZ-9664]).

=== Oracle heartbeats no longer stop when mining returns no data

The Debezium Oracle connector recently introduced an experimental feature using Common Table Expression (CTE) queries to allow another way to optimize the data fetch from Oracle LogMiner.
However, the community reported that when using this feature, if the query returned no events, Debezium stopped emitting heartbeat events.

This has been fixed, and users should observe that heartbeat events should always be emitted by the Oracle connector, even if the mining pass fetched no data (https://issues.redhat.com/browse/DBZ-9443[DBZ-9443]).

=== SQL Server incremental snapshots now resume after restart

When an incremental snapshot was in progress for a SQL Server connector, if a rebalance or connector restart was triggered for any reason, any in-progress incremental snapshot would fail to resume upon restart.
This is unintended and was due to regression in the handling of the connector's offsets during incremental snapshots.

This issue is fixed for SQL Sever, and we identified that no other connector was impacted by this regression.
SQL Server users should now observe that if the connector is restarted during an incremental snapshot, the snapshot resumes upon restart as intended (https://issues.redhat.com/browse/DBZ-9533[DBZ-9533]).

[id=other-fixes]
== Other fixes

* Can bind a LONG value only for insert into a LONG column https://issues.redhat.com/browse/DBZ-8276[DBZ-8276]
* Table column metadata is not fetched when table name has a '/' character https://issues.redhat.com/browse/DBZ-9620[DBZ-9620]
* MySQL connector does not parse CREATE TABLE https://issues.redhat.com/browse/DBZ-9623[DBZ-9623]

In total, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20and%20fixVersion%20%20in%20(3.2.5.Final)[7 issues] were resolved in Debezium 3.2.5.Final.
The list of changes can also be found in our https://debezium.io/releases/3.2/release-notes[release notes].

A big thank you to all the contributors from the community who worked diligently on this release:
 +
https://github.com/AlvarVG[Alvar Viana Gomez],
https://github.com/Naros[Chris Cranford],
https://github.com/kmos[Giovanni Panice],
https://github.com/HongqunXia[Hong Xia],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/ochedru[Olivier Chédru],
https://github.com/roldanbob[Robert Roldan], and
https://github.com/rptroberts[rptroberts]!