---
layout: post
title:  Debezium 3.4.0.Final Released
date:   2025-12-16
tags: [ releases, mongodb, mysql, mariadb, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner, jdbc, informix, ibmi, cockroachdb ]
author: ccranfor
extraClasses: release-v2
---

As we close our 2025 and the team takes a well deserved break for the holidays with friends and family, we're pleased to announce the immediate availability of **Debezium 3.4.0.Final**, the next minor release milestone.
This release includes over _125 new features, improvements, and fixes_ across the entire Debezium project portfolio.

+++<!-- more -->+++

In this post, we're going to take a deep dive into all the changes in Debezium 3.4, discussing new features, and explaining all the possible changes that could have any impact to your upgrade process.
As always, we recommend you read the link:/releases/3.4/release-notes#release-3.4.0-final[release notes] to learn about all the bugs that were fixed, update procedures, and more.

* link:#breaking-changes[Breaking changes]
* link:#new-features-and-improvements[New features and improvements]
* link:#other-changes[Other changes]
* link:#whats-next[What's next?]


[id=breaking-changes]
== Breaking changes

With any new release of software, there is often several breaking changes.
This release is no exception, so let's discuss the major changes you should be aware of before upgrading to **Debezium 3.3.0.Final**.

[cols="1,1"]
|===
| link:#breaking-changes-ibmi[Debezium for IBMi]
| link:#breaking-changes-oracle[Debezium for Oracle]
| link:#breaking-changes-postgres[Debezium for PostgreSQL]
| link:#breaking-changes-sqlserver[Debezium for SQL Server]
|===


[id=breaking-changes-ibmi]
=== Debezium for IBMi

==== String-based default values trimmed automatically

The IBMi connector will now automatically trim both leading and trailing whitespaces for string-based fields that have default values.
In previous versions, trimming was not performed and the default value was provided as maintained by the database.

We understand that this behavior change may not be desired in all environments, and therefore it can be customized.
A new configuration property `trim.non.xml.charsequence.field.mode` can be used to adjust the behavior as needed (https://issues.redhat.com/browse/DBZ-8835[DBZ-8835]).

`both`::
The connector default behavior, which will trim both leading and trailing whitespaces.
`leading`::
The connector will trim leading whitespaces only.
`trailing`::
The connector will trim trailing whitespaces only.
`none`::
The connector will not perform any whitespace trimming.
This option should be used if you wish to preserve the older connector behavior during the upgrade process.


[id=breaking-changes-oracle]
=== Debezium for Oracle

==== XML dependencies included by default

The Debezium Oracle connector now ships with the XDB and XMLParserV2 libraries as part of the community plugin distribution artifacts.
This simplifies the process for capturing XML column types as community users no longer need to download and install these dependencies separately (https://issues.redhat.com/browse/DBZ-9587[DBZ-9587]).


[id=breaking-changes-postgres]
=== Debezium for PostgreSQL

==== PostgreSQL 13 support has ended

With PostgreSQL 13 being sunset, the Debezium project will no longer test nor support PostgreSQL 13 in this and future releases (https://issues.redhat.com/browse/DBZ-9376[DBZ-9376]).
While Debezium frequently sunsets support for older database versions, most often Debezium remains compatible with these older database versions for extended periods of time.

==== Configurable flush strategy changes

A new configuration option was added for PostgreSQL users called `lsn.flush.mode`.
This option provides more control over the replication slot flush strategy (https://issues.redhat.com/browse/DBZ-9641[DBZ-9641]).
This configuration option replaces `flush.lsn.source`, which is now deprecated and will be removed in a future update.


[id=breaking-changes-sqlserver]
=== Debezium for SQL Server

==== Streaming query mode changed

In previous builds, the SQL Server connector used `function` as the default value for `data.query.mode`.
This meant that Debezium relied on SQL Server's built-in functions to provide the list of changes for a given table.

The default for `data.query.mode` has changed in Debezium 3.4, and is now `direct` (https://issues.redhat.com/browse/DBZ-9394[DBZ-9394]).
This uses a more efficient query that is built by Debezium for collecting changes for tables.

If you would like to restore the old behavior, please set `data.query.mode` to `function` in your connector configuration.


[id=new-features-and-improvements]
== New features and improvements

The following describes all noteworthy new features and improvements in **Debezium 3.4.0.Final**.
For a complete list, be sure to read the link:/releases/3.4/release-notes#release-3.4.0-final[release notes] for more details.

[cols="1,1,1"]
|===

| link:#new-features-and-improvements-core[Debezium Core]
| link:#new-features-and-improvements-ibmi[Debezium for IBMi]
| link:#new-features-and-improvements-mongodb[Debezium for MongoDB]

| link:#new-features-and-improvements-oracle[Debezium for Oracle]
| link:#new-features-and-improvements-postgres[Debezium for PostgreSQL]
| link:#new-features-and-improvements-quarkus[Debezium for Quarkus]

| link:#new-features-and-improvements-sqlserver[Debezium for SQL Server]
| link:#new-features-and-improvements-vitess[Debezium for Vitess]
| link:#new-features-and-improvements-jdbc[Debezium JDBC sink]

| link:#new-features-and-improvements-server[Debezium Server]
|
|

|===


[id=new-features-and-improvements-core]
=== Debezium Core

==== Kafka 4.1.1 support

Debezium 3.4 is based on the latest stable release of Kafka, version 4.1.1  (https://issues.redhat.com/browse/DBZ-9709[DBZ-9709]), released in November 2025.
Kafka has fixed https://issues.apache.org/jira/browse/KAFKA-19758[KAFKA-19758], a class loading regression reported by the Debezium community, that prevented Debezium from working with Kafka 4.1.

[TIP]
====
Please be sure to avoid updating to Kafka 4.1.0.
We recommend anyone who intends to update your Kafka ecosystem while staying on older Debezium builds, skip 4.1.0 and go directly to 4.1.1.

Debezium 3.4.0.Final or later is required if you intend to target Kafka 4.1.0 and not 4.1.1 or later.
====

==== OpenLineage improvements

Several users reported issues when `openlineage.integration.enabled` was set to `false`, Debezium was still trying to resolve OpenLineage features.
This could lead to undesirable `IllegalStateException` errors while trying to initialize OpenLineage, although it was not enabled.

Debezium now respects the `openlineage.integration.enabled` configuration property and will no longer attempt to perform any OpenLineage setup or initialization when set to `false` (https://issues.redhat.com/browse/DBZ-9504[DBZ-9504]).

Additionally, we have made several changes to how OpenLineage transforms manage state to minimize the impact of the class loading regression https://issues.apache.org/jira/browse/KAFKA-19758[KAFKA-19758].
If your Kafka ecosystem must use Kafka 4.1.0, _Debezium 3.4+ will be required to work correctly with Kafka 4.1.0_ (https://issues.redhat.com/browse/DBZ-9541[DBZ-9541]).

==== Large schema memory guards

For every table that a connector maintains schema history for and/or captures, Debezium maintains a model in-memory that describes the primary keys, columns, column types, and other attributes after the table.
In large environments where a connector is managing hundreds to tens of thousands of tables, the memory footprint for the in-memory relational model can be quite large.

To address these concerns, users can opt-in and configure limits to minimize the potential for `OutOfMemoryError` issues (https://issues.redhat.com/browse/DBZ-9427[DBZ-9427]).
These new configuration properties include the following:

`guardrail.collections.max`:: Specifies the maximum number of tables that the connector can capture.
Exceeding this limit triggers the action specified by `guardrail.collections.limit.action`.
Setting this property to `0` (the default) prevents the connector from triggering the guardrail action.

`guardrail.collections.limit.action`:: Specifies the action to trigger if the number of tables that the connector captures exceeds the number specified in `guardrails.collections.max`.
The property can be set to `fail` to report an exception or `warn` (the default) to log a warning.

These settings help avoid misconfigurations or malicious setups that lead to downtime or memory issues.
These are particularly useful for end users who want to avoid accidental crashes or for managed service vendors who use Debezium to minimize infrastructure risks.

==== New geometry coordinate system swap transformation

Not every source uses the same coordinate system to represent geometry and geography data.
In some sources, they prefer (longitude latitude) while others prefer (latitude longitude), similarly to (x y) versus (y x).

This inconsistency is prevalent in databases when replicating geometry data, so it's critical to understand not only how the source serializes the data, but equally important how the target database expects the coordinates to be provided.
For example, if your source uses (x y), and the target database expects (y x), incorrectly serializing the data to the target database will mean applications that read the geometry data will have inverted coordinates.

To make working with geometry data easier and to avoid needing to convert the byte data manually, Debezium introduces a new `SwapGeometryCoordinates` transformation specifically for this purpose (https://issues.redhat.com/browse/DBZ-9556[DBZ-9556]).
This transform is extremely important when you are emitting geometry data from one source like PostgreSQL and writing the data to Oracle where they use opposite coordinate systems.

.Example connector transform configuration
[source,json]
----
{
  "transforms": "swapcoords",
  "transforms.swapcoords.type": "io.debezium.transforms.SwapGeometryCoordinates",
  "transforms.swapcoords.srids": "4326,3857,4269"
}
----

By default, the transform will only swap the coordinates for geometry fields with a spatial reference identifier of `4326`, `3857`, or `4269`.
The list of spatial reference identifiers can be adjusted to your needs through configuration.

[IMPORTANT]
====
The transformation is designed to swap the coordinates for all encoded geometry types as long as the spatial reference identifier in the field's `Struct` matches on of the spatial references in the SRID list.
It's the sole responsibility of the user to understand the differences in the coordinate systems used by the source and target to determine if the transformation is necessary.
====

==== New Geometry format conversion transformation

The new `GeometryFormatTransformer` transformation allows for the conversion of `io.debezium.data.Geometry` or `io.debezium.data.Geography` logical types between Well-Known Binary (WKB) and Extended Well-Know Binary (EWKB) formats (https://issues.redhat.com/browse/DBZ-9575[DBZ-9575]).
To get started with this transformation, simply add it to your connector configuration

.Example connector transform configuration
[source,json]
----
{
  "transforms": "geo-format",
  "transforms.geo-format.type": "io.debezium.transforms.GeometryFormatTransformer",
  "transforms.geo-format.format": "WKB"
}
----

In the above example, if a geometry logical type field contains serialized bytes using the EWKB format, that value will be converted to use WKB instead.
See the https://debezium.io/documentation//reference/transformations/geometry-format-transformer.html[documentation] for more details.

==== Timezone conversion support for source info block fields

The `ConvertTimezone` SMT has been a great addition for specific use cases where the community has wanted to shift the values of timestamps by timezone offsets.
However, this transformation's capabilities were limited to very specific Debezium logical field types.

A common community request was to extend the transformation to support additional fields in the event's `source` information block.
In Debezium 3.4, the  `ts_ms`, `ts_us`, and `ts_ns` fields from the `source` information block are eligible fields that can be converted (https://issues.redhat.com/browse/DBZ-9372[DBZ-9372]).

Please see the https://debezium.io/documentation/reference/3.4/transformations/timezone-converter.html[ConvertTimezone documentation] for more details.


[id=new-features-and-improvements-ibmi]
=== Debezium for IBMi

==== Incremental snapshot support

The incremental snapshot feature is an integral part of Debezium's toolkit, which allows for on-demand, concurrent, resumable, and targeted snapshot/backfill of historical data for one or more tables (https://issues.redhat.com/browse/DBZ-7958[DBZ-7958]).
In Debezium 3.4, this feature is now supported by the Debezium for IBMi connector.

==== Multi-journal support

The IBMi database allows for the assignment of different journals to multiple tables under the same schema.
To address this unique database behavior and to provide sufficient context for correctly ordering events across a database, the IBMi connector's `source` information block now includes information about the journals receiver file name, receiver library, entry's timestamp, and sequence number (https://issues.redhat.com/browse/DBZ-9291[DBZ-9291]).


[id=new-features-and-improvements-mongodb]
=== Debezium for MongoDB

==== Support MongoDB wall clock time

In MongoDB 6+, `wallTime` was added to MongoDB change stream events to represent the server's date and time when a database operation occurred, specifically when the transaction was committed or the operation completed.
This is slightly different from `clusterTime`, which is when the entry was added to the database's oplog.

Starting with Debezium 3.4, the `ts_ms`, `ts_us`, and `ts_ns` source information block fields will be based on the `wallTime` if it's available in the change event.
If the `wallTime` is unavailable, the connector will fall back to `clusterTime` (https://issues.redhat.com/browse/DBZ-9683[DBZ-9683]).


[id=new-features-and-improvements-oracle]
=== Debezium for Oracle

==== LogMiner metrics improvements

We have added and adjusted several Oracle LogMiner JMX metrics to provide better information and clarify about the connector's health and performance.

===== Commit throughput and related metrics changes

Previously, the LogMiner `CommitThroughput` JMX metric was calculated over the connector's entire runtime, which meant extended periods of inactivity would progressively reduce the reported throughput value.
This approach proved unhelpful for users trying to gauge the actual throughput achieved during active change emission from Oracle's transaction buffer to Kafka.

To address this, the calculation of `CommiThroughput` has changed to focus exclusively on the commit duration window, delivering a more precise measure of the connector's capacity to queue changes for Kafka delivery (https://issues.redhat.com/browse/DBZ-9639[DBZ-9639]).

[TIP]
====
A declining value over time may indicate that your `QueueRemainingCapacity` has hit `0`, suggesting you should consider adjusting the outbound queue configuration or review your throughput to your target system.
====

Additionally, to align with metrics from other LogMiner processing stages, we've introduced a new JMX metric named `TotalCommitTimeInMilliseconds`.
This metric tracks the aggregate time spent executing the commit loop since the connector's current startup (https://issues.redhat.com/browse/DBZ-9637[DBZ-9637]).

===== New metrics

In some troubleshooting scenarios, it's often useful to understand what redo log positions are used by Debezium's Oracle connector.
To obtain this information requires increasing the connector's logging verbosity, which is not always feasible in a production environment.

In addition, Debezium introduced a separation between the mining log range and the data read range to improve performance and address a number of outstanding issues in https://issues.redhat.com/browse/DBZ-8747[DBZ-8747] for the LogMiner adapter.
To compliment that change, we have added these ranges to the existing breadth of connector streaming metrics.

[cols="30%,15%,65%"]
|===
|Metric Name |Type |Description

|MiningSessionLowerBounds
|BigInteger
|The system change number used as the LogMiner session lower boundary.

|MiningSessionUpperBounds
|BigInteger
|The system change number used as the LogMiner session upper boundary.

|MiningFetchLowerBounds
|BigInteger
|The system change number currently used as the LogMiner fetch query lower boundary.

|MiningFetchUpperBounds
|BigInteger
|The system change number currently used as the LogMiner fetch query upper boundary.

|===

[TIP]
====
The `MiningSession*` metrics represent the range that redo logs are gathered between while the `MiningFetch*` metrics represent the range Debezium requests to read the redo logs.
While Debezium may request a specific range, LogMiner may opt to read outside the fetch range but within the session range to satisfy transaction stitching needs.
====

==== Subset database replication supported

Debezium has long recommended that the best supplemental logging configuration is to enable minimum supplemental logging mode at the database level and use granular "all column" logging per table.
This minimizes the volume of data recorded in your database transaction logs and improves the overall performance of Debezium.

In Oracle 21, a new supplemental logging mode was introduced called `SUBSET DATABASE REPLICATION`, which acts as a replacement for the previously used Minimum Supplemental Logging Mode.
This new logging more is now recognized and treated as an equivalent to the minimal supplemental logging mode, allowing users to set one or the other rather than both (https://issues.redhat.com/browse/DBZ-7341[DBZ-7341]), simplifying the setup required for capturing changes using LogMiner.

==== Manually discard in-progress transactions via signals

The Oracle connector is a bit unique in that it must buffer all events for a transaction before the transaction can be emitted as change events when using LogMiner.
In some situations, users have found where a large or long-running transaction is being buffered, but it's not changing any tables that are being captured.
Currently, you need to wait for the transaction commit or rollback to be observed or the transaction buffer retention to be met.

A new Oracle-specific signal called `drop-transaction` can be used to specifically discard an in-progress transaction (https://issues.redhat.com/browse/DBZ-9552[DBZ-9552]).

.Example discard transaction signal
[source,sql]
----
INSERT INTO the_signal_table
VALUES ('my-signal-id', 'drop-transaction', '{"transaction-id": "<the-database-trx-id>"}');
----

When this signal is processed, Debezium will locate the transaction in the buffer, and if it exists, the transaction will be abandoned immediately rather than waiting for the transaction buffer retention if configured.

==== Configurable LogMiner performance options

An Oracle database is configured by database administrators with a variety of session default values.
Many of these settings control a variety of session behaviors, including the amount of resources the connection can consume when executing queries or running PL/SQL programs.
Two most notable database parameters are:

`hash_area_size`:: This specifies the maximum amount of memory, in bytes, to be used when performing hash joins.
`sort_area_size`:: This specifies the maximum amount of memory, in bytes, to be used when performing query sorts.

Normally these values are set automatically by the database sizing configuration and should not be altered.
However, there are some corner cases where adjusting these values can help improve specific queries and performance, including the log mining pass used by Debezium.

To adjust these two options, the Debezium Oracle connector provides two _internal_, _experimental_ properties:

`internal.log.mining.hash.area.size`:: Specifies the maximum amount of memory, in bytes, to be used for hash joins.
`internal.log.mining.sort.area.size`:: Specifies the maximum amount of memory, in bytes, to be used for query sorts.

[WARNING]
====
Careful consideration should be taken before setting these configuration options.
In situations where these values are set too large, this can create stability issues in the database.

You should consult your database administrator before setting these.
====

==== Performance improvements

When an Oracle LogMiner mining step completes, the connector needs to calculate the next starting position for mining.
When `lob.enabled` is set to `false` (the default), it was observed that this calculation was too conservative, and could lead to a regression in performance.
This regression affected a variety of Debezium 3.2, 3.3, and 3.4 preview builds.

The connector should once again resume reading changes without the low watermark calculation causing performance loss (https://issues.redhat.com/browse/DBZ-9664[DBZ-9664]).
This fix has been included in Debezium 3.4.0.Final, 3.3.2.Final, and 3.2.5.Final.

==== Heartbeats no longer stop when using CTE queries

The Debezium Oracle connector recently introduced an experimental feature using Common Table Expression (CTE) queries to allow another way to optimize the data fetch from Oracle LogMiner.
However, the community reported that when using this feature, if the query returned no events, Debezium stopped emitting heartbeat events.

This has been fixed, and users should observe that heartbeat events should always be emitted by the Oracle connector, even if the mining pass fetched no data (https://issues.redhat.com/browse/DBZ-9443[DBZ-9443]).

==== Active transaction identifiers included in stale offset warning

When the Oracle connector writes to the log file, _"Offset SCN X has not advanced in Y mining sessions..."_, users are often concerned about what this means and exactly do they determine what transactions are active.

This log message was adjusted to not only make it clearer, but to include all the current active transaction identifiers, making it easy for users to work with their DBA team to understand why there are long-running transactions (https://github.com/debezium/dbz/issues/20[debezium/dbz#20]).

The log message will now read, _"Offset SCN X has not changed in Y mining session iterations. This may indicate long-running transaction(s), active transactions: <list of transaction ids>. Commit SCN: <commit details>"_.

==== Transaction retention improvements

For users who use `log.mining.transaction.retention.ms`, there was an issue that indicated after transactions were evicted from the buffer due to the retention policy, the connector was not properly calculating several key metrics and values (https://issues.redhat.com/browse/DBZ-9659[DBZ-9659]).
This specific regression led to several metrics to report incorrect values, and moreover to LogMiner re-reading data that it should have otherwise skipped.

[IMPORTANT]
====
While this did not introduce any data issues, it did introduce a performance penality that could add up over time in high-traffic systems that we're happy to have resolved.
====


[id=new-features-and-improvements-postgres]
=== Debezium for PostgreSQL

==== Support for PostgreSQL 18

The next major milestone for the PostgreSQL database was released in September 2025, version 18.0.
We're pleased to announce that Debezium is now tested and compatible with PostgreSQL 18 (https://issues.redhat.com/browse/DBZ-9523[DBZ-9523]).

==== AWS IAM authentication support

You can now specify user credentials that will be validated using the AWS AIM authentication process.
This feature, while present for MySQL, is now available for PostgreSQL connector users.

.Prerequisites
* Add the https://github.com/aws/aws-advanced-jdbc-wrapper[AWS Advanced JDBC Wrapper] to your connector's plugin directory or class path. +
You can find more information about this process https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheIamAuthenticationPlugin.md[here].
* Add the connector configuration property `database.connection.factory.class` in the connector configuration. +
Set the value to `io.debezium.connector.postgresql.connection.PostgresAwsIamConnectionFactory`.

With this configuration, the connector credentials will be validated against AWS IAM rather than the database (https://issues.redhat.com/browse/DBZ-7297[DBZ-7297]).

==== Improved LSN flushing strategy

In previous versions, users often let Debezium control when the LSN was flushed to the replication slot using `flush.lsn.source`; however, users could set this `false` and control the flush manually outside of Debezium.

To expand on this functionality, a new connector configuration `lsn.flush.mode` was added to provide an extended ways to control how the LSN is flushed to PostgreSQL during the connector's lifecycle (https://issues.redhat.com/browse/DBZ-9641[DBZ-9641]).
This new property can be set to one of the following options:

`connector`:: Specifies that the Debezium PostgreSQL connector controls when the LSN is flushed to the replication slot.
This is the same behavior as the deprecated `flush.lsn.source` option when set to `true`.

`manual`:: Specifies that the Debezium PostgreSQL connector no longer controls when the LSN is flushed to the replication slot and that it must be performed manually or externally to the connector.
This is the same behavior as the deprecated `flush.lsn.source` option when set to `false`.

`connector_and_driver`:: Specifies a new mode where both the Debezium PostgreSQL connector and the PostgreSQL JDBC driver manage when the LSN is flushed to the replication slot.
Debezium will flush as it processes events while the driver will flush during idle periods based on the server keepalive messages.

[NOTE]
====
The `flush.lsn.source` configuration option is deprecated, and will be removed in a future release.
Please be sure to adjust your configuration accordingly if using the old option.
====


[id=new-features-and-improvements-quarkus]
=== Debezium for Quarkus

==== Debezium as a Quarkus DevService

One of the biggest features of this release includes the new Debezium Quarkus Extension modules.
The extension modules provide a complete change data capture solution using Quarkus techniques and best practices, and most importantly, this can all be done as a native application!

Our initial debut of this feature includes support for PostgreSQL (https://issues.redhat.com/brwose/DBZ-8902[DBZ-8902]), MongoDB (https://issues.redhat.com/browse/DBZ-9432[DBZ-9432]), MySQL (https://issues.redhat.com/browse/DBZ-9380[DBZ-9380]), MariaDB (https://issues.redhat.com/browse/DBZ-9381[DBZ-9381]), and SQL Server (https://issues.redhat.com/browse/DBZ-9384[DBZ-9384]) connectors.
For other database platforms, those are planned and you should see those phased in throughout the early part of 2026.

To get started using Debezium as a Quarkus DevService, the specific connector dependency needs to be added to your Quarkus application's dependencies.
Depending on your Quarkus version, these dependencies may be part of the existing Quarkus BOM, but if they are not, you can add these manually.

.Example adding a connector dependency
[source,xml]
----
<dependency>
  <groupId>io.debezium.quarkus</groupId>
  <artifactId>quarkus-debezium-mongodb</artifactId>
  <version>3.4.0.Final</version>
</dependency>
----

With the dependency added to your Quarkus project, you can now use the extension to capture changes with just a few configuration properties in your `application.properties` file, e.g.

.Example MongoDB configuration in application.properties
[source,properties]
----
quarkus.debezium.devservices.mongodb.enabled=true

quarkus.debezium.offset.storage=org.apache.kafka.connect.storage.MemoryOffsetBackingStore
quarkus.debezium.name=native
quarkus.debezium.topic.prefix=integration
quarkus.debezium.database.include.list=test
quarkus.debezium.snapshot.mode=initial
quarkus.mongodb.connection-string=mongodb://native:native@127.0.0.1:27017/?replicaSet=rs0
----

Capturing changes from MongoDB as simple as creating a Quarkus bean with the right annotations.

.Quarkus Debezium MongoDB change event bean
[source,java]
----
@ApplicationScoped
public class MongoDbChangeEventHandler {
    @Capturing
    public void handleChanges(RecordChangeEvent<SourceRecord> event) throws Exception {
        // your custom change event handler logic
    }
}
----

==== Multiple Debezium DevServices in a Quarkus application

In a Quarkus application, users can read data from multiple sources using a variety of Quarkus ready services, such as Hibernate using JPA.
So it raises a very valid question, why can't Debezium's Quarkus extension services?

In Debezium 3.4, this is now a reality!

In a single Quarkus application using Debezium's Quarkus extension, you can now capture changes from two or more independent Debezium connector services.
This enables a variety of application use cases, e.g., where data is aggregated to produce a data stream for warehousing or caches.
It can also be used to publish or emit enriched events from those multiple sources to any number of consumers or consumer types.

To get started, annotate your event observers using the `@Engine` annotation or `@DefaultEngine` annotation, e.g.

.Example snapshot event listeners
[source,java]
----
@ApplicationScoped
public class DefaultSnapshotEventObserver {
  public void handleSnapshotEvent(@Observes @Engine("default") SnapshotEvent event) {
  }
}

@ApplicationScoped
public class AlternativeSnapshotEventObserver {
  public void handleSnapshotEvent(@Observers @Engine("alternative") SnapshotEvent event) {
  }
}
----

With this pattern, multiple Debezium configurations can be added to your `application.properties` using the standard Quarkus naming pattern, e.g.

.Example application.properties
[source,properties]
----
quarkus.debezium.name=native-default
quarkus.debezium.topic.prefix=default
quarkus.debezium.plugin.name=pgoutput
quarkus.debezium.snapshot.mode=initial
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=native
quarkus.datasource.password=native
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/native

quarkus.debezium.capturing.alternative.name=native-alternative
quarkus.debezium.capturing.alternative.topic.prefix=alt
quarkus.debezium.capturing.alternative.plugin.name=pgoutput
quarkus.debezium.capturing.alternative.snapshot.mode=initial
quarkus.datasource.alternative.db-kind=postgresql
quarkus.datasource.alternative.username=native
quarkus.datasource.alternative.password=native
quarkus.datasource.alternative.jdbc.url=jdbc:postgresql://localhost:5432/native-alt

quarkus.datasource.devservices.enabled=false
----

In this trivial example, we've configured two independent data sources, each used by different Debezium Quarkus extension instances running all within the same Quarkus application.

What makes this feature really useful is that while the trivial example gathers changes from two independent PostgreSQL databases, the same can be done across database vendor boundaries.
By using two or more source connector extensions, you can gather changes from different vendor sources and handle those streams however you like.

[NOTE]
====
When using the Multiple Debezium DevService feature in your Quarkus applications, please note that if you are capturing changes from two independent vendor sources, all connector components must use the same base Debezium version.

In other words, it's not possible to use Debezium 3.4 for MySQL while using Debezium 3.3 for PostgreSQL within the same Quarkus application.
====

[id=new-features-and-improvements-sqlserver]
=== Debezium for SQL Server

==== Incremental snapshots now resume after restart

When an incremental snapshot was in progress for a SQL Server connector, if a rebalance or connector restart was triggered for any reason, any in-progress incremental snapshot would fail to resume upon restart.
This is unintended and was due to regression in the handling of the connector's offsets during incremental snapshots.

This issue is fixed for SQL Sever, and we identified that no other connector was impacted by this regression.
SQL Server users should now observe that if the connector is restarted during an incremental snapshot, the snapshot resumes upon restart as intended (https://issues.redhat.com/browse/DBZ-9533[DBZ-9533]).

==== Multitask signaling support

The Debezium SQL Server connector is the only core relational source connector that supports the ability to capture changes from multiple databases on a shared instance using multiple tasks.
This deployment model provides for an efficient CDC solution that uses different tasks for different databases, using a single connector deployment.
Unfortunately, not all of Debezium's advanced features were supported in this mode.

It is now possible when using a multitask connector deployment for SQL Server, signals can be used reliably (https://issues.redhat.com/browse/DBZ-7243[DBZ-7243]).
This allows triggering adhoc blocking or incremental snapshots with this deployment configuration.


[id=new-features-and-improvements-vitess]
=== Debezium for Vitess

==== Exclude keyspace from table name in Vitess for improved performance

The Debezium Vitess connector now permits users to exclude the keyspace from the table name by setting the `vitess.exclude.keyspace.from.table.name` configuration property.
When set to `true`, the keyspace is excluded from the table name which boosts the VTGate performance significantly, which avoids copying each event unnecessarily before they're sent to Debezium  (https://issues.redhat.com/browse/DBZ-9522[DBZ-9522]).

[WARNING]
====
This feature should be used only when streaming from one keyspace, which is currently the only supported mode of operation.
====


[id=new-features-and-improvements-jdbc]
=== Debezium JDBC sink

==== Field name transformation reliably adjusts all fields

The JDBC sink transformation `FieldNameTransformation` unfortunately was not apply the desired case to all field names in the payload.
This led to sporadic reports where the JDBC sink would report the column names were not adjusted by the transformation and that the columns could not be found in the target table (https://issues.redhat.com/browse/DBZ-9747[DBZ-9747]).

This regression is now fixed and the transform accounts for all use cases correctly.

==== Geometry data type support

Debezium's source connectors have had long-standing support for various geometry and geography column types.
These types are serialized using custom Debezium logical types based on Kafka's semantic type `Struct`.
This is a complex field type that allows Debezium to encode both the Well Known Binary (or Extended Well Known Binary) WKB/EWKB byte array along with the spatial reference identifier or SRID.

When pairing Debezium's JDBC sink with a source connector, the JDBC sink connector will seamlessly convert geometry column values to the target database's desired format if it supports such column types (https://issues.redhat.com/browse/DBZ-9508[DBZ-9508]).
This new feature is available out of the box with no special configuration.

==== New passthrough collection naming strategy

The JDBC sink connector is intended to consume Debezium change events without using the `ExtractNewRecordState` transformation.
However, when applying other transformations that are not designed to handle Debezium's nested event structure, it's often required so that additional transformations can be applied accurately.

This often creates a challenge because the `ExtractNewRecordState` removes the `source` information block from the event structure.
This prevents the use of `+${source.*}+` pattern inside the `collection.naming.format`, limiting your options when mapping events to tables.

To solve this issue, a new passthrough collection naming strategy is included with the JDBC sink connector (https://issues.redhat.com/browse/DBZ-9679[DBZ-9679]).

This strategy uses the event's topic name directly, without any sanitization, as the target table name.
This allows you to pair any other transformations that modify the event's structure, including the ability to modify the topic name in-flight, so you have precise control over how events are mapped to tables.

To enable the passthrough collection naming strategy, add this to your connector configuration:

.How to configure the passthrough collection naming strategy
[source,json]
----
{
  "collection.naming.strategy": "io.debezium.sink.naming.PassthroughCollectionNamingStrategy"
}
----

In this example, events from topic `public.orders` will be written directly to a table named `public.orders`.


[id=new-features-and-improvements-server]
=== Debezium Server

==== OpenLineage output datasets

OpenLineage is an open framework for data lineage collection and analysis.
Its purpose is to track metadata about datasets giving information needed to help identify the root cause of complexities often present in change data capture pipelines.

Debezium's source connectors have support for OpenLineages using a transformation while deployed on Kafka Connect.
To simply the process to integrate with OpenLineage, Debezium Server natively provides the integration out of the box without the need to configure a separate transformation (https://issues.redhat.com/browse/DBZ-9059[DBZ-9059]).

The following example configuration shows how easy it is to get started.

.Example Debezium Server application.properties
[source,properties]
----
# Standard Debezium configuration here
...

# OpenLineage configuration
debezium.source.openlineage.integration.enabled=true
debezium.source.openlineage.integration.job.tags=env=prod,team=cdc
debezium.source.openlineage.integration.job.description=This connector does cdc for products
debezium.source.openlineage.integration.job.owers=Mario=maintainer,John Doe=Data scientist
debezium.source.openlineage.integration.config.file.path=<path>/debezium-openlineage.yml
----

.Example debezium-openlineage.yml
[source,yaml]
----
transport:
  type: debezium
----

==== Azure Event Hubs dynamic partition routing

Debezium 3.2 introduced a new dynamic partitioning mechanism that inadvertently disrupted the `PartitionRouting` transformation's capability to pre-generate partition identifiers for Event Hubs publishing in specific scenarios.
To resolve this issue, we've added a new configuration option called `debezium.sink.eventhubs.dynamicpartitionrouting` (https://issues.redhat.com/browse/DBZ-9572[DBZ-9572]) that accepts one of the following values:

`default`:: If the event has a key, uses the hash algorithm to compute the partition based on the event key; otherwise when there is no key, falls back to using the `partitionId` strategy.
`key`:: If the event has a key, uses the hash algorithm to compute the partition based on the event key; otherwise falls back to the batch index for non partition id.
`partitionid`:: Will use the event's computed partition if present, otherwise falls back to the batch index for non partition id.


[id=other-changes]
== Other fixes

The following are just a subset of some noteworthy additional changes and fixes in Debezium 3.4:

* Can bind a LONG value only for insert into a LONG column https://issues.redhat.com/browse/DBZ-8276[DBZ-8276]
* Debezium db2i CDC source connector randomly loses Events https://issues.redhat.com/browse/DBZ-8538[DBZ-8538]
* Oracle Connector stops mining on REVOKE FLASHBACK on ... https://issues.redhat.com/browse/DBZ-9112[DBZ-9112]
* Support Redis Cluster mode in the Debezium Redis sink module https://issues.redhat.com/browse/DBZ-9226[DBZ-9226]
* Align Debezium Oracle DDL grammar with upstream https://issues.redhat.com/browse/DBZ-9302[DBZ-9302]
* Provide the table explorer table component https://issues.redhat.com/browse/DBZ-9318[DBZ-9318]
* Apply query.fetch.size universally to all Oracle non-snapshot queries https://issues.redhat.com/browse/DBZ-9448[DBZ-9448]
* Apply mining upper boundary to avoid PGA_AGGREGATE_LIMIT https://issues.redhat.com/browse/DBZ-9476[DBZ-9476]
* Debezium platform conductor service fails on /q/openapi https://issues.redhat.com/browse/DBZ-9496[DBZ-9496]
* Use Jakarta variant of ehcache https://issues.redhat.com/browse/DBZ-9517[DBZ-9517]
* Only log an error when the dump folder is provided but doesn't exist https://issues.redhat.com/browse/DBZ-9519[DBZ-9519]
* Events are mistakenly skipped during commit dispatch when LOB is enabled  https://issues.redhat.com/browse/DBZ-9521[DBZ-9521]
* Missing OpenLineage Complete event during gracefully shutdown https://issues.redhat.com/browse/DBZ-9524[DBZ-9524]
* Support TOKENLIST datatype in Spanner connector https://issues.redhat.com/browse/DBZ-9526[DBZ-9526]
* Correct type is not used for the PORT field in the connection payload https://issues.redhat.com/browse/DBZ-9530[DBZ-9530]
* Add support to show the Active count in the Connection page https://issues.redhat.com/browse/DBZ-9531[DBZ-9531]
* Oracle alter DDL to move partition/subpartition fails to be parsed https://issues.redhat.com/browse/DBZ-9534[DBZ-9534]
* SchemaUtil creates invalid JSON https://issues.redhat.com/browse/DBZ-9540[DBZ-9540]
* Pipeline page Issues https://issues.redhat.com/browse/DBZ-9543[DBZ-9543]
* Deadlock due to lost interrupt with blc keep alive thread https://issues.redhat.com/browse/DBZ-9548[DBZ-9548]
* DdlChanges not reset in schema history recovery https://issues.redhat.com/browse/DBZ-9549[DBZ-9549]
* Timestamp values cause NPE in Postgres on JDK23+ https://issues.redhat.com/browse/DBZ-9558[DBZ-9558]
* Handle the form properties with dot present in their name https://issues.redhat.com/browse/DBZ-9560[DBZ-9560]
* Add basic UI validation in the Pipeline package specific log configuration options https://issues.redhat.com/browse/DBZ-9561[DBZ-9561]
* Send the signal.data.collection property in the source payload only when its added https://issues.redhat.com/browse/DBZ-9562[DBZ-9562]
* Skipped events counter not handled correctly for compressed transactions https://issues.redhat.com/browse/DBZ-9564[DBZ-9564]
* Update MongoDB driver to 5.5.1 https://issues.redhat.com/browse/DBZ-9585[DBZ-9585]
* Fix failed to initialize open lineage for vitess connector https://issues.redhat.com/browse/DBZ-9613[DBZ-9613]
* Handle exceptions thrown from performCommit method to gracefully cleanup the coordinator during the stop call https://issues.redhat.com/browse/DBZ-9617[DBZ-9617]
* Table column metadata is not fetched when table name has a '/' character https://issues.redhat.com/browse/DBZ-9620[DBZ-9620]
* MySQL connector does not parse CREATE TABLE https://issues.redhat.com/browse/DBZ-9623[DBZ-9623]
* Debezium Server run.bat fails to execute on Windows https://issues.redhat.com/browse/DBZ-9625[DBZ-9625]
* Begin marker but no end marker for rollback transactions https://issues.redhat.com/browse/DBZ-9628[DBZ-9628]
* Fix minor issues in the Platform UI dark mode https://issues.redhat.com/browse/DBZ-9633[DBZ-9633]
* MariaDB fails to parse "CONVERT TO CHARSET <character-set>" https://issues.redhat.com/browse/DBZ-9634[DBZ-9634]
* Standardize source catalog descriptions https://issues.redhat.com/browse/DBZ-9642[DBZ-9642]
* Oracle does not support renaming partitions using alter table https://issues.redhat.com/browse/DBZ-9651[DBZ-9651]
* Debezium Server configuration import creates invalid pipelines https://issues.redhat.com/browse/DBZ-9652[DBZ-9652]
* MongoDB connector: Whitespace in collection.include.list causes incorrect regex pattern in change streams https://issues.redhat.com/browse/DBZ-9657[DBZ-9657]
* Debezium Oracle restarting mining session too frequently https://issues.redhat.com/browse/DBZ-9680[DBZ-9680]
* Debezium Oracle connector fails to parse Oracle database version https://issues.redhat.com/browse/DBZ-9681[DBZ-9681]
* MySQLGTIDSet Subtractions Fail on UUIDSet that exist only in the Left Operand https://issues.redhat.com/browse/DBZ-9682[DBZ-9682]
* Connection list shows connection of all source/destination https://issues.redhat.com/browse/DBZ-9685[DBZ-9685]
* Snapshot SQL Override Spaces https://issues.redhat.com/browse/DBZ-9695[DBZ-9695]
* NPE during sending to HTTP sink https://issues.redhat.com/browse/DBZ-9698[DBZ-9698]
* Signal Processing With Idle Database https://issues.redhat.com/browse/DBZ-9707[DBZ-9707]
* Task getErrorHandler throws NullPointerException https://issues.redhat.com/browse/DBZ-9708[DBZ-9708]
* Debezium Cassandra Connector Silently Stops Processing After CommitLog Move Failure https://issues.redhat.com/browse/DBZ-9710[DBZ-9710]
* MongoDb connector throws null ref exception https://issues.redhat.com/browse/DBZ-9719[DBZ-9719]
* JDBC offset store requires PK when connecting with a MySQL cluster https://github.com/debezium/dbz/issues/5[debezium/dbz#5]
* Oracle connector can incorrectly build on-demand table schema with optional key fields. https://github.com/debezium/dbz/issues/7[debezium/dbz#7]
* PostgreSQL Connector: Keep-alive thread logs ERROR on normal shutdown due to InterruptedException https://github.com/debezium/dbz/issues/14[debezium/dbz#14]
* Oracle numeric default values wrapped in `(` and `)` are mistakenly treated as expressions https://github.com/debezium/dbz/issues/16[debezium/dbz#16]


In total, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20and%20fixVersion%20%20in%20(3.4.0.Alpha1,3.4.0.Alpha2,3.4.0.Beta1,3.4.0.CR1,3.4.0.Final)[335 issues] were resolved in Debezium 3.4.
The list of changes can also be found in our https://debezium.io/releases/3.4[release notes].

A big thank you to all the contributors from the community who worked diligently on this release:
 +
https://github.com/AlvarVG[Alvar Viana Gomez],
https://github.com/big-andy-coates[Andy Coates],
https://github.com/akanimesh7[Animesh Kumar],
https://github.com/shybovycha[Artem Shubovych],
https://github.com/atorik[Atsushi Torikoshi],
https://github.com/aukevanleeuwen[Auke van Leeuwen],
https://github.com/bpaquet[Bertrand Paquet],
https://github.com/chaitradalawai[Chaitra Dalawai],
https://github.com/Naros[Chris Cranford],
https://github.com/moench-tegeder[Christoph Moench-Tegeder],
https://github.com/cjbooms[Conor Gallagher],
https://github.com/nrkdaer11[Daniel Eriksson],
https://github.com/dvolontyr1[Dmitry Volontyr],
https://github.com/hamnis[Erlend Hamnaberg],
https://github.com/gmiklos-ltg[Gabriel Miklós],
https://github.com/kmos[Giovanni Panice],
https://github.com/seanshi007[Guangnan Shi],
https://github.com/hagar-yasser1[Hagar Yasser],
https://github.com/HongqunXia[Hong Xia],
https://github.com/indraraj[Indra Shukla],
https://github.com/jiangzzhu[Jiang Zhu],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/jogomez97[Joan Gomez],
https://github.com/pricelessjunk[Kaustuv Chakrabarti],
https://github.com/nrkljo[Lars M. Johansson],
https://github.com/lgazire[Lucas Gazire],
https://github.com/piatekmarcin[Marcin Piatek],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/see-quick[Maros Orsak],
https://github.com/mateuszmichalik1993[Mateusz Michalik],
https://github.com/mhejnas[Matt Hejnas],
https://github.com/nagasreevalaboju[Nagasree Valaboju],
https://github.com/nathan-smit-1[Nathan Smit],
https://github.com/nkokitkar[Nikita Kokitkar],
https://github.com/ochedru[Olivier Chédru],
https://github.com/pypsink[Pierre-Yves Péton],
https://github.com/gildur[Piotr Wolny],
https://github.com/poonam-meghnani[Poonam Meghnani],
https://github.com/rajdangwal[Rajendra Dangwal],
https://github.com/roldanbob[Robert Roldan],
https://github.com/doljae[Seokjae Lee],
https://github.com/morozov[Sergei Morozov],
https://github.com/sumitjha4321[Sumit Jha],
https://github.com/twthorn[Thomas Thornton],
https://github.com/ThomasVerhoeven1998[Thomas Verhoeven],
https://github.com/PlugaruT[Tudor Plugaru],
https://github.com/notation-v[Vipin Kalra],
https://github.com/vjuranek[Vojtech Juranek],
Wang-Yu-Chao,
https://github.com/william-xiang[William Xiang],
https://github.com/internCoder[Xiang Qiu Min],
https://github.com/yramanovich[Yauheni Ramanovich],
https://github.com/archiedx[archiedx],
https://github.com/battmush[battmush],
https://github.com/ismailsimsek[ismail simsek],
https://github.com/MV-GH[maarten.vercruysse],
https://github.com/msillence[martin],
https://github.com/findingrish[rishabh singh], and
https://github.com/rptroberts[rptroberts]!


[id="whats-next"]
== What's next?

As the team will begin to turn focus to Debezium 3.5 in January, there is many new features and improvements on the horizon.
A few notable highlights for next year include:

* [Debezium Server] Cloud storage sinks, source connectors for Milvus and Qdrant
* [Quarkus Extension] Oracle database and advanced filtering support
* [Platform] Improved user experience focus
* [Core] Snapshotting single tables across multiple threads

For a complete roadmap on what you expect, we've recently updated our https://debezium.io/roadmap[project roadmap] to include all the anticipated planned features.
As always, the roadmap is heavily influenced by the community, i.e. you.
So if you would like to see any particular items, please let us know.

Merry Christmas and Happy Holidays, and we'll see you all in 2026!

Onwards and Upwards!
