---
layout: post
title:  Debezium 3.2.4.Final Released
date:   2025-10-07
tags: [ releases, mongodb, mysql, mariadb, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner, jdbc, informix, ibmi ]
author: ccranfor
extraClasses: release-v2
---

Debezium 3.2.4.Final is now available with important fixes for Oracle connector users and stability improvements across multiple database connectors.

+++<!-- more -->+++

In this post, we're going to take a deep dive into the improvements made across several key modules of Debezium, discussing any new features, and explaining any changes that could impact your upgrade process.
As always, we recommend you read the link:/releases/3.2/release-notes#release-3.2.4-final[release notes] to learn about all the bugs that were fixed, update procedures, and more.

[id=breaking-changes]
== Breaking changes

With any new release of software, there is often several breaking changes.
This release is no exception, so let's discuss the major changes you should be aware of before upgrading to **Debezium 3.2.4.Final**.

=== Db2 Offset position validation is unreliable

Due to reliability issues with offset position validation in Db2, we've temporarily disabled validation to prevent false failures (https://issues.redhat.com/browse/DBZ-9470[DBZ-9470]).
As a result, the `when_needed` snapshot mode is currently unavailable for Db2 connectors.

**Impact**: If you're using `when_needed` snapshot mode with Db2, you will need to use an alternative mode until this limitation is resolved in a future release.

[id=new-features-and-improvements]
== New features and improvements

Let's cover some noteworthy improvements and changes in 3.2.4.Final.

=== Oracle events mistakenly skipped

We introduced https://issues.redhat.com/browse/DBZ-8060[DBZ-8060] in Debezium 3.2.3.Final which unfortunately introduced a regression for users who enable LOB capture support for the Oracle connector.
This regression lead to situations where the connector would report that parts of transactions were being skipped.
Thanks to the swift action of the Debezium community, this regression was reported and fixed in Debezium 3.2.4.Final (https://issues.redhat.com/browse/DBZ-9521[DBZ-9521]).

For Oracle users, it's important if you are upgrading, please avoid the use of 3.2.3.Final and consider moving to 3.2.4.Final if you intend to use Debezium 3.2.

=== Oracle XStream no longer flushes invalid low watermarks

The Debezium Oracle XStream implementation must periodically flush an LCR position to the Oracle Outbound Server.
This flush acts as a hint to Oracle that all changes prior to that position have been processed, similar to how PostgreSQL confirms LSNs to a replication slot.

Previously, due to the way offset flushing was handled, the Oracle Outbound Server could incorrectly report a failure when attempting to flush the low watermark, treating a valid position as invalid.
This issue has now been fixed, and the Oracle Outbound Server will no longer falsely report invalid low-watermark positions (https://issues.redhat.com/browse/DBZ-8923[DBZ-8923]).

[id=other-fixes]
== Other fixes

* Dropping in process batch transactions when shutting down https://issues.redhat.com/browse/DBZ-8060[DBZ-8060]
* A transaction mined across two queries can randomly cause unsupported operations https://issues.redhat.com/browse/DBZ-8747[DBZ-8747]
* Oracle connector reselect  exception handling (ORA-01555 + ORA-22924) https://issues.redhat.com/browse/DBZ-9446[DBZ-9446]
* OutOfMemory exception when recreating list of tables for snapshot callables https://issues.redhat.com/browse/DBZ-9472[DBZ-9472]
* Debezium Server  raise  "AttributeNotFoundException QueueTotalCapacity" with SqlServer source https://issues.redhat.com/browse/DBZ-9477[DBZ-9477]
* Getting "Unknown column in 'field list'" when column name contains backtick https://issues.redhat.com/browse/DBZ-9479[DBZ-9479]
* MySQL Event get header throws NullPointerException https://issues.redhat.com/browse/DBZ-9483[DBZ-9483]
* MySQL example container images are not properly configured https://issues.redhat.com/browse/DBZ-9485[DBZ-9485]
* Dropping primary key does not change Oracle relational metadata https://issues.redhat.com/browse/DBZ-9505[DBZ-9505]

In total, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20and%20fixVersion%20%20in%20(3.2.3.Final,3.2.4.Final)[15 issues] were resolved in Debezium 3.2.4.Final.
The list of changes can also be found in our https://debezium.io/releases/3.2/release-notes[release notes].

A big thank you to all the contributors from the community who worked diligently on this release:
 +
https://github.com/AlvarVG[Alvar Viana Gomez],
https://github.com/AlvarVG[Alvar Viana],
https://github.com/Naros[Chris Cranford],
https://github.com/seanshi007[Guangnan Shi],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/rk3rn3r[René Kerner],
https://github.com/roldanbob[Robert Roldan],
https://github.com/kinolaev[Sergei Nikolaev],
https://github.com/vjuranek[Vojtech Juranek], and
https://github.com/leoloel[leoloel]!