---
layout: post
title:  Debezium 3.3.2.Final Released
date:   2025-12-01 00:02:00 -0600
tags: [ releases, mongodb, mysql, mariadb, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner, jdbc, informix, ibmi, cockroachdb ]
author: ccranfor
extraClasses: release-v2
---

Fix connector statrtup errors when OpenLineage is not used; Oracle LogMiner fixes and optimizations; PostgreSQL compatibility with Java 23+

Debezium 3.3.2.Final is now available with important fixes and stability improvements across multiple database connectors.

+++<!-- more -->+++

In this post, we're going to take a deep dive into the improvements made across several key modules of Debezium, discussing any new features, and explaining any changes that could impact your upgrade process.
As always, we recommend you read the link:/releases/3.3/release-notes#release-3.3.2-final[release notes] to learn about all the bugs that were fixed, update procedures, and more.

[id=new-features-and-improvements]
== New features and improvements

Let's cover some noteworthy improvements and changes in 3.3.2.Final.

=== PostgreSQL connector compatibility fixed for Java 23+

When running Debezium using JDK23+, sometimes when parsing `timestamp` values from PostgreSQL they could lead to `NullPointerException` errors.
To address this compatibility issue, we have made some adjustments so that later JDK builds do now lead to these obscure failures (https://issues.redhat.com/browse/DBZ-9558[DBZ-9558]).

=== Oracle low watermark calculation no longer causes performance loss

When an Oracle LogMiner mining step completes, the Debezium Oracle connector needs to calculate the next starting position for mining.
When `lob.enabled` is set to `false` (the default), it was observed that this calculation was too conservative, and could lead to a regression in performance.

This regression has been fixed, and the connector should once again resume reading changes without the low watermark calculation causing performance loss (https://issues.redhat.com/browse/DBZ-9664[DBZ-9664]).

=== Oracle heartbeats no longer stop when mining returns no data

The Debezium Oracle connector recently introduced an experimental feature using Common Table Expression (CTE) queries to allow another way to optimize the data fetch from Oracle LogMiner.
However, the community reported that when using this feature, if the query returned no events, Debezium stopped emitting heartbeat events.

This has been fixed, and users should observe that heartbeat events should always be emitted by the Oracle connector, even if the mining pass fetched no data (https://issues.redhat.com/browse/DBZ-9443[DBZ-9443]).

=== SQL Server incremental snapshots now resume after restart

When an incremental snapshot was in progress for a SQL Server connector, if a rebalance or connector restart was triggered for any reason, any in-progress incremental snapshot would fail to resume upon restart.
This is unintended and was due to regression in the handling of the connector's offsets during incremental snapshots.

This issue is fixed for SQL Sever, and we identified that no other connector was impacted by this regression.
SQL Server users should now observe that if the connector is restarted during an incremental snapshot, the snapshot resumes upon restart as intended (https://issues.redhat.com/browse/DBZ-9533[DBZ-9533]).

=== OpenLineage can now be fully disabled

Several users reported issues when `openlineage.integration.enabled` was set to `false`, Debezium was still trying to resolve OpenLineage features in some parts of the code, which could lead to undesirable `IllegalStateException` errors while trying to initialize OpenLineage.

This issue is resolved and Debezium fully respects the `openlineage.integration.enabled` property and will not attempt to perform any OpenLineage setup or initialization when set to `false` (https://issues.redhat.com/browse/DBZ-9504[DBZ-9504]).

[id=other-fixes]
== Other fixes

* Can bind a LONG value only for insert into a LONG column https://issues.redhat.com/browse/DBZ-8276[DBZ-8276]
* DdlChanges not reset in schema history recovery https://issues.redhat.com/browse/DBZ-9549[DBZ-9549]
* Skipped events counter not handled correctly for compressed transactions https://issues.redhat.com/browse/DBZ-9564[DBZ-9564]
* Handle exceptions thrown from perfromCommit method to gracefully cleanup the coordinator during the stop call https://issues.redhat.com/browse/DBZ-9617[DBZ-9617]
* Table column metadata is not fetched when table name has a '/' character https://issues.redhat.com/browse/DBZ-9620[DBZ-9620]
* MySQL connector does not parse CREATE TABLE https://issues.redhat.com/browse/DBZ-9623[DBZ-9623]
* Debezium Server run.bat fails to execute on Windows https://issues.redhat.com/browse/DBZ-9625[DBZ-9625]
* Begin marker but no end marker for rollbacked transactions https://issues.redhat.com/browse/DBZ-9628[DBZ-9628]
* MariaDB fails to parse "CONVERT TO CHARSET <character-set>" https://issues.redhat.com/browse/DBZ-9634[DBZ-9634]
* Oracle does not support renaming partitions using alter table https://issues.redhat.com/browse/DBZ-9651[DBZ-9651]
* MongoDB connector: Whitespace in collection.include.list causes incorrect regex pattern in change streams https://issues.redhat.com/browse/DBZ-9657[DBZ-9657]
* Debezium Oracle restarting mining session too frequently https://issues.redhat.com/browse/DBZ-9680[DBZ-9680]
* Debezium Oracle connector fails to parse Oracle database version https://issues.redhat.com/browse/DBZ-9681[DBZ-9681]
* MySQLGTIDSet Subtractions Fail on UUIDSet that exist only in the Left Operand https://issues.redhat.com/browse/DBZ-9682[DBZ-9682]
* NPE during sending to HTTP sink https://issues.redhat.com/browse/DBZ-9698[DBZ-9698]

In total, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20and%20fixVersion%20%20in%20(3.3.2.Final)[21 issues] were resolved in Debezium 3.3.2.Final.
The list of changes can also be found in our https://debezium.io/releases/3.3/release-notes[release notes].

A big thank you to all the contributors from the community who worked diligently on this release:
 +
https://github.com/akanimesh7[Animesh Kumar],
https://github.com/shybovycha[Artem Shubovych],
https://github.com/aukevanleeuwen[Auke van Leeuwen],
https://github.com/Naros[Chris Cranford],
https://github.com/nrkdaer11[Daniel Eriksson],
https://github.com/seanshi007[Guangnan Shi],
https://github.com/hagar-yasser1[Hagar Yasser],
https://github.com/HongqunXia[Hong Xia],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/pricelessjunk[Kaustuv Chakrabarti],
https://github.com/nrkljo[Lars M. Johansson],
https://github.com/ochedru[Olivier Chédru],
https://github.com/poonam-meghnani[Poonam Meghnani],
https://github.com/rajdangwal[Rajendra Dangwal],
https://github.com/roldanbob[Robert Roldan],
https://github.com/rptroberts[rptroberts], and
https://github.com/sumitjha4321[Sumit Jha]!