---
layout: post
title:  Debezium 3.2.0.Alpha1 Released
date:   2025-04-29
tags: [ releases, mongodb, mysql, mariadb, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner, jdbc, informix, ibmi ]
author: ccranfor
extraClasses: release-v2
---

Another release cadence done, and we're pleased to announce the next preview release of Debezium is available, **3.2.0.Alpha1**.
This release is built on Kafka 4.0 with several breaking changes with many improvements and bugfixes.

Let's take a moment and dive into all these changes.

+++<!-- more -->+++


[id="breaking-changes"]
== Breaking changes

With any new major release of software, there is often several breaking changes.
The Debezium **3.2.0.Alpha1** release is no exception, so let's discuss the major changes you should be aware of.

[%noheader, cols="3"]
|===

| link:#breaking-changes-core[Debezium Core]
| link:#breaking-changes-ibmi[Debezium for IBMi]
| link:#breaking-changes-oracle[Debezium for Oracle]

|===

[id=breaking-changes-core]
=== Debezium Core

==== Built on Kafka 4.0

Debezium 3.2 is built and tested using Kafka 4.0 (https://issues.redhat.com/browse/DBZ-8875[DBZ-8875]).

[id=breaking-changes-ibmi]
=== Debezium for IBMi

==== Error raised on missing journal files

In previous versions of Debezium for IBMi, if a journal file was missing, the connector resumed from the first available journal.
This would lead to silent data loss.
This behavior has changed and the connector will now throw an error if a required journal file no longer exists (https://issues.redhat.com/browse/DBZ-8898[DBZ-8898]).

[id=breaking-changes-oracle]
=== Debezium for Oracle

==== Using secure mTLS connections with JKS

When using the Debezium for Oracle connector to establish a secure mTLS connection using Java Keystores (JKS), special configuration is necessary.
We have added this information to the link:/documentation/reference/stable/connectors/oracle.html#using-mtls-secure-connections[Oracle connector documentation] (https://issues.redhat.com/browse/DBZ-8788[DBZ-8788]).



[id="new-features-and-improvements"]
== New features and improvements

The following describes all noteworthy new features and improvements in **Debezium 3.2.0.Alpha1**.
For a complete list, be sure to read the link:/releases/3.2/release-notes#release-3.2.0-alpha1[release notes] for more details.

[cols="1,1,1"]
|===

| link:#new-features-and-improvements-core[Debezium Core]
| link:#new-features-and-improvements-jdbc[Debezium JDBC sink]
| link:#new-features-and-improvements-ai[Debezium AI]

| link:#new-features-and-improvements-ibmi[Debezium for IBMi]
| link:#new-features-and-improvements-embedded[Debezium Embedded]
| link:#new-features-and-improvements-platform[Debezium Platform]

| link:#new-features-and-improvements-oracle[Debezium for Oracle]
| link:#new-features-and-improvements-jdbc[Debezium Server]
|

|===

[id=new-features-and-improvements-core]
=== Debezium Core

==== Regression with logging performance

In Debezium 3.1, a change was introduced to centralize the logging of sensitive information.
Unfortunately, this change introduced a regression, leading to lower performance across a variety of code paths.

This change has been reverted and replaced with an implementation that retains the centralized logging intent while restoring the prior performance (https://issues.redhat.com/browse/DBZ-8879[DBZ-8879]).

==== Reset certain streaming metrics through JMX

During periods of idle activity, a Debezium connector will continue to report `LagBehindSource` JMX metric as the last computed value, as this value is only updated as new changes are received.
For some environments, this is less than desirable or not intuitive if you are unaware of the idle or low activity window.

Debezium 3.1.1.Final introduces a new option that can be triggered through JConsole or other JMX integrations to reset the current `LagBehindSource` metric by calling the new function `resetLagBehindSource` (https://issues.redhat.com/browse/DBZ-8885[DBZ-8885]).

==== Log JMX MBean name when registration fails

When the JMX metric MBean fails registration, it's most often due to the fact that an existing MBean is already registered with such name.
This can happen for a variety of reasons, including a prior task not stopping gracefully or misconfiguration between two connectors sharing the same `topic.prefix`.

Unfortunately the logged information does not provide adequate information to know which MBean and connector the failure is about.
To address this, the JMX MBean name will be logged when the registration fails so that the exact connector deployment that's affected can be easily determined (https://issues.redhat.com/browse/DBZ-8862[DBZ-8862]).

[id=new-features-and-improvements-ibmi]
=== Debezium for IBMi

==== Add support for BOOLEAN data types

IBM provides support for the `BOOLEAN` data types on V7R5+ and later V7R4 releases of the IBM iSeries database.
In prior versions, if a table contained a boolean data type, this would result in a hard failure with the Debezium for IBMi connector.

With Debezium 3.2, `BOOLEAN` data types are now captured without throwing an exception (https://issues.redhat.com/browse/DBZ-7796[DBZ-7796]).

==== Add decimal handling mode support

The `decimal.handling.mode` configuration property specifies how the connector should handle floating point values for connector-specific data types.
In prior versions of the Debezium for IBMi connector, this configuration property was not honored.

Debezium 3.2 introduces support for `decimal.handling.mode`, allow you to specify whether floating point values are serialized (https://issues.redhat.com/browse/DBZ-8301[DBZ-8301]).
This configuration property can be configured with one of three values:

`precise`:: Represents values precisely by using `java.math.BigDecimal` values represented in change events in a binary form.
`double`:: Represents values by using `double` values. Using `double` values is easier, but can result in a loss of precision.
`string`:: Encodes values as formatted strings. Using the `string` option is easier to consume, but results in a loss of semantic information about the real type.

[id=new-features-and-improvements-oracle]
=== Debezium for Oracle

==== Unbuffered LogMiner adapter using committed data only

Debezium for Oracle introduces a new adapter implementation that buffers transactions on the relational database using the database's memory buffers rather than relying on the JVM heap or off-heap cache implementations (https://issues.redhat.com/browse/DBZ-8924[DBZ-8924]).

To get started with the new adapter, the connector configuration needs to be adjusted, as shown here:

[source,json]
----
{
  "database.connection.adapter": "logminer_unbuffered"
}
----

[NOTE]
====
While most of the `+log.mining.*+` connector configurations are honored by this new adapter, any configuration that relates to buffer, cache, or transaction management are not used.
====

This new adapter implementation is based on Oracle LogMiner's `COMMITTED_DATA_ONLY` mode.
This mode forces Oracle LogMiner to use the database's available memory to buffer transactions and to only supply Debezium with committed changes.
Because Debezium only receives committed changes, the connector can immediately dispatch changes as they're read which avoids complex memory sizing requirements along with the need to handle partial rollbacks due to savepoints or constraint violations.

Because Oracle LogMiner is now responsible for buffering transactions until the commit is observed, Oracle LogMiner will rely on the database's memory to handle this staging requirement.
This directly means that this staging is only as powerful as the `PGA_AGGREGATE_LIMIT` database administrator's configured Oracle database instance parameter.
When a transaction's memory requirement exceeds this limit, Oracle will refuse to buffer the transaction and will throw a connector error.
This can be resolved by raising the configured limit, removing the limit entirely, or resizing your transactions so they fit within the boundary of this Oracle limit.

[WARNING]
====
This feature is currently in incubating state, i.e. exact semantics, configuration options etc. may change in future revisions, based on the feedback we receive. Please let us know if you encounter any problems while using this extension.
====

==== Filter Oracle LogMiner results by client id

The Oracle LogMiner adapters provide a myriad of ways to exclude transactions by explicitly passing filters to the database query to excluding or only including transactions performed by specific database usernames.
In this release, we've added another interesting filter criteria based on the Oracle LogMiner field `CLIENT_ID`, where you can elect to include or exclude changes based on this field's value (https://issues.redhat.com/browse/DBZ-8904[DBZ-8904]).

The following configuration properties can be used:

`log.mining.clientid.include.list`:: Specifies a comma-separated list of values to match against the `CLIENT_ID` field for capture.
`log.mining.clientid.exclude.list`:: Specifies a comma-separated list of values to match against the `CLIENT_ID` field to exclude from capture.

Just like any of the other include/exclude configuration properties, these are mutually exclusive.

==== Reduced CPU utilization under specific scenarios

In Debezium 3.1, we introduced a change as part of https://issues.redhat.com/browse/DBZ-8665[DBZ-8665] to restore the same performance from 2.7.0.Final when processing constraint violations or save point rollback operations.
While this change was successful at reducing the latency caused by processing such events in Debezium 3.0 through 3.0.7, we found that even the performance from Debezium 2.7 was overall suboptimal.

We have implemented a complete rework of the transaction buffering solution to handle constraint violations and save point rollbacks more efficiently (https://issues.redhat.com/browse/DBZ-8860[DBZ-8860]).

When using heap-based buffering, we reduced the time needed to process such events by nearly 90% while also reducing the time complexity for off-heap buffering by 97-99%.
In addition to the time complexity reduction, we have also reduced the overall CPU usage while handling these events to remain aligned with expectations.

==== Improved the `online_catalog` mining strategy performance

Prior to adding the `hybrid` mining strategy, the Debezium Oracle LogMiner implementation included a specific condition to include events for tables where LogMiner failed to resolve the table name.
This use case happens when the object id and version in the redo entry does not match the online data dictionary, which occurs after specific DDL operations are performed.

Including these changes, particularly when users perform bulk operations and LogMiner fails to resolve the table name, this increases latency, connector overhead, only so that the connector can log the unknown table.
Given the reduction of performance solely for logging, we have chosen to omit including these events in the data fetch moving forward (https://issues.redhat.com/browse/DBZ-8926[DBZ-8926]).

==== Improved the `hybrid` mining strategy performance

We also identified another performance bottleneck, this time when using the `hybrid` mining strategy while processing bulk events where LogMiner failed to resolve the table name during object id/version mismatches.
The `hybrid` strategy is designed to handle this use case and fallback to Debezium's relational model to resolve the table name; however, despite using a cache, the cost overhead for the cache lookups for bulk operations was significantly high.

In order to reduce the cost and improve throughput performance of bulk  operations on unknown tables, we have reworked the lookup in a way that increases the throughput by significantly, allowing bulk operations to be handled more efficiently and with less overall CPU utilization (https://issues.redhat.com/browse/DBZ-8925[DBZ-8925]).

==== Improve log message when failing to apply a partial rollback

When using the Debezium for Oracle LogMiner buffered adapter, when a partial rollback is observed, the log entry does not capture critical information that could be useful for debugging purposes.
Debezium 3.2 now includes the transaction identifier and the system change number associated with the partial rollback redo entry (https://issues.redhat.com/browse/DBZ-8944[DBZ-8944]).

[id=new-features-and-improvements-jdbc]
=== Debezium JDBC sink

==== Configuration available to column/table naming strategies

The Debezium JDBC sink offers a variety of configurable hooks, including the option to define deployment-specific `TableNamingStrategy` or `ColumnNamingStrategy` implementations.
However, these implementations were unable to obtain the full configuration for the connector deployment, making these hooks far less restrictive than intended.

With Debezium 3.2, these strategy implementations provide a new configure method (https://issues.redhat.com/browse/DBZ-7051[DBZ-7051]), shown here:
[source,java]
----
@Override
public void configure(Map<String, Object> config) {
}
----

To provide backward compatibility, this method is defined as default with no implementation, so no code changes are required where this configuration step is unnecessary.

[id=new-features-and-improvements-embedded]
=== Debezium Embedded

==== New polling started/ended callbacks added

The `DebeziumEngine` interface provides a variety of features, including knowing when the connector or task has started or stopped.
However, because the connector operates asynchronously, it may be useful to know when the connector has entered the polling phase for specific user-driven logic.

To address this concern, two new methods have been added to the `ConnectorCallback` contract (https://issues.redhat.com/browse/DBZ-8948[DBZ-8948]):

[source,java]
----
/**
 * Called after all the tasks have been successfully started and engine has moved to polling phase, but before actual polling is started.
 */
default void pollingStarted() {
    // nothing by default
}

/**
 * Called after all the tasks have successfully exited from the polling loop, i.e. the callback is not called when any of the tasks has thrown
 * exception during polling or was interrupted abruptly.
 */
default void pollingStopped() {
    // nothing by default
}
----

Now when setting up a `DebeziumEngine` instance, the `ConnectorCallback` supplied implementation can include logic to call during these lifecycle state changes as needed.

[id=new-features-and-improvements-server]
=== Debezium Server

==== Milvus allows unwinding of JSON data types

Debezium source connectors are designed to emit JSON data type values as a `io.debezium.data.Json` semantic type that encodes the JSON value as a string.
However, this may not always be the desired outcome when sinking changes to a Milvus sink using Debezium Server.

A new configuration property, `debezium.sink.milvus.unwind.json`, has been added that can be set to either `true` or `false` (the default).
When this property is set to `true`, the JSON string value will be represented as a `JsonObject` instead (https://issues.redhat.com/browse/DBZ-8909[DBZ-8909]).

==== Redis can skip heartbeat messages

Debezium source connectors are often configured with heartbeat events so that at no point during low activity periods that the offset information for the source becomes stale.
However, for some sinks like Redis, these heartbeat events aren't useful to be passed to the sink target.

A new configuration property, `debezium.sink.redis.skip.heartbeat.messages`, has been added that can be set to either `true` or `false` (the default).
When this property is set to `true`, the Redis sink will skip emitting heartbeat events to the Redis target; however, the heartbeat events will continue to influence the management of stale offsets (https://issues.redhat.com/browse/DBZ-8911[DBZ-8911]).

[id=new-features-and-improvements-ai]
=== Debezium AI

==== Introduce timeout for Ollama embedding models

We have added a new configuration property `ollama.operation.timeout.ms` for the Debezium AI Ollama model integration using the `FieldToEmbedding` transformation.
This configuration property specifies the number of milliseconds that the model operation is allowed to execute for before the request is timed out.
By default, the transformation waits 15 seconds, but can be adjusted accordingly (https://issues.redhat.com/browse/DBZ-8908[DBZ-8908]).

[id=new-features-and-improvements-platform]
=== Debezium Platform

==== Improve navigation and workflow for transformations

We have added several new features to the Debezium Management Platform interface for transformations (https://issues.redhat.com/browse/DBZ-8328[DBZ-8328]), which includes:

* A new main navigation menu option called **Transforms**.
* Improved the pipeline creation workflow allowing transformations to be added in-flight.
* Support for modifying and removing existing transformations.

We'd love your feedback on the new navigation workflow and improvements around transformations.

[id="other-changes"]
== Other changes

* Incorrect NumberOfEventsFiltered metrics in streaming https://issues.redhat.com/browse/DBZ-8576[DBZ-8576]
* Signal table column names are arbitrary, but delete strategy expects column named id https://issues.redhat.com/browse/DBZ-8723[DBZ-8723]
* Prevent write operations in PostgreSQL in read-only mode. https://issues.redhat.com/browse/DBZ-8743[DBZ-8743]
* Upgrade MariaDB driver to 3.5.3 https://issues.redhat.com/browse/DBZ-8758[DBZ-8758]
* Add Localization support to UI https://issues.redhat.com/browse/DBZ-8859[DBZ-8859]
* Upgrade RocketMQ version from 5.1.4 to 5.2.0 https://issues.redhat.com/browse/DBZ-8864[DBZ-8864]
* Bump Chicory version and take advantage of latest improvements https://issues.redhat.com/browse/DBZ-8867[DBZ-8867]
* When using the Oracle relaxed SQL parser setup, strings with apostrophe followed by comma are trimmed https://issues.redhat.com/browse/DBZ-8869[DBZ-8869]
* Oracle Ehcache buffer will silently evict entries when configured size limits are reached https://issues.redhat.com/browse/DBZ-8874[DBZ-8874]
* Improve MySQL/MariaDB connector resilience during post-schema recovery reconnect https://issues.redhat.com/browse/DBZ-8877[DBZ-8877]
* Transaction events are not removed when transaction event count over threshold  https://issues.redhat.com/browse/DBZ-8880[DBZ-8880]
* Setting Oracle buffer type to an unsupported/invalid value is not validated properly https://issues.redhat.com/browse/DBZ-8886[DBZ-8886]
* Oracle timestamp columns are ignored when temporal mode set to ISOSTRING https://issues.redhat.com/browse/DBZ-8889[DBZ-8889]
* Kinesis Connector does not send failed records during retry, it sends records in original batch https://issues.redhat.com/browse/DBZ-8893[DBZ-8893]
* DDL parsing fails on "BY USER FOR STATISTICS" virtual column clause https://issues.redhat.com/browse/DBZ-8895[DBZ-8895]
* Postgres CapturedTables metric isn't populated. https://issues.redhat.com/browse/DBZ-8897[DBZ-8897]
* Raise more meaningful exception in case of inconsistent post processor config https://issues.redhat.com/browse/DBZ-8901[DBZ-8901]
* Update Outbox Extension Quarkus version to 3.21.2 https://issues.redhat.com/browse/DBZ-8905[DBZ-8905]
* Update to latest LTS of Quarkus 3.15.4 https://issues.redhat.com/browse/DBZ-8906[DBZ-8906]
* FieldToEmbedding SMT fails with NPE for delete records https://issues.redhat.com/browse/DBZ-8907[DBZ-8907]
* FieldToEmbedding SMT crashes when source field name is substring of embedding name https://issues.redhat.com/browse/DBZ-8910[DBZ-8910]
* Improve performance by removing unnecessary filter check https://issues.redhat.com/browse/DBZ-8921[DBZ-8921]
* Async engine doesn't terminate gracefully upon StopEngineException https://issues.redhat.com/browse/DBZ-8936[DBZ-8936]
* Remove unnecessary metadata query and map fetch calls https://issues.redhat.com/browse/DBZ-8938[DBZ-8938]
* Processing error because of incomplete date part of DATETIME datatype in MariaDB https://issues.redhat.com/browse/DBZ-8940[DBZ-8940]
* [Conductor] Add endpoint to verify correct setup of signal data collection  https://issues.redhat.com/browse/DBZ-8941[DBZ-8941]
* ORA-08186 invalid timestamp specified occurs when connector is started https://issues.redhat.com/browse/DBZ-8943[DBZ-8943]
* Multiple Predicates Don't Function with the Operator API https://issues.redhat.com/browse/DBZ-8975[DBZ-8975]

In total, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20and%20fixVersion%20%20in%20(3.2.0.Alpha1)[78 issues] were resolved in Debezium 3.2.0.Alpha1.
The list of changes can also be found in our https://debezium.io/releases/3.2[release notes].

A big thank you to all the contributors from the community who worked diligently on this release:
https://github.com/andreaTP[Andrea Peruffo],
https://github.com/adasari[Anil Dasari],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/ashoke-cube[Ashok],
https://github.com/b-goyal[Bhagyashree Goyal],
Oskar Bonde,
https://github.com/Naros[Chris Cranford],
https://github.com/gaurav7261[Gaurav Miglani],
https://github.com/kmos[Giovanni Panice],
https://github.com/gunnarmorling[Gunnar Morling],
https://github.com/gustavolira[Gustavo Lira],
https://github.com/HarisBinSaif[Haris Bin Saif],
https://github.com/hariso[Haris Osmanagić],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/jkosh44[Joseph Koshakow],
https://github.com/kavyaramaiah[Kavya R],
https://github.com/kavyaramaiah1991[Kavya Ramaiah],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/microhuang[Micro Huang],
https://github.com/peperon[Petar Kostov],
https://github.com/wukachn[Peter Hamer],
https://github.com/PhBouzid[Philipp Bouzid],
https://github.com/rajdangwal[Rajendra Dangwal],
https://github.com/roldanbob[Robert Roldan],
https://github.com/vjuranek[Vojtech Juranek],
https://github.com/spicy-sauce[Yossi Shirizli]