---
layout: post
title:  Debezium Charts
date:   2025-03-18
tags: [ releases, charts, operator, platform, UI ]
author: mfvitale
---
Recently there were some changes around Debezium charts, so I'm here to explain what these changes are and the reason behind them.
As you should be aware from our latest https://debezium.io/blog/2025/03/13/debezium-3-1-beta1-released/[release announcement], we are going to release the first version of our Debezium Management Platform.

Debezium Management Platform aims to simplify the deployment of Debezium to various environments in a highly opinionated manner. To achieve this goal, the platform uses a data-centric view of Debezium components.

It is for us a normal evolution from Debezium Server. We have provided you with an operator to easily operate it in Kubernetes environments, and now we are providing a high-level abstraction to deploy your data pipelines leveraging the operator + Debezium Server.
You can read more on the reasoning behind this new project in the https://debezium.io/blog/2024/08/05/Debezium-ui-update/[Status of Debezium UI].

+++<!-- more -->+++
Until now, we published helm charts only for our https://github.com/debezium/debezium-operator[Debezium Server Operator] and, for those who already started to use it, you should know that we publish it on https://charts.debezium.io/index.yaml[charts.debezium.io].
For those of you with keen eyes, you should have noticed two things:

* Another entry appeared: `debezium-platform`
* The `urls` for the operator have changed.

This is because, since the charts grew from 1 to 2, we decided to unify our charts so that you can easily find them in a single place.
This place is https://charts.debezium.io[charts.debezium.io].

Until now, the operator charts were released through the https://github.com/debezium/debezium-operator-manifests[debezium-operator-manifest] repo that was used not only for generating the helm chart repo index but also to publish the chart artifact.
Starting from now, our chart packages (Debezium operator and Debezium platform) will be published as GitHub release artifacts on their respective repositories and, as described before, the helm chart index will contain both chart releases.

Essentially, we have integrated the charts release into our Debezium release process, eliminating the manual steps done in the past with the operator chart release.

What does it change for you?

If you already used the helm repo, you can just run:

[source,bash]
----
helm repo update
----

so your index will be updated, then if you run:

[source,bash]
----
helm search repo debezium/ --versions --devel
----

you can see that `debezium-platform` has appeared in the index together with the `debezium-operator`.

If you want, for example, to install our Debezium Platform, you can run the following:

[source,bash]
----
helm install debezium-platform debezium/debezium-platform --version 3.1.0-beta1 --set database.enabled=true --set domain.url=platform.debezium.io
----

If instead, you have never used Debezium Helm chart, and you want to start playing with the Debezium Operator or the Debezium Platform, add the repository with:

[source,bash]
----
helm repo add debezium https://charts.debezium.io
----

Lastly, we have also started to publish our Helm charts as OCI artifacts to https://quay.io/organization/debezium-charts[quay.io], in which case you can install our charts with the following command:

[source,bash]
----
helm install debezium-platform --set database.enabled=true --set domain.url=platform.debezium.io --version 3.1.0-beta1 oci://quay.io/debezium-charts/debezium-platform
----

Practically nothing changes for you, but we wanted to share what changed under the hood.

As usual, any feedback is always welcomed.