---
layout: post
title:  Debezium 3.3.1.Final Released
date:   2025-10-15
tags: [ releases, mongodb, mysql, mariadb, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner, jdbc, informix, ibmi, cockroachdb ]
author: ccranfor
extraClasses: release-v2
---

Debezium 3.3.1.Final is a critical maintenance release addressing key issues.

+++<!-- more -->+++

[id=improvements]
== Fixes and improvements

=== JSON strings are properly escaped

When schema fields included nested JSON, there were situations where the escaped text would not be valid JSON that could be parsed because of incorrect escaping.
We have corrected this and JSON that includes nested quotes is now properly escaped (https://issues.redhat.com/browse/DBZ-9540[DBZ-9540]).

=== Oracle no longer mistakenly skips events

When the `lob.enabled` connector configuration property was set to `true`, certain combinations of the order of events would lead to the connector mistakenly dropping events due to out of order sequence emission.
This has been fixed and the only time events are skipped are when they've already previously been processed (https://issues.redhat.com/browse/DBZ-9521[DBZ-9521]).

=== OpenLineage failed on graceful shutdowns

The Debezium OpenLineage integration failed to properly emit the complete event when connectors gracefully shutdown.
This has been fixed and users should no longer see OpenLineage exceptions on graceful shutdowns (https://issues.redhat.com/browse/DBZ-9524[DBZ-9524]).

[id=other-fixes]
=== Other fixes

* MySQL example container images are not properly configured https://issues.redhat.com/browse/DBZ-9485[DBZ-9485]
* Document metric `NumberOfErroneousEvents` https://issues.redhat.com/browse/DBZ-9510[DBZ-9510]
* Only log an error when the dump folder is provided but doesn't exist https://issues.redhat.com/browse/DBZ-9519[DBZ-9519]

In total, https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20and%20fixVersion%20%20in%20(3.3.1.Final)[6 issues] were resolved in Debezium 3.3.1.Final.
The list of changes can also be found in our https://debezium.io/releases/3.3/release-notes[release notes].

A big thank you to all the contributors from the community who worked diligently on this release:
 +
https://github.com/graya-fnz[Adam Gray],
https://github.com/Naros[Chris Cranford],
https://github.com/hamnis[Erlend Hamnaberg],
https://github.com/kmos[Giovanni Panice],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/roldanbob[Robert Roldan],
https://github.com/notation-v[Vipin Kalra], and
https://github.com/vjuranek[Vojtech Juranek]!