---
layout: post
title:  Debezium 3.4.1.Final Released
date:   2026-01-27 00:00:00 -0500
tags: [ releases, mongodb, mysql, mariadb, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner, jdbc, informix, ibmi, cockroachdb ]
author: ccranfor
extraClasses: release-v2
---

As the team continues to work on the next development iteration of Debezium 3.5, we're pleased to report the immediate availability of Debezium **3.4.1.Final**, the first maintenance release of the 3.4 release stream.

+++<!-- more -->+++

In this post, we're going to take a deep dive into the improvements and fixes in this maintenance release of Debezium, highlighting any features or noteworthy changes.
As always, we recommend you read the link:/releases/3.4/release-notes#release-3.4.1-final[release notes] to learn more about all the bugs that were fixed, update procedures, and more.


[id=new-features-and-improvements]
== New features and improvements

=== Debezium for Oracle

==== Dynamic Archive Destination Support

When an Oracle primary server fails over to a standby server, it's very likely that Debezium has not read all the changes from the transaction logs on the primary when the failover occurs.
As a result, when the standby is promoted to the primary, it will begin to write changes to a new archive destination.

When Debezium reconnects to the newly promoted primary, Debezium will attempt to locate where it left off, and fail to start.
This failure to start issue is a result of the fact that the primary changes that were not consumed by Debezium exist in the archive destination specific to the standby system being in standby-mode, not primary-mode.

To solve this issue, the `archive.destination.name` configuration property can be supplied a series of comma-separated archive destination names.
When multiple names are supplied, Debezium will gather logs across all configured destinations and perform a deduplication pass by redo thread and log sequence pairs.
This deduplication pass will prefer logs in earlier destinations from logs in later destinations that have the same thread and sequence pair.

With this change, Debezium is significantly more fault-tolerant during a primary to standby failover and recovers without the need for a snapshot, as long as there is no data loss at the transaction log level between the two systems (https://github.com/debezium/dbz/issues/1246[debezium/dbz#1246]).


[id=other-fixes]
== Other fixes

* Oracle: Recovery private redo threads can lead to LogMiner failures https://github.com/debezium/dbz/issues/40[debezium/dbz#40]
* Oracle: DDL failure when user creates a table with a column named "override" https://github.com/debezium/dbz/issues/1461[debezium/dbz#1461]
* Cassandra: Returns wrong value for DATE columns https://github.com/debezium/dbz/issues/1486[debezium/dbz#1486]
* RedisOffsetBackingStore: Race condition causes infinite NullPointerException loop on reconnect leading to unrecoverable state https://github.com/debezium/dbz/issues/1488[debezium/dbz#1488]
* JDBC Sink: Fails to insert JSON data into MariaDB https://github.com/debezium/dbz/issues/1492[debezium/dbz#1492]
* MySQL: New charset not taken into account https://github.com/debezium/dbz/issues/1504[debezium/dbz#1504]
* Oracle: PDB name in lowercase not collecting DML operation [DBZ-9054] https://github.com/debezium/dbz/issues/1057[debezium/dbz#1057]
* MongoDB: Thread-safety issue causes incorrect `source.collection` metadata during parallel snapshot https://github.com/debezium/dbz/issues/1531[debezium/dbz#1531]
* Oracle: Log mining lower boundary does not update until a log switch https://github.com/debezium/dbz/issues/1560[debezium/dbz#1560]
* Oracle: Create Table DDL fails to parse when using `AUTOMATIC` keyword in partition list https://github.com/debezium/dbz/issues/1566[debezium/dbz#1566]

In total, https://github.com/orgs/debezium/projects/5/views/6?query=sort%3Aupdated-desc+is%3Aopen&filterQuery=status%3AReleased+iteration%3A3.4.1.Final[11 issues] were resolved in Debezium 3.4.1.Final.
The list of changes can also be found in our https://debezium.io/releases/3.4/release-notes[release notes].

A big thank you to all the contributors from the community who worked diligently on this release:
 +
https://github.com/abusquets[Alexandre Busquets],
https://github.com/AlvarVG[Alvar Viana],
https://github.com/big-andy-coates[Andy Coates],
https://github.com/archiedx[archiedx],
https://github.com/atorik[Atsushi Torikoshi],
https://github.com/Naros[Chris Cranford],
https://github.com/cjbooms[Conor Gallagher],
https://github.com/dvolontyr1[Dmitry Volontyr],
https://github.com/kmos[Giovanni Panice],
https://github.com/seanshi007[Guangnan Shi],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/nrkljo[Lars M. Johansson],
https://github.com/mfvitale[Mario Fiore Vitale],
https://github.com/mrtworo[Mateusz Tworek],
https://github.com/nkokitkar[Nikita Kokitkar],
https://github.com/ochedru[Olivier Chédru],
https://github.com/gildur[Piotr Wolny],
https://github.com/rajdangwal[Rajendra Dangwal],
https://github.com/redboyben[redboyben],
https://github.com/findingrish[Rishabh Singh],
https://github.com/roldanbob[Robert Roldan],
https://github.com/SreedevT[sreedev],
https://github.com/twthorn[Thomas Thornton],
https://github.com/ThomasVerhoeven1998[Thomas Verhoeven],
https://github.com/vjuranek[Vojtech Juranek],
https://github.com/william-xiang[William Xiang],
https://github.com/internCoder[Xiang Qiu Min]