---
layout: post
title:  Debezium 3.4.2.Final Released
date:   2026-03-02 00:00:00 -0500
tags: [ releases, mongodb, mysql, mariadb, postgres, sqlserver, cassandra, oracle, db2, vitess, outbox, spanner, jdbc, informix, ibmi, cockroachdb ]
author: ccranfor
extraClasses: release-v2
---

As the team continues to work on the next development iteration of Debezium 3.5, we're pleased to report the immediate availability of Debezium **3.4.2.Final**, the second maintenance release of the 3.4 release stream.

+++<!-- more -->+++

In this post, we're going to take a deep dive into the improvements and fixes in this maintenance release of Debezium, highlighting any features or noteworthy changes.
As always, we recommend you read the link:/releases/3.4/release-notes#release-3.4.2-final[release notes] to learn more about all the bugs that were fixed, update procedures, and more.


[id=new-features-and-improvements]
== New features and improvements

=== Debezium for Oracle

==== Support for Oracle 26ai

The Debezium connector for Oracle now supports Oracle's latest release, Oracle 26ai, based on version 23.26.0 (https://github.com/debezium/dbz/issues/1649[debezium/dbz#1649]).
This ensures that teams adopting Oracle's newest platform can seamlessly integrate change data capture into their workflows from day one.


[id=other-fixes]
== Other fixes

* Avoid storing irrelevant DDL statement "REPLACE INTO" in schema history topic [DBZ-9428] https://github.com/debezium/dbz/issues/1396[debezium/dbz#1396]
* Stuck transaction when using CTE query with Oracle connector https://github.com/debezium/dbz/issues/1564[debezium/dbz#1564]
* Implicit nullability in DDL (ALTER TABLE ... CHANGE ...) not respected by MySQL connector https://github.com/debezium/dbz/issues/1568[debezium/dbz#1568]
* SqlServerMetricsIT tests are unstable https://github.com/debezium/dbz/issues/1572[debezium/dbz#1572]
* "No enum constant io.debezium.connector.postgresql.connection.ReplicationMessage.Operation.NOOP" error when upgrading to Debezium 3.4.0 https://github.com/debezium/dbz/issues/1574[debezium/dbz#1574]
* ORA-03049 raised when querying archive logs https://github.com/debezium/dbz/issues/1579[debezium/dbz#1579]
* Oracle DDL fails to parse https://github.com/debezium/dbz/issues/1594[debezium/dbz#1594]
* Update Informix JDBC Driver to v4.50.13 https://github.com/debezium/dbz/issues/1623[debezium/dbz#1623]
* Oracle Alter index Modify Subpartition Shrink DDL fails https://github.com/debezium/dbz/issues/1637[debezium/dbz#1637]
* A rolled back transaction mined in two steps sometimes leads to partial transaction id [DBZ-9686] https://github.com/debezium/dbz/issues/1145[debezium/dbz#1145]
* Unable to parse ROW ARCHIVAL DDL and corresponding DML with hidden ORA_ARCHIVE_STATE column https://github.com/debezium/dbz/issues/1650[debezium/dbz#1650]
* InformixStreamingChangeEventSource can cause NullPointerException https://github.com/debezium/dbz/issues/1653[debezium/dbz#1653]
* Update to com.mchange:c3p0 to 0.12.0 https://github.com/debezium/dbz/issues/1654[debezium/dbz#1654]

In total, https://github.com/orgs/debezium/projects/5/views/6?query=sort%3Aupdated-desc+is%3Aopen&filterQuery=status%3AReleased+stable-iteration%3A3.4.2.Final[16 issues] were resolved in Debezium 3.4.2.Final.
The list of changes can also be found in our link:/releases/3.4/release-notes#release-3.4.2-final[release notes].

A big thank you to all the contributors from the community who worked diligently on this release:
 +
https://github.com/aofisherzg[Andrew Ofisher],
https://github.com/Naros[Chris Cranford],
https://github.com/duncan-prince[Duncan Prince],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/nrkljo[Lars M. Johansson],
https://github.com/nathan-smit-1[Nathan Smit],
https://github.com/roldanbob[Robert Roldan],
https://github.com/shinsj4653[Seongjun Shin]