---
layout: post
title: "Debezium Community Showcase"
date: 2026-06-24
tags: [ community, meetings, contributors, events, forum, showcase ]
featured: true
author: gpanice
---

It has been a month since we opened our weekly team meeting to the community, and we have received many interesting insights. Because of that, we have decided to create another opportunity for the community to connect and share:

Welcome to the *Debezium Community Showcase*!


Starting *next month*, we will host a *monthly* showcase session that will be live-streamed on YouTube.
Whether you would like to share something about CDC with Debezium, how you use Debezium in your work, or anything related to contributing to the project, you are welcome to submit a talk.

However, if there is not enough content for a given month, the showcase may be postponed to the following month.

== Session Proposal and Participation

To keep track of talks, session proposals will be managed through https://sessionize.com/debezium-community-showcase[Sessionize].

Community members are encouraged to first propose a session in our https://calendar.google.com/calendar/u/0/embed?src=debezium%40gmail.com&ctz=Europe%2FPrague[weekly forum] for a brief evaluation, and then formally submit the proposal through Sessionize so that we can schedule it on the calendar.

== Format of Sessions

We have two kind of sessions based on duration:

- Lightning Talks: 10-15min duration
- Standard talks: 30-40min duration

== Calendar and Scheduling

The showcase will be scheduled on a *Thursday* and will take place during the *weekly forum*, depending on the Debezium team’s schedule and the available content. The showcase will last up to *1 hour* and may include one lightning talk and one standard talk, with a few additional minutes for questions.

We truly believe these sessions provide another great opportunity to share, discuss, and exchange ideas that help shape the future of Debezium.

We look forward to seeing your insights!