# Default page title
title: Debezium

# Project id name
project: debezium

# Project full name
project_name: Debezium

encoding: UTF-8

# Default minify settings
css_minifier: disabled
js_minifier: disabled
html_minifier: disabled

asciidoctor:
  :attributes:
    idprefix: ''
    sectanchors: ''
    icons: font
    # Used when referring to the latest stable Debezium version
    debezium-version: 0.9.5.Final
    # Used when referring to the latest dev version
    debezium-dev-version: 0.10.0.Beta4
    debezium-docker-label: 0.9
    confluent-platform-version: 5.1.2
    debezium-kafka-version: 2.3.0
    strimzi-version: 0.13.0

# Merge multiple JavaScript files to improve performance
fileMerger:
  enabled: true
  outputFilePath: /javascripts/bootstrap-community.js
  paths:
    - /javascripts/_bootstrap-transition.js
    - /javascripts/_bootstrap-alert.js
    - /javascripts/_bootstrap-button.js
    - /javascripts/_bootstrap-carousel.js
    - /javascripts/_bootstrap-collapse.js
    - /javascripts/_bootstrap-dropdown.js
    - /javascripts/_bootstrap-modal.js
    - /javascripts/_bootstrap-tooltip.js
    - /javascripts/_bootstrap-popover.js
    - /javascripts/_bootstrap-scrollspy.js
    - /javascripts/_bootstrap-tab.js
    - /javascripts/_bootstrap-affix.js
    - /javascripts/_jbossorg-navbarfix.js
    - /javascripts/_jbossorg-FeedEk.js
    - /javascripts/_jbossorg-jiraWidget.js
    - /javascripts/_jquery-easytabs.js
    - /javascripts/_crisp-scripts.js

# Cache hosted fonts, images and javascript
wget:
  enabled: true
  rerunEach: 86400 # seconds
  timestampFilename: _wget-timestamp
  options:
    - --no-remove-listing
    - -q
    - -r
    - --no-parent
    - -N
    - --reject 'index.html*'
    - -e robots=off
    - --directory-prefix=cache
  urls:
    - https://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.js
    - https://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.min.js
    - https://static.jboss.org/theme/js/libs/html5/pre3.6/html5.min.js
    - https://static.jboss.org/theme/js/libs/prettify/188.0.0/prettify.min.js
    - https://static.jboss.org/theme/js/libs/holder/1.9/holder.js
    - https://static.jboss.org/theme/fonts/titilliumtext/
    - https://static.jboss.org/theme/fonts/font-awesome/
    - https://static.jboss.org/theme/images/common/
    - https://static.jboss.org/example/

# Update resource URLs based on the profile
profiles:
  development:
    jborg_fonts_url: /cache/static.jboss.org/theme/fonts
    jborg_images_url: /cache/static.jboss.org/theme/images
    jborg_js_url: /cache/static.jboss.org/theme/js
    project_images_url: /cache/static.jboss.org/example/images
    bootstrap_css_url: /stylesheets-source/_bootstrap-community
    bootstrap_js_url: /javascripts/bootstrap-community
    base_url: http://localhost:4242
    disqus_developer: true
    symlinker:
      from: ../stylesheets
      to: ./_site/stylesheets-source
    asciidoctor:
      :attributes:
        base_url: http://localhost:4242
        imagesdir: /images
  staging:
    jborg_fonts_url: https://static.jboss.org/theme/fonts
    jborg_images_url: https://static.jboss.org/theme/images
    jborg_js_url: https://static.jboss.org/theme/js
    project_images_url: https://static.jboss.org/example/images
    bootstrap_css_url: https://static.jboss.org/theme/css/bootstrap-community/3.2.0.2/bootstrap-community
    bootstrap_js_url: https://static.jboss.org/theme/js/libs/bootstrap-community/3.2.0.2/bootstrap-community
    base_url: http://debezium.io/staging
    disqus_developer: true
    wget:
      enabled: false
    asciidoctor:
      :attributes:
        base_url: http://debezium.io/staging
        imagesdir: /staging/images
  production:
    minified: .min
    css_minifier: enabled
    js_minifier: enabled
    html_minifier: enabled
    jborg_fonts_url: https://static.jboss.org/theme/fonts
    jborg_images_url: https://static.jboss.org/theme/images
    jborg_js_url: https://static.jboss.org/theme/js
    project_images_url: https://static.jboss.org/example/images
    bootstrap_css_url: https://static.jboss.org/theme/css/bootstrap-community/3.2.0.2/bootstrap-community
    bootstrap_js_url: https://static.jboss.org/theme/js/libs/bootstrap-community/3.2.0.2/bootstrap-community
    base_url: http://debezium.io
    wget:
      enabled: false
    asciidoctor:
      :attributes:
        base_url: http://debezium.io
        imagesdir: /images
    deploy:
      host: github_pages
      branch: master

google_analytics:
  account: UA-76464546-1
  anonymizeIp: true
  linkAttribution: true

disqus: Debezium
