= Debezium 0.7.0 Is Released
jpechane
:awestruct-tags: [ releases, mysql, mongodb, postgres, docker ]
:awestruct-layout: blog-post


After one month a new release is here! Debezium team brings you  *0.7.0* full of new features but a lot of bugs were squashed too.
And we are happy to say thank you for many external contributions from our community.
Please mind there are several breaking changes in this release so please pay attention to link:/docs/releases/#release-0-7-0[full change log].

Let's take a closer look at some of the changes.

== Apache Kafka
Few weeks ago the Apache Kafka team has https://www.confluent.io/blog/apache-kafka-goes-1-0/[released version 1.0.0] and we can now declare that Debezium is https://issues.jboss.org/browse/DBZ-432[built] with and runs on the first major Apache Kafka release.
Our Docker images were also https://issues.jboss.org/browse/DBZ-433[promoted] to contain Apache Kafka 1.0.0.

== PostgreSQL Connector

The PostgreSQL connector now https://issues.jboss.org/browse/DBZ-258[supports] https://github.com/eulerto/wal2json[wal2json] logical decoder plugin.
This means that you can try to run Debezium with PostgreSQL on https://aws.amazon.com/rds/[Amazon RDS] as it is the plugin that Amazon uses.
Just be aware that Amazon's version is few commits behind the recent one so there might not be a feature parity.
Many thanks to https://github.com/rcoup[Robert Coup] who significantly contributed to this feature.

There are new daily running https://issues.jboss.org/browse/DBZ-495[CI jobs] that verify that `wal2json` plugin passes our test suite.

We have identified and fixed an https://issues.jboss.org/browse/DBZ-379[ugly bug] caused by an internal race condition.
In previous version the decoder plug-in send the change events and metadata were obtained from JDBC.
When schema was changed this could result in old change event matched against a new JDBC metadata.
Current version of both decoders sends metadata together with data so we no longer depends on the JDBC channel.
There is still an exception to this rule: primary key information metadata.
These needs to be obtained via JDBC so be careful when you change primary key definitions.
See release documentation for more details.

https://github.com/jchipmunk[Andrey Pustovetov] discovered and proposed a fix for a https://issues.jboss.org/browse/DBZ-501[multi-threading bug] in PotsgreSQL Connector that could put the connector into undefined state during if rebalance is triggered during snapshot. 

== MySQL Connector

`BIGINT UNSIGNED` type is now encoded as `int64` type in  Debezium messages https://issues.jboss.org/browse/DBZ-495[by default] as it is easier for (polyglot) clients to work with.
If your values will not fit into the `int64` range you can switch it back to `Decimal` logical type.

https://github.com/rk3rn3r[Rene Kerner] has extended suport for MySQL `TIME` type.
It is possible to work with values larger than `23:59:59` and the type is no longer mapped as `int64` but has changed into `io.debezium.time.MicroTime` logical type.

Recently we got a https://issues.jboss.org/browse/DBZ-390[report] that MySQL's commit log can contain `ROLLBACK` statements and thus transactions that are not in effect committed.
So we introduced a https://issues.jboss.org/browse/DBZ-406[look-ahead buffer] functionality that reads commit log by transaction and excludes those that were rolled back.
This feature should be considered incubating and is disabled by default but we already welcome all feedback from the users.

https://github.com/ainagy[Andras Istvan Nagy] came with idea and https://issues.jboss.org/browse/DBZ-349[implemented] a way how to define a set of rows from each table that will be part of snapshotting process.
This feature has a big potential to simplify execution of large datasets snapshots.

Please see the link:/docs/releases/#release-0-7-0[full change log] for more details and the complete list of fixed issues.

== What's next?

The Debezium 0.7.1 release is planned to be out roughly two weeks after Christmas.

It will contain a new SMT that will unwind MongoDB change events into a regular JSON consumable by sink connectors.

A big overhaul of `GEOMETRY` types is in progress.
When completed all `GEOMETRY` types will be supported by both MySQL and PostgreSQL connectors and they will be available in standard `WKB` format for easy consumption by polyglot clients.

There is ongoing work for MySQL connector to allow dynamic update of `table.whitelist` option.
This will allow the user to re-configure the set of tables captured without need to re-create connector.

If you'd like to contribute, please let us know.
We're happy about any help and will work with you to get you started quickly.
Check out the details below on how to get in touch.

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.jboss.org/projects/DBZ/issues/[log an issue].
