= Debezium 0.6.2 Is Released
jpechane
:awestruct-tags: [ releases, mysql, mongodb, postgres, docker ]
:awestruct-layout: blog-post

We are accelerating! In 3 weeks since 0.6.1 release the Debezium team is briging **Debezium 0.6.2** for public consumption!

This release revolves mostly around bugfixes but we are bringing few new features too.

Let's take a closer look at some of the changes.

== PostgreSQL Connector

By far the most changes we come with are related to PostgreSQL connector.
Debezium now runs against https://issues.jboss.org/projects/DBZ/issues/DBZ-424[PostgreSQL 10] thanks to contribution from https://github.com/ScofieldXu[Scofield Xu].
As a part of this change we are providing a https://issues.jboss.org/projects/DBZ/issues/DBZ-426[Docker Image] with PostgreSQL 10 too and we run a http://ci.hibernate.org/view/Debezium/job/debezium-postgresql-10-test/[daily integration] test against it.
f
If you are building PostgreSQL images derived for the ones provided by Debezium and you would like to reduce their size then you can https://issues.jboss.org/projects/DBZ/issues/DBZ-445[omit PostGIS] from it and make it smaller.
Of course it works only when you are not using geometric data. Thanks to https://github.com/QazerLab[Danila Kiver] for the contribution.

== Changes in release process

As a part of release process we are now creating https://issues.jboss.org/projects/DBZ/issues/DBZ-418[micro tags] for every released version.
So tags in format `x.y.z` are fixed in time and in format `x.y` are rolled forward.


== Miscellaneous

We have expanded our examples repository with https://github.com/debezium/debezium-examples/tree/master/tutorial#using-mysql-and-the-avro-message-format[an Avro example].
For MySQL you wil get an information about https://issues.jboss.org/projects/DBZ/issues/DBZ-401[binlog position] in case of an error.

== Bugfixes

We have fixed quite a lot of bugs recently.
One of them can have an impact on existing applications as we now properly support https://issues.jboss.org/projects/DBZ/issues/DBZ-260[timezones in timestamps] in MySQL connector.

Other issues are related to MySQL parser which now covers more corner cases, a hidden https://issues.jboss.org/projects/DBZ/issues/DBZ-438[concurrency issue] was found in MongoDB connector, and https://issues.jboss.org/projects/DBZ/issues/DBZ-217[reliability] and https://issues.jboss.org/projects/DBZ/issues/DBZ-396[performance] of MySQL connector was improved.

Please see the link:/docs/releases/#release-0-6-2[full change log] for more details and the complete list of fixed issues.

== What's next?

The work on Oracle connector has stalled a little bit but we are now back on full throttle.
Further changes will include upgrade to Kafka 1.0.0 and there is move forward on dynamic updates of whitelisted tables for MySQL connector.

If all things will go smooth you can expect 0.7 as a gift under your Christmas tree.

If you'd like to contribute, please let us know.
We're happy about any help and will work with you to get you started quickly.
Check out the details below on how to get in touch.

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.jboss.org/projects/DBZ/issues/[log an issue].
