= Debezium 0.9.3.Final Released
jpechane
:awestruct-tags: [ releases, mysql, mongodb, postgres, sqlserver, docker ]
:awestruct-layout: blog-post

The Debezium team is happy to announce the release of Debezium *0.9.3.Final*!

This is mostly a bug-fix release and a drop-in replacement for earlier Debezium 0.9.x versions but there are few signifacnt new features too.
Overall, https://issues.jboss.org/issues/?jql=project%20%3D%20DBZ%20AND%20fixVersion%20%3D%200.9.3.Final[17 issues] were resolved.

[NOTE]
Docker images will be released with a delay due to Docker Hub configuration issues.

== New Features

The 0.9.3 release also comes with two larger new features:

* A feature request was made to execute a partial recovery of replication process from lost slot in PostgreSQL database.
The result is a first service provider interface in Debezium that allows the user to inject itw own Java class that controls snaphotting process (https://issues.jboss.org/browse/DBZ-1082[DBZ-1082]).
The feature is still in incubating phase and the SPI should be considered unstable.
* Not a long ago a blogpost was published about implementation of the link:/blog/2019/02/19/reliable-microservices-data-exchange-with-the-outbox-pattern/[outbox] pattern with Debezium.
https://github.com/renatomefi[Renato Mefi] expanded the idea and created an implementation that is part of Debezium core library (https://issues.jboss.org/browse/DBZ-1169[DBZ-1169]).

== Bug fixes

A couple of fixes relate to the link:/docs/connectors/postgres/[Debezium Postgres connector]:

* A regression that introduced deadlock in snapshotting process has been fixed (https://issues.jboss.org/browse/DBZ-1161[DBZ-1161])
* `hstore` datatype works correctly in snapshot phase (https://issues.jboss.org/browse/DBZ-1162[DBZ-1162])
* `wal2json` plug-in processes also empty events (https://issues.jboss.org/browse/DBZ-1181[DBZ-1181])
* Commit time is propely converted to microseconds (https://issues.jboss.org/browse/DBZ-1174[DBZ-1174])


Also the link:/docs/connectors/mysql/[Debezium MySQL connector] saw a number of fixes especially in SQL parser:

* `SERIAL` datatype and default value is now supported (https://issues.jboss.org/browse/DBZ-1185[DBZ-1185])
* A specific deatil in MySQL grammar that allowed to enumerate table options in `ALTER TABLE` without comma works (https://issues.jboss.org/browse/DBZ-1186[DBZ-1186])
* A false alarm for empty MySQL password is no longer reported (https://issues.jboss.org/browse/DBZ-1188[DBZ-1188])
* It is no longer necessary to create history topic manually for broker without default topic replication value (https://issues.jboss.org/browse/DBZ-1179[DBZ-1179])

It is now possible to process multiple schemas with a single Oracle connector (https://issues.jboss.org/browse/DBZ-1166[DBZ-1166]).

Check out the link:/docs/releases/#release-0-9-3-final[release notes] for the complete list of issues fixed in Debezium 0.9.3.

Many thanks to Debezium community members https://github.com/renatomefi[Renato Mefi], https://github.com/ShubhamRwt[Shubham Raj], https://github.com/addisonj[Addison Higham], https://github.com/jcasstevens[Jon Casstevens], https://github.com/hashhar[Ashar Hassan] and https://github.com/p5k6[Josh Stanfield] for their contributions to this release!

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.jboss.org/projects/DBZ/issues/[log an issue].
