= Debezium's Newsletter 02/2019
ccranfor
:awestruct-tags: [ community, news, newsletter ]
:awestruct-layout: blog-post

Welcome to the Debezium community newsletter in which we share blog posts, group discussions, as well as StackOverflow
questions that are relevant to our user community.

== Upcoming Events

* https://jokerconf.com[JokerConf - Practical change data streaming uses cases with Apache Kafka and Debezium]
* https://qconsf.com[QCon San Fransisco - Practical change data streaming use cases with Apache Kafka and Debezium]

== Articles

This https://debezium.io/blog/2019/10/01/audit-logs-with-change-data-capture-and-stream-processing/[recent blog] by Gunnar Morling discusses how Debezium combined with Kafka stream post processing can deliver an enriched stream of events suitable for even the most complicated of tasks like audit tracking.

Rod Shokrian from Varo https://medium.com/engineering-varo/event-driven-architecture-and-the-outbox-pattern-569e6fba7216[recently blogged] about their CDC solution and experiences using Debezium in conjunction with the Outbox Pattern.

Community involvement is critical to each Open Source project and Debezium is no different.  Joy Gao https://wecode.wepay.com/posts/streaming-cassandra-at-wepay-part-1[blogs] about her experience at WePay where CDC innovation brought Cassandra and Debezium together.

== Examples

* [NEW] https://github.com/debezium/debezium-examples/tree/master/auditlog[Build Audit Logs using Debezium and Kafka Streams]
* [NEW] https://github.com/debezium/debezium-examples/tree/master/postgres-toast[Dealing with PostgreSQL TOAST columns]
* [UPDATE] https://github.com/debezium/debezium-examples/tree/master/end-to-end-demo[End to End demo now supports propagating delete events]
* [UPDATE] https://github.com/debezium/debezium-examples/tree/master/unwrap-smt[Unwrap SMT example now propagates delete events]
* [UPDATE] https://github.com/debezium/debezium-examples/tree/master/unwrap-mongodb-smt[MongoDB Unwrap SMT example now propagates delete events]

== Time to upgrade

Debezium version https://debezium.io/blog/2019/10/02/debezium-0-10-0-final-released/[0.10.0.Final] was released at the beginning of October.
If you are using the 0.9 branch, we urge you to check out the latest major release.
For details on the bug fixes, enhancements, and improvements that spanned 8 preview releases, check out the https://debezium.io/releases/0.10/release-notes/[release-notes].

The Debezium team has also begun active development on the next major version, 1.0.
If you want details on the bug fixes, enhancements, and improvements, you can view https://debezium.io/releases/1.0/release-notes[release-notes] for more details.

== Questions and answers

* https://stackoverflow.com/questions/58337376/debezium-postgres-error-parameter-include-unchanged-toast-was-deprecated[Debezium postgres ERROR: Parameter "include-unchanged-toast" was deprecated]
* https://stackoverflow.com/questions/57095096/unable-to-register-debezium-kafka-connect-connector-in-ssl-enabled-kafka-clust[Unable to register Debezium (Kafka-Connect) connector in SSL enabled Kafka cluster]
* https://groups.google.com/d/msg/debezium/1vKTWwcf71I/L98pV5nnBgAJ[Debezium or database triggers]

== Using Debezium?

We recently added a https://www.debezium.io/community/users[community users] page to https://www.debezium.io.
If you are a user of Debezium and would like to be included, please send us a GitHub Pull Request or reach out to us directly.

== Getting involved

It can often be overwhelming when starting work on an existing code base.
We welcome community contributions and we want to make the process of getting started extremely easy.
Below is a list of open issues that are currently labeled with `easy-starter` if you want to dive in quick.

* Configure Avro serialization automatically when detecting link to schema registry (https://issues.jboss.org/browse/DBZ-59[DBZ-59])
* Add tests for using fallback values with default REPLICA IDENTITY (https://issues.jboss.org/browse/DBZ-1158[DBZ-1158])
* Add ability to insert fields from op field in ExtractNewRecordState SMT (https://issues.jboss.org/browse/DBZ-1452[DBZ-1452])
* Support CREATE TABLE ... LIKE syntax for blacklisted source table (https://issues.jboss.org/browse/DBZ-1496[DBZ-1496])
* Provide change event JSON Serde for Kafka Streams (https://issues.jboss.org/browse/DBZ-1533[DBZ-1533])
* Explore SMT for Externalizing large column values (https://issues.jboss.org/browse/DBZ-1541[DBZ-1541])
* Whitespaces not stripped from table.whitelist (https://issues.jboss.org/browse/DBZ-1546[DBZ-1546])

== Feedback

We intend to publish new additions of this newsletter periodically.
Should anyone have any suggestions on changes or what could be highlighted here, we welcome that feedback.
You can reach out to us via any of our community channels found link:/community[here].
