= Debezium wears Fedora
jpechane
:awestruct-tags: [ postgres, fedora, vagrant ]
:awestruct-layout: blog-post

Debezium project strives to provide easy deployment of connectors so a user can try and run a connector of his choice without too many additional steps or dependencies if this is possible without any licensing issues.
This is true for all connectors but for PostgreSQL connector.

PostgreSQL connector is specific in the regard that it requires a logical decoding plug-in to be installed inside PostgreSQL source databases, either https://github.com/debezium/postgres-decoderbufs[Protocol Buffers-based] or https://github.com/eulerto/wal2json[JSON-based].

We generally provide two ways of how the user can consume and deploy the necessary plug-in.
By far the easiest one is to use one of our pre-made https://hub.docker.com/r/debezium/postgres[Docker images].
If you are using containers in your datacenter and/or if you start a fresh database from scratch then you should probably follow this path.

The other option is building from the source.
Even if this is usually an easy task it still brings a barrier to an easy start and requires a non-trivial knowledge of Linux operating system.

To bridge the gap between those two extremes we've created and delivered an https://src.fedoraproject.org/rpms/postgres-decoderbufs[RPM package] available for Fedora 30 and Fedora Rawhide.
By installing the package you will have the necessary binaries deployed in place and the only task remaining is the configuration of PostgreSQL configuration files to enable the plug-in.

== Example

Let's show how the package works.
We will use https://www.vagrantup.com/[Vagrant] tool as an easy way how to fire up a pre-provisioned a virtual machine with Fedora but it is definitely not a requirement.

Create and start virtual machine with Fedora 30
```
$ vagrant init fedora/30-cloud-base
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
.
.
.
==> default: Machine booted and ready!

```

Log into the virtual machine
```
$ vagrant ssh
```

Install PostgreSQL server and Procol Buffers logical decoding plug-in
```
$ sudo yum -y install postgresql postgres-decoderbufs
.
.
.
Installed:
  postgres-decoderbufs-0.9.5-1.fc30.x86_64              postgresql-11.3-1.fc30.x86_64                             
  postgis-2.5.1-1.fc30.x86_64                           armadillo-9.400.4-1.fc30.x86_64                           
  blas-3.8.0-12.fc30.x86_64                             cairo-1.16.0-5.fc30.x86_64                                
  cups-libs-1:2.2.11-2.fc30.x86_64                      fontconfig-2.13.1-8.fc30.x86_64                           
  lapack-3.8.0-12.fc30.x86_64                           libgfortran-9.1.1-1.fc30.x86_64                           
  libpq-11.3-2.fc30.x86_64                              libquadmath-9.1.1-1.fc30.x86_64                           
  mariadb-connector-c-3.0.10-1.fc30.x86_64              mariadb-connector-c-config-3.0.10-1.fc30.noarch           
  nss-3.44.0-2.fc30.x86_64                              nss-softokn-3.44.0-2.fc30.x86_64                          
  nss-softokn-freebl-3.44.0-2.fc30.x86_64               nss-sysinit-3.44.0-2.fc30.x86_64                          
  nss-util-3.44.0-2.fc30.x86_64                         poppler-0.73.0-9.fc30.x86_64                              
  postgresql-server-11.3-1.fc30.x86_64                  proj-5.2.0-2.fc30.x86_64                                  
  proj-datumgrid-1.8-2.fc30.noarch                      uriparser-0.9.3-1.fc30.x86_64                             
  SuperLU-5.2.1-6.fc30.x86_64                           arpack-3.5.0-6.fc28.x86_64                                
  atk-2.32.0-1.fc30.x86_64                              avahi-libs-0.7-18.fc30.x86_64                             
  cfitsio-3.450-3.fc30.x86_64                           dejavu-fonts-common-2.37-1.fc30.noarch                    
  dejavu-sans-fonts-2.37-1.fc30.noarch                  fontpackages-filesystem-1.44-24.fc30.noarch               
  freexl-1.0.5-3.fc30.x86_64                            fribidi-1.0.5-2.fc30.x86_64                               
  gdal-libs-2.3.2-7.fc30.x86_64                         gdk-pixbuf2-2.38.1-1.fc30.x86_64                          
  gdk-pixbuf2-modules-2.38.1-1.fc30.x86_64              geos-3.7.1-1.fc30.x86_64                                  
  giflib-5.1.9-1.fc30.x86_64                            graphite2-1.3.10-7.fc30.x86_64                            
  gtk-update-icon-cache-3.24.8-1.fc30.x86_64            gtk2-2.24.32-4.fc30.x86_64                                
  harfbuzz-2.3.1-1.fc30.x86_64                          hdf5-1.8.20-6.fc30.x86_64                                 
  hicolor-icon-theme-0.17-5.fc30.noarch                 jasper-libs-2.0.14-8.fc30.x86_64                          
  jbigkit-libs-2.1-16.fc30.x86_64                       lcms2-2.9-5.fc30.x86_64                                   
  libXcomposite-0.4.4-16.fc30.x86_64                    libXcursor-1.1.15-5.fc30.x86_64                           
  libXdamage-1.1.4-16.fc30.x86_64                       libXfixes-5.0.3-9.fc30.x86_64                             
  libXft-2.3.2-12.fc30.x86_64                           libXi-1.7.9-9.fc30.x86_64                                 
  libXinerama-1.1.4-3.fc30.x86_64                       libaec-1.0.4-1.fc30.x86_64                                
  libdap-3.20.3-1.fc30.x86_64                           libgeotiff-1.4.3-3.fc30.x86_64                            
  libgta-1.0.9-2.fc30.x86_64                            libjpeg-turbo-2.0.2-1.fc30.x86_64                         
  libkml-1.3.0-19.fc30.x86_64                           libspatialite-4.3.0a-11.fc30.x86_64                       
  libtiff-4.0.10-4.fc30.x86_64                          libwebp-1.0.2-2.fc30.x86_64                               
  netcdf-4.4.1.1-12.fc30.x86_64                         nspr-4.21.0-1.fc30.x86_64                                 
  ogdi-3.2.1-4.fc30.x86_64                              openblas-0.3.5-5.fc30.x86_64                              
  openblas-openmp-0.3.5-5.fc30.x86_64                   openblas-serial-0.3.5-5.fc30.x86_64                       
  openblas-threads-0.3.5-5.fc30.x86_64                  openblas-threads64_-0.3.5-5.fc30.x86_64                   
  openjpeg2-2.3.1-1.fc30.x86_64                         pango-1.43.0-3.fc30.x86_64                                
  pixman-0.38.0-1.fc30.x86_64                           poppler-data-0.4.9-3.fc30.noarch                          
  protobuf-c-1.3.1-2.fc30.x86_64                        unixODBC-2.3.7-4.fc30.x86_64                              
  xerces-c-3.2.2-2.fc30.x86_64                         

Complete!

```

Initialize the database
```
$ sudo /usr/bin/postgresql-setup --initdb
```

Enable plug-in in database server configuration file `/var/lib/pgsql/data/postgresql.conf` by adding parameters
```
# MODULES
shared_preload_libraries = 'decoderbufs'

# REPLICATION
wal_level = logical             # minimal, archive, hot_standby, or logical (change requires restart)
max_wal_senders = 8             # max number of walsender processes (change requires restart)
wal_keep_segments = 4           # in logfile segments, 16MB each; 0 disables
#wal_sender_timeout = 60s       # in milliseconds; 0 disables
max_replication_slots = 4       # max number of replication slots (change requires restart)
```

Configure security file `/var/lib/pgsql/data/pg_hba.conf` for the database user that will be used by Debezium (e.g. `debezium`) by adding parameters
```
local   replication     debezium                          trust
host    replication     debezium  127.0.0.1/32            trust
host    replication     debezium  ::1/128                 trust
```

Start PostgreSQL
```
$ sudo systemctl restart postgresql
```

Now the virtual machine contains a PostgreSQL database that is ready to stream changes to PostgreSQL Debezium connector.
The decoder can be of course installed to already existing database just by installing the RPM package and configuring the config and security files.

== About Debezium

Debezium is an open source distributed platform that turns your existing databases into event streams,
so applications can see and respond almost instantly to each committed row-level change in the databases.
Debezium is built on top of http://kafka.apache.org/[Kafka] and provides http://kafka.apache.org/documentation.html#connect[Kafka Connect] compatible connectors that monitor specific database management systems.
Debezium records the history of data changes in Kafka logs, so your application can be stopped and restarted at any time and can easily consume all of the events it missed while it was not running,
ensuring that all events are processed correctly and completely.
Debezium is link:/license/[open source] under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].

== Get involved

We hope you find Debezium interesting and useful, and want to give it a try.
Follow us on Twitter https://twitter.com/debezium[@debezium], https://gitter.im/debezium/user[chat with us on Gitter],
or join our https://groups.google.com/forum/#!forum/debezium[mailing list] to talk with the community.
All of the code is open source https://github.com/debezium/[on GitHub],
so build the code locally and help us improve ours existing connectors and add even more connectors.
If you find problems or have ideas how we can improve Debezium, please let us know or https://issues.jboss.org/projects/DBZ/issues/[log an issue].
