= Site and Documentation Overhaul
ccranfor
:awestruct-tags: [ community, news, website ]
:awestruct-layout: blog-post

This past summer has been a super exciting time for the team.
Not only have we been working hard on Debezium 0.10 but we have unveiled some recent changes to link:https://www.debezium.io[debezium.io].

== New Releases Page

It is important that the Debezium community be able to find information easily about a given release series.
We have introduced a new link:https://www.debezium.io/releases[Releases] area on the site that describes details about each release series such as:

* What database or Apache Kafka (Connect) platforms were tested
* What Java version is supported
* How to migrate to a specific release series
* Where to download the connectors or other series artifacts
* What changes were introduced in that series
* And much more...

The goal is to make it simple and easy to find all information about a specific release series in a single place.

== New Documentation

Probably one of the most limiting factors with how our documentation was published previously is that it focused solely on the idea of the _latest stable_ version.
This presented several drawbacks:

* Confusing to users of older releases
* Prevents publishing documentation for _development_ versions

What we felt we needed to provide the community was documentation published by version.
This would allow documentation to be tailored specific to that version, allowing fluid changes for future versions without impact to prior versions.

Such a solution also has the benefit that it enables the Debezium team to publish _development_ version documentation easily, which is a critical step in helping users who test unstable releases.

Going forward, Debezium documentation can be found at link:https://www.debezium.io/documentation[Reference documentation].
This page allows visitors to quickly navigate to documentation for a specific version.
Once in the documentation, you can quickly navigate between various Debezium versions easily.

== Feedback

We certainly hope these recent changes make it much easier for the community.

If something is unclear, could be improved, or worse a link that isn't working, we welcome feedback.
You can report such concerns to us by link:https://issues.jboss.org[opening an issue] for our website.
