---
layout: page-menu
title: Contribute to Debezium
permalink: /community/contribute
---
:linkattrs:
:icons: font

We're an active open source software community. We welcome and value contributions from everyone, and have adopted a link:/community/code-of-conduct/[code of conduct] for our community.

[[follow]]
== Follow us

We frequently post to https://twitter.com/debezium[Twitter] about important goings on in the community. We also write on our link:/blog/[blog] about features, plans, and related technology. Follow both to keep track of what's going on with Debezium.

[[talk]]
== Talk to us

There are two ways you can talk with our community about development related topics:

* https://gitter.im/debezium/dev[Join us on Gitter] for the best and most immediate way to talk with the developers behind Debezium.
* https://groups.google.com/forum/#!forum/debezium[Join and post to our mailing list] for questions or suggestions that require more lengthy descriptions and context.

[[suggest]]
== Suggest improvements

See a problem or think of something that we could do better? Check our https://issues.redhat.com/projects/DBZ/issues[issues] to see if it's already been mentioned or discussed. If it has, join the conversation to add your take. Otherwise, go ahead and create an issue with more detail than you think is necessary.

[[contribute-code]]
== Code

All of our code is in the https://github.com/debezium/[Debezium Organization] on GitHub, and currently we have several repositories.

1. Get your development environment set up with the latest code, following the instructions in https://github.com/debezium/debezium/blob/master/CONTRIBUTE.md[CONTRIBUTE.md].
2. Check our https://issues.redhat.com/projects/DBZ/issues/?filter=allopenissues[open issues], especially those with the https://issues.redhat.com/issues/?jql=project%20%3D%20DBZ%20AND%20labels%20%3D%20help_wanted[help_wanted] label.
3. Look at previous https://github.com/debezium/debezium/pulls[pull requests] to learn our coding style and conventions.
4. https://gitter.im/debezium/dev[Ask fellow developers] for guidance if you're not sure how to proceed, get stuck, or simply need confirmation that you're headed in the right direction.
5. Make your changes and create a pull request, following our https://github.com/debezium/debezium/blob/master/CONTRIBUTE.md#making-changes[guidelines].

[[website]]
== Website

Our website is also a community effort, and we welcome suggestions, fixes, improvements, and even new blog posts related to Debezium. Everything for our website is also in https://github.com/debezium/debezium.github.io[on GitHub]. Follow the instructions in https://github.com/debezium/debezium.github.io/blob/develop/CONTRIBUTING.md[CONTRIBUTE.md] to get your environment set up with the latest source and to make your changes.

[[governance]]
== Governance

Debezium is an open source project owned and sponsored by https://www.redhat.com/[Red Hat]. The Debezium name and logo are trademarks of Red Hat.

The Debezium project is operated as a community-centric open source project. While Red Hat product management has a voice, it is akin to the same voice of any member of the community, whether they contribute code, bug reports, bug fixes or documentation.

