---
layout: page-menu
title: Governance
permalink: /community/governance/
---
:linkattrs:
:icons: font

This document outlines the governance model for Debezium projects.

== Overview

Anyone can contribute to Debezium by following the https://github.com/debezium/debezium/blob/main/CONTRIBUTING.md[contribution workflow] or discussing features and improvements on GitHub issues.
To become a committer in the Debezium project, start by making approved pull requests.
After sufficient trust is built working on Debezium, any current Debezium committer can nominate you to the steering committee for a committer role.

[[project-roles]]
== Project Roles

For governance purposes, there are three formal roles for the Debezium project.

* **Contributor**: +
Any community member who is not yet a committer.
* **Committers**: +
A group of contributors with the right to merge pull requests into the Debezium repositories and publish releases.
* **Steering Committee**: +
A committee composed of committers with the final authority over all decisions made on the project.

[[contributor]]
=== Contributor

Anyone who actively participates in the Debezium project is recognized as a contributor.
While this often includes individuals who submit code changes via pull requests, contributors also encompass those who engage in discussions on GitHub issues and pull requests.

Contributors form the foundation of the Debezium community.
We welcome and encourage everyone to get involved in any way they can.

[[committer]]
=== Committer

A committer is an individual who has been granted the right to merge pull requests into one of several Debezium GitHub repositories.
A pull request requires a voting/review procedure prior to merging, outlined below in the link:#pull-requests[Pull Requests] section.

A list of Debezium's committers can be found in https://github.com/debezium/governance/blob/main/committers.yml[committers.yml].

[[steering-committee]]
=== Steering Committee

The Debezium Steering committee is a group of committers who have the final authority over all decisions regarding the Debezium project, including but not limited to:

* Whether pull requests are merged or retained in the event of a dispute.
* Who should become a committer or member of the steering committee.
* Whether any changes are necessary to the project's governance or other assets in the https://github.com/debezium/governance[Governance] repository.

A list of Debezium's steering committee members can be found in https://github.com/debezium/governance/blob/main/steering-committee.yml[steering-committee.yml].

[[pull-requests]]
== Pull Requests

Pull requests against most repositories may be merged after receiving at least two positive committer or steering committee member votes.
Voting for pull requests can be done by providing a comment, a thumbs-up, or using the pull request approval workflow.

Pull requests that are small, low-risk, uncontroversial, or prefixed with `[ci]` or `[docs]` may be merged freely by anyone with commit privileges without a vote.
Examples of such pull requests may include, but are not limited to:

* Refactoring redundant code within a small number of files (2-5) that yields no behavior change.
* Adding or changing logged output.
* Adding or improving the test suite code with no loss of test coverage.
* Updating an action used by GitHub Actions, which commits should be prefixed with `[ci]`.
* Fixing typos or very small clarifications to the documentation, which commits should be prefixed with `[docs]`.

**Whenever in doubt about a pull request's scope or risk, fallback to the two positive vote requirement.**

The following repositories use a separate workflow and are excluded from this workflow:

* https://github.com/debezium/debezium-design-documents, see the link:#proposals[Proposals] section.
* https://github.com/debezium/governance, see the link:#project-governance-changes[Project Governance Changes] section.

[[proposals]]
== Proposals

Proposals, often referred to as _Debezium Design Documents_, are used to define changes to the Debezium project that could significantly impact its users or the project's direction.
Opening a proposal provides an opportunity for maintainers to review a concept before coding begins.
A proposal can be opened in the https://github.com/debezium/debezium-design-documents[Debezium Design Documents] repository by creating a pull request.

Proposals require link:#lazy-consensus-voting[lazy consensus voting], a procedure where steering committee members cast binding votes.
Any non-steering committee member may freely cast non-binding votes.
Non-binding votes are highly encouraged as they provide an indication to the proposals broader acceptance in the Debezium community.

Votes can be expressed by approving the pull request or specifying `+1` (thumbs-up emoji) on the original comment of the pull request.
Any other votes or positions can be expressed in a separate comment on the proposal.

**If you wish to express a disapproval with a `-1` (thumbs-down emoji), a reason must be given for the vote to be valid.**

[[project-governance-changes]]
== Project Governance Changes

The https://github.com/debezium/governance[Debezium governance] repository outlines the project's governance, code of conduct, along with a record of changes to steering committee and committer roles.

Any change in this repository requires an link:#explicit-majority-voting[explicit majority vote] except for when a steering committee member marks themselves as Emeritus, which indicates they're transitioning to an inactive status.
The vote is held by the steering committee where each non-Emeritus committee member can cast a binding vote and there are no non-binding votes.

The outcome of the vote will be made publicly available after the vote has concluded.

[[add-remove-committers]]
== Adding or Removing Committers

The process to add or remove someone as a committer requires an link:#explicit-majority-voting[explicit majority vote].
The vote is held by the steering committee, where each non-Emeritus committee member can cast a binding vote.

The outcome of the vote will be made publicly available, the https://github.com/debezium/governance/blob/main/committers.yml[committers.yml] file updated, and GitHub teams adjusted accordingly after the vote ends.

[[add-remove-steering-committee-members]]
== Adding or Removing Steering Committee members

The process to add or remove someone as a steering committee member requires an link:#explicit-majority-voting[explicit majority vote].
The vote is held by the steering committee, where each non-Emeritus committee member can cast a binding vote.

The outcome of the vote will be made publicly available, the https://github.com/debezium/governance/blob/main/steering-committee.yml[steering-committee.yml] file updated, and GitHub teams adjusted accordingly after the vote ends.

=== Extended absence

If a steering committee member is absent for more than 6-months, the committee will contact the member directly via email.
If there is no response from the committee member after a 1-month period, the committee member will be moved to Emeritus status by updating the https://github.com/debezium/governance/blob/main/steering-committee.yml[steering-committee.yml] accordingly.

=== Other changes

Unless already specified in herein, all other changes to the project require an link:#explicit-majority-voting[explicit majority vote] of steering committee members.
Additionally, any committee member, at any time, may request that any change require an explicit majority vote by the steering committee.

[[voting-strategies]]
== Voting Strategies

The Debezium project uses a voting system to guarantee no single member or entity can dominate the project, and ensures continued success and diversity in the project's forward vision.

The formal voting process involves the creation of a GitHub issue or pull request.
A vote is indicated by specifying `yes` or `no` on the issue or pull request, which can include the thumbs-up or thumbs-down emojis, or the use of the GitHub approval workflow.
After a defined period of time, votes are tallied, and the outcome is published.

Debezium uses several different strategies to handle voting, shown here:

* link:#lazy-consensus-voting[Lazy consensus voting]
* link:#explicit-majority-voting[Explicit majority voting]

Each of these strategies rely on two types of votes:

* **Binding**: a vote from a member with specific roles used to tally the outcome of the vote.
The determination of what roles are considered for binding votes is based on the subject area of the vote, such as a project proposal or governance changes as examples.
* **Non-Binding**: any other vote cast by individuals who do not meet the binding vote requirements.
While these votes do not count toward the outcome tally, they are heavily relied upon to guide those with binding-vote rights to the outcome that beset fits all involved.
The use of non-binding votes, where applicable, is highly encouraged.

[[lazy-consensus-voting]]
=== Lazy consensus voting

A lazy consensus vote uses `+1`, `0`, or `-1` to indicate one's position on a topic.

* `+1` indicates you approve
* `-1` indicates you disapprove
* `0` indicates you have no specific opinion

The voting process concludes when there are at least three `+1` binding votes, and no `-1` binding votes.
The vote should be open for at least 3 days to allow everyone to participate.

[[explicit-majority-voting]]
=== Explicit majority voting

An explicit majority vote uses `+1` or `-1` to indicate one's position on a topic.

* `+1` indicates you approve
* `-1` indicates you disapprove
* If you have no opinion, you should abstain from voting

The vote succeeds when at least three binding votes are cast, and two-thirds of cast binding values are `+1`.
The vote should be open for at least 3 days to allow everyone to participate.

[[code-of-conduct]]
== Code of Conduct

We are committed to making participation in the Commonhaus Foundation a harassment-free experience for everyone, based on respect and ethical conduct.
For the complete Code of Conduct, see the https://github.com/commonhaus/foundation/blob/main/policies/code-of-conduct.md[Commonhaus Foundation Code of Conduct].
Please ensure you are familiar with its guidelines and expectations, as it's essential for maintaining a positive and collaborative environment.

[[trackmark-policy]]
== Trademark Policy

The Debezium logos, icons, and domain names are protected by trademark rights.
Usage of these trademarks must adhere to our https://www.commonhaus.org/policies/trademark-policy/[Trademark Policy].

[[contributing]]
== Contributing

We welcome all forms of contributors, from code improvements to documentation and design.
For details on how to contribute and the process your contributions will follow, please read our https://github.com/debezium/debezium/blob/main/CONTRIBUTING.md[Contributing Guidelines].