---
layout: release-notes
title: Release Notes for Debezium 3.0
debezium-version: "3.0"
---
:toc:
:toc-placement: macro
:toclevels: 1
:sectanchors:
:linkattrs:
:icons: font

All notable changes for Debezium releases are documented in this file.
Release numbers follow http://semver.org[Semantic Versioning].

toc::[]

[[release-3.0.0-alpha1]]
== *Release 3.0.0.Alpha1* _(July 11st 2024)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12413693[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 3.7.0 and has been tested with version 3.7.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.


=== Upgrading

Before upgrading any connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 3.0.0.Alpha1 from any earlier versions,
first check the migration notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 3.0.0.Alpha1 plugin files, and restart the connector using the same configuration.
Upon restart, the 3.0.0.Alpha1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our container images, then please do not forget to pull them fresh from https://quay.io/organization/debezium[Quay.io].


=== Breaking changes

Debezium connectors now require Java 17 for runtime and Java 21 for building.
Debezium Server, Debezium Operator, and Debezium Outbox extension require Java 21 both for build and runtime (https://issues.redhat.com/browse/DBZ-6795[DBZ-6795]).



=== New features

* Provide MongoDB sink connector https://issues.redhat.com/browse/DBZ-7223[DBZ-7223]
* Extends process of finding Bundle path https://issues.redhat.com/browse/DBZ-7992[DBZ-7992]
* Support FLOAT32 type in debezium-connector-spanner https://issues.redhat.com/browse/DBZ-8043[DBZ-8043]


=== Fixes

* Debezium postgres jdbc sink not handling infinity values https://issues.redhat.com/browse/DBZ-7920[DBZ-7920]
* JdbcSinkTask doesn't clear offsets on stop https://issues.redhat.com/browse/DBZ-7946[DBZ-7946]
* ibmi as400 connector config isn't prefixed with "database." https://issues.redhat.com/browse/DBZ-7955[DBZ-7955]
* Duplicate downstream annotation comments incorrectly refer to Db2 connector https://issues.redhat.com/browse/DBZ-7968[DBZ-7968]
* Issue with Hybrid mode and DDL change https://issues.redhat.com/browse/DBZ-7991[DBZ-7991]
* Incorrect offset/history property mapping generatated  https://issues.redhat.com/browse/DBZ-8007[DBZ-8007]
* Debezium Server Operator on minikube with java.lang.NullPointerException': java.lang.NullPointerException https://issues.redhat.com/browse/DBZ-8019[DBZ-8019]
* ORA-65090: operation only allowed in a container database when connecting to a non-CDB database https://issues.redhat.com/browse/DBZ-8023[DBZ-8023]
* Added type to Prometheus JMX exporter https://issues.redhat.com/browse/DBZ-8036[DBZ-8036]
* Add `kafka.producer` metrics to debezium-server jmx exporter config https://issues.redhat.com/browse/DBZ-8037[DBZ-8037]


=== Other changes

* Use Java 17 as baseline https://issues.redhat.com/browse/DBZ-7224[DBZ-7224]
* Document new MariaDB connector https://issues.redhat.com/browse/DBZ-7786[DBZ-7786]
* Move to Maven 3.9.8 as build requirement https://issues.redhat.com/browse/DBZ-7965[DBZ-7965]
* Add disclaimer that PostProcessors and CustomConverters are Debezium source connectors only https://issues.redhat.com/browse/DBZ-8031[DBZ-8031]
* Typos in Bug report template https://issues.redhat.com/browse/DBZ-8038[DBZ-8038]
* Find an alternative way to manually deploy the connector with local changes that is compatible with Debezium 3 https://issues.redhat.com/browse/DBZ-8046[DBZ-8046]

