= Release Notes for Debezium 0.8
:toc:
:toc-placement: macro
:toclevels: 1
:sectanchors:
:linkattrs:
:icons: font

All notable changes for Debezium releases are documented in this file.
Release numbers follow http://semver.org[Semantic Versioning].

toc::[]

[[release-0-8-3-final]]
== *Release 0.8.3.Final* _(September 19th, 2018)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version0=12339197[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 1.1.0 and has been tested with version 1.1.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.8.3.Final from any of the earlier 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.8.3.Final plugin files, and restart the connector using the same configuration.
Upon restart, the 0.8.3.Final connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.

=== New Features

* Ability to rewrite deleted records https://issues.redhat.com/browse/DBZ-857)[DBZ-857]; note this deprecates the existing "drop.deletes" link:/docs/configuration/event-flattening/#configuration_options[SMT configuration option]; instead set "delete.handling.mode" to "drop";
* use tcpKeepAlive by default https://issues.redhat.com/browse/DBZ-895)[DBZ-895]

=== Fixes

This release includes the following fixes:

* Global read lock not release when exception raised during snapshot https://issues.redhat.com/browse/DBZ-769)[DBZ-769]
* Abort loops in MongoPrimary#execute() if the connector is stopped https://issues.redhat.com/browse/DBZ-784)[DBZ-784]
* GtidModeEnabled method check gtid mode will always be true https://issues.redhat.com/browse/DBZ-820)[DBZ-820]
* Sensitive vars CONNECT_CONSUMER_SASL_JAAS_CONFIG and CONNECT_PRODUCER_SASL_JAAS_CONFIG are printed to the log https://issues.redhat.com/browse/DBZ-861)[DBZ-861]
* A new replication slot waits for all concurrent transactions to finish https://issues.redhat.com/browse/DBZ-862)[DBZ-862]
* Execution of RecordsStreamProducer.closeConnections() is susceptible to race condition https://issues.redhat.com/browse/DBZ-887)[DBZ-887]
* PostgresConnection.initTypeRegistry() takes ~24 mins https://issues.redhat.com/browse/DBZ-899)[DBZ-899]
* java.time.format.DateTimeParseException: Text '1970-01-01 00:00:00' in mysql ALTER https://issues.redhat.com/browse/DBZ-901)[DBZ-901]
* org.antlr.v4.runtime.NoViableAltException on CREATE DEFINER=`web`@`%` PROCEDURE `... https://issues.redhat.com/browse/DBZ-903)[DBZ-903]
* RecordsStreamProducer should report refresh of the schema due to different column count https://issues.redhat.com/browse/DBZ-907)[DBZ-907]
* MongoDbConnector returns obsolete config values during validation https://issues.redhat.com/browse/DBZ-908)[DBZ-908]
* Can't parse create definition on the mysql connector https://issues.redhat.com/browse/DBZ-910)[DBZ-910]


=== Other changes

None


[[release-0-8-2]]
== *Release 0.8.2* _(August 30th, 2018)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12338793[complete list of issues].

Note that by accident the version of the release artifacts is _0.8.2_ instead of _0.8.2.Final_.
This is not in line with our recently established convention of always letting release versions end with qualifiers such as _Alpha1_, _Beta1_, _CR1_ or _Final_.
The next version in the 0.8 line will be _0.8.3.Final_ and we'll improve our release pipeline to make sure that this situation doesn't occur again.

=== Kafka compatibility

This release has been built against Kafka Connect 1.1.0 and has been tested with version 1.1.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.8.2.Final from any of the earlier 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.8.2.Final plugin files, and restart the connector using the same configuration.
Upon restart, the 0.8.2.Final connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.

=== New Features

* Postgres connector - add database, schema and table names to "source" section of records https://issues.redhat.com/browse/DBZ-866[DBZ-866]

=== Fixes

This release includes the following fixes:

* Initial synchronization is not interrupted https://issues.redhat.com/browse/DBZ-838[DBZ-838]
* Schema_only snapshot on idle server - offsets not stored after snapshot https://issues.redhat.com/browse/DBZ-859[DBZ-859]
* DDL parsing in MySQL - default value of primary key is set to null https://issues.redhat.com/browse/DBZ-860[DBZ-860]
* Antlr DDL parser exception for "create database ... CHARSET=..." https://issues.redhat.com/browse/DBZ-864[DBZ-864]
* Missing 0.8.1.Final tags for Zookeper and Kafka https://issues.redhat.com/browse/DBZ-868[DBZ-868]
* AlterTableParserListener does not remove column definition listeners https://issues.redhat.com/browse/DBZ-869[DBZ-869]
* MySQL parser does not recognize 0 as default value for date/time https://issues.redhat.com/browse/DBZ-870[DBZ-870]
* Antlr parser ignores table whitelist filter https://issues.redhat.com/browse/DBZ-872[DBZ-872]
* A new column might not be added with ALTER TABLE antlr parser https://issues.redhat.com/browse/DBZ-877[DBZ-877]
* MySQLConnectorTask always reports it has the required Binlog file from MySQL https://issues.redhat.com/browse/DBZ-880[DBZ-880]


=== Other changes

None

[[release-0-8-1-final]]
== *Release 0.8.1.Final* _(July 25th, 2018)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12338169[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 1.1.0 and has been tested with version 1.1.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.8.1.Final from any of the earlier 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.8.1.Final plugin files, and restart the connector using the same configuration.
Upon restart, the 0.8.1.Final connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.

=== New Features

None


=== Fixes

This release includes the following fixes:

* PostgreSQL LSNs are not committed when receiving events for filtered-out tables https://issues.redhat.com/browse/DBZ-800[DBZ-800]


=== Other changes

This release includes also other changes:

* Extract common TopicSelector contract https://issues.redhat.com/browse/DBZ-627[DBZ-627]
* Remove redundant Docker configuration https://issues.redhat.com/browse/DBZ-796[DBZ-796]


[[release-0-8-0-final]]
== *Release 0.8.0.Final* _(July 11th, 2018)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12338151[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 1.1.0 and has been tested with version 1.1.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.8.0.Final from any of the earlier 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.8.0.CR1 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.8.0.CR1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

The topic naming for Oracle connector has https://issues.redhat.com/browse/DBZ-725[changed] and the database name is no longer part of the name.
The naming convention is thus consistent accross all connectors.

=== New Features

This release includes the following new features:

* Expose more granular snapshot metrics via JMX https://issues.redhat.com/browse/DBZ-789[DBZ-789]


=== Fixes

None


=== Other changes

This release includes also other changes:

* Remove DB name from topic ids https://issues.redhat.com/browse/DBZ-725[DBZ-725]
* Don't use user with DBA permissions for Oracle connector tests https://issues.redhat.com/browse/DBZ-791[DBZ-791]


[[release-0-8-0-cr-1]]
== *Release 0.8.0.CR1* _(July 4th, 2018)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12338150[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 1.1.0 and has been tested with version 1.1.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.8.0.CR1 from any of the earlier 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.8.0.CR1 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.8.0.CR1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.

=== New Features

This release includes the following new features:

* List collections only for databases accepted by database filter https://issues.redhat.com/browse/DBZ-713[DBZ-713]
* Set DECIMAL precision as schema parameter https://issues.redhat.com/browse/DBZ-751[DBZ-751]
* Stop MongoDB connector in case of authorization failure https://issues.redhat.com/browse/DBZ-782[DBZ-782]
* Add the original data type of a column as schema parameter https://issues.redhat.com/browse/DBZ-644[DBZ-644]
* Add support for columns of type CITEXT https://issues.redhat.com/browse/DBZ-762[DBZ-762]


=== Fixes

This release includes the following fixes:

* Allow Empty Database Passwords https://issues.redhat.com/browse/DBZ-743[DBZ-743]
* Antlr parser raising exception for MySQL-valid ALTER TABLE https://issues.redhat.com/browse/DBZ-767[DBZ-767]
* Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff] https://issues.redhat.com/browse/DBZ-768[DBZ-768]
* Antlr parser raising exception when parsing ENUM fields https://issues.redhat.com/browse/DBZ-770[DBZ-770]
* Default value is not removed when changing a column's type https://issues.redhat.com/browse/DBZ-771[DBZ-771]


=== Other changes

This release includes also other changes:

* Add documentation for supported geometry types https://issues.redhat.com/browse/DBZ-573[DBZ-573]
* Benchmark Antlr parser https://issues.redhat.com/browse/DBZ-742[DBZ-742]
* Document rules for "slot.name" property of the Postgres connector https://issues.redhat.com/browse/DBZ-746[DBZ-746]
* Add table-of-contents sections to connector doc pages https://issues.redhat.com/browse/DBZ-752[DBZ-752]
* Guard against simple bugs https://issues.redhat.com/browse/DBZ-759[DBZ-759]
* Reduce test log output https://issues.redhat.com/browse/DBZ-765[DBZ-765]
* Document wal2json plugin streaming mode https://issues.redhat.com/browse/DBZ-772[DBZ-772]
* Extract common base class for relational DatabaseSchema implementations https://issues.redhat.com/browse/DBZ-773[DBZ-773]
* Intermittent failures in ReplicationConnectionIT#shouldCloseConnectionOnInvalidSlotName() https://issues.redhat.com/browse/DBZ-778[DBZ-778]
* Stabilize MongoDB integration test execution https://issues.redhat.com/browse/DBZ-779[DBZ-779]


[[release-0-8-0-beta-1]]
== *Release 0.8.0.Beta1* _(June 21st, 2018)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12337217[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 1.1.0 and has been tested with version 1.1.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.8.0.Beta1 from any of the earlier 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.8.0.Beta1 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.8.0.Beta1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

Topic names for heartbeat messages followed a hard-coded naming schema.
The rules were made more flexible in https://issues.redhat.com/browse/DBZ-668[DBZ-668].

Transaction id (`txId` field of `Envelope`) for PostgreSQL was originally encoded as an 32-bit `integer` type.
The real range is a 64-bit `long` type so this was changed in https://issues.redhat.com/browse/DBZ-673[DBZ-673].

The datatypes without timezone were not correctly offsetted for databases running in non-UTC timezones.
This was fixed in https://issues.redhat.com/browse/DBZ-578[DBZ-587] and https://issues.redhat.com/browse/DBZ-741[DBZ-741].
See link:docs/connectors/mysql/#temporal-values[MySQL] and link:docs/connectors/postgresql/#temporal-values[PostgreSQL] connector documentation for further details.

=== New Features

This release includes the following new features:

* Improve MySQL connector's handling of DML / DDL statements https://issues.redhat.com/browse/DBZ-252[DBZ-252]
* Snapshots fail if launching multiple connectors at once https://issues.redhat.com/browse/DBZ-601[DBZ-601]
* Data-inclusive snapshot without table locks (For RDS/Aurora) https://issues.redhat.com/browse/DBZ-639[DBZ-639]
* Enable ordered snapshotting of data-Mysql Connector https://issues.redhat.com/browse/DBZ-666[DBZ-666]
* Add a topic name configuration for the heartbeat messages https://issues.redhat.com/browse/DBZ-668[DBZ-668]
* Mongo cursor cleanup https://issues.redhat.com/browse/DBZ-672[DBZ-672]
* wal2json on RDS omits initial changes in streaming mode https://issues.redhat.com/browse/DBZ-679[DBZ-679]
* Make PG_CONFIG configurable (postgres-decoderbufs) https://issues.redhat.com/browse/DBZ-686[DBZ-686]
* Rebase Debezium to Kafka 1.1 and Confluent platform 4.1 https://issues.redhat.com/browse/DBZ-687[DBZ-687]
* When MySQL has BINLOG_ROWS_QUERY_LOG_EVENTS enabled, include original SQL query in event. https://issues.redhat.com/browse/DBZ-706[DBZ-706]
* Ingest change data from Oracle databases using XStream https://issues.redhat.com/browse/DBZ-20[DBZ-20]
* Support defaults in MySQL https://issues.redhat.com/browse/DBZ-191[DBZ-191]
* Run test suite against MongoDB 3.6 https://issues.redhat.com/browse/DBZ-529[DBZ-529]
* Provide option to flatten structs in MongoDB unwrapping SMT https://issues.redhat.com/browse/DBZ-561[DBZ-561]
* Allow configuration option for keep alive interval for Mysql binlog reader https://issues.redhat.com/browse/DBZ-670[DBZ-670]
* Add support for databases with encodings other than UTF-8/16/32 https://issues.redhat.com/browse/DBZ-676[DBZ-676]
* Provide option to specify statements to be executed upon connection creation (e.g.  connection wait timeout) https://issues.redhat.com/browse/DBZ-693[DBZ-693]

=== Fixes

This release includes the following fixes:

* Timestamps are not converted to UTC during snapshot https://issues.redhat.com/browse/DBZ-578[DBZ-578]
* wal2json cannot handle transactions bigger than 1Gb https://issues.redhat.com/browse/DBZ-638[DBZ-638]
* SMT - DataException with io.debezium.connector.mongodb.transforms.UnwrapFromMongoDbEnvelope https://issues.redhat.com/browse/DBZ-649[DBZ-649]
* SchemaParseException when using UnwrapFromMongoDbEnvelope SMT with Avro format https://issues.redhat.com/browse/DBZ-650[DBZ-650]
* Upgrade OpenShift intructions to Strimzi 0.2.0 https://issues.redhat.com/browse/DBZ-654[DBZ-654]
* Mysql ddl parser cannot parse scientific format number in exponential notation default values https://issues.redhat.com/browse/DBZ-667[DBZ-667]
* Close Kafka admin client after DB history topic has been created https://issues.redhat.com/browse/DBZ-669[DBZ-669]
* Postgres DateTimeParseException https://issues.redhat.com/browse/DBZ-671[DBZ-671]
* Transaction ID must be handled as long https://issues.redhat.com/browse/DBZ-673[DBZ-673]
* PostgreSQL connector doesn't handle TIME(p) columns correctly with wal2json https://issues.redhat.com/browse/DBZ-681[DBZ-681]
* Error on initial load for records with negative timestamp https://issues.redhat.com/browse/DBZ-694[DBZ-694]
* Postgres Connector inconsistent handling of timestamp precision https://issues.redhat.com/browse/DBZ-696[DBZ-696]
* Debezium is throwing exception when max OID in pg db is larger than max int https://issues.redhat.com/browse/DBZ-697[DBZ-697]
* PostgresReplicationConnection doesn't close jdbc connection https://issues.redhat.com/browse/DBZ-699[DBZ-699]
* Debezium is throwing exception when max typelem in pg db is larger than max int https://issues.redhat.com/browse/DBZ-701[DBZ-701]
* Plaintext jaas configuration passwords logged out https://issues.redhat.com/browse/DBZ-702[DBZ-702]
* Postgres TIME columns are always exported as nano-seconds, unlike documented https://issues.redhat.com/browse/DBZ-709[DBZ-709]
* Incorrect options for PostgreSQL sslmode listed in documentation https://issues.redhat.com/browse/DBZ-711[DBZ-711]
* Mongo Connector - doesn't redo initial sync after connector restart https://issues.redhat.com/browse/DBZ-712[DBZ-712]
* NUMERIC column without scale value causes exception https://issues.redhat.com/browse/DBZ-727[DBZ-727]
* Inconsistency in parameter names for database histy producer/consumer https://issues.redhat.com/browse/DBZ-728[DBZ-728]
* MySQL DATETIME Value Incorrectly Snapshotted https://issues.redhat.com/browse/DBZ-741[DBZ-741]

=== Other changes

This release includes also other changes:

* Support incubator repo in release process https://issues.redhat.com/browse/DBZ-749[DBZ-749]
* Upgrade Postgres Docker images to wal2json 1.0 https://issues.redhat.com/browse/DBZ-750[DBZ-750]
* Provide Maven profile so that the MySQL module test suite can be run using old and new parser https://issues.redhat.com/browse/DBZ-734[DBZ-734]
