= Release Notes for Debezium 1.0
:awestruct-layout: doc
:awestruct-documentation_version: "1.0"
:toc:
:toc-placement: macro
:toclevels: 1
:sectanchors:
:linkattrs:
:icons: font

All notable changes for Debezium releases are documented in this file.
Release numbers follow http://semver.org[Semantic Versioning].

toc::[]

[[release-1.0.0-cr1]]
== *Release 1.0.0.CR1* _(December 10th, 2019)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12343169[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.3.1 and has been tested with version 2.3.1 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 1.0.0.CR1 from any of the earlier 1.0.x, 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 1.0.0.CR1 plugin files, and restart the connector using the same configuration.
Upon restart, the 1.0.0.CR1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

For the SQL Server and Oracle connectors, the snapshot mode `initial_schema_only` has been deprecated and will be removed in a future version. Please use `schema_only` instead (https://issues.redhat.com/browse/DBZ-585[DBZ-585]).


=== New Features

* Transaction level TRANSACTION_READ_COMMITTED not implemented https://issues.jboss.org/browse/DBZ-1480[DBZ-1480]
* Provide change event JSON Serde for Kafka Streams https://issues.jboss.org/browse/DBZ-1533[DBZ-1533]
* Provide MongoDB 4.2 image https://issues.jboss.org/browse/DBZ-1626[DBZ-1626]
* Support PostgreSQL enum types https://issues.jboss.org/browse/DBZ-920[DBZ-920]
* Upgrade container images to Java 11 https://issues.jboss.org/browse/DBZ-969[DBZ-969]
* Support MongoDB 4.0 transaction https://issues.jboss.org/browse/DBZ-1215[DBZ-1215]
* Make connection timeout configurable in MySQL connection URL https://issues.jboss.org/browse/DBZ-1632[DBZ-1632]
* Support for arrays of uuid (_uuid) https://issues.jboss.org/browse/DBZ-1637[DBZ-1637]
* Add test matrix for SQL Server https://issues.jboss.org/browse/DBZ-1644[DBZ-1644]


=== Fixes

This release includes the following fixes:

* Empty history topic treated as not existing https://issues.jboss.org/browse/DBZ-1201[DBZ-1201]
* Incorrect handling of type alias https://issues.jboss.org/browse/DBZ-1413[DBZ-1413]
* Blacklisted columns are not being filtered out when generating a Kafka message from a CDC event https://issues.jboss.org/browse/DBZ-1617[DBZ-1617]
* IoUtil Bugfix https://issues.jboss.org/browse/DBZ-1621[DBZ-1621]
* VariableLatch Bugfix https://issues.jboss.org/browse/DBZ-1622[DBZ-1622]
* The oracle connector scans too many objects while attempting to determine the most recent ddl time https://issues.jboss.org/browse/DBZ-1631[DBZ-1631]
* Connector does not update its state correctly when processing compound ALTER statement https://issues.jboss.org/browse/DBZ-1645[DBZ-1645]
* Outbox event router shouldn't lower-case topic names https://issues.jboss.org/browse/DBZ-1648[DBZ-1648]


=== Other changes

This release includes also other changes:

* Consolidate configuration parameters https://issues.jboss.org/browse/DBZ-585[DBZ-585]
* Merge the code for upscaling decimal values with scale lower than defined https://issues.jboss.org/browse/DBZ-825[DBZ-825]
* Make Debezium project Java 11 compatible https://issues.jboss.org/browse/DBZ-1402[DBZ-1402]
* Run SourceClear https://issues.jboss.org/browse/DBZ-1602[DBZ-1602]
* Extend MySQL to test Enum with column.propagate.source.type https://issues.jboss.org/browse/DBZ-1636[DBZ-1636]
* Sticky ToC hides tables in PG connector docs https://issues.jboss.org/browse/DBZ-1652[DBZ-1652]
* Antora generates build warning  https://issues.jboss.org/browse/DBZ-1654[DBZ-1654]



[[release-1.0.0-beta3]]
== *Release 1.0.0.Beta3* _(November 14th, 2019)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12343094[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.3.1 and has been tested with version 2.3.1 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 1.0.0.Beta3 from any of the earlier 1.0.x, 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 1.0.0.Beta3 plugin files, and restart the connector using the same configuration.
Upon restart, the 1.0.0.Beta3 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

Configuration parameter `drop_on_stop` of PostgreSQL connector has been renamed to `drop.on.stop` (https://issues.redhat.com/browse/DBZ-1595[DBZ-1595]) to make it consistent with other parameter names.


=== New Features

* Standardize source info for Cassandra connector https://issues.redhat.com/browse/DBZ-1408[DBZ-1408]
* Clarify presence of old values when not using REPLICA IDENTITY FULL https://issues.redhat.com/browse/DBZ-1518[DBZ-1518]
* Propagate replicator exception so failure reason is available from Connect https://issues.redhat.com/browse/DBZ-1583[DBZ-1583]
* Envelope methods should accept Instant instead of long for "ts" parameter https://issues.redhat.com/browse/DBZ-1607[DBZ-1607]


=== Fixes

This release includes the following fixes:

* Debezium Erroneously Reporting No Tables to Capture https://issues.redhat.com/browse/DBZ-1519[DBZ-1519]
* Debezium Oracle connector attempting to analyze tables https://issues.redhat.com/browse/DBZ-1569[DBZ-1569]
* Null values in "before" are populated with "__debezium_unavailable_value" https://issues.redhat.com/browse/DBZ-1570[DBZ-1570]
* Postgresql 11+ pgoutput plugin error with truncate https://issues.redhat.com/browse/DBZ-1576[DBZ-1576]
* Regression of postgres Connector times out in schema discovery for DBs with many tables https://issues.redhat.com/browse/DBZ-1579[DBZ-1579]
* The ts_ms value is not correct during the snapshot processing https://issues.redhat.com/browse/DBZ-1588[DBZ-1588]
* LogInterceptor is not thread-safe https://issues.redhat.com/browse/DBZ-1590[DBZ-1590]
* Heartbeats are not generated for non-whitelisted tables https://issues.redhat.com/browse/DBZ-1592[DBZ-1592]
* Config `tombstones.on.delete` is missing from SQL Server Connector configDef https://issues.redhat.com/browse/DBZ-1593[DBZ-1593]
* AWS RDS Performance Insights screwed a little by non-closed statement in "SELECT COUNT(1) FROM pg_publication" https://issues.redhat.com/browse/DBZ-1596[DBZ-1596]
* Update Postgres documentation to use ts_ms instead of ts_usec https://issues.redhat.com/browse/DBZ-1610[DBZ-1610]
* Exception while trying snapshot schema of non-whitelisted table https://issues.redhat.com/browse/DBZ-1613[DBZ-1613]


=== Other changes

This release includes also other changes:

* Auto-format source code upon build https://issues.redhat.com/browse/DBZ-1392[DBZ-1392]
* Update documentation based on Technology Preview https://issues.redhat.com/browse/DBZ-1543[DBZ-1543]
* Reduce size of Postgres container images https://issues.redhat.com/browse/DBZ-1549[DBZ-1549]
* Debezium should not use SHARE UPDATE EXCLUSIVE MODE locks https://issues.redhat.com/browse/DBZ-1559[DBZ-1559]
* Allows tags to be passed to CI jobs https://issues.redhat.com/browse/DBZ-1578[DBZ-1578]
* Upgrade MongoDB driver to 3.11 https://issues.redhat.com/browse/DBZ-1597[DBZ-1597]
* Run formatter validation in Travis CI https://issues.redhat.com/browse/DBZ-1603[DBZ-1603]
* Place formatting rules into Maven module https://issues.redhat.com/browse/DBZ-1605[DBZ-1605]
* Upgrade to Kafka 2.3.1 https://issues.redhat.com/browse/DBZ-1612[DBZ-1612]
* Allow per-connector setting for schema/catalog precedence in TableId use https://issues.redhat.com/browse/DBZ-1555[DBZ-1555]



[[release-1.0.0-beta2]]
== *Release 1.0.0.Beta2* _(October 24th, 2019)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12343067[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.3.0 and has been tested with version 2.3.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 1.0.0.Beta2 from any of the earlier 1.0.x, 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 1.0.0.Beta2 plugin files, and restart the connector using the same configuration.
Upon restart, the 1.0.0.Beta2 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.


=== New Features

* Update tooling image to use latest kafkacat https://issues.redhat.com/browse/DBZ-1522[DBZ-1522]
* Validate configured replication slot names https://issues.redhat.com/browse/DBZ-1525[DBZ-1525]
* Make password field to be hidden for MS SQL connector https://issues.redhat.com/browse/DBZ-1554[DBZ-1554]
* Raise a warning about growing backlog https://issues.redhat.com/browse/DBZ-1565[DBZ-1565]
* Support Postgres LTREE columns https://issues.redhat.com/browse/DBZ-1336[DBZ-1336]


=== Fixes

This release includes the following fixes:

* Aborting snapshot due to error when last running 'UNLOCK TABLES': Only REPEATABLE READ isolation level is supported for START TRANSACTION WITH CONSISTENT SNAPSHOT in RocksDB Storage Engine. https://issues.redhat.com/browse/DBZ-1428[DBZ-1428]
* MySQL Connector fails to parse DDL containing the keyword VISIBLE for index definitions https://issues.redhat.com/browse/DBZ-1534[DBZ-1534]
* MySQL connector fails to parse DDL - GRANT SESSION_VARIABLES_ADMIN... https://issues.redhat.com/browse/DBZ-1535[DBZ-1535]
* Mysql connector: The primary key cannot reference a non-existant column 'id' in table '***' https://issues.redhat.com/browse/DBZ-1560[DBZ-1560]
* Incorrect source struct's collection field when dot is present in collection name https://issues.redhat.com/browse/DBZ-1563[DBZ-1563]
* Transaction left open after db snapshot https://issues.redhat.com/browse/DBZ-1564[DBZ-1564]


=== Other changes

This release includes also other changes:

* Add Postgres 12 to testing matrix https://issues.redhat.com/browse/DBZ-1542[DBZ-1542]
* Update Katacoda learning experience https://issues.redhat.com/browse/DBZ-1548[DBZ-1548]



[[release-1.0.0-beta1]]
== *Release 1.0.0.Beta1* _(October 17th, 2019)_

See the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12317320&version=12341896[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.3.0 and has been tested with version 2.3.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 1.0.0.Beta1 from any of the earlier 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 1.0.0.Beta1 plugin files, and restart the connector using the same configuration.
Upon restart, the 1.0.0.Beta1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

The ExtractNewDocumentState and EventRouter SMTs now propagate any heartbeat or schema change messages unchanged instead of dropping them as before. This is to ensure consistency with the ExtractNewRecordState SMT (https://issues.redhat.com/browse/DBZ-1513[DBZ-1513]).

The new Postgres connector option `interval.handling.mode` allows to control whether `INTERVAL` columns should be exported as microseconds (previous behavior, remains the default) or as ISO 8601 formatted string (https://issues.redhat.com/browse/DBZ-1498[DBZ-1498]). The following upgrade order must be maintained when existing connectors capture `INTERVAL` columns:

1. Upgrade the Debezium Kafka Connect Postgres connector
2. Upgrade the logical decoding plug-in installed in the database
3. (Optionally) switch `interval.handling.mode` to string

In particular it should be avoided to upgrade the logical decoding plug-in before the connector, as this will cause no value to be exported for `INTERVAL` columns.


=== New Features

* Provide alternative mapping for INTERVAL https://issues.redhat.com/browse/DBZ-1498[DBZ-1498]
* Ensure message keys have correct field order https://issues.redhat.com/browse/DBZ-1507[DBZ-1507]
* Image incorrect on Deploying Debezium on OpenShift https://issues.redhat.com/browse/DBZ-1545[DBZ-1545]
* Indicate table locking issues in log https://issues.redhat.com/browse/DBZ-1280[DBZ-1280]


=== Fixes

This release includes the following fixes:

* Debezium fails to snapshot large databases https://issues.redhat.com/browse/DBZ-685[DBZ-685]
* Connector Postgres runs out of disk space https://issues.redhat.com/browse/DBZ-892[DBZ-892]
* Debezium-MySQL Connector Fails while parsing AWS RDS internal events https://issues.redhat.com/browse/DBZ-1492[DBZ-1492]
* MongoDB ExtractNewDocumentState SMT blocks heartbeat messages https://issues.redhat.com/browse/DBZ-1513[DBZ-1513]
* pgoutput string decoding depends on JVM default charset https://issues.redhat.com/browse/DBZ-1532[DBZ-1532]
* Whitespaces not stripped from table.whitelist https://issues.redhat.com/browse/DBZ-1546[DBZ-1546]


=== Other changes

This release includes also other changes:

* Upgrade to latest JBoss Parent POM https://issues.redhat.com/browse/DBZ-675[DBZ-675]
* CheckStyle: Flag missing whitespace https://issues.redhat.com/browse/DBZ-1341[DBZ-1341]
* Upgrade to the latest Checkstyle plugin https://issues.redhat.com/browse/DBZ-1355[DBZ-1355]
* CheckStyle: no code after closing braces https://issues.redhat.com/browse/DBZ-1391[DBZ-1391]
* Add "adopters" file https://issues.redhat.com/browse/DBZ-1460[DBZ-1460]
* Add Google Analytics to Antora-published pages https://issues.redhat.com/browse/DBZ-1526[DBZ-1526]
* Create 0.10 RPM for postgres-decoderbufs https://issues.redhat.com/browse/DBZ-1540[DBZ-1540]
* Postgres documentation fixes https://issues.redhat.com/browse/DBZ-1544[DBZ-1544]
