= Release Notes for Debezium 1.0
:awestruct-layout: doc
:awestruct-documentation_version: "1.0"
:toc:
:toc-placement: macro
:toclevels: 1
:sectanchors:
:linkattrs:
:icons: font

All notable changes for Debezium releases are documented in this file.
Release numbers follow http://semver.org[Semantic Versioning].

toc::[]

[[release-1.0.0-beta1]]
== *Release 1.0.0.Beta1* _(October 17th, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12341896[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.3.0 and has been tested with version 2.3.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 1.0.0.Beta1 from any of the earlier 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 1.0.0.Beta1 plugin files, and restart the connector using the same configuration.
Upon restart, the 1.0.0.Beta1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

The ExtractNewDocumentState and EventRouter SMTs now propagate any heartbeat or schema change messages unchanged instead of dropping them as before. This is to ensure consistency with the ExtractNewRecordState SMT (https://issues.jboss.org/browse/DBZ-1513[DBZ-1513]).

The new Postgres connector option `interval.handling.mode` allows to control whether `INTERVAL` columns should be exported as microseconds (previous behavior, remains the default) or as ISO 8601 formatted string (https://issues.jboss.org/browse/DBZ-1498[DBZ-1498]). The following upgrade order must be maintained when existing connectors capture `INTERVAL` columns:

1. Upgrade the Debezium Kafka Connect Postgres connector
2. Upgrade the logical decoding plug-in installed in the database
3. (Optionally) switch `interval.handling.mode` to string

In particular it should be avoided to upgrade the logical decoding plug-in before the connector, as this will cause no value to be exported for `INTERVAL` columns.


=== New Features

* Provide alternative mapping for INTERVAL https://issues.jboss.org/browse/DBZ-1498[DBZ-1498]
* Ensure message keys have correct field order https://issues.jboss.org/browse/DBZ-1507[DBZ-1507]
* Image incorrect on Deploying Debezium on OpenShift https://issues.jboss.org/browse/DBZ-1545[DBZ-1545]
* Indicate table locking issues in log https://issues.jboss.org/browse/DBZ-1280[DBZ-1280]


=== Fixes

This release includes the following fixes:

* Debezium fails to snapshot large databases https://issues.jboss.org/browse/DBZ-685[DBZ-685]
* Connector Postgres runs out of disk space https://issues.jboss.org/browse/DBZ-892[DBZ-892]
* Debezium-MySQL Connector Fails while parsing AWS RDS internal events https://issues.jboss.org/browse/DBZ-1492[DBZ-1492]
* MongoDB ExtractNewDocumentState SMT blocks heartbeat messages https://issues.jboss.org/browse/DBZ-1513[DBZ-1513]
* pgoutput string decoding depends on JVM default charset https://issues.jboss.org/browse/DBZ-1532[DBZ-1532]
* Whitespaces not stripped from table.whitelist https://issues.jboss.org/browse/DBZ-1546[DBZ-1546]


=== Other changes

This release includes also other changes:

* Upgrade to latest JBoss Parent POM https://issues.jboss.org/browse/DBZ-675[DBZ-675]
* CheckStyle: Flag missing whitespace https://issues.jboss.org/browse/DBZ-1341[DBZ-1341]
* Upgrade to the latest Checkstyle plugin https://issues.jboss.org/browse/DBZ-1355[DBZ-1355]
* CheckStyle: no code after closing braces https://issues.jboss.org/browse/DBZ-1391[DBZ-1391]
* Add "adopters" file https://issues.jboss.org/browse/DBZ-1460[DBZ-1460]
* Add Google Analytics to Antora-published pages https://issues.jboss.org/browse/DBZ-1526[DBZ-1526]
* Create 0.10 RPM for postgres-decoderbufs https://issues.jboss.org/browse/DBZ-1540[DBZ-1540]
* Postgres documentation fixes https://issues.jboss.org/browse/DBZ-1544[DBZ-1544]
