= Debezium Documentation
:awestruct-layout: doc
:linkattrs:
:icons: font

[[gs-overview]]
== Overview

As developer interest moves to creating rich applications for mobile handsets, tablets, or any device using HTML5
and Javascript, the need for server-side code is significantly reduced.

LiveOak is all about making it easier to develop mobile client applications by providing ready made, easy to consume cloud
services that most mobile applications today require.

Our goal is to enable you, a mobile application developer, to focus on developing an amazing mobile application quickly.
To that end, we provide a "point and click" interface for specifying the services you need for your mobile application.

To enable quicker development of applications that are almost 100% client-side, LiveOak provides both the typically-needed
services like data persistence out of the box, along with a platform and API for providing your own custom services. Additional
services may be created and deployed by 3rd-party service-providers, or as little blobs of custom server-side code explicitly in
support of a specific application.

LiveOak can be deployed locally on a developer machine, or in the cloud - either to OpenShift Online or as a Docker container.


As developer interest moves to creating rich applications for mobile handsets, tablets, or any device using HTML5
and Javascript, the need for server-side code is significantly reduced.

LiveOak is all about making it easier to develop mobile client applications by providing ready made, easy to consume cloud
services that most mobile applications today require.

Our goal is to enable you, a mobile application developer, to focus on developing an amazing mobile application quickly.
To that end, we provide a "point and click" interface for specifying the services you need for your mobile application.

To enable quicker development of applications that are almost 100% client-side, LiveOak provides both the typically-needed
services like data persistence out of the box, along with a platform and API for providing your own custom services. Additional
services may be created and deployed by 3rd-party service-providers, or as little blobs of custom server-side code explicitly in
support of a specific application.

LiveOak can be deployed locally on a developer machine, or in the cloud - either to OpenShift Online or as a Docker container.


As developer interest moves to creating rich applications for mobile handsets, tablets, or any device using HTML5
and Javascript, the need for server-side code is significantly reduced.

LiveOak is all about making it easier to develop mobile client applications by providing ready made, easy to consume cloud
services that most mobile applications today require.

Our goal is to enable you, a mobile application developer, to focus on developing an amazing mobile application quickly.
To that end, we provide a "point and click" interface for specifying the services you need for your mobile application.

To enable quicker development of applications that are almost 100% client-side, LiveOak provides both the typically-needed
services like data persistence out of the box, along with a platform and API for providing your own custom services. Additional
services may be created and deployed by 3rd-party service-providers, or as little blobs of custom server-side code explicitly in
support of a specific application.

LiveOak can be deployed locally on a developer machine, or in the cloud - either to OpenShift Online or as a Docker container.


