= Debezium Change Log
:awestruct-layout: doc
:linkattrs:
:icons: font

All notable changes for Debezium releases are documented in this file.
Release numbers follow http://semver.org[Semantic Versioning].



[[release-0-10-0-beta4]]
== *Release 0.10.0.Beta4* _(August 16th, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12342545[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.3.0 and has been tested with version 2.3.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.10.0.Beta4 from any of the earlier 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.10.0.Beta4 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.10.0.Beta4 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

The default format of the message values produced by the link:/docs/configuration/outbox-event-router/[outbox event router] has been https://issues.jboss.org/browse/DBZ-1385[changed].
It will solely contain the value of the `payload` column by default.
In order to add the `eventType` value that previously was part of the message value, use the "additional field" configuration option with a placement option of `envelope`.
In this case, the message value will be a complex structure containing the `payload` key and one additional key for each further field.

=== New Features

* Implement a CDC connector for Apache Cassandra https://issues.jboss.org/browse/DBZ-607[DBZ-607]
* Support "Exported Snapshots" feature for taking lockless snapshots with Postgres https://issues.jboss.org/browse/DBZ-1035[DBZ-1035]
* Snapshot Order of tables https://issues.jboss.org/browse/DBZ-1254[DBZ-1254]
* Add ability to insert fields from source struct in ExtractNewRecordState SMT https://issues.jboss.org/browse/DBZ-1395[DBZ-1395]


=== Fixes

This release includes the following fixes:

* Debezium for MySQL fails on GRANT DELETE ON <table> https://issues.jboss.org/browse/DBZ-1411[DBZ-1411]
* Debezium for MySQL tries to flush a table for a database not in the database whitelist https://issues.jboss.org/browse/DBZ-1414[DBZ-1414]
* Table scan is performed anyway even if snapshot.mode is set to initial_schema_only https://issues.jboss.org/browse/DBZ-1417[DBZ-1417]
* SMT ExtractNewDocumentState does not support Heartbeat events https://issues.jboss.org/browse/DBZ-1430[DBZ-1430]
* Postgres connector does not honor `publication.name` configuration https://issues.jboss.org/browse/DBZ-1436[DBZ-1436]


=== Other changes

This release includes also other changes:

* Issue with debezium embedded documentation https://issues.jboss.org/browse/DBZ-393[DBZ-393]
* Refactor Postgres connector to be based on new framework classes https://issues.jboss.org/browse/DBZ-777[DBZ-777]
* Don't obtain new connection each time when getting xmin position https://issues.jboss.org/browse/DBZ-1381[DBZ-1381]
* Unify handling of attributes in EventRouter SMT https://issues.jboss.org/browse/DBZ-1385[DBZ-1385]
* DockerHub: show container specific README files https://issues.jboss.org/browse/DBZ-1387[DBZ-1387]
* Remove unused dependencies from Cassandra connector https://issues.jboss.org/browse/DBZ-1424[DBZ-1424]
* Simplify custom engine name parsing grammar https://issues.jboss.org/browse/DBZ-1432[DBZ-1432]



[[release-0-10-0-beta3]]
== *Release 0.10.0.Beta3* _(July 23rd, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12342463[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.3.0 and has been tested with version 2.3.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.10.0.Beta3 from any of the earlier 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.10.0.Beta3 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.10.0.Beta3 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

The value of heartbeat messages has been https://issues.jboss.org/browse/DBZ-1363[changed], it now contains a field with the timestamp of the heartbeat.
Note that the message format of heartbeat messages is considered an implementation detail of Debezium, i.e. its format may be altered incompatibly and consumers should not rely on any specific format.

=== New Features

* Handle tables without primary keys https://issues.jboss.org/browse/DBZ-916[DBZ-916]
* Define exposed connector metrics in MySQL https://issues.jboss.org/browse/DBZ-1120[DBZ-1120]
* Set heartbeat interval for the binlog reader https://issues.jboss.org/browse/DBZ-1338[DBZ-1338]
* Outbox router should skip heartbeat messages by default https://issues.jboss.org/browse/DBZ-1388[DBZ-1388]
* Introduce number ofEventsInError metric https://issues.jboss.org/browse/DBZ-1222[DBZ-1222]
* Add option to skip table locks when snapshotting https://issues.jboss.org/browse/DBZ-1238[DBZ-1238]
* Explore built-in logical decoding added in Postgres 10 https://issues.jboss.org/browse/DBZ-766[DBZ-766]
* Support deletion events in the outbox routing SMT https://issues.jboss.org/browse/DBZ-1320[DBZ-1320]
* Expose metric for progress of DB history recovery https://issues.jboss.org/browse/DBZ-1356[DBZ-1356]


=== Fixes

This release includes the following fixes:

* Incorrect offset may be committed despite unparseable DDL statements https://issues.jboss.org/browse/DBZ-599[DBZ-599]
* SavePoints are getting stored in history topic https://issues.jboss.org/browse/DBZ-794[DBZ-794]
* delete message "op:d" on tables with unique combination of 2 primary keys  = (composite keys) ,  the d records are not sent  https://issues.jboss.org/browse/DBZ-1180[DBZ-1180]
* When a MongoDB collection haven't had activity for a period of time an initial sync is triggered https://issues.jboss.org/browse/DBZ-1198[DBZ-1198]
* Restore compatibility with Kafka 1.x https://issues.jboss.org/browse/DBZ-1361[DBZ-1361]
* no viable alternative at input 'LOCK DEFAULT' https://issues.jboss.org/browse/DBZ-1376[DBZ-1376]
* NullPointer Exception on getReplicationSlotInfo for Postgres https://issues.jboss.org/browse/DBZ-1380[DBZ-1380]
* CHARSET is not supported for CAST function https://issues.jboss.org/browse/DBZ-1397[DBZ-1397]
* Aria engine is not known by Debezium parser https://issues.jboss.org/browse/DBZ-1398[DBZ-1398]
* Debezium does not get the first change after creating the replication slot in PostgreSQL https://issues.jboss.org/browse/DBZ-1400[DBZ-1400]
* Built-in database filter throws NPE https://issues.jboss.org/browse/DBZ-1409[DBZ-1409]
* Error processing RDS heartbeats https://issues.jboss.org/browse/DBZ-1410[DBZ-1410]
* PostgreSQL Connector generates false alarm for empty password https://issues.jboss.org/browse/DBZ-1379[DBZ-1379]


=== Other changes

This release includes also other changes:

* Developer Preview Documentation https://issues.jboss.org/browse/DBZ-1284[DBZ-1284]
* Upgrade to Apache Kafka 2.3 https://issues.jboss.org/browse/DBZ-1358[DBZ-1358]
* Stabilize test executions on CI https://issues.jboss.org/browse/DBZ-1362[DBZ-1362]
* Handling tombstone emission option consistently https://issues.jboss.org/browse/DBZ-1365[DBZ-1365]
* Avoid creating unnecessary type metadata instances; only init once per column. https://issues.jboss.org/browse/DBZ-1366[DBZ-1366]
* Fix tests to run more reliably on Amazon RDS https://issues.jboss.org/browse/DBZ-1371[DBZ-1371]



[[release-0-10-0-beta2]]
== *Release 0.10.0.Beta2* _(June 27th, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12342231[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.3.0 and has been tested with version 2.3.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.10.0.Beta2 from any of the earlier 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.10.0.Beta2 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.10.0.Beta2 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.


=== New Features

* Protect against invalid configuration https://issues.jboss.org/browse/DBZ-1340[DBZ-1340]
* Make emission of tombstone events configurable https://issues.jboss.org/browse/DBZ-835[DBZ-835]
* Support HSTORE array types https://issues.jboss.org/browse/DBZ-1337[DBZ-1337]


=== Fixes

This release includes the following fixes:

* Events for TRUNCATE TABLE not being emitted https://issues.jboss.org/browse/DBZ-708[DBZ-708]
* Connector consumes huge amount of memory https://issues.jboss.org/browse/DBZ-1065[DBZ-1065]
* Exception when starting the connector on Kafka Broker 0.10.1.0 https://issues.jboss.org/browse/DBZ-1270[DBZ-1270]
* Raise warning when renaming table causes  it to be captured or not captured any longer https://issues.jboss.org/browse/DBZ-1278[DBZ-1278]
* no viable alternative at input 'ALTER TABLE `documents` RENAME INDEX' https://issues.jboss.org/browse/DBZ-1329[DBZ-1329]
* MySQL DDL parser - issue with triggers and NEW https://issues.jboss.org/browse/DBZ-1331[DBZ-1331]
* MySQL DDL parser - issue with COLLATE in functions https://issues.jboss.org/browse/DBZ-1332[DBZ-1332]
* Setting "include.unknown.datatypes" to true works for streaming but not during snapshot https://issues.jboss.org/browse/DBZ-1335[DBZ-1335]
* PostgreSQL db with materialized view failing during snapshot https://issues.jboss.org/browse/DBZ-1345[DBZ-1345]
* Switch RecordsStreamProducer to use non-blocking stream call https://issues.jboss.org/browse/DBZ-1347[DBZ-1347]
* Can't parse create definition on the mysql connector https://issues.jboss.org/browse/DBZ-1348[DBZ-1348]
* String literal should support utf8mb3 charset https://issues.jboss.org/browse/DBZ-1349[DBZ-1349]
* NO_AUTO_CREATE_USER sql mode is not supported in MySQL 8 https://issues.jboss.org/browse/DBZ-1350[DBZ-1350]
* Incorrect assert for invalid timestamp check in MySQL 8 https://issues.jboss.org/browse/DBZ-1353[DBZ-1353]


=== Other changes

This release includes also other changes:

* Add to FAQ what to do on offset flush timeout https://issues.jboss.org/browse/DBZ-799[DBZ-799]
* Update MongoDB driver to 3.10.1 https://issues.jboss.org/browse/DBZ-1333[DBZ-1333]
* Fix test for partitioned table snapshot https://issues.jboss.org/browse/DBZ-1342[DBZ-1342]
* Enable PostGIS for Alpine 9.6 https://issues.jboss.org/browse/DBZ-1351[DBZ-1351]
* Fix description for state of Snapshot https://issues.jboss.org/browse/DBZ-1346[DBZ-1346]
* Remove unused code for alternative topic selection strategy https://issues.jboss.org/browse/DBZ-1352[DBZ-1352]


[[release-0-10-0-beta1]]
== *Release 0.10.0.Beta1* _(June 11th, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12342194[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.2.1 and has been tested with version 2.2.1 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.10.0.Beta1 from any of the earlier 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.10.0.Beta1 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.10.0.Beta1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.


=== New Features

* Issue a warning for filters not matching any table/database https://issues.jboss.org/browse/DBZ-1242[DBZ-1242]


=== Fixes

This release includes the following fixes:

* Multiple cdc entries with exactly the same commitLsn and changeLsn https://issues.jboss.org/browse/DBZ-1152[DBZ-1152]
* PostGIS does not work in Alpine images https://issues.jboss.org/browse/DBZ-1307[DBZ-1307]
* Processing MongoDB document contains UNDEFINED type causes exception with MongoDB Unwrap SMT https://issues.jboss.org/browse/DBZ-1315[DBZ-1315]
* Partial zero date datetime/timestamp will fail snapshot https://issues.jboss.org/browse/DBZ-1318[DBZ-1318]
* Default value set null when modify a column from nullable to not null https://issues.jboss.org/browse/DBZ-1321[DBZ-1321]
* Out-of-order chunks don't initiate commitTime https://issues.jboss.org/browse/DBZ-1323[DBZ-1323]
* NullPointerException when receiving noop event https://issues.jboss.org/browse/DBZ-1317[DBZ-1317]


=== Other changes

This release includes also other changes:

* Describe structure of SQL Server CDC events https://issues.jboss.org/browse/DBZ-1296[DBZ-1296]
* Upgrade to Apache Kafka 2.2.1 https://issues.jboss.org/browse/DBZ-1316[DBZ-1316]


[[release-0-10-0-alpha2]]
== *Release 0.10.0.Alpha2* _(June 3rd, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12342158[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.2.0 and has been tested with version 2.2.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.10.0.Alpha2 from any of the earlier 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.10.0.Alpha2 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.10.0.Alpha2 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

The snapshot marking has been overhauled https://issues.jboss.org/browse/DBZ-1295[DBZ-1295].
Originally the snapshot marker has been field with boolean value indicating whther the record was obtained via snapshot or not.
Now it has been turned into three state string enumeration indicating the record came from snapshot (true), is last in the snapshot (last) or is from streaming (false).

=== New Features

* "source" block for MySQL schema change events should contain db and table names https://issues.jboss.org/browse/DBZ-871[DBZ-871]
* Adhere to Dockerfile good practices https://issues.jboss.org/browse/DBZ-1279[DBZ-1279]


=== Fixes

This release includes the following fixes:

* DDL that contains `user` are unparsable by antlr https://issues.jboss.org/browse/DBZ-1300[DBZ-1300]
* Only validate history topic name for affected connectors https://issues.jboss.org/browse/DBZ-1283[DBZ-1283]


=== Other changes

This release includes also other changes:

* Replace Predicate<Column> with ColumnNameFilter https://issues.jboss.org/browse/DBZ-1092[DBZ-1092]
* Upgrade ZooKeeper to 3.4.14 https://issues.jboss.org/browse/DBZ-1298[DBZ-1298]
* Upgrade Docker tooling image https://issues.jboss.org/browse/DBZ-1301[DBZ-1301]
* Upgrade Debezium Postgres Example image to 11 https://issues.jboss.org/browse/DBZ-1302[DBZ-1302]
* Create profile to build assemblies without drivers https://issues.jboss.org/browse/DBZ-1303[DBZ-1303]
* Modify release pipeline to use new Dockerfiles https://issues.jboss.org/browse/DBZ-1304[DBZ-1304]
* Add 3rd party licences https://issues.jboss.org/browse/DBZ-1306[DBZ-1306]
* Remove unused methods from ReplicationStream https://issues.jboss.org/browse/DBZ-1310[DBZ-1310]


[[release-0-10-0-alpha1]]
== *Release 0.10.0.Alpha1* _(May 28th, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12340285[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.2.0 and has been tested with version 2.2.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.10.0.Alpha1 from any of the earlier 0.10.x, 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.10.0.Alpha1 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.10.0.Alpha1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

All connectors now share the common source info block fields https://issues.jboss.org/browse/DBZ-596[DBZ-596].
This led to the renaming and/or change of content of some of the source fields.
We are providing an option `source.struct.version=v1` to use legacy source info block.

Unwrap SMTs have been renamed https://issues.jboss.org/browse/DBZ-677[DBZ-677] to better express their use.

MySQL connector now consistently handle `database.history.store.only.monitored.tables.ddl` for both snapshot and streaming mode https://issues.jboss.org/browse/DBZ-683[DBZ-683].
This leads to changes in the contents of database history topic.

MySQL legacy DDL parser has been removed https://issues.jboss.org/browse/DBZ-736[DBZ-736] and was fully replaced with ANTLR-based parser.

Oracle and SQL Server connectors now contain database, schema, and table names in the source info block https://issues.jboss.org/browse/DBZ-875[DBZ-875].

MongoDB now contains both database and collection name in source info block https://issues.jboss.org/browse/DBZ-1175[DBZ-1175].
The original `ns` field has been dropped.

Metric `NumberOfEventsSkipped` is now available only for MySQL connector https://issues.jboss.org/browse/DBZ-1209[DBZ-1209].

All deprecated features and configuration options https://issues.jboss.org/browse/DBZ-1234[DBZ-1234] have been removed from the codebase and are no longer available.

Outbox routing SMT option names have been renamed to follow a consistent naming schema https://issues.jboss.org/browse/DBZ-1289[DBZ-1289].


=== New Features

* Excessive warnings in log about column missing charset https://issues.jboss.org/browse/DBZ-844[DBZ-844]
* Update JDBC (and Mongo) drivers to latest versions https://issues.jboss.org/browse/DBZ-1273[DBZ-1273]
* Support snapshot SELECT overrides for SQL Server connector https://issues.jboss.org/browse/DBZ-1224[DBZ-1224]
* Generate warning in logs if change table list is empty https://issues.jboss.org/browse/DBZ-1281[DBZ-1281]


=== Fixes

This release includes the following fixes:

* MySQL connection with client authentication does not work https://issues.jboss.org/browse/DBZ-1228[DBZ-1228]
* Unhandled exception prevents snapshot.mode : when_needed functioning https://issues.jboss.org/browse/DBZ-1244[DBZ-1244]
* MySQL connector stops working with a NullPointerException error https://issues.jboss.org/browse/DBZ-1246[DBZ-1246]
* CREATE INDEX can fail for non-monitored tables after connector restart https://issues.jboss.org/browse/DBZ-1264[DBZ-1264]
* Create a spec file for RPM for postgres protobuf plugin https://issues.jboss.org/browse/DBZ-1272[DBZ-1272]
* Last transaction events get duplicated on EmbeddedEngine MySQL connector restart https://issues.jboss.org/browse/DBZ-1276[DBZ-1276]


=== Other changes

This release includes also other changes:

* Misleading description for column.mask.with.length.chars parameter https://issues.jboss.org/browse/DBZ-1290[DBZ-1290]
* Clean up integration tests under integration-tests https://issues.jboss.org/browse/DBZ-263[DBZ-263]
* Consolidate DDL parser tests https://issues.jboss.org/browse/DBZ-733[DBZ-733]
* Document "database.ssl.mode" option https://issues.jboss.org/browse/DBZ-985[DBZ-985]
* Synchronize MySQL grammar with upstream grammar https://issues.jboss.org/browse/DBZ-1127[DBZ-1127]
* Add FAQ entry about -XX:+UseStringDeduplication JVM flag https://issues.jboss.org/browse/DBZ-1139[DBZ-1139]
* Test and handle time 24:00:00 supported by PostgreSQL https://issues.jboss.org/browse/DBZ-1164[DBZ-1164]
* Define final record format for MySQL, Postgres, SQL Server and MongoDB https://issues.jboss.org/browse/DBZ-1235[DBZ-1235]
* Improve error reporting in case of misaligned schema and data https://issues.jboss.org/browse/DBZ-1257[DBZ-1257]
* Adding missing contributors to COPYRIGHT.txt https://issues.jboss.org/browse/DBZ-1259[DBZ-1259]
* Automate contributor check during release pipeline. https://issues.jboss.org/browse/DBZ-1282[DBZ-1282]


[[release-0-9-5-final]]
== *Release 0.9.5.Final* _(May 2nd, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12341657[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.2.0 and has been tested with version 2.2.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.9.5.Final from any of the earlier 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.9.5.Final plugin files, and restart the connector using the same configuration.
Upon restart, the 0.9.5.Final connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.


=== New Features

* Upgrade to Kafka 2.2.0 https://issues.jboss.org/browse/DBZ-1227[DBZ-1227]
* Ability to specify batch size during snapshot https://issues.jboss.org/browse/DBZ-1247[DBZ-1247]
* Postgresql ARRAY support https://issues.jboss.org/browse/DBZ-1076[DBZ-1076]
* Add support macaddr and macaddr8 PostgreSQL column types https://issues.jboss.org/browse/DBZ-1193[DBZ-1193]


=== Fixes

This release includes the following fixes:

* Failing to specify value for database.server.name results in invalid Kafka topic name https://issues.jboss.org/browse/DBZ-212[DBZ-212]
* Escape sequence handling needs to be unified https://issues.jboss.org/browse/DBZ-481[DBZ-481]
* Postgres Connector times out in schema discovery for DBs with many tables https://issues.jboss.org/browse/DBZ-1214[DBZ-1214]
* Oracle connector: JDBC transaction can only capture single DML record  https://issues.jboss.org/browse/DBZ-1223[DBZ-1223]
* Enable enumeration options to contain escaped characters or commas. https://issues.jboss.org/browse/DBZ-1226[DBZ-1226]
* Antlr parser fails on column named with MODE keyword https://issues.jboss.org/browse/DBZ-1233[DBZ-1233]
* Lost precision for timestamp with timezone https://issues.jboss.org/browse/DBZ-1236[DBZ-1236]
* NullpointerException due to optional value for commitTime https://issues.jboss.org/browse/DBZ-1241[DBZ-1241]
* Default value for datetime(0) is  incorrectly handled https://issues.jboss.org/browse/DBZ-1243[DBZ-1243]
* Postgres connector failing because empty state data is being stored in offsets topic https://issues.jboss.org/browse/DBZ-1245[DBZ-1245]
* Default value for Bit does not work for larger values https://issues.jboss.org/browse/DBZ-1249[DBZ-1249]
* Microsecond precision is lost when reading timetz data from Postgres. https://issues.jboss.org/browse/DBZ-1260[DBZ-1260]


=== Other changes

This release includes also other changes:

* Zookeeper image documentation does not describe txns mountpoint https://issues.jboss.org/browse/DBZ-1231[DBZ-1231]
* Parse enum and set options with Antlr https://issues.jboss.org/browse/DBZ-739[DBZ-739]


[[release-0-9-4-final]]
== *Release 0.9.4.Final* _(April 11th, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12341407[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.1.1 and has been tested with version 2.1.1 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.9.4.Final from any of the earlier 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.9.4.Final plugin files, and restart the connector using the same configuration.
Upon restart, the 0.9.4.Final connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.


=== New Features

* Add MySQL Connector metric to expose "number of filtered events" https://issues.jboss.org/browse/DBZ-1206[DBZ-1206]
* Support TLS 1.2 for MySQL https://issues.jboss.org/browse/DBZ-1208[DBZ-1208]
* Create new MysqlConnector metric exposing if the connector is tracking offsets using GTIDs or not. https://issues.jboss.org/browse/DBZ-1221[DBZ-1221]
* Add support for columns of type INET https://issues.jboss.org/browse/DBZ-1189[DBZ-1189]


=== Fixes

This release includes the following fixes:

* Incorrect value for datetime field for '0001-01-01 00:00:00' https://issues.jboss.org/browse/DBZ-1143[DBZ-1143]
* PosgreSQL DecoderBufs crash when working with geometries in "public" schema https://issues.jboss.org/browse/DBZ-1144[DBZ-1144]
* [postgres] differing logic between snapsnot and streams for create record https://issues.jboss.org/browse/DBZ-1163[DBZ-1163]
* Error while deserializing binlog event https://issues.jboss.org/browse/DBZ-1191[DBZ-1191]
* MySQL connector throw an exception when captured invalid datetime https://issues.jboss.org/browse/DBZ-1194[DBZ-1194]
* Error when alter Enum column with CHARACTER SET https://issues.jboss.org/browse/DBZ-1203[DBZ-1203]
* Mysql: Getting ERROR `Failed due to error: connect.errors.ConnectException: For input string: "false"` https://issues.jboss.org/browse/DBZ-1204[DBZ-1204]
* MySQL connection timeout after bootstrapping a new table https://issues.jboss.org/browse/DBZ-1207[DBZ-1207]
* SLF4J usage issues https://issues.jboss.org/browse/DBZ-1212[DBZ-1212]
* JDBC Connection Not Closed in MySQL Connector Snapshot Reader https://issues.jboss.org/browse/DBZ-1218[DBZ-1218]
* Support FLOAT(p) column definition style https://issues.jboss.org/browse/DBZ-1220[DBZ-1220]


=== Other changes

This release includes also other changes:

* Add WhitespaceAfter check to Checkstyle https://issues.jboss.org/browse/DBZ-362[DBZ-362]
* Document RDS Postgres wal_level behavior https://issues.jboss.org/browse/DBZ-1219[DBZ-1219]


[[release-0-9-3-final]]
== *Release 0.9.3.Final* _(March 25th, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12340751[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.1.1 and has been tested with version 2.1.1 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.9.3.Final from any of the earlier 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.9.3.Final plugin files, and restart the connector using the same configuration.
Upon restart, the 0.9.3.Final connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.


=== New Features

* Support Outbox SMT as part of Debezium core https://issues.jboss.org/browse/DBZ-1169[DBZ-1169]
* Add support for partial recovery from lost slot in postgres https://issues.jboss.org/browse/DBZ-1082[DBZ-1082]


=== Fixes

This release includes the following fixes:

* Postgresql Snapshot with a table that has > 8192records hangs https://issues.jboss.org/browse/DBZ-1161[DBZ-1161]
* HStores fail to Snapshot properly  https://issues.jboss.org/browse/DBZ-1162[DBZ-1162]
* NullPointerException When there are multiple tables in different schemas in the whitelist  https://issues.jboss.org/browse/DBZ-1166[DBZ-1166]
* Cannot set offset.flush.interval.ms via docker entrypoint https://issues.jboss.org/browse/DBZ-1167[DBZ-1167]
* Missing Oracle OCI library is not reported as error https://issues.jboss.org/browse/DBZ-1170[DBZ-1170]
* RecordsStreamProducer forgets to convert commitTime from nanoseconds to microseconds https://issues.jboss.org/browse/DBZ-1174[DBZ-1174]
* MongoDB Connector doesn't fail on invalid hosts configuration https://issues.jboss.org/browse/DBZ-1177[DBZ-1177]
* Handle NPE errors when trying to create history topic against confluent cloud https://issues.jboss.org/browse/DBZ-1179[DBZ-1179]
* The Postgres wal2json streaming and non-streaming decoders do not process empty events https://issues.jboss.org/browse/DBZ-1181[DBZ-1181]
* Can't continue after snapshot is done https://issues.jboss.org/browse/DBZ-1184[DBZ-1184]
* ParsingException for SERIAL keyword https://issues.jboss.org/browse/DBZ-1185[DBZ-1185]
* STATS_SAMPLE_PAGES config cannot be parsed https://issues.jboss.org/browse/DBZ-1186[DBZ-1186]
* MySQL Connector generates false alarm for empty password https://issues.jboss.org/browse/DBZ-1188[DBZ-1188]


=== Other changes

This release includes also other changes:

* Ensure no brace-less if() blocks are used in the code base https://issues.jboss.org/browse/DBZ-1039[DBZ-1039]
* Align Oracle DDL parser code to use the same structure as MySQL https://issues.jboss.org/browse/DBZ-1192[DBZ-1192]


[[release-0-9-2-final]]
== *Release 0.9.2.Final* _(February 22nd, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12340752[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.1.1 and has been tested with version 2.1.1 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, PostgreSQL or SQL Server connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.9.2.Final from any of the earlier 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.9.2.Final plugin files, and restart the connector using the same configuration.
Upon restart, the 0.9.2.Final connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.


=== New Features

* Add snapshotting mode NEVER for MongoDB connector https://issues.jboss.org/browse/DBZ-867[DBZ-867]
* Allow passing of arbitrary parameters when replication slot is started https://issues.jboss.org/browse/DBZ-1130[DBZ-1130]


=== Fixes

This release includes the following fixes:

* Integer default value for DECIMAL column fails with Avro Converter https://issues.jboss.org/browse/DBZ-1077[DBZ-1077]
* connect binds only to hostname interface https://issues.jboss.org/browse/DBZ-1108[DBZ-1108]
* Connector fails to connect to binlog on connectors rebalance, throws ServerException https://issues.jboss.org/browse/DBZ-1132[DBZ-1132]
* Fail to parse MySQL TIME with values bigger than 23:59:59.999999 https://issues.jboss.org/browse/DBZ-1137[DBZ-1137]
* Test dependencies shouldn't be part of the SQL Server connector archive https://issues.jboss.org/browse/DBZ-1138[DBZ-1138]
* Emit correctly-typed fallback values for replica identity DEFAULT https://issues.jboss.org/browse/DBZ-1141[DBZ-1141]
* Unexpected exception while streaming changes from row with unchanged toast https://issues.jboss.org/browse/DBZ-1146[DBZ-1146]
* SQL syntax error near '"gtid_purged"' https://issues.jboss.org/browse/DBZ-1147[DBZ-1147]
* Postgres delete operations throwing DataException https://issues.jboss.org/browse/DBZ-1149[DBZ-1149]
* Antlr parser fails on column names that are keywords https://issues.jboss.org/browse/DBZ-1150[DBZ-1150]
* SqlServerConnector doesn't work with table names with "special characters" https://issues.jboss.org/browse/DBZ-1153[DBZ-1153]


=== Other changes

This release includes also other changes:

* Describe topic-level settings to ensure event consumption when log compaction is enabled https://issues.jboss.org/browse/DBZ-1136[DBZ-1136]
* Upgrade binlog client to 0.19.0 https://issues.jboss.org/browse/DBZ-1140[DBZ-1140]
* Upgrade kafkacat to 1.4.0-RC1 https://issues.jboss.org/browse/DBZ-1148[DBZ-1148]
* Upgrade Avro connector version to 5.1.2 https://issues.jboss.org/browse/DBZ-1156[DBZ-1156]
* Upgrade to Kafka 2.1.1 https://issues.jboss.org/browse/DBZ-1157[DBZ-1157]


[[release-0-9-1-final]]
== *Release 0.9.1.Final* _(February 13th, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12340576[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.1.0 and has been tested with version 2.1.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.9.1.Final from any of the earlier 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.9.1.Final plugin files, and restart the connector using the same configuration.
Upon restart, the 0.9.1.Final connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.


=== New Features

* Provide new container image with tooling for examples and demos https://issues.jboss.org/browse/DBZ-1125[DBZ-1125]


=== Fixes

This release includes the following fixes:

* BigDecimal has mismatching scale value for given Decimal schema error due to permissive mysql ddl https://issues.jboss.org/browse/DBZ-983[DBZ-983]
* Primary key changes cause UnsupportedOperationException https://issues.jboss.org/browse/DBZ-997[DBZ-997]
* java.lang.IllegalArgumentException: timeout value is negative https://issues.jboss.org/browse/DBZ-1019[DBZ-1019]
* Connector consumes huge amount of memory https://issues.jboss.org/browse/DBZ-1065[DBZ-1065]
* Strings.join() doesn't apply conversation for first element https://issues.jboss.org/browse/DBZ-1112[DBZ-1112]
* NPE if database history filename has no parent folder https://issues.jboss.org/browse/DBZ-1122[DBZ-1122]
* Generated columns not supported by DDL parser https://issues.jboss.org/browse/DBZ-1123[DBZ-1123]
* Advancing LSN in the first iteration - possible data loss https://issues.jboss.org/browse/DBZ-1128[DBZ-1128]
* Incorrect LSN comparison can cause out of order processing https://issues.jboss.org/browse/DBZ-1131[DBZ-1131]


=== Other changes

This release includes also other changes:

* io.debezium.connector.postgresql.PostgisGeometry shouldn't use DatatypeConverter https://issues.jboss.org/browse/DBZ-962[DBZ-962]
* Schema change events should be of type ALTER when table is modified https://issues.jboss.org/browse/DBZ-1121[DBZ-1121]
* Wal2json ISODateTimeFormatTest fails with a locale other than Locale.ENGLISH https://issues.jboss.org/browse/DBZ-1126[DBZ-1126]


=== Known issues

A potential https://github.com/shyiko/mysql-binlog-connector-java/pull/260[race condition] was identified in upstream library for MySQL's binary log processing.
The problem exhibits as the issue https://issues.jboss.org/projects/DBZ/issues/DBZ-1132[DBZ-1132].
If you are affected by it we propose as the workaround to increase Kafka Connect configuration options `task.shutdown.graceful.timeout.ms` and `connect.rebalance.timeout.ms`.
If the problem persists please disable keepalive thread via Debezium configration option `connect.keep.alive`.


[[release-0-9-0-final]]
== *Release 0.9.0.Final* _(February 5th, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12340275[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.1.0 and has been tested with version 2.1.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.9.0.Final from any of the earlier 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.9.0.Final plugin files, and restart the connector using the same configuration.
Upon restart, the 0.9.0.Final connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.


=== New Features

* Expose more useful metrics and improve Grafana dashboard https://issues.jboss.org/browse/DBZ-1040[DBZ-1040]


=== Fixes

This release includes the following fixes:

* Allow to use drop-slot-on-close option with wal2json https://issues.jboss.org/browse/DBZ-1111[DBZ-1111]
* MySqlDdlParser does not support adding multiple partitions in a single ALTER TABLE ... ADD PARTITION statement  https://issues.jboss.org/browse/DBZ-1113[DBZ-1113]
* Debezium fails to take a lock during snapshot https://issues.jboss.org/browse/DBZ-1115[DBZ-1115]
* Data from Postgres partitioned table written to wrong topic during snapshot https://issues.jboss.org/browse/DBZ-1118[DBZ-1118]


=== Other changes

This release includes also other changes:

* Clarify whether DDL parser is actually needed for SQL Server connector https://issues.jboss.org/browse/DBZ-1096[DBZ-1096]
* Add design description to SqlServerStreamingChangeEventSource https://issues.jboss.org/browse/DBZ-1097[DBZ-1097]
* Put out message about missing LSN at WARN level https://issues.jboss.org/browse/DBZ-1116[DBZ-1116]


[[release-0-9-0-cr1]]
== *Release 0.9.0.CR1* _(January 19th, 2019)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12340263[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.1.0 and has been tested with version 2.1.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.9.0.CR1 from any of the earlier 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.9.0.CR1 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.9.0.CR1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

SQL Server connector has re-worked semantics of snapshot modes (https://issues.jboss.org/browse/DBZ-947[DBZ-947]). +
SQL Server connector also adds a new field to offsets in the streaming mode (https://issues.jboss.org/browse/DBZ-1090[DBZ-1090]) which could prevent seamless upgrading of versions.
We recommend to re-register and restart the connector. +
SQL Server connector has changed the schema name of messages schemas (https://issues.jboss.org/browse/DBZ-1089[DBZ-1089]), superfluous database name has been dropped.


=== New Features

* Snapshot isolation level overhaul https://issues.jboss.org/browse/DBZ-947[DBZ-947]
* Kafka docker image - support for topic cleanup policy https://issues.jboss.org/browse/DBZ-1038[DBZ-1038]
* Optimize sys.fn_cdc_map_lsn_to_time() calls https://issues.jboss.org/browse/DBZ-1078[DBZ-1078]
* Fallback to restart_lsn if confirmed_flush_lsn is not found https://issues.jboss.org/browse/DBZ-1081[DBZ-1081]
* table.whitelist option update for an existing connector doesn't work https://issues.jboss.org/browse/DBZ-175[DBZ-175]
* EmbeddedEngine should allow for more flexible record consumption https://issues.jboss.org/browse/DBZ-1080[DBZ-1080]
* Client-side column blacklisting in SQL Server connector https://issues.jboss.org/browse/DBZ-1067[DBZ-1067]
* column.propagate.source.type missing scale https://issues.jboss.org/browse/DBZ-1073[DBZ-1073]


=== Fixes

This release includes the following fixes:

* ArrayIndexOutOfBoundsException when a column is deleted (Postgres) https://issues.jboss.org/browse/DBZ-996[DBZ-996]
* Messages from tables without PK and with REPLICA IDENTITY FULL https://issues.jboss.org/browse/DBZ-1029[DBZ-1029]
* Inconsistent schema name in streaming and snapshotting phase https://issues.jboss.org/browse/DBZ-1051[DBZ-1051]
* "watch-topic" and "create-topic" commands fail https://issues.jboss.org/browse/DBZ-1057[DBZ-1057]
* Antlr Exception: mismatched input '.' expecting {<EOF>, '--'} https://issues.jboss.org/browse/DBZ-1059[DBZ-1059]
* MySQL JDBC Context sets the wrong truststore password https://issues.jboss.org/browse/DBZ-1062[DBZ-1062]
* Unsigned smallint column in mysql failing due to out of range error https://issues.jboss.org/browse/DBZ-1063[DBZ-1063]
* NULL Values are replaced by default values even in NULLABLE fields https://issues.jboss.org/browse/DBZ-1064[DBZ-1064]
* Uninformative "Found previous offset" log https://issues.jboss.org/browse/DBZ-1066[DBZ-1066]
* SQL Server connector does not persist LSNs in Kafka https://issues.jboss.org/browse/DBZ-1069[DBZ-1069]
* [debezium] ERROR: option \"include-unchanged-toast\" = \"0\" is unknown https://issues.jboss.org/browse/DBZ-1083[DBZ-1083]
* Debezium fails when consuming table without primary key with turned on topic routing https://issues.jboss.org/browse/DBZ-1086[DBZ-1086]
* Wrong message key and event used when primary key is updated https://issues.jboss.org/browse/DBZ-1088[DBZ-1088]
* Connect schema name is wrong for SQL Server https://issues.jboss.org/browse/DBZ-1089[DBZ-1089]
* Incorrect LSN tracking - possible data loss https://issues.jboss.org/browse/DBZ-1090[DBZ-1090]
* Race condition in EmbeddedEngine shutdown https://issues.jboss.org/browse/DBZ-1103[DBZ-1103]


=== Other changes

This release includes also other changes:

* Intermittent failures in RecordsStreamProducerIT#shouldPropagateSourceColumnTypeToSchemaParameter() https://issues.jboss.org/browse/DBZ-781[DBZ-781]
* Assert MongoDB supported versions https://issues.jboss.org/browse/DBZ-988[DBZ-988]
* Describe how to do DDL changes for SQL Server https://issues.jboss.org/browse/DBZ-993[DBZ-993]
* Verify version of wal2json on RDS https://issues.jboss.org/browse/DBZ-1056[DBZ-1056]
* Move SQL Server connector to main repo https://issues.jboss.org/browse/DBZ-1084[DBZ-1084]
* Don't enqueue further records when connector is stopping https://issues.jboss.org/browse/DBZ-1099[DBZ-1099]
* Race condition in SQLServer tests during snapshot phase https://issues.jboss.org/browse/DBZ-1101[DBZ-1101]
* Remove columnNames field from TableImpl https://issues.jboss.org/browse/DBZ-1105[DBZ-1105]
* column.propagate.source.type missing scale https://issues.jboss.org/browse/DBZ-387[DBZ-387]
* write catch-up binlog reader https://issues.jboss.org/browse/DBZ-388[DBZ-388]
* changes to Snapshot and Binlog readers to allow for concurrent/partial running https://issues.jboss.org/browse/DBZ-389[DBZ-389]


[[release-0-9-0-beta2]]
== *Release 0.9.0.Beta2* _(December 19th, 2018)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12339976[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.1.0 and has been tested with version 2.1.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.9.0.Beta2 from any of the earlier 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.9.0.Beta2 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.9.0.Beta2 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

The link:/docs/configuration/mongodb-event-flattening/[MongoDB CDC Event Flattening] transformation now by default removes deletion messages (https://issues.jboss.org/browse/DBZ-563[DBZ-563]).
The previous default was to keep them.

=== New Features

* Add support for Oracle 11g https://issues.jboss.org/browse/DBZ-954[DBZ-954]
* UnwrapFromMongoDbEnvelope refactor https://issues.jboss.org/browse/DBZ-1020[DBZ-1020]
* Add option for dropping deletes and tombstone events to MongoDB struct recreation SMT https://issues.jboss.org/browse/DBZ-563[DBZ-563]
* Expose "snapshot.delay.ms" option for all connectors https://issues.jboss.org/browse/DBZ-966[DBZ-966]
* Convey original operation type when using flattening SMTs https://issues.jboss.org/browse/DBZ-971[DBZ-971]
* Provide last event and captured tables in metrics https://issues.jboss.org/browse/DBZ-978[DBZ-978]
* Skip MySQL BinLog Event in case of Invalid Cell Values https://issues.jboss.org/browse/DBZ-1010[DBZ-1010]

=== Fixes

This release includes the following fixes:

* BinaryLogClient can't disconnect when adding records after shutdown has been initiated https://issues.jboss.org/browse/DBZ-604[DBZ-604]
* UnwrapFromMongoDbEnvelope fails when encountering $unset operator https://issues.jboss.org/browse/DBZ-612[DBZ-612]
* "no known snapshots" error when DBs rows are large https://issues.jboss.org/browse/DBZ-842[DBZ-842]
* MongoDB connector stops processing oplog events after encountering "new primary" event https://issues.jboss.org/browse/DBZ-848[DBZ-848]
* MySQL active-passive: brief data loss on failover when Debezium encounters new GTID channel https://issues.jboss.org/browse/DBZ-923[DBZ-923]
* ConnectException: Only REPEATABLE READ isolation level is supported for START TRANSACTION WITH CONSISTENT SNAPSHOT in RocksDB Storage Engine https://issues.jboss.org/browse/DBZ-960[DBZ-960]
* ConnectException during ALTER TABLE for non-whitelisted table https://issues.jboss.org/browse/DBZ-977[DBZ-977]
* UnwrapFromMongoDbEnvelope fails when encountering full updates https://issues.jboss.org/browse/DBZ-987[DBZ-987]
* UnwrapFromMongoDbEnvelope fails when encountering Tombstone messages https://issues.jboss.org/browse/DBZ-989[DBZ-989]
* Postgres schema changes detection (not-null constraint) https://issues.jboss.org/browse/DBZ-1000[DBZ-1000]
* NPE in SqlServerConnectorTask#cleanupResources() if connector failed to start https://issues.jboss.org/browse/DBZ-1002[DBZ-1002]
* Explicitly initialize history topic in HistorizedRelationalDatabaseSchema https://issues.jboss.org/browse/DBZ-1003[DBZ-1003]
* BinlogReader ignores GTIDs for empty database https://issues.jboss.org/browse/DBZ-1005[DBZ-1005]
* NPE in MySqlConnectorTask.stop() https://issues.jboss.org/browse/DBZ-1006[DBZ-1006]
* The name of captured but not whitelisted table is not logged https://issues.jboss.org/browse/DBZ-1007[DBZ-1007]
* GTID set is not properly initialized after DB failover https://issues.jboss.org/browse/DBZ-1008[DBZ-1008]
* Postgres Connector fails on none nullable MACADDR field during initial snapshot https://issues.jboss.org/browse/DBZ-1009[DBZ-1009]
* Connector crashes with java.lang.NullPointerException when using multiple sinks to consume the messages https://issues.jboss.org/browse/DBZ-1017[DBZ-1017]
* Postgres connector fails upon event of recently deleted table https://issues.jboss.org/browse/DBZ-1021[DBZ-1021]
* ORA-46385: DML and DDL operations are not allowed on table "AUDSYS"."AUD$UNIFIED" https://issues.jboss.org/browse/DBZ-1023[DBZ-1023]
* Postgres plugin does not signal the end of snapshot properly https://issues.jboss.org/browse/DBZ-1024[DBZ-1024]
* MySQL Antlr runtime.NoViableAltException https://issues.jboss.org/browse/DBZ-1028[DBZ-1028]
* Debezium 0.8.2 and 0.8.3.Final Not Available on Confluent Hub https://issues.jboss.org/browse/DBZ-1030[DBZ-1030]
* Snapshot of tables with reserved names fails https://issues.jboss.org/browse/DBZ-1031[DBZ-1031]
* UnwrapFromMongoDbEnvelope doesn't support operation header on tombstone messages https://issues.jboss.org/browse/DBZ-1032[DBZ-1032]
* Mysql binlog reader lost data if restart task when last binlog event is QUERY event. https://issues.jboss.org/browse/DBZ-1033[DBZ-1033]
* The same capture instance name is logged twice https://issues.jboss.org/browse/DBZ-1047[DBZ-1047]


=== Other changes

This release includes also other changes:

* MySQL 8 compatibility https://issues.jboss.org/browse/DBZ-688[DBZ-688]
* Don't hard code list of supported MySQL storage engines in Antlr grammar https://issues.jboss.org/browse/DBZ-992[DBZ-992]
* Provide updated KSQL example https://issues.jboss.org/browse/DBZ-999[DBZ-999]
* Update to Kafka 2.1 https://issues.jboss.org/browse/DBZ-1001[DBZ-1001]
* Skipt Antlr tests when tests are skipped https://issues.jboss.org/browse/DBZ-1004[DBZ-1004]
* Fix expected records counts in MySQL tests https://issues.jboss.org/browse/DBZ-1016[DBZ-1016]
* Cannot run tests against Kafka 1.x https://issues.jboss.org/browse/DBZ-1037[DBZ-1037]
* Configure MySQL Matrix testing job to test with and without GTID https://issues.jboss.org/browse/DBZ-1050[DBZ-1050]


[[release-0-9-0-beta1]]
== *Release 0.9.0.Beta1* _(November 20th, 2018)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12339372[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.0.1 and has been tested with version 2.0.1 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.9.0.Beta1 from any of the earlier 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.9.0.Beta1 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.9.0.Beta1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

MySQL Connector now uses Antlr parser as https://issues.jboss.org/browse/DBZ-990[the default].

=== New Features

* Add STATUS_STORAGE_TOPIC environment variable to container images https://issues.jboss.org/browse/DBZ-893[DBZ-893]
* Support Postgres 11 in Decoderbufs https://issues.jboss.org/browse/DBZ-955[DBZ-955]
* Define the data directory where tests are storing their data https://issues.jboss.org/browse/DBZ-963[DBZ-963]
* Upgrade Kafka to 2.0.1 https://issues.jboss.org/browse/DBZ-979[DBZ-979]
* Implement unified metrics across connectors https://issues.jboss.org/browse/DBZ-776[DBZ-776]
* Initial snapshot using snapshot isolation level https://issues.jboss.org/browse/DBZ-941[DBZ-941]
* Add decimal.handling.mode for SQLServer Configuration https://issues.jboss.org/browse/DBZ-953[DBZ-953]
* Support pass-through of "database." properties to JDBC driver https://issues.jboss.org/browse/DBZ-964[DBZ-964]
* Handle changes of table definitions and tables created while streaming https://issues.jboss.org/browse/DBZ-812[DBZ-812]


=== Fixes

This release includes the following fixes:

* Error while parsing JSON column type for MySQL https://issues.jboss.org/browse/DBZ-935[DBZ-935]
* wal2json CITEXT columns set to empty strings https://issues.jboss.org/browse/DBZ-937[DBZ-937]
* Base docker image is deprecated https://issues.jboss.org/browse/DBZ-939[DBZ-939]
* Mysql connector failed to parse add partition statement https://issues.jboss.org/browse/DBZ-959[DBZ-959]
* PostgreSQL replication slots not updated in transactions https://issues.jboss.org/browse/DBZ-965[DBZ-965]
* wal2json_streaming decoder does not provide the right plugin name https://issues.jboss.org/browse/DBZ-970[DBZ-970]
* Create topics command doesn't work in Kafka docker image https://issues.jboss.org/browse/DBZ-976[DBZ-976]
* Antlr parser: support quoted engine names in DDL https://issues.jboss.org/browse/DBZ-990[DBZ-990]


=== Other changes

This release includes also other changes:

* Switch to Antlr-based parser implementation by default https://issues.jboss.org/browse/DBZ-757[DBZ-757]
* Support RENAME column syntax from MySQL 8.0 https://issues.jboss.org/browse/DBZ-780[DBZ-780]
* Fix documentation of 'array.encoding' option https://issues.jboss.org/browse/DBZ-925[DBZ-925]
* Support MongoDB 4.0 https://issues.jboss.org/browse/DBZ-974[DBZ-974]


[[release-0-9-0-alpha2]]
== *Release 0.9.0.Alpha2* _(October 4th, 2018)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12338766[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 2.0.0 and has been tested with version 2.0.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.9.0.Alpha2 from any of the earlier 0.9.x, 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.9.0.Alpha2 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.9.0.Alpha2 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

MySQL JDBC driver was https://issues.jboss.org/browse/DBZ-763[upgraded] to version 8.x.
Kafka has been https://issues.jboss.org/browse/DBZ-858[upgraded] to version 2.0.0.

=== New Features

* Build Alpine Linux versions of the PostgreSQL containers https://issues.jboss.org/browse/DBZ-705[DBZ-705]
* Refactor methods to read MySQL sytem variables https://issues.jboss.org/browse/DBZ-849[DBZ-849]
* Correct param name for excludeColumns(String fullyQualifiedTableNames) https://issues.jboss.org/browse/DBZ-854[DBZ-854]
* Make BinlogReader#informAboutUnknownTableIfRequired() log with tableId https://issues.jboss.org/browse/DBZ-855[DBZ-855]
* MySQL identifier with dot or space could not be parsed https://issues.jboss.org/browse/DBZ-878[DBZ-878]
* Use postgres:10 instead of postgres:10.0 as base docker image https://issues.jboss.org/browse/DBZ-929[DBZ-929]
* Support temporary replication slots with Postgres >= 10 https://issues.jboss.org/browse/DBZ-934[DBZ-934]
* Support white/black-listing Mongo fields https://issues.jboss.org/browse/DBZ-633[DBZ-633]
* Postgres connector - add database, schema and table names to "source" section of records https://issues.jboss.org/browse/DBZ-866[DBZ-866]
* Support renaming Mongo fields https://issues.jboss.org/browse/DBZ-881[DBZ-881]
* use tcpKeepAlive by default https://issues.jboss.org/browse/DBZ-895[DBZ-895]
* Hstore support in Postgresql-connector https://issues.jboss.org/browse/DBZ-898[DBZ-898]
* Add connector type to source info https://issues.jboss.org/browse/DBZ-918[DBZ-918]


=== Fixes

This release includes the following fixes:

* Global read lock not release when exception raised during snapshot https://issues.jboss.org/browse/DBZ-769[DBZ-769]
* Abort loops in MongoPrimary#execute() if the connector is stopped https://issues.jboss.org/browse/DBZ-784[DBZ-784]
* Initial synchronization is not interrupted https://issues.jboss.org/browse/DBZ-838[DBZ-838]
* Kafka database history miscounting attempts even if there are more database history records to consume https://issues.jboss.org/browse/DBZ-853[DBZ-853]
* Schema_only snapshot on idle server - offsets not stored after snapshot https://issues.jboss.org/browse/DBZ-859[DBZ-859]
* DDL parsing in MySQL - default value of primary key is set to null https://issues.jboss.org/browse/DBZ-860[DBZ-860]
* Antlr DDL parser exception for "create database ... CHARSET=..." https://issues.jboss.org/browse/DBZ-864[DBZ-864]
* Error when MongoDB collection contains characters not compatible with kafka topic naming https://issues.jboss.org/browse/DBZ-865[DBZ-865]
* AlterTableParserListener does not remove column definition listeners https://issues.jboss.org/browse/DBZ-869[DBZ-869]
* MySQL parser does not recognize 0 as default value for date/time https://issues.jboss.org/browse/DBZ-870[DBZ-870]
* Antlr parser ignores table whitelist filter https://issues.jboss.org/browse/DBZ-872[DBZ-872]
* A new column might not be added with ALTER TABLE antlr parser https://issues.jboss.org/browse/DBZ-877[DBZ-877]
* MySQLConnectorTask always reports it has the required Binlog file from MySQL https://issues.jboss.org/browse/DBZ-880[DBZ-880]
* Execution of RecordsStreamProducer.closeConnections() is susceptible to race condition https://issues.jboss.org/browse/DBZ-887[DBZ-887]
* Watch-topic command in docker image uses unsupported parameter https://issues.jboss.org/browse/DBZ-890[DBZ-890]
* SQLServer should use only schema and table name in table naming https://issues.jboss.org/browse/DBZ-894[DBZ-894]
* Prevent resending of duplicate change events after restart https://issues.jboss.org/browse/DBZ-897[DBZ-897]
* PostgresConnection.initTypeRegistry() takes ~24 mins https://issues.jboss.org/browse/DBZ-899[DBZ-899]
* java.time.format.DateTimeParseException: Text '1970-01-01 00:00:00' in mysql ALTER https://issues.jboss.org/browse/DBZ-901[DBZ-901]
* org.antlr.v4.runtime.NoViableAltException on CREATE DEFINER=`web`@`%` PROCEDURE `... https://issues.jboss.org/browse/DBZ-903[DBZ-903]
* MySQL default port is wrong in tutorial link https://issues.jboss.org/browse/DBZ-904[DBZ-904]
* RecordsStreamProducer should report refresh of the schema due to different column count https://issues.jboss.org/browse/DBZ-907[DBZ-907]
* MongoDbConnector returns obsolete config values during validation https://issues.jboss.org/browse/DBZ-908[DBZ-908]
* Can't parse create definition on the mysql connector https://issues.jboss.org/browse/DBZ-910[DBZ-910]
* RecordsStreamProducer#columnValues() does not take into account unchanged TOASTed columns, refreshing table schemas unnecessarily https://issues.jboss.org/browse/DBZ-911[DBZ-911]
* Wrong type in timeout call for Central wait release https://issues.jboss.org/browse/DBZ-914[DBZ-914]
* Exception while parsing table schema with invalid default value for timestamp field https://issues.jboss.org/browse/DBZ-927[DBZ-927]
* Discard null fields in MongoDB event flattening SMT https://issues.jboss.org/browse/DBZ-928[DBZ-928]


=== Other changes

This release includes also other changes:

* Create Travis CI build for debezium-incubator repository https://issues.jboss.org/browse/DBZ-817[DBZ-817]
* Cache prepared statements in JdbcConnection https://issues.jboss.org/browse/DBZ-819[DBZ-819]
* Upgrade to Kafka 2.0.0 https://issues.jboss.org/browse/DBZ-858[DBZ-858]
* Upgrad SQL Server image to CU9 GDR2 release https://issues.jboss.org/browse/DBZ-873[DBZ-873]
* Speed-up Travis builds using parallel build https://issues.jboss.org/browse/DBZ-874[DBZ-874]
* Add version format check into the release pipeline https://issues.jboss.org/browse/DBZ-884[DBZ-884]
* Handle non-complete list of plugins https://issues.jboss.org/browse/DBZ-885[DBZ-885]
* Parametrize wait time for Maven central sync https://issues.jboss.org/browse/DBZ-889[DBZ-889]
* Assert non-empty release in release script https://issues.jboss.org/browse/DBZ-891[DBZ-891]
* Upgrade Postgres driver to 42.2.5 https://issues.jboss.org/browse/DBZ-912[DBZ-912]
* Upgrade MySQL JDBC driver to version 8.0.x https://issues.jboss.org/browse/DBZ-763[DBZ-763]
* Upgrade MySQL binlog connector https://issues.jboss.org/browse/DBZ-764[DBZ-764]


[[release-0-8-3-final]]
== *Release 0.8.3.Final* _(September 19th, 2018)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version0=12339197[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 1.1.0 and has been tested with version 1.1.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.8.3.Final from any of the earlier 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.8.3.Final plugin files, and restart the connector using the same configuration.
Upon restart, the 0.8.3.Final connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.

=== New Features

* Ability to rewrite deleted records https://issues.jboss.org/browse/DBZ-857)[DBZ-857]; note this deprecates the existing "drop.deletes" link:/docs/configuration/event-flattening/#configuration_options[SMT configuration option]; instead set "delete.handling.mode" to "drop";
* use tcpKeepAlive by default https://issues.jboss.org/browse/DBZ-895)[DBZ-895]

=== Fixes

This release includes the following fixes:

* Global read lock not release when exception raised during snapshot https://issues.jboss.org/browse/DBZ-769)[DBZ-769]
* Abort loops in MongoPrimary#execute() if the connector is stopped https://issues.jboss.org/browse/DBZ-784)[DBZ-784]
* GtidModeEnabled method check gtid mode will always be true https://issues.jboss.org/browse/DBZ-820)[DBZ-820]
* Sensitive vars CONNECT_CONSUMER_SASL_JAAS_CONFIG and CONNECT_PRODUCER_SASL_JAAS_CONFIG are printed to the log https://issues.jboss.org/browse/DBZ-861)[DBZ-861]
* A new replication slot waits for all concurrent transactions to finish https://issues.jboss.org/browse/DBZ-862)[DBZ-862]
* Execution of RecordsStreamProducer.closeConnections() is susceptible to race condition https://issues.jboss.org/browse/DBZ-887)[DBZ-887]
* PostgresConnection.initTypeRegistry() takes ~24 mins https://issues.jboss.org/browse/DBZ-899)[DBZ-899]
* java.time.format.DateTimeParseException: Text '1970-01-01 00:00:00' in mysql ALTER https://issues.jboss.org/browse/DBZ-901)[DBZ-901]
* org.antlr.v4.runtime.NoViableAltException on CREATE DEFINER=`web`@`%` PROCEDURE `... https://issues.jboss.org/browse/DBZ-903)[DBZ-903]
* RecordsStreamProducer should report refresh of the schema due to different column count https://issues.jboss.org/browse/DBZ-907)[DBZ-907]
* MongoDbConnector returns obsolete config values during validation https://issues.jboss.org/browse/DBZ-908)[DBZ-908]
* Can't parse create definition on the mysql connector https://issues.jboss.org/browse/DBZ-910)[DBZ-910]


=== Other changes

None


[[release-0-8-2]]
== *Release 0.8.2* _(August 30th, 2018)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12338793[complete list of issues].

Note that by accident the version of the release artifacts is _0.8.2_ instead of _0.8.2.Final_.
This is not in line with our recently established convention of always letting release versions end with qualifiers such as _Alpha1_, _Beta1_, _CR1_ or _Final_.
The next version in the 0.8 line will be _0.8.3.Final_ and we'll improve our release pipeline to make sure that this situation doesn't occur again.

=== Kafka compatibility

This release has been built against Kafka Connect 1.1.0 and has been tested with version 1.1.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.8.2.Final from any of the earlier 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.8.2.Final plugin files, and restart the connector using the same configuration.
Upon restart, the 0.8.2.Final connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.

=== New Features

* Postgres connector - add database, schema and table names to "source" section of records https://issues.jboss.org/browse/DBZ-866[DBZ-866]

=== Fixes

This release includes the following fixes:

* Initial synchronization is not interrupted https://issues.jboss.org/browse/DBZ-838[DBZ-838]
* Schema_only snapshot on idle server - offsets not stored after snapshot https://issues.jboss.org/browse/DBZ-859[DBZ-859]
* DDL parsing in MySQL - default value of primary key is set to null https://issues.jboss.org/browse/DBZ-860[DBZ-860]
* Antlr DDL parser exception for "create database ... CHARSET=..." https://issues.jboss.org/browse/DBZ-864[DBZ-864]
* Missing 0.8.1.Final tags for Zookeper and Kafka https://issues.jboss.org/browse/DBZ-868[DBZ-868]
* AlterTableParserListener does not remove column definition listeners https://issues.jboss.org/browse/DBZ-869[DBZ-869]
* MySQL parser does not recognize 0 as default value for date/time https://issues.jboss.org/browse/DBZ-870[DBZ-870]
* Antlr parser ignores table whitelist filter https://issues.jboss.org/browse/DBZ-872[DBZ-872]
* A new column might not be added with ALTER TABLE antlr parser https://issues.jboss.org/browse/DBZ-877[DBZ-877]
* MySQLConnectorTask always reports it has the required Binlog file from MySQL https://issues.jboss.org/browse/DBZ-880[DBZ-880]


=== Other changes

None


[[release-0-9-0-alpha1]]
== *Release 0.9.0.Alpha1* _(July 26th, 2018)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12338152[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 1.1.1 and has been tested with version 1.1.1 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.9.0.Alpha1 from any of the earlier 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.9.0.Alpha1 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.9.0.Alpha1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

The Oracle connector was storing event timestamp in the `source` block in field `ts_sec`. The time stamp is in fact measured in milliseconds to so the field was https://issues.jboss.org/browse/DBZ-795[renamed] to `ts_ms`.

=== New Features

* Ingest change data from SQL Server databases https://issues.jboss.org/browse/DBZ-40[DBZ-40]
* Oracle connector implementation cont'd (initial snapshotting etc.) https://issues.jboss.org/browse/DBZ-716[DBZ-716]
* Implement initial snapshotting for Oracle https://issues.jboss.org/browse/DBZ-720[DBZ-720]
* Implement capturing of streamed changes https://issues.jboss.org/browse/DBZ-787[DBZ-787]
* Implement initial snapshotting for SQL Server https://issues.jboss.org/browse/DBZ-788[DBZ-788]
* Emit NUMBER columns as Int32/Int64 if precision and scale allow https://issues.jboss.org/browse/DBZ-804[DBZ-804]
* Support heartbeat messages for Oracle https://issues.jboss.org/browse/DBZ-815[DBZ-815]
* Upgrade to Kafka 1.1.1 https://issues.jboss.org/browse/DBZ-829[DBZ-829]


=== Fixes

This release includes the following fixes:

* Offset remains with "snapshot" set to true after completing schema only snapshot https://issues.jboss.org/browse/DBZ-803[DBZ-803]
* Misleading timestamp field name https://issues.jboss.org/browse/DBZ-795[DBZ-795]
* Adjust scale of decimal values to column's scale if present https://issues.jboss.org/browse/DBZ-818[DBZ-818]
* Avoid NPE if commit is called before any offset is prepared https://issues.jboss.org/browse/DBZ-826[DBZ-826]


=== Other changes

This release includes also other changes:

* Make DatabaseHistory set-up code re-usable https://issues.jboss.org/browse/DBZ-816[DBZ-816]
* Use TableFilter contract instead of Predicate<TableId> https://issues.jboss.org/browse/DBZ-793[DBZ-793]
* Expand SourceInfo https://issues.jboss.org/browse/DBZ-719[DBZ-719]
* Provide Maven module and Docker set-up https://issues.jboss.org/browse/DBZ-786[DBZ-786]
* Avoid a few raw type warnings https://issues.jboss.org/browse/DBZ-801[DBZ-801]


[[release-0-8-1-final]]
== *Release 0.8.1.Final* _(July 25th, 2018)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12338169[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 1.1.0 and has been tested with version 1.1.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.8.1.Final from any of the earlier 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.8.1.Final plugin files, and restart the connector using the same configuration.
Upon restart, the 0.8.1.Final connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.

=== New Features

None


=== Fixes

This release includes the following fixes:

* PostgreSQL LSNs are not committed when receiving events for filtered-out tables https://issues.jboss.org/browse/DBZ-800[DBZ-800]


=== Other changes

This release includes also other changes:

* Extract common TopicSelector contract https://issues.jboss.org/browse/DBZ-627[DBZ-627]
* Remove redundant Docker configuration https://issues.jboss.org/browse/DBZ-796[DBZ-796]


[[release-0-8-0-final]]
== *Release 0.8.0.Final* _(July 11th, 2018)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12338151[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 1.1.0 and has been tested with version 1.1.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.8.0.Final from any of the earlier 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.8.0.CR1 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.8.0.CR1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

The topic naming for Oracle connector has https://issues.jboss.org/browse/DBZ-725[changed] and the database name is no longer part of the name.
The naming convention is thus consistent accross all connectors.

=== New Features

This release includes the following new features:

* Expose more granular snapshot metrics via JMX https://issues.jboss.org/browse/DBZ-789[DBZ-789]


=== Fixes

None


=== Other changes

This release includes also other changes:

* Remove DB name from topic ids https://issues.jboss.org/browse/DBZ-725[DBZ-725]
* Don't use user with DBA permissions for Oracle connector tests https://issues.jboss.org/browse/DBZ-791[DBZ-791]


[[release-0-8-0-cr-1]]
== *Release 0.8.0.CR1* _(July 4th, 2018)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12338150[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 1.1.0 and has been tested with version 1.1.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.8.0.CR1 from any of the earlier 0.8.x, 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.8.0.CR1 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.8.0.CR1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.

=== New Features

This release includes the following new features:

* List collections only for databases accepted by database filter https://issues.jboss.org/browse/DBZ-713[DBZ-713]
* Set DECIMAL precision as schema parameter https://issues.jboss.org/browse/DBZ-751[DBZ-751]
* Stop MongoDB connector in case of authorization failure https://issues.jboss.org/browse/DBZ-782[DBZ-782]
* Add the original data type of a column as schema parameter https://issues.jboss.org/browse/DBZ-644[DBZ-644]
* Add support for columns of type CITEXT https://issues.jboss.org/browse/DBZ-762[DBZ-762]


=== Fixes

This release includes the following fixes:

* Allow Empty Database Passwords https://issues.jboss.org/browse/DBZ-743[DBZ-743]
* Antlr parser raising exception for MySQL-valid ALTER TABLE https://issues.jboss.org/browse/DBZ-767[DBZ-767]
* Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff] https://issues.jboss.org/browse/DBZ-768[DBZ-768]
* Antlr parser raising exception when parsing ENUM fields https://issues.jboss.org/browse/DBZ-770[DBZ-770]
* Default value is not removed when changing a column's type https://issues.jboss.org/browse/DBZ-771[DBZ-771]


=== Other changes

This release includes also other changes:

* Add documentation for supported geometry types https://issues.jboss.org/browse/DBZ-573[DBZ-573]
* Benchmark Antlr parser https://issues.jboss.org/browse/DBZ-742[DBZ-742]
* Document rules for "slot.name" property of the Postgres connector https://issues.jboss.org/browse/DBZ-746[DBZ-746]
* Add table-of-contents sections to connector doc pages https://issues.jboss.org/browse/DBZ-752[DBZ-752]
* Guard against simple bugs https://issues.jboss.org/browse/DBZ-759[DBZ-759]
* Reduce test log output https://issues.jboss.org/browse/DBZ-765[DBZ-765]
* Document wal2json plugin streaming mode https://issues.jboss.org/browse/DBZ-772[DBZ-772]
* Extract common base class for relational DatabaseSchema implementations https://issues.jboss.org/browse/DBZ-773[DBZ-773]
* Intermittent failures in ReplicationConnectionIT#shouldCloseConnectionOnInvalidSlotName() https://issues.jboss.org/browse/DBZ-778[DBZ-778]
* Stabilize MongoDB integration test execution https://issues.jboss.org/browse/DBZ-779[DBZ-779]


[[release-0-8-0-beta-1]]
== *Release 0.8.0.Beta1* _(June 21st, 2018)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12337217[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 1.1.0 and has been tested with version 1.1.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.8.0.Beta1 from any of the earlier 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.8.0.Beta1 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.8.0.Beta1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

Topic names for heartbeat messages followed a hard-coded naming schema.
The rules were made more flexible in https://issues.jboss.org/browse/DBZ-668[DBZ-668].

Transaction id (`txId` field of `Envelope`) for PostgreSQL was originally encoded as an 32-bit `integer` type.
The real range is a 64-bit `long` type so this was changed in https://issues.jboss.org/browse/DBZ-673[DBZ-673].

The datatypes without timezone were not correctly offsetted for databases running in non-UTC timezones.
This was fixed in https://issues.jboss.org/browse/DBZ-578[DBZ-587] and https://issues.jboss.org/browse/DBZ-741[DBZ-741].
See link:docs/connectors/mysql/#temporal-values[MySQL] and link:docs/connectors/postgresql/#temporal-values[PostgreSQL] connector documentation for further details.

=== New Features

This release includes the following new features:

* Improve MySQL connector's handling of DML / DDL statements https://issues.jboss.org/browse/DBZ-252[DBZ-252]
* Snapshots fail if launching multiple connectors at once https://issues.jboss.org/browse/DBZ-601[DBZ-601]
* Data-inclusive snapshot without table locks (For RDS/Aurora) https://issues.jboss.org/browse/DBZ-639[DBZ-639]
* Enable ordered snapshotting of data-Mysql Connector https://issues.jboss.org/browse/DBZ-666[DBZ-666]
* Add a topic name configuration for the heartbeat messages https://issues.jboss.org/browse/DBZ-668[DBZ-668]
* Mongo cursor cleanup https://issues.jboss.org/browse/DBZ-672[DBZ-672]
* wal2json on RDS omits initial changes in streaming mode https://issues.jboss.org/browse/DBZ-679[DBZ-679]
* Make PG_CONFIG configurable (postgres-decoderbufs) https://issues.jboss.org/browse/DBZ-686[DBZ-686]
* Rebase Debezium to Kafka 1.1 and Confluent platform 4.1 https://issues.jboss.org/browse/DBZ-687[DBZ-687]
* When MySQL has BINLOG_ROWS_QUERY_LOG_EVENTS enabled, include original SQL query in event. https://issues.jboss.org/browse/DBZ-706[DBZ-706]
* Ingest change data from Oracle databases using XStream https://issues.jboss.org/browse/DBZ-20[DBZ-20]
* Support defaults in MySQL https://issues.jboss.org/browse/DBZ-191[DBZ-191]
* Run test suite against MongoDB 3.6 https://issues.jboss.org/browse/DBZ-529[DBZ-529]
* Provide option to flatten structs in MongoDB unwrapping SMT https://issues.jboss.org/browse/DBZ-561[DBZ-561]
* Allow configuration option for keep alive interval for Mysql binlog reader https://issues.jboss.org/browse/DBZ-670[DBZ-670]
* Add support for databases with encodings other than UTF-8/16/32 https://issues.jboss.org/browse/DBZ-676[DBZ-676]
* Provide option to specify statements to be executed upon connection creation (e.g.  connection wait timeout) https://issues.jboss.org/browse/DBZ-693[DBZ-693]

=== Fixes

This release includes the following fixes:

* Timestamps are not converted to UTC during snapshot https://issues.jboss.org/browse/DBZ-578[DBZ-578]
* wal2json cannot handle transactions bigger than 1Gb https://issues.jboss.org/browse/DBZ-638[DBZ-638]
* SMT - DataException with io.debezium.connector.mongodb.transforms.UnwrapFromMongoDbEnvelope https://issues.jboss.org/browse/DBZ-649[DBZ-649]
* SchemaParseException when using UnwrapFromMongoDbEnvelope SMT with Avro format https://issues.jboss.org/browse/DBZ-650[DBZ-650]
* Upgrade OpenShift intructions to Strimzi 0.2.0 https://issues.jboss.org/browse/DBZ-654[DBZ-654]
* Mysql ddl parser cannot parse scientific format number in exponential notation default values https://issues.jboss.org/browse/DBZ-667[DBZ-667]
* Close Kafka admin client after DB history topic has been created https://issues.jboss.org/browse/DBZ-669[DBZ-669]
* Postgres DateTimeParseException https://issues.jboss.org/browse/DBZ-671[DBZ-671]
* Transaction ID must be handled as long https://issues.jboss.org/browse/DBZ-673[DBZ-673]
* PostgreSQL connector doesn't handle TIME(p) columns correctly with wal2json https://issues.jboss.org/browse/DBZ-681[DBZ-681]
* Error on initial load for records with negative timestamp https://issues.jboss.org/browse/DBZ-694[DBZ-694]
* Postgres Connector inconsistent handling of timestamp precision https://issues.jboss.org/browse/DBZ-696[DBZ-696]
* Debezium is throwing exception when max OID in pg db is larger than max int https://issues.jboss.org/browse/DBZ-697[DBZ-697]
* PostgresReplicationConnection doesn't close jdbc connection https://issues.jboss.org/browse/DBZ-699[DBZ-699]
* Debezium is throwing exception when max typelem in pg db is larger than max int https://issues.jboss.org/browse/DBZ-701[DBZ-701]
* Plaintext jaas configuration passwords logged out https://issues.jboss.org/browse/DBZ-702[DBZ-702]
* Postgres TIME columns are always exported as nano-seconds, unlike documented https://issues.jboss.org/browse/DBZ-709[DBZ-709]
* Incorrect options for PostgreSQL sslmode listed in documentation https://issues.jboss.org/browse/DBZ-711[DBZ-711]
* Mongo Connector - doesn't redo initial sync after connector restart https://issues.jboss.org/browse/DBZ-712[DBZ-712]
* NUMERIC column without scale value causes exception https://issues.jboss.org/browse/DBZ-727[DBZ-727]
* Inconsistency in parameter names for database histy producer/consumer https://issues.jboss.org/browse/DBZ-728[DBZ-728]
* MySQL DATETIME Value Incorrectly Snapshotted https://issues.jboss.org/browse/DBZ-741[DBZ-741]

=== Other changes

This release includes also other changes:

* Support incubator repo in release process https://issues.jboss.org/browse/DBZ-749[DBZ-749]
* Upgrade Postgres Docker images to wal2json 1.0 https://issues.jboss.org/browse/DBZ-750[DBZ-750]
* Provide Maven profile so that the MySQL module test suite can be run using old and new parser https://issues.jboss.org/browse/DBZ-734[DBZ-734]

[[release-0-7-5]]
== *Release 0.7.5* _(March 20th, 2018)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12337159[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 1.0.1 and has been tested with version 1.0.1 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.7.5 from any of the earlier 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.7.5 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.7.5 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

The MySQL connector in Debezium 0.7.3 and 0.7.4 was creating database history topic with an infinite time-based log retention but a broker default one for topic size log retention.
This was fixed in https://issues.jboss.org/browse/DBZ-663[DBZ-663].
See our https://debezium.io/blog/2018/03/16/note-on-database-history-topic-configuration/[blogpost] for more details,
in particular how you should adjust your database history topic configuration, if you're affected by this issue.

MySQL snapshot JMX metrics were removed after the snapshot was completed.
This was changed in https://issues.jboss.org/browse/DBZ-640[DBZ-640] and the metrics are available till next connector restart.

=== New Features

This release includes the following new features:

* Keep SnapshotReaderMetrics bean registered after snapshot completed https://issues.jboss.org/browse/DBZ-640[DBZ-640]
* Cache replaced topic names and shard ids in ByLogicalTableRouter SMT https://issues.jboss.org/browse/DBZ-655[DBZ-655]
* Filter out useless commands from the history topic https://issues.jboss.org/browse/DBZ-661[DBZ-661]
* Apache Kafka 1.0.1 updates https://issues.jboss.org/browse/DBZ-647[DBZ-647]

=== Fixes

This release includes the following fixes:

* io.debezium.text.ParsingException for TokuDB table https://issues.jboss.org/browse/DBZ-646[DBZ-646]
* MongoDB connector continues to try to connect to invalid host even after deletion https://issues.jboss.org/browse/DBZ-648[DBZ-648]
* Streaming stopped due to JsonParseException https://issues.jboss.org/browse/DBZ-657[DBZ-657]
* 'ALTER TABLE tbl_name ADD CONSTRAINT UNIQUE KEY key_name (colname)' throwing exception https://issues.jboss.org/browse/DBZ-660[DBZ-660]
* Missing setting for the automatic history topic creation https://issues.jboss.org/browse/DBZ-663[DBZ-663]
* EmbeddedEngine passes time of last commit to policy, not time since https://issues.jboss.org/browse/DBZ-665[DBZ-665]

=== Other changes

This release includes also other changes:

* "snapshot" attribute should be false instead of null for events based on the binlog https://issues.jboss.org/browse/DBZ-592[DBZ-592]
* Describe limitations of wal2json version currently used on RDS https://issues.jboss.org/browse/DBZ-619[DBZ-619]

[[release-0-7-4]]
== *Release 0.7.4* _(March 7th, 2018)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12336214[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 1.0.0 and has been tested with version 1.0.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.7.4 from any of the earlier 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.7.4 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.7.4 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

`NUMERIC` and geo-spatial schema types were optional regardless of database column configuration. This was fixed in https://issues.jboss.org/browse/DBZ-635[DBZ-635].

PostgresSQL decoder plug-in now uses text to transfer decimal values instead of double - https://issues.jboss.org/browse/DBZ-351[DBZ-351].
Debezium is backward compatible with the old version.
It is thus necessary first to upgrade Debezium and after that upgrade logical decoder plug-in.


=== New Features

This release includes the following new features:

* Provide MySQL snapshot mode that does not require table locks https://issues.jboss.org/browse/DBZ-602[DBZ-602]
* Add support for columns of type "bytea" https://issues.jboss.org/browse/DBZ-605[DBZ-605]
* Add string as an option for decimal.handling.mode https://issues.jboss.org/browse/DBZ-611[DBZ-611]
* Support CREATE TABLE statements with PARTITION ... ENGINE=InnoDB https://issues.jboss.org/browse/DBZ-641[DBZ-641]
* Document VariableScaleDecimal in PG connector docs https://issues.jboss.org/browse/DBZ-631[DBZ-631]
* Propagate schema validator by passing AvroValidator instance instead of Function<String, String> https://issues.jboss.org/browse/DBZ-626[DBZ-626]
* Move MAX_QUEUE_SIZE, MAX_BATCH_SIZE and POLL_INTERVAL_MS to CommonConnectorConfig https://issues.jboss.org/browse/DBZ-628[DBZ-628]
* Unify common start-up logic across connectors https://issues.jboss.org/browse/DBZ-630[DBZ-630]
* Removing unused code from database history classes https://issues.jboss.org/browse/DBZ-632[DBZ-632]

=== Fixes

This release includes the following fixes:

* Numeric datatype is transferred with lost precision https://issues.jboss.org/browse/DBZ-351[DBZ-351]
* Cannot Serialize NaN value(numeric field) in Postgres https://issues.jboss.org/browse/DBZ-606[DBZ-606]
* Decimal datatype DDL issues https://issues.jboss.org/browse/DBZ-615[DBZ-615]
* Avoid NPE if confirmed_flush_lsn is null https://issues.jboss.org/browse/DBZ-623[DBZ-623]
* REAL column values are omitted if value is an exact integer https://issues.jboss.org/browse/DBZ-625[DBZ-625]
* Fix intermittent error in BinlogReaderIT https://issues.jboss.org/browse/DBZ-629[DBZ-629]
* Schema for NUMERIC and geo-spatial array columns shouldn't be optional by default https://issues.jboss.org/browse/DBZ-635[DBZ-635]
* Fix typo in README of debezium/connect-base image https://issues.jboss.org/browse/DBZ-636[DBZ-636]
* Avoid repeated creation of Envelope schema https://issues.jboss.org/browse/DBZ-620[DBZ-620]

[[release-0-7-3]]
== *Release 0.7.3* _(February 14th, 2018)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12336643[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 1.0.0 and has been tested with version 1.0.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.7.3 from any of the earlier 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.7.3 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.7.3 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

A new namespace for parameters was https://issues.jboss.org/browse/DBZ-576[created] - `internal` - that is used for parameters that are not documented and should not be used as they are subject of changes without warning.
As a result of this change the undocumented parameter `database.history.ddl.filter` was renamed to `internal.database.history.ddl.filter`.

OpenShift deployment now uses templates and images from [Strimzi project](https://issues.jboss.org/browse/DBZ-545).

=== New Features

This release includes the following new features:

* MySQL connector should automatically create database history topic https://issues.jboss.org/browse/DBZ-278[DBZ-278]
* Change OpenShift instructions to use Strimzi https://issues.jboss.org/browse/DBZ-545[DBZ-545]
* Create an internal namespace for configuration options not intended for general usage https://issues.jboss.org/browse/DBZ-576[DBZ-576]
* Make ChainedReader immutable https://issues.jboss.org/browse/DBZ-583[DBZ-583]
* Snapshots are not interruptable with the Postgres connector https://issues.jboss.org/browse/DBZ-586[DBZ-586]
* Add optional field with Debezium version to "source" element of messages https://issues.jboss.org/browse/DBZ-593[DBZ-593]
* Add the ability to control the strategy for committing offsets by the offset store https://issues.jboss.org/browse/DBZ-537[DBZ-537]
* Create support for arrays of PostGIS types https://issues.jboss.org/browse/DBZ-571[DBZ-571]
* Add option for controlling whether to produce tombstone records on DELETE operations https://issues.jboss.org/browse/DBZ-582[DBZ-582]
* Add example for using the MongoDB event flattening SMT https://issues.jboss.org/browse/DBZ-567[DBZ-567]
* Prefix the names of all threads spawned by Debezium with "debezium-" https://issues.jboss.org/browse/DBZ-587[DBZ-587]

=== Fixes

This release includes the following fixes:

* Force DBZ to commit regularly https://issues.jboss.org/browse/DBZ-220[DBZ-220]
* Carry over SourceInfo.restartEventsToSkip to next binlog file handling cause binlog events are not written to kafka https://issues.jboss.org/browse/DBZ-572[DBZ-572]
* Numeric arrays not handled correctly https://issues.jboss.org/browse/DBZ-577[DBZ-577]
* Debezium skipping binlog events silently https://issues.jboss.org/browse/DBZ-588[DBZ-588]
* Stop the connector if WALs to continue from aren't available https://issues.jboss.org/browse/DBZ-590[DBZ-590]
* Producer thread of DB history topic leaks after connector shut-down https://issues.jboss.org/browse/DBZ-595[DBZ-595]
* Integration tests should have completely isolated environment and configuration/setup files https://issues.jboss.org/browse/DBZ-300[DBZ-300]
* MongoDB integration tests should have completely isolated environment and configuration/setup files https://issues.jboss.org/browse/DBZ-579[DBZ-579]
* Extract a separate change event class to be re-used across connectors https://issues.jboss.org/browse/DBZ-580[DBZ-580]
* Propagate producer errors to Kafka Connect in MongoDB connector https://issues.jboss.org/browse/DBZ-581[DBZ-581]
* Shutdown thread pool used for MongoDB snaphots once it's not needed anymore https://issues.jboss.org/browse/DBZ-594[DBZ-594]
* Refactor type and array handling for Postgres https://issues.jboss.org/browse/DBZ-609[DBZ-609]
* Avoid unneccessary schema refreshs https://issues.jboss.org/browse/DBZ-616[DBZ-616]
* Incorrect type retrieved by stream producer for column TIMESTAMP (0) WITH TIME ZONE https://issues.jboss.org/browse/DBZ-618[DBZ-618]

[[release-0-7-2]]
== *Release 0.7.2* _(January 25th, 2018)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?version=12336456&projectId=12317320[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 1.0.0 and has been tested with version 1.0.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.7.2 from any of the earlier 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.7.2 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.7.2 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.

=== New Features

This release includes the following new features:

* As a Debezium user, I would like MySQL Connector to support 'Spatial' data types https://issues.jboss.org/browse/DBZ-208[DBZ-208]
* Allow easy consumption of MongoDB CDC events by other connectors https://issues.jboss.org/browse/DBZ-409[DBZ-409]
* New snapshotting mode for recovery of DB history topic https://issues.jboss.org/browse/DBZ-443[DBZ-443]
* Add support for Postgres VARCHAR array columns https://issues.jboss.org/browse/DBZ-506[DBZ-506]
* Unified Geometry type support https://issues.jboss.org/browse/DBZ-507[DBZ-507]
* Add support for "snapshot.select.statement.overrides" option for Postgres https://issues.jboss.org/browse/DBZ-510[DBZ-510]
* Make PostGIS optional in Postgres Docker images https://issues.jboss.org/browse/DBZ-526[DBZ-526]
* Provide an option to only store DDL statements referring to captured tables in DB history topic https://issues.jboss.org/browse/DBZ-541[DBZ-541]
* Add ToC to tutorial and make section captions linkable https://issues.jboss.org/browse/DBZ-369[DBZ-369]
* Remove Zulu JDK images https://issues.jboss.org/browse/DBZ-449[DBZ-449]
* Add example for sending CDC events to Elasticsearch https://issues.jboss.org/browse/DBZ-502[DBZ-502]
* Adapt examples to MongoDB 3.6 https://issues.jboss.org/browse/DBZ-509[DBZ-509]
* Backport add-ons definition from add-ons repo https://issues.jboss.org/browse/DBZ-520[DBZ-520]
* Set up pull request build job for testing the PG connector with wal2json https://issues.jboss.org/browse/DBZ-568[DBZ-568]

=== Fixes

This release includes the following fixes:

* Debezium MySQL connector only works for lower-case table names on case-insensitive file systems https://issues.jboss.org/browse/DBZ-392[DBZ-392]
* Numbers after decimal point are different between source and destination https://issues.jboss.org/browse/DBZ-423[DBZ-423]
* Fix support for date arrays https://issues.jboss.org/browse/DBZ-494[DBZ-494]
* Changes in type contraints will not trigger new schema https://issues.jboss.org/browse/DBZ-504[DBZ-504]
* Task is still running after connector is paused https://issues.jboss.org/browse/DBZ-516[DBZ-516]
* NPE happened for PAUSED task https://issues.jboss.org/browse/DBZ-519[DBZ-519]
* Possibility of commit LSN before record is consumed/notified https://issues.jboss.org/browse/DBZ-521[DBZ-521]
* Snapshot fails when encountering null MySQL TIME fields https://issues.jboss.org/browse/DBZ-522[DBZ-522]
* Debezium unable to parse DDLs in MySql with RESTRICT contstraint https://issues.jboss.org/browse/DBZ-524[DBZ-524]
* DateTimeFormatter Exception in wal2json https://issues.jboss.org/browse/DBZ-525[DBZ-525]
* Multiple partitions does not work in ALTER TABLE https://issues.jboss.org/browse/DBZ-530[DBZ-530]
* Incorrect lookup in List in MySqlDdlParser.parseCreateView https://issues.jboss.org/browse/DBZ-534[DBZ-534]
* Improve invalid DDL statement logging https://issues.jboss.org/browse/DBZ-538[DBZ-538]
* Fix required protobuf version in protobuf decoder documentation https://issues.jboss.org/browse/DBZ-542[DBZ-542]
* EmbeddedEngine strips settings required to use KafkaOffsetBackingStore https://issues.jboss.org/browse/DBZ-555[DBZ-555]
* Handling of date arrays collides with handling of type changes via wal2json https://issues.jboss.org/browse/DBZ-558[DBZ-558]
* ROLLBACK to savepoint cannot be parsed https://issues.jboss.org/browse/DBZ-411[DBZ-411]
* Avoid usage of deprecated numeric types constructors https://issues.jboss.org/browse/DBZ-455[DBZ-455]
* Don't add source and JavaDoc JARs to Kafka image https://issues.jboss.org/browse/DBZ-489[DBZ-489]

[[release-0-7-1]]
== *Release 0.7.1* _(December 20th, 2017)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?version=12336215&projectId=12317320[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 1.0.0 and has been tested with version 1.0.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.7.1 from any of the earlier 0.7.x, 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.7.1 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.7.1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

If you are using our docker images then do not forget to pull them fresh from Docker registry.

=== Breaking changes

There are no breaking changes in this release.

=== New Features

This release includes the following new features:

* Provide a wal2json plug-in mode enforcing RDS environment https://issues.jboss.org/browse/DBZ-517[DBZ-517]

=== Fixes

This release includes the following fixes:

* For old connector OID should be used to detect schema change https://issues.jboss.org/browse/DBZ-512[DBZ-512]
* AWS RDS Postgresql 9.6.5 not supporting "include-not-null" = "true" in connector setup https://issues.jboss.org/browse/DBZ-513[DBZ-513]
* RecordsStreamProducerIT.shouldNotStartAfterStop can make subsequent test dependent https://issues.jboss.org/browse/DBZ-518[DBZ-518]

== Known issues
* PostgreSQL Connector does not detect schema changes in type constraints - e.g. the length of `array` datatype https://issues.jboss.org/browse/DBZ-504[DBZ-504]

[[release-0-7-0]]
== *Release 0.7.0* _(December 15th, 2017)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?version=12335366&projectId=12317320[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 1.0.0 and has been tested with version 1.0.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.7.0 from any of the earlier 0.6.x, 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.7.0 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.7.0 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release includes the following changes that can affect existing installations:

* Change default setting for BIGINT UNSIGNED handling https://issues.jboss.org/browse/DBZ-461[DBZ-461];
`UNSIGNED BIGINT` is treated by default as `int64`, not as `Decimal` before. Set `bigint.unsigned.handling.mode` if you need to continue with the original behaviour.
* Invalid value for HourOfDay ConnectException when the value of MySQL TIME filed is above 23:59:59 https://issues.jboss.org/browse/DBZ-342[DBZ-342]; The default mapping for MySQL TIME(0-3) columns has changed. Such columns can store values from -838:59:59.000000 to 838:59:59.000000, which cannot be stored as milliseconds in an int32 field (the previous default mapping).
Hence the default mapping has changed to int64 and the semantic type io.debezium.time.MicroTime, i.e. values represent microseconds. +
If you prefer to keep the previous mapping (which only should be done if it's guaranteed that no values are stored in that column whose milliseconds value exceeds int32), you can do so by specifying the connector option time.precision.mode=adaptive (see the connector documentation for further details). +
This change does not affect other connectors.
* Postgres connectors stops to work after concurrent schema changes and updates https://issues.jboss.org/browse/DBZ-379[DBZ-379]; PostgreSQL connector was using JDBC metadata to get additional type information when it was processing logical events.
This could lead to a race condition when database schema was updated and Debezium was still processing events with old schema structure. +
To mitigate the problem a new version of https://github.com/debezium/postgres-decoderbufs[Protocol Buffers decoder plugin] was introduced that passes additional type metadata with each event.
The connector is backward compatible with the old decoder plugin (using the original approach) but we strongly recommend to upgrade it to the latest one as soon as possible. +
The race condition issue can still happen when primary key structure is changed for the table as this information is still obtained from JDBC metadata.
To properly handle primary key change you should follow the rules
** Application should be placed in a _read-only_ mode, not writing any new data actively
** PostgreSQL connector must consume all remaining events from the database
** Primary key change is executed
** Application can switch back to regular mode
* Hardcoded schema version overrides schema registry version https://issues.jboss.org/browse/DBZ-466[DBZ-466]; The schema version returned for CDC message values (schema type dbserver1.inventory.customers.Envelope) has changed. While always `1` was returned in earlier versions, the schema version as managed by the schema registry will be returned in case the Avro serializer/deserializer is used. `Null` will be returned when using the JSON serializer/deserializer. Note that the schema version is only set during Avro message serialization, i.e. an SMT applied on the source side will also get null when querying for the schema version, as SMTs will be applied before the serialization.

=== New Features

This release includes the following new features:

* PostgreSQL connector should work on Amazon RDS and be able to use the available plugin https://issues.jboss.org/browse/DBZ-256[DBZ-256]
* Build Debezium against Kafka 1.0.0 https://issues.jboss.org/browse/DBZ-432[DBZ-432]
* Build Debezium images with Kafka 1.0.0 https://issues.jboss.org/browse/DBZ-433[DBZ-433]
* Protobuf message should contain type modifiers https://issues.jboss.org/browse/DBZ-485[DBZ-485]
* Protobuf message should contain optional flags https://issues.jboss.org/browse/DBZ-486[DBZ-486]
* Better support for large append-only tables by making the snapshotting process restartable https://issues.jboss.org/browse/DBZ-349[DBZ-349]
* Support new wal2json type specifiers https://issues.jboss.org/browse/DBZ-453[DBZ-453]
* Optionally return raw value for unsupported column types https://issues.jboss.org/browse/DBZ-498[DBZ-498]
* Provide Postgres example image for 0.7 https://issues.jboss.org/browse/DBZ-382[DBZ-382]
* Create an automated build for Postgres example image in Docker Hub https://issues.jboss.org/browse/DBZ-383[DBZ-383]
* Move configuration of ProtoBuf code generation to Postgres module https://issues.jboss.org/browse/DBZ-416[DBZ-416]
* Provide MongoDB example image for Debezium 0.7 https://issues.jboss.org/browse/DBZ-451[DBZ-451]
* Upgrade to Confluent Platform 4.0 https://issues.jboss.org/browse/DBZ-492[DBZ-492]
* Set up CI job for testing Postgres with new wal2json type identifiers https://issues.jboss.org/browse/DBZ-495[DBZ-495]
* Change PostgreSQL connector to support multiple plugins https://issues.jboss.org/browse/DBZ-257[DBZ-257]
* PostgreSQL connector should support the wal2json logical decoding plugin https://issues.jboss.org/browse/DBZ-258[DBZ-258]
* Provide instructions for using Debezium on Minishift https://issues.jboss.org/browse/DBZ-364[DBZ-364]
* Modify BinlogReader to process transactions via buffer https://issues.jboss.org/browse/DBZ-405[DBZ-405]
* Modify BinlogReader to support transactions of unlimited size https://issues.jboss.org/browse/DBZ-406[DBZ-406]

=== Fixes

This release includes the following fixes:

* Data are read from the binlog and not written into Kafka https://issues.jboss.org/browse/DBZ-390[DBZ-390]
* MySQL connector may not read database history to end https://issues.jboss.org/browse/DBZ-464[DBZ-464]
* connect-base image advertises wrong port by default https://issues.jboss.org/browse/DBZ-467[DBZ-467]
* INSERT statements being written to db history topic https://issues.jboss.org/browse/DBZ-469[DBZ-469]
* MySQL Connector does not handle properly startup/shutdown https://issues.jboss.org/browse/DBZ-473[DBZ-473]
* Cannot parse NOT NULL COLLATE in DDL https://issues.jboss.org/browse/DBZ-474[DBZ-474]
* Failed to parse the sql statement of RENAME user https://issues.jboss.org/browse/DBZ-475[DBZ-475]
* Exception when parsing enum field with escaped characters values https://issues.jboss.org/browse/DBZ-476[DBZ-476]
* All to insert null value into numeric array columns https://issues.jboss.org/browse/DBZ-478[DBZ-478]
* produceStrings method slow down on sending messages https://issues.jboss.org/browse/DBZ-479[DBZ-479]
* Failing unit tests when run in EST timezone https://issues.jboss.org/browse/DBZ-491[DBZ-491]
* PostgresConnector falls with RejectedExecutionException https://issues.jboss.org/browse/DBZ-501[DBZ-501]
* Docker images cannot be re-built when a new version of ZooKeeper/Kafka is released https://issues.jboss.org/browse/DBZ-503[DBZ-503]
* Insert ids as long instead of float for MongoDB example image https://issues.jboss.org/browse/DBZ-470[DBZ-470]
* Port changes in 0.6 Docker files into 0.7 files https://issues.jboss.org/browse/DBZ-463[DBZ-463]
* Add check to release process to make sure all issues are assigned to a component https://issues.jboss.org/browse/DBZ-468[DBZ-468]
* Document requirement for database history topic to be not partitioned https://issues.jboss.org/browse/DBZ-482[DBZ-482]
* Remove dead code from MySqlSchema https://issues.jboss.org/browse/DBZ-483[DBZ-483]
* Remove redundant calls to pfree https://issues.jboss.org/browse/DBZ-496[DBZ-496]

== Known issues
* PostgreSQL Connector does not detect schema changes in type constraints - e.g. the length of `array` datatype https://issues.jboss.org/browse/DBZ-504[DBZ-504]

[[release-0-6-2]]
== *Release 0.6.2* _(November 15th, 2017)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?version=12335989&projectId=12317320[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 0.11.0.1 and has been tested with version 0.11.0.1 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.6.2 from any of the earlier 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.6.2 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.6.2 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

* Timestamp field not handle time zone correctly https://issues.jboss.org/projects/DBZ/issues/DBZ-260[DBZ-260]
** This issue finally fixes a long standing bug in timestamp timezone handling. If there is a client that was depending on this bug to provide value without the correct offset then it has to be fixed.

=== New Features

This release includes the following new features:

* Log current position in MySQL binlog to simplify debugging https://issues.jboss.org/projects/DBZ/issues/DBZ-401[DBZ-401]
* Support PostgreSQL 10 https://issues.jboss.org/projects/DBZ/issues/DBZ-424[DBZ-424]
* Create a Docker image for PostgreSQL 10 https://issues.jboss.org/projects/DBZ/issues/DBZ-426[DBZ-426]
* Add example for using Avro messages https://issues.jboss.org/projects/DBZ/issues/DBZ-430[DBZ-430]
* Make postGIS dependency optional https://issues.jboss.org/projects/DBZ/issues/DBZ-445[DBZ-445]
* Avro console-consumer example in docs https://issues.jboss.org/projects/DBZ/issues/DBZ-458[DBZ-458]
* Docker micro version tags (e.g., 0.6.1) https://issues.jboss.org/projects/DBZ/issues/DBZ-418[DBZ-418]
* Create a CI job for testing with PostgreSQL 10 https://issues.jboss.org/projects/DBZ/issues/DBZ-427[DBZ-427]
* Upgrade dependencies in Docker images to match Kafka 0.11.0.1 https://issues.jboss.org/projects/DBZ/issues/DBZ-450[DBZ-450]

=== Fixes

This release includes the following fixes:

* Connector fails and stops when coming across corrupt event https://issues.jboss.org/projects/DBZ/issues/DBZ-217[DBZ-217]
* [Postgres] Interval column causes exception during handling of DELETE https://issues.jboss.org/projects/DBZ/issues/DBZ-259[DBZ-259]
* The scope of the Kafka Connect dependency should be "provided" https://issues.jboss.org/projects/DBZ/issues/DBZ-285[DBZ-285]
* KafkaCluster#withKafkaConfiguration() does not work https://issues.jboss.org/projects/DBZ/issues/DBZ-323[DBZ-323]
* MySQL connector "initial_only" snapshot mode results in CPU spike from ConnectorTask polling https://issues.jboss.org/projects/DBZ/issues/DBZ-396[DBZ-396]
* Allow to omit COLUMN word in ALTER TABLE MODIFY/ALTER/CHANGE https://issues.jboss.org/projects/DBZ/issues/DBZ-412[DBZ-412]
* MySQL connector should handle stored procedure definitions https://issues.jboss.org/projects/DBZ/issues/DBZ-415[DBZ-415]
* Support constraints without name in DDL statement https://issues.jboss.org/projects/DBZ/issues/DBZ-419[DBZ-419]
* Short field not null throw an exception https://issues.jboss.org/projects/DBZ/issues/DBZ-422[DBZ-422]
* ALTER TABLE cannot change default value of column https://issues.jboss.org/projects/DBZ/issues/DBZ-425[DBZ-425]
* DDL containing text column with length specification cannot be parsed https://issues.jboss.org/projects/DBZ/issues/DBZ-428[DBZ-428]
* Integer column with negative default value causes MySQL connector to crash https://issues.jboss.org/projects/DBZ/issues/DBZ-429[DBZ-429]
* MySQL procedure parser handles strings and keywords as same tokens https://issues.jboss.org/projects/DBZ/issues/DBZ-437[DBZ-437]
* Mongo initial sync misses records with initial.sync.max.threads > 1 https://issues.jboss.org/projects/DBZ/issues/DBZ-438[DBZ-438]
* Can't parse DDL containing PRECISION clause without parameters https://issues.jboss.org/projects/DBZ/issues/DBZ-439[DBZ-439]
* Task restart triggers MBean to register twice https://issues.jboss.org/projects/DBZ/issues/DBZ-447[DBZ-447]
* Remove slowness in KafkaDatabaseHistoryTest https://issues.jboss.org/projects/DBZ/issues/DBZ-456[DBZ-456]


[[release-0-6-1]]
== *Release 0.6.1* _(October 26th, 2017)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?version=12335619&projectId=12317320[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 0.11.0.1 and has been tested with version 0.11.0.1 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.6.1 from any of the earlier 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.6.1 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.6.1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

There should be no breaking changes in this relese.

=== New Features

This release includes the following new features:

* Support for UNSIGNED BIGINT to not be treated as byte[] https://issues.jboss.org/projects/DBZ/issues/DBZ-363[DBZ-363]
* Make Debezium build on Java 9 https://issues.jboss.org/projects/DBZ/issues/DBZ-227[DBZ-227]
* Add a test for "PAGE_CHECKSUM" DDL option https://issues.jboss.org/projects/DBZ/issues/DBZ-336[DBZ-336]
* Provide tutorial Docker Compose files for MongoDB and Postgres https://issues.jboss.org/projects/DBZ/issues/DBZ-361[DBZ-361]
* Upgrade to latest Kafka 0.11.x https://issues.jboss.org/projects/DBZ/issues/DBZ-367[DBZ-367]
* Prevent warning when building the plug-ins https://issues.jboss.org/projects/DBZ/issues/DBZ-370[DBZ-370]
* Replace hard-coded version references with variables https://issues.jboss.org/projects/DBZ/issues/DBZ-371[DBZ-371]
* Upgrade to latest version of mysql-binlog-connector-java https://issues.jboss.org/projects/DBZ/issues/DBZ-398[DBZ-398]
* Create wal2json CI job https://issues.jboss.org/projects/DBZ/issues/DBZ-403[DBZ-403]
* Travis jobs tests are failing due to Postgres https://issues.jboss.org/projects/DBZ/issues/DBZ-404[DBZ-404]

=== Fixes

This release includes the following fixes:

* Avoid NullPointerException when closing MySQL connector after another error https://issues.jboss.org/projects/DBZ/issues/DBZ-378[DBZ-378]
* RecordsStreamProducer#streamChanges() can die on an exception without failing the connector https://issues.jboss.org/projects/DBZ/issues/DBZ-380[DBZ-380]
* Encoding to JSON does not support all MongoDB types https://issues.jboss.org/projects/DBZ/issues/DBZ-385[DBZ-385]
* MySQL connector does not filter out DROP TEMP TABLE statements from DB history topic https://issues.jboss.org/projects/DBZ/issues/DBZ-395[DBZ-395]
* Binlog Reader is registering MXBean when using "initial_only" snapshot mode https://issues.jboss.org/projects/DBZ/issues/DBZ-402[DBZ-402]
* A column named `column`, even when properly escaped, causes exception https://issues.jboss.org/projects/DBZ/issues/DBZ-408[DBZ-408]


[[release-0-6-0]]
== *Release 0.6.0* _(September 21st, 2017)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?version=12331386&projectId=12317320[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 0.11.0.0 and has been tested with version 0.11.0.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.6.0 from any of the earlier 0.5.x, 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.6.0 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.6.0 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release includes the following change that affects existing installations that capture MongoDB:

* Add support for different MongoDB id types in key struct https://issues.jboss.org/projects/DBZ/issues/DBZ-306[DBZ-306];
the key payload continues to be a string in all cases, but it will be created using MongoDB's extended JSON serialization (strict mode).
So e.g. an int key will result in a key payload such as `{ "id" : "1234" }`, a String key will yield `{ "id" : "\"1234\"" }` and an `ObjectId` key will yield `{ "id" : "{\"$oid\" : \"596e275826f08b2730779e1f\"}" }`.
This allows to restore the key into the correct type from the serialized representation.
Note that the id field has been renamed from "_id" into "id".
This is to be consistent with the format used by the other Debezium connectors;
also it allows you to tell apart messages written by earlier Debezium versions from messages written by 0.6 and beyond.

=== New Features

This release includes the following new features:

* Use new Kafka 0.10 properties for listeners and advertised listeners https://issues.jboss.org/projects/DBZ/issues/DBZ-39[DBZ-39]
* Add docker-compose handling for Debezium tutorial https://issues.jboss.org/projects/DBZ/issues/DBZ-127[DBZ-127]
* Topic configuration requirements are not clearly documented https://issues.jboss.org/projects/DBZ/issues/DBZ-241[DBZ-241]
* Upgrade Docker images to Kafka 0.11.0.0 https://issues.jboss.org/projects/DBZ/issues/DBZ-305[DBZ-305]
* add support for different mongodb _id types in key struct https://issues.jboss.org/projects/DBZ/issues/DBZ-306[DBZ-306]
* Add SMT implementation to convert CDC event structure to more traditional row state structure https://issues.jboss.org/projects/DBZ/issues/DBZ-226[DBZ-226]
* Support SSL connection to Mongodb https://issues.jboss.org/projects/DBZ/issues/DBZ-343[DBZ-343]
* Support DEC and FIXED type for mysql ddl parser https://issues.jboss.org/projects/DBZ/issues/DBZ-359[DBZ-359]

=== Fixes

This release includes the following fixes:

* MySQL snapshotter is not guaranteed to give a consistent snapshot https://issues.jboss.org/projects/DBZ/issues/DBZ-210[DBZ-210]
* MySQL connector stops consuming data from binlog after server restart https://issues.jboss.org/projects/DBZ/issues/DBZ-219[DBZ-219]
* Warnings and notifications from PostgreSQL are ignored by the connector https://issues.jboss.org/projects/DBZ/issues/DBZ-279[DBZ-279]
* BigDecimal has mismatching scale value for given Decimal schema error. https://issues.jboss.org/projects/DBZ/issues/DBZ-318[DBZ-318]
* Views in database stop PostgreSQL connector https://issues.jboss.org/projects/DBZ/issues/DBZ-319[DBZ-319]
* Don't pass database history properties to the JDBC connection https://issues.jboss.org/projects/DBZ/issues/DBZ-333[DBZ-333]
* Sanitize readings from database history topic https://issues.jboss.org/projects/DBZ/issues/DBZ-341[DBZ-341]
* Support UNION for ALTER TABLE https://issues.jboss.org/projects/DBZ/issues/DBZ-346[DBZ-346]
* Debezium fails to start when schema history topic contains unparseable SQL https://issues.jboss.org/projects/DBZ/issues/DBZ-347[DBZ-347]
* JDBC Connection is not closed after schema refresh https://issues.jboss.org/projects/DBZ/issues/DBZ-356[DBZ-356]
* MySQL integration tests should have completely isolated environment and configuration/setup files https://issues.jboss.org/projects/DBZ/issues/DBZ-304[DBZ-304]


[[release-0-5-2]]
== *Release 0.5.2* _(August 17, 2017)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?version=12334601&projectId=12317320[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 0.10.2.0 and has been tested with version 0.10.2.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.5.2 from any of the earlier 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.5.2 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.5.2 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

There should be no breaking changes in this relese.

=== New Features

This release includes the following new features:

* Mongo Connector: Add "database.whitelist" and "database.blacklist" configuration options https://issues.jboss.org/projects/DBZ/issues/DBZ-302[DBZ-302]
* Provide a Dockerfile to build images from latest released snapshot https://issues.jboss.org/projects/DBZ/issues/DBZ-320[DBZ-320]
* Support decimal handling mode for Postgres https://issues.jboss.org/projects/DBZ/issues/DBZ-337[DBZ-337]
* Enable and show usage of Avro converters (https://issues.jboss.org/projects/DBZ/issues/DBZ-271)
* Keep TCP connection alive for Postgres https://issues.jboss.org/projects/DBZ/issues/DBZ-286[DBZ-286]
* Support "PAGE_CHECKSUM=1" option for MySQL tables https://issues.jboss.org/projects/DBZ/issues/DBZ-324[DBZ-324]

=== Fixes

This release includes the following fixes:

* Images cannot run on OpenShift online https://issues.jboss.org/projects/DBZ/issues/DBZ-267[DBZ-267]
* NPE when processing null value in POINT column https://issuesjbossorg/projects/DBZ/issues/DBZ-284[DBZ-284]
* Postgres Connector: error of mismatching scale value for Decimal and Numeric data types https://issues.jboss.org/projects/DBZ/issues/DBZ-287[DBZ-287]
* Postgres connector fails with array columns https://issues.jboss.org/projects/DBZ/issues/DBZ-297[DBZ-297]
* Postgres connector fails with quoted type names https://issues.jboss.org/projects/DBZ/issues/DBZ-298[DBZ-298]
* LogicalTableRouter SMT uses wrong comparison for validation https://issues.jboss.org/projects/DBZ/issues/DBZ-326[DBZ-326]
* LogicalTableRouter SMT has a broken key replacement validation https://issues.jboss.org/projects/DBZ/issues/DBZ-327[DBZ-327]
* Pre-compile and simplify some regular expressions https://issues.jboss.org/projects/DBZ/issues/DBZ-311[DBZ-311]
* JMX metrics for MySQL connector should be documented https://issues.jboss.org/projects/DBZ/issues/DBZ-293[DBZ-293]
* PostgreSQL integration tests should have completely isolated environment and configuration/setup files https://issues.jboss.org/projects/DBZ/issues/DBZ-301[DBZ-301]
* Move snapshot Dockerfile into separated directory https://issues.jboss.org/projects/DBZ/issues/DBZ-321[DBZ-321]
* Cover ByLogicalTableRouter SMT in reference documentation https://issues.jboss.org/projects/DBZ/issues/DBZ-325[DBZ-325]
* Add documentation for JDBC url pass-through properties https://issues.jboss.org/projects/DBZ/issues/DBZ-330[DBZ-330]


[[release-0-5-1]]
== *Release 0.5.1* _(June 9, 2017)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12334135[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 0.10.2.0 and has been tested with version 0.10.2.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.5.1 from any of the earlier 0.4.1, 0.4.0, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.5.0 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.5.1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release includes the following change that affect existing installations which capture system tables:

* MySQL connector should apply database and table filters to system dbs/tables https://issues.jboss.org/projects/DBZ/issues/DBZ-242[DBZ-242]

=== New Features

This release includes the following new features:

* MySQL Connector should support 'Point' data type https://issues.jboss.org/projects/DBZ/issues/DBZ-222[DBZ-222]
* Support tstzrange column type on Postgres https://issues.jboss.org/projects/DBZ/issues/DBZ-280[DBZ-280]

=== Fixes

This release includes the following fixes:

* Control how Debezium connectors maps tables to topics for sharding and other use cases https://issues.jboss.org/projects/DBZ/issues/DBZ-121[DBZ-121]
* MySqlConnector Table and Database recommenders cause timeouts on large instances https://issues.jboss.org/projects/DBZ/issues/DBZ-232[DBZ-232]
* Option to disable SSL certificate validation for PostgreSQL https://issues.jboss.org/projects/DBZ/issues/DBZ-244[DBZ-244]
* Let enum types implement EnumeratedValue https://issues.jboss.org/projects/DBZ/issues/DBZ-262[DBZ-262]
* The  MySQL connector is failing with the DDL statements. https://issues.jboss.org/projects/DBZ/issues/DBZ-198[DBZ-198]
* Correct MongoDB build https://issues.jboss.org/projects/DBZ/issues/DBZ-213[DBZ-213]
* MongoDB connector should handle new primary better https://issues.jboss.org/projects/DBZ/issues/DBZ-214[DBZ-214]
* Validate that database.server.name and database.history.kafka.topic have different values https://issues.jboss.org/projects/DBZ/issues/DBZ-215[DBZ-215]
* When restarting Kafka Connect, we get io.debezium.text.ParsingException https://issues.jboss.org/projects/DBZ/issues/DBZ-216[DBZ-216]
* Postgres connector crash on a database managed by Django https://issues.jboss.org/projects/DBZ/issues/DBZ-223[DBZ-223]
* MySQL Connector doesn't handle any value above '2147483647' for 'INT UNSIGNED' types https://issues.jboss.org/projects/DBZ/issues/DBZ-228[DBZ-228]
* MySqlJdbcContext#userHasPrivileges() is broken for multiple privileges https://issues.jboss.org/projects/DBZ/issues/DBZ-229[DBZ-229]
* Postgres Connector does not work when "sslmode" is "require" https://issues.jboss.org/projects/DBZ/issues/DBZ-238[DBZ-238]
* Test PostgresConnectorIT.shouldSupportSSLParameters is incorrect https://issues.jboss.org/projects/DBZ/issues/DBZ-245[DBZ-245]
* Recommender and default value broken for EnumeratedValue type https://issues.jboss.org/projects/DBZ/issues/DBZ-246[DBZ-246]
* PG connector is CPU consuming  https://issues.jboss.org/projects/DBZ/issues/DBZ-250[DBZ-250]
* MySQL tests are interdependent https://issues.jboss.org/projects/DBZ/issues/DBZ-251[DBZ-251]
* MySQL DDL parser fails on "ANALYZE TABLE" statement  https://issues.jboss.org/projects/DBZ/issues/DBZ-253[DBZ-253]
* Binary fields with trailing "00" are truncated https://issues.jboss.org/projects/DBZ/issues/DBZ-254[DBZ-254]
* Enable Maven repository caching on Travis https://issues.jboss.org/projects/DBZ/issues/DBZ-274[DBZ-274]
* Memory leak and excessive CPU usage when using materialized views https://issues.jboss.org/projects/DBZ/issues/DBZ-277[DBZ-277]
* Postgres task should fail when connection to server is lost https://issues.jboss.org/projects/DBZ/issues/DBZ-281[DBZ-281]
* Fix some wrong textual descriptions of default values https://issues.jboss.org/projects/DBZ/issues/DBZ-282[DBZ-282]
* Apply consistent default value for Postgres port https://issues.jboss.org/projects/DBZ/issues/DBZ-237[DBZ-237]
* Make Docker images run on OpenShift https://issues.jboss.org/projects/DBZ/issues/DBZ-240[DBZ-240]
* Don't mention default value for "database.server.name" https://issues.jboss.org/projects/DBZ/issues/DBZ-243[DBZ-243]

[[release-0-5-0]]
== *Release 0.5.0* _(March 27, 2017)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12334135[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 0.10.2.0 and has been tested with version 0.10.2.0 of the Kafka brokers. See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.5.0 from any of the earlier 0.4.1, 0.4.0, 0.3.x, 0.2.x, or 0.1.x versions, first check the upgrading notes for the version you're using. Gracefully stop the running connector, remove the old plugin files, install the 0.5.0 plugin files, and restart the connector using the same configuration. Upon restart, the 0.5.0 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release includes the following changes that are likely to affect existing installations:

* Upgraded from Kafka 0.10.1.1 to 0.10.2.0. https://issues.jboss.org/projects/DBZ/issues/DBZ-203[DBZ-203]

This release has no breaking changes since the link:release-0-4-1[previous] release.

=== New Features

This release has no new features since the link:release-0-4-1[previous] release.

=== Fixes

This release includes the following fixes relative to the link:release-0-4-1[0.4.1] release:

* MySQL connector now better handles DDL statements with `BEGIN...END` blocks, especially those that use `IF()` functions and `CASE...WHEN` statements. https://issues.jboss.org/projects/DBZ/issues/DBZ-198[DBZ-198]
* MySQL connector handles 2-digit years in `DATETIME`, `DATE`, `TIMESTAMP`, and `YEAR` columns in the same way as MySQL. https://issues.jboss.org/projects/DBZ/issues/DBZ-205[DBZ-205]



[[release-0-4-1]]
== *Release 0.4.1* _(March 17, 2017)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12333486[complete list of issues].

=== Kafka compatibility

This release has been tested with Kafka Connect 0.10.1.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.4.1 from any of the earlier 0.4.0, 0.3.x, 0.2.x, or 0.1.x versions, first check the upgrading notes for the version you're using. Gracefully stop the running connector, remove the old plugin files, install the 0.4.1 plugin files, and restart the connector using the same configuration. Upon restart, the 0.4.1 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release has no breaking changes since the link:release-0-4-0[previous] release.

=== New Features

This release adds/improves to the MySQL connector preliminary support for https://aws.amazon.com/rds/mysql/[Amazon RDS] and https://aws.amazon.com/rds/aurora/[Amazon Aurora (MySQL compatibility)] (see https://issues.jboss.org/projects/DBZ/issues/DBZ-140[DBZ-140]).

=== Fixes

This release includes the following fixes relative to the link:release-0-4-0[0.4.0] release:

* MySQL connector now allows filtering production of DML events by GTIDs. https://issues.jboss.org/projects/DBZ/issues/DBZ-188[DBZ-188]
* Support InnoDB savepoints. https://issues.jboss.org/projects/DBZ/issues/DBZ-196[DBZ-196]
* Corrected MySQL DDL parser. https://issues.jboss.org/projects/DBZ/issues/DBZ-193[DBZ-193] https://issues.jboss.org/projects/DBZ/issues/DBZ-198[DBZ-198]
* Improved handling of MySQL connector's built-in tables. https://issues.jboss.org/projects/DBZ/issues/DBZ-194[DBZ-194]
* MySQL connector properly handles invalid/blank enum literal values. https://issues.jboss.org/projects/DBZ/issues/DBZ-197[DBZ-197]
* MySQL connector properly handles reserved names as column names. https://issues.jboss.org/projects/DBZ/issues/DBZ-200[DBZ-200]
* MongoDB connector properly generates event keys based upon ObjectID for updates. https://issues.jboss.org/projects/DBZ/issues/DBZ-201[DBZ-201]



[[release-0-4-0]]
== *Release 0.4.0* _(February 7, 2017)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12330743[complete list of issues].

=== Kafka compatibility

This release has been tested with Kafka Connect 0.10.1.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.4.0 from any of the earlier 0.3.x, 0.2.x, or 0.1.x versions, first check the upgrading notes for the version you're using. Gracefully stop the running connector, remove the old plugin files, install the 0.4.0 plugin files, and restart the connector using the same configuration. Upon restart, the 0.4.0 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release has no breaking changes since the link:release-0-3-5[previous] release.

=== New Features

This release includes a new link:/docs/connectors/postgresql/[PostgreSQL connector] (see https://issues.jboss.org/projects/DBZ/issues/DBZ-3[DBZ-3]) and adds to the MySQL connector preliminary support for https://aws.amazon.com/rds/mysql/[Amazon RDS] and https://aws.amazon.com/rds/aurora/[Amazon Aurora (MySQL compatibility)] (see https://issues.jboss.org/projects/DBZ/issues/DBZ-140[DBZ-140]).

=== Fixes

This release includes the following fixes relative to the link:release-0-3-6[0.3.6] release:

* Update Kafka dependencies to 0.10.1.1. https://issues.jboss.org/projects/DBZ/issues/DBZ-173[DBZ-173]
* Update MySQL binary log client library to 0.9.0. https://issues.jboss.org/projects/DBZ/issues/DBZ-186[DBZ-186]
* MySQL should apply GTID filters to database history. https://issues.jboss.org/projects/DBZ/issues/DBZ-185[DBZ-185]
* Add names of database and table to the MySQL event metadata. https://issues.jboss.org/projects/DBZ/issues/DBZ-184[DBZ-184]
* Add the MySQL thread ID to the MySQL event metadata. https://issues.jboss.org/projects/DBZ/issues/DBZ-113[DBZ-113]
* Corrects MySQL connector to properly handle timezone information for `TIMESTAMP`. https://issues.jboss.org/projects/DBZ/issues/DBZ-183[DBZ-183]
* Correct MySQL DDL parser to handle `CREATE TRIGGER` command with `DEFINER` clauses. https://issues.jboss.org/projects/DBZ/issues/DBZ-176[DBZ-176]
* Update MongoDB Java driver and MongoDB server versions. https://issues.jboss.org/projects/DBZ/issues/DBZ-187[DBZ-187]
* MongoDB connector should restart incomplete initial sync. https://issues.jboss.org/projects/DBZ/issues/DBZ-182[DBZ-182]
* MySQL and PostgreSQL connectors should load JDBC driver independently of DriverManager. https://issues.jboss.org/projects/DBZ/issues/DBZ-177[DBZ-177]
* Upgrade MySQL binlog client library to support new binlog events added with MySQL 5.7. https://issues.jboss.org/projects/DBZ/issues/DBZ-174[DBZ-174]
* EmbeddedEngine should log all errors. https://issues.jboss.org/projects/DBZ/issues/DBZ-178[DBZ-178]
* PostgreSQL containers' generated Protobuf source moved to separate directory. https://issues.jboss.org/projects/DBZ/issues/DBZ-179[DBZ-179]




[[release-0-3-6]]
== *Release 0.3.6* _(December 21, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12332775[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.6 from any of the earlier 0.3.x, 0.2.x, or 0.1.x versions, first check the upgrading notes for the version you're using. Gracefully stop the running connector, remove the old plugin files, install the 0.3.6 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.6 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release has no breaking changes since the link:release-0-3-5[previous] release.

=== New Features

There are no new features in this release.

=== Fixes

This release includes the following fixes to the link:release-0-3-5[0.3.5] release:

* Deleting a Debezium connector in Kafka Connect no longer causes NPEs. https://issues.jboss.org/projects/DBZ/issues/DBZ-138[DBZ-138]
* MongoDB connector properly connects to a sharded cluster and the primaries for each replica set. https://issues.jboss.org/projects/DBZ/issues/DBZ-170[DBZ-170], https://issues.jboss.org/projects/DBZ/issues/DBZ-167[DBZ-167]
* Stopping the MySQL connector while in the middle of a snapshot now cloasses all MySQL resources. https://issues.jboss.org/projects/DBZ/issues/DBZ-166[DBZ-166]
* MySQL connector properly parses with `ON UPDATE` timestamp values. https://issues.jboss.org/projects/DBZ/issues/DBZ-169[DBZ-169]
* MySQL connector ignores `CREATE FUNCTION` DDL statements. https://issues.jboss.org/projects/DBZ/issues/DBZ-162[DBZ-162]
* MySQL connector properly parses `CREATE TABLE` script with ENUM type and default value 'b'. https://issues.jboss.org/projects/DBZ/issues/DBZ-160[DBZ-160]
* MySQL connector now properly supports `NVARCHAR` columns. https://issues.jboss.org/projects/DBZ/issues/DBZ-142[DBZ-142]
* MySQL connector's snapshot process now uses `SHOW TABLE STATUS ...` rather than `SELECT COUNT(\*)` to obtain an estimate of the number of rows for each table, and can even forgo this step if all tables are to be streamed. https://issues.jboss.org/projects/DBZ/issues/DBZ-152[DBZ-152]
* MySQL connector's snaphot process ignores "artificial" database names exposed by MySQL. https://issues.jboss.org/projects/DBZ/issues/DBZ-164[DBZ-164]
* MySQL connector ignores XA statements appearing in the binlog. https://issues.jboss.org/projects/DBZ/issues/DBZ-168[DBZ-168]
* MySQL connector no longer expects GTID set information on older MySQL versions. https://issues.jboss.org/projects/DBZ/issues/DBZ-161[DBZ-161]
* Improved the EmbeddedEngine and fixed several issues. https://issues.jboss.org/projects/DBZ/issues/DBZ-156[DBZ-156]
* Upgrade to the latest Docker Maven plugin https://issues.jboss.org/projects/DBZ/issues/DBZ-157[DBZ-157]




[[release-0-3-5]]
== *Release 0.3.5* _(November 9, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12332052[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

*We strongly urge all users to upgrade to this release from earlier versions.* In prior versions, the MySQL connector may stop without completing all updates in a transaction, and when the connector restarts it starts with the _next_ transaction and therefore might fail to capture some of the change events in the earlier transaction. This release fixes this issue so that when restarting it will always pick up where it left off, even if that point is in the middle of a transaction. Note that this fix only takes affect once a connector is upgraded and restarted. Also, this fix does not affect or alter the content of change events produced by the connector. See https://issues.jboss.org/projects/DBZ/issues/DBZ-144[the issue] for more details.

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.5 from 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.5 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.5 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release has no backward-incompatible changes since the link:release-0-3-4[0.3.4] release.

=== New Features

* MySQL connector now supports failover to MySQL masters that are slaves of _multiple_ other MySQL servers/clusters, as long as the new MySQL master has all of the transactions (as specified by GTID sets) the connector had previously seen. The connector can be configured to include or exclude particular GTID sources. https://issues.jboss.org/projects/DBZ/issues/DBZ-143[DBZ-143]

=== Fixes

This release includes the following fixes to the link:release-0-3-4[0.3.4] release:

* Restarting MySQL connector will no longer lose or miss events from the previous transaction that was incompletely processed prior to the easlier shutdown. The content of change events are unaffected. https://issues.jboss.org/projects/DBZ/issues/DBZ-144[DBZ-144]
* Shutting down MySQL connector task database and quickly terminating the Kafka Connect process may cause connector to be restarted in a strange state when Kafka Connect is restarted, but this no longer results in a null pointer exception in the Kafka database history. https://issues.jboss.org/projects/DBZ/issues/DBZ-146[DBZ-146]
* MySQL connector now has option to treat `DECIMAL` and `NUMERIC` columns as double values rather than `java.math.BigDecimal` values that are encoded in the messages by Kafka Connect in binary form. This option may result in lost precision, but makes the values far easier for consumers to work with them. https://issues.jboss.org/projects/DBZ/issues/DBZ-147[DBZ-147]
* MySQL connector tests now take into account daylight savings time in the expected results. https://issues.jboss.org/projects/DBZ/issues/DBZ-148[DBZ-148]
* MySQL connector now properly treats `BINARY` columns as binary values rather than string values. https://issues.jboss.org/projects/DBZ/issues/DBZ-149[DBZ-149]
* MySQL connector now handles updates to a row's primary/unique key by issuing `DELETE` and tombstone events for the row with the old key, and then an `INSERT` event for the row with the new key. Previously, the `INSERT` was emitted before the `DELETE`. https://issues.jboss.org/projects/DBZ/issues/DBZ-150[DBZ-150]
* MySQL connector now handles `ENUM` and `SET` literals with parentheses. https://issues.jboss.org/projects/DBZ/issues/DBZ-153[DBZ-153]



[[release-0-3-4]]
== *Release 0.3.4* _(October 25, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12331604[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.4 from 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.4 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.4 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release has one breaking changes since the link:release-0-3-3[0.3.3] release:

* MySQL connector produced change events with a `ts_sec` field that now shows correct timestamp in seconds past epoch as found from the MySQL server events. In previous releases the last 3 digits in this field were truncated. https://issues.jboss.org/projects/DBZ/issues/DBZ-139[DBZ-139]

=== New Features

* MySQL connector has a new `SCHEMA_ONLY` snapshot mode. When the connector starts up for the first time and uses this snapshot mode, the connector captures the current table schemas without reading any data, and then proceeds to read the binlog. The resulting change event streams do not have all the data in the databases, but do include those change events that occurred after the snapshot started. This may be useful for consumers that only need to know the changes since the connector was started. https://issues.jboss.org/projects/DBZ/issues/DBZ-133[DBZ-133]
* MySQL connector supports the MySQL `JSON` datatype. These JSON values are represented as STRING values in the change events, although the name of the field's Kafka Connect schema is `io.debezium.data.Json` to signal to consumers that the string value is actually a JSON document, array, or scalar. https://issues.jboss.org/projects/DBZ/issues/DBZ-126[DBZ-126]
* MySQL connector metrics are exposed via JMX. All of the Debezium Docker images can expose the JMX data via a custom port. See the link:/docs/monitoring/[Monitoring Debezium] document for more details. https://issues.jboss.org/projects/DBZ/issues/DBZ-134[DBZ-134]

=== Fixes

This release includes no other fixes.



[[release-0-3-3]]
== *Release 0.3.3* _(October 18, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12331604[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.3 from 0.3.2, 0.3.1, 0.3.0, 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.3 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.3 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release includes no breaking changes since the link:release-0-3-2[0.3.2] release.

=== New Features

This release includes no new features since the link:release-0-3-2[0.3.2] release.

=== Fixes

This release includes the following fixes to the link:release-0-3-2[0.3.2] release:

* MySQL connector now works with MySQL 5.5. https://issues.jboss.org/projects/DBZ/issues/DBZ-115[DBZ-115]
* MySQL connector now handles `BIT(n)` column values. https://issues.jboss.org/projects/DBZ/issues/DBZ-123[DBZ-123]
* MySQL connector supports failing over based on subset of GTIDs. https://issues.jboss.org/projects/DBZ/issues/DBZ-129[DBZ-129]
* MySQL connector processes GTIDs with line feeds and carriage returns. https://issues.jboss.org/projects/DBZ/issues/DBZ-135[DBZ-135]
* MySQL connector has improved output of GTIDs and status when reading the binary log. https://issues.jboss.org/projects/DBZ/issues/DBZ-130[DBZ-130], https://issues.jboss.org/projects/DBZ/issues/DBZ-131[DBZ-131]
* MySQL connector properly handles multi-character `ENUM` and `SET` values. https://issues.jboss.org/projects/DBZ/issues/DBZ-132[DBZ-132]



[[release-0-3-2]]
== *Release 0.3.2* _(September 26, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12331401[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.2 from 0.3.1, 0.3.0, 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.2 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.2 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release includes no breaking changes since the link:release-0-3-1[0.3.1] release.

=== New Features

This release includes no new features since the link:release-0-3-1[0.3.1] release.

=== Fixes

This release includes the following fixes to the link:release-0-3-1[0.3.1] release:

* MySQL connector now handles zero-value dates. https://issues.jboss.org/projects/DBZ/issues/DBZ-114[DBZ-114]
* MySQL connector no longer prints out password-related configuration properties, though https://issues.apache.org/jira/browse/KAFKA-4171[KAFKA-4171] for a similar issue with Kafka Connect. https://issues.jboss.org/projects/DBZ/issues/DBZ-122[DBZ-122]
* MySQL connector no longer causes "Error registering AppInfo mbean" warning in Kafka Connect. https://issues.jboss.org/projects/DBZ/issues/DBZ-124[DBZ-124]
* MySQL connector periodically outputs status when reading binlog. https://issues.jboss.org/projects/DBZ/issues/DBZ-116[DBZ-116]
* MongoDB connector periodically outputs status when reading binlog. https://issues.jboss.org/projects/DBZ/issues/DBZ-117[DBZ-117]
* MySQL connector correctly uses long for the `server.id` configuration property. https://issues.jboss.org/projects/DBZ/issues/DBZ-118[DBZ-118]
* MySQL connector fails or warns when MySQL is not using row-level logging. https://issues.jboss.org/projects/DBZ/issues/DBZ-128[DBZ-128]


[[release-0-3-1]]
== *Release 0.3.1* _(August 30, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12331359[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.1 from 0.3.0, 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.1 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.1 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release includes no breaking changes compared to the link:release-0-3-0[0.3.0] release.

=== New Features

* Added support for secure (encrypted) connections to MySQL. https://issues.jboss.org/projects/DBZ/issues/DBZ-99[DBZ-99]

=== Fixes

This release includes the following fixes to the link:release-0-3-0[0.3.0] release:

* MySQL connector now properly decodes string values from the binlog based upon the column's character set encoding as read by the DDL statement. Upon upgrade and restart, the connector will re-read the recorded database history and now associate the columns with their the character sets, and any newly processed events will use properly encoded strings values. As expected, previously generated events are never altered. Force a snapshot to regenerate events for the servers. https://issues.jboss.org/projects/DBZ/issues/DBZ-102[DBZ-102]
* Corrected how the MySQL connector parses some DDL statements. https://issues.jboss.org/projects/DBZ/issues/DBZ-106[DBZ-106]
* Corrected the MySQL connector to handle MySQL server GTID sets with newline characters. https://issues.jboss.org/projects/DBZ/issues/DBZ-107[DBZ-107], https://issues.jboss.org/projects/DBZ/issues/DBZ-111[DBZ-111]
* Corrected the MySQL connector's startup logic properly compare the MySQL SSL-related system properties to prevent overwriting them. The connector no longer fails when the system properties are the same, which can happen upon restart or starting a second MySQL connector with the same keystore. https://issues.jboss.org/projects/DBZ/issues/DBZ-112[DBZ-112]
* Removed unused code and test case. https://issues.jboss.org/projects/DBZ/issues/DBZ-108[DBZ-108]
* Ensure that the MySQL error code and SQLSTATE are included in exceptions reported by the connector. https://issues.jboss.org/projects/DBZ/issues/DBZ-109[DBZ-109]


[[release-0-3-0]]
== *Release 0.3.0* _(August 16, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12329661[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.0 from 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.0 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.0 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release includes one potentially breaking changes from the link:release-0-2-4[0.2.4] release:

* By default the MySQL connector now represents temporal values with millisecond, microsecond, or nanosecond precision based upon the precision of the source database columns. This changes the schema name of these fields to Debezium-specific constants, and the meaning/interpretation of the literal values now depends on this schema name. To enable previous behavior that always used millisecond precision using only Kafka Connect logical types, set `time.precision.mode` connector property to `connect`. https://issues.jboss.org/projects/DBZ/issues/DBZ-91[DBZ-91]

=== New Features

* Added the link:/docs/connectors/mongodb/[MongoDB connector], which can capture and record the changes within a MongoDB replica set or MongoDB sharded cluster. In the latter case, the connector even automatically handles the addition or removal of shards. https://issues.jboss.org/projects/DBZ/issues/DBZ-2[DBZ-2]

=== Fixes

This release includes all of the fixes from the link:release-0-2-4[0.2.4] release, and also includes the following fixes:

* Corrected how the MySQL connector handles `TINYINT` columns. https://issues.jboss.org/projects/DBZ/issues/DBZ-84[DBZ-84]
* MySQL snapshots records DDL statements as separate events on the schema change topic. https://issues.jboss.org/browse/DBZ-97[DBZ-97]
* MySQL connector tolerates binlog filename missing from ROTATE events in certain situations. https://issues.jboss.org/browse/DBZ-95[DBZ-95]
* The Kafka Connect schema names used in the MySQL connector's change events are now always Avro-compatible schema names. Now, using the Avro converter with a `database.server.name` value, database names, or table names that contain Avro-incompatible characters produce log warnings but no longer result in errors during serialization and Avro schema generation. Whenever possible, use a `database.server.name` value that contains alphanumeric and underscore characters. https://issues.jboss.org/projects/DBZ/issues/DBZ-86[DBZ-86]



[[release-0-2-4]]
== *Release 0.2.4* _(August 16, 2016)_

August 16, 2016 - https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12331221[Detailed release notes]

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12331221[complete list of issues].

=== Upgrading

There are no backward-incompatible changes when upgrading to 0.2.4 from 0.2.3 or 0.2.2. Gracefully stop the running 0.2.3 connector, remove the 0.2.3 plugin files, install the 0.2.4 plugin files, and restart the connector using the same configuration. Upon restart, the 0.2.4 connector will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.


=== Kafka compatibility

This release requires Kafka Connect 0.9.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.10.0 due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details.


=== Fixes

This release includes all of the fixes from the link:release-0-2-3[0.2.3] release plus the following fixes:

* Stream result set rows when taking snapshot of MySQL databases to prevent out of memory problems with very large databases. https://issues.jboss.org/browse/DBZ-94[DBZ-94]
* Add more verbose logging statements to the MySQL connector to show progress and activity during snapshots. https://issues.jboss.org/browse/DBZ-92[DBZ-92]
* Corrected potential error during graceful MySQL connector shutdown. https://issues.jboss.org/browse/DBZ-103[DBZ-103]



[[release-0-2-4]]
== *Release 0.2.4* _(August 16, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12331221[complete list of issues].

=== Upgrading

There are no backward-incompatible changes when upgrading to 0.2.4 from 0.2.3 or 0.2.2. Gracefully stop the running 0.2.3 connector, remove the 0.2.3 plugin files, install the 0.2.4 plugin files, and restart the connector using the same configuration. Upon restart, the 0.2.4 connector will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.


=== Kafka compatibility

This release requires Kafka Connect 0.9.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.10.0 due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details.

=== Fixes

This release includes all of the fixes from the link:release-0-2-3[0.2.3] release plus the following fixes:

* Stream result set rows when taking snapshot of MySQL databases to prevent out of memory problems with very large databases. https://issues.jboss.org/browse/DBZ-94[DBZ-94]
* Add more verbose logging statements to the MySQL connector to show progress and activity during snapshots. https://issues.jboss.org/browse/DBZ-92[DBZ-92]
* Corrected potential error during graceful MySQL connector shutdown. https://issues.jboss.org/browse/DBZ-103[DBZ-103]


[[release-0-2-3]]
== *Release 0.2.3* _(July 26, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12330932[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.9.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.10.0 due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details.

=== Upgrading

There are no backward-incompatible changes when upgrading to 0.2.3 from 0.2.2. Gracefully stop the running 0.2.2 connector, remove the 0.2.2 plugin files, install the 0.2.3 plugin files, and restart the connector using the same configuration. Upon restart, the 0.2.3 connector will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.


=== Fixes

This release includes all of the fixes from the link:release-0-2-2[0.2.2] release plus the following fixes:

* Corrected parsing errors when MySQL DDL statements are generated by Liquibase. https://issues.jboss.org/projects/DBZ/issues/DBZ-83[DBZ-83]
* Corrected support of MySQL `TINYINT` and `SMALLINT` types. https://issues.jboss.org/projects/DBZ/issues/DBZ-84[DBZ-84], https://issues.jboss.org/projects/DBZ/issues/DBZ-87[DBZ-87]
* Corrected support of MySQL temporal types, including `DATE`, `TIME`, and `TIMESTAMP`. https://issues.jboss.org/projects/DBZ/issues/DBZ-85[DBZ-85]
* Corrected call to MySQL SHOW MASTER STATUS so that it works on pre-5.7 versions of MySQL. https://issues.jboss.org/projects/DBZ/issues/DBZ-82[DBZ-82]

[[release-0-2-2]]
== *Release 0.2.2* _(June 22, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12330862[complete list of issues].

=== Kafka compatibility

This release can be used with Kafka Connect 0.9.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.10.0 due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details.

=== Upgrading

Check the backward-incompatible changes when upgrading to 0.2.2 from 0.2.1 or 0.2.0.

When you decide to upgrade the MySQL connector to 0.2.2 from 0.2.1 or 0.2.0, gracefully stop the running 0.2.1 connector, remove the 0.2.1 plugin files, install the 0.2.2 plugin files, and restart the connector using the same configuration. Upon restart, the 0.2.2 connector will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.


=== Backwards-incompatible changes

* Removed several methods in the `GtidSet` class inside the MySQL connector. The class was introduced in 0.2. This change will only affect applications explicitly using the class (by reusing the MySQL connector JAR), and will not affect how the MySQL connector works. https://issues.jboss.org/projects/DBZ/issues/DBZ-79[DBZ-79]
* The `source` field within each MySQL change event now contains the binlog position of that event (rather than the next event). The structure of the change events (and semantics of other values remain) the same as with 0.2.1. Note that this change _may_ adversely clients that are explicitly comparing the position values across multiple events. https://issues.jboss.org/projects/DBZ/issues/DBZ-71[DBZ-71]

=== Fixes

This release includes all of the fixes from the link:release-0-2-1[0.2.1] release plus the following fixes:

* Correct how the MySQL connector records offsets with multi-row MySQL events so that, even if the connector experiences a non-graceful shutdown (i.e., crash) after committing the offset of _some_ of the rows from such an event, upon restart the connector will resume with the remaining rows in that multi-row event. Previously, the connector might incorrectly restart at the next event. https://issues.jboss.org/projects/DBZ/issues/DBZ-73[DBZ-73]
* Shutdown of the MySQL connector immediately after a snapshot completes (before another change event is reccorded) will now be properly marked as complete. https://issues.jboss.org/projects/DBZ/issues/DBZ-77[DBZ-77]


[[release-0-2-1]]
== *Release 0.2.1* _(June 10, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12330752[complete list of issues].

=== Kafka compatibility

This release can be used with Kafka Connect 0.9.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.10.0 due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80]

=== Upgrading

Check the backward-incompatible changes when upgrading to 0.2.1 from 0.2.0.

When you decide to upgrade the MySQL connector to 0.2.1 from 0.2.0, gracefully stop the running 0.2.0 connector, remove the 0.2.0 plugin files, install the 0.2.1 plugin files, and restart the connector using the same configuration. Upon restart, the 0.2.1 connector will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Backwards-incompatible changes

* Corrected the names of the Avro-compliant Kafka Connect schemas generated by the MySQL connector for the `before` and `after` fields in its data change events. Consumers that require knowledge (by name) of the particular schemas used in 0.2 events may have trouble consuming events produced by the 0.2.1 (or later) connector. https://issues.jboss.org/projects/DBZ/issues/DBZ-72[DBZ-72]

=== Fixes

This release includes all of the fixes from the link:release-0-2-0[0.2.0] release plus the following fixes:

* The MySQL connector's plugin archive now contains the MySQL JDBC driver JAR file required by the connector. https://issues.jboss.org/projects/DBZ/issues/DBZ-71[DBZ-71]



[[release-0-2-0]]
== *Release 0.2.0* _(June 8, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12329465[complete list of issues] addressed in this release.

[WARNING]
====
The 0.2.0 release contained a significant issue, and link:#release-0-2-1[0.2.1] was quickly released to fix the problem. We recommend using a newer release than 0.2.
====

=== Backwards-incompatible changes

* Completely redesigned the structure of event messages produced by MySQL connector and stored in Kafka topics. Events now contain an _envelope_ structure with information about the source event, the kind of operation (create/insert, update, delete, read), the time that Debezium processed the event, and the state of the row before and/or after the event. The messages written to each topic have a distinct Avro-compliant Kafka Connect schema that reflects the structure of the source table, which may vary over time independently from the schemas of all other topics. See the https://debezium.io/docs/connectors/mysql#events[documentation] for details. This envelope structure will likely be used by future connectors. https://issues.jboss.org/projects/DBZ/issues/DBZ-50[DBZ-50], https://issues.jboss.org/projects/DBZ/issues/DBZ-52[DBZ-52], https://issues.jboss.org/projects/DBZ/issues/DBZ-45[DBZ-45], https://issues.jboss.org/projects/DBZ/issues/DBZ-60[DBZ-60]
* MySQL connector handles deletion of a row by recording a delete event message whose value contains the state of the removed row (and other metadata), followed by a _tombstone event_ message with a null value to signal *Kafka's log compaction* that all messages with the same key can be garbage collected. See the https://debezium.io/docs/connectors/mysql#events[documentation] for details. https://issues.jboss.org/projects/DBZ/issues/DBZ-44[DBZ-44]
* Changed the format of events that the MySQL connector writes to its schema change topic, through which consumers can access events with the DDL statements applied to the database(s). The format change makes it possible for consumers to correlate these events with the data change events. https://issues.jboss.org/projects/DBZ/issues/DBZ-43[DBZ-43], https://issues.jboss.org/projects/DBZ/issues/DBZ-55[DBZ-55]

=== New features

* MySQL connector supports *high availability* MySQL cluster topologies. See the https://debezium.io/docs/connectors/mysql[documentation] for details. https://issues.jboss.org/projects/DBZ/issues/DBZ-37[DBZ-37]
* MySQL connector now by default starts by performing a *consistent snapshot* of the schema and contents of the upstream MySQL databases in its current state. See the https://debezium.io/docs/connectors/mysql#snapshots[documentation] for details about how this works and how it impacts other database clients. https://issues.jboss.org/projects/DBZ/issues/DBZ-31[DBZ-31]
* MySQL connector can be configured to *exclude*, *truncate*, or *mask* specific columns in events. https://issues.jboss.org/projects/DBZ/issues/DBZ-29[DBZ-29]
* MySQL connector events can be serialized using the http://docs.confluent.io/3.0.0/avro.html[Confluent Avro converter] or the JSON converter. Previously, only the JSON converter could be used. https://issues.jboss.org/projects/DBZ/issues/DBZ-29[DBZ-29], https://issues.jboss.org/projects/DBZ/issues/DBZ-63[DBZ-63], https://issues.jboss.org/projects/DBZ/issues/DBZ-64[DBZ-64]

=== Changes

* DDL parsing framework identifies table affected by statements via a new listener callback. https://issues.jboss.org/projects/DBZ/issues/DBZ-38[DBZ-38]
* The `database.binlog` configuration property was required in version 0.1 of the MySQL connector, but now it is no longer used because of the new snapshot feature. If provided, it will be quietly ignored. https://issues.jboss.org/projects/DBZ/issues/DBZ-31[DBZ-31]

=== Bug fixes

* MySQL connector now properly parses `COMMIT` statements, the `REFERENCES` clauses of `CREATE TABLE` statements, and statements with `CHARSET` shorthand of `CHARACTER SET`. https://issues.jboss.org/projects/DBZ/issues/DBZ-48[DBZ-48], https://issues.jboss.org/projects/DBZ/issues/DBZ-49[DBZ-49], https://issues.jboss.org/projects/DBZ/issues/DBZ-57[DBZ-57]
* MySQL connector properly handles binary values that are hexadecimal strings https://issues.jboss.org/projects/DBZ/issues/DBZ-61[DBZ-61]



[[release-0-1-0]]
== *Release 0.1.0* _(March 17, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12329464[complete list of issues] addressed in this release.

=== Kafka compatibility

This release can be used with Kafka Connect 0.9.0.1 (or a subsequent API-compatible release).

=== Added

* MySQL connector for ingesting change events from MySQL databases. https://issues.jboss.org/projects/DBZ/issues/DBZ-1[DBZ-1]
* Kafka Connect plugin archive for MySQL connector. https://issues.jboss.org/projects/DBZ/issues/DBZ-17[DBZ-17]
* Simple DDL parsing framework that can be extended and used by various connectors. https://issues.jboss.org/projects/DBZ/issues/DBZ-1[DBZ-1]
* Framework for embedding a single Kafka Connect connector inside an application. https://issues.jboss.org/projects/DBZ/issues/DBZ-8[DBZ-8]
