= Debezium Change Log
:awestruct-layout: doc
:linkattrs:
:icons: font

All notable changes for Debezium releases are documented in this file. Release numbers follow http://semver.org[Semantic Versioning].


[[release-0-3-3]]
== *Release 0.3.3* _(October 18, 2016)_

See the https://issues.jboss.org/browse/DBZ/versions/12331604[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrading the MySQL connector to 0.3.3 from 0.3.2, 0.3.1, 0.3.0, 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.3 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.3 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Backwards-incompatible changes

This release includes no backward-incompatible changes since the link:release-0-3-2[0.3.2] release.

=== New Features

This release includes no new features since the link:release-0-3-2[0.3.2] release.

=== Fixes

This release includes the following fixes to the link:release-0-3-2[0.3.2] release.

* MySQL connector now works with MySQL 5.5. https://issues.jboss.org/projects/DBZ/issues/DBZ-115[DBZ-115]
* MySQL connector now handles `BIT(n)` column values. https://issues.jboss.org/projects/DBZ/issues/DBZ-123[DBZ-123]
* MySQL connector supports failing over based on subset of GTIDs. https://issues.jboss.org/projects/DBZ/issues/DBZ-129[DBZ-129]
* MySQL connector processes GTIDs with line feeds and carriage returns. https://issues.jboss.org/projects/DBZ/issues/DBZ-135[DBZ-135]
* MySQL connector has improved output of GTIDs and status when reading the binary log. https://issues.jboss.org/projects/DBZ/issues/DBZ-130[DBZ-130], https://issues.jboss.org/projects/DBZ/issues/DBZ-131[DBZ-131]
* MySQL connector properly handles multi-character `ENUM` and `SET` values. https://issues.jboss.org/projects/DBZ/issues/DBZ-132[DBZ-132]



[[release-0-3-2]]
== *Release 0.3.2* _(September 26, 2016)_

See the https://issues.jboss.org/browse/DBZ/versions/12331401[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrading the MySQL connector to 0.3.2 from 0.3.1, 0.3.0, 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.2 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.2 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Backwards-incompatible changes

This release includes no backward-incompatible changes since the link:release-0-3-1[0.3.1] release.

=== New Features

This release includes no new features since the link:release-0-3-1[0.3.1] release.

=== Fixes

This release includes the following fixes to the link:release-0-3-1[0.3.1] release.

* MySQL connector now handles zero-value dates. https://issues.jboss.org/projects/DBZ/issues/DBZ-114[DBZ-114]
* MySQL connector no longer prints out password-related configuration properties, though https://issues.apache.org/jira/browse/KAFKA-4171[KAFKA-4171] for a similar issue with Kafka Connect. https://issues.jboss.org/projects/DBZ/issues/DBZ-122[DBZ-122]
* MySQL connector no longer causes "Error registering AppInfo mbean" warning in Kafka Connect. https://issues.jboss.org/projects/DBZ/issues/DBZ-124[DBZ-124]
* MySQL connector periodically outputs status when reading binlog. https://issues.jboss.org/projects/DBZ/issues/DBZ-116[DBZ-116]
* MongoDB connector periodically outputs status when reading binlog. https://issues.jboss.org/projects/DBZ/issues/DBZ-117[DBZ-117]
* MySQL connector correctly uses long for the `server.id` configuration property. https://issues.jboss.org/projects/DBZ/issues/DBZ-118[DBZ-118]
* MySQL connector fails or warns when MySQL is not using row-level logging. https://issues.jboss.org/projects/DBZ/issues/DBZ-128[DBZ-128]


[[release-0-3-1]]
== *Release 0.3.1* _(August 30, 2016)_

See the https://issues.jboss.org/browse/DBZ/versions/12331359[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrading the MySQL connector to 0.3.1 from 0.3.0, 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.1 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.1 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Backwards-incompatible changes

This release includes no backward-incompatible changes compared to the link:release-0-3-0[0.3.0] release.

=== New Features

* Added support for secure (encrypted) connections to MySQL. https://issues.jboss.org/projects/DBZ/issues/DBZ-99[DBZ-99]

=== Fixes

This release includes the following fixes to the link:release-0-3-0[0.3.0] release.

* MySQL connector now properly decodes string values from the binlog based upon the column's character set encoding as read by the DDL statement. Upon upgrade and restart, the connector will re-read the recorded database history and now associate the columns with their the character sets, and any newly processed events will use properly encoded strings values. As expected, previously generated events are never altered. Force a snapshot to regenerate events for the servers. https://issues.jboss.org/projects/DBZ/issues/DBZ-102[DBZ-102]
* Corrected how the MySQL connector parses some DDL statements. https://issues.jboss.org/projects/DBZ/issues/DBZ-106[DBZ-106]
* Corrected the MySQL connector to handle MySQL server GTID sets with newline characters. https://issues.jboss.org/projects/DBZ/issues/DBZ-107[DBZ-107], https://issues.jboss.org/projects/DBZ/issues/DBZ-111[DBZ-111]
* Corrected the MySQL connector's startup logic properly compare the MySQL SSL-related system properties to prevent overwriting them. The connector no longer fails when the system properties are the same, which can happen upon restart or starting a second MySQL connector with the same keystore. https://issues.jboss.org/projects/DBZ/issues/DBZ-112[DBZ-112]
* Removed unused code and test case. https://issues.jboss.org/projects/DBZ/issues/DBZ-108[DBZ-108]
* Ensure that the MySQL error code and SQLSTATE are included in exceptions reported by the connector. https://issues.jboss.org/projects/DBZ/issues/DBZ-109[DBZ-109]


[[release-0-3-0]]
== *Release 0.3.0* _(August 16, 2016)_

See the https://issues.jboss.org/browse/DBZ/versions/12329661[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrading the MySQL connector to 0.3.0 from 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.0 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.0 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Backwards-incompatible changes

This release includes the potentially backward-incompatible changes from the link:release-0-2-4[0.2.4] release:

* By default the MySQL connector now represents temporal values with millisecond, microsecond, or nanosecond precision based upon the precision of the source database columns. This changes the schema name of these fields to Debezium-specific constants, and the meaning/interpretation of the literal values now depends on this schema name. To enable previous behavior that always used millisecond precision using only Kafka Connect logical types, set `time.precision.mode` connector property to `connect`. https://issues.jboss.org/projects/DBZ/issues/DBZ-91[DBZ-91]

=== New Features

* Added the link:/docs/connectors/mongodb[MongoDB connector], which can capture and record the changes within a MongoDB replica set or MongoDB sharded cluster. In the latter case, the connector even automatically handles the addition or removal of shards. https://issues.jboss.org/projects/DBZ/issues/DBZ-2[DBZ-2]

=== Fixes

This release includes all of the fixes from the link:release-0-2-4[0.2.4] release, and also includes the following fixes:

* Corrected how the MySQL connector handles `TINYINT` columns. https://issues.jboss.org/projects/DBZ/issues/DBZ-84[DBZ-84]
* MySQL snapshots records DDL statements as separate events on the schema change topic. https://issues.jboss.org/browse/DBZ-97[DBZ-97]
* MySQL connector tolerates binlog filename missing from ROTATE events in certain situations. https://issues.jboss.org/browse/DBZ-95[DBZ-95]
* The Kafka Connect schema names used in the MySQL connector's change events are now always Avro-compatible schema names. Now, using the Avro converter with a `database.server.name` value, database names, or table names that contain Avro-incompatible characters produce log warnings but no longer result in errors during serialization and Avro schema generation. Whenever possible, use a `database.server.name` value that contains alphanumeric and underscore characters. https://issues.jboss.org/projects/DBZ/issues/DBZ-86[DBZ-86]



[[release-0-2-4]]
== *Release 0.2.4* _(August 16, 2016)_

August 16, 2016 - [Detailed release notes](https://issues.jboss.org/projects/DBZ/versions/12331221)

See the https://issues.jboss.org/projects/DBZ/versions/12331221[complete list of issues]. 

=== Upgrading

There are no backward-incompatible changes when upgrading to 0.2.4 from 0.2.3 or 0.2.2. Gracefully stop the running 0.2.3 connector, remove the 0.2.3 plugin files, install the 0.2.4 plugin files, and restart the connector using the same configuration. Upon restart, the 0.2.4 connector will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.


=== Kafka compatibility

This release requires Kafka Connect 0.9.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.10.0 due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details.

=== Fixes

This release includes all of the fixes from the link:release-0-2-3[0.2.3] release plus the following fixes:

* Stream result set rows when taking snapshot of MySQL databases to prevent out of memory problems with very large databases. https://issues.jboss.org/browse/DBZ-94[DBZ-94]
* Add more verbose logging statements to the MySQL connector to show progress and activity during snapshots. https://issues.jboss.org/browse/DBZ-92[DBZ-92]
* Corrected potential error during graceful MySQL connector shutdown. https://issues.jboss.org/browse/DBZ-103[DBZ-103]



[[release-0-2-4]]
== *Release 0.2.4* _(August 16, 2016)_

See the https://issues.jboss.org/projects/DBZ/versions/12331221[complete list of issues]. 

=== Upgrading

There are no backward-incompatible changes when upgrading to 0.2.4 from 0.2.3 or 0.2.2. Gracefully stop the running 0.2.3 connector, remove the 0.2.3 plugin files, install the 0.2.4 plugin files, and restart the connector using the same configuration. Upon restart, the 0.2.4 connector will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.


=== Kafka compatibility

This release requires Kafka Connect 0.9.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.10.0 due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details.

=== Fixes

This release includes all of the fixes from the link:release-0-2-3[0.2.3] release plus the following fixes:

* Stream result set rows when taking snapshot of MySQL databases to prevent out of memory problems with very large databases. https://issues.jboss.org/browse/DBZ-94[DBZ-94]
* Add more verbose logging statements to the MySQL connector to show progress and activity during snapshots. https://issues.jboss.org/browse/DBZ-92[DBZ-92]
* Corrected potential error during graceful MySQL connector shutdown. https://issues.jboss.org/browse/DBZ-103[DBZ-103]


[[release-0-2-3]]
== *Release 0.2.3* _(July 26, 2016)_

See the https://issues.jboss.org/browse/DBZ/versions/12330932[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.9.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.10.0 due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details.

=== Upgrading

There are no backward-incompatible changes when upgrading to 0.2.3 from 0.2.2. Gracefully stop the running 0.2.2 connector, remove the 0.2.2 plugin files, install the 0.2.3 plugin files, and restart the connector using the same configuration. Upon restart, the 0.2.3 connector will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.


=== Fixes

This release includes all of the fixes from the link:release-0-2-2[0.2.2] release plus the following fixes:

* Corrected parsing errors when MySQL DDL statements are generated by Liquibase. https://issues.jboss.org/projects/DBZ/issues/DBZ-83[DBZ-83]
* Corrected support of MySQL `TINYINT` and `SMALLINT` types. https://issues.jboss.org/projects/DBZ/issues/DBZ-84[DBZ-84], https://issues.jboss.org/projects/DBZ/issues/DBZ-87[DBZ-87]
* Corrected support of MySQL temporal types, including `DATE`, `TIME`, and `TIMESTAMP`. https://issues.jboss.org/projects/DBZ/issues/DBZ-85[DBZ-85]
* Corrected call to MySQL SHOW MASTER STATUS so that it works on pre-5.7 versions of MySQL. https://issues.jboss.org/projects/DBZ/issues/DBZ-82[DBZ-82]

[[release-0-2-2]]
== *Release 0.2.2* _(June 22, 2016)_

See the https://issues.jboss.org/browse/DBZ/versions/12330862[complete list of issues].

=== Kafka compatibility

This release can be used with Kafka Connect 0.9.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.10.0 due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details.

=== Upgrading

Check the backward-incompatible changes when upgrading to 0.2.2 from 0.2.1 or 0.2.0.

When you decide to upgrading the MySQL connector to 0.2.2 from 0.2.1 or 0.2.0, gracefully stop the running 0.2.1 connector, remove the 0.2.1 plugin files, install the 0.2.2 plugin files, and restart the connector using the same configuration. Upon restart, the 0.2.2 connector will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.


=== Backwards-incompatible changes

* Removed several methods in the `GtidSet` class inside the MySQL connector. The class was introduced in 0.2. This change will only affect applications explicitly using the class (by reusing the MySQL connector JAR), and will not affect how the MySQL connector works. https://issues.jboss.org/projects/DBZ/issues/DBZ-79[DBZ-79]
* The `source` field within each MySQL change event now contains the binlog position of that event (rather than the next event). The structure of the change events (and semantics of other values remain) the same as with 0.2.1. Note that this change _may_ adversely clients that are explicitly comparing the position values across multiple events. https://issues.jboss.org/projects/DBZ/issues/DBZ-71[DBZ-71]

=== Fixes

This release includes all of the fixes from the link:release-0-2-1[0.2.1] release plus the following fixes:

* Correct how the MySQL connector records offsets with multi-row MySQL events so that, even if the connector experiences a non-graceful shutdown (i.e., crash) after committing the offset of _some_ of the rows from such an event, upon restart the connector will resume with the remaining rows in that multi-row event. Previously, the connector might incorrectly restart at the next event. https://issues.jboss.org/projects/DBZ/issues/DBZ-73[DBZ-73]
* Shutdown of the MySQL connector immediately after a snapshot completes (before another change event is reccorded) will now be properly marked as complete. https://issues.jboss.org/projects/DBZ/issues/DBZ-77[DBZ-77]


[[release-0-2-1]]
== *Release 0.2.1* _(June 10, 2016)_

See the https://issues.jboss.org/browse/DBZ/fixforversion/12330752[complete list of issues].

=== Kafka compatibility

This release can be used with Kafka Connect 0.9.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.10.0 due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80]

=== Upgrading

Check the backward-incompatible changes when upgrading to 0.2.1 from 0.2.0.

When you decide to upgrading the MySQL connector to 0.2.1 from 0.2.0, gracefully stop the running 0.2.0 connector, remove the 0.2.0 plugin files, install the 0.2.1 plugin files, and restart the connector using the same configuration. Upon restart, the 0.2.1 connector will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Backwards-incompatible changes

* Corrected the names of the Avro-compliant Kafka Connect schemas generated by the MySQL connector for the `before` and `after` fields in its data change events. Consumers that require knowledge (by name) of the particular schemas used in 0.2 events may have trouble consuming events produced by the 0.2.1 (or later) connector. https://issues.jboss.org/projects/DBZ/issues/DBZ-72[DBZ-72]

=== Fixes

This release includes all of the fixes from the link:release-0-2-0[0.2.0] release plus the following fixes:

* The MySQL connector's plugin archive now contains the MySQL JDBC driver JAR file required by the connector. https://issues.jboss.org/projects/DBZ/issues/DBZ-71[DBZ-71]



[[release-0-2-0]]
== *Release 0.2.0* _(June 8, 2016)_

See the https://issues.jboss.org/browse/DBZ/fixforversion/12329465[complete list of issues] addressed in this release.

[WARNING]
====
The 0.2.0 release contained a significant issue, and link:#release-0-2-1[0.2.1] was quickly released to fix the problem. We recommend using a newer release than 0.2.
====

=== Backwards-incompatible changes

* Completely redesigned the structure of event messages produced by MySQL connector and stored in Kafka topics. Events now contain an _envelope_ structure with information about the source event, the kind of operation (create/insert, update, delete, read), the time that Debezium processed the event, and the state of the row before and/or after the event. The messages written to each topic have a distinct Avro-compliant Kafka Connect schema that reflects the structure of the source table, which may vary over time independently from the schemas of all other topics. See the http://debezium.io/docs/connectors/mysql#events[documentation] for details. This envelope structure will likely be used by future connectors. https://issues.jboss.org/projects/DBZ/issues/DBZ-50[DBZ-50], https://issues.jboss.org/projects/DBZ/issues/DBZ-52[DBZ-52], https://issues.jboss.org/projects/DBZ/issues/DBZ-45[DBZ-45], https://issues.jboss.org/projects/DBZ/issues/DBZ-60[DBZ-60]
* MySQL connector handles deletion of a row by recording a delete event message whose value contains the state of the removed row (and other metadata), followed by a _tombstone event_ message with a null value to signal *Kafka's log compaction* that all messages with the same key can be garbage collected. See the http://debezium.io/docs/connectors/mysql#events[documentation] for details. https://issues.jboss.org/projects/DBZ/issues/DBZ-44[DBZ-44]
* Changed the format of events that the MySQL connector writes to its schema change topic, through which consumers can access events with the DDL statements applied to the database(s). The format change makes it possible for consumers to correlate these events with the data change events. https://issues.jboss.org/projects/DBZ/issues/DBZ-43[DBZ-43], https://issues.jboss.org/projects/DBZ/issues/DBZ-55[DBZ-55]

=== New features

* MySQL connector supports *high availability* MySQL cluster topologies. See the http://debezium.io/docs/connectors/mysql[documentation] for details. https://issues.jboss.org/projects/DBZ/issues/DBZ-37[DBZ-37]
* MySQL connector now by default starts by performing a *consistent snapshot* of the schema and contents of the upstream MySQL databases in its current state. See the http://debezium.io/docs/connectors/mysql#snapshots[documentation] for details about how this works and how it impacts other database clients. https://issues.jboss.org/projects/DBZ/issues/DBZ-31[DBZ-31]
* MySQL connector can be configured to *exclude*, *truncate*, or *mask* specific columns in events. https://issues.jboss.org/projects/DBZ/issues/DBZ-29[DBZ-29]
* MySQL connector events can be serialized using the http://docs.confluent.io/3.0.0/avro.html[Confluent Avro converter] or the JSON converter. Previously, only the JSON converter could be used. https://issues.jboss.org/projects/DBZ/issues/DBZ-29[DBZ-29], https://issues.jboss.org/projects/DBZ/issues/DBZ-63[DBZ-63], https://issues.jboss.org/projects/DBZ/issues/DBZ-64[DBZ-64]

=== Changes

* DDL parsing framework identifies table affected by statements via a new listener callback. https://issues.jboss.org/projects/DBZ/issues/DBZ-38[DBZ-38]
* The `database.binlog` configuration property was required in version 0.1 of the MySQL connector, but now it is no longer used because of the new snapshot feature. If provided, it will be quietly ignored. https://issues.jboss.org/projects/DBZ/issues/DBZ-31[DBZ-31]

=== Bug fixes

* MySQL connector now properly parses `COMMIT` statements, the `REFERENCES` clauses of `CREATE TABLE` statements, and statements with `CHARSET` shorthand of `CHARACTER SET`. https://issues.jboss.org/projects/DBZ/issues/DBZ-48[DBZ-48], https://issues.jboss.org/projects/DBZ/issues/DBZ-49[DBZ-49], https://issues.jboss.org/projects/DBZ/issues/DBZ-57[DBZ-57]
* MySQL connector properly handles binary values that are hexadecimal strings https://issues.jboss.org/projects/DBZ/issues/DBZ-61[DBZ-61]



[[release-0-1-0]]
== *Release 0.1.0* _(March 17, 2016)_

See the https://issues.jboss.org/browse/DBZ/fixforversion/12329464[complete list of issues] addressed in this release.

=== Kafka compatibility

This release can be used with Kafka Connect 0.9.0.1 (or a subsequent API-compatible release).

=== Added

* MySQL connector for ingesting change events from MySQL databases. https://issues.jboss.org/projects/DBZ/issues/DBZ-1[DBZ-1]
* Kafka Connect plugin archive for MySQL connector. https://issues.jboss.org/projects/DBZ/issues/DBZ-17[DBZ-17]
* Simple DDL parsing framework that can be extended and used by various connectors. https://issues.jboss.org/projects/DBZ/issues/DBZ-1[DBZ-1]
* Framework for embedding a single Kafka Connect connector inside an application. https://issues.jboss.org/projects/DBZ/issues/DBZ-8[DBZ-8]
