= Debezium Change Log
:awestruct-layout: doc
:linkattrs:
:icons: font

All notable changes for Debezium releases are documented in this file.
Release numbers follow http://semver.org[Semantic Versioning].

[[release-0-5-2]]
== *Release 0.5.2* _(August 17, 2017)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?version=12334601&projectId=12317320[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 0.10.2.0 and has been tested with version 0.10.2.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.5.2 from any of the earlier 0.4.x, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.5.2 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.5.2 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

There should be no breaking changes in this relese.

=== New Features

This release includes the following new features:

* Mongo Connector: Add "database.whitelist" and "database.blacklist" configuration options [DBZ-302](https://issues.jboss.org/projects/DBZ/issues/DBZ-302)
* Provide a Dockerfile to build images from latest released snapshot [DBZ-320](https://issues.jboss.org/projects/DBZ/issues/DBZ-320)
* Support decimal handling mode for Postgres [DBZ-337](https://issues.jboss.org/projects/DBZ/issues/DBZ-337)
* Enable and show usage of Avro converters [DBZ-271](https://issues.jboss.org/projects/DBZ/issues/DBZ-271)
* Keep TCP connection alive for Postgres [DBZ-286](https://issues.jboss.org/projects/DBZ/issues/DBZ-286)
* Support "PAGE_CHECKSUM=1" option for MySQL tables [DBZ-324](https://issues.jboss.org/projects/DBZ/issues/DBZ-324)

=== Fixes

This release includes the following fixes:

* Images cannot run on OpenShift online [DBZ-267](https://issues.jboss.org/projects/DBZ/issues/DBZ-267)
* NPE when processing null value in POINT column [DBZ-284](https://issues.jboss.org/projects/DBZ/issues/DBZ-284)
* Postgres Connector: error of mismatching scale value for Decimal and Numeric data types [DBZ-287](https://issues.jboss.org/projects/DBZ/issues/DBZ-287)
* Postgres connector fails with array columns [DBZ-297](https://issues.jboss.org/projects/DBZ/issues/DBZ-297)
* Postgres connector fails with quoted type names [DBZ-298](https://issues.jboss.org/projects/DBZ/issues/DBZ-298)
* LogicalTableRouter SMT uses wrong comparison for validation [DBZ-326](https://issues.jboss.org/projects/DBZ/issues/DBZ-326)
* LogicalTableRouter SMT has a broken key replacement validation [DBZ-327](https://issues.jboss.org/projects/DBZ/issues/DBZ-327)
* Pre-compile and simplify some regular expressions [DBZ-311](https://issues.jboss.org/projects/DBZ/issues/DBZ-311)
* JMX metrics for MySQL connector should be documented [DBZ-293](https://issues.jboss.org/projects/DBZ/issues/DBZ-293)
* PostgreSQL integration tests should have completely isolated environment and configuration/setup files [DBZ-301](https://issues.jboss.org/projects/DBZ/issues/DBZ-301)
* Move snapshot Dockerfile into separated directory [DBZ-321](https://issues.jboss.org/projects/DBZ/issues/DBZ-321)
* Cover ByLogicalTableRouter SMT in reference documentation [DBZ-325](https://issues.jboss.org/projects/DBZ/issues/DBZ-325)
* Add documentation for JDBC url pass-through properties [DBZ-330](https://issues.jboss.org/projects/DBZ/issues/DBZ-330)

[[release-0-5-1]]
== *Release 0.5.1* _(June 9, 2017)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12334135[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 0.10.2.0 and has been tested with version 0.10.2.0 of the Kafka brokers.
See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.5.1 from any of the earlier 0.4.1, 0.4.0, 0.3.x, 0.2.x, or 0.1.x versions,
first check the upgrading notes for the version you're using.
Gracefully stop the running connector, remove the old plugin files, install the 0.5.0 plugin files, and restart the connector using the same configuration.
Upon restart, the 0.5.1 connectors will continue where the previous connector left off.
As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release includes the following change that affect existing installations which capture system tables:

* MySQL connector should apply database and table filters to system dbs/tables https://issues.jboss.org/projects/DBZ/issues/DBZ-242[DBZ-242]

=== New Features

This release includes the following new features:

* MySQL Connector should support 'Point' data type https://issues.jboss.org/projects/DBZ/issues/DBZ-222[DBZ-222]
* Support tstzrange column type on Postgres https://issues.jboss.org/projects/DBZ/issues/DBZ-280[DBZ-280]

=== Fixes

This release includes the following fixes:

* Control how Debezium connectors maps tables to topics for sharding and other use cases https://issues.jboss.org/projects/DBZ/issues/DBZ-121[DBZ-121]
* MySqlConnector Table and Database recommenders cause timeouts on large instances https://issues.jboss.org/projects/DBZ/issues/DBZ-232[DBZ-232]
* Option to disable SSL certificate validation for PostgreSQL https://issues.jboss.org/projects/DBZ/issues/DBZ-244[DBZ-244]
* Let enum types implement EnumeratedValue https://issues.jboss.org/projects/DBZ/issues/DBZ-262[DBZ-262]
* The  MySQL connector is failing with the DDL statements. https://issues.jboss.org/projects/DBZ/issues/DBZ-198[DBZ-198]
* Correct MongoDB build https://issues.jboss.org/projects/DBZ/issues/DBZ-213[DBZ-213]
* MongoDB connector should handle new primary better https://issues.jboss.org/projects/DBZ/issues/DBZ-214[DBZ-214]
* Validate that database.server.name and database.history.kafka.topic have different values https://issues.jboss.org/projects/DBZ/issues/DBZ-215[DBZ-215]
* When restarting Kafka Connect, we get io.debezium.text.ParsingException https://issues.jboss.org/projects/DBZ/issues/DBZ-216[DBZ-216]
* Postgres connector crash on a database managed by Django https://issues.jboss.org/projects/DBZ/issues/DBZ-223[DBZ-223]
* MySQL Connector doesn't handle any value above '2147483647' for 'INT UNSIGNED' types https://issues.jboss.org/projects/DBZ/issues/DBZ-228[DBZ-228]
* MySqlJdbcContext#userHasPrivileges() is broken for multiple privileges https://issues.jboss.org/projects/DBZ/issues/DBZ-229[DBZ-229]
* Postgres Connector does not work when "sslmode" is "require" https://issues.jboss.org/projects/DBZ/issues/DBZ-238[DBZ-238]
* Test PostgresConnectorIT.shouldSupportSSLParameters is incorrect https://issues.jboss.org/projects/DBZ/issues/DBZ-245[DBZ-245]
* Recommender and default value broken for EnumeratedValue type https://issues.jboss.org/projects/DBZ/issues/DBZ-246[DBZ-246]
* PG connector is CPU consuming  https://issues.jboss.org/projects/DBZ/issues/DBZ-250[DBZ-250]
* MySQL tests are interdependent https://issues.jboss.org/projects/DBZ/issues/DBZ-251[DBZ-251]
* MySQL DDL parser fails on "ANALYZE TABLE" statement  https://issues.jboss.org/projects/DBZ/issues/DBZ-253[DBZ-253]
* Binary fields with trailing "00" are truncated https://issues.jboss.org/projects/DBZ/issues/DBZ-254[DBZ-254]
* Enable Maven repository caching on Travis https://issues.jboss.org/projects/DBZ/issues/DBZ-274[DBZ-274]
* Memory leak and excessive CPU usage when using materialized views https://issues.jboss.org/projects/DBZ/issues/DBZ-277[DBZ-277]
* Postgres task should fail when connection to server is lost https://issues.jboss.org/projects/DBZ/issues/DBZ-281[DBZ-281]
* Fix some wrong textual descriptions of default values https://issues.jboss.org/projects/DBZ/issues/DBZ-282[DBZ-282]
* Apply consistent default value for Postgres port https://issues.jboss.org/projects/DBZ/issues/DBZ-237[DBZ-237]
* Make Docker images run on OpenShift https://issues.jboss.org/projects/DBZ/issues/DBZ-240[DBZ-240]
* Don't mention default value for "database.server.name" https://issues.jboss.org/projects/DBZ/issues/DBZ-243[DBZ-243]

[[release-0-5-0]]
== *Release 0.5.0* _(March 27, 2017)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12334135[complete list of issues].

=== Kafka compatibility

This release has been built against Kafka Connect 0.10.2.0 and has been tested with version 0.10.2.0 of the Kafka brokers. See the https://kafka.apache.org/documentation/#upgrade[Kafka documentation] for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.5.0 from any of the earlier 0.4.1, 0.4.0, 0.3.x, 0.2.x, or 0.1.x versions, first check the upgrading notes for the version you're using. Gracefully stop the running connector, remove the old plugin files, install the 0.5.0 plugin files, and restart the connector using the same configuration. Upon restart, the 0.5.0 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release includes the following changes that are likely to affect existing installations:

* Upgraded from Kafka 0.10.1.1 to 0.10.2.0. https://issues.jboss.org/projects/DBZ/issues/DBZ-203[DBZ-203]

This release has no breaking changes since the link:release-0-4-1[previous] release.

=== New Features

This release has no new features since the link:release-0-4-1[previous] release.

=== Fixes

This release includes the following fixes relative to the link:release-0-4-1[0.4.1] release:

* MySQL connector now better handles DDL statements with `BEGIN...END` blocks, especially those that use `IF()` functions and `CASE...WHEN` statements. https://issues.jboss.org/projects/DBZ/issues/DBZ-198[DBZ-198]
* MySQL connector handles 2-digit years in `DATETIME`, `DATE`, `TIMESTAMP`, and `YEAR` columns in the same way as MySQL. https://issues.jboss.org/projects/DBZ/issues/DBZ-205[DBZ-205]



[[release-0-4-1]]
== *Release 0.4.1* _(March 17, 2017)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12333486[complete list of issues].

=== Kafka compatibility

This release has been tested with Kafka Connect 0.10.1.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL, MongoDB, or PostgreSQL connectors, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade one of these connectors to 0.4.1 from any of the earlier 0.4.0, 0.3.x, 0.2.x, or 0.1.x versions, first check the upgrading notes for the version you're using. Gracefully stop the running connector, remove the old plugin files, install the 0.4.1 plugin files, and restart the connector using the same configuration. Upon restart, the 0.4.1 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release has no breaking changes since the link:release-0-4-0[previous] release.

=== New Features

This release adds/improves to the MySQL connector preliminary support for https://aws.amazon.com/rds/mysql/[Amazon RDS] and https://aws.amazon.com/rds/aurora/[Amazon Aurora (MySQL compatibility)] (see https://issues.jboss.org/projects/DBZ/issues/DBZ-140[DBZ-140]).

=== Fixes

This release includes the following fixes relative to the link:release-0-4-0[0.4.0] release:

* MySQL connector now allows filtering production of DML events by GTIDs. https://issues.jboss.org/projects/DBZ/issues/DBZ-188[DBZ-188]
* Support InnoDB savepoints. https://issues.jboss.org/projects/DBZ/issues/DBZ-196[DBZ-196]
* Corrected MySQL DDL parser. https://issues.jboss.org/projects/DBZ/issues/DBZ-193[DBZ-193] https://issues.jboss.org/projects/DBZ/issues/DBZ-198[DBZ-198]
* Improved handling of MySQL connector's built-in tables. https://issues.jboss.org/projects/DBZ/issues/DBZ-194[DBZ-194]
* MySQL connector properly handles invalid/blank enum literal values. https://issues.jboss.org/projects/DBZ/issues/DBZ-197[DBZ-197]
* MySQL connector properly handles reserved names as column names. https://issues.jboss.org/projects/DBZ/issues/DBZ-200[DBZ-200]
* MongoDB connector properly generates event keys based upon ObjectID for updates. https://issues.jboss.org/projects/DBZ/issues/DBZ-201[DBZ-201]



[[release-0-4-0]]
== *Release 0.4.0* _(February 7, 2017)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12330743[complete list of issues].

=== Kafka compatibility

This release has been tested with Kafka Connect 0.10.1.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.4.0 from any of the earlier 0.3.x, 0.2.x, or 0.1.x versions, first check the upgrading notes for the version you're using. Gracefully stop the running connector, remove the old plugin files, install the 0.4.0 plugin files, and restart the connector using the same configuration. Upon restart, the 0.4.0 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release has no breaking changes since the link:release-0-3-5[previous] release.

=== New Features

This release includes a new link:/docs/connectors/postgresql[PostgreSQL connector] (see https://issues.jboss.org/projects/DBZ/issues/DBZ-3[DBZ-3]) and adds to the MySQL connector preliminary support for https://aws.amazon.com/rds/mysql/[Amazon RDS] and https://aws.amazon.com/rds/aurora/[Amazon Aurora (MySQL compatibility)] (see https://issues.jboss.org/projects/DBZ/issues/DBZ-140[DBZ-140]).

=== Fixes

This release includes the following fixes relative to the link:release-0-3-6[0.3.6] release:

* Update Kafka dependencies to 0.10.1.1. https://issues.jboss.org/projects/DBZ/issues/DBZ-173[DBZ-173]
* Update MySQL binary log client library to 0.9.0. https://issues.jboss.org/projects/DBZ/issues/DBZ-186[DBZ-186]
* MySQL should apply GTID filters to database history. https://issues.jboss.org/projects/DBZ/issues/DBZ-185[DBZ-185]
* Add names of database and table to the MySQL event metadata. https://issues.jboss.org/projects/DBZ/issues/DBZ-184[DBZ-184]
* Add the MySQL thread ID to the MySQL event metadata. https://issues.jboss.org/projects/DBZ/issues/DBZ-113[DBZ-113]
* Corrects MySQL connector to properly handle timezone information for `TIMESTAMP`. https://issues.jboss.org/projects/DBZ/issues/DBZ-183[DBZ-183]
* Correct MySQL DDL parser to handle `CREATE TRIGGER` command with `DEFINER` clauses. https://issues.jboss.org/projects/DBZ/issues/DBZ-176[DBZ-176]
* Update MongoDB Java driver and MongoDB server versions. https://issues.jboss.org/projects/DBZ/issues/DBZ-187[DBZ-187]
* MongoDB connector should restart incomplete initial sync. https://issues.jboss.org/projects/DBZ/issues/DBZ-182[DBZ-182]
* MySQL and PostgreSQL connectors should load JDBC driver independently of DriverManager. https://issues.jboss.org/projects/DBZ/issues/DBZ-177[DBZ-177]
* Upgrade MySQL binlog client library to support new binlog events added with MySQL 5.7. https://issues.jboss.org/projects/DBZ/issues/DBZ-174[DBZ-174]
* EmbeddedEngine should log all errors. https://issues.jboss.org/projects/DBZ/issues/DBZ-178[DBZ-178]
* PostgreSQL containers' generated Protobuf source moved to separate directory. https://issues.jboss.org/projects/DBZ/issues/DBZ-179[DBZ-179]




[[release-0-3-6]]
== *Release 0.3.6* _(December 21, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12332775[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.6 from any of the earlier 0.3.x, 0.2.x, or 0.1.x versions, first check the upgrading notes for the version you're using. Gracefully stop the running connector, remove the old plugin files, install the 0.3.6 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.6 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release has no breaking changes since the link:release-0-3-5[previous] release.

=== New Features

There are no new features in this release.

=== Fixes

This release includes the following fixes to the link:release-0-3-5[0.3.5] release:

* Deleting a Debezium connector in Kafka Connect no longer causes NPEs. https://issues.jboss.org/projects/DBZ/issues/DBZ-138[DBZ-138]
* MongoDB connector properly connects to a sharded cluster and the primaries for each replica set. https://issues.jboss.org/projects/DBZ/issues/DBZ-170[DBZ-170], https://issues.jboss.org/projects/DBZ/issues/DBZ-167[DBZ-167]
* Stopping the MySQL connector while in the middle of a snapshot now cloasses all MySQL resources. https://issues.jboss.org/projects/DBZ/issues/DBZ-166[DBZ-166]
* MySQL connector properly parses with `ON UPDATE` timestamp values. https://issues.jboss.org/projects/DBZ/issues/DBZ-169[DBZ-169]
* MySQL connector ignores `CREATE FUNCTION` DDL statements. https://issues.jboss.org/projects/DBZ/issues/DBZ-162[DBZ-162]
* MySQL connector properly parses `CREATE TABLE` script with ENUM type and default value 'b'. https://issues.jboss.org/projects/DBZ/issues/DBZ-160[DBZ-160]
* MySQL connector now properly supports `NVARCHAR` columns. https://issues.jboss.org/projects/DBZ/issues/DBZ-142[DBZ-142]
* MySQL connector's snapshot process now uses `SHOW TABLE STATUS ...` rather than `SELECT COUNT(\*)` to obtain an estimate of the number of rows for each table, and can even forgo this step if all tables are to be streamed. https://issues.jboss.org/projects/DBZ/issues/DBZ-152[DBZ-152]
* MySQL connector's snaphot process ignores "artificial" database names exposed by MySQL. https://issues.jboss.org/projects/DBZ/issues/DBZ-164[DBZ-164]
* MySQL connector ignores XA statements appearing in the binlog. https://issues.jboss.org/projects/DBZ/issues/DBZ-168[DBZ-168]
* MySQL connector no longer expects GTID set information on older MySQL versions. https://issues.jboss.org/projects/DBZ/issues/DBZ-161[DBZ-161]
* Improved the EmbeddedEngine and fixed several issues. https://issues.jboss.org/projects/DBZ/issues/DBZ-156[DBZ-156]
* Upgrade to the latest Docker Maven plugin https://issues.jboss.org/projects/DBZ/issues/DBZ-157[DBZ-157]




[[release-0-3-5]]
== *Release 0.3.5* _(November 9, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12332052[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

*We strongly urge all users to upgrade to this release from earlier versions.* In prior versions, the MySQL connector may stop without completing all updates in a transaction, and when the connector restarts it starts with the _next_ transaction and therefore might fail to capture some of the change events in the earlier transaction. This release fixes this issue so that when restarting it will always pick up where it left off, even if that point is in the middle of a transaction. Note that this fix only takes affect once a connector is upgraded and restarted. Also, this fix does not affect or alter the content of change events produced by the connector. See https://issues.jboss.org/projects/DBZ/issues/DBZ-144[the issue] for more details.

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.5 from 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.5 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.5 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release has no backward-incompatible changes since the link:release-0-3-4[0.3.4] release.

=== New Features

* MySQL connector now supports failover to MySQL masters that are slaves of _multiple_ other MySQL servers/clusters, as long as the new MySQL master has all of the transactions (as specified by GTID sets) the connector had previously seen. The connector can be configured to include or exclude particular GTID sources. https://issues.jboss.org/projects/DBZ/issues/DBZ-143[DBZ-143]

=== Fixes

This release includes the following fixes to the link:release-0-3-4[0.3.4] release:

* Restarting MySQL connector will no longer lose or miss events from the previous transaction that was incompletely processed prior to the easlier shutdown. The content of change events are unaffected. https://issues.jboss.org/projects/DBZ/issues/DBZ-144[DBZ-144]
* Shutting down MySQL connector task database and quickly terminating the Kafka Connect process may cause connector to be restarted in a strange state when Kafka Connect is restarted, but this no longer results in a null pointer exception in the Kafka database history. https://issues.jboss.org/projects/DBZ/issues/DBZ-146[DBZ-146]
* MySQL connector now has option to treat `DECIMAL` and `NUMERIC` columns as double values rather than `java.math.BigDecimal` values that are encoded in the messages by Kafka Connect in binary form. This option may result in lost precision, but makes the values far easier for consumers to work with them. https://issues.jboss.org/projects/DBZ/issues/DBZ-147[DBZ-147]
* MySQL connector tests now take into account daylight savings time in the expected results. https://issues.jboss.org/projects/DBZ/issues/DBZ-148[DBZ-148]
* MySQL connector now properly treats `BINARY` columns as binary values rather than string values. https://issues.jboss.org/projects/DBZ/issues/DBZ-149[DBZ-149]
* MySQL connector now handles updates to a row's primary/unique key by issuing `DELETE` and tombstone events for the row with the old key, and then an `INSERT` event for the row with the new key. Previously, the `INSERT` was emitted before the `DELETE`. https://issues.jboss.org/projects/DBZ/issues/DBZ-150[DBZ-150]
* MySQL connector now handles `ENUM` and `SET` literals with parentheses. https://issues.jboss.org/projects/DBZ/issues/DBZ-153[DBZ-153]



[[release-0-3-4]]
== *Release 0.3.4* _(October 25, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12331604[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.4 from 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.4 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.4 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release has one breaking changes since the link:release-0-3-3[0.3.3] release:

* MySQL connector produced change events with a `ts_sec` field that now shows correct timestamp in seconds past epoch as found from the MySQL server events. In previous releases the last 3 digits in this field were truncated. https://issues.jboss.org/projects/DBZ/issues/DBZ-139[DBZ-139]

=== New Features

* MySQL connector has a new `SCHEMA_ONLY` snapshot mode. When the connector starts up for the first time and uses this snapshot mode, the connector captures the current table schemas without reading any data, and then proceeds to read the binlog. The resulting change event streams do not have all the data in the databases, but do include those change events that occurred after the snapshot started. This may be useful for consumers that only need to know the changes since the connector was started. https://issues.jboss.org/projects/DBZ/issues/DBZ-133[DBZ-133]
* MySQL connector supports the MySQL `JSON` datatype. These JSON values are represented as STRING values in the change events, although the name of the field's Kafka Connect schema is `io.debezium.data.Json` to signal to consumers that the string value is actually a JSON document, array, or scalar. https://issues.jboss.org/projects/DBZ/issues/DBZ-126[DBZ-126]
* MySQL connector metrics are exposed via JMX. All of the Debezium Docker images can expose the JMX data via a custom port. See the link:/docs/monitoring[Monitoring Debezium] document for more details. https://issues.jboss.org/projects/DBZ/issues/DBZ-134[DBZ-134]

=== Fixes

This release includes no other fixes.



[[release-0-3-3]]
== *Release 0.3.3* _(October 18, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12331604[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.3 from 0.3.2, 0.3.1, 0.3.0, 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.3 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.3 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release includes no breaking changes since the link:release-0-3-2[0.3.2] release.

=== New Features

This release includes no new features since the link:release-0-3-2[0.3.2] release.

=== Fixes

This release includes the following fixes to the link:release-0-3-2[0.3.2] release:

* MySQL connector now works with MySQL 5.5. https://issues.jboss.org/projects/DBZ/issues/DBZ-115[DBZ-115]
* MySQL connector now handles `BIT(n)` column values. https://issues.jboss.org/projects/DBZ/issues/DBZ-123[DBZ-123]
* MySQL connector supports failing over based on subset of GTIDs. https://issues.jboss.org/projects/DBZ/issues/DBZ-129[DBZ-129]
* MySQL connector processes GTIDs with line feeds and carriage returns. https://issues.jboss.org/projects/DBZ/issues/DBZ-135[DBZ-135]
* MySQL connector has improved output of GTIDs and status when reading the binary log. https://issues.jboss.org/projects/DBZ/issues/DBZ-130[DBZ-130], https://issues.jboss.org/projects/DBZ/issues/DBZ-131[DBZ-131]
* MySQL connector properly handles multi-character `ENUM` and `SET` values. https://issues.jboss.org/projects/DBZ/issues/DBZ-132[DBZ-132]



[[release-0-3-2]]
== *Release 0.3.2* _(September 26, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12331401[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.2 from 0.3.1, 0.3.0, 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.2 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.2 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release includes no breaking changes since the link:release-0-3-1[0.3.1] release.

=== New Features

This release includes no new features since the link:release-0-3-1[0.3.1] release.

=== Fixes

This release includes the following fixes to the link:release-0-3-1[0.3.1] release:

* MySQL connector now handles zero-value dates. https://issues.jboss.org/projects/DBZ/issues/DBZ-114[DBZ-114]
* MySQL connector no longer prints out password-related configuration properties, though https://issues.apache.org/jira/browse/KAFKA-4171[KAFKA-4171] for a similar issue with Kafka Connect. https://issues.jboss.org/projects/DBZ/issues/DBZ-122[DBZ-122]
* MySQL connector no longer causes "Error registering AppInfo mbean" warning in Kafka Connect. https://issues.jboss.org/projects/DBZ/issues/DBZ-124[DBZ-124]
* MySQL connector periodically outputs status when reading binlog. https://issues.jboss.org/projects/DBZ/issues/DBZ-116[DBZ-116]
* MongoDB connector periodically outputs status when reading binlog. https://issues.jboss.org/projects/DBZ/issues/DBZ-117[DBZ-117]
* MySQL connector correctly uses long for the `server.id` configuration property. https://issues.jboss.org/projects/DBZ/issues/DBZ-118[DBZ-118]
* MySQL connector fails or warns when MySQL is not using row-level logging. https://issues.jboss.org/projects/DBZ/issues/DBZ-128[DBZ-128]


[[release-0-3-1]]
== *Release 0.3.1* _(August 30, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12331359[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.1 from 0.3.0, 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.1 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.1 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release includes no breaking changes compared to the link:release-0-3-0[0.3.0] release.

=== New Features

* Added support for secure (encrypted) connections to MySQL. https://issues.jboss.org/projects/DBZ/issues/DBZ-99[DBZ-99]

=== Fixes

This release includes the following fixes to the link:release-0-3-0[0.3.0] release:

* MySQL connector now properly decodes string values from the binlog based upon the column's character set encoding as read by the DDL statement. Upon upgrade and restart, the connector will re-read the recorded database history and now associate the columns with their the character sets, and any newly processed events will use properly encoded strings values. As expected, previously generated events are never altered. Force a snapshot to regenerate events for the servers. https://issues.jboss.org/projects/DBZ/issues/DBZ-102[DBZ-102]
* Corrected how the MySQL connector parses some DDL statements. https://issues.jboss.org/projects/DBZ/issues/DBZ-106[DBZ-106]
* Corrected the MySQL connector to handle MySQL server GTID sets with newline characters. https://issues.jboss.org/projects/DBZ/issues/DBZ-107[DBZ-107], https://issues.jboss.org/projects/DBZ/issues/DBZ-111[DBZ-111]
* Corrected the MySQL connector's startup logic properly compare the MySQL SSL-related system properties to prevent overwriting them. The connector no longer fails when the system properties are the same, which can happen upon restart or starting a second MySQL connector with the same keystore. https://issues.jboss.org/projects/DBZ/issues/DBZ-112[DBZ-112]
* Removed unused code and test case. https://issues.jboss.org/projects/DBZ/issues/DBZ-108[DBZ-108]
* Ensure that the MySQL error code and SQLSTATE are included in exceptions reported by the connector. https://issues.jboss.org/projects/DBZ/issues/DBZ-109[DBZ-109]


[[release-0-3-0]]
== *Release 0.3.0* _(August 16, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12329661[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.10.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.9.0.x due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details, and Kafka documentation for compatibility with other versions of Kafka brokers.

=== Upgrading

Before upgrading the MySQL connector, be sure to check the backward-incompatible changes that have been made since the release you were using.

When you decide to upgrade the MySQL connector to 0.3.0 from 0.2.4, 0.2.3, 0.2.2, or 0.2.1, gracefully stop the running connector, remove the old plugin files, install the 0.3.0 plugin files, and restart the connector using the same configuration. Upon restart, the 0.3.0 MySQL connectors will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Breaking changes

This release includes one potentially breaking changes from the link:release-0-2-4[0.2.4] release:

* By default the MySQL connector now represents temporal values with millisecond, microsecond, or nanosecond precision based upon the precision of the source database columns. This changes the schema name of these fields to Debezium-specific constants, and the meaning/interpretation of the literal values now depends on this schema name. To enable previous behavior that always used millisecond precision using only Kafka Connect logical types, set `time.precision.mode` connector property to `connect`. https://issues.jboss.org/projects/DBZ/issues/DBZ-91[DBZ-91]

=== New Features

* Added the link:/docs/connectors/mongodb[MongoDB connector], which can capture and record the changes within a MongoDB replica set or MongoDB sharded cluster. In the latter case, the connector even automatically handles the addition or removal of shards. https://issues.jboss.org/projects/DBZ/issues/DBZ-2[DBZ-2]

=== Fixes

This release includes all of the fixes from the link:release-0-2-4[0.2.4] release, and also includes the following fixes:

* Corrected how the MySQL connector handles `TINYINT` columns. https://issues.jboss.org/projects/DBZ/issues/DBZ-84[DBZ-84]
* MySQL snapshots records DDL statements as separate events on the schema change topic. https://issues.jboss.org/browse/DBZ-97[DBZ-97]
* MySQL connector tolerates binlog filename missing from ROTATE events in certain situations. https://issues.jboss.org/browse/DBZ-95[DBZ-95]
* The Kafka Connect schema names used in the MySQL connector's change events are now always Avro-compatible schema names. Now, using the Avro converter with a `database.server.name` value, database names, or table names that contain Avro-incompatible characters produce log warnings but no longer result in errors during serialization and Avro schema generation. Whenever possible, use a `database.server.name` value that contains alphanumeric and underscore characters. https://issues.jboss.org/projects/DBZ/issues/DBZ-86[DBZ-86]



[[release-0-2-4]]
== *Release 0.2.4* _(August 16, 2016)_

August 16, 2016 - https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12331221[Detailed release notes]

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12331221[complete list of issues].

=== Upgrading

There are no backward-incompatible changes when upgrading to 0.2.4 from 0.2.3 or 0.2.2. Gracefully stop the running 0.2.3 connector, remove the 0.2.3 plugin files, install the 0.2.4 plugin files, and restart the connector using the same configuration. Upon restart, the 0.2.4 connector will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.


=== Kafka compatibility

This release requires Kafka Connect 0.9.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.10.0 due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details.


=== Fixes

This release includes all of the fixes from the link:release-0-2-3[0.2.3] release plus the following fixes:

* Stream result set rows when taking snapshot of MySQL databases to prevent out of memory problems with very large databases. https://issues.jboss.org/browse/DBZ-94[DBZ-94]
* Add more verbose logging statements to the MySQL connector to show progress and activity during snapshots. https://issues.jboss.org/browse/DBZ-92[DBZ-92]
* Corrected potential error during graceful MySQL connector shutdown. https://issues.jboss.org/browse/DBZ-103[DBZ-103]



[[release-0-2-4]]
== *Release 0.2.4* _(August 16, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12331221[complete list of issues].

=== Upgrading

There are no backward-incompatible changes when upgrading to 0.2.4 from 0.2.3 or 0.2.2. Gracefully stop the running 0.2.3 connector, remove the 0.2.3 plugin files, install the 0.2.4 plugin files, and restart the connector using the same configuration. Upon restart, the 0.2.4 connector will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.


=== Kafka compatibility

This release requires Kafka Connect 0.9.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.10.0 due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details.

=== Fixes

This release includes all of the fixes from the link:release-0-2-3[0.2.3] release plus the following fixes:

* Stream result set rows when taking snapshot of MySQL databases to prevent out of memory problems with very large databases. https://issues.jboss.org/browse/DBZ-94[DBZ-94]
* Add more verbose logging statements to the MySQL connector to show progress and activity during snapshots. https://issues.jboss.org/browse/DBZ-92[DBZ-92]
* Corrected potential error during graceful MySQL connector shutdown. https://issues.jboss.org/browse/DBZ-103[DBZ-103]


[[release-0-2-3]]
== *Release 0.2.3* _(July 26, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12330932[complete list of issues].

=== Kafka compatibility

This release requires Kafka Connect 0.9.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.10.0 due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details.

=== Upgrading

There are no backward-incompatible changes when upgrading to 0.2.3 from 0.2.2. Gracefully stop the running 0.2.2 connector, remove the 0.2.2 plugin files, install the 0.2.3 plugin files, and restart the connector using the same configuration. Upon restart, the 0.2.3 connector will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.


=== Fixes

This release includes all of the fixes from the link:release-0-2-2[0.2.2] release plus the following fixes:

* Corrected parsing errors when MySQL DDL statements are generated by Liquibase. https://issues.jboss.org/projects/DBZ/issues/DBZ-83[DBZ-83]
* Corrected support of MySQL `TINYINT` and `SMALLINT` types. https://issues.jboss.org/projects/DBZ/issues/DBZ-84[DBZ-84], https://issues.jboss.org/projects/DBZ/issues/DBZ-87[DBZ-87]
* Corrected support of MySQL temporal types, including `DATE`, `TIME`, and `TIMESTAMP`. https://issues.jboss.org/projects/DBZ/issues/DBZ-85[DBZ-85]
* Corrected call to MySQL SHOW MASTER STATUS so that it works on pre-5.7 versions of MySQL. https://issues.jboss.org/projects/DBZ/issues/DBZ-82[DBZ-82]

[[release-0-2-2]]
== *Release 0.2.2* _(June 22, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12330862[complete list of issues].

=== Kafka compatibility

This release can be used with Kafka Connect 0.9.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.10.0 due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. See https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80] for details.

=== Upgrading

Check the backward-incompatible changes when upgrading to 0.2.2 from 0.2.1 or 0.2.0.

When you decide to upgrade the MySQL connector to 0.2.2 from 0.2.1 or 0.2.0, gracefully stop the running 0.2.1 connector, remove the 0.2.1 plugin files, install the 0.2.2 plugin files, and restart the connector using the same configuration. Upon restart, the 0.2.2 connector will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.


=== Backwards-incompatible changes

* Removed several methods in the `GtidSet` class inside the MySQL connector. The class was introduced in 0.2. This change will only affect applications explicitly using the class (by reusing the MySQL connector JAR), and will not affect how the MySQL connector works. https://issues.jboss.org/projects/DBZ/issues/DBZ-79[DBZ-79]
* The `source` field within each MySQL change event now contains the binlog position of that event (rather than the next event). The structure of the change events (and semantics of other values remain) the same as with 0.2.1. Note that this change _may_ adversely clients that are explicitly comparing the position values across multiple events. https://issues.jboss.org/projects/DBZ/issues/DBZ-71[DBZ-71]

=== Fixes

This release includes all of the fixes from the link:release-0-2-1[0.2.1] release plus the following fixes:

* Correct how the MySQL connector records offsets with multi-row MySQL events so that, even if the connector experiences a non-graceful shutdown (i.e., crash) after committing the offset of _some_ of the rows from such an event, upon restart the connector will resume with the remaining rows in that multi-row event. Previously, the connector might incorrectly restart at the next event. https://issues.jboss.org/projects/DBZ/issues/DBZ-73[DBZ-73]
* Shutdown of the MySQL connector immediately after a snapshot completes (before another change event is reccorded) will now be properly marked as complete. https://issues.jboss.org/projects/DBZ/issues/DBZ-77[DBZ-77]


[[release-0-2-1]]
== *Release 0.2.1* _(June 10, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12330752[complete list of issues].

=== Kafka compatibility

This release can be used with Kafka Connect 0.9.0.1 (or a subsequent API-compatible release), and is known to be _incompatible_ with Kafka Connect 0.10.0 due to https://issues.apache.org/jira/browse/KAFKA-3006[binary incompatible changes in the Kafka 0.10.0 API]. https://issues.jboss.org/projects/DBZ/issues/DBZ-80[DBZ-80]

=== Upgrading

Check the backward-incompatible changes when upgrading to 0.2.1 from 0.2.0.

When you decide to upgrade the MySQL connector to 0.2.1 from 0.2.0, gracefully stop the running 0.2.0 connector, remove the 0.2.0 plugin files, install the 0.2.1 plugin files, and restart the connector using the same configuration. Upon restart, the 0.2.1 connector will continue where the previous connector left off. As one might expect, all change events previously written to Kafka by the old connector will not be modified.

=== Backwards-incompatible changes

* Corrected the names of the Avro-compliant Kafka Connect schemas generated by the MySQL connector for the `before` and `after` fields in its data change events. Consumers that require knowledge (by name) of the particular schemas used in 0.2 events may have trouble consuming events produced by the 0.2.1 (or later) connector. https://issues.jboss.org/projects/DBZ/issues/DBZ-72[DBZ-72]

=== Fixes

This release includes all of the fixes from the link:release-0-2-0[0.2.0] release plus the following fixes:

* The MySQL connector's plugin archive now contains the MySQL JDBC driver JAR file required by the connector. https://issues.jboss.org/projects/DBZ/issues/DBZ-71[DBZ-71]



[[release-0-2-0]]
== *Release 0.2.0* _(June 8, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12329465[complete list of issues] addressed in this release.

[WARNING]
====
The 0.2.0 release contained a significant issue, and link:#release-0-2-1[0.2.1] was quickly released to fix the problem. We recommend using a newer release than 0.2.
====

=== Backwards-incompatible changes

* Completely redesigned the structure of event messages produced by MySQL connector and stored in Kafka topics. Events now contain an _envelope_ structure with information about the source event, the kind of operation (create/insert, update, delete, read), the time that Debezium processed the event, and the state of the row before and/or after the event. The messages written to each topic have a distinct Avro-compliant Kafka Connect schema that reflects the structure of the source table, which may vary over time independently from the schemas of all other topics. See the http://debezium.io/docs/connectors/mysql#events[documentation] for details. This envelope structure will likely be used by future connectors. https://issues.jboss.org/projects/DBZ/issues/DBZ-50[DBZ-50], https://issues.jboss.org/projects/DBZ/issues/DBZ-52[DBZ-52], https://issues.jboss.org/projects/DBZ/issues/DBZ-45[DBZ-45], https://issues.jboss.org/projects/DBZ/issues/DBZ-60[DBZ-60]
* MySQL connector handles deletion of a row by recording a delete event message whose value contains the state of the removed row (and other metadata), followed by a _tombstone event_ message with a null value to signal *Kafka's log compaction* that all messages with the same key can be garbage collected. See the http://debezium.io/docs/connectors/mysql#events[documentation] for details. https://issues.jboss.org/projects/DBZ/issues/DBZ-44[DBZ-44]
* Changed the format of events that the MySQL connector writes to its schema change topic, through which consumers can access events with the DDL statements applied to the database(s). The format change makes it possible for consumers to correlate these events with the data change events. https://issues.jboss.org/projects/DBZ/issues/DBZ-43[DBZ-43], https://issues.jboss.org/projects/DBZ/issues/DBZ-55[DBZ-55]

=== New features

* MySQL connector supports *high availability* MySQL cluster topologies. See the http://debezium.io/docs/connectors/mysql[documentation] for details. https://issues.jboss.org/projects/DBZ/issues/DBZ-37[DBZ-37]
* MySQL connector now by default starts by performing a *consistent snapshot* of the schema and contents of the upstream MySQL databases in its current state. See the http://debezium.io/docs/connectors/mysql#snapshots[documentation] for details about how this works and how it impacts other database clients. https://issues.jboss.org/projects/DBZ/issues/DBZ-31[DBZ-31]
* MySQL connector can be configured to *exclude*, *truncate*, or *mask* specific columns in events. https://issues.jboss.org/projects/DBZ/issues/DBZ-29[DBZ-29]
* MySQL connector events can be serialized using the http://docs.confluent.io/3.0.0/avro.html[Confluent Avro converter] or the JSON converter. Previously, only the JSON converter could be used. https://issues.jboss.org/projects/DBZ/issues/DBZ-29[DBZ-29], https://issues.jboss.org/projects/DBZ/issues/DBZ-63[DBZ-63], https://issues.jboss.org/projects/DBZ/issues/DBZ-64[DBZ-64]

=== Changes

* DDL parsing framework identifies table affected by statements via a new listener callback. https://issues.jboss.org/projects/DBZ/issues/DBZ-38[DBZ-38]
* The `database.binlog` configuration property was required in version 0.1 of the MySQL connector, but now it is no longer used because of the new snapshot feature. If provided, it will be quietly ignored. https://issues.jboss.org/projects/DBZ/issues/DBZ-31[DBZ-31]

=== Bug fixes

* MySQL connector now properly parses `COMMIT` statements, the `REFERENCES` clauses of `CREATE TABLE` statements, and statements with `CHARSET` shorthand of `CHARACTER SET`. https://issues.jboss.org/projects/DBZ/issues/DBZ-48[DBZ-48], https://issues.jboss.org/projects/DBZ/issues/DBZ-49[DBZ-49], https://issues.jboss.org/projects/DBZ/issues/DBZ-57[DBZ-57]
* MySQL connector properly handles binary values that are hexadecimal strings https://issues.jboss.org/projects/DBZ/issues/DBZ-61[DBZ-61]



[[release-0-1-0]]
== *Release 0.1.0* _(March 17, 2016)_

See the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317320&version=12329464[complete list of issues] addressed in this release.

=== Kafka compatibility

This release can be used with Kafka Connect 0.9.0.1 (or a subsequent API-compatible release).

=== Added

* MySQL connector for ingesting change events from MySQL databases. https://issues.jboss.org/projects/DBZ/issues/DBZ-1[DBZ-1]
* Kafka Connect plugin archive for MySQL connector. https://issues.jboss.org/projects/DBZ/issues/DBZ-17[DBZ-17]
* Simple DDL parsing framework that can be extended and used by various connectors. https://issues.jboss.org/projects/DBZ/issues/DBZ-1[DBZ-1]
* Framework for embedding a single Kafka Connect connector inside an application. https://issues.jboss.org/projects/DBZ/issues/DBZ-8[DBZ-8]
