name: Receive PR

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Checks that all commits contain sign-offs
  check-signed-commits:
    name: Check signed commits
    runs-on: ubuntu-latest
    steps:
      - uses: debezium/dbz/.github/actions/check-dco@main

  build-preview:
    needs: [ check-signed-commits ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Update snapshot links
        run: ./_scripts/create-snapshot-links.sh

      - name: Build
        run: docker run --privileged -i --rm -p 4000:4000 -e LC_ALL=C.UTF-8 -e LANG=C.UTF-8 -v $(pwd):/site debezium/website-builder bash -c "rake clean build[production]"

      - name: upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: _site/
          retention-days: 5

      - name: Save PR number
        if: ${{ always() }}
        run: |
          PR_NUM="${{ github.event.number }}"
          if ! [[ "$PR_NUM" =~ ^[0-9]+$ ]]; then
            echo "Error: Invalid PR number"
            exit 1
          fi
          echo "$PR_NUM" > ./pr-id.txt

      - name: Upload PR number
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: ./pr-id.txt
