name: Surge.sh Preview

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: docker run --privileged -i --rm -p 4000:4000 -e LC_ALL=C.UTF-8 -e LANG=C.UTF-8 -v $(pwd):/site debezium/website-builder bash -c "rake clean build[staging]"

    - name: Preview
      uses: afc163/surge-preview@v1
      id: preview_step
      with:
        surge_token: ${{ secrets.SURGE_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dist: _site/
        failOnError: 'true'
        build: |
          echo Deploying to surge.sh
    - name: Get the preview_url
      run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"