name: Teardown abandoned website preview Workflow 

on: 
  workflow_dispatch:
    inputs:
      PRNumber:
        description: 'PR number to tear down; omit to list all existing preview environments'

jobs:
  success:
    runs-on: ubuntu-20.04
    steps:
      - name: Teardown surge.sh preview
        id: teardown
        if: github.event.inputs.PRNumber != ''
        run: |
          npx surge teardown https://debezium-debezium-github-io-preview-pr-${{ github.event.inputs.PRNumber }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
          npx surge list --token ${{ secrets.SURGE_TOKEN }}
        continue-on-error: true
      - name: Show preview log
        if: steps.teardown.outcome == 'failure' || github.event.inputs.PRNumber == ''
        run: npx surge list --token ${{ secrets.SURGE_TOKEN }}