name: Teardown abandoned website preview Workflow 

on: 
  workflow_dispatch:
    inputs:
      PRNumber:
        description: 'PR number to teardown'     
        required: true

jobs:
  preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Teardown surge preview
        run: |
          npx surge teardown https://debezium-debezium-github-io-preview-pr-${{ github.event.inputs.PRNumber }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}