name: Surge.sh Preview Teardown

on:
  pull_request:
    # when using teardown: 'true', add default event types + closed event type
    types: [closed]

jobs:
  preview:
    runs-on: ubuntu-20.04
    steps:
      - uses: afc163/surge-preview@v1
        id: preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          teardown: 'true'
          failOnError: 'false'
          build: |
            echo Deleting from surge.sh